### ISSUE TITLE
wan2.2 animate

### ISSUE THREAD

**Issue by igor-iki** [comfyanonymous/ComfyUI#10028]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

i want run dwpose on gpu instead cpu

### Actual Behavior

error
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device`

### Steps to Reproduce

error apears after pip install onnxruntime-gpu

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 233
- **Node Type:** DWPreprocessor
- **Exception Type:** onnxruntime.capi.onnxruntime_pybind11_state.Fail
- **Exception Message:** [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

## Stack Trace

  File "C:\comfy\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "C:\comfy\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 91, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution, xinsr_stick_scaling=scale_stick_for_xinsr_cn)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in func
    pose_img, openpose_dict = model(image, **kwargs)
                              ~~~~~^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 266, in __call__
    poses = self.detect_poses(input_image)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 255, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 93, in __call__
    det_result = inference_onnx_yolox(self.det, oriImg, detect_classes=[0], dtype=np.float32)

  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\dw_onnx\cv_ox_det.py", line 104, in inference_detector
    output = session.run(None, {input_name: input})

  File "c:\comfy\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 275, in run
    return self._sess.run(output_names, input_feed, run_options)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.60
- **Arguments:** main.py --gpu
- **OS:** nt
- **Python Version:** 3.13.7 (main, Sep 18 2025, 19:43:45) [MSC v.1944 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0+cu129
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 5090 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25650855936
  - **VRAM Free:** 24151851008
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs

2025-09-26T07:01:12.819087 - [START] Security scan2025-09-26T07:01:12.819108 - 
2025-09-26T07:01:13.588117 - [DONE] Security scan2025-09-26T07:01:13.588128 - 
2025-09-26T07:01:13.747649 - ## ComfyUI-Manager: installing dependencies done.2025-09-26T07:01:13.747852 - 
2025-09-26T07:01:13.747967 - ** ComfyUI startup time:2025-09-26T07:01:13.748008 -  2025-09-26T07:01:13.748049 - 2025-09-26 07:01:13.7472025-09-26T07:01:13.748079 - 
2025-09-26T07:01:13.748115 - ** Platform:2025-09-26T07:01:13.748145 -  2025-09-26T07:01:13.748210 - Windows2025-09-26T07:01:13.748303 - 
2025-09-26T07:01:13.748360 - ** Python version:2025-09-26T07:01:13.748408 -  2025-09-26T07:01:13.748455 - 3.13.7 (main, Sep 18 2025, 19:43:45) [MSC v.1944 64 bit (AMD64)]2025-09-26T07:01:13.748487 - 
2025-09-26T07:01:13.748518 - ** Python executable:2025-09-26T07:01:13.748548 -  2025-09-26T07:01:13.748577 - c:\comfy\.venv\Scripts\python.exe2025-09-26T07:01:13.748604 - 
2025-09-26T07:01:13.748633 - ** ComfyUI Path:2025-09-26T07:01:13.748661 -  2025-09-26T07:01:13.748689 - C:\comfy\ComfyUI2025-09-26T07:01:13.748717 - 
2025-09-26T07:01:13.748746 - ** ComfyUI Base Folder Path:2025-09-26T07:01:13.748773 -  2025-09-26T07:01:13.748800 - C:\comfy\ComfyUI2025-09-26T07:01:13.748828 - 
2025-09-26T07:01:13.748856 - ** User directory:2025-09-26T07:01:13.748883 -  2025-09-26T07:01:13.748911 - C:\comfy\ComfyUI\user2025-09-26T07:01:13.748938 - 
2025-09-26T07:01:13.748966 - ** ComfyUI-Manager config path:2025-09-26T07:01:13.748993 -  2025-09-26T07:01:13.749021 - C:\comfy\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-09-26T07:01:13.749048 - 
2025-09-26T07:01:13.749078 - ** Log path:2025-09-26T07:01:13.749116 -  2025-09-26T07:01:13.749257 - C:\comfy\ComfyUI\user\comfyui.log2025-09-26T07:01:13.749296 - 
2025-09-26T07:01:14.456408 - 
Prestartup times for custom nodes:
2025-09-26T07:01:14.456678 -    1.9 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2025-09-26T07:01:14.456771 - 
2025-09-26T07:01:15.550851 - Checkpoint files will always be loaded safely.
2025-09-26T07:01:15.656871 - Total VRAM 24463 MB, total RAM 64943 MB
2025-09-26T07:01:15.657138 - pytorch version: 2.10.0.dev20250924+cu130
2025-09-26T07:01:15.657642 - Set vram state to: NORMAL_VRAM
2025-09-26T07:01:15.658045 - Device: cuda:0 NVIDIA GeForce RTX 5090 Laptop GPU : cudaMallocAsync
2025-09-26T07:01:16.328821 - Using pytorch attention
2025-09-26T07:01:17.445767 - Python version: 3.13.7 (main, Sep 18 2025, 19:43:45) [MSC v.1944 64 bit (AMD64)]
2025-09-26T07:01:17.446059 - ComfyUI version: 0.3.60
2025-09-26T07:01:17.466881 - ComfyUI frontend version: 1.26.13
2025-09-26T07:01:17.468020 - [Prompt Server] web root: c:\comfy\.venv\Lib\site-packages\comfyui_frontend_package\static
2025-09-26T07:01:18.488194 - ComfyUI-GGUF: Allowing full torch compile
2025-09-26T07:01:18.520134 - ### Loading: ComfyUI-Manager (V3.37)
2025-09-26T07:01:18.520741 - [ComfyUI-Manager] network_mode: public
2025-09-26T07:01:18.793401 - ### ComfyUI Version: v0.3.60-5-gce4cb238 | Released on '2025-09-25'
2025-09-26T07:01:19.170236 - [36;20m[C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2025-09-26T07:01:19.170550 - [36;20m[C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2025-09-26T07:01:19.170746 - [36;20m[C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2025-09-26T07:01:19.242499 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-09-26T07:01:19.263958 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-09-26T07:01:19.300041 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-09-26T07:01:19.344397 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-09-26T07:01:19.424334 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-09-26T07:01:19.428320 - DWPose: Onnxruntime with acceleration providers detected2025-09-26T07:01:19.428437 - 
2025-09-26T07:01:19.434691 - 
Import times for custom nodes:
2025-09-26T07:01:19.435105 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\websocket_image_save.py
2025-09-26T07:01:19.435244 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2025-09-26T07:01:19.435311 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-GGUF
2025-09-26T07:01:19.435376 -    0.0 seconds: C:\comfy\ComfyUI\custom_nodes\comfyui-kjnodes
2025-09-26T07:01:19.435435 -    0.3 seconds: C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux
2025-09-26T07:01:19.435492 -    0.6 seconds: C:\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2025-09-26T07:01:19.435533 - 
2025-09-26T07:01:20.006308 - Context impl SQLiteImpl.
2025-09-26T07:01:20.006558 - Will assume non-transactional DDL.
2025-09-26T07:01:20.007402 - No target revision found.
2025-09-26T07:01:20.015579 - Starting server

2025-09-26T07:01:20.015969 - To see the GUI go to: http://127.0.0.1:8188
2025-09-26T07:01:24.189744 - FETCH ComfyRegistry Data: 5/982025-09-26T07:01:24.189867 - 
2025-09-26T07:01:24.247447 - got prompt
2025-09-26T07:01:26.206881 - Using pytorch attention in VAE
2025-09-26T07:01:26.207921 - Using pytorch attention in VAE
2025-09-26T07:01:26.359805 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-09-26T07:01:28.379927 - FETCH ComfyRegistry Data: 10/982025-09-26T07:01:28.380050 - 
2025-09-26T07:01:33.183183 - FETCH ComfyRegistry Data: 15/982025-09-26T07:01:33.183360 - 
2025-09-26T07:01:36.514022 - [{'startX': 70.47225047713542, 'startY': 828.8878984691643}]2025-09-26T07:01:36.514222 - 
2025-09-26T07:01:36.535651 - c:\comfy\.venv\Lib\site-packages\torch\backends\__init__.py:46: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:85.)
  self.setter(val)
2025-09-26T07:01:36.535878 - model_path: 2025-09-26T07:01:36.535983 -  2025-09-26T07:01:36.536113 - C:\comfy\ComfyUI\models\sam2\sam2_hiera_base_plus.safetensors2025-09-26T07:01:36.536217 - 
2025-09-26T07:01:36.536345 - Using model config: C:\comfy\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2_configs\sam2_hiera_b+.yaml2025-09-26T07:01:36.536432 - 
2025-09-26T07:01:37.284693 - Resizing to model input image size: 2025-09-26T07:01:37.284937 -  2025-09-26T07:01:37.285115 - 10242025-09-26T07:01:37.285235 - 
2025-09-26T07:01:37.356343 - FETCH ComfyRegistry Data: 20/982025-09-26T07:01:37.361040 - 
2025-09-26T07:01:37.662639 - combined labels: 2025-09-26T07:01:37.662944 -  2025-09-26T07:01:37.663571 - [1. 1. 1. 1.]2025-09-26T07:01:37.663758 - 
2025-09-26T07:01:37.663869 - combined labels shape: 2025-09-26T07:01:37.663987 -  2025-09-26T07:01:37.664097 - (4,)2025-09-26T07:01:37.664157 - 
2025-09-26T07:01:41.690041 - 
propagate in video:  14%|██████████████▊                                                                                              | 60/442 [00:03<00:21, 18.11it/s]2025-09-26T07:01:41.770976 - FETCH ComfyRegistry Data: 25/982025-09-26T07:01:41.771129 - 
2025-09-26T07:01:45.853957 - 
propagate in video:  30%|████████████████████████████████▋                                                                           | 134/442 [00:07<00:17, 17.84it/s]2025-09-26T07:01:45.948222 - FETCH ComfyRegistry Data: 30/982025-09-26T07:01:45.948377 - 
2025-09-26T07:01:49.881090 - 
propagate in video:  47%|██████████████████████████████████████████████████▎                                                         | 206/442 [00:11<00:12, 18.29it/s]2025-09-26T07:01:49.949703 - FETCH ComfyRegistry Data: 35/982025-09-26T07:01:49.949804 - 
2025-09-26T07:01:55.996975 - 
propagate in video:  72%|█████████████████████████████████████████████████████████████████████████████▋                              | 318/442 [00:17<00:06, 18.16it/s]2025-09-26T07:01:56.030460 - FETCH ComfyRegistry Data: 40/982025-09-26T07:01:56.030577 - 
2025-09-26T07:02:00.386359 - 
propagate in video:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████▏          | 398/442 [00:21<00:02, 18.86it/s]2025-09-26T07:02:00.434087 - FETCH ComfyRegistry Data: 45/982025-09-26T07:02:00.434212 - 
2025-09-26T07:02:02.778805 - 
propagate in video: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442/442 [00:24<00:00, 18.66it/s]2025-09-26T07:02:02.779110 - 
propagate in video: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442/442 [00:24<00:00, 18.13it/s]2025-09-26T07:02:02.779267 - 
2025-09-26T07:02:05.329476 - FETCH ComfyRegistry Data: 50/982025-09-26T07:02:05.329664 - 
2025-09-26T07:02:09.369790 - FETCH ComfyRegistry Data: 55/982025-09-26T07:02:09.370384 - 
2025-09-26T07:02:14.425870 - FETCH ComfyRegistry Data: 60/982025-09-26T07:02:14.425967 - 
2025-09-26T07:02:18.501958 - FETCH ComfyRegistry Data: 65/982025-09-26T07:02:18.502077 - 
2025-09-26T07:02:23.684503 - FETCH ComfyRegistry Data: 70/982025-09-26T07:02:23.684633 - 
2025-09-26T07:02:28.030673 - FETCH ComfyRegistry Data: 75/982025-09-26T07:02:28.030783 - 
2025-09-26T07:02:32.199516 - FETCH ComfyRegistry Data: 80/982025-09-26T07:02:32.199801 - 
2025-09-26T07:02:36.426980 - FETCH ComfyRegistry Data: 85/982025-09-26T07:02:36.427239 - 
2025-09-26T07:02:40.675295 - FETCH ComfyRegistry Data: 90/982025-09-26T07:02:40.675620 - 
2025-09-26T07:02:44.871459 - FETCH ComfyRegistry Data: 95/982025-09-26T07:02:44.872162 - 
2025-09-26T07:02:47.844766 - FETCH ComfyRegistry Data [DONE]2025-09-26T07:02:47.845517 - 
2025-09-26T07:02:48.000425 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-09-26T07:02:48.026021 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-09-26T07:02:48.026243 - 2025-09-26T07:02:48.144471 -  [DONE]2025-09-26T07:02:48.144715 - 
2025-09-26T07:02:48.220823 - [ComfyUI-Manager] All startup tasks have been completed.
2025-09-26T07:02:57.903082 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v\DWPose\yolox_l.onnx2025-09-26T07:02:57.903302 - 
2025-09-26T07:02:57.903779 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16\DWPose-TorchScript-BatchSize5\dw-ll_ucoco_384_bs5.torchscript.pt2025-09-26T07:02:57.903855 - 
2025-09-26T07:02:57.903905 - 
DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation2025-09-26T07:02:57.903950 - 
2025-09-26T07:02:57.904014 - DWPose: Caching ONNXRuntime session yolox_l.onnx...2025-09-26T07:02:57.904044 - 
2025-09-26T07:03:01.888697 - DWPose: Caching TorchScript module dw-ll_ucoco_384_bs5.torchscript.pt on ...2025-09-26T07:03:01.889139 - 
2025-09-26T07:03:02.174807 - !!! Exception during processing !!! [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
2025-09-26T07:03:02.179358 - Traceback (most recent call last):
  File "C:\comfy\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\comfy\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 91, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution, xinsr_stick_scaling=scale_stick_for_xinsr_cn)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in func
    pose_img, openpose_dict = model(image, **kwargs)
                              ~~~~~^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 266, in __call__
    poses = self.detect_poses(input_image)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 255, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 93, in __call__
    det_result = inference_onnx_yolox(self.det, oriImg, detect_classes=[0], dtype=np.float32)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\dw_onnx\cv_ox_det.py", line 104, in inference_detector
    output = session.run(None, {input_name: input})
  File "c:\comfy\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 275, in run
    return self._sess.run(output_names, input_feed, run_options)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

2025-09-26T07:03:02.182351 - Prompt executed in 97.93 seconds
2025-09-26T07:03:57.489130 - got prompt
2025-09-26T07:03:57.507787 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v\DWPose\yolox_l.onnx2025-09-26T07:03:57.507894 - 
2025-09-26T07:03:57.508113 - model_path is C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16\DWPose-TorchScript-BatchSize5\dw-ll_ucoco_384_bs5.torchscript.pt2025-09-26T07:03:57.508537 - 
2025-09-26T07:03:57.508755 - 
DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation2025-09-26T07:03:57.509589 - 
2025-09-26T07:03:57.531348 - !!! Exception during processing !!! [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
2025-09-26T07:03:57.532794 - Traceback (most recent call last):
  File "C:\comfy\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\comfy\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 91, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution, xinsr_stick_scaling=scale_stick_for_xinsr_cn)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in func
    pose_img, openpose_dict = model(image, **kwargs)
                              ~~~~~^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 266, in __call__
    poses = self.detect_poses(input_image)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 255, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 93, in __call__
    det_result = inference_onnx_yolox(self.det, oriImg, detect_classes=[0], dtype=np.float32)
  File "C:\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\dw_onnx\cv_ox_det.py", line 104, in inference_detector
    output = session.run(None, {input_name: input})
  File "c:\comfy\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 275, in run
    return self._sess.run(output_names, input_feed, run_options)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_34' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

2025-09-26T07:03:57.536189 - Prompt executed in 0.04 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

Workflow too large. Please manually upload the workflow from local file system.


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

### Other

without  onnxruntime-gpu dwpose works withuot problem on cpu

**Comment by ShadoW-Shinigami** [comment]
Facing the same issue with onnxruntime-gpu, but probably not a comfy bug. Feel like it is more of a compatibility with 50 series gpu bug.

**Comment by igor-iki** [comment]
> Facing the same issue with onnxruntime-gpu, but probably not a comfy bug. Feel like it is more of a compatibility with 50 series gpu bug.

so what to do?

**Comment by spotya699-dev** [comment]
Same issue here with freshly installed and formatted pc. How to fix it?

**Comment by igor-iki** [comment]
onnx from pip doesnt have sm120 kernel. u need to git clone and build own whl and install it. ive done it and it works!

**Comment by babaprayogsadhan-AIC** [comment]
@igor-iki Can you explain on how to do it? I cloned the onnx from github, but then everything after that seems to go over my head. Tried using Perplexity to help me navigate but I can't seem to find any files that it specifies. Thanks

**Comment by igor-iki** [comment]
> [@igor-iki](https://github.com/igor-iki) Can you explain on how to do it? I cloned the onnx from github, but then everything after that seems to go over my head. Tried using Perplexity to help me navigate but I can't seem to find any files that it specifies. Thanks

https://github.com/microsoft/onnxruntime/issues/26181#issuecomment-3342020521
and install visual studio 2022 before cuda.

**Comment by AndreaGiulianoK** [comment]
I noticed that using version 1.22 works without problems on RTX5090.
`pip install onnxruntime-gpu==1.22`
