### ISSUE TITLE
face detailer- 'DifferentialDiffusion' object has no attribute 'apply'

### ISSUE THREAD

**Issue by GenshiStudio** [comfyanonymous/ComfyUI#10242]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

I updated to ComfyUI version 2.62 but I get this error with the Face Detailer Custom Node.

'DifferentialDiffusion' object has no attribute 'apply'

### Actual Behavior

'DifferentialDiffusion' object has no attribute 'apply'

### Steps to Reproduce

to run my workflow

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 67
- **Node Type:** FaceDetailer
- **Exception Type:** AttributeError
- **Exception Message:** 'DifferentialDiffusion' object has no attribute 'apply'

## Stack Trace

  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 876, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 830, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,

  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 304, in do_detail
    model = nodes_differential_diffusion.DifferentialDiffusion().apply(model)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.63
- **Arguments:** C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\main.py --user-directory C:\Users\genshistudio\Documents\ComfyUI\user --input-directory C:\Users\genshistudio\Documents\ComfyUI\input --output-directory C:\Users\genshistudio\Documents\ComfyUI\output --front-end-root C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\web_custom_versions\desktop_app --base-directory C:\Users\genshistudio\Documents\ComfyUI --extra-model-paths-config C:\Users\genshistudio\AppData\Roaming\ComfyUI\extra_models_config.yaml --log-stdout --listen 127.0.0.1 --port 8002
- **OS:** nt
- **Python Version:** 3.12.11 (main, Aug 18 2025, 19:17:54) [MSC v.1944 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0+cu129
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2080 Ti : native
  - **Type:** cuda
  - **VRAM Total:** 11810832384
  - **VRAM Free:** 10597957632
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs

2025-10-06T21:47:07.102669 - Adding extra search path vae J:\ComfyModels\vae
2025-10-06T21:47:07.102669 - Adding extra search path clip J:\ComfyModels\clip
2025-10-06T21:47:07.102669 - Adding extra search path clip_vision J:\ComfyModels\clip_vision
2025-10-06T21:47:07.102669 - Adding extra search path diffusion_models J:\ComfyModels\diffusion_models
2025-10-06T21:47:07.102669 - Adding extra search path embeddings J:\ComfyModels\embeddings
2025-10-06T21:47:07.102669 - Adding extra search path insightface J:\ComfyModels\insightface
2025-10-06T21:47:07.102669 - Adding extra search path rembg J:\ComfyModels\rembg
2025-10-06T21:47:07.102669 - Adding extra search path sam2 J:\ComfyModels\sam2
2025-10-06T21:47:07.102669 - Adding extra search path sams J:\ComfyModels\sams
2025-10-06T21:47:07.102669 - Adding extra search path ultralytics J:\ComfyModels\Ultralyics
2025-10-06T21:47:07.102669 - Adding extra search path upscale_models J:\ComfyModels\upscale_models
2025-10-06T21:47:07.102669 - Adding extra search path vibevoice J:\ComfyModels\vibevoice
2025-10-06T21:47:07.102669 - Adding extra search path text_encoders J:\ComfyModels\text_encoders
2025-10-06T21:47:07.102669 - Setting output directory to: C:\Users\genshistudio\Documents\ComfyUI\output
2025-10-06T21:47:07.102669 - Setting input directory to: C:\Users\genshistudio\Documents\ComfyUI\input
2025-10-06T21:47:07.102669 - Setting user directory to: C:\Users\genshistudio\Documents\ComfyUI\user
2025-10-06T21:47:08.178882 - [START] Security scan2025-10-06T21:47:08.178882 - 
2025-10-06T21:47:09.807150 - [DONE] Security scan2025-10-06T21:47:09.807150 - 
2025-10-06T21:47:09.980478 - ## ComfyUI-Manager: installing dependencies done.2025-10-06T21:47:09.980478 - 
2025-10-06T21:47:09.980478 - ** ComfyUI startup time:2025-10-06T21:47:09.980478 -  2025-10-06T21:47:09.981478 - 2025-10-06 21:47:09.9802025-10-06T21:47:09.981478 - 
2025-10-06T21:47:09.981478 - ** Platform:2025-10-06T21:47:09.981478 -  2025-10-06T21:47:09.981478 - Windows2025-10-06T21:47:09.981478 - 
2025-10-06T21:47:09.981478 - ** Python version:2025-10-06T21:47:09.981478 -  2025-10-06T21:47:09.981478 - 3.12.11 (main, Aug 18 2025, 19:17:54) [MSC v.1944 64 bit (AMD64)]2025-10-06T21:47:09.981478 - 
2025-10-06T21:47:09.981478 - ** Python executable:2025-10-06T21:47:09.981478 -  2025-10-06T21:47:09.981478 - C:\Users\genshistudio\Documents\ComfyUI\.venv\Scripts\python.exe2025-10-06T21:47:09.981478 - 
2025-10-06T21:47:09.981478 - ** ComfyUI Path:2025-10-06T21:47:09.981478 -  2025-10-06T21:47:09.981478 - C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI2025-10-06T21:47:09.981478 - 
2025-10-06T21:47:09.981478 - ** ComfyUI Base Folder Path:2025-10-06T21:47:09.981478 -  2025-10-06T21:47:09.982478 - C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI2025-10-06T21:47:09.982478 - 
2025-10-06T21:47:09.982478 - ** User directory:2025-10-06T21:47:09.982478 -  2025-10-06T21:47:09.982478 - C:\Users\genshistudio\Documents\ComfyUI\user2025-10-06T21:47:09.982478 - 
2025-10-06T21:47:09.982478 - ** ComfyUI-Manager config path:2025-10-06T21:47:09.982478 -  2025-10-06T21:47:09.982478 - C:\Users\genshistudio\Documents\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-10-06T21:47:09.982478 - 
2025-10-06T21:47:09.982478 - ** Log path:2025-10-06T21:47:09.982478 -  2025-10-06T21:47:09.982478 - C:\Users\genshistudio\Documents\ComfyUI\user\comfyui.log2025-10-06T21:47:09.982478 - 
2025-10-06T21:47:12.239926 - [ComfyUI-Manager] Skipped fixing the 'comfyui-frontend-package' dependency because the ComfyUI is outdated.
2025-10-06T21:47:12.240926 - 
Prestartup times for custom nodes:
2025-10-06T21:47:12.240926 -    5.1 seconds: C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-10-06T21:47:12.240926 - 
2025-10-06T21:47:14.680040 - Checkpoint files will always be loaded safely.
2025-10-06T21:47:14.748874 - C:\Users\genshistudio\Documents\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py:283: UserWarning: 
    Found GPU1 NVIDIA GeForce GTX 980 which is of cuda capability 5.2.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (7.0) - (12.0)
    
  warnings.warn(
2025-10-06T21:47:14.749875 - C:\Users\genshistudio\Documents\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py:304: UserWarning: 
    Please install PyTorch with a following CUDA
    configurations:  12.6 following instructions at
    https://pytorch.org/get-started/locally/
    
  warnings.warn(matched_cuda_warn.format(matched_arches))
2025-10-06T21:47:14.750875 - C:\Users\genshistudio\Documents\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py:326: UserWarning: 
NVIDIA GeForce GTX 980 with CUDA capability sm_52 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.
If you want to use the NVIDIA GeForce GTX 980 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
2025-10-06T21:47:14.894735 - Total VRAM 11264 MB, total RAM 98183 MB
2025-10-06T21:47:14.894735 - pytorch version: 2.8.0+cu129
2025-10-06T21:47:14.896735 - Set vram state to: NORMAL_VRAM
2025-10-06T21:47:14.896735 - Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : native
2025-10-06T21:47:16.739183 - Using pytorch attention
2025-10-06T21:47:19.876794 - Python version: 3.12.11 (main, Aug 18 2025, 19:17:54) [MSC v.1944 64 bit (AMD64)]
2025-10-06T21:47:19.876794 - ComfyUI version: 0.3.63
2025-10-06T21:47:19.922099 - [Prompt Server] web root: C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\web_custom_versions\desktop_app
2025-10-06T21:47:23.835838 - [36;20m[C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfy-mtb] | INFO -> loaded [96m106[0m nodes successfuly[0m
2025-10-06T21:47:23.836836 - [36;20m[C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfy-mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8002/mtb if you want more information.[0m
2025-10-06T21:47:23.856948 - Failed to find comfy root automatically, please copy the folder C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyLiterals\web manually in the web/extensions folder of ComfyUI2025-10-06T21:47:23.856948 - 
2025-10-06T21:47:30.682674 - [34m[ComfyUI-Easy-Use] server: [0mv1.3.3 [92mLoaded[0m2025-10-06T21:47:30.682674 - 
2025-10-06T21:47:30.682674 - [34m[ComfyUI-Easy-Use] web root: [0mC:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-easy-use\web_version/v2 [92mLoaded[0m2025-10-06T21:47:30.682674 - 
2025-10-06T21:47:30.726262 - ComfyUI-GGUF: Allowing full torch compile
2025-10-06T21:47:30.733262 - ### Loading: ComfyUI-Impact-Pack (V8.23)
2025-10-06T21:47:30.994556 - [Impact Pack] Wildcards loading done.
2025-10-06T21:47:31.002557 - ### Loading: ComfyUI-Impact-Subpack (V1.3.5)
2025-10-06T21:47:31.005701 - [Impact Pack/Subpack] Using folder_paths to determine whitelist path: C:\Users\genshistudio\Documents\ComfyUI\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
2025-10-06T21:47:31.005701 - [Impact Pack/Subpack] Ensured whitelist directory exists: C:\Users\genshistudio\Documents\ComfyUI\user\default\ComfyUI-Impact-Subpack
2025-10-06T21:47:31.006699 - [Impact Pack/Subpack] Loaded 0 model(s) from whitelist: C:\Users\genshistudio\Documents\ComfyUI\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
2025-10-06T21:47:31.108489 - [Impact Subpack] ultralytics_bbox: C:\Users\genshistudio\Documents\ComfyUI\models\ultralytics\bbox
2025-10-06T21:47:31.108489 - [Impact Subpack] ultralytics_segm: C:\Users\genshistudio\Documents\ComfyUI\models\ultralytics\segm
2025-10-06T21:47:31.108489 - [Impact Subpack] ultralytics_bbox: C:\Users\genshistudio\Documents\ComfyUI\models\ultralytics\bbox
2025-10-06T21:47:31.108489 - [Impact Subpack] ultralytics_segm: C:\Users\genshistudio\Documents\ComfyUI\models\ultralytics\segm
2025-10-06T21:47:31.698560 - [MultiGPU Core Patching] Patching mm.soft_empty_cache for Comprehensive Memory Management (VRAM + CPU + Store Pruning)
2025-10-06T21:47:31.701561 - [MultiGPU Core Patching] Patching mm.get_torch_device and mm.text_encoder_device
2025-10-06T21:47:31.701561 - [MultiGPU DEBUG] Initial current_device: cuda:0
2025-10-06T21:47:31.702561 - [MultiGPU DEBUG] Initial current_text_encoder_device: cuda:0
2025-10-06T21:47:31.714707 - [MultiGPU] Initiating custom_node Registration. . .
2025-10-06T21:47:31.715812 - -----------------------------------------------
2025-10-06T21:47:31.716811 - custom_node                   Found     Nodes
2025-10-06T21:47:31.716811 - -----------------------------------------------
2025-10-06T21:47:31.718811 - ComfyUI-LTXVideo                  N         0
2025-10-06T21:47:31.719811 - ComfyUI-Florence2                 Y         2
2025-10-06T21:47:31.720811 - ComfyUI_bitsandbytes_NF4          N         0
2025-10-06T21:47:31.720811 - x-flux-comfyui                    N         0
2025-10-06T21:47:31.721812 - ComfyUI-MMAudio                   N         0
2025-10-06T21:47:31.722813 - ComfyUI-GGUF                      Y        18
2025-10-06T21:47:31.722813 - PuLID_ComfyUI                     N         0
2025-10-06T21:47:31.723812 - ComfyUI-HunyuanVideoWrapper       N         0
2025-10-06T21:47:31.724812 - ComfyUI-WanVideoWrapper           Y         8
2025-10-06T21:47:31.724812 - -----------------------------------------------
2025-10-06T21:47:31.725908 - [MultiGPU] Registration complete. Final mappings: DeviceSelectorMultiGPU, HunyuanVideoEmbeddingsAdapter, CheckpointLoaderAdvancedMultiGPU, CheckpointLoaderAdvancedDisTorch2MultiGPU, UNetLoaderLP, UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, QuadrupleCLIPLoaderMultiGPU, CLIPVisionLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU, DiffusersLoaderMultiGPU, DiffControlNetLoaderMultiGPU, UNETLoaderDisTorch2MultiGPU, VAELoaderDisTorch2MultiGPU, CLIPLoaderDisTorch2MultiGPU, DualCLIPLoaderDisTorch2MultiGPU, TripleCLIPLoaderDisTorch2MultiGPU, QuadrupleCLIPLoaderDisTorch2MultiGPU, CLIPVisionLoaderDisTorch2MultiGPU, CheckpointLoaderSimpleDisTorch2MultiGPU, ControlNetLoaderDisTorch2MultiGPU, DiffusersLoaderDisTorch2MultiGPU, DiffControlNetLoaderDisTorch2MultiGPU, Florence2ModelLoaderMultiGPU, DownloadAndLoadFlorence2ModelMultiGPU, UnetLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFAdvancedDisTorchMultiGPU, CLIPLoaderGGUFDisTorchMultiGPU, DualCLIPLoaderGGUFDisTorchMultiGPU, TripleCLIPLoaderGGUFDisTorchMultiGPU, QuadrupleCLIPLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFDisTorch2MultiGPU, UnetLoaderGGUFAdvancedDisTorch2MultiGPU, CLIPLoaderGGUFDisTorch2MultiGPU, DualCLIPLoaderGGUFDisTorch2MultiGPU, TripleCLIPLoaderGGUFDisTorch2MultiGPU, QuadrupleCLIPLoaderGGUFDisTorch2MultiGPU, UnetLoaderGGUFMultiGPU, UnetLoaderGGUFAdvancedMultiGPU, CLIPLoaderGGUFMultiGPU, DualCLIPLoaderGGUFMultiGPU, TripleCLIPLoaderGGUFMultiGPU, QuadrupleCLIPLoaderGGUFMultiGPU, WanVideoModelLoaderMultiGPU, WanVideoModelLoaderMultiGPU_2, WanVideoVAELoaderMultiGPU, LoadWanVideoT5TextEncoderMultiGPU, LoadWanVideoClipTextEncoderMultiGPU, WanVideoTextEncodeMultiGPU, WanVideoBlockSwapMultiGPU, WanVideoSamplerMultiGPU
2025-10-06T21:47:31.759130 - here: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyUI-tbox2025-10-06T21:47:31.759130 - 
2025-10-06T21:47:31.761132 - Using ckpts path: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyUI-tbox\..\..\models\annotator2025-10-06T21:47:31.761132 - 
2025-10-06T21:47:31.761132 - Using symlinks: False2025-10-06T21:47:31.762131 - 
2025-10-06T21:47:31.762131 - Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']2025-10-06T21:47:31.762131 - 
2025-10-06T21:47:31.918827 - DWPose: Onnxruntime with acceleration providers detected2025-10-06T21:47:31.918827 - 
2025-10-06T21:47:32.359434 - Warning: Could not load sageattention: No module named 'sageattention'
2025-10-06T21:47:32.359434 - sageattention package is not installed, sageattention will not be available
2025-10-06T21:47:32.473568 - [AcademiaSD Loader] Adding ComfyUI root path to sys.path: C:\Users\genshistudio\Documents\ComfyUI2025-10-06T21:47:32.473568 - 
2025-10-06T21:47:32.474568 - [AcademiaSD Loader] Successfully pre-imported the 'comfy' module.2025-10-06T21:47:32.474568 - 
2025-10-06T21:47:32.481659 - [36;20m[C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2025-10-06T21:47:32.482659 - [36;20m[C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2025-10-06T21:47:32.483659 - [36;20m[C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2025-10-06T21:47:32.649019 - 
2025-10-06T21:47:32.649019 - [92m[rgthree-comfy] Loaded 48 fantastic nodes. 🎉[0m2025-10-06T21:47:32.649019 - 
2025-10-06T21:47:32.649019 - 
2025-10-06T21:47:32.661145 - [VibeVoice] Using embedded VibeVoice (MIT licensed)
2025-10-06T21:47:32.851054 - [VibeVoice] VibeVoice nodes registered successfully
2025-10-06T21:47:32.867294 - ### Loading: ComfyUI-Manager (V3.36)
2025-10-06T21:47:32.867294 - [ComfyUI-Manager] network_mode: public
2025-10-06T21:47:32.868294 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
2025-10-06T21:47:32.903662 - 
Import times for custom nodes:
2025-10-06T21:47:32.904663 -    0.0 seconds: C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-10-06T21:47:32.904663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-int-and-float
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\debugnode-comfyui
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-mxtoolkit
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyLiterals
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui_AcademiaSD
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyUI-GGUF
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-florence2
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui_essentials
2025-10-06T21:47:32.905663 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyMath
2025-10-06T21:47:32.906699 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-frame-interpolation
2025-10-06T21:47:32.906806 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2025-10-06T21:47:32.906806 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-advanced-controlnet
2025-10-06T21:47:32.906806 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-kjnodes
2025-10-06T21:47:32.906806 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-multigpu
2025-10-06T21:47:32.906806 -    0.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\rgthree-comfy
2025-10-06T21:47:32.906806 -    0.0 seconds: C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-10-06T21:47:32.906806 -    0.1 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui_controlnet_aux
2025-10-06T21:47:32.906806 -    0.1 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\facerestore_cf
2025-10-06T21:47:32.906806 -    0.1 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-subpack
2025-10-06T21:47:32.907804 -    0.1 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-videohelpersuite
2025-10-06T21:47:32.907804 -    0.2 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
2025-10-06T21:47:32.907804 -    0.2 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyUI-tbox
2025-10-06T21:47:32.907804 -    0.2 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\VibeVoice-ComfyUI
2025-10-06T21:47:32.907804 -    0.3 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack
2025-10-06T21:47:32.907804 -    0.3 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-tensorops
2025-10-06T21:47:32.907804 -    0.6 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\ComfyUI-MelBandRoFormer
2025-10-06T21:47:32.907804 -    2.0 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfy-mtb
2025-10-06T21:47:32.907804 -    6.8 seconds: C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-easy-use
2025-10-06T21:47:32.907804 - 
2025-10-06T21:47:33.104405 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-10-06T21:47:33.202303 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-10-06T21:47:33.346728 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-10-06T21:47:33.415641 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-10-06T21:47:33.466416 - Failed to initialize database. Please ensure you have installed the latest requirements. If the error persists, please report this as in future the database will be required: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-10-06T21:47:33.514763 - Starting server

2025-10-06T21:47:33.514763 - To see the GUI go to: http://127.0.0.1:8002
2025-10-06T21:47:33.595538 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-10-06T21:47:35.456163 - comfyui-frontend-package not found in requirements.txt
2025-10-06T21:47:36.289584 - FETCH ComfyRegistry Data: 5/992025-10-06T21:47:36.289584 - 
2025-10-06T21:47:36.945377 - comfyui-frontend-package not found in requirements.txt
2025-10-06T21:47:37.043246 - [36;20m[C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfy-mtb] | INFO -> Found multiple match, we will pick the last J:\ComfyModels\upscale_models
['C:\\Users\\genshistudio\\Documents\\ComfyUI\\models\\upscale_models', 'J:\\ComfyModels\\upscale_models'][0m
2025-10-06T21:47:37.689714 - [VibeVoice] No valid models found in vibevoice directory
2025-10-06T21:47:37.690714 - [VibeVoice] Please download models to: C:\Users\genshistudio\Documents\ComfyUI\models\vibevoice
2025-10-06T21:47:37.690714 - [VibeVoice] No LoRA adapters found in ComfyUI/models/vibevoice/loras
2025-10-06T21:47:39.405119 - FETCH ComfyRegistry Data: 10/992025-10-06T21:47:39.405119 - 
2025-10-06T21:47:42.506048 - FETCH ComfyRegistry Data: 15/992025-10-06T21:47:42.506048 - 
2025-10-06T21:47:45.628479 - FETCH ComfyRegistry Data: 20/992025-10-06T21:47:45.628479 - 
2025-10-06T21:47:48.779447 - FETCH ComfyRegistry Data: 25/992025-10-06T21:47:48.779447 - 
2025-10-06T21:47:51.867010 - FETCH ComfyRegistry Data: 30/992025-10-06T21:47:51.867010 - 
2025-10-06T21:47:54.399826 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-10-06T21:47:54.399826 - 
2025-10-06T21:47:54.510644 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-10-06T21:47:54.510644 - 2025-10-06T21:47:54.805038 -  [DONE]2025-10-06T21:47:54.805038 - 
2025-10-06T21:47:54.971562 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-10-06T21:47:54.971562 - 2025-10-06T21:47:55.081711 - FETCH ComfyRegistry Data: 35/992025-10-06T21:47:55.081711 - 
2025-10-06T21:47:55.190609 -  [DONE]2025-10-06T21:47:55.190609 - 
2025-10-06T21:47:55.227889 - [ComfyUI-Manager] DB item is broken:
{'title': 'RC Image Compositor', 'author': 'kj863257', 'description': 'A comprehensive ComfyUI plugin suite that brings professional Photoshop-style layer effects and advanced compositing capabilities. Features modular architecture, 24 blend modes, and enhanced positioning system.', 'files': ['https://github.com/kj863257/ComfyUI_RC_Image_Compositor'], 'install_type': 'git-clone', 'tags': ['compositing', 'layer', 'blend modes', 'photoshop-style'], 'repository': 'https://github.com/kj863257/ComfyUI_RC_Image_Compositor', 'version': 'unknown', 'state': 'not-installed'}
2025-10-06T21:47:55.228889 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extras.json2025-10-06T21:47:55.228889 - 2025-10-06T21:47:55.384730 -  [DONE]2025-10-06T21:47:55.384730 - 
2025-10-06T21:47:55.516484 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-10-06T21:47:55.516484 - 2025-10-06T21:47:55.794053 -  [DONE]2025-10-06T21:47:55.794053 - 
2025-10-06T21:47:58.167669 - FETCH ComfyRegistry Data: 40/992025-10-06T21:47:58.168669 - 
2025-10-06T21:48:01.373146 - FETCH ComfyRegistry Data: 45/992025-10-06T21:48:01.373146 - 
2025-10-06T21:48:04.559119 - FETCH ComfyRegistry Data: 50/992025-10-06T21:48:04.559119 - 
2025-10-06T21:48:07.661795 - FETCH ComfyRegistry Data: 55/992025-10-06T21:48:07.661795 - 
2025-10-06T21:48:09.840189 - got prompt
2025-10-06T21:48:10.171397 - Using pytorch attention in VAE
2025-10-06T21:48:10.173398 - Using pytorch attention in VAE
2025-10-06T21:48:10.385344 - VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
2025-10-06T21:48:10.704041 - model weight dtype torch.float16, manual cast: None
2025-10-06T21:48:10.706173 - model_type EPS
2025-10-06T21:48:10.882082 - FETCH ComfyRegistry Data: 60/992025-10-06T21:48:10.882082 - 
2025-10-06T21:48:13.508017 - Using pytorch attention in VAE
2025-10-06T21:48:13.510017 - Using pytorch attention in VAE
2025-10-06T21:48:13.718063 - VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
2025-10-06T21:48:13.728066 - [MultiGPU Core Patching] text_encoder_device_patched returning device: cuda:0 (current_text_encoder_device=cuda:0)
2025-10-06T21:48:13.965204 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-10-06T21:48:14.048222 - FETCH ComfyRegistry Data: 65/992025-10-06T21:48:14.048222 - 
2025-10-06T21:48:15.294504 - Requested to load SDXLClipModel
2025-10-06T21:48:15.851166 - loaded completely 8687.8 1560.802734375 True
2025-10-06T21:48:17.249276 - FETCH ComfyRegistry Data: 70/992025-10-06T21:48:17.249276 - 
2025-10-06T21:48:17.860414 - Requested to load SDXL
2025-10-06T21:48:20.480565 - FETCH ComfyRegistry Data: 75/992025-10-06T21:48:20.480565 - 
2025-10-06T21:48:23.655439 - FETCH ComfyRegistry Data: 80/992025-10-06T21:48:23.655439 - 
2025-10-06T21:48:23.883491 - loaded completely 7071.87080078125 4897.0483474731445 True
2025-10-06T21:48:26.711408 - 
 93%|█████████▎| 14/15 [00:02<00:00,  5.70it/s]2025-10-06T21:48:26.776838 - FETCH ComfyRegistry Data: 85/992025-10-06T21:48:26.776838 - 
2025-10-06T21:48:26.868002 - 
100%|██████████| 15/15 [00:02<00:00,  5.90it/s]2025-10-06T21:48:26.868002 - 
100%|██████████| 15/15 [00:02<00:00,  5.16it/s]2025-10-06T21:48:26.868002 - 
2025-10-06T21:48:26.869002 - Requested to load AutoencoderKL
2025-10-06T21:48:27.000818 - loaded completely 999.3818359375 319.11416244506836 True
2025-10-06T21:48:29.933904 - FETCH ComfyRegistry Data: 90/992025-10-06T21:48:29.933904 - 
2025-10-06T21:48:30.082938 - loaded completely 6746.336193847656 4897.0483474731445 True
2025-10-06T21:48:32.861220 - 
 27%|██▋       | 8/30 [00:02<00:07,  2.91it/s]2025-10-06T21:48:33.076653 - FETCH ComfyRegistry Data: 95/992025-10-06T21:48:33.076653 - 
2025-10-06T21:48:35.960826 - 
 57%|█████▋    | 17/30 [00:05<00:04,  2.91it/s]2025-10-06T21:48:36.166872 - FETCH ComfyRegistry Data [DONE]2025-10-06T21:48:36.166872 - 
2025-10-06T21:48:36.313905 - 
 60%|██████    | 18/30 [00:06<00:04,  2.88it/s]2025-10-06T21:48:36.463939 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-10-06T21:48:36.538956 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-10-06T21:48:36.806016 - 
 63%|██████▎   | 19/30 [00:06<00:04,  2.56it/s]2025-10-06T21:48:36.845025 -  [DONE]2025-10-06T21:48:36.845025 - 
2025-10-06T21:48:36.992058 - [ComfyUI-Manager] All startup tasks have been completed.
2025-10-06T21:48:40.812099 - 
100%|██████████| 30/30 [00:10<00:00,  2.73it/s]2025-10-06T21:48:40.812099 - 
100%|██████████| 30/30 [00:10<00:00,  2.80it/s]2025-10-06T21:48:40.812099 - 
2025-10-06T21:48:42.487521 - 
2025-10-06T21:48:42.803513 - 0: 384x640 1 face, 56.4ms
2025-10-06T21:48:42.803513 - Speed: 68.9ms preprocess, 56.4ms inference, 69.8ms postprocess per image at shape (1, 3, 384, 640)
2025-10-06T21:48:42.829664 - !!! Exception during processing !!! 'DifferentialDiffusion' object has no attribute 'apply'
2025-10-06T21:48:42.832665 - Traceback (most recent call last):
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 876, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 830, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 304, in do_detail
    model = nodes_differential_diffusion.DifferentialDiffusion().apply(model)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DifferentialDiffusion' object has no attribute 'apply'

2025-10-06T21:48:42.835666 - Prompt executed in 32.99 seconds
2025-10-06T21:49:05.861332 - got prompt
2025-10-06T21:49:05.884472 - Requested to load SDXL
2025-10-06T21:49:08.046307 - loaded completely 7682.6359375 4897.0483474731445 True
2025-10-06T21:49:10.566005 - 
100%|██████████| 15/15 [00:02<00:00,  6.12it/s]2025-10-06T21:49:10.566005 - 
100%|██████████| 15/15 [00:02<00:00,  6.00it/s]2025-10-06T21:49:10.566005 - 
2025-10-06T21:49:13.076583 - loaded completely 8191.389416503906 4897.0483474731445 True
2025-10-06T21:49:23.981714 - 
100%|██████████| 30/30 [00:10<00:00,  2.55it/s]2025-10-06T21:49:23.981714 - 
100%|██████████| 30/30 [00:10<00:00,  2.76it/s]2025-10-06T21:49:23.981714 - 
2025-10-06T21:49:25.027514 - 
2025-10-06T21:49:25.064522 - 0: 384x640 1 face, 18.4ms
2025-10-06T21:49:25.064522 - Speed: 2.4ms preprocess, 18.4ms inference, 2.7ms postprocess per image at shape (1, 3, 384, 640)
2025-10-06T21:49:25.093529 - !!! Exception during processing !!! 'DifferentialDiffusion' object has no attribute 'apply'
2025-10-06T21:49:25.095529 - Traceback (most recent call last):
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\genshistudio\AppData\Local\Programs\ComfyUI\resources\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 876, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 830, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
  File "C:\Users\genshistudio\Documents\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 304, in do_detail
    model = nodes_differential_diffusion.DifferentialDiffusion().apply(model)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DifferentialDiffusion' object has no attribute 'apply'

2025-10-06T21:49:25.098530 - Prompt executed in 19.23 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

Workflow too large. Please manually upload the workflow from local file system.


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by kittituch-git** [comment]
I've got this error after update comfyui too, so, how to fix this error?

**Comment by krul12** [comment]
how to fix?

**Comment by airmilk90410** [comment]
ComfyUI-Impact-Pack Node error

**Comment by mindAddiction** [comment]
This might have a cause for it, though I haven't tested it yet:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1113

**Comment by nova452** [comment]
Switch to nightly

**Comment by airmilk90410** [comment]
ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py
從apply更改為execute。

**Comment by thaihbn** [comment]
I've got same error! :(

**Comment by LokeshYadav** [comment]
> Switch to nightly

Switching toi nightly didn't resolve this issue.

**Comment by futhark16** [comment]
switching to 3.62 in the manager has worked for me

**Comment by mindAddiction** [comment]
Seems a bit silly that the only solution is a rollback.
Couldn't get the impact changes to work, so don't know.

**Comment by InoriNatsume** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1113#issuecomment-3368356145 worked for me

<img width="1402" height="790" alt="Image" src="https://github.com/user-attachments/assets/f8e44a07-97dd-4f51-8c23-bab6d7e06f5c" />

<img width="783" height="172" alt="Image" src="https://github.com/user-attachments/assets/13336beb-db9f-4cda-bc3d-ae7c35486fa2" />

**Comment by shadowfire4577-cpu** [comment]
> switching to 3.62 in the manager has worked for me

How do you go about rollbacking?

**Comment by LokeshYadav** [comment]
Thanks to @thomas-lennon-atu-ie for fast resolving this issue.

You can refer to this thread to resolve this issue
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1113#issuecomment-3368356145

**Comment by futhark16** [comment]
> > switching to 3.62 in the manager has worked for me
> 
> How do you go about rollbacking?

if you have comfy manager installed, just click switch comfyui and select the version you want.

**Comment by Gamalonia** [comment]
I see in the manager only other version numbers (8.x) - witch is it?

**Comment by pxdx** [comment]
> I see in the manager only other version numbers (8.x) - witch is it?

When you open the manager,  right above the red Restart button is "Switch ComfyUI" button. Click that and wait a couple of seconds and then a dropdown menu with all of the versions appears. Choose 3.62.
Working solution as of 08. Oct. switching from an update 3.64 (broke FD)

**Comment by tarar999** [comment]
its easy to fix guys, just import "differential diffusion" node and drag it into your workflow right before the FACE DETAILER node. connect it to the same model input that face detailer uses. leave the inputs default. workflow will be LOAD CHECKPOINT.....DIFFERENTIAL DIFFUSION....FACE DETAILER.....KSampler. the error should vanish now

**Comment by Gamalonia** [comment]
> its easy to fix guys, just import "differential diffusion" node and drag it into your workflow right before the FACE DETAILER node. connect it to the same model input that face detailer uses. leave the inputs default. workflow will be LOAD CHECKPOINT.....DIFFERENTIAL DIFFUSION....FACE DETAILER.....KSampler. the error should vanish now

Ah it is working - thx for the "fix"!

**Comment by steph-vie** [comment]
Hello,

Version 8.25.0 works for me !

**Comment by Aquaman03** [comment]
> > its easy to fix guys, just import "differential diffusion" node and drag it into your workflow right before the FACE DETAILER node. connect it to the same model input that face detailer uses. leave the inputs default. workflow will be LOAD CHECKPOINT.....DIFFERENTIAL DIFFUSION....FACE DETAILER.....KSampler. the error should vanish now
> 
> Ah it is working - thx for the "fix"!

THANK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by xjw2005** [comment]
> its easy to fix guys, just import "differential diffusion" node and drag it into your workflow right before the FACE DETAILER node. connect it to the same model input that face detailer uses. leave the inputs default. workflow will be LOAD CHECKPOINT.....DIFFERENTIAL DIFFUSION....FACE DETAILER.....KSampler. the error should vanish now

Thank you!

**Comment by kowninjae** [comment]
> its easy to fix guys, just import "differential diffusion" node and drag it into your workflow right before the FACE DETAILER node. connect it to the same model input that face detailer uses. leave the inputs default. workflow will be LOAD CHECKPOINT.....DIFFERENTIAL DIFFUSION....FACE DETAILER.....KSampler. the error should vanish now

Thank you, good info.

**Comment by hectorpikoz-cyber** [comment]
> differential diffusion

thank you!

**Comment by Karos44** [comment]
> its easy to fix guys, just import "differential diffusion" node and drag it into your workflow right before the FACE DETAILER node. connect it to the same model input that face detailer uses. leave the inputs default. workflow will be LOAD CHECKPOINT.....DIFFERENTIAL DIFFUSION....FACE DETAILER.....KSampler. the error should vanish now

It works! thank you!

**Comment by comfyuistudio** [comment]
> > switching to 3.62 in the manager has worked for me

FIX!!!! 

switch Impact Pack custom node version to 8.25.0
it will fix it

**Comment by VB-Taro** [comment]
I've connected differential diffusion node to the face detailer node and it works fine. It seems to be similar to the inpainting workflow.
