### ISSUE TITLE
🚫 “HIP out of memory” – ComfyUI fails on AMD Radeon 8060S (96 GB VRAM)

### ISSUE THREAD

**Issue by skenetti** [comfyanonymous/ComfyUI#10277]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question
📌 _**Hardware Snapshot**_

🧠 CPU: AMD Ryzen AI Max+ 395 (16 C/32 T, max turbo 5.1 GHz, 64 MB L3 cache)
🎮 GPU: AMD Radeon 8060S – 40 CU, 96 GB VRAM
💾 RAM: 128 GB LPDDR5X @ 8000 MT/s

🛠️ _**Environment**_

Ubuntu 24.04 LTS
ROCm 6.4.4 (installed from the official AMD repository)
PyTorch built for ROCm 6.4.4 (installed from the official AMD repository)

🎯 **_Goal_**

Run ComfyUI on this machine and generate an AI video using the Wan 2.2‑5B model.

🔍 **_What I’ve Tried So Far_**

1. Installed ROCm & the matching PyTorch packages.
2. Started ComfyUI (v0.3.64).
3. Ran a workflow that uses the Wan 2.2‑5B checkpoint.

Result: an out‑of‑memory error pops up immediately.

❌ **_Error Message_**
```
HIP out of memory. Tried to allocate 66.54 GiB.
GPU 0 has a total capacity of 96.00 GiB of which 10.75 GiB is free.
Of the allocated memory 84.36 GiB is allocated by PyTorch,
and 360.11 MiB is reserved by PyTorch but unallocated.

If reserved but unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.

See documentation for Memory Management:
https://pytorch.org/docs/stable/notes/cuda.html#environment-variables

This error means you ran out of memory on your GPU.
TIPS: If the workflow worked before you might have accidentally set
the batch_size to a large number.
```
🤔 **_Why This Is Unexpected_**

The GPU has 96 GB of VRAM, yet PyTorch reports only ~10 GB free.
Even though total allocation (84 GiB) is below 96 GiB, the system refuses an additional 66 GiB that should comfortably fit.

🛠️ **_Work‑arounds I’ve Tried_**
1. Reduced batch size in the workflow
Still fails with the same error
2. Set **PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True**
No improvement
4. Re‑installed PyTorch/ROCm packages
Same behavior

❓ **_Questions for the Community_**

1. Why can’t PyTorch utilize the full 96 GB VRAM on this card?
2. Is there a known issue with ROCm 6.4.4 + ComfyUI causing memory fragmentation or incorrect free‑memory reporting?
3. What environment variables or runtime flags should I set to allow larger allocations on AMD GPUs?
4. Are there any specific build options for PyTorch/ROCm that enable “expandable segments” or similar features on the Radeon 8060S ?

🙏 Thanks for any insights or fixes!
### Logs

```powershell

```

**Comment by ghost** [comment]
I tried the same workflow on Windows 11 using the latest AMD Adrenalin Driver 25.20 Preview, and it did not give the same “HIP out of memory” error! 🎉

This makes me wonder:

- Have I missed something in installing the Ubuntu amdgpu drivers?
- Or does this particular hardware (Ryzen AI Max+ 395 / Radeon 8060S) simply lack an Ubuntu driver?

I checked AMD’s official download page for the Ryzen AI Max+ 395 and could only find Windows installers. If anyone has a working Ubuntu driver or knows how to get the ROCm stack correctly set up on this board, please let me know! 🙏

Hope this info helps other users in the same boat—if my assumption turns out to be wrong, I’d still appreciate any guidance. 🚧

**Comment by donlaiq** [comment]
I’m experimenting with similar problems in ComfyUI using the same hardware described by @skenetti.

Working with Ubuntu 24.04.3 LTS and ROCm 7.1.1.

I'm unable to generate text-to-video and image-to-video models because the PC runs out of memory.

Any idea if it works on another Linux distro? Does it even work on Windows?

**Comment by ghost** [comment]
> 
> Any idea if it works on another Linux distro? Does it even work on Windows?
> 

Dear @donlaiq at the end i have installed Windows 11 to run ComfyUI with AMD hardware and It works.

At the end of my research, i could say you this: ROCm is for only CPU hardware.

If you check GPU's Marketing name after ROCm Installation, you see a general "AMD Radeon Graphics".
This indicate that is not competely supported by AMD on Linux.

And GPU acceleration is requested to run this kind of software.

**Comment by ghost** [comment]
Update on my setup:

Inspired by @donlaiq request, I installed Kubuntu 25.10 on my machine.

I found that using Vulkan support directly works very well on my AMD Radeon 8060S (96 GB VRAM), without needing to install the proprietary ROCm module and while keeping the standard stock kernel provided by the distro.

I tested this using LM Studio with the gpt-oss 120b model, and the performance is very good. It seems the native Vulkan stack on this kernel is robust enough to handle heavy inference without the manual ROCm setup.

# Suggestion:

Given how flawlessly the Vulkan backend performs on this hardware (compared to the strict ROCm requirements), I strongly suggest that supporting/prioritizing a Vulkan execution path for ComfyUI could be the ultimate solution to solve these driver compatibility headaches on Linux.

**Comment by donlaiq** [comment]
That's the point. I was using Ubuntu 24.04.3 LTS, and my only problem was with video generation. Not only could I not generate any video, but it also froze the device, causing me to lose the video signal.

However, the image generation (also using ComfyUI) worked very well, and the inference for LLM models in LM Studio was very good.

That's why I'm not quite convinced whether it was a problem with the drivers or a bug in the ComfyUI version for Linux.

Now, I've installed Windows. I was able to generate videos, but it takes an eternity for them to finish.

**Comment by jovan2009** [comment]
I agree that vulkan works very well in llama.cpp. Even though I have an Nvidia GPU I noticed that vulkan version is sometimes more stable than cuda version, although is not faster is not much slower and is sometimes more forgiving with low VRAM. But llama.cpp is llama.cpp, ComfyUI relies on Pytorch. A vulkan pathway for ComfyUI would need a vulkan version of Pytorch. Although I have seen some discussions about that at Pytorch repository I am unaware of an actual vulkan Pytorch build available, or am I wrong?

**Comment by donlaiq** [comment]
Hey, guys! 
I made some progress. Maybe you would like to check it out to bring some new ideas: https://github.com/comfyanonymous/ComfyUI/discussions/11500
