### ISSUE TITLE
Something broke down because of one of the last updates

### ISSUE THREAD

**Issue by BestofthebestinAI** [comfyanonymous/ComfyUI#10377]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

As you can see I am using one of MY OWN workflows, since it comes from MY output folder:

<img width="560" height="187" alt="Image" src="https://github.com/user-attachments/assets/224779f5-d254-4859-b19b-435bc953c69b" />

What was expected is it working again! Its that simple
Its this workflow (should be inside the image, otherwise I provided it in text form)

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/c8ee8e6a-7bc3-43ed-804f-f3b73cb4a8ba" />

[workedBefore.txt](https://github.com/user-attachments/files/22963706/workedBefore.txt)

It is literally one of my first gens, as you see its numeration,
Problem I can no longer run the workflow due to messages saying I reached limit ( torch._dynamo hit config.recompile_limit (64)), I did not have that in my successful gen previousely.

Only noticeable change I did was:
- increase windows page file size (for another workflow I believe) from 3096 to 32k then 40ishk+ (I tried to bring it back to base afterwards and changed nothing)
- Installed ComfyUI-WanAnimatePreprocess through git clone and pip install -r req, despite the manager asking to reduce SECURITY in order to install it.. (I removed it manually, did not solve my issue, I uninstalled the libraries it brought to my install (onnx and ml_dtypes), did not solve my issue, I finally started a new comfy install, same)
- **Probably did some comfy update sometime during the last 3 days**, once or twice.
- Installed nunchaku (but the new comfy install still has the new problem, and it does not have nunchaku so..)

### Actual Behavior

MY OWN workflow does not work anymore! That's what is happening
And there IS NOT REASON for it. I am getting this:
(torch._dynamo hit config.recompile_limit (64))
I get a spike in vram usage, then comfy craches:

<img width="791" height="594" alt="Image" src="https://github.com/user-attachments/assets/4c593ea2-d5eb-4206-80de-48989be320b3" />

___
The workflow is no longer able to perform the workflow with same params that worked 2-3 days ago!
(btw I RE use the workflow as is, with same input image and same params which are: 1280x720x81, and same everything even the seed,)
I was trying to see if something could work, I tried 720x720x33 it passed, but 2-3 days I was able to to do 1280x720x81.
So the workflow is still working for smaller perfs, I mean smaller consumption (smaller video), it just would not work as 2-3 days where the video was longer)

- I spent hours trying to solve this problem, I did all the following:
- remove  triton files (from both 2 paths ":\Users\<username>\AppData\Local\Temp\torchinductor_<username>\triton>" and "\Users\<username>\.triton") -> restart and try the same workflow. = FAILED. OOR
- increase dynamo cache size limit from 64 to 128 -> max gpu (comfy frozen)
- Same but with reserve-ram 2 -> same (comfy not advancing at ksampler level)
- Same but reserve-ram 4 -> FAILED (error and crach)
- cache size limit from at 96 + reserve ram 2  (error: torch._dynamo hit config.recompile_limit (96))
- try ANOTHER WORKFLOW at first, then try the current workflow (in case of 2.8.0 first gen vram excessive usage) -> no effect.

C shows at high usage but it stil has 160 free GBs. Whichever page file size I experiment I never go below a resaonable free space and certainly not below 0)

### Steps to Reproduce

use the workflow on this image or txt file:

[workedBefore.txt](https://github.com/user-attachments/files/22964077/workedBefore.txt)

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/c375e1c9-4551-4404-8529-c950f30be57c" />

Have triton and sage attention (see my versions in the pip list I posted below).
Run.
(windows page file can be ANY size I get always the same error it seems: https://www.reddit.com/r/StableDiffusion/comments/1o4kntc/psa_increasing_paging_file_size_helps_preventing/)

### Debug Logs

```powershell
FETCH ComfyRegistry Data: 100/100
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load devicG: cuda:0, offload devicG: cpu, dtypG: torch.bfloat16
Requested to load CLIPVisionModelProjection
loaded completely 21785.8 1208.09814453125 True
Using scaled fp8: fp8 matrix mult: False, scale input: False
CLIP/text encoder model load devicG: cuda:0, offload devicG: cpu, current: cpu, dtypG: torch.float16
Requested to load WanTEModel
loaded completely 20505.5744140625 6419.477203369141 True
Requested to load WanVAE
loaded completely 4358.422206878662 242.02829551696777 True
gguf qtypes: F16 (694), Q8_0 (400), F32 (1)
model weight dtype torch.float16, manual cast: None
model_type FLOW
lora key not loaded: diffusion_model.blocks.0.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.0.cross_attn.k_img.lora_down.weight

.....

lora key not loaded: diffusion_model.blocks.9.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.img_emb.proj.0.diff
lora key not loaded: diffusion_model.img_emb.proj.0.diff_b
lora key not loaded: diffusion_model.img_emb.proj.1.diff_b
lora key not loaded: diffusion_model.img_emb.proj.1.lora_down.weight
lora key not loaded: diffusion_model.img_emb.proj.1.lora_up.weight
lora key not loaded: diffusion_model.img_emb.proj.3.diff_b
lora key not loaded: diffusion_model.img_emb.proj.3.lora_down.weight
lora key not loaded: diffusion_model.img_emb.proj.3.lora_up.weight
lora key not loaded: diffusion_model.img_emb.proj.4.diff
lora key not loaded: diffusion_model.img_emb.proj.4.diff_b
Requested to load WAN21
loaded partially 8588.889382366657 8580.986450195312 0
Attempting to release mmap (235)
Patching comfy attention to use sageattn
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]W1017 xx:50:14.963000 17892 Lib\site-packages\torch\_dynamo\convert_frame.py:1016] [7/64] torch._dynamo hit config.recompile_limit (64)
W1017 xx:50:14.963000 17892 Lib\site-packages\torch\_dynamo\convert_frame.py:1016] [7/64]    function: 'torch_dynamo_resume_in_forward_at_124' (G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ops.py:124)
W1017 xx:50:14.963000 17892 Lib\site-packages\torch\_dynamo\convert_frame.py:1016] [7/64]    last reason: 7/63: self._parameters['weight'].patches[0][1] == 'diffusion_model.blocks.6.self_attn.o.weight'
W1017 xx:50:14.963000 17892 Lib\site-packages\torch\_dynamo\convert_frame.py:1016] [7/64] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W1017 xx:50:14.963000 17892 Lib\site-packages\torch\_dynamo\convert_frame.py:1016] [7/64] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
  0%|                                                                                            | 0/2 [00:30<?, ?it/s]
Restoring initial comfy attention
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1559, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1492, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
                                  denoise=denoise, disable_noise=disable_noise, start_step=start_step, last_step=last_step,
                                  force_full_denoise=force_full_denoise, noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1154, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1044, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1029, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 997, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 980, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 752, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 1009, in sample_lcm
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 401, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 953, in __call__
    return self.outer_predict_noise(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 960, in outer_predict_noise
    ).execute(x, timestep, model_options, seed)
      ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 963, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 381, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 206, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 214, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 326, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 161, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...<2 lines>...
        comfy.patcher_extension.get_all_wrappers(comfy.patcher_extension.WrappersMP.APPLY_MODEL, transformer_options)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ).execute(x, t, c_concat, c_crossattn, control, transformer_options, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 113, in execute
    return self.wrappers[self.idx](self, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy_api\torch_helpers\torch_compile.py", line 26, in apply_torch_compile_wrapper
    return executor(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 105, in __call__
    return new_executor.execute(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 200, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 614, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...<2 lines>...
        comfy.patcher_extension.get_all_wrappers(comfy.patcher_extension.WrappersMP.DIFFUSION_MODEL, transformer_options)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ).execute(x, timestep, context, clip_fea, time_dim_concat, transformer_options, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 634, in _forward
    return self.forward_orig(x, timestep, context, clip_fea=clip_fea, freqs=freqs, transformer_options=transformer_options, **kwargs)[:, :, :t, :h, :w]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 579, in forward_orig
    x = block(x, e=e0, freqs=freqs, context=context, context_img_len=context_img_len, transformer_options=transformer_options)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in __call__
    return super().__call__(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 736, in compile_wrapper
    return fn(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 236, in forward
    torch.addcmul(repeat_e(e[0], x), self.norm1(x), 1 + repeat_e(e[1], x)),
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 235, in torch_dynamo_resume_in_forward_at_236
    y = self.self_attn(
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 243, in torch_dynamo_resume_in_forward_at_235
    x = x + self.cross_attn(self.norm3(x), context, context_img_len=context_img_len, transformer_options=transformer_options)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 243, in torch_dynamo_resume_in_forward_at_243
    x = x + self.cross_attn(self.norm3(x), context, context_img_len=context_img_len, transformer_options=transformer_options)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 244, in torch_dynamo_resume_in_forward_at_243
    y = self.ffn(torch.addcmul(repeat_e(e[3], x), self.norm2(x), 1 + repeat_e(e[4], x)))
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\ComfyUI\comfy\ldm\wan\model.py", line 244, in torch_dynamo_resume_in_forward_at_244
    y = self.ffn(torch.addcmul(repeat_e(e[3], x), self.norm2(x), 1 + repeat_e(e[4], x)))
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\container.py", line 244, in forward
    input = module(input)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\activation.py", line 738, in forward
    return F.gelu(input, approximate=self.approximate)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.

G:\ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable>pause
Press any key to continue . . .


__

And my pip list currently (new comfy install has runs ONLY the workflow that I am trying to make REWORK after 2-3 days from it working fine):
ComfyUI_windows_portable_nvidia171025\ComfyUI_windows_portable\python_embeded>python.exe -m pip list
Package                    Version
-------------------------- ---------------------------
accelerate                 1.10.1
aiofiles                   24.1.0
aiohappyeyeballs           2.6.1
aiohttp                    3.12.15
aiohttp_socks              0.10.1
aiosignal                  1.4.0
alembic                    1.16.5
annotated-types            0.7.0
attrs                      25.3.0
av                         15.1.0
certifi                    2025.8.3
cffi                       2.0.0
chardet                    5.2.0
charset-normalizer         3.4.3
click                      8.3.0
clip-interrogator          0.6.0
color-matcher              0.6.0
colorama                   0.4.6
coloredlogs                15.0.1
comfyui-embedded-docs      0.3.0
comfyui_frontend_package   1.28.7
comfyui_workflow_templates 0.1.95
contourpy                  1.3.3
cryptography               46.0.3
cycler                     0.12.1
ddt                        1.7.2
diffusers                  0.35.2
docutils                   0.22.2
einops                     0.8.1
filelock                   3.19.1
flatbuffers                25.9.23
fonttools                  4.60.1
frozenlist                 1.7.0
fsspec                     2025.9.0
ftfy                       6.3.1
gguf                       0.17.1
gitdb                      4.0.12
GitPython                  3.1.45
greenlet                   3.2.4
h11                        0.16.0
h2                         4.3.0
hpack                      4.1.0
huggingface-hub            0.35.3
humanfriendly              10.0
hyperframe                 6.1.0
idna                       3.10
imageio                    2.37.0
imageio-ffmpeg             0.6.0
importlib_metadata         8.7.0
Jinja2                     3.1.6
jsonschema                 4.25.1
jsonschema-specifications  2025.9.1
kiwisolver                 1.4.9
kornia                     0.8.1
kornia_rs                  0.1.9
lark                       1.3.0
Mako                       1.3.10
markdown-it-py             4.0.0
MarkupSafe                 3.0.3
matplotlib                 3.10.7
matrix-nio                 0.25.2
mdurl                      0.1.2
mpmath                     1.3.0
mss                        10.1.0
multidict                  6.6.4
networkx                   3.5
numpy                      2.2.6
onnxruntime                1.23.1
open_clip_torch            3.2.0
opencv-python              4.12.0.88
opencv-python-headless     4.12.0.88
packaging                  25.0
peft                       0.17.1
pillow                     11.3.0
pip                        25.2
propcache                  0.3.2
protobuf                   6.33.0
psutil                     7.1.0
pycparser                  2.23
pycryptodome               3.23.0
pydantic                   2.11.9
pydantic_core              2.33.2
pydantic-settings          2.11.0
pygit2                     1.18.2
PyGithub                   2.8.1
Pygments                   2.19.2
PyJWT                      2.10.1
PyNaCl                     1.6.0
pyparsing                  3.2.5
pyreadline3                3.5.4
python-dateutil            2.9.0.post0
python-dotenv              1.1.1
python-socks               2.7.2
PyYAML                     6.0.3
referencing                0.37.0
regex                      2025.9.18
requests                   2.32.5
rich                       14.2.0
rpds-py                    0.27.1
safetensors                0.6.2
sageattention              2.2.0+cu128torch2.8.0.post3
scipy                      1.16.2
sentencepiece              0.2.1
setuptools                 80.9.0
shellingham                1.5.4
six                        1.17.0
smmap                      5.0.2
soundfile                  0.13.1
spandrel                   0.4.1
SQLAlchemy                 2.0.43
sympy                      1.14.0
timm                       1.0.20
tokenizers                 0.22.1
toml                       0.10.2
torch                      2.8.0+cu129
torchaudio                 2.8.0+cu129
torchsde                   0.2.6
torchvision                0.23.0+cu129
tqdm                       4.67.1
trampoline                 0.1.2
transformers               4.56.2
triton-windows             3.4.0.post20
typer                      0.19.2
typing_extensions          4.15.0
typing-inspection          0.4.1
unpaddedbase64             2.1.0
urllib3                    2.5.0
uv                         0.9.3
wcwidth                    0.2.14
yarl                       1.20.1
zipp                       3.23.0
```

### Other

This is driving me insane, what can I do?
I am legit thinking a spyware or crypto that hides at every gen (by eating a bit of vram) could be there, but:
- doing a new comfy install
- changing browser.. etc
made believe it might not the case but who knows?
After all one of the custom nodes asked me to remove security (i mean the manager asked) for its installation, i did not listen and went installing it with git clone and git install -r req txt file, (ComfyUI-WanAnimatePreprocess) unlikely but who knows. I mean i removed it and removed the 2 libraries it installed, but maybe it did something else i did not see. The source seems reliable (kijai node I believe) so Idk...

I was intially thinking about changes in wanvideo wrapper (since I did git pulls trying to run the flash upscaler (latest 1 step workflow that upscales) and need his latest code, i had to make the custom node becomes git..table sicen it was only installed by manager initially) so I removed that ndoe later on when i discovede the workflow does not rely on it, still same problem.
I also wondered if it was a change on torchcompilemodelwanvideoV2 node (to adapt to latest torch versions) that broke something? Since I am reaching the limit torch._dynamo hit config.recompile_limit (64) or 96 faster whereas i was NEVER DOIN THAT 2-3 days ago with SAME WORKFLOW.
I want to FIX IT.
if a workflow WORKED IN THE PAST (2-3 days) I SHOULD BE ABLE TO MAKE IT WORK AGAIN right?
Thanks

**Comment by BestofthebestinAI** [comment]
Update:
My paranoia IS REAL!
The comfyUI zip release I downloaded 3-4 days ago (windows tell me latest modified is 12 oct) does NOT have this problem.
And I think I had done an update 3-4 days ago
Since then both updated version of that release, and another more recent release have these problems.
Something broke and I was only able to detect it because I tried a workflow that probably pushed my system to good vram quantity usage and the new commits made it somehow use a bit more causing the errors
Other people did not notice the issue because they had more vram than me (I am at 3090) and did not notice the increase in vram usage perhaps?
**Again i confirm that the problem does NOT HAPPEN if I use an older comfyUI releas**e!

**Comment by BestofthebestinAI** [comment]
Found the culprit:

![Image](https://github.com/user-attachments/assets/54d7dbe1-a273-40c1-854f-ac47ec25cdb4)



What can we do? https://github.com/comfyanonymous/ComfyUI/commit/3374e900d0f310100ebe54944175a36f287110cb
@comfyanonymous 
I dont want to have to use a version of Comfy where I need to modify commits I wish just to use all the updates, 
do you think this change is necessary? it is causing for me problems and OOM, this is how it goes:

<img width="898" height="430" alt="Image" src="https://github.com/user-attachments/assets/2f6424df-aa92-4b1d-a4f2-108eaec17850" />

Edit: might be another problem after all. Still investigating

**Comment by BestofthebestinAI** [comment]
Last report on this:
Faster cancellation might be okay after all.
Only problem it might have (that you want to check again) is:
It cancels the calculations even before the first ksampler runs (high noise wan model/lora), which itself would run normally without any error up until the second sampler (LOW noise) would cause the OOM indeed, so the faster cancellation did indeed predict the high vram usage (overall) and cancelled the workflow immediately (if that's what it does although not sure what that commit change does I am assuming from its name).

So the reason my workflow (it comes from an output i produced myself = I RUN IT in the past (3 days ago)), can no longer run for whatever reason, **remains unkown** despite having:
- Restarted comfy, pc, browser change.
- Deleted triton files in user in appdata temp and most of temp actually
- tried with a 6oct comfy release, a 12 oct comfy zip release, and the one from 3 days ago (14 oct?), all with torch 2.8, in the end it seems something is wrong in my computer, something broke or something changed, it does not have to do with the commits like I announced. Remains to be found and confirmed.

Faster cancellation could break a workflow that has double pass or more, in the case where the last ksampler fail but first one succeed, so the only thing I could report reliably about it is that it does not allow first ksampler from working if last ones would cauze an OOM. (This can be a problem for people creating workflows, they think that their first ksampler has a poblem whereas it is the one that comes after. **In my case: "high ksampler"  worked, low ksampler failed, but faster cancellation cancelled the whole workflow (both ksampler did not run) before any ksampler run**).

I refuse to try torch 2.9 until I find what's the reason MY workflow stopped working, after knowing for a fact that that workflow worked 2-3 days ago.

Other culprits/causes I was not able to investigate are these 2 custom nodes that got update during the 3-4 days ago:

<img width="1360" height="329" alt="Image" src="https://github.com/user-attachments/assets/798987c6-cece-4164-a89f-cd0f881c4e39" />
Could try to investigate there.

My own machine cuda stuff affecting the comfy python embed env somehow (did not really change anything as far as I remember), my own machine visual studio stuff (unlikely, did not touch and I don't think I need the Cl.exe thing, triton and sage is already ready to use etc)

One last thing to check is to solve the situations I have with windows update being blocked (because I changed the boot, now the update seems to fail and cancel), maybe windows activated some vram to.. handle all those files in the background? Likely or unlikely? Well I am considering EVERYTHING, I need to know what is the reason.

What else to investigate? I could not say (know).

**Comment by Streety111** [comment]
Нет, чувак, у меня точно такая же проблема. 
Я откатился на 0.3.64 версию и всё стало хорошо. 
WorkFlow, где проблему можно повторить: https://civitai.com/models/1866565/wan22-continuous-generation-subgraphs?modelVersionId=2166114 
(при чистой I2V (wan2.2) генерации, даже без лоры, на safetensors моделях, не GGUF)
В ООМ уходит стабильно при второй генерации тремя семплерами (то есть вторая 5-секундная часть)
Ubuntu 24.04.3 CUDA 13.0 PyTorch 2.9.0 + CU130 (также проблема была и на +CU128, я тоже перебирал варианты, только через 3-4 часа понял, что это из-за обновления ComfyUI)

**Comment by tallestbydesign-ui** [comment]
I have the exact same problem, an inocuous update to stable branch brought me 0.3.65 and since then basic KSamplers with Wan give OOM after nearly crashing the computer trying to squeeze RAM out of it. What i noticied is that EVERYTIME it wsa about to crash (not _exactly_ at the same point btw, but close), it started filling RAM like crazy, leaving VRAM alone, and started to fill PAGEFILE like crazy too, flooding the pagefile disk until the whole system came to a halt, and then same "torch.OutOfMemoryError: Allocation on device / Got an OOM, unloading all loaded models." error as OP. 

Spent hours trying to debug it because it made no sense that a perfectly good WF that has crazy optimizations suddenly stops working for the exact same reasons as posted by OP. And no, I haven't updated torch to 2.9 because i HAVE TO use Sageattention etc, and right now anything above 2.7.1+128 screws my WFs.

Ryzen 5 / 32GB RAM / 4070 SUPER 12GB / torch2.7.1 + cu128

EDIT : Oh shoot, @BestofthebestinAI you're right there was a windows update in the meantime.

**Comment by BestofthebestinAI** [comment]
Spent hours trying to debug it because it made no sense that a perfectly good WF that has crazy optimizations suddenly stops working for the exact same reasons as posted by OP
Literally same though I just want a previousely perfectly working workflow... to continue working! There is no reason for it to stop working!
As for the windows update, update did not go through (some some other related reason) so I was thinking the files in the backend and windows was using vram in some strange way, but I am assuming your own update did actually go, maybe its irrelevant.
(Unless forced some backend program that is altering our machines but unlikely to cause such OOMs)
edit: what custom nodes are you using @tallestbydesign-ui ? And are you using any of the ones I shown?

**Comment by tallestbydesign-ui** [comment]
>  edit: what custom nodes are you using [@tallestbydesign-ui](https://github.com/tallestbydesign-ui) ? And are you using any of the ones I shown?

I use all those shown except FantasyTalking. I remember there was a GGUF update very recently - i'll try to roll it back and report.
I've rolled back to Comfy 0.3.64 and the pagefile filling / 100% usage on pagefile disk is still absolutely crippling. Will roll back things (nodes and windows updates) until i find out what's up, and report back.

EDIT : 2025 10 17 
Switched back to 0.3.64, workflow runs smoothly up to a point then OOM when it shouldn't because the stage it's running at that point has already been run 5 times flawlessly. So to sum up what i know as of know : 

0.3.62 and earlier : running fine until the end (for hours)
0.3.64 : workflow runs but is stopped at a late stage point which doesnt make sense because load was already that high before in the WF
0.3.65 : worflow doesn't even pass the first "stage" of sampling when OOM appears. 

For reference, the worflow uses : 
- Wan2.2
- Torchcompile (defaults)
- Blockswap (all 40 blocks, non blocking)
- SageAttention (fp16 CUDA)
- NAG
- Lightx2v LORAs (but irrelevant i think, OOM on 0.3.65 happens on lora-less stage)

Currently downversioning the custom nodes to identify the culprit, staying in 0.3.64. (That will take a while)

Results : downgrading the recently updated nodes had no effect. Will try downgrading comfy to 0.3.62

**Comment by BestofthebestinAI** [comment]
Very well.
Here is a proof that Faster Cancellation commit (3374e900d0f310100ebe54944175a36f287110cb) alters my inference, It gets to OOM faster:
https://mega.nz/folder/cnFVibgb#4_wdmdck4wMZ_Z5nO0yN5A
(First sampler is sometimes run successfully if faster cancellation feature is not there for example at (51696e3fdcdfad657cb15854345fbcbbe70eef8d)). But if we are at (3374e900d0f310100ebe54944175a36f287110cb) then OOM happens before both ksampler happen (90% of the times))

___
___
Summary:

0:14 checking out the commit Faster Cancellation (3374e900d0f310100ebe54944175a36f287110cb)
0:47 pressing the first RUN (with faster cancellation as an available feature)
2:15 OOM in 87.46 seconds
___
2:33 checked out to a commit just before introduction of Faster Cancellation (51696e3fdcdfad657cb15854345fbcbbe70eef8d)
2:33 SECOND RUN (no faster cancellation feature), 
4:50 still no OOM (after 150 sec+)
___
5:15 checked back to the faster cancellation commit
5:33 THIRD RUN ( faster cancellation as an available feature),
6:43 OOM in 68.23 seconds
___
7:15 checking out the commit just before faster cancellation
7:39 FOURTH RUN (no faster cancellation feature),
10:42 sill no OOM (3 min or 180sec+)
Conclusions: Faster Cancelation make the system OOM faster for some reason even though it should not.

**Comment by BestofthebestinAI** [comment]
LLMs said the following, perhaps this explains what happened:

`The recent changes made to comfy/ops.py to enable more responsive process interruption have an unforeseen but critical side effect that makes the system incompatible with torch.compile. While the goal of instantaneous interruption is valuable, the current implementation forces PyTorch's compiler into a "recompilation storm." The low-level checks, particularly the dynamic logic that inspects layer names as strings, prevent the compiler from creating a single, efficient computational graph. Instead, it is forced to recompile a new, tiny graph for nearly every layer in the model. This repeated recompilation process is extremely memory-intensive, leading directly to the OutOfMemoryError crashes that users are experiencing when compilation is enabled. A more compiler-friendly "hybrid" approach, which moves the interrupt check to a higher level (e.g., between the major blocks in the model's main forward method), would still provide excellent responsiveness without breaking these crucial performance optimizations, offering a more stable solution for all users.`
Anyway here are some changes that can work, modify (ComfyUI\comfy\ldm\wan\model.py) and revent the ops.py changes

[model.py](https://github.com/user-attachments/files/22979843/model.py)
Summary:  Adding this line "comfy.model_management.throw_exception_if_processing_interrupted()" to every: "for i, block in enumerate(self.blocks):". (and not forgetting  the import model management)

___
This change keeps some cancellation feature, but no longer produce OOMs as before.
BUT, I still am not able to run a workflow I was able to run in the past despite it all, I mean my change made it so faster cancellation feature does not produce OOM (regardless of it cancel button being pushed) but the initial problem for me (a workflow worked and is no longer working) remains.

**Comment by rattus128** [comment]
@BestofthebestinAI do you have the torch compiler in your workflow? I had a look at your video and I cant see it in play. Its usually a custom model-in-model-out node and that above theory from your LLM would only matter if that was setup.

If you want to continue debugging, you can try the Cuda memory tracer. Add these two before and after your workflow.

```
+        torch.cuda.memory._record_memory_history()
+        torch.cuda.memory._dump_snapshot("memory_trace.pickle")
```

You need to start with the --disable-cuda-malloc option.

Id also suggest start with --novram. This will very likely fix the problem (and you may run slower), but you should then be able to see your VRAM traces both before and after the change and see a peak height difference. memory_trace.pickle has an online visualizer here:

https://docs.pytorch.org/memory_viz

**Comment by BestofthebestinAI** [comment]
@rattus128  I am noting:
So I should add (torch.cuda.memory._record_memory_history()) something in the code or is that in the terminal before launching the bat that starts comfy? (like when we declare in the termianl some torch env to see logs?)
Then at the end: (torch.cuda.memory._dump_snapshot("memory_trace.pickle"))?
Thanks.
You can see the full workflow in the image shared above, does it still have the metadata?
Otherwise i decided to comment out all "run_every_op()" calls in the ops.py file
and git pulled some latest kj nodes changes and turned off a new parameter:

<img width="577" height="414" alt="Image" src="https://github.com/user-attachments/assets/ae51a860-046e-46ea-af0f-490e2e113416" />

As per kijai suggestion.
added: 

<img width="549" height="291" alt="Image" src="https://github.com/user-attachments/assets/98d3c2b9-1892-432a-bdcc-8dfa44e4ebf0" />
and ofc just decided to upgrade to torch 2.9
I am not sure if those changes would have worked if I had stayed in 2.8, I wish I was able to solve it whiel staying in 2.8 just to be sure we are not missing anything. Might come back debugging it wihtin 2.8 just to see what was happening besides the ops.py calls.

**Comment by rattus128** [comment]
Those lines can be added to the code to get an over time VRAM usage trace which is great for tracking VRAM leaks. The first line goes where you want recording to start and the second where you want it to stop.

**Comment by BestofthebestinAI** [comment]
> Those lines can be added to the code to get an over time VRAM usage trace which is great for tracking VRAM leaks. The first line goes where you want recording to start and the second where you want it to stop.

There are so many py files, I suppose I could add them to the.. sampler.. or is it to the torch inductor node (kj custom nodes) py file or all  of the relevant files. such as model.py under wan folder or something.
Thank you I shall try to  use it in the future

**Comment by alperktt** [comment]
So what's the fix?

**Comment by comfyanonymous** [comment]
The fix is either to go back to the last stable tag or update to the latest git.

**Comment by Streety111** [comment]
У меня заработало, спасибо.
