### ISSUE TITLE
RTX 5080 CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by piquet10** [comfyanonymous/ComfyUI#10382]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. 

Hello how can I fix this?

### Actual Behavior

<img width="677" height="339" alt="Image" src="https://github.com/user-attachments/assets/6f40ce81-26ee-40ef-97b3-98cf89d6cd24" />

### Steps to Reproduce

<img width="2050" height="819" alt="Image" src="https://github.com/user-attachments/assets/81675847-7569-4fb8-b749-e5e3832d9fbc" />

### Debug Logs

```powershell
CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by tcox1969** [comment]
Can confirm ANY RTX 50x0 model shows this error when used with workflows whereas RTX 40x0 and 30x0 works fine at this point.

**Comment by Yashground** [comment]
I am trying on RTX 5090 model and I get same error as yours

**Comment by Kyoukobu** [comment]
same for me( on 40* and 30* works fine

**Comment by lucianosb** [comment]
I'm using comfy installed via Comfy-CLI and I fixed it by following this tutorial: 

https://assuntonerd.com.br/2025/08/28/como-resolver-rtx-5070-cuda-error-no-kernel-image-is-available-for-execution-on-the-device/

I believe stable versions of [pytorch for CUDA 13 ](https://pytorch.org/get-started/locally/) might also work.

I can now use ComfyUI on RTX 5070 TI. It might work on 5080 as well, since they have the same Blackwell architecture.
