### ISSUE TITLE
1080ti error

### ISSUE THREAD

**Issue by Omkara1982** [comfyanonymous/ComfyUI#10400]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

CLIPTextEncode
CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Logs

```powershell

```

**Comment by Mescalamba** [comment]
In case you are not using..

# CUDA 12.6
pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu126

Try it.

I have similar GPU and torch 2.8 gave me quite a bit of issues. Also support for 10xx is I think dropping from newer CUDA, or at least 12.6 is only that works reliable for me.

Current ComfyUI works for me good, but it needs that torch 2.7.1 and CUDA 12.6 mix. Dont think its ComfyUI issue. I would say recent torch versions are ... well, not great. Guess they started vibe coding it.

**Comment by Frediloker** [comment]
reinstall the video card driver
