### ISSUE TITLE
Fedora 43 - After system update - Isssues with installation

### ISSUE THREAD

**Issue by somapatrik** [comfyanonymous/ComfyUI#10632]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Run "comfy launch" command

### Actual Behavior

Issues with python version 3.14 . I gave up any attempts to repair it and I just tried to install new comfyui following website instructions. However it was not working. I created virtual enviroment using python 3.14 and after running the pip install - r requirements.txt I still got errors on missing modules.

I had to install missing modules manually as I was getting these error. At the end I had to also install comfyui-frontend-package, then I got it to work.

### Steps to Reproduce

Update Python from 3.12 to 3.14

### Debug Logs

```powershell
pip install -r requirements.txt 
Collecting comfyui-frontend-package==1.28.8 (from -r requirements.txt (line 1))
  Downloading comfyui_frontend_package-1.28.8-py3-none-any.whl.metadata (117 bytes)
Collecting comfyui-workflow-templates==0.2.4 (from -r requirements.txt (line 2))
  Downloading comfyui_workflow_templates-0.2.4-py3-none-any.whl.metadata (55 kB)
Collecting comfyui-embedded-docs==0.3.1 (from -r requirements.txt (line 3))
  Downloading comfyui_embedded_docs-0.3.1-py3-none-any.whl.metadata (2.9 kB)
Collecting torch (from -r requirements.txt (line 4))
  Downloading torch-2.9.0-cp314-cp314-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting torchsde (from -r requirements.txt (line 5))
  Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Collecting torchvision (from -r requirements.txt (line 6))
  Downloading torchvision-0.24.0-cp314-cp314-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Collecting torchaudio (from -r requirements.txt (line 7))
  Downloading torchaudio-2.9.0-cp314-cp314-manylinux_2_28_x86_64.whl.metadata (6.7 kB)
Collecting numpy>=1.25.0 (from -r requirements.txt (line 8))
  Downloading numpy-2.3.4-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting einops (from -r requirements.txt (line 9))
  Using cached einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Collecting transformers>=4.37.2 (from -r requirements.txt (line 10))
  Downloading transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Collecting tokenizers>=0.13.3 (from -r requirements.txt (line 11))
  Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting sentencepiece (from -r requirements.txt (line 12))
  Downloading sentencepiece-0.2.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting safetensors>=0.4.2 (from -r requirements.txt (line 13))
  Using cached safetensors-0.6.2-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting aiohttp>=3.11.8 (from -r requirements.txt (line 14))
  Downloading aiohttp-3.13.2-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting yarl>=1.18.0 (from -r requirements.txt (line 15))
  Downloading yarl-1.22.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (75 kB)
Collecting pyyaml (from -r requirements.txt (line 16))
  Using cached pyyaml-6.0.3-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting Pillow (from -r requirements.txt (line 17))
  Downloading pillow-12.0.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting scipy (from -r requirements.txt (line 18))
  Downloading scipy-1.16.3-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (62 kB)
Collecting tqdm (from -r requirements.txt (line 19))
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting psutil (from -r requirements.txt (line 20))
  Using cached psutil-7.1.3-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting alembic (from -r requirements.txt (line 21))
  Downloading alembic-1.17.1-py3-none-any.whl.metadata (7.2 kB)
Collecting SQLAlchemy (from -r requirements.txt (line 22))
  Downloading sqlalchemy-2.0.44-py3-none-any.whl.metadata (9.5 kB)
Collecting av>=14.2.0 (from -r requirements.txt (line 23))
  Downloading av-16.0.1-cp314-cp314-manylinux_2_28_x86_64.whl.metadata (4.6 kB)
Collecting kornia>=0.7.1 (from -r requirements.txt (line 26))
  Using cached kornia-0.8.1-py2.py3-none-any.whl.metadata (17 kB)
Collecting spandrel (from -r requirements.txt (line 27))
  Using cached spandrel-0.4.1-py3-none-any.whl.metadata (15 kB)
Collecting pydantic~=2.0 (from -r requirements.txt (line 28))
  Downloading pydantic-2.12.3-py3-none-any.whl.metadata (87 kB)
Collecting pydantic-settings~=2.0 (from -r requirements.txt (line 29))
  Downloading pydantic_settings-2.11.0-py3-none-any.whl.metadata (3.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic~=2.0->-r requirements.txt (line 28))
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.4 (from pydantic~=2.0->-r requirements.txt (line 28))
  Downloading pydantic_core-2.41.4-cp314-cp314-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typing-extensions>=4.14.1 (from pydantic~=2.0->-r requirements.txt (line 28))
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic~=2.0->-r requirements.txt (line 28))
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings~=2.0->-r requirements.txt (line 29))
  Downloading python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Collecting filelock (from torch->-r requirements.txt (line 4))
  Downloading filelock-3.20.0-py3-none-any.whl.metadata (2.1 kB)
Collecting setuptools (from torch->-r requirements.txt (line 4))
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch->-r requirements.txt (line 4))
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch->-r requirements.txt (line 4))
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch->-r requirements.txt (line 4))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch->-r requirements.txt (line 4))
  Downloading fsspec-2025.10.0-py3-none-any.whl.metadata (10 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch->-r requirements.txt (line 4))
  Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.3.20 (from torch->-r requirements.txt (line 4))
  Downloading nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch->-r requirements.txt (line 4))
  Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.5.0 (from torch->-r requirements.txt (line 4))
  Downloading triton-3.5.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting trampoline>=0.1.2 (from torchsde->-r requirements.txt (line 5))
  Using cached trampoline-0.1.2-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers>=4.37.2->-r requirements.txt (line 10))
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Collecting packaging>=20.0 (from transformers>=4.37.2->-r requirements.txt (line 10))
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting regex!=2019.12.17 (from transformers>=4.37.2->-r requirements.txt (line 10))
  Downloading regex-2025.11.3-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting requests (from transformers>=4.37.2->-r requirements.txt (line 10))
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.34.0->transformers>=4.37.2->-r requirements.txt (line 10))
  Downloading hf_xet-1.2.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Downloading frozenlist-1.8.0-cp314-cp314-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Downloading multidict-6.7.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Downloading propcache-0.4.1-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting idna>=2.0 (from yarl>=1.18.0->-r requirements.txt (line 15))
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting Mako (from alembic->-r requirements.txt (line 21))
  Using cached mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet>=1 (from SQLAlchemy->-r requirements.txt (line 22))
  Downloading greenlet-3.2.4-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Collecting kornia_rs>=0.1.9 (from kornia>=0.7.1->-r requirements.txt (line 26))
  Downloading kornia_rs-0.1.9.tar.gz (108 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      Python reports SOABI: cpython-314-x86_64-linux-gnu
      Computed rustc target triple: x86_64-unknown-linux-gnu
      Installation directory: /home/somachr/.cache/puccinialin
      Downloading rustup-init from https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
      Checking for Rust toolchain....
      Rust not found, installing into a temporary directory
      
      Downloading rustup-init:   0%|          | 0.00/20.9M [00:00<?, ?B/s]
      Downloading rustup-init:   6%|▌         | 1.30M/20.9M [00:00<00:01, 12.9MB/s]
      Downloading rustup-init:  17%|█▋        | 3.50M/20.9M [00:00<00:00, 18.2MB/s]
      Downloading rustup-init:  32%|███▏      | 6.78M/20.9M [00:00<00:00, 24.8MB/s]
      Downloading rustup-init:  46%|████▌     | 9.51M/20.9M [00:00<00:00, 25.8MB/s]
      Downloading rustup-init:  59%|█████▊    | 12.2M/20.9M [00:00<00:00, 26.3MB/s]
      Downloading rustup-init:  72%|███████▏  | 15.0M/20.9M [00:00<00:00, 26.7MB/s]
      Downloading rustup-init:  85%|████████▍ | 17.7M/20.9M [00:00<00:00, 26.9MB/s]
      Downloading rustup-init:  98%|█████████▊| 20.5M/20.9M [00:00<00:00, 27.0MB/s]
      Downloading rustup-init: 100%|██████████| 20.9M/20.9M [00:00<00:00, 25.5MB/s]
      Installing rust to /home/somachr/.cache/puccinialin/rustup
      info: profile set to 'minimal'
      info: default host triple is x86_64-unknown-linux-gnu
      info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
      info: latest update on 2025-10-30, rust version 1.91.0 (f8297e351 2025-10-28)
      info: downloading component 'cargo'
      info: downloading component 'rust-std'
      info: downloading component 'rustc'
      info: installing component 'cargo'
      info: installing component 'rust-std'
      info: installing component 'rustc'
      info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
      Checking if cargo is installed
      cargo 1.91.0 (ea2d97820 2025-10-10)
      Python reports SOABI: cpython-314-x86_64-linux-gnu
      Computed rustc target triple: x86_64-unknown-linux-gnu
      Installation directory: /home/somachr/.cache/puccinialin
      Rustup already downloaded
      Installing rust to /home/somachr/.cache/puccinialin/rustup
      warn: It looks like you have an existing rustup settings file at:
      warn: /home/somachr/.rustup/settings.toml
      warn: Rustup will install the default toolchain as specified in the settings file,
      warn: instead of the one inferred from the default host triple.
      info: profile set to 'minimal'
      info: default host triple is x86_64-unknown-linux-gnu
      warn: Updating existing toolchain, profile choice will be ignored
      info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
      info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
      Checking if cargo is installed
      cargo 1.91.0 (ea2d97820 2025-10-10)
      error: failed to parse manifest at `/tmp/pip-install-u2i7lxzh/kornia-rs_b61664c0d4ca441981e249471a9000a6/kornia-py/Cargo.toml`
      
      Caused by:
        can't find library `kornia_rs`, rename file to `src/lib.rs` or specify lib.path
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-bxr00qo8', '--interpreter', '/home/somachr/ComfyUI/venv/bin/python3']' returned non-zero exit status 1.
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-bxr00qo8 --interpreter /home/somachr/ComfyUI/venv/bin/python3`
      Rust not found, installing into a temporary directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(venv) somachr@Victus:~/ComfyUI$ python main.py 
Traceback (most recent call last):
  File "/home/somachr/ComfyUI/main.py", line 11, in <module>
    import utils.extra_config
  File "/home/somachr/ComfyUI/utils/extra_config.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by somapatrik** [comment]
I am no expert in linux or python, pip....But I think method 1 from https://comfyui-wiki.com/en/install/install-comfyui/install-comfyui-on-linux#comments is not working, I had to do method 2 and install some modules manually as stated above. If this is not an issue to be placed here, I would understand.

Log from above is only partial, but you can see that I ran pip install -r requirements.txt and got ModuleNotFoundError: No module named 'yaml' after.

**Comment by boyan-orion** [comment]
@somapatrik  It's mentioned in the readme that kornia_rs is not compatible with python 3.14, so you should comment it in the requirements.txt. 

Use python 3.12 or 3.13 inside a pyenv virtual env and problem solved.

**Comment by somapatrik** [comment]
I tried again with the 3.12 venv and got no problem...Not sure why i got issues before. Closing.
