### ISSUE TITLE
FlashVsr. LoadWanVideoT5TextEncoder Error while deserializing header: incomplete metadata, file not fully covered

### ISSUE THREAD

**Issue by Dkop123** [comfyanonymous/ComfyUI#10675]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

**LoadWanVideoT5TextEncoder
Error while deserializing header: incomplete metadata, file not fully covered**

`
# ComfyUI Error Report
## Error Details
- **Node ID:** 139
- **Node Type:** LoadWanVideoT5TextEncoder
- **Exception Type:** safetensors_rust.SafetensorError
- **Exception Message:** Error while deserializing header: incomplete metadata, file not fully covered

## Stack Trace
```
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e

  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** 0.3.68
- **Arguments:** C:\Stability matrix\Packages\ComfyUI\main.py --normalvram --preview-method auto --use-pytorch-cross-attention
- **OS:** nt
- **Python Version:** 3.12.10 (main, May 30 2025, 05:39:07) [MSC v.1943 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.9.0+cu128
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1060 6GB : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 6442188800
  - **VRAM Free:** 5449449472
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2025-11-07T15:27:09.979408 - 
2025-11-07T15:27:09.979408 - ** ComfyUI startup time:2025-11-07T15:27:09.979408 -  2025-11-07T15:27:09.979408 - 2025-11-07 15:27:09.9792025-11-07T15:27:09.979408 - 
2025-11-07T15:27:09.979408 - ** Platform:2025-11-07T15:27:09.979408 -  2025-11-07T15:27:09.979408 - Windows2025-11-07T15:27:09.979408 - 
2025-11-07T15:27:09.979408 - ** Python version:2025-11-07T15:27:09.979408 -  2025-11-07T15:27:09.979408 - 3.12.10 (main, May 30 2025, 05:39:07) [MSC v.1943 64 bit (AMD64)]2025-11-07T15:27:09.980407 - 
2025-11-07T15:27:09.980407 - ** Python executable:2025-11-07T15:27:09.980407 -  2025-11-07T15:27:09.980407 - C:\Stability matrix\Packages\ComfyUI\venv\Scripts\python.exe2025-11-07T15:27:09.980407 - 
2025-11-07T15:27:09.980407 - ** ComfyUI Path:2025-11-07T15:27:09.980407 -  2025-11-07T15:27:09.980407 - C:\Stability matrix\Packages\ComfyUI2025-11-07T15:27:09.980407 - 
2025-11-07T15:27:09.980407 - ** ComfyUI Base Folder Path:2025-11-07T15:27:09.980407 -  2025-11-07T15:27:09.980407 - C:\Stability matrix\Packages\ComfyUI2025-11-07T15:27:09.980407 - 
2025-11-07T15:27:09.980407 - ** User directory:2025-11-07T15:27:09.980407 -  2025-11-07T15:27:09.980407 - C:\Stability Matrix\Packages\ComfyUI\user2025-11-07T15:27:09.980407 - 
2025-11-07T15:27:09.981407 - ** ComfyUI-Manager config path:2025-11-07T15:27:09.981407 -  2025-11-07T15:27:09.981407 - C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-11-07T15:27:09.981407 - 
2025-11-07T15:27:09.981407 - ** Log path:2025-11-07T15:27:09.981407 -  2025-11-07T15:27:09.981407 - C:\Stability Matrix\Packages\ComfyUI\user\comfyui.log2025-11-07T15:27:09.981407 - 
2025-11-07T15:27:11.978273 - 
Prestartup times for custom nodes:
2025-11-07T15:27:11.978273 -    8.1 seconds: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Manager-main
2025-11-07T15:27:11.978273 - 
2025-11-07T15:27:17.145825 - Checkpoint files will always be loaded safely.
2025-11-07T15:27:17.272039 - C:\Stability matrix\Packages\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py:283: UserWarning: 
    Found GPU0 NVIDIA GeForce GTX 1060 6GB which is of cuda capability 6.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (7.0) - (12.0)
    
  warnings.warn(
2025-11-07T15:27:17.273039 - C:\Stability matrix\Packages\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py:304: UserWarning: 
    Please install PyTorch with a following CUDA
    configurations:  12.6 following instructions at
    https://pytorch.org/get-started/locally/
    
  warnings.warn(matched_cuda_warn.format(matched_arches))
2025-11-07T15:27:17.274038 - C:\Stability matrix\Packages\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py:326: UserWarning: 
NVIDIA GeForce GTX 1060 6GB with CUDA capability sm_61 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.
If you want to use the NVIDIA GeForce GTX 1060 6GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
2025-11-07T15:27:17.383997 - Total VRAM 6144 MB, total RAM 8153 MB
2025-11-07T15:27:17.383997 - pytorch version: 2.9.0+cu128
2025-11-07T15:27:17.384982 - Set vram state to: NORMAL_VRAM
2025-11-07T15:27:17.384982 - Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : cudaMallocAsync
2025-11-07T15:27:17.463997 - working around nvidia conv3d memory bug.
2025-11-07T15:27:20.502861 - Using pytorch attention
2025-11-07T15:27:29.358089 - Python version: 3.12.10 (main, May 30 2025, 05:39:07) [MSC v.1943 64 bit (AMD64)]
2025-11-07T15:27:29.358089 - ComfyUI version: 0.3.68
2025-11-07T15:27:29.396624 - ComfyUI frontend version: 1.28.8
2025-11-07T15:27:29.400622 - [Prompt Server] web root: C:\Stability matrix\Packages\ComfyUI\venv\Lib\site-packages\comfyui_frontend_package\static
2025-11-07T15:27:35.857210 - ### Loading: ComfyUI-Manager (V3.37)
2025-11-07T15:27:35.858204 - [ComfyUI-Manager] network_mode: public
2025-11-07T15:27:35.858204 - [ComfyUI-Manager] Since --preview-method is set, ComfyUI-Manager's preview method feature will be ignored.
2025-11-07T15:27:36.143303 - ### ComfyUI Revision: 4177 [265adad8] *DETACHED | Released on '2025-11-04'
2025-11-07T15:27:36.782323 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-11-07T15:27:36.787321 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-11-07T15:27:36.990288 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-11-07T15:27:37.197268 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-11-07T15:27:37.363698 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-11-07T15:27:39.541069 - Warning: Could not load sageattention: No module named 'sageattention'
2025-11-07T15:27:39.541069 - sageattention package is not installed, sageattention will not be available
2025-11-07T15:27:40.051823 - WanVideoWrapper WARNING: FantasyPortrait nodes not available due to error in importing them: No module named 'onnx'
2025-11-07T15:27:40.102792 - 
Import times for custom nodes:
2025-11-07T15:27:40.102792 -    0.0 seconds: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\websocket_image_save.py
2025-11-07T15:27:40.102792 -    0.3 seconds: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
2025-11-07T15:27:40.102792 -    0.6 seconds: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Manager-main
2025-11-07T15:27:40.102792 -    0.9 seconds: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2025-11-07T15:27:40.102792 -    2.7 seconds: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
2025-11-07T15:27:40.102792 - 
2025-11-07T15:27:40.839541 - Context impl SQLiteImpl.
2025-11-07T15:27:40.839541 - Will assume non-transactional DDL.
2025-11-07T15:27:40.841539 - No target revision found.
2025-11-07T15:27:40.883032 - Starting server

2025-11-07T15:27:40.884015 - To see the GUI go to: http://127.0.0.1:8188
2025-11-07T15:27:42.119770 - FETCH ComfyRegistry Data: 5/1042025-11-07T15:27:42.119770 - 
2025-11-07T15:27:45.845391 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-07T15:27:45.845391 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-07T15:27:45.878013 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/widgetInputs.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-07T15:27:46.477295 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-07T15:27:46.485292 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-07T15:27:46.862814 - FETCH ComfyRegistry Data: 10/1042025-11-07T15:27:46.862814 - 
2025-11-07T15:27:51.645554 - FETCH ComfyRegistry Data: 15/1042025-11-07T15:27:51.645554 - 
2025-11-07T15:27:56.410613 - FETCH ComfyRegistry Data: 20/1042025-11-07T15:27:56.410613 - 
2025-11-07T15:28:01.342153 - FETCH ComfyRegistry Data: 25/1042025-11-07T15:28:01.342153 - 
2025-11-07T15:28:06.110119 - FETCH ComfyRegistry Data: 30/1042025-11-07T15:28:06.111121 - 
2025-11-07T15:28:10.877817 - FETCH ComfyRegistry Data: 35/1042025-11-07T15:28:10.877817 - 
2025-11-07T15:28:15.635649 - FETCH ComfyRegistry Data: 40/1042025-11-07T15:28:15.635649 - 
2025-11-07T15:28:20.583883 - FETCH ComfyRegistry Data: 45/1042025-11-07T15:28:20.583883 - 
2025-11-07T15:28:25.322603 - FETCH ComfyRegistry Data: 50/1042025-11-07T15:28:25.322603 - 
2025-11-07T15:28:27.139597 - got prompt
2025-11-07T15:28:27.686855 - [VideoHelperSuite] - [0;33mWARNING[0m - Failed to calculate available memory. Memory load limit has been disabled
2025-11-07T15:28:29.510063 - CUDA Compute Capability: 6.1
2025-11-07T15:28:29.510063 - Loading extra model: 2025-11-07T15:28:29.510063 -  2025-11-07T15:28:29.510063 - C:\Stability matrix\Models\DiffusionModels\Wan2_1_FlashVSR_LQ_proj_model_bf16.safetensors2025-11-07T15:28:29.510063 - 
2025-11-07T15:28:29.511063 - Detected model in_channels: 16
2025-11-07T15:28:29.511063 - Model cross attention type: t2v, num_heads: 12, num_layers: 30
2025-11-07T15:28:29.512062 - Model variant detected: 1_3B
2025-11-07T15:28:29.715192 - FlashVSR model detected, patching model...
2025-11-07T15:28:30.578825 - FETCH ComfyRegistry Data: 55/1042025-11-07T15:28:30.578825 - 
2025-11-07T15:28:31.966986 - model_type FLOW
2025-11-07T15:28:32.127168 - !!! Exception during processing !!! Error while deserializing header: incomplete metadata, file not fully covered
2025-11-07T15:28:32.170352 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered

2025-11-07T15:28:32.173554 - Prompt executed in 5.01 seconds
2025-11-07T15:28:35.692670 - FETCH ComfyRegistry Data: 60/1042025-11-07T15:28:35.692670 - 
2025-11-07T15:28:41.158031 - FETCH ComfyRegistry Data: 65/1042025-11-07T15:28:41.158031 - 
2025-11-07T15:28:45.985288 - FETCH ComfyRegistry Data: 70/1042025-11-07T15:28:45.985288 - 
2025-11-07T15:28:50.809598 - FETCH ComfyRegistry Data: 75/1042025-11-07T15:28:50.809598 - 
2025-11-07T15:28:55.612830 - FETCH ComfyRegistry Data: 80/1042025-11-07T15:28:55.612830 - 
2025-11-07T15:29:00.473026 - FETCH ComfyRegistry Data: 85/1042025-11-07T15:29:00.473026 - 
2025-11-07T15:29:06.479594 - FETCH ComfyRegistry Data: 90/1042025-11-07T15:29:06.479594 - 
2025-11-07T15:29:11.319632 - FETCH ComfyRegistry Data: 95/1042025-11-07T15:29:11.319748 - 
2025-11-07T15:29:16.170088 - FETCH ComfyRegistry Data: 100/1042025-11-07T15:29:16.170088 - 
2025-11-07T15:29:20.514336 - FETCH ComfyRegistry Data [DONE]2025-11-07T15:29:20.514336 - 
2025-11-07T15:29:20.839796 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-11-07T15:29:20.883269 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-11-07T15:29:20.883269 - 2025-11-07T15:29:21.392360 -  [DONE]2025-11-07T15:29:21.392360 - 
2025-11-07T15:29:21.544856 - [ComfyUI-Manager] All startup tasks have been completed.
2025-11-07T15:30:44.629398 - got prompt
2025-11-07T15:30:45.193087 - !!! Exception during processing !!! Error while deserializing header: incomplete metadata, file not fully covered
2025-11-07T15:30:45.197086 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered

2025-11-07T15:30:45.217368 - Prompt executed in 0.56 seconds
2025-11-07T15:30:47.969481 - got prompt
2025-11-07T15:30:48.263500 - !!! Exception during processing !!! Error while deserializing header: incomplete metadata, file not fully covered
2025-11-07T15:30:48.274488 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered

2025-11-07T15:30:48.284474 - Prompt executed in 0.30 seconds
2025-11-07T15:30:51.938794 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-11-07T15:30:51.938794 - 
2025-11-07T15:30:52.196459 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1514988643_custom-node-list.json2025-11-07T15:30:52.196459 - 2025-11-07T15:30:52.231478 -  [DONE]2025-11-07T15:30:52.231478 - 
2025-11-07T15:30:52.358394 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\746607195_github-stats.json2025-11-07T15:30:52.358394 - 2025-11-07T15:30:52.386143 -  [DONE]2025-11-07T15:30:52.386143 - 
2025-11-07T15:30:52.391003 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\832903789_extras.json2025-11-07T15:30:52.391003 - 2025-11-07T15:30:52.402289 -  [DONE]2025-11-07T15:30:52.402289 - 
2025-11-07T15:30:52.577366 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1742899825_extension-node-map.json2025-11-07T15:30:52.577366 - 2025-11-07T15:30:52.621168 -  [DONE]2025-11-07T15:30:52.621168 - 
2025-11-07T15:30:57.753297 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-11-07T15:30:57.753297 - 
2025-11-07T15:30:57.873557 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1514988643_custom-node-list.json2025-11-07T15:30:57.873557 - 2025-11-07T15:30:57.888766 -  [DONE]2025-11-07T15:30:57.888766 - 
2025-11-07T15:30:58.014457 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\746607195_github-stats.json2025-11-07T15:30:58.014457 - 2025-11-07T15:30:58.020655 -  [DONE]2025-11-07T15:30:58.020655 - 
2025-11-07T15:30:58.025644 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\832903789_extras.json2025-11-07T15:30:58.026643 - 2025-11-07T15:30:58.026643 -  [DONE]2025-11-07T15:30:58.026643 - 
2025-11-07T15:30:58.207829 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1742899825_extension-node-map.json2025-11-07T15:30:58.207829 - 2025-11-07T15:30:58.222071 -  [DONE]2025-11-07T15:30:58.222071 - 
2025-11-07T15:31:00.745765 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-11-07T15:31:00.745765 - 
2025-11-07T15:31:00.860158 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1514988643_custom-node-list.json2025-11-07T15:31:00.860158 - 2025-11-07T15:31:00.882430 -  [DONE]2025-11-07T15:31:00.882430 - 
2025-11-07T15:31:01.005580 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\746607195_github-stats.json2025-11-07T15:31:01.005580 - 2025-11-07T15:31:01.011569 -  [DONE]2025-11-07T15:31:01.011569 - 
2025-11-07T15:31:01.016566 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\832903789_extras.json2025-11-07T15:31:01.017566 - 2025-11-07T15:31:01.017566 -  [DONE]2025-11-07T15:31:01.017566 - 
2025-11-07T15:31:01.188019 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1742899825_extension-node-map.json2025-11-07T15:31:01.188019 - 2025-11-07T15:31:01.207312 -  [DONE]2025-11-07T15:31:01.208310 - 
2025-11-07T15:31:03.337006 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-11-07T15:31:03.337006 - 
2025-11-07T15:31:03.478808 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1514988643_custom-node-list.json2025-11-07T15:31:03.478808 - 2025-11-07T15:31:03.495799 -  [DONE]2025-11-07T15:31:03.495799 - 
2025-11-07T15:31:03.634851 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\746607195_github-stats.json2025-11-07T15:31:03.634851 - 2025-11-07T15:31:03.644845 -  [DONE]2025-11-07T15:31:03.644845 - 
2025-11-07T15:31:03.651840 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\832903789_extras.json2025-11-07T15:31:03.652839 - 2025-11-07T15:31:03.652839 -  [DONE]2025-11-07T15:31:03.652839 - 
2025-11-07T15:31:03.655836 - Start fetching...2025-11-07T15:31:03.655836 - 2025-11-07T15:31:03.657840 - [2K
Fetching: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite2025-11-07T15:31:03.657840 - 2025-11-07T15:31:03.658835 - [2K
Fetching: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes2025-11-07T15:31:03.658835 - 2025-11-07T15:31:03.661832 - [2K
Fetching: C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper2025-11-07T15:31:03.662832 - 2025-11-07T15:31:10.133018 - [2K
Fetching done.2025-11-07T15:31:10.133018 - 
2025-11-07T15:31:10.296349 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\1742899825_extension-node-map.json2025-11-07T15:31:10.296349 - 2025-11-07T15:31:10.331616 -  [DONE]2025-11-07T15:31:10.331616 - 
2025-11-07T15:31:17.867194 - ERROR: To use this feature, you must either set '--listen' to a local IP and set the security level to 'normal-' or lower, or set the security level to 'middle' or 'weak'. Please contact the administrator.
Reference: https://github.com/ltdrdata/ComfyUI-Manager#security-policy
2025-11-07T15:31:35.282258 - got prompt
2025-11-07T15:31:35.419626 - !!! Exception during processing !!! Error while deserializing header: incomplete metadata, file not fully covered
2025-11-07T15:31:35.421626 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered

2025-11-07T15:31:35.424624 - Prompt executed in 0.12 seconds
2025-11-07T15:31:42.693182 - FETCH DATA from: C:\Stability Matrix\Packages\ComfyUI\user\default\ComfyUI-Manager\cache\4245046894_model-list.json2025-11-07T15:31:42.693182 - 2025-11-07T15:31:42.714268 -  [DONE]2025-11-07T15:31:42.714268 - 
2025-11-07T15:32:08.252464 - got prompt
2025-11-07T15:32:08.520188 - !!! Exception during processing !!! Can't import SageAttention: No module named 'sageattention'
2025-11-07T15:32:08.524187 - Traceback (most recent call last):
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1048, in loadmodel
    from sageattention import sageattn
ModuleNotFoundError: No module named 'sageattention'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1050, in loadmodel
    raise ValueError(f"Can't import SageAttention: {str(e)}")
ValueError: Can't import SageAttention: No module named 'sageattention'

2025-11-07T15:32:08.530183 - Prompt executed in 0.25 seconds
2025-11-07T15:32:18.543828 - got prompt
2025-11-07T15:32:18.795340 - CUDA Compute Capability: 6.1
2025-11-07T15:32:18.796341 - Loading extra model: 2025-11-07T15:32:18.796341 -  2025-11-07T15:32:18.796341 - C:\Stability matrix\Models\DiffusionModels\Wan2_1_FlashVSR_LQ_proj_model_bf16.safetensors2025-11-07T15:32:18.796341 - 
2025-11-07T15:32:18.817327 - Detected model in_channels: 16
2025-11-07T15:32:18.817327 - Model cross attention type: t2v, num_heads: 12, num_layers: 30
2025-11-07T15:32:18.817327 - Model variant detected: 1_3B
2025-11-07T15:32:19.013820 - FlashVSR model detected, patching model...
2025-11-07T15:32:21.126805 - model_type FLOW
2025-11-07T15:32:21.659699 - !!! Exception during processing !!! Error while deserializing header: incomplete metadata, file not fully covered
2025-11-07T15:32:21.661700 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered

2025-11-07T15:32:21.664695 - Prompt executed in 3.10 seconds
2025-11-07T15:35:25.919328 - got prompt
2025-11-07T15:35:26.096765 - CUDA Compute Capability: 6.1
2025-11-07T15:35:26.097346 - Loading extra model: 2025-11-07T15:35:26.097346 -  2025-11-07T15:35:26.097346 - C:\Stability matrix\Models\DiffusionModels\Wan2_1_FlashVSR_LQ_proj_model_bf16.safetensors2025-11-07T15:35:26.097346 - 
2025-11-07T15:35:26.097346 - !!! Exception during processing !!! No patch_embedding weight found, is the selected model a full WanVideo model?
2025-11-07T15:35:26.097346 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1177, in loadmodel
    raise ValueError("No patch_embedding weight found, is the selected model a full WanVideo model?")
ValueError: No patch_embedding weight found, is the selected model a full WanVideo model?

2025-11-07T15:35:26.097346 - Prompt executed in 0.17 seconds
2025-11-07T15:35:47.184277 - got prompt
2025-11-07T15:35:47.884233 - CUDA Compute Capability: 6.1
2025-11-07T15:35:47.884233 - Loading extra model: 2025-11-07T15:35:47.884233 -  2025-11-07T15:35:47.884233 - C:\Stability matrix\Models\DiffusionModels\Wan2_1_FlashVSR_LQ_proj_model_bf16.safetensors2025-11-07T15:35:47.884233 - 
2025-11-07T15:35:47.884233 - Detected model in_channels: 16
2025-11-07T15:35:47.884233 - Model cross attention type: t2v, num_heads: 12, num_layers: 30
2025-11-07T15:35:47.887808 - Model variant detected: 1_3B
2025-11-07T15:35:48.109400 - FlashVSR model detected, patching model...
2025-11-07T15:35:50.265088 - model_type FLOW
2025-11-07T15:35:50.334166 - !!! Exception during processing !!! Error while deserializing header: incomplete metadata, file not fully covered
2025-11-07T15:35:50.336166 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered

2025-11-07T15:35:50.340362 - Prompt executed in 3.13 seconds
2025-11-07T15:35:59.680093 - got prompt
2025-11-07T15:35:59.920385 - CUDA Compute Capability: 6.1
2025-11-07T15:35:59.921385 - Loading extra model: 2025-11-07T15:35:59.921385 -  2025-11-07T15:35:59.921385 - C:\Stability matrix\Models\DiffusionModels\Wan2_1_FlashVSR_LQ_proj_model_bf16.safetensors2025-11-07T15:35:59.921385 - 
2025-11-07T15:35:59.922384 - Detected model in_channels: 16
2025-11-07T15:35:59.922384 - Model cross attention type: t2v, num_heads: 12, num_layers: 30
2025-11-07T15:35:59.922384 - Model variant detected: 1_3B
2025-11-07T15:36:00.138582 - FlashVSR model detected, patching model...
2025-11-07T15:36:02.427673 - model_type FLOW
2025-11-07T15:36:02.609834 - !!! Exception during processing !!! Error while deserializing header: incomplete metadata, file not fully covered
2025-11-07T15:36:02.611834 - Traceback (most recent call last):
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Stability matrix\Packages\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_model_loading.py", line 1769, in loadmodel
    sd = load_torch_file(model_path, safe_load=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 79, in load_torch_file
    raise e
  File "C:\Stability matrix\Packages\ComfyUI\comfy\utils.py", line 63, in load_torch_file
    with safetensors.safe_open(ckpt, framework="pt", device=device.type) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered

2025-11-07T15:36:02.614831 - Prompt executed in 2.92 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
`

### Logs

```powershell

```

**Comment by sud33p** [comment]
I had the same error, my model was incorrect or corrupted:
```
The safetensors error is caused by a corrupted model file: models/diffusion_models/qwen_image_edit_fp8_e4m3fn.safetensors

The file appears incomplete (7.3GB modified Aug 25, 2025) - likely a failed/interrupted download.
```

**Comment by damnms** [comment]
having the same problem, checked multiple times the models. unfortunately, no md5sum or so, so no idea if its fully downloaded or not.

```
oli@DESKTOP-RA0V02P:~/ComfyUI/models$ ls -lah *
audio_encoders:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_audio_encoder_models_here

checkpoints:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_checkpoints_here

clip:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_clip_or_text_encoder_models_here

clip_vision:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_clip_vision_models_here

configs:
insgesamt 56K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli 1,9K 10. Nov 14:03 anything_v3.yaml
-rw-rw-r--  1 oli oli 2,0K 10. Nov 14:03 v1-inference_clip_skip_2_fp16.yaml
-rw-rw-r--  1 oli oli 1,9K 10. Nov 14:03 v1-inference_clip_skip_2.yaml
-rw-rw-r--  1 oli oli 1,9K 10. Nov 14:03 v1-inference_fp16.yaml
-rw-rw-r--  1 oli oli 1,9K 10. Nov 14:03 v1-inference.yaml
-rw-rw-r--  1 oli oli 2,0K 10. Nov 14:03 v1-inpainting-inference.yaml
-rw-rw-r--  1 oli oli 1,8K 10. Nov 14:03 v2-inference_fp32.yaml
-rw-rw-r--  1 oli oli 1,8K 10. Nov 14:03 v2-inference-v_fp32.yaml
-rw-rw-r--  1 oli oli 1,8K 10. Nov 14:03 v2-inference-v.yaml
-rw-rw-r--  1 oli oli 1,8K 10. Nov 14:03 v2-inference.yaml
-rw-rw-r--  1 oli oli 4,4K 10. Nov 14:03 v2-inpainting-inference.yaml

controlnet:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_controlnets_and_t2i_here

diffusers:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_diffusers_models_here

diffusion_models:
insgesamt 39G
drwxrwxr-x  2 oli oli 4,0K 10. Nov 15:57 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_diffusion_model_files_here
-rw-rw-r--  1 oli oli  20G 10. Nov 14:46 qwen_image_distill_full_fp8_e4m3fn.safetensors
-rw-rw-r--  1 oli oli  20G 10. Nov 14:10 qwen_image_fp8_e4m3fn.safetensors

embeddings:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_embeddings_or_textual_inversion_concepts_here

gligen:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_gligen_models_here

hypernetworks:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_hypernetworks_here

loras:
insgesamt 1,6G
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:37 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_loras_here
-rw-rw-r--  1 oli oli 1,6G 10. Nov 14:08 Qwen-Image-Lightning-4steps-V1.0.safetensors

model_patches:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_model_patches_here

photomaker:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_photomaker_models_here

style_models:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_t2i_style_model_here

text_encoders:
insgesamt 4,1G
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:37 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_text_encoder_files_here
-rw-rw-r--  1 oli oli 4,0G 10. Nov 14:36 qwen_2.5_vl_7b_fp8_scaled.safetensors

unet:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_unet_files_here

upscale_models:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_esrgan_and_other_upscale_models_here

vae:
insgesamt 243M
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:37 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_vae_here
-rw-rw-r--  1 oli oli 243M 10. Nov 14:08 qwen_image_vae.safetensors

vae_approx:
insgesamt 8,0K
drwxrwxr-x  2 oli oli 4,0K 10. Nov 14:03 .
drwxrwxr-x 22 oli oli 4,0K 10. Nov 14:37 ..
-rw-rw-r--  1 oli oli    0 10. Nov 14:03 put_taesd_encoder_pth_and_taesd_decoder_pth_here
```

i assume its because of qwen_image_distill_full_bf16.safetensors which should be nearly 40gb, but when downloading with firefox, it "stops" after about 20gb? at least thats how it looks like. going to try it now with wget and resume if required. just noticed that this is also not listed as required model in the "getting started" page.

**Comment by Dkop123** [comment]
who knows how to solve this problem?

**Comment by Niemand-geht-an-mein-Schnitzel** [comment]
**Subject:** Solution: The "incomplete metadata" error implies a corrupted/interrupted download

I encountered the exact same issue (same error in the logs: `safetensors_rust.SafetensorError: Error while deserializing header: incomplete metadata, file not fully covered`).

**The Cause:**
The model file was not downloaded completely. The browser or download manager marked the download as "finished" prematurely, leaving the file truncated.
In my specific case, the `flux1-schnell-fp8.safetensors` file in my folder was only **3 GB** in size, whereas it is supposed to be roughly **17 GB**. Because the file ends abruptly, ComfyUI crashes when trying to read the header.

**The Solution:**
1. Check your log to see which file is being loaded right before the crash.
2. Navigate to your `models/checkpoints` (or `diffusion_models`) folder.
3. Check the file size. If it is significantly smaller than the size listed on HuggingFace, it is corrupted.
4. **Delete the corrupted file.**
5. Re-download the file **manually** (directly from HuggingFace) to ensure the download completes 100%.
6. Place the new file into the folder and restart.

It worked instantly for me after fixing the file size. 



@sud33p @damnms @tobbez @jeske

**Comment by MagreYun** [comment]
Error "Server error: Error while deserializing header: incomplete metadata, file not fully covered" shows also if LoRA files are corrupted too! Just found it out "the hard way"(tried redownloading checkpoint models with no success).

**Comment by RadzdomManG** [comment]
got the same error, 

lora failed too so i just check the original Lora I downloaded (146MB) and check the Lora inside comfy (90mb) so i just delete it, then move the 146MB and wait for it to complete. Problem solved

**Comment by dacy** [comment]
Run this - it will show which files are corrupted. This happened to me because my comfyUI downloading of missing models were interrupted and partial models were downloaded. 

`python - <<'PY'
from pathlib import Path
from safetensors import safe_open

root = Path("/path/to/your/ComfyUI/models")

for f in root.rglob("*.safetensors"):
    try:
        with safe_open(str(f), framework="pt", device="cpu") as sf:
            keys = list(sf.keys())
        print("OK   ", f)
    except Exception as e:
        print("BAD  ", f)
        print("     ", e)
PY
`
