### ISSUE TITLE
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by prog-ape** [comfyanonymous/ComfyUI#10732]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Able to operate normally and stably

### Actual Behavior

!!! Exception during processing !!! CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Steps to Reproduce

Total VRAM 24091 MB, total RAM 1031813 MB
pytorch version: 2.6.0+cu126
xformers version: 0.0.29.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Enabled pinned memory 980222.0
Using xformers attention
Python version: 3.10.18 (main, Jun  5 2025, 13:14:17) [GCC 11.2.0]
ComfyUI version: 0.3.68
ComfyUI frontend version: 1.28.8

Without any additional startup parameters, it simply starts with `python main.py`.

Before executing a new task, I call the `/free` interface of comfyui. After updating to the latest code, this exception occurs and the program freezes after running for a while. Rolling back to version bda0eb24 does not cause this problem.

### Debug Logs

```powershell
Requested to load WAN21
!!! Exception during processing !!! CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/wp/ComfyUI/execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "/wp/ComfyUI/execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "/wp/ComfyUI/execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/wp/ComfyUI/execution.py", line 286, in process_inputs
    result = f(**inputs)
  File "/wp/ComfyUI/nodes.py", line 1559, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "/wp/ComfyUI/nodes.py", line 1492, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/wp/ComfyUI/comfy/sample.py", line 60, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/wp/ComfyUI/comfy/samplers.py", line 1163, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/wp/ComfyUI/comfy/samplers.py", line 1053, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/wp/ComfyUI/comfy/samplers.py", line 1035, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
  File "/wp/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "/wp/ComfyUI/comfy/samplers.py", line 984, in outer_sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds, self.model_options)
  File "/wp/ComfyUI/comfy/sampler_helpers.py", line 130, in prepare_sampling
    return executor.execute(model, noise_shape, conds, model_options=model_options)
  File "/wp/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "/wp/ComfyUI/comfy/sampler_helpers.py", line 138, in _prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required + inference_memory, minimum_memory_required=minimum_memory_required + inference_memory)
  File "/wp/ComfyUI/comfy/model_management.py", line 674, in load_models_gpu
    free_memory(total_memory_required[device] * 1.1 + extra_mem, device)
  File "/wp/ComfyUI/comfy/model_management.py", line 606, in free_memory
    if current_loaded_models[i].model_unload(memory_to_free):
  File "/wp/ComfyUI/comfy/model_management.py", line 532, in model_unload
    self.model.detach(unpatch_weights)
  File "/wp/ComfyUI/comfy/model_patcher.py", line 950, in detach
    self.unpatch_model(self.offload_device, unpatch_weights=unpatch_all)
  File "/wp/ComfyUI/comfy/model_patcher.py", line 832, in unpatch_model
    self.model.to(device_to)
  File "/wp/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1343, in to
    return self._apply(convert)
  File "/wp/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/wp/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/wp/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/wp/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 930, in _apply
    param_applied = fn(param)
  File "/wp/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1329, in convert
    return t.to(
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by spike4379** [comment]
Also getting this. It appears to be a problem with wan video ksampler and wan video ksampler(advanced)
After using the kijai model sampler his works fine, but I would prefer this one to work because i dont want to have to update a whole workflow because comfy has broken it.

On my end for error resolution testing I have tried
changing the model loader,
removing blockswapping,
reloading nodes,
purging caches between generation attempts.


Something interesting I noticed was the it will generate okay on the first time I load up comfyUI but if you do another generation it appears to get this error.
I believe this to be an actual bug.

I have attached my error as well. For reference you are using python 3.10 by the looks of it which is not recommended. However I am using 3.12 which IS recommended, which helps point out that this is indeed a bug

[error.txt](https://github.com/user-attachments/files/23516300/error.txt)

**Comment by prog-ape** [comment]
Okay, thank you. I'll modify it again and run it for a while to see.

**Comment by gitterB302** [comment]
So there's still no fix for this problem?

**Comment by Aenon1** [comment]
This also happens when using SDXL models in a simple workflow.
