### ISSUE TITLE
working around nvidia conv3d memory bug

### ISSUE THREAD

**Issue by Trombo38** [comfyanonymous/ComfyUI#10827]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

wan 2.2 workflow with fastVSR success

### Actual Behavior

Since i've updated to last comfyui my wan 2.2 workflow with FastVSR is not going to the end. I get OOM. My felling is it comes from this update "working around nvidia conv3d memory bug." Do you this posible to add an arg to activate/desactivate this workaround in the launch.bat?

Edit : i just relaunched, FASTVSR crashed at VAE loading. Maybe it is due to torch 2.9.1?

### Steps to Reproduce

it happens each time i run the workflow now

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-11-21 20:18:48.991
** Platform: Windows
** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
** Python executable: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI
** ComfyUI Base Folder Path: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI
** User directory: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\user
** ComfyUI-Manager config path: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-easy-use
  10.9 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 12287 MB, total RAM 32725 MB
pytorch version: 2.9.1+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
working around nvidia conv3d memory bug.
Using pytorch attention
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.3.71
ComfyUI frontend version: 1.28.9
[Prompt Server] web root: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\comfyui_frontend_package\static
Total VRAM 12287 MB, total RAM 32725 MB
pytorch version: 2.9.1+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[ComfyUI-Easy-Use] server: v1.3.4 Loaded
[ComfyUI-Easy-Use] web root: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-easy-use\web_version/v2 Loaded
ComfyUI-GGUF: Allowing full torch compile
### Loading: ComfyUI-Impact-Pack (V8.28)
[Impact Pack] Wildcard total size (0.00 MB) is within cache limit (50.00 MB). Using full cache mode.
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V3.37.1)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.71 | Released on '2025-11-21'
======================================== ComfyUI-nunchaku Initialization ========================================
Nunchaku version: 1.1.0.dev20251111
ComfyUI-nunchaku version: 1.0.2
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Nodes `NunchakuPulidApply`,`NunchakuPulidLoader`, `NunchakuPuLIDLoaderV2` and `NunchakuFluxPuLIDApplyV2` import failed:
Traceback (most recent call last):
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 119, in <module>
    from .nodes.models.pulid import (
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\pulid.py", line 21, in <module>
    from nunchaku.pipeline.pipeline_flux_pulid import PuLIDPipeline
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\nunchaku\pipeline\pipeline_flux_pulid.py", line 18, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'
=================================================================================================================
======================================== ComfyUI-QwenImageLoraLoader Initialization ========================================
[DEBUG] Added to sys.path: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-QwenImageLoraLoader
[DEBUG] wrappers dir exists: True
[DEBUG] qwenimage.py exists: True
============================================================================================================================

Initializing ControlAltAI Nodes

[rgthree-comfy] Loaded 48 fantastic nodes. 🎉

Traceback (most recent call last):
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\nodes.py", line 2136, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI-nunchaku\\ComfyUI-Easy-Install\\ComfyUI\\custom_nodes\\was-node-suite-comfyui\\__init__.py'

Cannot import D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI-nunchaku\\ComfyUI-Easy-Install\\ComfyUI\\custom_nodes\\was-node-suite-comfyui\\__init__.py'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui_memory_cleanup
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-PainterI2V
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-unload-model
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-QwenImageLoraLoader
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\wan22fmlf
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-QwenVL
   0.0 seconds (IMPORT FAILED): D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\was-node-suite-comfyui
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-custom-scripts
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\controlaltai-nodes
   0.0 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\gguf
   0.1 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-kjnodes
   0.1 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast
   0.1 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\rgthree-comfy
   0.7 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-impact-pack
   0.7 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-nunchaku
   0.7 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
   0.9 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-manager
   1.3 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-videohelpersuite
  11.5 seconds: D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\comfyui-easy-use

FETCH ComfyRegistry Data: 5/107
Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 10/107
FETCH ComfyRegistry Data: 15/107
FETCH ComfyRegistry Data: 20/107
FETCH ComfyRegistry Data: 25/107
FETCH ComfyRegistry Data: 30/107
FETCH ComfyRegistry Data: 35/107
FETCH ComfyRegistry Data: 40/107
FETCH ComfyRegistry Data: 45/107
FETCH ComfyRegistry Data: 50/107
FETCH ComfyRegistry Data: 55/107
FETCH ComfyRegistry Data: 60/107
FETCH ComfyRegistry Data: 65/107
FETCH ComfyRegistry Data: 70/107
FETCH ComfyRegistry Data: 75/107
FETCH ComfyRegistry Data: 80/107
FETCH ComfyRegistry Data: 85/107
FETCH ComfyRegistry Data: 90/107
FETCH ComfyRegistry Data: 95/107
FETCH ComfyRegistry Data: 100/107
FETCH ComfyRegistry Data: 105/107
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
[QwenVL] Node on nvidia_gpu
D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\huggingface_hub\file_download.py:979: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████████████| 12/12 [00:00<?, ?it/s]
[QwenVL] Loading Qwen3-VL-4B-Instruct (None (FP16), attn=flash_attention_2)
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:24<00:00, 12.13s/it]
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load CLIPVisionModelProjection
loaded completely; 9770.67 MB usable, 1208.10 MB loaded, full load: True
Using scaled fp8: fp8 matrix mult: False, scale input: False
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load WanTEModel
loaded completely; 8562.57 MB usable, 6419.48 MB loaded, full load: True
Requested to load WanVAE
loaded completely; 277.38 MB usable, 242.03 MB loaded, full load: True
ComfyUI-GGUF: Allowing full torch compile
gguf qtypes: F16 (694), Q8_0 (400), F32 (1)
model weight dtype torch.float16, manual cast: None
model_type FLOW
lora key not loaded: diffusion_model.blocks.0.diff_m
lora key not loaded: diffusion_model.blocks.1.diff_m
lora key not loaded: diffusion_model.blocks.10.diff_m
lora key not loaded: diffusion_model.blocks.11.diff_m
lora key not loaded: diffusion_model.blocks.12.diff_m
lora key not loaded: diffusion_model.blocks.13.diff_m
lora key not loaded: diffusion_model.blocks.14.diff_m
lora key not loaded: diffusion_model.blocks.15.diff_m
lora key not loaded: diffusion_model.blocks.16.diff_m
lora key not loaded: diffusion_model.blocks.17.diff_m
lora key not loaded: diffusion_model.blocks.18.diff_m
lora key not loaded: diffusion_model.blocks.19.diff_m
lora key not loaded: diffusion_model.blocks.2.diff_m
lora key not loaded: diffusion_model.blocks.20.diff_m
lora key not loaded: diffusion_model.blocks.21.diff_m
lora key not loaded: diffusion_model.blocks.22.diff_m
lora key not loaded: diffusion_model.blocks.23.diff_m
lora key not loaded: diffusion_model.blocks.24.diff_m
lora key not loaded: diffusion_model.blocks.25.diff_m
lora key not loaded: diffusion_model.blocks.26.diff_m
lora key not loaded: diffusion_model.blocks.27.diff_m
lora key not loaded: diffusion_model.blocks.28.diff_m
lora key not loaded: diffusion_model.blocks.29.diff_m
lora key not loaded: diffusion_model.blocks.3.diff_m
lora key not loaded: diffusion_model.blocks.30.diff_m
lora key not loaded: diffusion_model.blocks.31.diff_m
lora key not loaded: diffusion_model.blocks.32.diff_m
lora key not loaded: diffusion_model.blocks.33.diff_m
lora key not loaded: diffusion_model.blocks.34.diff_m
lora key not loaded: diffusion_model.blocks.35.diff_m
lora key not loaded: diffusion_model.blocks.36.diff_m
lora key not loaded: diffusion_model.blocks.37.diff_m
lora key not loaded: diffusion_model.blocks.38.diff_m
lora key not loaded: diffusion_model.blocks.39.diff_m
lora key not loaded: diffusion_model.blocks.4.diff_m
lora key not loaded: diffusion_model.blocks.5.diff_m
lora key not loaded: diffusion_model.blocks.6.diff_m
lora key not loaded: diffusion_model.blocks.7.diff_m
lora key not loaded: diffusion_model.blocks.8.diff_m
lora key not loaded: diffusion_model.blocks.9.diff_m
lora key not loaded: diffusion_model.head.diff_m
Requested to load WAN21
0 models unloaded.
loaded partially; 128.00 MB usable, 128.00 MB loaded, 14697.47 MB offloaded, lowvram patches: 0
100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [09:33<00:00, 191.08s/it]
Unload Model:
 - Unloading all models...
 - Clearing Cache...
gguf qtypes: F16 (694), Q8_0 (400), F32 (1)
model weight dtype torch.float16, manual cast: None
model_type FLOW
lora key not loaded: diffusion_model.blocks.0.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.0.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.0.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.0.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.0.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.0.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.0.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.1.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.1.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.1.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.1.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.1.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.1.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.1.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.10.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.10.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.10.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.10.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.10.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.10.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.10.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.11.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.11.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.11.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.11.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.11.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.11.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.11.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.12.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.12.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.12.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.12.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.12.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.12.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.12.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.13.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.13.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.13.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.13.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.13.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.13.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.13.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.14.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.14.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.14.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.14.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.14.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.14.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.14.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.15.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.15.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.15.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.15.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.15.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.15.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.15.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.16.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.16.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.16.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.16.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.16.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.16.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.16.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.17.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.17.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.17.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.17.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.17.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.17.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.17.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.18.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.18.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.18.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.18.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.18.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.18.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.18.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.19.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.19.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.19.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.19.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.19.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.19.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.19.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.2.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.2.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.2.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.2.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.2.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.2.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.2.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.20.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.20.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.20.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.20.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.20.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.20.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.20.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.21.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.21.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.21.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.21.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.21.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.21.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.21.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.22.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.22.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.22.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.22.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.22.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.22.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.22.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.23.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.23.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.23.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.23.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.23.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.23.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.23.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.24.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.24.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.24.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.24.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.24.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.24.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.24.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.25.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.25.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.25.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.25.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.25.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.25.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.25.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.26.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.26.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.26.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.26.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.26.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.26.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.26.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.27.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.27.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.27.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.27.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.27.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.27.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.27.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.28.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.28.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.28.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.28.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.28.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.28.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.28.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.29.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.29.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.29.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.29.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.29.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.29.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.29.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.3.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.3.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.3.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.3.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.3.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.3.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.3.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.30.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.30.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.30.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.30.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.30.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.30.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.30.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.31.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.31.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.31.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.31.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.31.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.31.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.31.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.32.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.32.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.32.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.32.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.32.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.32.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.32.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.33.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.33.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.33.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.33.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.33.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.33.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.33.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.34.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.34.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.34.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.34.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.34.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.34.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.34.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.35.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.35.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.35.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.35.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.35.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.35.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.35.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.36.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.36.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.36.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.36.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.36.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.36.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.36.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.37.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.37.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.37.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.37.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.37.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.37.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.37.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.38.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.38.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.38.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.38.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.38.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.38.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.38.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.39.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.39.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.39.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.39.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.39.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.39.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.39.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.4.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.4.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.4.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.4.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.4.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.4.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.4.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.5.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.5.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.5.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.5.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.5.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.5.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.5.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.6.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.6.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.6.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.6.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.6.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.6.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.6.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.7.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.7.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.7.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.7.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.7.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.7.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.7.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.8.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.8.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.8.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.8.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.8.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.8.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.8.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.9.cross_attn.k_img.diff_b
lora key not loaded: diffusion_model.blocks.9.cross_attn.k_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.9.cross_attn.k_img.lora_up.weight
lora key not loaded: diffusion_model.blocks.9.cross_attn.norm_k_img.diff
lora key not loaded: diffusion_model.blocks.9.cross_attn.v_img.diff_b
lora key not loaded: diffusion_model.blocks.9.cross_attn.v_img.lora_down.weight
lora key not loaded: diffusion_model.blocks.9.cross_attn.v_img.lora_up.weight
lora key not loaded: diffusion_model.img_emb.proj.0.diff
lora key not loaded: diffusion_model.img_emb.proj.0.diff_b
lora key not loaded: diffusion_model.img_emb.proj.1.diff_b
lora key not loaded: diffusion_model.img_emb.proj.1.lora_down.weight
lora key not loaded: diffusion_model.img_emb.proj.1.lora_up.weight
lora key not loaded: diffusion_model.img_emb.proj.3.diff_b
lora key not loaded: diffusion_model.img_emb.proj.3.lora_down.weight
lora key not loaded: diffusion_model.img_emb.proj.3.lora_up.weight
lora key not loaded: diffusion_model.img_emb.proj.4.diff
lora key not loaded: diffusion_model.img_emb.proj.4.diff_b
Requested to load WAN21
0 models unloaded.
loaded partially; 128.00 MB usable, 128.00 MB loaded, 14697.47 MB offloaded, lowvram patches: 0
100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [08:47<00:00, 175.86s/it]
Requested to load WanVAE
0 models unloaded.
loaded partially; 128.00 MB usable, 128.00 MB loaded, 114.00 MB offloaded, lowvram patches: 0
Unload Model:
 - Unloading all models...
 - Clearing Cache...
RAM清理完成 [78.3% → 59.4%, 释放: 6199MB]

 ███████╗██╗      █████╗ ███████╗██╗  ██╗██╗   ██╗███████╗█████╗
 ██╔════╝██║     ██╔══██╗██╔════╝██║  ██║██║   ██║██╔════╝██╔══██╗   ██╗
 █████╗  ██║     ███████║███████╗███████║╚██╗ ██╔╝███████╗███████║ ██████╗
 ██╔══╝  ██║     ██╔══██║╚════██║██╔══██║ ╚████╔╝ ╚════██║██╔═██║    ██╔═╝
 ██║     ███████╗██║  ██║███████║██║  ██║  ╚██╔╝  ███████║██║  ██║   ╚═╝
 ╚═╝     ╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝

Using wan_video_dit from D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\models\FlashVSR-v1.1\diffusion_pytorch_model_streaming_dmd.safetensors
Using wan_video_vae from D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\models\FlashVSR-v1.1\Wan2.1_VAE.pth
[FlashVSR] Processing tile 1/18: coords (0,0) to (256,256)
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:09<00:00,  1.01s/it]
[FlashVSR] Offloading DiT to the CPU to free up VRAM...
[FlashVSR] Starting VAE decoding...
VAE decoding: 100%|██████████████████████████████████████████████████████████████████████| 2/2 [01:00<00:00, 30.35s/it]
[FlashVSR] Processing tile 2/18: coords (232,0) to (488,256)
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.19it/s]
[FlashVSR] Offloading DiT to the CPU to free up VRAM...
[FlashVSR] Starting VAE decoding...
VAE decoding:   0%|                                                                              | 0/2 [00:02<?, ?it/s]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\nodes.py", line 540, in main
    output = flashvsr(pipe, frames, scale, True, tiled_vae, tiled_dit, 256, 24, unload_dit, 2.0, 3.0, 11, seed, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\nodes.py", line 274, in flashvsr
    output_tile_gpu = pipe(
                      ^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\pipelines\flashvsr_full.py", line 457, in __call__
    frames = self.decode_video(latents, **tiler_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\pipelines\flashvsr_full.py", line 300, in decode_video
    frames = self.vae.decode(latents, device=self.device, tiled=tiled, tile_size=tile_size, tile_stride=tile_stride)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\models\wan_video_vae.py", line 812, in decode
    video = self.tiled_decode(hidden_state, device, tile_size, tile_stride)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\models\wan_video_vae.py", line 696, in tiled_decode
    hidden_states_batch = self.model.decode(hidden_states_batch, self.scale).to(data_device)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\models\wan_video_vae.py", line 572, in decode
    out_ = self.decoder(x[:, :, i:i + 1, :, :],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\models\wan_video_vae.py", line 461, in forward
    x = layer(x, feat_cache, feat_idx)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\models\wan_video_vae.py", line 228, in forward
    x = layer(x, feat_cache[idx])
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\vram_management\layers.py", line 38, in forward
    return module(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-FlashVSR_Ultra_Fast\src\models\wan_video_vae.py", line 53, in forward
    return super().forward(x)
           ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 717, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-nunchaku\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 712, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 00:30:02
```

**Comment by jovan2009** [comment]
> Since i've updated to last comfyui my wan 2.2 workflow with FastVSR is not going to the end.

How old was your previous ComfyUI version? I ask this because the "working around conv3d" is not new in ComfyUI code, it is at least 1 or 2 months old. It was put in place because of a cudnn bug. In fact it was somewhat reverted recently, if you happen to have a newer cudnn version (9.15+) inside your pytorch installation this workaround is not applied any more in ComfyUI. Since I see you have pytorch 2.9.1 you may try to install with pip latest nvidia-cudnn 9.16 package and that way pytorch might use it instead of cudnn version 9.12 which is compiled inside pytorch. See Pytorch 2.9.1 release notes: https://github.com/pytorch/pytorch/releases

>Significant Memory Regression in F.conv3d with bfloat16 Inputs in PyTorch 2.9.0 (https://github.com/pytorch/pytorch/issues/166643)
This release provides work around this issue. If you are impacted please install nvidia-cudnn package version 9.15+ from pypi. (https://github.com/pytorch/pytorch/pull/166480) (https://github.com/pytorch/pytorch/pull/167111)

That Pytorch workaround mentioned in the above release notes works probably in Linux. For me it didn't work on Windows, what worked for me was copying directly the latest Nvidia cudnn 9.16 dll files over the files with the same names inside pytorch folder, overwriting them.

You can find more details about what I did to "update" Cudnn inside pytorch here https://github.com/comfyanonymous/ComfyUI/issues/10758

**Comment by comfyanonymous** [comment]
The workaround is so native comfyui works, it does not cover custom nodes which is why you are having the problem.

**Comment by Trombo38** [comment]
> > Since i've updated to last comfyui my wan 2.2 workflow with FastVSR is not going to the end.
> 
> How old was your previous ComfyUI version? I ask this because the "working around conv3d" is not new in ComfyUI code, it is at least 1 or 2 months old. It was put in place because of a cudnn bug. In fact it was somewhat reverted recently, if you happen to have a newer cudnn version (9.15+) inside your pytorch installation this workaround is not applied any more in ComfyUI. Since I see you have pytorch 2.9.1 you may try to install with pip latest nvidia-cudnn 9.16 package and that way pytorch might use it instead of cudnn version 9.12 which is compiled inside pytorch. See Pytorch 2.9.1 release notes: https://github.com/pytorch/pytorch/releases
> 
> > Significant Memory Regression in F.conv3d with bfloat16 Inputs in PyTorch 2.9.0 ([pytorch/pytorch#166643](https://github.com/pytorch/pytorch/issues/166643))
> > This release provides work around this issue. If you are impacted please install nvidia-cudnn package version 9.15+ from pypi. ([pytorch/pytorch#166480](https://github.com/pytorch/pytorch/pull/166480)) ([pytorch/pytorch#167111](https://github.com/pytorch/pytorch/pull/167111))
> 
> That Pytorch workaround mentioned in the above release notes works probably in Linux. For me it didn't work on Windows, what worked for me was copying directly the latest Nvidia cudnn 9.16 dll files over the files with the same names inside pytorch folder, overwriting them.
> 
> You can find more details about what I did to "update" Cudnn inside pytorch here [#10758](https://github.com/comfyanonymous/ComfyUI/issues/10758)

Thanks, i will try
