### ISSUE TITLE
Intel B580 XPU: Native API failed. Native API returns: 20 (UR_RESULT_ERROR_DEVICE_LOST)

### ISSUE THREAD

**Issue by CNWuhan027** [comfyanonymous/ComfyUI#10847]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

use a wan2.2 5b template, only click run, then after about 10 minutes, shows this error 

### Actual Behavior

<img width="2560" height="1259" alt="Image" src="https://github.com/user-attachments/assets/154a3d61-3553-4d31-a7bd-7ea17f031ee9" />

### Steps to Reproduce

1. run comfy
2. load wan2.2 5b template
3. click run
4. after about 10 minutes task failed

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 8
- **Node Type:** VAEDecode
- **Exception Type:** RuntimeError
- **Exception Message:** Native API failed. Native API returns: 20 (UR_RESULT_ERROR_DEVICE_LOST)

## Stack Trace

  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\nodes.py", line 295, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\comfy\sd.py", line 708, in decode
    out = self.process_output(self.first_stage_model.decode(samples, **vae_options).to(self.output_device).float())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.68
- **Arguments:** main.py --port 49000 --preview-method auto --output-directory C:\Users\rootm\Documents\AI-Playground\media --lowvram --disable-ipex-optimize --bf16-unet --reserve-vram 6.0
- **OS:** nt
- **Python Version:** 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0+xpu
## Devices

- **Name:** xpu:0 Intel(R) Arc(TM) B580 Graphics
  - **Type:** xpu
  - **VRAM Total:** 12446343168
  - **VRAM Free:** 6113294336
  - **Torch VRAM Total:** 8759803904
  - **Torch VRAM Free:** 2426755072

## Logs

2025-11-23T18:27:48.390902 - Adding extra search path checkpoints D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-11-23T18:27:48.390902 - Adding extra search path clip D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-11-23T18:27:48.390902 - Adding extra search path vae D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-11-23T18:27:48.390902 - Adding extra search path unet D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-11-23T18:27:48.390902 - Adding extra search path loras D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\lora
2025-11-23T18:27:48.390902 - Setting output directory to: C:\Users\rootm\Documents\AI-Playground\media
2025-11-23T18:27:48.829645 - [START] Security scan2025-11-23T18:27:48.829645 - 
2025-11-23T18:27:49.981165 - [DONE] Security scan2025-11-23T18:27:49.981165 - 
2025-11-23T18:27:50.192153 - ## ComfyUI-Manager: installing dependencies done.2025-11-23T18:27:50.192153 - 
2025-11-23T18:27:50.192153 - ** ComfyUI startup time:2025-11-23T18:27:50.192153 -  2025-11-23T18:27:50.192153 - 2025-11-23 18:27:50.1922025-11-23T18:27:50.192153 - 
2025-11-23T18:27:50.192153 - ** Platform:2025-11-23T18:27:50.192153 -  2025-11-23T18:27:50.192153 - Windows2025-11-23T18:27:50.192153 - 
2025-11-23T18:27:50.192153 - ** Python version:2025-11-23T18:27:50.192153 -  2025-11-23T18:27:50.192153 - 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]2025-11-23T18:27:50.192153 - 
2025-11-23T18:27:50.192153 - ** Python executable:2025-11-23T18:27:50.192153 -  2025-11-23T18:27:50.192153 - D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\comfyui-backend-env\python.exe2025-11-23T18:27:50.192153 - 
2025-11-23T18:27:50.192153 - ** ComfyUI Path:2025-11-23T18:27:50.192153 -  2025-11-23T18:27:50.192153 - D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI2025-11-23T18:27:50.192153 - 
2025-11-23T18:27:50.192153 - ** ComfyUI Base Folder Path:2025-11-23T18:27:50.192153 -  2025-11-23T18:27:50.192153 - D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI2025-11-23T18:27:50.192153 - 
2025-11-23T18:27:50.193153 - ** User directory:2025-11-23T18:27:50.193153 -  2025-11-23T18:27:50.193153 - D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\user2025-11-23T18:27:50.193153 - 
2025-11-23T18:27:50.193153 - ** ComfyUI-Manager config path:2025-11-23T18:27:50.193153 -  2025-11-23T18:27:50.193153 - D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-11-23T18:27:50.193153 - 
2025-11-23T18:27:50.193153 - ** Log path:2025-11-23T18:27:50.193153 -  2025-11-23T18:27:50.193153 - D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\user\comfyui.log2025-11-23T18:27:50.193153 - 
2025-11-23T18:27:51.080609 - 
Prestartup times for custom nodes:
2025-11-23T18:27:51.080609 -    2.7 seconds: D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-manager
2025-11-23T18:27:51.080609 - 
2025-11-23T18:27:52.279899 - Checkpoint files will always be loaded safely.
2025-11-23T18:27:52.428015 - Total VRAM 11870 MB, total RAM 65277 MB
2025-11-23T18:27:52.428015 - pytorch version: 2.8.0+xpu
2025-11-23T18:27:52.428015 - Set vram state to: LOW_VRAM
2025-11-23T18:27:52.428015 - Device: xpu:0 Intel(R) Arc(TM) B580 Graphics
2025-11-23T18:27:54.117973 - Using pytorch attention
2025-11-23T18:27:56.803271 - Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
2025-11-23T18:27:56.803271 - ComfyUI version: 0.3.68
2025-11-23T18:27:56.906914 - ________________________________________________________________________
WARNING WARNING WARNING WARNING WARNING

Installed frontend version 1.23.4 is lower than the recommended version 1.28.8.

Please install the updated requirements.txt file by running:
D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\comfyui-backend-env\python.exe -s -m pip install -r D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\requirements.txt
If you are on the portable package you can run: update\update_comfyui.bat to solve this problem.

This error is happening because the ComfyUI frontend is no longer shipped as part of the main repo but as a pip package instead.
________________________________________________________________________
2025-11-23T18:27:56.907913 - [Prompt Server] web root: D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\comfyui-backend-env\Lib\site-packages\comfyui_frontend_package\static
2025-11-23T18:27:57.954489 - ComfyUI-GGUF: Allowing full torch compile
2025-11-23T18:27:57.961504 - ### Loading: ComfyUI-Manager (V3.37)
2025-11-23T18:27:57.961504 - [ComfyUI-Manager] network_mode: public
2025-11-23T18:27:57.962503 - [ComfyUI-Manager] Since --preview-method is set, ComfyUI-Manager's preview method feature will be ignored.
2025-11-23T18:27:58.206531 - ### ComfyUI Revision: 4177 [265adad8] *DETACHED | Released on '2025-11-04'
2025-11-23T18:27:58.417303 - [MultiGPU Core Patching] Patching mm.soft_empty_cache for Comprehensive Memory Management (VRAM + CPU + Store Pruning)
2025-11-23T18:27:58.421752 - [MultiGPU Core Patching] Patching mm.get_torch_device, mm.text_encoder_device, mm.unet_offload_device
2025-11-23T18:27:58.422192 - [MultiGPU DEBUG] Initial current_device: xpu:0
2025-11-23T18:27:58.422697 - [MultiGPU DEBUG] Initial current_text_encoder_device: cpu
2025-11-23T18:27:58.422697 - [MultiGPU DEBUG] Initial current_unet_offload_device: cpu
2025-11-23T18:27:58.425703 - Traceback (most recent call last):
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\nodes.py", line 2131, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-multigpu\__init__.py", line 249, in <module>
    from .wanvideo import (
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-multigpu\wanvideo.py", line 14, in <module>
    from accelerate import init_empty_weights
ModuleNotFoundError: No module named 'accelerate'

2025-11-23T18:27:58.425703 - Cannot import D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-multigpu module for custom nodes: No module named 'accelerate'
2025-11-23T18:27:58.426703 - 
Import times for custom nodes:
2025-11-23T18:27:58.426703 -    0.0 seconds: D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-11-23T18:27:58.426703 -    0.0 seconds: D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-automaticcfg
2025-11-23T18:27:58.426703 -    0.0 seconds (IMPORT FAILED): D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-multigpu
2025-11-23T18:27:58.426703 -    0.1 seconds: D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-GGUF
2025-11-23T18:27:58.426703 -    0.5 seconds: D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-manager
2025-11-23T18:27:58.426703 - 
2025-11-23T18:27:58.750161 - Context impl SQLiteImpl.
2025-11-23T18:27:58.750161 - Will assume non-transactional DDL.
2025-11-23T18:27:58.752162 - No target revision found.
2025-11-23T18:27:58.761786 - ________________________________________________________________________
WARNING WARNING WARNING WARNING WARNING

Installed frontend version 1.23.4 is lower than the recommended version 1.28.8.

Please install the updated requirements.txt file by running:
D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\comfyui-backend-env\python.exe -s -m pip install -r D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\requirements.txt
If you are on the portable package you can run: update\update_comfyui.bat to solve this problem.

This error is happening because the ComfyUI frontend is no longer shipped as part of the main repo but as a pip package instead.
________________________________________________________________________
2025-11-23T18:27:58.761786 - Starting server

2025-11-23T18:27:58.761786 - To see the GUI go to: http://127.0.0.1:49000
2025-11-23T18:27:59.093991 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-11-23T18:27:59.127600 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-11-23T18:27:59.411206 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-11-23T18:27:59.630818 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-11-23T18:27:59.660818 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-11-23T18:28:03.812189 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-23T18:28:03.812189 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-23T18:28:03.965070 - FETCH ComfyRegistry Data: 5/1072025-11-23T18:28:03.965070 - 
2025-11-23T18:28:04.038682 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-23T18:28:04.042982 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-11-23T18:28:08.604103 - FETCH ComfyRegistry Data: 10/1072025-11-23T18:28:08.604103 - 
2025-11-23T18:28:13.033057 - FETCH ComfyRegistry Data: 15/1072025-11-23T18:28:13.033057 - 
2025-11-23T18:28:15.466612 - got prompt
2025-11-23T18:28:15.496274 - Using pytorch attention in VAE
2025-11-23T18:28:15.497174 - Using pytorch attention in VAE
2025-11-23T18:28:16.379573 - VAE load device: xpu:0, offload device: cpu, dtype: torch.bfloat16
2025-11-23T18:28:16.534173 - [MultiGPU Core Patching] text_encoder_device_patched returning device: cpu (current_text_encoder_device=cpu)
2025-11-23T18:28:16.534173 - Using scaled fp8: fp8 matrix mult: False, scale input: False
2025-11-23T18:28:16.970522 - Requested to load WanTEModel
2025-11-23T18:28:16.976522 - loaded completely; 95367431640625005117571072.00 MB usable, 6419.48 MB loaded, full load: True
2025-11-23T18:28:16.977510 - CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
2025-11-23T18:28:17.818611 - FETCH ComfyRegistry Data: 20/1072025-11-23T18:28:17.818611 - 
2025-11-23T18:28:23.180073 - FETCH ComfyRegistry Data: 25/1072025-11-23T18:28:23.180073 - 
2025-11-23T18:28:28.117556 - FETCH ComfyRegistry Data: 30/1072025-11-23T18:28:28.117556 - 
2025-11-23T18:28:33.622893 - FETCH ComfyRegistry Data: 35/1072025-11-23T18:28:33.622893 - 
2025-11-23T18:28:39.223046 - FETCH ComfyRegistry Data: 40/1072025-11-23T18:28:39.223046 - 
2025-11-23T18:28:44.346046 - FETCH ComfyRegistry Data: 45/1072025-11-23T18:28:44.346046 - 
2025-11-23T18:28:47.199580 - model weight dtype torch.bfloat16, manual cast: None
2025-11-23T18:28:47.199580 - model_type FLOW
2025-11-23T18:28:49.668166 - FETCH ComfyRegistry Data: 50/1072025-11-23T18:28:49.668166 - 
2025-11-23T18:28:53.087958 - Requested to load WAN22
2025-11-23T18:28:54.117434 - loaded partially; 4747.90 MB usable, 4747.90 MB loaded, 4788.50 MB offloaded, lowvram patches: 0
2025-11-23T18:28:54.563120 - FETCH ComfyRegistry Data: 55/1072025-11-23T18:28:54.563120 - 
2025-11-23T18:28:56.639391 - 
  0%|          | 0/20 [00:00<?, ?it/s]2025-11-23T18:28:59.427550 - FETCH ComfyRegistry Data: 60/1072025-11-23T18:28:59.427550 - 
2025-11-23T18:29:04.651660 - FETCH ComfyRegistry Data: 65/1072025-11-23T18:29:04.651660 - 
2025-11-23T18:29:14.444979 - FETCH ComfyRegistry Data: 70/1072025-11-23T18:29:14.444979 - 
2025-11-23T18:29:21.892000 - FETCH ComfyRegistry Data: 75/1072025-11-23T18:29:21.892000 - 
2025-11-23T18:29:24.682118 - 
  5%|▌         | 1/20 [00:28<08:52, 28.04s/it]2025-11-23T18:29:28.599509 - FETCH ComfyRegistry Data: 80/1072025-11-23T18:29:28.599509 - 
2025-11-23T18:29:35.959475 - FETCH ComfyRegistry Data: 85/1072025-11-23T18:29:35.959475 - 
2025-11-23T18:29:40.710871 - FETCH ComfyRegistry Data: 90/1072025-11-23T18:29:40.710871 - 
2025-11-23T18:29:45.342962 - FETCH ComfyRegistry Data: 95/1072025-11-23T18:29:45.342962 - 
2025-11-23T18:29:49.174114 - 
 10%|█         | 2/20 [00:52<07:47, 25.95s/it]2025-11-23T18:29:50.449283 - FETCH ComfyRegistry Data: 100/1072025-11-23T18:29:50.449283 - 
2025-11-23T18:29:55.713567 - FETCH ComfyRegistry Data: 105/1072025-11-23T18:29:55.713567 - 
2025-11-23T18:29:58.038269 - FETCH ComfyRegistry Data [DONE]2025-11-23T18:29:58.038269 - 
2025-11-23T18:29:58.146274 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-11-23T18:29:58.161274 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-11-23T18:29:58.161274 - 2025-11-23T18:29:59.332802 -  [DONE]2025-11-23T18:29:59.332802 - 
2025-11-23T18:29:59.385397 - [ComfyUI-Manager] All startup tasks have been completed.
2025-11-23T18:34:12.034867 - 
 65%|██████▌   | 13/20 [05:15<02:47, 23.97s/it]2025-11-23T18:34:24.196849 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2025-11-23T18:34:24.197850 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2025-11-23T18:34:24.201849 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2025-11-23T18:37:02.758974 - 
100%|██████████| 20/20 [08:06<00:00, 24.32s/it]2025-11-23T18:37:02.758974 - 
100%|██████████| 20/20 [08:06<00:00, 24.31s/it]2025-11-23T18:37:02.758974 - 
2025-11-23T18:37:02.768402 - Requested to load WanVAE
2025-11-23T18:37:04.280132 - 0 models unloaded.
2025-11-23T18:37:04.695237 - loaded completely; 4747.90 MB usable, 1344.09 MB loaded, full load: True
2025-11-23T18:46:02.585136 - !!! Exception during processing !!! Native API failed. Native API returns: 20 (UR_RESULT_ERROR_DEVICE_LOST)
2025-11-23T18:46:02.586124 - Traceback (most recent call last):
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\nodes.py", line 295, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\rootm\AppData\Local\Programs\AI Playground\resources\ComfyUI\comfy\sd.py", line 708, in decode
    out = self.process_output(self.first_stage_model.decode(samples, **vae_options).to(self.output_device).float())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Native API failed. Native API returns: 20 (UR_RESULT_ERROR_DEVICE_LOST)

2025-11-23T18:46:02.588124 - Prompt executed in 00:17:47
2025-11-23T18:46:03.231419 - Exception in thread 2025-11-23T18:46:03.231419 - Thread-7 (prompt_worker)2025-11-23T18:46:03.231419 - :


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"id":"91f6bbe2-ed41-4fd6-bac7-71d5b5864ecb","revision":0,"last_node_id":59,"last_link_id":108,"nodes":[{"id":38,"type":"CLIPLoader","pos":[-30,190],"size":[350,110],"flags":{},"order":0,"mode":0,"inputs":[{"localized_name":"CLIP名称","name":"clip_name","type":"COMBO","widget":{"name":"clip_name"},"link":null},{"localized_name":"类型","name":"type","type":"COMBO","widget":{"name":"type"},"link":null},{"localized_name":"设备","name":"device","shape":7,"type":"COMBO","widget":{"name":"device"},"link":null}],"outputs":[{"localized_name":"CLIP","name":"CLIP","type":"CLIP","slot_index":0,"links":[74,75]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CLIPLoader","models":[{"name":"umt5_xxl_fp8_e4m3fn_scaled.safetensors","url":"https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors","directory":"text_encoders"}]},"widgets_values":["umt5_xxl_fp8_e4m3fn_scaled.safetensors","wan","default"]},{"id":39,"type":"VAELoader","pos":[-30,350],"size":[350,60],"flags":{},"order":1,"mode":0,"inputs":[{"localized_name":"vae名称","name":"vae_name","type":"COMBO","widget":{"name":"vae_name"},"link":null}],"outputs":[{"localized_name":"VAE","name":"VAE","type":"VAE","slot_index":0,"links":[76,105]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"VAELoader","models":[{"name":"wan2.2_vae.safetensors","url":"https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan2.2_vae.safetensors","directory":"vae"}]},"widgets_values":["wan2.2_vae.safetensors"]},{"id":55,"type":"Wan22ImageToVideoLatent","pos":[380,540],"size":[271.9126892089844,150],"flags":{},"order":7,"mode":0,"inputs":[{"localized_name":"vae","name":"vae","type":"VAE","link":105},{"localized_name":"start_image","name":"start_image","shape":7,"type":"IMAGE","link":106},{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":null},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":null},{"localized_name":"length","name":"length","type":"INT","widget":{"name":"length"},"link":null},{"localized_name":"batch_size","name":"batch_size","type":"INT","widget":{"name":"batch_size"},"link":null}],"outputs":[{"localized_name":"Latent","name":"LATENT","type":"LATENT","links":[104]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"Wan22ImageToVideoLatent"},"widgets_values":[1280,704,121,1]},{"id":56,"type":"LoadImage","pos":[0,540],"size":[274.080078125,314],"flags":{},"order":2,"mode":4,"inputs":[{"localized_name":"图像","name":"image","type":"COMBO","widget":{"name":"image"},"link":null},{"localized_name":"选择文件上传","name":"upload","type":"IMAGEUPLOAD","widget":{"name":"upload"},"link":null}],"outputs":[{"localized_name":"图像","name":"IMAGE","type":"IMAGE","links":[106]},{"localized_name":"遮罩","name":"MASK","type":"MASK","links":null}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"LoadImage"},"widgets_values":["example.png","image"]},{"id":7,"type":"CLIPTextEncode","pos":[380,260],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":6,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":75},{"localized_name":"文本","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"条件","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[52]}],"title":"CLIP Text Encode (Negative Prompt)","properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CLIPTextEncode"},"widgets_values":["色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走"],"color":"#322","bgcolor":"#533"},{"id":59,"type":"MarkdownNote","pos":[-550,10],"size":[480,340],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[],"title":"Model Links","properties":{},"widgets_values":["[Tutorial](https://docs.comfy.org/tutorials/video/wan/wan2_2\n) | [教程](https://docs.comfy.org/zh-CN/tutorials/video/wan/wan2_2\n)\n\n**Diffusion Model**\n- [wan2.2_ti2v_5B_fp16.safetensors](https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors)\n\n**VAE**\n- [wan2.2_vae.safetensors](https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan2.2_vae.safetensors)\n\n**Text Encoder**   \n- [umt5_xxl_fp8_e4m3fn_scaled.safetensors](https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors)\n\n\nFile save location\n\n\nComfyUI/\n├───📂 models/\n│   ├───📂 diffusion_models/\n│   │   └───wan2.2_ti2v_5B_fp16.safetensors\n│   ├───📂 text_encoders/\n│   │   └─── umt5_xxl_fp8_e4m3fn_scaled.safetensors \n│   └───📂 vae/\n│       └── wan2.2_vae.safetensors\n\n"],"color":"#432","bgcolor":"#653"},{"id":6,"type":"CLIPTextEncode","pos":[380,50],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":5,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":74},{"localized_name":"文本","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"条件","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[46]}],"title":"CLIP Text Encode (Positive Prompt)","properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CLIPTextEncode"},"widgets_values":["Low contrast. In a retro 1970s-style subway station, a street musician plays in dim colors and rough textures. He wears an old jacket, playing guitar with focus. Commuters hurry by, and a small crowd gathers to listen. The camera slowly moves right, capturing the blend of music and city noise, with old subway signs and mottled walls in the background."],"color":"#232","bgcolor":"#353"},{"id":3,"type":"KSampler","pos":[850,130],"size":[315,474],"flags":{},"order":9,"mode":0,"inputs":[{"localized_name":"模型","name":"model","type":"MODEL","link":95},{"localized_name":"正面条件","name":"positive","type":"CONDITIONING","link":46},{"localized_name":"负面条件","name":"negative","type":"CONDITIONING","link":52},{"localized_name":"Latent图像","name":"latent_image","type":"LATENT","link":104},{"localized_name":"种子","name":"seed","type":"INT","widget":{"name":"seed"},"link":null},{"localized_name":"步数","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"cfg","name":"cfg","type":"FLOAT","widget":{"name":"cfg"},"link":null},{"localized_name":"采样器名称","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null},{"localized_name":"调度器","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"降噪","name":"denoise","type":"FLOAT","widget":{"name":"denoise"},"link":null}],"outputs":[{"localized_name":"Latent","name":"LATENT","type":"LATENT","slot_index":0,"links":[35]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"KSampler"},"widgets_values":[471501564568656,"randomize",20,5,"uni_pc","simple",1]},{"id":48,"type":"ModelSamplingSD3","pos":[850,20],"size":[210,58],"flags":{"collapsed":false},"order":8,"mode":0,"inputs":[{"localized_name":"模型","name":"model","type":"MODEL","link":94},{"localized_name":"移位","name":"shift","type":"FLOAT","widget":{"name":"shift"},"link":null}],"outputs":[{"localized_name":"模型","name":"MODEL","type":"MODEL","slot_index":0,"links":[95]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"ModelSamplingSD3"},"widgets_values":[8]},{"id":37,"type":"UNETLoader","pos":[-30,50],"size":[346.7470703125,82],"flags":{},"order":4,"mode":0,"inputs":[{"localized_name":"UNet名称","name":"unet_name","type":"COMBO","widget":{"name":"unet_name"},"link":null},{"localized_name":"数据类型","name":"weight_dtype","type":"COMBO","widget":{"name":"weight_dtype"},"link":null}],"outputs":[{"localized_name":"模型","name":"MODEL","type":"MODEL","slot_index":0,"links":[94]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"UNETLoader","models":[{"name":"wan2.2_ti2v_5B_fp16.safetensors","url":"https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors","directory":"diffusion_models"}]},"widgets_values":["wan2.2_ti2v_5B_fp16.safetensors","default"]},{"id":8,"type":"VAEDecode","pos":[1207.304931640625,115.38958740234375],"size":[210,46],"flags":{},"order":10,"mode":0,"inputs":[{"localized_name":"Latent","name":"samples","type":"LATENT","link":35},{"localized_name":"vae","name":"vae","type":"VAE","link":76}],"outputs":[{"localized_name":"图像","name":"IMAGE","type":"IMAGE","slot_index":0,"links":[107]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":58,"type":"SaveVideo","pos":[1240.6103515625,498.17413330078125],"size":[660,450],"flags":{},"order":12,"mode":0,"inputs":[{"localized_name":"视频","name":"video","type":"VIDEO","link":108},{"localized_name":"文件名前缀","name":"filename_prefix","type":"STRING","widget":{"name":"filename_prefix"},"link":null},{"localized_name":"格式","name":"format","type":"COMBO","widget":{"name":"format"},"link":null},{"localized_name":"编码器","name":"codec","type":"COMBO","widget":{"name":"codec"},"link":null}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"SaveVideo"},"widgets_values":["video/ComfyUI","auto","auto"]},{"id":57,"type":"CreateVideo","pos":[1343.402099609375,257.7666320800781],"size":[270,78],"flags":{},"order":11,"mode":0,"inputs":[{"localized_name":"图像","name":"images","type":"IMAGE","link":107},{"localized_name":"音频","name":"audio","shape":7,"type":"AUDIO","link":null},{"localized_name":"帧率","name":"fps","type":"FLOAT","widget":{"name":"fps"},"link":null}],"outputs":[{"localized_name":"视频","name":"VIDEO","type":"VIDEO","links":[108]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CreateVideo"},"widgets_values":[24]}],"links":[[35,3,0,8,0,"LATENT"],[46,6,0,3,1,"CONDITIONING"],[52,7,0,3,2,"CONDITIONING"],[74,38,0,6,0,"CLIP"],[75,38,0,7,0,"CLIP"],[76,39,0,8,1,"VAE"],[94,37,0,48,0,"MODEL"],[95,48,0,3,0,"MODEL"],[104,55,0,3,3,"LATENT"],[105,39,0,55,0,"VAE"],[106,56,0,55,1,"IMAGE"],[107,8,0,57,0,"IMAGE"],[108,57,0,58,0,"VIDEO"]],"groups":[{"id":1,"title":"Step1 - Load models","bounding":[-50,-20,400,453.6000061035156],"color":"#3f789e","font_size":24,"flags":{}},{"id":2,"title":"Step3 - Prompt","bounding":[370,-20,448.27801513671875,473.2060852050781],"color":"#3f789e","font_size":24,"flags":{}},{"id":3,"title":"For i2v, use Ctrl + B to enable","bounding":[-50,450,400,420],"color":"#3f789e","font_size":24,"flags":{}},{"id":4,"title":"Video Size & length","bounding":[370,470,291.9127197265625,233.60000610351562],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.8390545288824496,"offset":[376.01246011250686,104.65919290931124]},"frontendVersion":"1.25.1","VHS_latentpreview":false,"VHS_latentpreviewrate":0,"VHS_MetadataImage":true,"VHS_KeepIntermediate":true},"version":0.4}


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

### Other

<img width="1319" height="1014" alt="Image" src="https://github.com/user-attachments/assets/90a155a4-8fe4-4601-9401-44f2342c00ef" />

**Comment by a-One-Fan** [comment]
I've been getting this with my A770, using the latest driver. However, I suspect it's a driver/firmware bug. Intel memory management on windows has always been a bit iffy.
Not sure how correlated it is, but I also recently had llama cpp start crashing. Though, it didn't print any error and I haven't investigated it further.

**Comment by Kajakmann** [comment]
>Intel memory management on windows has always been a bit iffy. 

It's not just a  "windows" thing. Have the same problem with Ubuntu 25 and my Intel Arc B60. :)

<img width="1063" height="868" alt="Image" src="https://github.com/user-attachments/assets/3d6273f7-ba3e-4d15-ac98-ab14a483e455" />

**Comment by tks0721hg** [comment]
I'm having a similar problem. I'm using an A770 with Windows 11. My error message was "level_zero backend failed with error: 20 (UR_RESULT_ERROR_DEVICE_LOST)". If anyone knows how to fix this, please let me know.

**Comment by savvadesogle** [comment]
It works for me on A770 with driver 8509 
https://github.com/Comfy-Org/ComfyUI/discussions/476#discussioncomment-15841100
