### ISSUE TITLE
Loading .safetensors files requires double memory on DGX Spark

### ISSUE THREAD

**Issue by phaserblast** [comfyanonymous/ComfyUI#10896]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Loading .safetensors files on DGX Spark causes a problem because of the mandatory mmap used by safetensors.torch.load_file. I have been testing Flux.2-dev, and cannot load the FP16 model despite the DGX Spark having plenty of RAM for loading both the model and text encoder. It seems mmap is a disaster on DGX Spark due to the coherent memory implementation. The result is the safetensors loader tries to load the model twice: First to "RAM," then a copy to "VRAM," which obviously fails since there is no separate RAM/VRAM and we run out of memory loading large models.

This is also a problem with llama-server and LM Studio. With mmap enabled, llama-server tries to load GGUF models into "RAM" first, then copy to "VRAM." Disabling mmap solves the problem, and models can be loaded directly into memory _once_ without the additional move from "RAM" to "VRAM." A similar workaround with the safetensors model loader would be great, and would save time.

### Logs

```powershell

```

**Comment by A-Dalton** [comment]
I can confirm the finding on my DGX Spark with the same behavior.

Loading the BF16 Safetensor version causes the full 128 GB of unified memory to be used and after the Swap file is also fully utilized, the ComfyUI (*Python*) process gets killed.
Using the GGUF version (full BF16 GGFUF) in combination with the BF16 Safetensor `mistral_3_small_flux2_bf16.safetensors` for text encoding only uses roughly 90 GB of the memory.

I was however still unable to run the BF16 Safetensor for FLUX.2 when setting the `copy` argument to `false` for the `tensor.to` function in line 67 in `~/ComfyUI/comfy/utils.py`, even when starting ComfyUI with the `--disable-mmap` option - as it still runs out of memory.


Using the `--cache-none` option also solves the issue and I can execute the BF16 Safetensor for FLUX.2 with roughly 75 GB of memory used during sampling.

**Comment by phaserblast** [comment]
> Using the `--cache-none` option also solves the issue and I can execute the BF16 Safetensor for FLUX.2 with roughly 75 GB of memory used during sampling.

Not using --disable-mmap and instead using --cache-none works, but the model is unloaded after every run so this isn't really a solution. There needs to be a way to load the model the "correct" way, but to leave it in memory for the next run without using up every last byte of memory for no reason as is the case now.

These screenshots give an idea of the memory behavior before/after:

**Before using --cache-none:**
<img width="628" height="587" alt="Image" src="https://github.com/user-attachments/assets/e8fe1f0d-1273-46b2-aafc-a8f59deb88e4" />

**After using --cache-none:**
<img width="627" height="543" alt="Image" src="https://github.com/user-attachments/assets/690b58be-5fb9-4472-9633-99f6a49f5027" />

**Comment by phaserblast** [comment]
I tested this .safetensors loader:
https://github.com/foundation-model-stack/fastsafetensors

This will load a .safetensors file into VRAM directly from storage, bypassing the CPU->GPU copy. It loads the file in only a few seconds, as opposed to a few minutes with the standard safetensors.safe_open method. Perhaps a node can be written to use this loader instead of the default loader, as this is faster and way more efficient on DGX Spark by loading directly into VRAM using NVIDIA GPUDirect. Unfortunately it later fails if I omit the copy using .detach().clone() (pointless though, since it puts things back to square one), so maybe the tensors are falling out of scope before they're accessed. Maybe somewhere down the line after load_torch_file() ComfyUI expects the tensors to be on the CPU:

```
from fastsafetensors import fastsafe_open
with fastsafe_open(filenames=[ckpt], nogds=False, device=device, debug_log=True) as f:
				sd = {} # state dictionary
				for k in f.keys():
					sd[k] = f.get_tensor(k)
```

safetensors.safe_open _always_ loads to the CPU using mmap. I'm not sure how the copy is bypassed using --cache-none, but this still isn't a good solution since the model doesn't stay in VRAM after an inference run and it _**takes forever**_ to load the model again.

**Comment by A-Dalton** [comment]
> Not using --disable-mmap and instead using --cache-none works, but the model is unloaded after every run so this isn't really a solution.

I only mentioned the `--cache-none` option, as it is a way to execute FLUX.2 with the full BF16 Safetensor variants of both the text encoder and the diffusion model. But I fully agree that it should not be seen as the solution to the problem, if it can be fixed otherwise.

<br />
<br />

> safetensors.safe_open always loads to the CPU using mmap. I'm not sure how the copy is bypassed using --cache-none, but this still isn't a good solution since the model doesn't stay in VRAM after an inference run and it takes forever to load the model again.

To me it looks like the copy to RAM is not actually being bypassed, but rather the ComfyUI cache already contains cached output at the point where it runs OOM.
With `--cache-none` this output is never cached and therefore only the memory used by the current node is in memory.

Caching happens in the file `~\execution.py` when executing a Node with `execute_async` with the output of the nodes being cached to one of several cache implementations via `self.caches.outputs`. And the `NullCache` implementation (used with the argument `--cache-none`) simply discards the node output instead of caching anything.


**With some added additional logging, I can see that there are already some caches set before ComfyUI crashes because it runs OOM (the `Killed` line):**
```
got prompt
Setting HierarchicalCache cache for Node 10
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cuda:0, dtype: torch.bfloat16
Setting HierarchicalCache cache for Node 10
Setting HierarchicalCache cache for Node 47
Setting HierarchicalCache cache for Node 47
Setting HierarchicalCache cache for Node 48
Setting HierarchicalCache cache for Node 48
Setting HierarchicalCache cache for Node 16
Setting HierarchicalCache cache for Node 16
Setting HierarchicalCache cache for Node 38
Using MixedPrecisionOps for text encoder: 210 quantized layers
Requested to load Flux2TEModel_
loaded completely; 95367431640625005117571072.00 MB usable, 1280.59 MB loaded, full load: True
CLIP/text encoder model load device: cuda:0, offload device: cuda:0, current: cuda:0, dtype: torch.float16
Setting HierarchicalCache cache for Node 38
Setting HierarchicalCache cache for Node 38
Setting HierarchicalCache cache for Node 6
Setting HierarchicalCache cache for Node 6
Setting HierarchicalCache cache for Node 6
Setting HierarchicalCache cache for Node 26
Setting HierarchicalCache cache for Node 26
Setting HierarchicalCache cache for Node 12
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
Killed
```

**The Node Ids being:**
- 6 = CLIP Text Encode
- 10 = Load VAE
- 12 = Load Diffusion Model
- 16 = KSamplerSelect
- 26 = FluxGuidance
- 38 = Load CLIP
- 47 = Empty Flux 2 Latent
- 48 = Flux2Schedular


**And when using the FP8 version of FLUX.2 with some additional logging I can see that caches from various nodes are being reused on the second execution:**
```
got prompt
NO cached Node Id 6
NO cached Node Id 8
NO cached Node Id 9
Using cached Node Id 10
Using cached Node Id 12
NO cached Node Id 13
Using cached Node Id 16
NO cached Node Id 22
NO cached Node Id 25
NO cached Node Id 26
Using cached Node Id 38
Using cached Node Id 47
Using cached Node Id 48
loaded completely; 95367431640625005117571072.00 MB usable, 17180.59 MB loaded, full load: True
```


### **TLDR;**
With my limited knowledge it looks more like a limitation of the Safetensors library rather than something ComfyUI can actually solve with their current approach.

<br />
<br />

> I tested this .safetensors loader:
https://github.com/foundation-model-stack/fastsafetensors

Thanks for checking the fastsafetensors library and trying to get it working in ComfyUI!

I hope this might be something which can actually be used in ComfyUI in the future.
While I could not find a sample implementation of fastsafetensors for image generation (to check the different behavior), there is also a discussion thread in the official DGX Spark forum related to LLMs, which points to fastsafetensors bringing a huge improvement:
- https://forums.developer.nvidia.com/t/very-slow-mmap-on-dgx-spark-that-affects-model-loading-questions-to-nvidia/349886

**Comment by phaserblast** [comment]
I wrote a custom node that does what we want:
https://github.com/phaserblast/ComfyUI-DGXSparkSafetensorsLoader

I only tested it briefly. Give it a shot and let me know if it's working for you.

**Comment by A-Dalton** [comment]
Really cool - your custom node works pretty well in my initial testing.
Thanks for digging deeper and actually creating a (although very experimental) node for testing purposes!

In combination with the FP8 Mistral_3_small text encoder, image size of 2000x1504, using sageattention and a batch size of 4, your node is always faster when comparing it to the built-in diffusion model loader combined with the `--cache-none` argument.

Comparing it to the full BF16 GGUF I get about the same memory footprint (which is a bit higher than what you posted using `htop`) with the stable 2.9.1 version of PyTorch using CUDA 13.0.
Timewise your loader is much faster compared the GGUF loader upon the first full run (`00:41:08` vs. `00:37:03`), but for consecutive full runs I get slightly higher numbers (**GGUF:** `00:33:36|00:33:25|00:33:22` / **YOURS:**`00:36:11|00:35:52|00:35:47`).

Seeing how you were able to integrate it, I would love to see an official fastsafetensors support for ComfyUI, maybe similar to how the attention mechanism can be controlled via an argument.

**Comment by DomiStyle** [comment]
This happens on Strix Halo as well, FLUX.2 fails to load in BF16 because it loads to RAM first and then to VRAM.

The node by @phaserblast solves this. Full model fits comfortably into VRAM now.

**Comment by jovan2009** [comment]
I was excited to try this custom node with fastsafetensors but it seems that I am not able to compile fastsafetensors in windows. The features seem very interesting but...

**Comment by phaserblast** [comment]
> Seeing how you were able to integrate it, I would love to see an official fastsafetensors support for ComfyUI, maybe similar to how the attention mechanism can be controlled via an argument.

Thanks for testing. And yes, it would be great if this could be integrated into the normal model loader as an option!

**Comment by phaserblast** [comment]
> The node by [@phaserblast](https://github.com/phaserblast) solves this. Full model fits comfortably into VRAM now.

That's great news! I was wondering if this would work on AMD the same way, and I'm happy to hear it does.

**Comment by phaserblast** [comment]
> I was excited to try this custom node with fastsafetensors but it seems that I am not able to compile fastsafetensors in windows. The features seem very interesting but...

Yeah, fastsafetensors/cpp/ext.cpp looks quite Unix-ey, so it might need to be compiled with MinGW.

**Comment by jovan2009** [comment]
> > I was excited to try this custom node with fastsafetensors but it seems that I am not able to compile fastsafetensors in windows. The features seem very interesting but...
> 
> Yeah, fastsafetensors/cpp/ext.cpp looks quite Unix-ey, so it might need to be compiled with MinGW.

Forgive my lack of knowledge, are you saying that I might have a chance compiling fastsafetensors with MingGW in Windows? I will try if that's true, I used MSYS2 in the past but I don't have it on my computer currently. I even compiled apps inside termux on my 2015 android phone, very similar experience, but it's been a while since I dabbled in a "Linux like" terminal. But I could refresh my memory if it's worth trying.

Indeed, in ext.cpp are called some header .h files that I found out are Unix specific but I passed that compilation step finding their windows adapted variants (some projects on GitHub that have this exact purpose). But then I hit a wall when MSVC complained about a lot of "unreferenced functions", it was obvious it doesn't understand the code and I have no chance.

**Comment by phaserblast** [comment]
> Forgive my lack of knowledge, are you saying that I might have a chance compiling fastsafetensors with MingGW in Windows?

I'm not sure. ext.cpp includes sys/mman.h, which isn't part of the normal MinGW install as far as I can tell. You might have better luck running under WSL2 assuming all the CUDA stuff works. I haven't tried it.

Also, this: It looks like someone made a mman lib for Windows: https://github.com/alitrack/mman-win32 Apparently, this is a package that can be installed if you're using MSYS2. I wish I could be more help! I'm just not very familiar with Windows development outside of using WSL2.

**Comment by jovan2009** [comment]
Yeah, that was one of the files I searched for, I found probably the same project that you are referring to but it didn't help with MSVC, obviously, I was too naive. I will look into it more, thanks for your suggestions.

**Comment by phaserblast** [comment]
> Yeah, that was one of the files I searched for, I found probably the same project that you are referring to but it didn't help with MSVC, obviously, I was too naive. I will look into it more, thanks for your suggestions.

Now that I'm looking at ext.cpp, it seems mman.h is only needed if nogds_file_reader is used. gds_file_reader doesn't call mmap(). So I guess you can just remove the nogds_file_reader class from ext.cpp, remove the mman.h header include line and just make sure to set any options to ensure nogds_file_reader is never used.

Just a warning, gds_file_reader uses the NVIDIA GPUDirect API so you'll need the headers for that. They should be part of the normal CUDA toolkit install. I just checked and I have it in /usr/local/cuda/include/cufile.h. So you can toss mman.h if you have an NVIDIA GPU.

**Comment by frauttauteffasu** [comment]
Further from @phaserblast's observation `use_mmap` does not ever appear to be set to true so remove its use:
```patch
diff --git a/fastsafetensors/copier/gds.py b/fastsafetensors/copier/gds.py
index 9fde2af..7c77411 100644
--- a/fastsafetensors/copier/gds.py
+++ b/fastsafetensors/copier/gds.py
@@ -181,7 +181,7 @@ def new_gds_file_copier(
 
     if nogds:
         nogds_reader = fstcpp.nogds_file_reader(
-            False, bbuf_size_kb, max_threads, device_is_not_cpu
+            bbuf_size_kb, max_threads, device_is_not_cpu
         )
 
         def construct_nogds_copier(
diff --git a/fastsafetensors/cpp.pyi b/fastsafetensors/cpp.pyi
index 40fcb67..897ae53 100644
--- a/fastsafetensors/cpp.pyi
+++ b/fastsafetensors/cpp.pyi
@@ -13,7 +13,7 @@ class gds_device_buffer:
 
 class nogds_file_reader:
     def __init__(
-        self, use_mmap: bool, bbuf_size_kb: int, max_threads: int, use_cuda: bool
+        self, bbuf_size_kb: int, max_threads: int, use_cuda: bool
     ) -> None: ...
     def submit_read(
         self, fd: int, dst: gds_device_buffer, offset: int, length: int, ptr_off: int
diff --git a/fastsafetensors/cpp/ext.cpp b/fastsafetensors/cpp/ext.cpp
index ec89199..33a4dcf 100644
--- a/fastsafetensors/cpp/ext.cpp
+++ b/fastsafetensors/cpp/ext.cpp
@@ -6,7 +6,6 @@
 #include <fcntl.h>
 #include <cstring>
 #include <unistd.h>
-#include <sys/mman.h>
 #include <chrono>
 #include <dlfcn.h>
 #include <cstdlib>
@@ -468,26 +467,11 @@ const int gds_device_buffer::memmove(uint64_t _dst_off, uint64_t _src_off, const
 
 
 void nogds_file_reader::_thread(const int thread_id, ext_funcs_t *fns, const int fd, const gds_device_buffer& dst, const int64_t offset, const int64_t length, const uint64_t ptr_off, thread_states_t *s) {
-    void * src = nullptr;
     cudaError_t err;
     int64_t count;
     bool failed = false;
     void * buffer = reinterpret_cast<void*>(reinterpret_cast<uintptr_t>(s->_read_buffer) + s->_bbuf_size_kb * 1024 * (thread_id % s->_max_threads));
 
-    if (s->_use_mmap) {
-        std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
-        src = mmap(NULL, length, PROT_READ, MAP_PRIVATE, fd, offset);
-        if (src == MAP_FAILED) {
-            std::printf("nogds_file_reader._thread: mmap(fd=%d, offset=%" PRIu64 ", length=%" PRIu64 ") failed\n", fd, offset, length);
-            failed = true;
-            goto out;
-        }
-        if (debug_log) {
-            std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
-            std::printf("[DEBUG] nogds_file_reader._thread: mmap, fd=%d, offset=%" PRIu64 ", length=%" PRIu64 ", elapsed=%" PRId64 " us\n",
-                fd, offset, length, std::chrono::duration_cast<std::chrono::microseconds>(end - begin).count());
-        }
-    }
     count = 0;
     while (count < length) {
         int64_t l = length - count;
@@ -496,16 +480,11 @@ void nogds_file_reader::_thread(const int thread_id, ext_funcs_t *fns, const int
             l = (int64_t)(s->_bbuf_size_kb * 1024);
         }
         std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
-        if (s->_use_mmap) {
-            std::memcpy(buffer, (void *)((uintptr_t)src + count), l);
-            c = l;
-        } else {
-            c = pread(fd, buffer, l, offset + count);
-            if (c != l) {
-                std::printf("nogds_file_reader._thread failed: pread(fd=%d, buffer=%p, offset=%" PRIu64 ", count=%" PRIi64 ", l=%" PRIi64 "), c=%" PRIi64 "\n", fd, buffer, offset, count, l, c);
-                failed = true;
-                goto out;
-            }
+        c = pread(fd, buffer, l, offset + count);
+        if (c != l) {
+            std::printf("nogds_file_reader._thread failed: pread(fd=%d, buffer=%p, offset=%" PRIu64 ", count=%" PRIi64 ", l=%" PRIi64 "), c=%" PRIi64 "\n", fd, buffer, offset, count, l, c);
+            failed = true;
+            goto out;
         }
         std::chrono::steady_clock::time_point memcpy_begin = std::chrono::steady_clock::now();
         err = fns->cudaMemcpy(dst._get_raw_pointer(ptr_off + count, c), buffer, c, cudaMemcpyHostToDevice);
@@ -519,8 +498,8 @@ void nogds_file_reader::_thread(const int thread_id, ext_funcs_t *fns, const int
         count += c;
         if (debug_log) {
             std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
-            std::printf("[DEBUG] nogds_file_reader._thread: read (mmap=%d), fd=%d, offset=%" PRIu64 ", count=%" PRIi64 ", c=%" PRIi64 ", copy=%" PRId64 " us, cuda_copy=%" PRId64 " us\n",
-                s->_use_mmap, fd, offset, count, c, std::chrono::duration_cast<std::chrono::microseconds>(memcpy_begin - begin).count(), std::chrono::duration_cast<std::chrono::microseconds>(end - memcpy_begin).count());
+            std::printf("[DEBUG] nogds_file_reader._thread: read, fd=%d, offset=%" PRIu64 ", count=%" PRIi64 ", c=%" PRIi64 ", copy=%" PRId64 " us, cuda_copy=%" PRId64 " us\n",
+                fd, offset, count, c, std::chrono::duration_cast<std::chrono::microseconds>(memcpy_begin - begin).count(), std::chrono::duration_cast<std::chrono::microseconds>(end - memcpy_begin).count());
         }
     }
 out:
@@ -533,9 +512,6 @@ out:
         }
         s->_result_cond.notify_one();
     }
-    if (s->_use_mmap && src != nullptr) {
-        munmap(src, length);
-    }
 }
 
 const int nogds_file_reader::submit_read(const int fd, const gds_device_buffer& dst, const int64_t offset, const int64_t length, const uint64_t ptr_off)
@@ -829,7 +805,7 @@ PYBIND11_MODULE(__MOD_NAME__, m)
     };
 
     pybind11::class_<nogds_file_reader>(m, "nogds_file_reader")
-        .def(pybind11::init<const bool, const uint64_t, const int, bool>())
+        .def(pybind11::init<const uint64_t, const int, bool>())
         .def("submit_read", nogds_submit_read)
         .def("wait_read", nogds_wait_read);
 
diff --git a/fastsafetensors/cpp/ext.hpp b/fastsafetensors/cpp/ext.hpp
index 762fa0c..d1da1f1 100644
--- a/fastsafetensors/cpp/ext.hpp
+++ b/fastsafetensors/cpp/ext.hpp
@@ -135,15 +135,14 @@ private:
         std::condition_variable _result_cond;
         std::map<int, void *> _results;
         void * _read_buffer;
-        const bool _use_mmap;
         const uint64_t _bbuf_size_kb;
         const uint64_t _max_threads;
     } thread_states_t;
     thread_states_t _s;
 public:
-    nogds_file_reader(const bool use_mmap, const uint64_t bbuf_size_kb, const uint64_t max_threads, bool use_cuda):
+    nogds_file_reader(const uint64_t bbuf_size_kb, const uint64_t max_threads, bool use_cuda):
         _next_thread_id(1), _threads(nullptr), _fns(use_cuda?&cuda_fns:&cpu_fns),
-        _s(thread_states_t{._read_buffer = nullptr, ._use_mmap = use_mmap,
+        _s(thread_states_t{._read_buffer = nullptr,
             ._bbuf_size_kb = (bbuf_size_kb + max_threads - 1)/max_threads, ._max_threads = max_threads})
          {}
 
diff --git a/tests/test_fastsafetensors.py b/tests/test_fastsafetensors.py
index 1f4ff28..b315bd1 100644
--- a/tests/test_fastsafetensors.py
+++ b/tests/test_fastsafetensors.py
@@ -82,7 +82,7 @@ def run_nogds_file_read(
     size = meta.size_bytes - meta.header_length
     device, dev_is_gpu = get_and_check_device(framework)
     gbuf = framework.alloc_tensor_memory(size, device)
-    reader = fstcpp.nogds_file_reader(False, 20 * 1024, 1, dev_is_gpu)
+    reader = fstcpp.nogds_file_reader(20 * 1024, 1, dev_is_gpu)
     req = reader.submit_read(fd, gbuf, meta.header_length, size, 0)
     assert req > 0
     assert reader.wait_read(req) >= 0
@@ -297,7 +297,7 @@ def test_nogds_file_reader(fstcpp_log, input_files, framework) -> None:
     assert fd > 0
     device, dev_is_gpu = get_and_check_device(framework)
     gbuf = framework.alloc_tensor_memory(s.st_size, device)
-    reader = fstcpp.nogds_file_reader(False, 256 * 1024, 4, dev_is_gpu)
+    reader = fstcpp.nogds_file_reader(256 * 1024, 4, dev_is_gpu)
     step = s.st_size // 4
     reqs = []
     off = 0
@@ -324,7 +324,7 @@ def test_NoGdsFileCopier(fstcpp_log, input_files, framework) -> None:
     print("test_NoGdsFileCopier")
     meta = SafeTensorsMetadata.from_file(input_files[0], framework)
     device, dev_is_gpu = get_and_check_device(framework)
-    reader = fstcpp.nogds_file_reader(False, 256 * 1024, 4, dev_is_gpu)
+    reader = fstcpp.nogds_file_reader(256 * 1024, 4, dev_is_gpu)
     copier = NoGdsFileCopier(meta, device, reader, framework, True)
     gbuf = copier.submit_io(False, 10 * 1024 * 1024 * 1024)
     tensors = copier.wait_io(gbuf)
```

**Comment by lostdisc** [comment]
> This happens on Strix Halo as well, FLUX.2 fails to load in BF16 because it loads to RAM first and then to VRAM.
> 
> The node by [@phaserblast](https://github.com/phaserblast) solves this. Full model fits comfortably into VRAM now.

Would this help with Strix Point as well?  I'd love to try it, but I'm on Windows too, haha.

**Comment by DomiStyle** [comment]
@lostdisc I don't see why not, they also used shared RAM/VRAM.

**Comment by phaserblast** [comment]
> Would this help with Strix Point as well? I'd love to try it, but I'm on Windows too, haha.

fastsafetensors on Windows presents a minor problem because it requires mmap() if not using GPUDirect. But, GPUDirect is an NVIDIA thing. So it should be pretty straightforward to port the C++ stuff to Windows if not using mmap(), but this may only benefit users with NVIDIA GPUs. See the above posts for details on that.

**Comment by frauttauteffasu** [comment]
As of writing ROCM support is not any any release of fastsafetensors so you will need git head. I think the next likely build failure would be the use of `dlopen` I think even if it does build it will still fail even as the the ROCM library name is hardcoded to `libamdhip64.so` on https://github.com/foundation-model-stack/fastsafetensors/blob/main/fastsafetensors/cpp/cuda_compat.h#L25. I think WSL as has been mentioned already would stand a much higher chance of working. Still speculation though.

**Comment by frauttauteffasu** [comment]
@phaserblast have you tried https://github.com/huggingface/safetensors/pull/676 plus an edit to ComfyUI/comfy/utils.py to add `, use_gds=True` to the safetensors.safe_open call?

**Comment by jerkstorecaller** [comment]
@phaserblast 

I'm using the built-in ComfyUI template titled Flux.2 Dev Text To Image, your loader node helps me get past the VRAM OOM. However, generations are random noise.

- I swapped the base workflow's Load Diffusion Model with your node. Now the workflow loads, using 75/120GB memory
- Problem: the image generated is just analog noise (screenshot below)
- Question: you only provided a model loader node, not a Load Clip node. And yet, Mistral from Load Clip isn't using double memory. Why is that? I know it was using double memory before. Does adding your node somehow "patch" all other safetensor loading in the workflow? Or is this just a matter of temporary memory and because I have enough to fix 1x model and 2x Mistral, I stay under the 120GB limit and Comfy can later unload the duplicate Mistral?
- Question: During the loading phase, memory went as high as 102/120GB, before going back down to 75. Why is that? Why wouldn't it peak at 75?
- Question: If I click Comfy Manager's "Unload models" and "Free model and node cache" buttons after using your node, memory usage goes down from 75GB to 40GB only (I use 5GB at idle). So it's keeping one model loaded, and I'm guessing it's the one loaded by your new loader node. I don't have this issue with eg Z-Image Turbo workflow which doesn't require custom nodes.

All outputs give this:

<img width="592" height="609" alt="Image" src="https://github.com/user-attachments/assets/788b4775-5a80-4c2a-aaf9-d83f575eef77" />

**Comment by phaserblast** [comment]
> * Problem: the image generated is just analog noise (screenshot below)

I recall encountering this problem early on. I think the solution was to run the text encoder on the CPU. This isn't ideal, but as long as you use the same prompt ComfyUI should cache the embeddings so you won't see any performance issues on subsequent runs.

> * Question: you only provided a model loader node, not a Load Clip node. And yet, Mistral from Load Clip isn't using double memory. Why is that? I know it was using double memory before. Does adding your node somehow "patch" all other safetensor loading in the workflow? Or is this just a matter of temporary memory and because I have enough to fix 1x model and 2x Mistral, I stay under the 120GB limit and Comfy can later unload the duplicate Mistral?

Are you running the text encoder on the GPU? My loader is super hacky and probably messes with the ComfyUI state in incorrect ways since it bypasses a lot of ComfyUI's own stuff.

> * Question: During the loading phase, memory went as high as 102/120GB, before going back down to 75. Why is that? Why wouldn't it peak at 75?

Hmm, I'm not sure. It sounds like a memory leak after an attempt to load the model a second time. There's currently no way to free the memory allocated by the fastsafetensors calls to cudaMalloc since ComfyUI wasn't responsible for the allocation and therefore there's no handle to it. There may be a way to work this out so ComfyUI can free it, but I haven't figured that out yet.

> * Question: If I click Comfy Manager's "Unload models" and "Free model and node cache" buttons after using your node, memory usage goes down from 75GB to 40GB only (I use 5GB at idle). So it's keeping one model loaded, and I'm guessing it's the one loaded by your new loader node. I don't have this issue with eg Z-Image Turbo workflow which doesn't require custom nodes.

Again, ComfyUI doesn't have any way to free the memory used by fastsafetensors/cuFile. This is being done on the C/C++ backend, and  ComfyUI doesn't know about it. The only way to free it as far as I know is to make another C call to the matching cuFile* stuff. This can possibly be wrapped in Python, but ComfyUI would need to call this custom Python function. I opened an issue on the ComfyUI GitHub about implementing a callback feature, but no progress on that yet.

**Comment by jerkstorecaller** [comment]
Sigh. What's unfortunate is that this means Spark users are effectively locked out of easily using Comfy workflows if they require > 60GB VRAM. 
I thought buying a DGX Spark was the perfect lazy/casual choice where everything just works up to 120GB VRAM, just more slowly. No worrying about offloading, no worrying about workflows not working because it's still Nvidia.

If I had known the Spark had this problem on Comfy (and I did a lot of research before buying and no one posting benchmarks ever brought up double memory!), I wouldn't have bought it. I already was feeling like I overpaid at $3000, but now that feeling has doubled. **BUYERS BEWARE.**

Even if your custom node was working perfectly, so much tinkering seems to be required, and we still need other loaders for other safetensors in the workflow. Any non-standard community stuff probably wouldn't work either. And you can't build API-driven workflows against Comfy directly, since starting/stopping Comfy is a required operation to swap models!

@comfyanonymous can anything be done about this? DGX Spark and Strix Halo (to a lesser extent since the Strix is awful slow at image models) are two popular options cheap people use for home AI inference.

**Comment by phaserblast** [comment]
> If I had known the Spark had this problem on Comfy (and I did a lot of research before buying and no one posting benchmarks ever brought up double memory!), I wouldn't have bought it. I already was feeling like I overpaid at $3000, but now that feeling has doubled. **BUYERS BEWARE.**

I'm sure this will all get sorted at some point. Nvidia are aware of the mmap problem and are working on it, from what I understand. This may be resolved in a future kernel patch, maybe. Or maybe the Comfy folks will do the right thing and add GPUDirect loading natively for supported devices. I prefer the latter.

**Comment by luix93** [comment]
Is there an update on this? Has it been fixed?

**Comment by frauttauteffasu** [comment]
@phaserblast would it be possible to add a Load Clip node with GDS support? Using your node to load the BF16 FLUX.2 safetensor and the standard Clip Loader with --disable-mmap for Mistral requires 4GB of swap in addition to full RAM use.

**Comment by phaserblast** [comment]
> would it be possible to add a Load Clip node with GDS support?

Sure, I can take a look at it. You'll likely need to run the float 16 version of the text encoder since my loader doesn't work with quantized models right now.

**Comment by luix93** [comment]
The latest kernel update (6.17.0-1008-nvidia) didn't fix this issue, any update from @comfyanonymous regarding a potential patch?

**Comment by Balaxxe** [comment]
No changes with latest kernel - @comfyanonymous is this something you are working with Nvidia on? 

Any insight would be greatly appreciated.

**Comment by broken-gage** [comment]
Still having this issue as of 4/4/2026. 

Side note: spent some time investigating GDS, turns out GB10 doesn't support GDS either. In the meantime I'm using custom nodes to load models into the VRAM. Cannot bypass the RAM >> VRAM loading process, but the models stay in VRAM during and after the workflow is completed, and no RAM cache on the model, the load time basically doubled, but about 20% boost in performance after models fully loaded, which works great when I have hundreds of repeat runs on a single workflow. 

@comfyanonymous it would be very appreciated if there is any update on the issue. I really wish there is a --unified-memory flag that we can use to fix this issue, it would probably be beneficial to strix halo and apple silicon system too.

**Comment by Balaxxe** [comment]
heads up - the dynamic vram updated finally addressed this. try it out :)

**Comment by broken-gage** [comment]
Test with --disable-mmap flag. Native FLUX dev and klein workflow. I can confirm that double loading issue is resolved with DGX Spark / GB10.  

The caveat I found so far is that the loading path is likely still routing through CPU therefore the loading speed of the model weight is still suboptimal on the native path (~200MB/s with PCIE4.0 SSD) compare to fastsafetensors (~1500MB/s, same SSD).

Side note: it also breaks all the fastsafetensors and instanttensor loading, as they will double load the VRAM under the new dynamic VRAM pipeline...

**Comment by lathrodectus** [comment]
Any updates on this?

**Comment by broken-gage** [comment]
> Any updates on this?

Do you still experience the issue? It has been resolved on my end since version 0.22.0

**Comment by rattus128** [comment]
closing as fixed. DGX spark loading should be fixed. Please post fresh information if re-opening.
