### ISSUE TITLE
Getting this CUDA error all of a sudden after one or two gens

### ISSUE THREAD

**Issue by gonzalu** [comfyanonymous/ComfyUI#11331]
```
Requested to load Flux2TEModel_
loaded completely; 21472.80 MB usable, 17180.60 MB loaded, full load: True
Requested to load Flux2
loaded partially; 15401.26 MB usable, 13113.03 MB loaded, 20700.00 MB offloaded, 2268.00 MB buffer reserved, lowvram patches: 119
100%|█████████████████████████████████████████████████████████████████████████████████████████| 20/20 [02:03<00:00,  6.15s/it]
Requested to load AutoencoderKL
Unloaded partially: 4689.03 MB freed, 8424.00 MB remains loaded, 2268.00 MB buffer reserved, lowvram patches: 134
loaded completely; 1414.53 MB usable, 160.31 MB loaded, full load: True
Prompt executed in 190.03 seconds
got prompt
SELECTED: input3
[Inspire Pack] LoadSinglePromptFromFile: file found 'personal\AI Prompts Megapack 015.txt'
SELECTED: input3
Requested to load Flux2TEModel_
!!! Exception during processing !!! CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 515, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "E:\ComfyUI\ComfyUI\execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\nodes.py", line 77, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\comfy\sd.py", line 205, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\comfy\sd.py", line 267, in encode_from_tokens
    self.load_model()
  File "E:\ComfyUI\ComfyUI\comfy\sd.py", line 301, in load_model
    model_management.load_model_gpu(self.patcher)
  File "E:\ComfyUI\ComfyUI\comfy\model_management.py", line 706, in load_model_gpu
    return load_models_gpu([model])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\comfy\model_management.py", line 671, in load_models_gpu
    free_memory(total_memory_required[device] * 1.1 + extra_mem, device)
  File "E:\ComfyUI\ComfyUI\comfy\model_management.py", line 603, in free_memory
    if current_loaded_models[i].model_unload(memory_to_free):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\comfy\model_management.py", line 526, in model_unload
    freed = self.model.partially_unload(self.model.offload_device, memory_to_free)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\comfy\model_patcher.py", line 917, in partially_unload
    m.to(device_to)
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1369, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\comfy\ops.py", line 642, in _apply
    self.register_parameter(key, torch.nn.Parameter(fn(param), requires_grad=False))
                                                    ^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1355, in convert
    return t.to(
           ^^^^^
torch.AcceleratorError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Prompt executed in 2.57 seconds
Exception in thread Thread-13 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "E:\ComfyUI\ComfyUI\main.py", line 272, in prompt_worker
    comfy.model_management.soft_empty_cache()
  File "E:\ComfyUI\ComfyUI\comfy\model_management.py", line 1520, in soft_empty_cache
    torch.cuda.empty_cache()
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\cuda\memory.py", line 224, in empty_cache
    torch._C._cuda_emptyCache()
torch.AcceleratorError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Stopped server
Unhandled exception caught in c10/util/AbortHandler.h
00007FFD08843A74 <unknown symbol address> torch_python.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDD8ED19D7 <unknown symbol address> ucrtbase.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDB9551AAB <unknown symbol address> VCRUNTIME140_1.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDB9552317 <unknown symbol address> VCRUNTIME140_1.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDB955237A <unknown symbol address> VCRUNTIME140_1.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDB9554149 <unknown symbol address> VCRUNTIME140_1.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDDB7462FF <unknown symbol address> ntdll.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDDB5F2327 <unknown symbol address> ntdll.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDDB5EA961 <unknown symbol address> ntdll.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDD87F782A <unknown symbol address> KERNELBASE.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDC64A6720 <unknown symbol address> VCRUNTIME140.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDACE68196 <unknown symbol address> c10_cuda.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDACE6DD42 <unknown symbol address> c10_cuda.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDACE6DBBC <unknown symbol address> c10_cuda.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD7598495E <unknown symbol address> c10.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFBE43447E5 <unknown symbol address> torch_cpu.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD7596FB92 <unknown symbol address> c10.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD759A927C <unknown symbol address> c10.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD759A9873 <unknown symbol address> c10.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFBE42E9B68 <unknown symbol address> torch_cpu.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD08851575 <unknown symbol address> torch_python.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD088F55FB <unknown symbol address> torch_python.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD088F58FE <unknown symbol address> torch_python.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C0BB <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C0BB <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98DFA9 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C0BB <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C1C6 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98DFA9 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C0BB <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C0BB <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98DFA9 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C0BB <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98DFA9 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98DD54 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C989DB4 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C989DB4 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98B87A <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98DE50 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C98C13C <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C96F9A2 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C96FBD2 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C96FC9A <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1C96E3E2 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1CA2EE80 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1CA2EE3C <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1CA0B1AD <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1CA09B32 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFD1CA09579 <unknown symbol address> python311.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FF7325E1230 <unknown symbol address> python.exe!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDDA55E8D7 <unknown symbol address> KERNEL32.DLL!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDDB66C53C <unknown symbol address> ntdll.dll!<unknown symbol> [<unknown file> @ <unknown line number>]
```

**Comment by TristanWillcox** [comment]
same thing hoping to get this fixed

**Comment by gonzalu** [comment]
I rebooted and it has gone away. If you use your GPU to drive large monitor(S) as high res, this eats up VRAM a lot too and it causes the system to run on the edge. 

Anyway, rebooting my PC did the trick. Flux.2 Dev is a beast.

**Comment by treeshark12** [comment]
Sub-stack overflow it tanks the card. Using VAE tiled helps as it reduces memory usage. Also occasionally clear the models and empty the execution cache.
