### ISSUE TITLE
Pinned-memory causing ComfyUI OOM crash under WSL

### ISSUE THREAD

**Issue by HelloClyde** [comfyanonymous/ComfyUI#11531]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

ComfyUI can run normally and complete the workflow.

### Actual Behavior

When running the official z-image-turbo workflow, everything works fine, including the ksampler. However, during the VAE decode step, when loading the model, a CUDA OOM (Out of Memory) error occurs, causing the program to crash.

I performed debugging and found that when attempting to load the AutoencodingEngine during VAE decode, there was insufficient GPU memory, so it started unloading models previously loaded into CUDA. An error(terminate called after throwing an instance of 'c10::AcceleratorError' what():  CUDA error: out of memory) occurred during the execution of partially_unload at m.to(device_to). Since this is an exception from the PyTorch lib, it could not be caught at the Python layer, leading to a crash of ComfyUI.

During debugging, I noticed that there was sufficient GPU memory available (with 3GB remaining) when performing partially_unload. Even accounting for some additional memory required by tensor.to, it shouldn't have caused an OOM error. Therefore, I shifted the focus of investigation to RAM. Considering that pinned memory was recently updated, I tried using the --disable-pinned-memory option, and the issue was resolved.

### Steps to Reproduce

env: windows 10   + wsl2(ubuntu)
64G ram + RTX 4090-24G
I allocated 47GB of memory to WSL2.

cmd: python main.py --listen 0.0.0.0  --disable-all-custom-nodes
running the official z-image-turbo workflow

### Debug Logs

```powershell
loaded completely; 14008.43 MB usable, 11739.55 MB loaded, full load: True
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.32it/s]
Requested to load AutoencodingEngine
terminate called after throwing an instance of 'c10::AcceleratorError'
  what():  CUDA error: out of memory
Search for `cudaErrorMemoryAllocation' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x7d3c9e37cb80 in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x11fb7 (0x7d3c9e663fb7 in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x5c051 (0x7d3c9e6ae051 in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x48cb9f (0x7d3c7ea8cb9f in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::copy_tensor_metadata_except_version_counter(c10::TensorImpl const*, c10::TensorImpl*, bool) + 0x1b5 (0x7d3c9e35b1d5 in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #5: c10::TensorImpl::copy_tensor_metadata(c10::TensorImpl const*, c10::TensorImpl*, c10::VariableVersion const&, bool) + 0x14 (0x7d3c9e35b224 in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0x55347d8 (0x7d3c6f1347d8 in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x7cf76a (0x7d3c7edcf76a in /root/miniconda3/envs/comfyui2/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #8: _PyObject_GenericSetAttrWithDict + 0x6dc (0x4fd31c in /root/miniconda3/envs/comfyui2/bin/python)
frame #9: PyObject_SetAttr + 0x69 (0x4fcb59 in /root/miniconda3/envs/comfyui2/bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x3f1a (0x51499a in /root/miniconda3/envs/comfyui2/bin/python)
frame #11: /root/miniconda3/envs/comfyui2/bin/python() [0x55774f]
frame #12: /root/miniconda3/envs/comfyui2/bin/python() [0x556d63]
frame #13: PyObject_Call + 0xa2 (0x542292 in /root/miniconda3/envs/comfyui2/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x44bd (0x514f3d in /root/miniconda3/envs/comfyui2/bin/python)
frame #15: /root/miniconda3/envs/comfyui2/bin/python() [0x5e061a]
frame #16: /root/miniconda3/envs/comfyui2/bin/python() [0x5e2d26]
frame #17: /root/miniconda3/envs/comfyui2/bin/python() [0x540adb]
frame #18: PyObject_VectorcallMethod + 0x82 (0x50abc2 in /root/miniconda3/envs/comfyui2/bin/python)
frame #19: /root/miniconda3/envs/comfyui2/bin/python() [0x4316e3]
frame #20: /root/miniconda3/envs/comfyui2/bin/python() [0x5e061a]
frame #21: /root/miniconda3/envs/comfyui2/bin/python() [0x5e2d26]
frame #22: /root/miniconda3/envs/comfyui2/bin/python() [0x540adb]
frame #23: PyObject_VectorcallMethod + 0x82 (0x50abc2 in /root/miniconda3/envs/comfyui2/bin/python)
frame #24: /root/miniconda3/envs/comfyui2/bin/python() [0x4316e3]
frame #25: /root/miniconda3/envs/comfyui2/bin/python() [0x5e061a]
frame #26: /root/miniconda3/envs/comfyui2/bin/python() [0x5e2d26]
frame #27: /root/miniconda3/envs/comfyui2/bin/python() [0x540adb]
frame #28: PyObject_VectorcallMethod + 0x82 (0x50abc2 in /root/miniconda3/envs/comfyui2/bin/python)
frame #29: /root/miniconda3/envs/comfyui2/bin/python() [0x4316e3]
frame #30: /root/miniconda3/envs/comfyui2/bin/python() [0x5e061a]
frame #31: /root/miniconda3/envs/comfyui2/bin/python() [0x5e2d26]
frame #32: /root/miniconda3/envs/comfyui2/bin/python() [0x540adb]
frame #33: PyObject_VectorcallMethod + 0x82 (0x50abc2 in /root/miniconda3/envs/comfyui2/bin/python)
frame #34: /root/miniconda3/envs/comfyui2/bin/python() [0x4316e3]
frame #35: /root/miniconda3/envs/comfyui2/bin/python() [0x5e061a]
frame #36: <unknown function> + 0x786a (0x7d3ca418f86a in /root/miniconda3/envs/comfyui2/lib/python3.11/lib-dynload/_asyncio.cpython-311-x86_64-linux-gnu.so)
frame #37: _PyObject_MakeTpCall + 0x254 (0x504f04 in /root/miniconda3/envs/comfyui2/bin/python)
frame #38: /root/miniconda3/envs/comfyui2/bin/python() [0x4c509b]
frame #39: /root/miniconda3/envs/comfyui2/bin/python() [0x51e247]
frame #40: _PyEval_EvalFrameDefault + 0x9288 (0x519d08 in /root/miniconda3/envs/comfyui2/bin/python)
frame #41: _PyFunction_Vectorcall + 0x173 (0x5380f3 in /root/miniconda3/envs/comfyui2/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x44bd (0x514f3d in /root/miniconda3/envs/comfyui2/bin/python)
frame #43: /root/miniconda3/envs/comfyui2/bin/python() [0x55774f]
frame #44: /root/miniconda3/envs/comfyui2/bin/python() [0x556d98]
frame #45: _PyEval_EvalFrameDefault + 0x44bd (0x514f3d in /root/miniconda3/envs/comfyui2/bin/python)
frame #46: _PyFunction_Vectorcall + 0x173 (0x5380f3 in /root/miniconda3/envs/comfyui2/bin/python)
frame #47: _PyObject_FastCallDictTstate + 0x65 (0x5085f5 in /root/miniconda3/envs/comfyui2/bin/python)
frame #48: _PyObject_Call_Prepend + 0x66 (0x540076 in /root/miniconda3/envs/comfyui2/bin/python)
frame #49: /root/miniconda3/envs/comfyui2/bin/python() [0x611203]
frame #50: PyObject_Call + 0x20b (0x5423fb in /root/miniconda3/envs/comfyui2/bin/python)
frame #51: /root/miniconda3/envs/comfyui2/bin/python() [0x62bbbf]
frame #52: /root/miniconda3/envs/comfyui2/bin/python() [0x5f9f84]
frame #53: <unknown function> + 0x8609 (0x7d3ca765a609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #54: clone + 0x43 (0x7d3ca7425353 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by HelloClyde** [comment]
To add more context, I looked into the code related to MAX_PINNED_MEMORY, and since WSL is recognized as a Linux system, the MAX_PINNED_MEMORY is set to 45GB (I allocated 47GB to WSL2 out of a total of 64GB). 

I suspect that the large size of MAX_PINNED_MEMORY might be causing the issue. However, even after manually reducing it to 15GB, the error`terminate called after throwing an instance of 'c10::AcceleratorError' what():  CUDA error: out of memory` still occurs.


```
if not args.disable_pinned_memory:
    if is_nvidia() or is_amd():
        if WINDOWS:
            MAX_PINNED_MEMORY = get_total_memory(torch.device("cpu")) * 0.45  # Windows limit is apparently 50%
        else:
            MAX_PINNED_MEMORY = get_total_memory(torch.device("cpu")) * 0.95
        logging.info("Enabled pinned memory {}".format(MAX_PINNED_MEMORY // (1024 * 1024)))
```

**Comment by ervinpapp** [comment]
I experience the same when I use WAN2.2 workflow with lightning lora. It works fine but as soon as the VAE decode starts (after the 2nd KSampler) ComfyUI crashes. Windows 11, 64 GB RAM and RTX 5060 TI 16GB GPU.  In the Windows system logs I see torch related crash.

**Comment by rattus128** [comment]
@HelloClyde can you try this PR?

https://github.com/comfyanonymous/ComfyUI/pull/10738

**Comment by HelloClyde** [comment]
> [@HelloClyde](https://github.com/HelloClyde) can you try this PR?
> 
> [#10738](https://github.com/comfyanonymous/ComfyUI/pull/10738)

it works! 

After switching to this PR, the workflows for ZIT and WAN that previously failed are now able to run normally.

PS: I can see that cudaHostRegister is still failing, but it indeed no longer affects the workflow execution.

**Comment by HelloClyde** [comment]
After commit [9ca7e143afe6f09734c9aefcc85f491c5c0dc6e0](https://github.com/comfyanonymous/ComfyUI/commit/9ca7e143afe6f09734c9aefcc85f491c5c0dc6e0), the issue has been resolved.
