### ISSUE TITLE
FP8 WAN safetensors crash with OOM on RTX 5090

### ISSUE THREAD

**Issue by Velour-Fog** [comfyanonymous/ComfyUI#11593]
### Hardware

RTX 5090
64 GB system ram
Latest NVIDIA drivers installed (fully up to date)

### Environment

Fresh install of ComfyUI_windows_portable_nvidia_cu128.7z [v0.7.0]
Also tested ComfyUI_windows_portable_nvidia.7z (non‑cu128) [v0.7.0]
No manual Python environment
No custom patches
Clean, default portable installs

### Summary of the issue
Using the default Wan 2.2 I2V workflow FP8 WAN safetensors models consistently crash with CUDA OOM during sampling, even though VRAM usage is far below the 32 GB available. This happens on both portable builds (cu128 and non‑cu128). The crash usually occurs after the Wan 2.2 high ksampler finishes and passes it to the low ksampler. This default I2V workflow use to work previously a few months ago.

.gguf versions of WAN work fine, so the issue appears specific to FP8 safetensors.

### Models used
wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors
wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors
umt5_xxl_fp8_e4m3fn_scaled.safetensors
wan_2.1_vae.safetensors

### Behavior
Models load successfully (UNet + text encoder + VAE)
VRAM usage stays well below 32 GB
During sampling, ComfyUI attempts to unload/reload models
Then crashes with a fake OOM error
Browser sometimes crashes
Console shows repeated FP8‑related warnings

### Errors
unet unexpected: ['scaled_fp8']
CUDA error: out of memory
This happens identically on both portable builds.

### What I’ve already tested
fresh portable cu128 install → crashes
fresh portable non‑cu128 install → crashes
latest NVIDIA drivers → no change
weight_dtype=fp8 → crashes even with FP16 models
GGUF versions of WAN → work perfectly
same workflow months ago → worked perfectly

Additionally using the weight_dtype=default DOES work when using the full wan2.2_i2v_high_noise_14B_fp16.safetensors and wan2.2_i2v_low_noise_14B_fp16.safetensors but is extremely slow since using the full fp16 model.

### Expected behavior
FP8 WAN safetensors should load and sample without crashing, as they did in earlier ComfyUI versions and as the default workflow suggests.

### Actual behavior
FP8 WAN safetensors crash during sampling with a misleading OOM error, even though VRAM is not exhausted.

### Request
Can someone else with a 5090 (or really any Nvidia card that can run the standard fp8 .safetensors) test this? You just need to install the current Nvidia portable version [v0.7.0] and try running the default Wan 2.2 I2V workflow.

**Comment by bmgjet** [comment]
Works fine on my 5090 and my 3090.
5090 will do 1440x1440 @ 117 any larger and I get OOM.  Same amount of ram [64GB] and a 9950X3D for cpu.
3090 will do 1024x1024  and 1280x720 at around 22gb.

The default of 640x640 @ 81 frames is 1 min 30 secs on 5090 and 4min 11 on 3090.
Now getting SVI Pro to work is another story and only reason im even here looking in the comfyui issues.

**Comment by rattus128** [comment]
Can we get the full console crash log? The stuff leading up to your error message might shed some light.

**Comment by rattus128** [comment]
> Works fine on my 5090 and my 3090. 5090 will do 1440x1440 @ 117 any larger and I get OOM. Same amount of ram [64GB] and a 9950X3D for cpu. 3090 will do 1024x1024 and 1280x720 at around 22gb.
> 
> The default of 640x640 @ 81 frames is 1 min 30 secs on 5090 and 4min 11 on 3090. Now getting SVI Pro to work is another story and only reason im even here looking in the comfyui issues.

Thanks for the data.

One subtlety, are these cards on the same system? There is radically different behaviour of the windows cuda driver regarding its use of shared (and maybe pinned) memory when I had a 5090 + 3060 plugged in (with the multi-card setup being more stable). If it works for you with two cards probed but not OP with just a 5090 it might means something. It doesnt matter if both cards in use, just the driver changes things if the system knows two cards.

**Comment by rattus128** [comment]
I tried this. Windows + 0.7.0 portable and no problems with the FP8 scaled models.

Did you change the video resolution for the gen or just the template default?

A task manager screenshot on the GPU page at the time of crash will help too. Regular RAM issues might be in play here.

Any OOM that happens on a second ksampler sometimes improves with

--disable-smart-memory

In the startup args.

There is also the more drastic

--cache-none

startup arg but try --disable-smart-memory first.

LMK if these helps as it's still a bug if so.

**Comment by bmgjet** [comment]
> > Works fine on my 5090 and my 3090. 5090 will do 1440x1440 @ 117 any larger and I get OOM. Same amount of ram [64GB] and a 9950X3D for cpu. 3090 will do 1024x1024 and 1280x720 at around 22gb.
> > The default of 640x640 @ 81 frames is 1 min 30 secs on 5090 and 4min 11 on 3090. Now getting SVI Pro to work is another story and only reason im even here looking in the comfyui issues.
> 
> Thanks for the data.
> 
> One subtlety, are these cards on the same system? There is radically different behaviour of the windows cuda driver regarding its use of shared (and maybe pinned) memory when I had a 5090 + 3060 plugged in (with the multi-card setup being more stable). If it works for you with two cards probed but not OP with just a 5090 it might means something. It doesnt matter if both cards in use, just the driver changes things if the system knows two cards.

Seperate systems. Yeah had same issue when they were both in the same rig.

**Comment by Velour-Fog** [comment]
@rattus128 --disable-smart-memory was the solution, it works now, good suggestion.

Disabling that parameter makes sense to me as it certainly sounds like a parameter that could cause a bug when swapping between models from one ksampler to another.

As this sounds like a genuine bug to me I'll give some more info on my setup for the devs. Others mentioned multiple GPUs and I forgot to mention that I also have 2 GPUs in my PC. I have a RTX 5090 and a RTX 4060TI. Maybe multiple GPUs have something to do with it?

To recap the issue:
using ComfyUI_windows_portable_nvidia_cu128 [v0.7.0] version of comfyui
using run_nvidia_gpu.bat
Default Wan 2.2 I2V workflow
2 GPU setup with RTX 5090 and a RTX 4060TI
Latest NVIDIA drivers 
64 GB system ram
only 2 custom nodes are ComfyUI Manager and Crystools so I can easily watch the ram usage
ALSO - again it DOES work with the fp16 version of the wan models - just not the fp8 versions.

Here is a screenshot of the default I2V workflow I used and got working. It is working in this screenshot since I enabled --disable-smart-memory for this:
<img width="1917" height="980" alt="Image" src="https://github.com/user-attachments/assets/0fec5fd0-943a-43f7-bcaf-d1cc2de89e01" />

Finally here is a full log of running it without --disable-smart-memory which causes it to crash and fail upon swapping to the second advanced ksampler node:
<details>
<summary>Click to expand error log</summary>

D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2026-01-02 15:23:12.455
** Platform: Windows
** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
** Python executable: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\python_embeded\python.exe
** ComfyUI Path: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI
** ComfyUI Base Folder Path: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI
** User directory: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\user
** ComfyUI-Manager config path: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\user\__manager\config.ini
** Log path: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   1.6 seconds: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\custom_nodes\comfyui-manager

D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\python_embeded\Lib\site-packages\torch\cuda\__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Checkpoint files will always be loaded safely.
Total VRAM 32607 MB, total RAM 63080 MB
pytorch version: 2.9.1+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 28386.0
working around nvidia conv3d memory bug.
Using pytorch attention
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.7.0
ComfyUI frontend version: 1.35.9
[Prompt Server] web root: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\python_embeded\Lib\site-packages\comfyui_frontend_package\static
Total VRAM 32607 MB, total RAM 63080 MB
pytorch version: 2.9.1+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 28386.0
[Crystools INFO] Crystools version: 1.27.4
[Crystools INFO] Platform release: 11
[Crystools INFO] JETSON: Not detected.
[Crystools INFO] CPU: AMD Ryzen 9 9900X 12-Core Processor - Arch: AMD64 - OS: Windows 11
[Crystools INFO] pynvml (NVIDIA) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 5090
[Crystools INFO] 1) NVIDIA GeForce RTX 4060 Ti
[Crystools INFO] NVIDIA Driver: 591.59
### Loading: ComfyUI-Manager (V3.39)
[ComfyUI-Manager] network_mode: public
[ComfyUI-Manager] ComfyUI per-queue preview override detected (PR #11261). Manager's preview method feature is disabled. Use ComfyUI's --preview-method CLI option or 'Settings > Execution > Live preview method'.
### ComfyUI Revision: 150 [f59f71cf] *DETACHED | Released on '2025-12-30'

Import times for custom nodes:
   0.0 seconds: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\custom_nodes\websocket_image_save.py
   0.1 seconds: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\custom_nodes\comfyui-manager
   0.1 seconds: D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\custom_nodes\ComfyUI-Crystools

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Starting server

To see the GUI go to: http://127.0.0.1:8188
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
FETCH ComfyRegistry Data: 5/117
FETCH ComfyRegistry Data: 10/117
FETCH ComfyRegistry Data: 15/117
FETCH ComfyRegistry Data: 20/117
FETCH ComfyRegistry Data: 25/117
FETCH ComfyRegistry Data: 30/117
FETCH ComfyRegistry Data: 35/117
FETCH ComfyRegistry Data: 40/117
FETCH ComfyRegistry Data: 45/117
FETCH ComfyRegistry Data: 50/117
FETCH ComfyRegistry Data: 55/117
FETCH ComfyRegistry Data: 60/117
FETCH ComfyRegistry Data: 65/117
FETCH ComfyRegistry Data: 70/117
FETCH ComfyRegistry Data: 75/117
FETCH ComfyRegistry Data: 80/117
FETCH ComfyRegistry Data: 85/117
FETCH ComfyRegistry Data: 90/117
FETCH ComfyRegistry Data: 95/117
FETCH ComfyRegistry Data: 100/117
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Found quantization metadata version 1
Using MixedPrecisionOps for text encoder
FETCH ComfyRegistry Data: 105/117
Requested to load WanTEModel
loaded completely; 95367431640625005117571072.00 MB usable, 6419.49 MB loaded, full load: True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
Requested to load WanVAE
loaded completely; 18987.90 MB usable, 242.03 MB loaded, full load: True
FETCH ComfyRegistry Data: 110/117
Found quantization metadata version 1
Detected mixed precision quantization
Using mixed precision operations
model weight dtype torch.float16, manual cast: torch.float16
model_type FLOW
unet unexpected: ['scaled_fp8']
Requested to load WAN21
Unloaded partially: 4016.49 MB freed, 2403.00 MB remains loaded, 280.00 MB buffer reserved, lowvram patches: 0
FETCH ComfyRegistry Data: 115/117
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
loaded completely; 21496.10 MB usable, 13631.42 MB loaded, full load: True
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.78s/it]
Found quantization metadata version 1
Detected mixed precision quantization
Using mixed precision operations
model weight dtype torch.float16, manual cast: torch.float16
model_type FLOW
unet unexpected: ['scaled_fp8']
Requested to load WAN21
!!! Exception during processing !!! CUDA error: out of memory
Search for `cudaErrorMemoryAllocation' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\execution.py", line 516, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\execution.py", line 330, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\execution.py", line 304, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\execution.py", line 292, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\nodes.py", line 1572, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\nodes.py", line 1505, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\sample.py", line 60, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\samplers.py", line 1178, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\samplers.py", line 1068, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\samplers.py", line 1050, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\samplers.py", line 984, in outer_sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds, self.model_options)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\sampler_helpers.py", line 130, in prepare_sampling
    return executor.execute(model, noise_shape, conds, model_options=model_options, force_full_load=force_full_load)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\sampler_helpers.py", line 138, in _prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required + inference_memory, minimum_memory_required=minimum_memory_required + inference_memory, force_full_load=force_full_load)
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\model_management.py", line 674, in load_models_gpu
    free_memory(total_memory_required[device] * 1.1 + extra_mem, device)
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\model_management.py", line 606, in free_memory
    if current_loaded_models[i].model_unload(memory_to_free):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\model_management.py", line 529, in model_unload
    freed = self.model.partially_unload(self.model.offload_device, memory_to_free)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\model_patcher.py", line 917, in partially_unload
    m.to(device_to)
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1371, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\ComfyUI\comfy\ops.py", line 642, in _apply
    self.register_parameter(key, torch.nn.Parameter(fn(param), requires_grad=False))
                                                    ^^^^^^^^^
  File "D:\Portable Apps\ComfyUI_windows_portable_nvidia_cu128\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1357, in convert
    return t.to(
           ^^^^^
torch.AcceleratorError: CUDA error: out of memory
Search for `cudaErrorMemoryAllocation' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Prompt executed in 33.53 seconds

</details>

Lemme know if theres any other details you would like regarding this issue.

**Comment by wood-123456** [comment]
我測都沒啥問題

<img width="3839" height="1890" alt="Image" src="https://github.com/user-attachments/assets/ddf73caa-d599-482e-ab66-ede8d11e7b6e" />

<img width="2451" height="1285" alt="Image" src="https://github.com/user-attachments/assets/ee7552d8-34cc-4c52-944b-7e10d54eb7ae" />

<img width="2441" height="1282" alt="Image" src="https://github.com/user-attachments/assets/489e266d-07cb-4fd4-9014-94e3b7c48be8" />

<img width="2449" height="1274" alt="Image" src="https://github.com/user-attachments/assets/f6a49b18-55c2-4cc1-918a-fcf878b09c43" />

**Comment by wood-123456** [comment]
我驅動版本是用

<img width="1721" height="913" alt="Image" src="https://github.com/user-attachments/assets/366afe55-24dc-413f-bc7f-e6c93df0bc17" />還有你要記得把功耗調低,不然有機率掉驅動,螢幕黑掉,顯卡一直轉

<img width="1930" height="1398" alt="Image" src="https://github.com/user-attachments/assets/0f19b8ff-b267-4138-84f4-9a05fe9d9910" />
