### ISSUE TITLE
VRAM Out-of-Memory Error When Using LoRA with Qwen_image_edit in ComfyUI v0.7

### ISSUE THREAD

**Issue by luuIlee** [comfyanonymous/ComfyUI#11591]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

After updating ComfyUI to version 0.7, a GPU VRAM out-of-memory error occurs when using Qwen_image_edit with LoRA enabled. The error message is displayed as follows:
KSamplerAllocation on deviceThis error means you ran out of memory on your GPU.

### Actual Behavior

This issue also occurs when using the standard official workflow "mage_qwen_image_edit_2511".

### Steps to Reproduce

[Error reporting.txt](https://github.com/user-attachments/files/24402526/Error.reporting.txt)

### Debug Logs

```powershell
The issue is completely resolved once LoRA is disabled.
```

**Comment by luuIlee** [comment]
The issue was resolved after I disabled the community plugins, which may be caused by some plugins not being updated to the latest version

**Comment by rattus128** [comment]
> The issue was resolved after I disabled the community plugins, which may be caused by some plugins not being updated to the latest version

For future support of others can I get your list of plugins that broke it?

**Comment by mailzwj** [comment]
I had the same problem even without using LoRA(Official template)
ComfyUI version: 0.7.0
I tried using ComfyUI-Manager to switch back to v0.6.0 and v0.5.1, but it still doesn't work, maybe it's a problem with some dependency package

**Comment by mailzwj** [comment]
> I had the same problem even without using LoRA(Official template) ComfyUI version: 0.7.0 I tried using ComfyUI-Manager to switch back to v0.6.0 and v0.5.1, but it still doesn't work, maybe it's a problem with some dependency package

Amazing, after I restart my computer, it was fine now

**Comment by CreatoonForge** [comment]
My setup works normally once I remove the --highvram option.
