### ISSUE TITLE
Enhancement on VRAM (and maybe RAM?) handling between samplers on LTX 2 comfy native workflow

### ISSUE THREAD

**Issue by yusrmuttaqien** [comfyanonymous/ComfyUI#11726]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

1080p above 200 frames with 25 fps video generation can be normally performed without OOM across samplers

### Actual Behavior

At 1080p above 200 frames with 25 fps video generation, when the progress move from first sampling to the second sampling (upscale 2x step), the VRAM usage shoots up and causes OOM

### Steps to Reproduce

I'm using native ComfyUI workflow (from the templates browser) I2V LTX 2 distilled workflow, nothing is changed.

The flags i'm using to run comfy ui is: `comfy launch -- --use-sage-attention --listen --novram --cache-none --disable-smart-memory --preview-method taesd`

Machine specs is: 16GB VRAM, 32GB RAM, 64GB file swap, swappiness set to 6. I'm using Linux in headless mode (no desktop environment running, operate solely using SSH, remotely)

The versions as follows (i'm on nightly channel):

<img width="658" height="789" alt="Image" src="https://github.com/user-attachments/assets/c31e5ffe-9318-4f67-b66c-e553a73dc442" />

At first I thought ComfyUI doesn't have room to move stuff from VRAM to RAM, so i tried also added flag `--disable-pinned-memory`, drastically reduces the RAM usage when generating, but still got OOM (VRAM shoots up when starting the second sampling).

Then I'm experimenting, to split the run between the two samplers this way:
1. Run the first sampling steps, and save all the latents to file, there is three 3 latents: audio, video before `LTXVCropGuides` node node, video after `LTXVlmgToVideolnplace` node.
2. After all latents is saved, I invert the bypassed nodes and plug all the saved latents, and it works! Successfully generated the video without OOM, the VRAM usage is at mid hovering around 50%

By that experiment, I think there's a possibly for enhancement in VRAM handling, or maybe not. So, I give it to the contributors that know the inner working of VRAM handling for LTX 2 in ComfyUI.

This issue only surface when I tried to generate 1080p video with frame above 200 frames at 25 fps. 1080p 200 frame with the same fps work just fine without the experiment.

### Debug Logs

```powershell
Requested to load LTXAV
loaded partially; 0.00 MB usable, 0.00 MB loaded, 20541.27 MB offloaded, 448.07 MB buffer reserved, lowvram patches: 0
  0%|                                                                                                                                           | 0/3 [00:02<?, ?it/s]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/execution.py", line 518, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy_api/internal/__init__.py", line 149, in wrapped_func
    return method(locked_class, **inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy_api/latest/_io.py", line 1570, in EXECUTE_NORMALIZED
    to_return = cls.execute(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy_extras/nodes_custom_sampler.py", line 950, in execute
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 1050, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 994, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 980, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 752, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/3.12/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/k_diffusion/sampling.py", line 1465, in sample_gradient_estimation
    denoised = model(x, sigmas[i] * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 401, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 953, in __call__
    return self.outer_predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 960, in outer_predict_noise
    ).execute(x, timestep, model_options, seed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 963, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 381, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 206, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 214, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/samplers.py", line 326, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/model_base.py", line 163, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/model_base.py", line 205, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/ldm/lightricks/av_model.py", line 828, in forward
    return super().forward(
           ^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/ldm/lightricks/model.py", line 745, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/ldm/lightricks/model.py", line 792, in _forward
    x = self._process_transformer_blocks(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/ldm/lightricks/av_model.py", line 745, in _process_transformer_blocks
    vx, ax = block(
             ^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yusrmuttaqien/Documents/ComfyUI/py-3.12/bin/comfy/ldm/lightricks/av_model.py", line 257, in forward
    self.audio_to_video_attn(
torch.OutOfMemoryError: Allocation on device

Memory summary: |===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  13507 MiB |  14926 MiB |      0 B   |      0 B   |
|       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Active memory         |  13507 MiB |  14926 MiB |      0 B   |      0 B   |
|       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Requested memory      |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| GPU reserved memory   |  15712 MiB |  15712 MiB |      0 B   |      0 B   |
|       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Non-releasable memory |      0 B   |      0 B   |      0 B   |      0 B   |
|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |
|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |
|---------------------------------------------------------------------------|
| Allocations           |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Active allocs         |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       0    |       0    |       0    |       0    |
|       from large pool |       0    |       0    |       0    |       0    |
|       from small pool |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

Got an OOM, unloading all loaded models.
```

### Other

Additionally, i'm not sure what's wrong with sage attention when running the LTX 2 workflow, i got this log:

```bash
got prompt
Found quantization metadata version 1
Detected mixed precision quantization
Using mixed precision operations
model weight dtype torch.bfloat16, manual cast: torch.bfloat16
model_type FLUX
unet unexpected: ['audio_embeddings_connector.learnable_registers', ...<and many more>..., 'video_embeddings_connector.transformer_1d_blocks.1.ff.net.2.weight']
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.
Requested to load VideoVAE
loaded partially; 0.00 MB usable, 0.00 MB loaded, 2378.23 MB offloaded, 648.02 MB buffer reserved, lowvram patches: 0
clip missing: ['gemma3_12b.logit_scale', ...<and many more>... , 'gemma3_12b.transformer.vision_model.post_layernorm.bias']
Requested to load LTXAVTEModel_
loaded completely; 95367431640625005117571072.00 MB usable, 25965.49 MB loaded, full load: True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
Error running sage attention: list indices must be integers or slices, not NoneType, using pytorch attention instead.
Error running sage attention: list indices must be integers or slices, not NoneType, using pytorch attention instead.
Error running sage attention: list indices must be integers or slices, not NoneType, using pytorch attention instead.
Error running sage attention: list indices must be integers or slices, not NoneType, using pytorch attention instead.
Warning: TAESD previews enabled, but could not find models/vae_approx/None
Requested to load LTXAV
loaded partially; 0.00 MB usable, 0.00 MB loaded, 20541.27 MB offloaded, 448.07 MB buffer reserved, lowvram patches: 0
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [02:40<00:00, 20.09s/it]
Requested to load VideoVAE
loaded partially; 0.00 MB usable, 0.00 MB loaded, 2378.23 MB offloaded, 648.02 MB buffer reserved, lowvram patches: 0
VRAMdebug: free memory before:  16,481,845,248
VRAMdebug: free memory after:  16,481,845,248
VRAMdebug: freed memory:  0
Warning: TAESD previews enabled, but could not find models/vae_approx/None
```

Not sure if it's refuse to use sage attention for the text encoder (gemini) or the model itself (distilled fp8 ltx2 19B)

**Comment by gitmylo** [comment]
The sage attention errors are on the text encoder only. Also I'm wondering if other people are also getting 10x slower sample times without `--novram` than with? Getting like 8 seconds per step for 720p 250 frames with `--novram` but 80-110 seconds per step without the flag. But on `--novram` the text encoder is much slower so I wish I could just switch to the novram behavior during sampling but use the loaded text encoder during the text encoding stage. Maybe this will improve when the memory estimation is more accurate though.

**Comment by Rumaben** [comment]
You could try bypassing the 'Upscale Image By' and all the whole upscale section. I really don't understand why we need to generate at 50% just to upscale it back to the intended resolution, but I'm not the boss. Haha. :D 

32gb is not a lot. My pc is still swapping with 64gb of system ram, I have the same card as you. :) I use '--reserve-vram 3' (fp8 ltx-2 and fp8 gemma).

The 'LTXV Audio Text Encoder Loader' should apparently be able to use quants now but I can't see the gguf's inside of the node so it's properly not ready yet.

**Comment by gitmylo** [comment]
> You could try bypassing the 'Upscale Image By' and all the whole upscale section. I really don't understand why we need to generate at 50% just to upscale it back to the intended resolution, but I'm not the boss. Haha. :D

Because generating in a lower resolution and then upscaling is much faster than generating natively at the higher resolution, and speed seems to have been a part of their goals when making LTX-2.

**Comment by Rumaben** [comment]
> > You could try bypassing the 'Upscale Image By' and all the whole upscale section. I really don't understand why we need to generate at 50% just to upscale it back to the intended resolution, but I'm not the boss. Haha. :D
> 
> Because generating in a lower resolution and then upscaling is much faster than generating natively at the higher resolution, and speed seems to have been a part of their goals when making LTX-2.

I'm sure you're right about that. :) Anyway it's just the workflow wanting that. We're free to change it.

**Comment by Rumaben** [comment]
I just wanted to add that perhaps using the distilled fp8 model without using the distilled lora would save some system ram since that lora is so large in size. Strangely both the normal dev models and the distilled ones are identical in size, so perhaps not. :)

**Comment by gitmylo** [comment]
> Strangely both the normal dev models and the distilled ones are identical in size, so perhaps not. :)

Yeah the distilled models are step distilled, not weight distilled. So same size, but works for lower step counts.

**Comment by JigenD** [comment]
I have observed this same exact behavior on a 3090 with 64GB RAM. I may be mistaken but it seems to have begun after some of the recent commits regarding ltx2 memory handling (LTX2 seemed to not have this issue in the first commits that added LTX2 support).

**Comment by Rumaben** [comment]
Fix:

https://youtu.be/I_b2QN-B1W0?si=zHLdn0a3LwiuukuX&t=712

And adding '--disable-pinned-memory' saved my system ram. I got a wierd cuda error without the launch parameter. I could remove the '--reserve-vram' command.
This workflow:

https://github.com/Lightricks/ComfyUI-LTXVideo/blob/master/example_workflows/LTX-2_T2V_Distilled_wLora.json

I had to download all the files on the gemma huggingface manually since the larger files wouldn't download properly with the git clone command.

**Comment by rkfg** [comment]
I can't even generate 1024x576x251 on a 5090. The first phase goes fast enough but it OOMs on upscaling. Without upscaling (set `scale_by` to 1 and bypassed the upscale group, also connected the video/audio latents to the VAE decode nodes) I can go with 1280x720x251 no problems but it takes much more time. I assume the VRAM estimation is still wrong OR the latent upscale model doesn't unload when it should. Running the current master @ 1a206564487d672561d83ce3eb007517bf018995

<img width="1037" height="1125" alt="Image" src="https://github.com/user-attachments/assets/4201b8e9-0acc-441c-988a-859c1325e2ec" />

**Comment by Rumaben** [comment]
> I can't even generate 1024x576x251 on a 5090. The first phase goes fast enough but it OOMs on upscaling. Without upscaling (set `scale_by` to 1 and bypassed the upscale group, also connected the video/audio latents to the VAE decode nodes) I can go with 1280x720x251 no problems but it takes much more time. I assume the VRAM estimation is still wrong OR the latent upscale model doesn't unload when it should. Running the current master @ [1a20656](https://github.com/Comfy-Org/ComfyUI/commit/1a206564487d672561d83ce3eb007517bf018995)
> 
> <img alt="Image" width="1037" height="1125" src="https://private-user-images.githubusercontent.com/184066/533626651-4201b8e9-0acc-441c-988a-859c1325e2ec.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njc5MTYzNDcsIm5iZiI6MTc2NzkxNjA0NywicGF0aCI6Ii8xODQwNjYvNTMzNjI2NjUxLTQyMDFiOGU5LTBhY2MtNDQxYy05ODhhLTg1OWMxMzI1ZTJlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEwOFQyMzQ3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2Q0MzBiOWZkYzE3ODEwZjIwMjA2MGM3MTk0MWJkOGE2YjU2NTEwY2ZjMTE5N2VhNzg3MTg3ZjM4YWY5MjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.glXn_ij1AUlrYZ3fUmsVI_KOzrPP27Jk4pRsVDz72oM">

Try increasing the '--reserve-vram' value until your oom error goes away.

Also just saw this on reddit: https://github.com/dreamfast/ComfyUI-LTX2-MultiGPU

I haven't tried it yet so I can't vouch for it.

**Comment by rkfg** [comment]
I tried with `--reserve-vram 8` and I'm able to generate 1280x720x251 now, however, the ComfyUI process still takes 28 GB which is clearly too much since I have 32 GB of VRAM. Should be 24 GB at most, but considering the other programs taking 2 more gigabytes, it should be 22 GB. During VAE decoding it comes really close to OOM leaving just 100 MB free so the estimates or some other logic are incorrect. Basically it undershoots during the main phase and overshoots by a lot during upscale/decode. I never had an OOM during decoding and I remember it being handled in a special way, quietly resorting to tiled decode if it OOMs. The weird thing is that it crashes only with this two-stage workflow and not with one stage. I also tried adding `model_management.unload_all_models()` to `LTXVLatentUpsampler` and while I can see the effect (the model is reloaded slowly when the second sampler starts), it doesn't eliminate the issue at all.

**Comment by Rumaben** [comment]
The reason you're getting a oom error is most likely because you're generating at too high of a resolution. Either set your 'Upscale Image By' at a value lower than 1 or bypass that node and enter in a lower resolution directly.

The LTX-2 comfyui nodes are still so new so not many vram tweaks have been made yet.

**Comment by rkfg** [comment]
>The reason you're getting a oom error is most likely because you're generating at too high of a resolution.

I mentioned above that I can generate at the same high resolution in one go (much slower) but it fails at half resolution + upscale. So the VRAM estimate is correct overall but it fails with two passes. This is the line I get in the log with `--reserve-vram 10`, using 1280x720x376:
```
loaded partially; 17661.37 MB usable, 17613.36 MB loaded, 2927.91 MB offloaded, 48.01 MB buffer reserved, lowvram patches: 0
```
Then it runs 20 steps, loads the upscale model:
```
Unloaded partially: 1943.46 MB freed, 15669.90 MB remains loaded, 96.02 MB buffer reserved, lowvram patches: 0
loaded completely; 2632.80 MB usable, 2331.69 MB loaded, full load: True
```
And then loads the main model again for the final 3-step denoising:
```
loaded partially; 12704.32 MB usable, 12592.30 MB loaded, 7948.98 MB offloaded, 112.02 MB buffer reserved, lowvram patches: 1003
```
This time 5 GB are gone somewhere, probably the upscaled latents took them. I also had to replace the VAE Decode node with the tiled variant because otherwise I get `RuntimeError: input tensor must fit into 32-bit index math` — apparently the resolution and video length are too big, tiled VAE works fine.

With `--reserved-vram 16` I can run 1920x1080x376, the upscaling phase says:
```
loaded partially; 0.00 MB usable, 0.00 MB loaded, 20541.27 MB offloaded, 832.11 MB buffer reserved, lowvram patches: 1370
```
But occupies 23 GB and leaves about 6 GB free (the rest is taken by the other programs). So the numbers don't make any sense and don't work as they should, at least if the help message is correct. I couldn't find the latent memory estimation yet for the sampler, only for the model itself and the VAE memory estimations. The former is a static number and the latter only applies during encoding/decoding but not sampling which is what I need.

**Comment by Rumaben** [comment]
Strange. :/ Properly still some kind of bug unless you're understandment of the 'Upscale Image By' node scaling is reverse or something.  I'm not sure what it could be? With a resolution in the 'EmptyImage' node of 1280x720  that node at 1 would result in an upscaled video 2560x1440, so pretty high. At 0.5 that would only result in a final resolution  of 1280x720.

Math is chinese to me lol so maybe I'm way off but the 'Get Image Size' node will always show you the starting resolution and your final outputs metadata will contain your upscaled resolution.

My guess is you're simply pushing your vram to much, lower your settings a bit and try again or wait for comfyui updates.

There's a few launch parameters on this page to help with vram:

https://docs.comfy.org/troubleshooting/overview

**Comment by rkfg** [comment]
The final resolution is here:
<img width="376" height="249" alt="Image" src="https://github.com/user-attachments/assets/e1bbf727-8b9d-4c7a-b43b-9ab46f7c617c" />
In my case it's rounded down a little to 1920x1024 but that's not very important. The "Upscale By" node is only used to divide the numbers by two. The video I get has roughly the resolution I set in the main workflow, it's not doubled or halved.

>My guess is you're simply pushing your vram to much, lower your settings a bit and try again or wait for comfyui updates.

I already explained it's not the case but a VRAM management issue in ComfyUI. I don't really like the VRAM reserve hack because I run many models and those with correct memory estimations would underuse my memory and run much slower. But at least it provides some working baseline to test against.

**Comment by Rumaben** [comment]
Perhaps '--cache-none' will help but it's slow. LTX-2 prefers resolution numbers divisible by 32. Sorry if I don't answer adequately, it's super late here 2.30 at night. :D

Wan2GP supports LTX-2 now.

https://github.com/deepbeepmeep/Wan2GP

https://pinokio.co/item.html?uri=https%3A%2F%2Fgithub.com%2Fpinokiofactory%2Fwan&parent_frame=https://www.google.com/

**Comment by rkfg** [comment]
I think the memory usage factor needs further tweaking: https://github.com/Comfy-Org/ComfyUI/blob/1a206564487d672561d83ce3eb007517bf018995/comfy/supported_models.py#L848
I changed it to a more aggressive 0.2 and was able to render 1280x704x401 with no `--reserve-vram` flag. Needs more experiments but it's a good start. Note that it works good enough on my 5090 with 32 GB and it might offload too much (and slow down generation as a result) on less beefy hardware. So it's not a silver bullet, better wait for a proper fix if you're not in a hurry.

**Comment by Rumaben** [comment]
I just did a quick test. The best I could do was 17 seconds on my little 4060 ti (16gb)

<img width="1151" height="1204" alt="Image" src="https://github.com/user-attachments/assets/b8a560bd-1ab4-49eb-b44a-43121fec2764" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/71832032-15d7-4cc5-88cf-340ce4d55e29" />

**Comment by rkfg** [comment]
Look in the log, if it says `loaded partially; 0.00 MB usable` the second time (during upscale) then this parameter won't change anything for you as the entire model is already swapping out.

**Comment by Rumaben** [comment]
https://github.com/user-attachments/assets/f08a5f71-8d89-4dbd-a433-cbac1bf7b512

Just proof of my claim. Yeah something if properly going wrong in your setup since you can't even do 10 seconds with your much more powerful and capable 5090.

This is my log if it helps any:

<img width="2244" height="262" alt="Image" src="https://github.com/user-attachments/assets/72fbf823-5d9c-447e-ae2e-885c549010b3" />

<img width="2244" height="304" alt="Image" src="https://github.com/user-attachments/assets/bc0a19c2-d6df-45b5-93d5-67e263c05530" />

**Comment by Rumaben** [comment]
> I think the memory usage factor needs further tweaking:
> 
> [ComfyUI/comfy/supported_models.py](https://github.com/Comfy-Org/ComfyUI/blob/1a206564487d672561d83ce3eb007517bf018995/comfy/supported_models.py#L848)
> 
> Line 848 in [1a20656](/Comfy-Org/ComfyUI/commit/1a206564487d672561d83ce3eb007517bf018995)
> 
>  self.memory_usage_factor = 0.061  # TODO 
> 
> I changed it to a more aggressive 0.2 and was able to render 1280x704x401 with no `--reserve-vram` flag. Needs more experiments but it's a good start. Note that it works good enough on my 5090 with 32 GB and it might offload too much (and slow down generation as a result) on less beefy hardware. So it's not a silver bullet, better wait for a proper fix if you're not in a hurry.

Awesome congrats on your findings. 👍

**Comment by JigenD** [comment]
> I think the memory usage factor needs further tweaking:
> 
> [ComfyUI/comfy/supported_models.py](https://github.com/Comfy-Org/ComfyUI/blob/1a206564487d672561d83ce3eb007517bf018995/comfy/supported_models.py#L848)
> 
> Line 848 in [1a20656](/Comfy-Org/ComfyUI/commit/1a206564487d672561d83ce3eb007517bf018995)
>  self.memory_usage_factor = 0.061  # TODO 
> 
> I changed it to a more aggressive 0.2 and was able to render 1280x704x401 with no `--reserve-vram` flag. Needs more experiments but it's a good start. Note that it works good enough on my 5090 with 32 GB and it might offload too much (and slow down generation as a result) on less beefy hardware. So it's not a silver bullet, better wait for a proper fix if you're not in a hurry.


FWIW this doesn't make at different at all for me. Same memory usage, same OOM. (restarted ComfyUI each time)

**Comment by JigenD** [comment]
> --reserve-vram

This worked perfectly for me. Got rid of OOM issues and sped up inference time.

**Comment by rkfg** [comment]
Reserve VRAM shouldn't be required, it's to allow the *other* programs to use the GPU. ComfyUI shouldn't OOM without it if no other clients allocate VRAM randomly during the run. So it's a temporary workaround (I hope), not a fix.

>Same memory usage, same OOM

Post the log, I think the memory usage should be different for the first and second stage. You can also increase `self.memory_usage_factor` further as an experiment. I set it to 0.15 for now, doesn't break for 1920x1080 but comes close enough leaving about 1.3 GB free during the upscale.

**Comment by Rumaben** [comment]
gguf's are getting uploaded now by Kijai: https://huggingface.co/Kijai/LTXV2_comfy/tree/main/diffusion_models

**Comment by BadAtCaptchas** [comment]
> I think the memory usage factor needs further tweaking:
> 
> [ComfyUI/comfy/supported_models.py](https://github.com/Comfy-Org/ComfyUI/blob/1a206564487d672561d83ce3eb007517bf018995/comfy/supported_models.py#L848)
> 
> Line 848 in [1a20656](/Comfy-Org/ComfyUI/commit/1a206564487d672561d83ce3eb007517bf018995)
>  self.memory_usage_factor = 0.061  # TODO 
> 
> I changed it to a more aggressive 0.2 and was able to render 1280x704x401 with no `--reserve-vram` flag. Needs more experiments but it's a good start. Note that it works good enough on my 5090 with 32 GB and it might offload too much (and slow down generation as a result) on less beefy hardware. So it's not a silver bullet, better wait for a proper fix if you're not in a hurry.

I spotted this too. I changed it to `self.memory_usage_factor = (unet_config.get("cross_attention_dim", 4096) / 2048) * 5.5 * 1.5` and it fixed the OOM issue. I can generate 30 seconds of video on a RTX 5080 with no issues now.

**Comment by morganavr** [comment]
self.memory_usage_factor = 0.061 # TODO

Changing it to 0.2 fixed OOM error on RTX 5080. Should not this fix be ported into main branch?

**Comment by sanebg** [comment]
Same issue, getting OOM on 5090 even with 1080p

**Comment by vvhitevvizard** [comment]
> Same issue, getting OOM on 5090 even with 1080p

"even"?

**Comment by JamesMowery** [comment]
I've also been having a nightmare with my 5090 + LTX2. Constant OOM errors. ComfyUI is just not handling the VRAM correctly at all. And the fact we have to mess around with all these launch parameters seems to go against all the memory management improvements that I thought were introduced.

Beyond that, having to launch ComfyUI with different parameters for different models is just not a good way to go about this in general (sometimes you need --use-sage-attention and sometimes having it breaks things; --reserve-vram is a thing, I saw --fast mentioned as a new thing in a different article yesterday for Nvidia Blackwell). ComfyUI definitely seems to be getting worse in these regards over time.

**Comment by MeiYi-dev** [comment]
> I've also been having a nightmare with my 5090 + LTX2. Constant OOM errors. ComfyUI is just not handling the VRAM correctly at all. And the fact we have to mess around with all these launch parameters seems to go against all the memory management improvements that I thought were introduced.
> 
> Beyond that, having to launch ComfyUI with different parameters for different models is just not a good way to go about this in general (sometimes you need --use-sage-attention and sometimes having it breaks things; --reserve-vram is a thing, I saw --fast mentioned as a new thing in a different article yesterday for Nvidia Blackwell). ComfyUI definitely seems to be getting worse in these regards over time.

I would recommend https://github.com/pollockjj/ComfyUI-MultiGPU which gives us the controls on how much of the model / TE / VAE to keep in VRAM and in RAM

On the topic of sage attention, remove the --use-sage-attention arg from the startup args and use the "patch sage attention" node from KJNodes https://github.com/kijai/ComfyUI-KJNodes since sage attention won't work with LTX 2 with that arg.

**Comment by besch** [comment]
I feel your pain with the VRAM issues – spent weeks hitting the same walls with LTX-2 and Hunyuan before I decided to solve it differently.

If you're tired of the --lowvram flag dance and model offloading juggling, I built OpenFork specifically to avoid this headache. It's completely open source (https://github.com/besch/openfork_client) and uses Docker containers so every model "just works" – no manual Python environments, no CUDA version conflicts, no scattered model files.

The best part: you can share your GPU when idle and earn credits to run jobs on bigger GPUs when you need more VRAM. So if you've got an 8GB card but need to run a 24GB workflow, the network handles it.

It supports LTX-2 FP4, Hunyuan 1.5, WAN 2.2, and a bunch of other models that are normally painful to set up locally. Desktop app is at https://github.com/besch/openfork_desktop if you want to check it out.

Not trying to spam – just sharing what worked for me after hitting the same frustrations you're describing.

**Comment by trashkollector** [comment]
You need to put a video of this, to see how it works.

**Comment by mjzcng** [comment]
Your disk-split experiment is very close to what eventually worked for me with MiniMax H3. I packaged the same general idea here: https://github.com/mjzcng/ComfyUI-MiniMaxH3-Disk-Relay

Rather than keeping every scene in one prompt, it saves the current scene and checkpoint to disk, ends that prompt, unloads models and clears the execution cache, then requeues the next scene from disk. It also supports pausing after each scene for review, or running the whole chain unattended.

It only supports H3 at the moment, not LTX-2, so it will not directly fix this workflow. But if you are also experimenting with H3, it may be worth a try. At minimum, it is another data point that a disk handoff between stages can avoid cross-stage memory pressure.
