### ISSUE TITLE
Memory access fault by GPU node-1

### ISSUE THREAD

**Issue by Schnurzel700** [comfyanonymous/ComfyUI#11781]
OS: Arch Linux
CPU: Ryzen 7 5700x
Kernel: 6.18.3 and 6.12.63-lts (same result)
GPU: AMD RX 6800 XT (gfx1030, 16 GB VRAM)
RAM: 32 GB
Python: 3.12, 3.13 (same result)
ComfyUI: 0.8.2
Frontend: 1.36.13
PyTorch: 2.11.0.dev + ROCm 7.1
ROCm tested: 6.2, 6.4, 7.1

Model:
Model: sdxl_turbo_fp16
Resolutions: 512×512, 768×768, 1024x1024x

Reproduction:
```
python3 -m venv comfy-env
source comfy-env/bin/activate
pip install comfy-cli
pip install torch torchvision torchaudio \
  --index-url https://download.pytorch.org/whl/rocm6.4
comfy --workspace=/home/user/repos/ComfyUI/comfy install
```

PyTorch and Python Versions i tried:
```
❯ python --version                                                                                 
Python 3.13.11
❯ python -c "import torch; print('PyTorch:', torch.__version__); print('ROCm:', torch.version.hip)"
PyTorch: 2.11.0.dev20260108+rocm7.1
ROCm: 7.1.52802

❯ python --version                                                                                 
Python 3.12.12
❯ python -c "import torch; print('PyTorch:', torch.__version__); print('ROCm:', torch.version.hip)"
PyTorch: 2.5.1+rocm6.2
ROCm: 6.2.41133-dd7f95766
```

Error:
Memory access fault by GPU node-1 (Agent handle: 0x577d0d3344f0) on address 0x730e41a5f000. Reason: Page not present or supervisor privilege.

ComfyUI runs fast, but reliably crashes the GPU with a memory access fault after repeated generations, especially when switching resolutions.
After this, GPU execution is broken until ComfyUI is restarted.
I also tried the manual Installation and Installtion with comfy-cli.

How can i solve this problem?

**Comment by Ultra119** [comment]
I use a 6800 xt and have been dealing with this problem on Arch for a long time (since rocm 5).
Just use officially supported [distros](https://rocm.docs.amd.com/en/latest/compatibility/compatibility-matrix.html). Preferably, of course, based on Debian/Ubuntu. I don't have this problem there.

**Comment by basicist** [comment]
Same issue here using Arch with a AMD 7800 XT

**Comment by Schnurzel700** [comment]
I just tested the issue again on a supported distribution (Ubuntu 24.04.3) and the problem does not appear there. Seems to be related to a too new kernel, which maybe changed VRAM Management Control.

**Comment by popsUlfr** [comment]
Not exactly sure if at all related but I got comfyui working smoothly again on my Strix Halo with CachyOS by using following rocm url: https://rocm.nightlies.amd.com/v2/gfx1151/
I wiped my venv and first thing I did after recreating it:
```
pip3 install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2/gfx1151/
```

Then install all requirements: `pip3 install -r requirements.txt`

And no crashes, memory access faults or segfaults anymore.

For gfx1030 it is most likely this:
```
pip3 install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/
```

**Comment by alexheretic** [comment]
I've been seeing this on Arch with my 7900gre. However, I found reverting to kernel `6.17.9` stopped it occurring so may be a different issue (or perhaps try that).

On arch you can downgrade the kernel using the archive, and for the kernel package this is a fairly ok thing to do unlike doing so with many other packages.
```
pacman -U https://archive.archlinux.org/packages/l/linux/linux-6.17.9.arch1-1-x86_64.pkg.tar.zst
```

Related issues:
*  https://github.com/ROCm/amdgpu/issues/204
*  https://github.com/ROCm/ROCm/issues/5051#issuecomment-3730224118

**Comment by waydxd** [comment]
Downgrading the Arch Linux kernel to an older version (in my case `linux-lts 6.12.66-1`) resolved my memory access fault issues with the RX 6700 XT.

I also attempted @popsUlfr’s workaround by installing the ROCm nightly builds:

```bash
pip3 install --pre torch torchvision torchaudio \
  --index-url https://rocm.nightlies.amd.com/v2-staging/gfx103X-dgpu/
```

However, the memory access faults persisted on the latest kernel. The issue only disappeared after switching to the LTS kernel, so it seems both steps are necessary.

**Comment by Schnurzel700** [comment]
I already tried downgrading to Linux Kernel LTS-6.12.63, in my case it did not resolve the issue with my RX 6800 XT.

**Comment by Schnurzel700** [comment]
Which python version do you use?

**Comment by Schnurzel700** [comment]
I tried running the ROCm PyTorch installation command @popsUlfr shared, but it failed with a "no matching distribution" error. Here’s the output:
`pip3 install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/
Looking in indexes: https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch`

**Comment by Ultra119** [comment]
> I tried running the ROCm PyTorch installation command @popsUlfr shared, but it failed with a "no matching distribution" error. Here’s the output:
> `pip3 install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/
> Looking in indexes: https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/
> ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
> ERROR: No matching distribution found for torch`

There is no torch or other components for gfx1030 on rocm.nightlies.amd.com. They are distributed via https://download.pytorch.org/whl/rocm6.4 or https://download.pytorch.org/whl/nightly/rocm7.1/ if you need latest

**Comment by Schnurzel700** [comment]
Just tried Linux Kernel 6.17.9-arch1-1 as @alexheretic and @waydxd suggested, but still same Issue for me

**Comment by alexheretic** [comment]
> Just tried Linux Kernel 6.17.9-arch1-1 as @alexheretic and @waydxd suggested, but still same Issue for me

Could be another issue with the same symptoms I guess. You definitely restarted after changing kernel I assume? (Can confirm with `uname -r`).

**Comment by TomatoLoli** [comment]
For those still experiencing this issue. Try the following launch options. `python main.py --use-quad-cross-attention --disable-smart-memory --cache-none`

**Comment by feffy380** [comment]
> For those still experiencing this issue. Try the following launch options. `python main.py --use-quad-cross-attention --disable-smart-memory --cache-none`

I had luck with `--gpu-only` and I've never encountered this issue with A1111 or reForge, so it looks like comfyui's partial offload is triggering a bug in rocm 7

**Comment by Schnurzel700** [comment]
@alexheretic Yes, I rebooted every time after changing kernel
@TomatoLoli The Launch Command you provided did unfortunately not work for me. Same as `--gpu-only`. Still same issue.
I tried Python v3.14.2 and v3.12.12.

**Comment by TomatoLoli** [comment]
@Schnurzel700 

If you're interested in trying this. The other variables at play I'm using rocm7.1 on a clean install of comfyui with the LTS kernel 6.12

**Comment by Schnurzel700** [comment]
I already tried the LTS Kernel 6.12:
`❯ uname -r
6.12.66-1-lts`

This is my Log:
`❯ HSA_OVERRIDE_GFX_VERSION=10.3.0 comfy launch -- --use-quad-cross-attention --disable-smart-memory --cache-none --gpu-only

Launching ComfyUI from: /home/user/repos/ComfyUI/comfy

[START] Security scan
[ComfyUI-Manager] Using `uv` as Python module for pip operations.
Using Python 3.14.2 environment at: /home/user/repos/ComfyUI/venv
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2026-01-20 19:08:28.294
** Platform: Linux
** Python version: 3.14.2 (main, Jan  2 2026, 14:27:39) [GCC 15.2.1 20251112]
** Python executable: /home/user/repos/ComfyUI/venv/bin/python
** ComfyUI Path: /home/user/repos/ComfyUI/comfy
** ComfyUI Base Folder Path: /home/user/repos/ComfyUI/comfy
** User directory: /home/user/repos/ComfyUI/comfy/user
** ComfyUI-Manager config path: /home/user/repos/ComfyUI/comfy/user/__manager/config.ini
** Log path: /home/user/repos/ComfyUI/comfy/user/comfyui.log
Using Python 3.14.2 environment at: /home/user/repos/ComfyUI/venv
Using Python 3.14.2 environment at: /home/user/repos/ComfyUI/venv

Prestartup times for custom nodes:
   0.2 seconds: /home/user/repos/ComfyUI/comfy/custom_nodes/ComfyUI-Manager

Checkpoint files will always be loaded safely.
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
Total VRAM 16368 MB, total RAM 32005 MB
pytorch version: 2.11.0.dev20260119+rocm7.1
AMD arch: gfx1030
ROCm version: (7, 1)
Set vram state to: HIGH_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon Graphics : native
Using async weight offloading with 2 streams
Enabled pinned memory 30404.0
Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend cuda: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.14.2 (main, Jan  2 2026, 14:27:39) [GCC 15.2.1 20251112]
ComfyUI version: 0.10.0
ComfyUI frontend version: 1.37.11
[Prompt Server] web root: /home/user/repos/ComfyUI/venv/lib/python3.14/site-packages/comfyui_frontend_package/static
### Loading: ComfyUI-Manager (V3.39.2)
[ComfyUI-Manager] network_mode: public
[ComfyUI-Manager] ComfyUI per-queue preview override detected (PR #11261). Manager's preview method feature is disabled. Use ComfyUI's --preview-method CLI option or 'Settings > Execution > Live preview method'.
### ComfyUI Version: v0.10.0-4-g8ccc0c94 | Released on '2026-01-20'

Import times for custom nodes:
   0.0 seconds: /home/user/repos/ComfyUI/comfy/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/user/repos/ComfyUI/comfy/custom_nodes/ComfyUI-Manager

Context impl SQLiteImpl.
Will assume non-transactional DDL.
Assets scan(roots=['models']) completed in 0.013s (created=0, skipped_existing=12, total_seen=12)
Disabling intermediate node cache.
Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH ComfyRegistry Data: 5/120
FETCH ComfyRegistry Data: 10/120
FETCH ComfyRegistry Data: 15/120
FETCH ComfyRegistry Data: 20/120
FETCH ComfyRegistry Data: 25/120
FETCH ComfyRegistry Data: 30/120
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
FETCH ComfyRegistry Data: 35/120
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cuda:0, dtype: torch.float32
Requested to load SD1ClipModel
loaded completely;  235.84 MB loaded, full load: True
CLIP/text encoder model load device: cuda:0, offload device: cuda:0, current: cuda:0, dtype: torch.float16
loaded diffusion model directly to GPU
Requested to load BaseModel
loaded completely;  1639.41 MB loaded, full load: True
Requested to load SD1ClipModel
loaded completely;  235.84 MB loaded, full load: True
Requested to load BaseModel
loaded completely;  1639.41 MB loaded, full load: True
  0%|                                                                                                                 | 0/20 [00:00<?, ?it/s]FETCH ComfyRegistry Data: 40/120
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.31it/s]
Requested to load AutoencoderKL
loaded completely;  319.11 MB loaded, full load: True
Prompt executed in 4.58 seconds
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
FETCH ComfyRegistry Data: 45/120
VAE load device: cuda:0, offload device: cuda:0, dtype: torch.float32
Requested to load SD1ClipModel
loaded completely;  235.84 MB loaded, full load: True
CLIP/text encoder model load device: cuda:0, offload device: cuda:0, current: cuda:0, dtype: torch.float16
loaded diffusion model directly to GPU
Requested to load BaseModel
loaded completely;  1639.41 MB loaded, full load: True
Requested to load SD1ClipModel
loaded completely;  235.84 MB loaded, full load: True
Requested to load BaseModel
loaded completely;  1639.41 MB loaded, full load: True
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.74it/s]
Requested to load AutoencoderKL
loaded completely;  319.11 MB loaded, full load: True
Prompt executed in 3.13 seconds
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cuda:0, dtype: torch.float32
Requested to load SD1ClipModel
loaded completely;  235.84 MB loaded, full load: True
CLIP/text encoder model load device: cuda:0, offload device: cuda:0, current: cuda:0, dtype: torch.float16
loaded diffusion model directly to GPU
Requested to load BaseModel
loaded completely;  1639.41 MB loaded, full load: True
Requested to load SD1ClipModel
loaded completely;  235.84 MB loaded, full load: True
Requested to load BaseModel
loaded completely;  1639.41 MB loaded, full load: True
  0%|                                                                                                                 | 0/20 [00:00<?, ?it/s]
  Memory access fault by GPU node-1 (Agent handle: 0x563cc93a8470) on address 0x7ce4e3b7f000. Reason: Page not present or supervisor privilege.
FETCH ComfyRegistry Data: 50/120
`

This is a clean install of comfyui with the pip package 'comfy-cli'

**Comment by TomatoLoli** [comment]
Since my install is from yesterday you have a slightly newer version and I'm on a older version of python. But on my side I don't have any depreciation warnings and its coming out as NORMAL_VRAM for my card vs yours coming up as HIGH_VRAM  when we both have 16GB of vram.

Are you using an old workflow that's bringing in deprecated objects? 
Does the behaviour change if you force normal_vram mode?

 I also noticed troubleshooting this issue that once the Memory access fault has occurred nothing will fix it without a full reboot and any software using gpu acceleration becomes unstable.


`OpenSUSE TW linux 6.12.65-1-longterm #1 SMP PREEMPT_DYNAMIC Mon Jan 12 22:10:57 UTC 2026 (1bd3225) x86_64 x86_64 x86_64 GNU/Linux

amdgpu 3.61.0
Mesa 25.3.3


(venv) user@linux:~/ComfyUI> nice python main.py --use-quad-cross-attention --disable-smart-memory --cache-none
Checkpoint files will always be loaded safely.
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
Total VRAM 16304 MB, total RAM 64055 MB
pytorch version: 2.11.0.dev20260118+rocm7.1
Set: torch.backends.cudnn.enabled = False for better AMD performance.
AMD arch: gfx1201
ROCm version: (7, 1)
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon Graphics : native
Using async weight offloading with 2 streams
Enabled pinned memory 60851.0
Found comfy_kitchen backend cuda: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.13.11 (main, Dec 19 2025, 18:38:03) [GCC]
ComfyUI version: 0.9.2
ComfyUI frontend version: 1.36.14
[Prompt Server] web root: /home/user/ComfyUI/venv/lib64/python3.13/site-packages/comfyui_frontend_package/static

Import times for custom nodes:
   0.0 seconds: /home/user/ComfyUI/custom_nodes/websocket_image_save.py

Context impl SQLiteImpl.
Will assume non-transactional DDL.
Assets scan(roots=['models']) completed in 0.011s (created=0, skipped_existing=35, total_seen=35)
Disabling intermediate node cache.
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SDXLClipModel
loaded completely; 14536.80 MB usable, 1560.80 MB loaded, full load: True
Requested to load SDXL
loaded completely; 13149.04 MB usable, 4897.05 MB loaded, full load: True
  0%|                                                                                                                                                                                                                                                                                                                                              | 0/15 [00:00<?, ?it/s]/home/user/ComfyUI/venv/lib64/python3.13/site-packages/torchsde/_brownian/brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=14.614640235900879 and t1=14.61464.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.94it/s]
Requested to load AutoencoderKL
loaded completely; 6109.87 MB usable, 159.56 MB loaded, full load: True
Requested to load AutoencoderKL
0 models unloaded.
loaded completely; 6067.47 MB usable, 159.56 MB loaded, full load: True
Requested to load SDXL
loaded completely; 10500.50 MB usable, 4897.05 MB loaded, full load: True
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:17<00:00,  1.17it/s]
Requested to load AutoencoderKL
0 models unloaded.
loaded completely; 6067.47 MB usable, 159.56 MB loaded, full load: True
Prompt executed in 75.13 seconds

`

**Comment by Schnurzel700** [comment]
I was using the Python `comfy‑cli` script. When I install ComfyUI manually, the deprecated‑object warnings disappear, but launching it with `--normal‑vram` still crashes. Using the same Python version as yours doesn’t resolve the issue. Other applications, such as games, continue to run fine after the crash.

`
❯ python main.py --use-quad-cross-attention --disable-smart-memory --cache-none --normalvram
Checkpoint files will always be loaded safely.
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
Total VRAM 16368 MB, total RAM 32005 MB
pytorch version: 2.11.0.dev20260120+rocm7.1
AMD arch: gfx1030
ROCm version: (7, 1)
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon Graphics : native
Using async weight offloading with 2 streams
Enabled pinned memory 30404.0
Found comfy_kitchen backend cuda: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.13.11 (main, Jan 21 2026, 13:42:06) [GCC 15.2.1 20260103]
ComfyUI version: 0.10.0
ComfyUI frontend version: 1.37.11
[Prompt Server] web root: /home/janek/repos/ComfyUI/venv3/lib/python3.13/site-packages/comfyui_frontend_package/static

Import times for custom nodes:
   0.0 seconds: /home/janek/repos/ComfyUI/ComfyUI/custom_nodes/websocket_image_save.py

Context impl SQLiteImpl.
Will assume non-transactional DDL.
Assets scan(roots=['models']) completed in 0.015s (created=0, skipped_existing=12, total_seen=12)
Disabling intermediate node cache.
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SD1ClipModel
loaded completely; 15084.80 MB usable, 235.84 MB loaded, full load: True
Requested to load BaseModel
loaded completely; 14814.80 MB usable, 1639.41 MB loaded, full load: True
 75%|██████████████████████████████████████████████████████████████████████████████                          | 15/20 [00:01<00:00, 10.06it/s]Memory access fault by GPU node-1 (Agent handle: 0x635dcb51f100) on address 0x7f46255ee000. Reason: Page not present or supervisor privilege.
 75%|██████████████████████████████████████████████████████████████████████████████                          | 15/20 [00:20<00:00, 10.06it/s]GPU core dump created: gpucore.5418`

**Comment by basicist** [comment]
SOLVED (For myself)

I resolved the issue by running the following command within my python virtual environment (venv):

`python main.py --reserve-vram 2`

OS: ArchLinux
GPU: AMD 7800 XT
Python venv: 3.11.14

ROCm/Torch Installation:
Followed the installation guide from the [ComfyUI GitHub](https://github.com/Comfy-Org/ComfyUI)

After installing the required dependencies from requirements.txt, I ran the following to install the correct versions of PyTorch for ROCm for my GPU:

```
pip uninstall -y torch torchvision torchaudio
pip install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/
```

Root Cause:
It seems the issue was related to my OS not having access to safely allocated VRAM. Using the --reserve-vram 2 flag resolved the problem by reserving VRAM manually.

**Comment by Schnurzel700** [comment]
@basicist Your launch Command did unfortunately not work for me.

**Comment by waydxd** [comment]
> I tried running the ROCm PyTorch installation command [@popsUlfr](https://github.com/popsUlfr) shared, but it failed with a "no matching distribution" error. Here’s the output: `pip3 install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/ Looking in indexes: https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/ ERROR: Could not find a version that satisfies the requirement torch (from versions: none) ERROR: No matching distribution found for torch`

I’m using the staging build since `https://rocm.nightlies.amd.com/v2/gfx103X-dgpu/` doesn’t list `torch`.  

For my RX 6700 XT, the install works with:  
```
pip install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2-staging/gfx103X-dgpu/
```

**Comment by Schnurzel700** [comment]
Using the install Command from @waydxd does not fix it. I am getting these warnings on startup:
`warning: xnack 'Off' was requested for a processor that does not support it!`
Additionally still crashing:
`Memory access fault by GPU node-1 (Agent handle: 0x56369c6f8e50) on address 0x7f2ddf71a000. Reason: Page not present or supervisor privilege.
 40%|████████████████████████████████▊                                                 | 8/20 [00:00<00:00, 25.55it/s]Failed to write segment data to pipe: Broken pipe
GPU coredump: handler exited with error (status: 1)
GPU core dump failed`

**Comment by Schnurzel700** [comment]
Using the Install Command from @waydxd, the generation speed seems much faster. I was getting 24.39 it/s instead of 9.51 it/s!

Edit:
Never mind. It's actually the KSampler generation that's faster with the command, but VAE decoding is slower. Overall, the speed ends up being about the same.

**Comment by Schnurzel700** [comment]
I think I’ve found the solution. It turned out to be my overclock. After disabling it, the crashes stopped completely and the system seems stable now. I honestly never expected the OC to be the cause, since everything was perfectly stable while gaming. After slightly reducing the GPU voltage offset, it’s now stable again even with the overclock enabled. Using Kernel 6.18.6-arch1-1 with Python 3.14.2 and Rocm7.1.1.

**Comment by feffy380** [comment]
`--disable-pinned-memory` seems to work for me (7900 XTX, rocm 7.2). I have yet to see a crash when previously I could trigger it 100% reliably

**Comment by alexheretic** [comment]
> `--disable-pinned-memory` seems to work for me (7900 XTX, rocm 7.2)

Aha this is also the case for me (Arch Linux, 7900 GRE). Testing kernel `6.18.6-arch1-1` I can no longer reproduce this issue when using  `--disable-pinned-memory`. I wonder what pinned memory is doing exactly that could cause this?

**Comment by xegim** [comment]
> `--disable-pinned-memory` seems to work for me (7900 XTX, rocm 7.2)

I have the same setup, and this seems to have worked for me as well, thanks a lot. I can now consistently run various workflows without crashing in-between.

**Comment by Schnurzel700** [comment]
@alexheretic How exactly did you install Rocm7.2?

`❯ pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm7.2
Looking in indexes: https://download.pytorch.org/whl/nightly/rocm7.2
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch`

This doesn't seem to be published yet.

**Comment by Schnurzel700** [comment]
Does anyone know what these warnings mean?
`got prompt
100%|█████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:05<00:00,  8.74it/s]
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 9863168, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 9863168, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 9863168, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 9863168, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 39452672, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 39452672, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 39452672, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 39452672, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 78905344, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 78905344, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 78905344, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 78905344, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 157810688, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 157810688, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 157810688, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 157810688, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 315621376, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 315621376, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [GetSolutionsFallback WTI] Solver <GemmFwdRest>, workspace required: 315621376, provided ptr: 0 size: 0
MIOpen(HIP): Warning [IsEnoughWorkspace] [EvaluateInvokers] Solver <GemmFwdRest>, workspace required: 315621376, provided ptr: 0 size: 0
Prompt executed in 32.42 seconds`

**Comment by alexheretic** [comment]
> [@alexheretic](https://github.com/alexheretic) How exactly did you install Rocm7.2?

I'm currently using the rocm nightlies from https://rocm.nightlies.amd.com/v2/gfx110X-all/. See https://github.com/Comfy-Org/ComfyUI?tab=readme-ov-file#amd-gpus-experimental-windows-and-linux-rdna-3-35-and-4-only

**Comment by Schnurzel700** [comment]
Will this also work on a RX6800 XT?

**Comment by alexheretic** [comment]
> Will this also work on a RX6800 XT?

I guess not, it doesn't look like they're supporting rdna2 for this.

**Comment by EnochPrime** [comment]
> Does anyone know what these warnings mean?

@Schnurzel700 check out https://github.com/pytorch/pytorch/issues/150168

**Comment by rein1410** [comment]
Still happening on RX 7800 XT

**Comment by PazoxZodiac** [comment]
My PC:

Kernel: 6.19.3-2-cachyos (64-bit) (Arch Linux)
CPU: AMD Ryzen 7 7800X3D
RAM: 96 GB DDR5
GPU: AMD Radeon RX 9070 XT 16 GB
Mesa: 25.3.5-2
ROCm: 7.1

`--disable-pinned-memory`

Seems to be working with "--disable-pinned-memory" for now.
I don't get the following error message anymore:

`Memory access fault by GPU node-1`

**Comment by TomatoLoli** [comment]
Installing this resolved the problem for me. 

https://download.pytorch.org/whl/rocm7.2

2026-06-23
After doing more with comfyui the problem came back just less often and doesn't crash the entire system anymore.

**Comment by PDCWolf** [comment]
Excuse the necro.

For anyone finding this from the net, currently (end of June '26) on:
* Arch Linux
* Linux 7.0.13
* RX 6750XT (gfx1031)
* ROCm 7.2.4

ComfyUI seems to have issues managing the VRAM correctly. Sometimes it outright crashes with a memory error.  In some cases the generation might die midway, or even run fine right up to the VAE Decode stage, where it doesn't correctly detect it's gonna overrun the available VRAM causing a GPU mode1 reset (not sure of the internal workings for everything to fail until that point but hey, that's what's happening.)

Basically you have to **manage VRAM manually** with the parameters comfy gives you. 
* Sometimes just using a VAE Decode (tiled) node is enough.
* In some cases just --cpu-vae (if you have a strong enough CPU that the slowdown is minimal) is enough. 
* In other cases you have to --reserve-vram and pray its enough. 
* IF it outright crashes comfy with the error mentioned in this issue, --disable-pinned-memory should let you get past that.

Handling the mode1 reset is up to whatever compositor you have and its libraries. In Hyprland's case, aquamarine currently just dies, but that's it's own problem.
