### ISSUE TITLE
KSamplerAdvanced Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

### ISSUE THREAD

**Issue by l663855724** [comfyanonymous/ComfyUI#12202]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Adding extra search path custom_nodes /Users/lihaoze/Documents/ComfyUI/custom_nodes
Adding extra search path download_model_base /Users/lihaoze/Documents/ComfyUI/models
Adding extra search path custom_nodes /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes
Setting output directory to: /Users/lihaoze/Documents/ComfyUI/output
Setting input directory to: /Users/lihaoze/Documents/ComfyUI/input
Setting user directory to: /Users/lihaoze/Documents/ComfyUI/user
[START] Security scan
[ComfyUI-Manager] Using uv as Python module for pip operations.
[DONE] Security scan
** ComfyUI startup time: 2026-02-01 14:47:34.478
** Platform: Darwin
** Python version: 3.12.11 (main, Aug 18 2025, 19:02:39) [Clang 20.1.4 ]
** Python executable: /Users/lihaoze/Documents/ComfyUI/.venv/bin/python
** ComfyUI Path: /Applications/ComfyUI.app/Contents/Resources/ComfyUI
** ComfyUI Base Folder Path: /Applications/ComfyUI.app/Contents/Resources/ComfyUI
** User directory: /Users/lihaoze/Documents/ComfyUI/user
** ComfyUI-Manager config path: /Users/lihaoze/Documents/ComfyUI/user/__manager/config.ini
** Log path: /Users/lihaoze/Documents/ComfyUI/user/comfyui.log
[ComfyUI-Manager] Skipped fixing the 'comfyui-frontend-package' dependency because the ComfyUI is outdated.
[PRE] ComfyUI-Manager
Checkpoint files will always be loaded safely.
Total VRAM 16384 MB, total RAM 16384 MB
pytorch version: 2.10.0
Mac Version (26, 2)
Set vram state to: SHARED
Device: mps
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': "ImportError: No module named 'triton'", 'capabilities': []}
Found comfy_kitchen backend cuda: {'available': False, 'disabled': True, 'unavailable_reason': 'Extension file not found: /Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/backends/cuda/_C.abi3.so', 'capabilities': []}
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.12.11 (main, Aug 18 2025, 19:02:39) [Clang 20.1.4 ]
ComfyUI version: 0.11.1
[Prompt Server] web root: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app
[START] ComfyUI-Manager
[ComfyUI-Manager] network_mode: public

Import times for custom nodes:
   0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/websocket_image_save.py

Context impl SQLiteImpl.
Will assume non-transactional DDL.
Assets scan(roots=['models']) completed in 0.010s (created=0, skipped_existing=10, total_seen=10)
Starting server

To see the GUI go to: http://127.0.0.1:8000
comfyui-frontend-package not found in requirements.txt
got prompt
Using split attention in VAE
Using split attention in VAE
VAE load device: mps, offload device: cpu, dtype: torch.bfloat16
Found quantization metadata version 1
Using MixedPrecisionOps for text encoder
Requested to load WanTEModel
loaded completely;  6419.48 MB loaded, full load: True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
Found quantization metadata version 1
Detected mixed precision quantization
Using mixed precision operations
model weight dtype torch.float16, manual cast: torch.float16
model_type FLOW
Requested to load WAN21
0 models unloaded.
!!! Exception during processing !!! Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.
Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 518, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1624, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1555, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sample.py", line 66, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1178, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1068, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1050, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 984, in outer_sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds, self.model_options)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sampler_helpers.py", line 130, in prepare_sampling
    return executor.execute(model, noise_shape, conds, model_options=model_options, force_full_load=force_full_load)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sampler_helpers.py", line 138, in _prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required + inference_memory, minimum_memory_required=minimum_memory_required + inference_memory, force_full_load=force_full_load)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_management.py", line 715, in load_models_gpu
    loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_management.py", line 520, in model_load
    self.model_use_more_vram(use_more_vram, force_patch_weights=force_patch_weights)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_management.py", line 550, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory, force_patch_weights=force_patch_weights)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_patcher.py", line 983, in partially_load
    raise e
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_patcher.py", line 980, in partially_load
    self.load(device_to, lowvram_model_memory=current_used + extra_memory, force_patch_weights=force_patch_weights, full_load=full_load)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_patcher.py", line 778, in load
    self.patch_weight_to_device(key, device_to=device_to)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_patcher.py", line 630, in patch_weight_to_device
    temp_weight = convert_func(temp_weight, inplace=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 697, in convert_weight
    return weight.dequantize()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/tensor/base.py", line 286, in dequantize
    full = self.layout_cls.dequantize(qdata, self._params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/tensor/fp8.py", line 68, in dequantize
    return ck.dequantize_per_tensor_fp8(qdata, params.scale, params.orig_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/__init__.py", line 84, in dequantize_per_tensor_fp8
    return torch.ops.comfy_kitchen.dequantize_fp8(x, scale, dtype_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/_ops.py", line 1209, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 347, in backend_impl
    result = self._backend_fns[device_type](*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/_compile.py", line 54, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 1181, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 382, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/backends/eager/quantization.py", line 252, in _op_dequantize_fp8
    return impl(**kwargs)
           ^^^^^^^^^^^^^^
  File "/Users/lihaoze/Documents/ComfyUI/.venv/lib/python3.12/site-packages/comfy_kitchen/backends/eager/quantization.py", line 57, in dequantize_per_tensor_fp8
    dq_tensor = x.to(dtype=output_type) * scale.to(dtype=output_type)
                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

Prompt executed in 27.11 seconds

### Logs

```powershell

```

**Comment by l663855724** [comment]
跪求大佬解决，感谢！

**Comment by raresabr** [comment]
> 跪求大佬解决，感谢！

Same problem here 😁

**Comment by GlamoramaAttack** [comment]
> Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

Maybe because you use  "pytorch version: 2.10.0"  according to your log.  And according to:
https://pytorch.org/blog/pytorch-2-10-release-blog Pytorch 2.10  was officially released January 21, 2026.

The installation instructions on this repo code page that led you to the issue: 

> We generally recommend using the latest major version of pytorch with the latest cuda version **unless it is less than 2 weeks old.**

This means it should be working soon.

You are a Mac user, is Triton not available for it?  You try "to load WAN21" which works well for other Mac users with prior Pytorch versions. You either go back to Pytorch 2.9.1 or you wait until ComfyUI's "kitchen" backend supports it.

**Comment by Dinosorceror** [comment]
<img width="804" height="307" alt="Image" src="https://github.com/user-attachments/assets/3355710a-129f-49f4-bbd3-2d9f795b1fcd" />

I'm still getting this after numerous ComfyUI auto-updates on macOS (Apple silicon.)  Does anyone have an easy guide to fix?  Looking at tech responses above doesn't grant any clarity into issue, other than a reference to pytorch needing to play catch up.  Does someone have a guide on downgrading pytorch under macOS?  Anyone else actually doing LTX 2 Video successfully on Apple silicon who can advise?  Right now, ComfyUI is just dead in the water on macOS for me.  Any advice/guides appreciated to fix.

**Comment by FramedStone** [comment]
same here!

**Comment by MisterDiz** [comment]
same same
(fresh install up-to-date on MacOS M1)

**Comment by david-mart** [comment]
same issue, fresh install M4 Max, Tahoe 26.2

**Comment by ViesLink** [comment]
same issue, fresh install M5

**Comment by pigubaoza** [comment]
same here. M1 Max.  @GlamoramaAttack how do i install another version of pytorch? i installed straight from comfy.org. perhaps the version of `torch` should be pinned in the requirements.txt?

**Comment by GlamoramaAttack** [comment]
No, better not, if you ask how to install it ;-) but I'm just a Windows user and you and the other users have a common Mac/ComfyUI-problem. I really don't know how to install anything on Mac. But maybe here are some workarounds, from...

August 2024:
Not running on MacOS ComfyUI ( https://huggingface.co/black-forest-labs/FLUX.1-schnell/discussions/13 )

November 2024-September 2025:
Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype. SD3.5 FP8 Mac M2  #5533 ( https://github.com/Comfy-Org/ComfyUI/issues/5533 )

September 2025 -December 2025:
Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype. #9263
( https://github.com/Comfy-Org/ComfyUI/issues/9263 )

But if you had prior versions which worked, you could downgrade because it doesn't seem to be a ComfyUI issue - Mac seems to be slow in catching up if you read some of the comments.

**Comment by MisterDiz** [comment]
The issue is MacOS doesn't really support FP8, I switched text encoder to the FP16 variant and the error went away

**Comment by Dinosorceror** [comment]
I'm pretty much a noob when it comes to ComfyUI.  Can you explain where
that's changed?

**Comment by MisterDiz** [comment]
> I'm pretty much a noob when it comes to ComfyUI.  Can you explain where
> that's changed?
> […](#)

It will vary with whichever model you're trying to run, but you're looking to replace any models that are `fp4` or less, for example with `lx-2`, you will replace `ltx-2-19b-dev-fp8` with `bf16` variant, you can find it here: [https://github.com/wildminder/awesome-ltx2](https://github.com/wildminder/awesome-ltx2)
Most things are available on Hugging Face. Download what you need and place the files in the same folders as the goofy ones, press `r` in comfy to refresh and you should be able to select them in the nodes and be good to run. Bear in mind that the higher fidelity models will be more memory hungry though. Wan 2.2 was the easiest to set up for me.

**Comment by quantumArc** [comment]
The file sd3.5_large_fp8_scaled.safetensors is specifically formatted with FP8 (Float8) weights. Because Apple’s MPS (Metal Performance Shaders) backend does not currently support the Float8_e4m3fn data type, ComfyUI crashes when it attempts to load these tensors onto your Mac's GPU. 

To fix this on a Mac, you must use a model version that uses supported data types like FP16 or BF16.

**Comment by marcoszhang35-cell** [comment]
> The issue is MacOS doesn't really support FP8, I switched text encoder to the FP16 variant and the error went away
How to switch, could you show us a clear way to switch it?

**Comment by zhujunting1** [comment]
M5 Refresh

**Comment by pawel-mazurkiewicz** [comment]
Hello, my fellow Mac users. Long have I avoided ComfyUI because most of the workflows you'd find would be useless because of this issue, but I finally got fed up with it and decided to have it worked around, but not by using CPU fallback and/or fp16 upcast. The result is [this repo](https://github.com/pawel-mazurkiewicz/ComfyUI-AppleSilicon-FP8) where I put my fixes for ComfyUI to pick up generic workflows floating around the web and have it work on Apple Silicon out of the box and also some smaller fixes (like a documented SDPA values drift on sequences above certain point). I have been able to use Ideogram workflows (both KJ and vanilla from Templates), Flux, Qwen 2512, without manual changes to templated workflows (using f8e4m3fn weights) and so far so good - I hope it'll help someone. Put up issues in that repo if some workflow is not working out of the box.
