### ISSUE TITLE
升级到cli_args: Default comfy to DynamicVram mode (#12658)版本后运行：audio-separation-nodes-comfyui节点 和ComfyUI-llama-cpp_vlm自定义插件时报错

### ISSUE THREAD

**Issue by lyqxx2023** [comfyanonymous/ComfyUI#12728]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

My ComfyUI integration environment configuration is as follows:

PyTorch version: 2.10.0+cu130

Xformers version: 0.0.34

Graphics card: cuda:0 NVIDIA GeForce RTX 5090 Laptop GPU

After upgrading to cli_args: Default Comfy to DynamicVram mode (#12658), errors occurred when running the audio-separation-nodes-comfyui node and the ComfyUI-llama-cpp_vlm custom plugin.

### Actual Behavior

<img width="1863" height="1006" alt="Image" src="https://github.com/user-attachments/assets/137fe860-7f33-4f5b-be4c-082c56953145" />

<img width="1385" height="785" alt="Image" src="https://github.com/user-attachments/assets/c76238f3-ec30-4ebf-9e2a-e88078c026a8" />

### Steps to Reproduce

It worked fine in version #12653 where dynamic_vram was disabled when weight hooks were applied, but it threw an error after the upgrade.

### Debug Logs

```powershell
the audio-separation-nodes-comfyui node resulted in the following error:

PyTorch version: 2.10.0+cu130

Xformers version: 0.0.34

Graphics card: cuda:0 NVIDIA GeForce RTX 5090 Laptop GPU

After upgrading to: cli_args: Default Comfy to DynamicVram mode (#12658), running the audio-separation-nodes-comfyui node resulted in the following error:

Traceback (most recent call last):

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 524, in execute

output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 333, in get_output_data 
return_values ​​= await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\custom_nodes\comfyui-lora-manager\py\metadata_collector\metadata_hook.py", line 168, in async_map_node_over_list_with_metadata 
results = await original_map_node_over_list( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 307, in _async_map_node_over_list 
await process_inputs(input_dict, i) 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 295, in process_inputs 
result = f(**inputs) 
^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\custom_nodes\audio-separation-nodes-comfyui\src\separation.py", line 86, in main 
sources = self.separate_sources( 
^^^^^^^^^^^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\custom_nodes\audio-separation-nodes-comfyui\src\separation.py", line 160, in separate_sources 
out = model.forward(chunk) 
^^^^^^^^^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\python\Lib\site-packages\torchaudio\models\_hdemucs.py", line 547, in forward 
z = self._spec(input) 
^^^^^^^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\python\Lib\site-packages\torchaudio\models\_hdemucs.py", line 483, in _spec 
z = _spectro(x, nfft, hl)[..., :-1, :] 
^^^^^^^^^^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\python\Lib\site-packages\torchaudio\models\_hdemucs.py", line 925, in _spectro 
z = torch.stft( 
^^^^^^^^^^^ 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\python\Lib\site-packages\torch\functional.py", line 681, in stft

return _VF.stft( # type: ignore[attr-defined]

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR






running the ComfyUI-llama-cpp_vlm custom plug-in, an error occurs:

llama_cpp_model_loader
Failed to load model from file: H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\models\LLM\qwen\Qwen3-VL-8B-Instruct-abliterated-v2.0.Q8_0.gguf


# ComfyUI Error Report
## Error Details
- **Node ID:** 9
- **Node Type:** llama_cpp_model_loader
- **Exception Type:** ValueError
- **Exception Message:** Failed to load model from file: H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\models\LLM\qwen\Qwen3-VL-8B-Instruct-abliterated-v2.0.Q8_0.gguf

## Stack Trace
 
File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 524, in execute 
output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 333, in get_output_data 
return_values ​​= await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\custom_nodes\comfyui-lora-manager\py\metadata_collector\metadata_hook.py", line 168, in async_map_node_over_list_with_metadata 
results = await original_map_node_over_list( 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 307, in _async_map_node_over_list 
await process_inputs(input_dict, i) 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\execution.py", line 295, in process_inputs 
result = f(**inputs) 
^^^^^^^^^^^ 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\custom_nodes\ComfyUI-llama-cpp_vlm\nodes.py", line 360, in loadmodel 
LLAMA_CPP_STORAGE.load_model(custom_config) 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\custom_nodes\ComfyUI-llama-cpp_vlm\nodes.py", line 197, in load_model 
cls.llm = Llama(model_path, chat_handler=cls.chat_handler, n_gpu_layers=n_gpu_layers, n_ctx=n_ctx, verbose=False) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\python\Lib\site-packages\llama_cpp\llama.py", line 404, in __init__ internals.LlamaModel( 

File "H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\python\Lib\site-packages\llama_cpp\_internals.py", line 56, in __init__ 
raise ValueError(f"Failed to load model from file: {path_model}")


## System Information
- **ComfyUI Version:** 0.15.1
- **Arguments:** H:\sd\ComfyUI\ComfyUI-aki-v1.3\COMFYUI_dapaopao\ComfyUI\main.py --auto-launch --preview-method auto --use-sage-attention --disable-smart-memory --disable-cuda-malloc
- **OS:** win32
- **Python Version:** 3.11.13 | packaged by conda-forge | (main, Jun 4 2025, 14:39:58) [MSC v.1943 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.10.0+cu130
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 5090 Laptop GPU: cudaMallocAsync 
- **Type:** cuda 
- **VRAM Total:** 25650855936 
- **VRAM Free:** 24206245888 
- **Torch VRAM Total:** 33554432 
- **Torch VRAM Free:** 25034752
```

**Comment by rattus128** [comment]
Please update to comfy-aimdo 0.2.4 using pip and try again.

**Comment by lyqxx2023** [comment]
After upgrading to comfy-aimdo 0.2.4 using your method, it works normally. Thank you.
