### ISSUE TITLE
AMD - Linux - HIP error locks up computer

### ISSUE THREAD

**Issue by AlfredSartan572** [comfyanonymous/ComfyUI#12762]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

When running a Wan2.2 workflow with command-line arguments
--use-pytorch-cross-attention --disable-smart-memory
and a HIP error happens, then that gets logged, or an OOM is displayed, but the computer remains functional.

### Actual Behavior

When running a Wan2.2 workflow with command-line arguments
--use-pytorch-cross-attention --disable-smart-memory
the computer locks up completely. No mouse, no keyboard.
All I can do then is reboot.

### Steps to Reproduce

Run comfyUI with --use-pytorch-cross-attention --disable-smart-memory
Start a Wan 2.2 I2V flow, using FP8 models, with lightx2v, 6 steps, and a resolution of at least 640 x  800.
Run the workflow and wait.

### Debug Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2026-03-03 12:50:58.088] ** ComfyUI startup time: 2026-03-03 12:50:58.088
[2026-03-03 12:50:58.088] ** Platform: Linux
[2026-03-03 12:50:58.088] ** Python version: 3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]
[2026-03-03 12:50:58.088] ** Python executable: ~/comfyui-venv/bin/python3
[2026-03-03 12:50:58.088] ** ComfyUI Path: ~/ComfyUI
[2026-03-03 12:50:58.088] ** ComfyUI Base Folder Path: ~/ComfyUI
[2026-03-03 12:50:58.088] ** User directory: ~/ComfyUI/user
[2026-03-03 12:50:58.088] ** ComfyUI-Manager config path: ~/ComfyUI/user/__manager/config.ini
[2026-03-03 12:50:58.088] ** Log path: ~/ComfyUI/user/comfyui.log

Prestartup times for custom nodes:
[2026-03-03 12:50:58.133]    0.0 seconds: ~/ComfyUI/custom_nodes/rgthree-comfy
[2026-03-03 12:50:58.133]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-easy-use
[2026-03-03 12:50:58.133]    0.4 seconds: ~/ComfyUI/custom_nodes/comfyui-manager
[2026-03-03 12:50:58.133] 
[2026-03-03 12:50:59.923] Found comfy_kitchen backend cuda: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
[2026-03-03 12:50:59.923] Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
[2026-03-03 12:50:59.923] Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
[2026-03-03 12:50:59.928] Checkpoint files will always be loaded safely.
[2026-03-03 12:50:59.936] Total VRAM 24560 MB, total RAM 63938 MB
[2026-03-03 12:50:59.936] pytorch version: 2.9.1+rocm7.2.0.git7e1940d4
[2026-03-03 12:50:59.936] AMD arch: gfx1100
[2026-03-03 12:50:59.936] ROCm version: (7, 2)
[2026-03-03 12:50:59.936] Set vram state to: NORMAL_VRAM
[2026-03-03 12:50:59.936] Disabling smart memory management
[2026-03-03 12:50:59.936] Device: cuda:0 Radeon RX 7900 XTX : native
[2026-03-03 12:50:59.937] Using async weight offloading with 2 streams
[2026-03-03 12:51:00.079] Using pytorch attention
[2026-03-03 12:51:01.476] Python version: 3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]
[2026-03-03 12:51:01.476] ComfyUI version: 0.15.1
[2026-03-03 12:51:01.478] ComfyUI frontend version: 1.39.19
[2026-03-03 12:51:01.479] [Prompt Server] web root: ~/comfyui-venv/lib/python3.12/site-packages/comfyui_frontend_package/static
[2026-03-03 12:51:02.157] ### Loading: ComfyUI-Manager (V3.39.2)
[2026-03-03 12:51:02.158] [ComfyUI-Manager] network_mode: offline
[2026-03-03 12:51:02.158] [ComfyUI-Manager] ComfyUI per-queue preview override detected (PR #11261). Manager's preview method feature is disabled. Use ComfyUI's --preview-method CLI option or 'Settings > Execution > Live preview method'.
[2026-03-03 12:51:02.194] ### ComfyUI Version: v0.15.1-5-g35e9fce7 | Released on '2026-02-26'
[2026-03-03 12:51:02.200] [ComfyUI-Manager] All startup tasks have been completed.
[2026-03-03 12:51:02.208] 
[2026-03-03 12:51:02.209] [92m[rgthree-comfy] Loaded 48 extraordinary nodes. 🎉[0m
[2026-03-03 12:51:02.209] 
[2026-03-03 12:51:02.209] [33m[rgthree-comfy] ComfyUI's new Node 2.0 rendering may be incompatible with some rgthree-comfy nodes and features, breaking some rendering as well as losing the ability to access a node's properties (a vital part of many nodes). It also appears to run MUCH more slowly spiking CPU usage and causing jankiness and unresponsiveness, especially with large workflows. Personally I am not planning to use the new Nodes 2.0 and, unfortunately, am not able to invest the time to investigate and overhaul rgthree-comfy where needed. If you have issues when Nodes 2.0 is enabled, I'd urge you to switch it off as well and join me in hoping ComfyUI is not planning to deprecate the existing, stable canvas rendering all together.
[0m
[2026-03-03 12:51:02.442] ### Loading: ComfyUI-Impact-Pack (V8.28.2)
[2026-03-03 12:51:02.456] 
----------------------------------------------------------------------------
[Impact Pack] The SAM2 functionality is unavailable because the `facebook/sam2` dependency is not installed.

Installation command:
~/comfyui-venv/bin/python3 -m pip install git+https://github.com/facebookresearch/sam2
----------------------------------------------------------------------------

[2026-03-03 12:51:02.462] 
----------------------------------------------------------------------------
[Impact Pack] The SAM2 functionality is unavailable because the `facebook/sam2` dependency is not installed.

Installation command:
~/comfyui-venv/bin/python3 -m pip install git+https://github.com/facebookresearch/sam2
----------------------------------------------------------------------------

[2026-03-03 12:51:02.467] [Impact Pack] Wildcard total size (0.00 MB) is within cache limit (50.00 MB). Using full cache mode.
[2026-03-03 12:51:02.468] [Impact Pack] Wildcards loading done.
[2026-03-03 12:51:02.496] ### Loading: ComfyUI-Impact-Subpack (V1.3.5)
[2026-03-03 12:51:02.497] [Impact Pack/Subpack] Using folder_paths to determine whitelist path: ~/ComfyUI/user/default/ComfyUI-Impact-Subpack/model-whitelist.txt
[2026-03-03 12:51:02.497] [Impact Pack/Subpack] Ensured whitelist directory exists: ~/ComfyUI/user/default/ComfyUI-Impact-Subpack
[2026-03-03 12:51:02.497] [Impact Pack/Subpack] Loaded 0 model(s) from whitelist: ~/ComfyUI/user/default/ComfyUI-Impact-Subpack/model-whitelist.txt
[2026-03-03 12:51:02.532] [Impact Subpack] ultralytics_bbox: ~/ComfyUI/models/ultralytics/bbox
[2026-03-03 12:51:02.532] [Impact Subpack] ultralytics_segm: ~/ComfyUI/models/ultralytics/segm
[2026-03-03 12:51:03.038] [34m[ComfyUI-Easy-Use] server: [0mv1.3.6 [92mLoaded[0m
[2026-03-03 12:51:03.038] [34m[ComfyUI-Easy-Use] web root: [0m~/ComfyUI/custom_nodes/comfyui-easy-use/web_version/v2 [92mLoaded[0m
[2026-03-03 12:51:03.042] ComfyUI-GGUF: Allowing full torch compile
[2026-03-03 12:51:03.043] 
Import times for custom nodes:
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/websocket_image_save.py
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-mxtoolkit
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-logic
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/ComfyUI-GGUF
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/ComfyUI-VFI
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-image-saver
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-frame-interpolation
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/rgthree-comfy
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui_essentials
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-videohelpersuite
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-impact-pack
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-impact-subpack
[2026-03-03 12:51:03.043]    0.0 seconds: ~/ComfyUI/custom_nodes/comfyui-manager
[2026-03-03 12:51:03.043]    0.2 seconds: ~/ComfyUI/custom_nodes/ComfyUI-KJNodes
[2026-03-03 12:51:03.043]    0.5 seconds: ~/ComfyUI/custom_nodes/comfyui-easy-use
[2026-03-03 12:51:03.043] 
[2026-03-03 12:51:03.044] Context impl SQLiteImpl.
[2026-03-03 12:51:03.045] Will assume non-transactional DDL.
[2026-03-03 12:51:03.075] Assets scan(roots=['models']) completed in 0.028s (created=0, skipped_existing=531, orphans_pruned=0, total_seen=531)
[2026-03-03 12:51:03.100] Starting server

[2026-03-03 12:51:03.101] To see the GUI go to: http://127.0.0.1:8188
[2026-03-03 12:51:08.665] [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[2026-03-03 12:51:08.666] [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[2026-03-03 12:51:08.676] [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/clipspace.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[2026-03-03 12:51:08.677] [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/widgetInputs.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[2026-03-03 12:51:09.185] [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[2026-03-03 12:51:09.196] [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[2026-03-03 12:51:29.510] got prompt
[2026-03-03 12:51:29.544] Using split attention in VAE
[2026-03-03 12:51:29.545] Using split attention in VAE
[2026-03-03 12:51:29.689] VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
[2026-03-03 12:51:30.346] Requested to load CLIPVisionModelProjection
[2026-03-03 12:51:30.504] loaded completely; 23286.80 MB usable, 1208.10 MB loaded, full load: True
[2026-03-03 12:51:31.080] Found quantization metadata version 1
[2026-03-03 12:51:31.080] Using MixedPrecisionOps for text encoder
[2026-03-03 12:51:31.701] CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
[2026-03-03 12:51:31.821] Found quantization metadata version 1
[2026-03-03 12:51:31.821] Detected mixed precision quantization
[2026-03-03 12:51:31.821] Using mixed precision operations
[2026-03-03 12:51:31.833] model weight dtype torch.float16, manual cast: torch.float16
[2026-03-03 12:51:31.835] model_type FLOW
[2026-03-03 12:51:32.103] Found quantization metadata version 1
[2026-03-03 12:51:32.103] Detected mixed precision quantization
[2026-03-03 12:51:32.103] Using mixed precision operations
[2026-03-03 12:51:32.114] model weight dtype torch.float16, manual cast: torch.float16
[2026-03-03 12:51:32.116] model_type FLOW
[2026-03-03 12:51:32.219] Requested to load WanTEModel
[2026-03-03 12:51:36.021] loaded completely; 21584.80 MB usable, 6419.48 MB loaded, full load: True
[2026-03-03 12:51:37.345] Requested to load WanVAE
[2026-03-03 12:51:38.697] loaded completely; 17722.62 MB usable, 242.03 MB loaded, full load: True
[2026-03-03 13:04:05.276] Requested to load WAN21
[2026-03-03 13:04:15.347] loaded completely; 15459.76 MB usable, 13631.42 MB loaded, full load: True
[2026-03-03 13:09:11.206] 
100%|████████████████████████████████████████████████████████████████████████████| 3/3 [04:55<00:00, 114.84s/it]
100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [04:55<00:00, 98.61s/it]
[2026-03-03 13:11:38.550] Requested to load WAN21
[2026-03-03 13:11:54.046] loaded completely; 15636.01 MB usable, 13631.42 MB loaded, full load: True
[2026-03-03 13:16:51.171] 
100%|████████████████████████████████████████████████████████████████████████████| 3/3 [04:57<00:00, 105.14s/it]
100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [04:57<00:00, 99.03s/it]
[2026-03-03 13:16:53.397] ~/ComfyUI/comfy/latent_formats.py:516: UserWarning: HIP warning: unspecified launch failure (Triggered internally at /pytorch/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:83.)
  latents_mean = self.latents_mean.to(latent.device, latent.dtype)
[2026-03-03 13:16:53.421] !!! Exception during processing !!! HIP error: unspecified launch failure
Search for `hipErrorLaunchFailure' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

[2026-03-03 13:16:53.422] Traceback (most recent call last):
  File "~/ComfyUI/execution.py", line 524, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/execution.py", line 333, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/execution.py", line 307, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "~/ComfyUI/execution.py", line 295, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "~/ComfyUI/nodes.py", line 1627, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/nodes.py", line 1558, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/sample.py", line 66, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/samplers.py", line 1177, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/samplers.py", line 1067, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/samplers.py", line 1049, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/samplers.py", line 993, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/samplers.py", line 980, in inner_sample
    return self.inner_model.process_latent_out(samples.to(torch.float32))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/model_base.py", line 333, in process_latent_out
    return self.latent_format.process_out(latent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/comfy/latent_formats.py", line 516, in process_out
    latents_mean = self.latents_mean.to(latent.device, latent.dtype)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: HIP error: unspecified launch failure
Search for `hipErrorLaunchFailure' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


[2026-03-03 13:16:53.424] Exception in thread Thread-3 (prompt_worker):
[2026-03-03 13:16:53.424] Traceback (most recent call last):
[2026-03-03 13:16:53.424]   File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
[2026-03-03 13:16:53.425]     self.run()
[2026-03-03 13:16:53.425]   File "/usr/lib/python3.12/threading.py", line 1010, in run
[2026-03-03 13:16:53.425]     self._target(*self._args, **self._kwargs)
[2026-03-03 13:16:53.425]   File "~/ComfyUI/main.py", line 261, in prompt_worker
[2026-03-03 13:16:53.425]     e.execute(item[2], prompt_id, extra_data, item[4])
[2026-03-03 13:16:53.425]   File "~/ComfyUI/execution.py", line 688, in execute
[2026-03-03 13:16:53.425]     asyncio.run(self.execute_async(prompt, prompt_id, extra_data, execute_outputs))
[2026-03-03 13:16:53.425]   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
[2026-03-03 13:16:53.425]     return runner.run(main)
[2026-03-03 13:16:53.426]            ^^^^^^^^^^^^^^^^
[2026-03-03 13:16:53.426]   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
[2026-03-03 13:16:53.426]     return self._loop.run_until_complete(task)
[2026-03-03 13:16:53.426]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2026-03-03 13:16:53.426]   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
[2026-03-03 13:16:53.426]     return future.result()
[2026-03-03 13:16:53.426]            ^^^^^^^^^^^^^^^
[2026-03-03 13:16:53.427]   File "~/ComfyUI/execution.py", line 762, in execute_async
[2026-03-03 13:16:53.427]     comfy.model_management.unload_all_models()
[2026-03-03 13:16:53.427]   File "~/ComfyUI/comfy/model_management.py", line 1715, in unload_all_models
[2026-03-03 13:16:53.427]     free_memory(1e30, get_torch_device())
[2026-03-03 13:16:53.427]                       ^^^^^^^^^^^^^^^^^^
[2026-03-03 13:16:53.427]   File "~/ComfyUI/comfy/model_management.py", line 201, in get_torch_device
[2026-03-03 13:16:53.427]     return torch.device(torch.cuda.current_device())
[2026-03-03 13:16:53.427]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2026-03-03 13:16:53.428]   File "~/comfyui-venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 1070, in current_device
[2026-03-03 13:16:53.428]     return torch._C._cuda_getDevice()
[2026-03-03 13:16:53.428]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2026-03-03 13:16:53.428] torch.AcceleratorError: HIP error: unspecified launch failure
Search for `hipErrorLaunchFailure' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
[2026-03-03 13:16:53.429]
```

### Other

I updated the log file so that it shows "~/..." instead of "/home/myuser/..." (see #12716)

my hardware setup:
CPU : AMD Ryzen 9 7950X (16c/32t)
GPU : AMD Radeon RX 7900 XTX (24 GB VRAM)
System Memory : 64 GB
OS : Linux Mint 22.3
Driver: latest drivers with ROCm 7.2

When I run the same flow with --use-quad-cross-attention, then I don't have any issues.

I observed 1 visual difference:
with "--use-quad-cross-attention" the progress bar in the KSampler nodes starts at 0%, then the flow does 1 step, and then the progress bar advances. So when all steps in 1 KSampler are done, the progress bar jumps to 100% and the workflow continues with the next node.

But with "--use-pytorch-cross-attention", the progress bar immediately progresses 1 step, and then does some work. So when the second-but-last step in the KSampler is busy, then the progress bar is already at 100%. And then is remains at 100% while the last step is running.

**Comment by chejh-amd** [comment]
Hi @AlfredSartan572 Your issue is similar to [#2229](https://github.com/ROCm/TheRock/issues/2229), and #2229 mentions that the latest build (torch‑2.10.0a0+rocm7.11.0a20251211) can use --use-pytorch-cross-attention.

**Comment by LuXuxue** [comment]
if you have enabled miopen, `export MIOPEN_DEBUG_CONV_DIRECT=0` may solve your issue

**Comment by AlfredSartan572** [comment]
Adding that option resolves the issue.
I get an error when running the workflow: !!! Exception during processing !!! miopenStatusUnknownError
This error appears in a nice popup, so I can properly close the app and then try again with other settings.
The system no longer locks up.

**Comment by LuXuxue** [comment]
[0xDELUXA](https://github.com/patientx/ComfyUI-Zluda/issues/435#issuecomment-4026960520) said `export MIOPEN_DEBUG_CONV_DIRECT=0` sometimes breaks MIOpen, and suggests changing it to `export MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0`.

**Comment by 0xDELUXA** [comment]
`MIOPEN_DEBUG_CONV_DIRECT=0` disables the entire Direct convolution algorithm family in MIOpen, blocking all solvers whose names start with `ConvDirect*`. In cases like [this](https://github.com/patientx/ComfyUI-Zluda/issues/435#issuecomment-4019999041), if no alternative solver is available, MIOpen will error out with `No suitable algorithm was found to execute the required convolution`.
`MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0` is more specific, it only disables a single solver: `ConvDirectNaiveConvFwd`.

**Comment by AlfredSartan572** [comment]
Using "MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0" gives the same error as just setting "MIOPEN_DEBUG_CONV_DIRECT=0".
This happens during the WanImageToVideo node, 2 seconds after it starts (in a successfull run, this node takes about 9 seconds).

In the logging file I get :
> [2026-03-10 21:25:36.706] Requested to load WanVAE
> [2026-03-10 21:25:38.087] loaded completely; 17648.62 MB usable, 242.03 MB loaded, full load: True
> [2026-03-10 21:25:38.572] !!! Exception during processing !!! miopenStatusUnknownError
> [2026-03-10 21:25:38.576] Traceback (most recent call last):
>   File "~/ComfyUI/execution.py", line 524, in execute
>     output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
> 
In the console it additionally logs that "no suitable algorithm" error.
> Requested to load WanVAE
> loaded completely; 17648.62 MB usable, 242.03 MB loaded, full load: True
> MIOpen Error: linux:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/ocl/convolutionocl.cpp:610: No suitable algorithm was found to execute the required convolution
> !!! Exception during processing !!! miopenStatusUnknownError
> Traceback (most recent call last):
>   File "~/ComfyUI/execution.py", line 524, in execute
>     output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
>

using "COMFYUI_ENABLE_MIOPEN=0" works correctly.
=> issue resolved. Thank you!

I recently moved from Windows to Linux. I'm OK with Linux but definitely not a specialist.
On Windows, I got the best results with --use-pytorch-cross-attention, so I simply wanted to test that performance on Linux.
Maybe I did something wrong with the install? I described my installation in discussion [#12761](https://github.com/Comfy-Org/ComfyUI/discussions/12761)

Using --use-pytorch-cross-attention with COMFYUI_ENABLE_MIOPEN=0 now finishes correctly but I get timings that are about 20% slower than when using --use-quad-cross-attention. I'll stick to quad-cross-attention :-)

**Comment by 0xDELUXA** [comment]
This means you actually need `ConvDirectNaiveConvFwd`, so do not set `MIOPEN_DEBUG ... =0`.

**Comment by LuXuxue** [comment]
another way is `export MIOPEN_FIND_MODE=FAST` without `COMFYUI_ENABLE_MIOPEN=0 MIOPEN_DEBUG ... =0`, this will make miopen only use system database and will not setup user find database, which may lead to freeze. you can try it and find which run faster.
