### ISSUE TITLE
CUDA error OOM after updating to v0.16.3

### ISSUE THREAD

**Issue by trevormyers** [comfyanonymous/ComfyUI#12823]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

I updated to the newest version of comfyui tonight and started having cuda error out of memory issues. I'm using the exact same workflow as I was when getting no errors before updating. I have tried simplifying my workflow, disabling all custom nodes and only using the core nodes, but I still have the oom error. it seems to happen on vae decode. sometimes it will happen on the first job, and other times it wont happen until the 10th job. it is random.

[comfyui.prev.log](https://github.com/user-attachments/files/25812621/comfyui.prev.log)

### Logs

```powershell
log file was too long, uploaded the file instead
```

### Other

i have done some research and others are stating the new dynamic vram feature is causing problems. i added the argument to disable it, and my oom errors have stopped. maybe this is pure coincidence, but from what i can gather, this feature was added since i last updated (maybe 2 weeks ago).

**Comment by rattus128** [comment]
@trevormyers can you confirm your version of comfy-aimdo in pip?

```
pip show comfy-aimdo
```

Your logs are missing some expected startup messages from this component. There is an issue where the aimdo messages dont appear in the browser terminal.

Did you paste from the in-browser console or from the launch terminal?

If aimdo is up to date and you still have problems, can you re-paste the startup log from the terminal directly (not browser console). You dont need to repro the crash, we can just debug your startup messages.

If the issue persist after those steps and your logs are the same, we can debug further why your aimdo isn't probing correctly.

Aimdo is the low level backend to the dynamic VRAM engine

**Comment by rattus128** [comment]
> [@trevormyers](https://github.com/trevormyers) can you confirm your version of comfy-aimdo in pip?
> 
> ```
> pip show comfy-aimdo
> ```
> 
> Your logs are missing some expected startup messages from this component. There is an issue where the aimdo messages dont appear in the browser terminal.
> 
> Did you paste from the in-browser console or from the launch terminal?
> 
> If aimdo is up to date and you still have problems, can you re-paste the startup log from the terminal directly (not browser console). You dont need to repro the crash, we can just debug your startup messages.
> 
> If the issue persist after those steps and your logs are the same, we can debug further why your aimdo isn't probing correctly.
> 
> Aimdo is the low level backend to the dynamic VRAM engine

I should probably say we need comfy-aimdo 0.2.7+.

This can be repulled with pip install -r requirements.txt

**Comment by rattus128** [comment]
Also, if your aimdo is stale, let us know what your update processes was.

**Comment by bandifiu** [comment]
I updated to 16.3 from 14 using comfy manager and my RAM usage went to 99% on 96G using a wan 2.2 workflow. After starting with --disable-dynamic-vram  the same workflow works like before and RAM usage tops at about 60G, including all my other background tasks.

**Comment by rattus128** [comment]
> I updated to 16.3 from 14 using comfy manager and my RAM usage went to 99% on 96G using a wan 2.2 workflow. After starting with --disable-dynamic-vram the same workflow works like before and RAM usage tops at about 60G, including all my other background tasks.

What are your runtimes before and after though and did it slow you down? V16.3 will cache your models in RAM on load but it will do so as uncomitted memory which means it will use the RAM and report it in task manager, but if other things come along that are more important, like other processes it will free it. Thats why its able to sit stable at 99%.

Can you check your "committed" memory in task manager and let us know if its higher or lower. Also let us know if the workflow is slower or faster.

**Comment by bandifiu** [comment]
With dynamic VRAM, committed RAM is lower, all in use, and more shared VRAM used. Total runtime almost the same for the first, the 2nd was slower than with disabled dynamic VRAM. (screenshots are in Hungarian)
```
** Platform: Windows
** Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
** Python executable: E:\StableDiffusion\ComfyUI\.venv_2.9\Scripts\python.exe
** ComfyUI Path: E:\StableDiffusion\ComfyUI
** ComfyUI Base Folder Path: E:\StableDiffusion\ComfyUI
** User directory: E:\StableDiffusion\ComfyUI\user
** ComfyUI-Manager config path: E:\StableDiffusion\ComfyUI\user\__manager\config.ini
** Log path: E:\StableDiffusion\ComfyUI\user\comfyui.log
[PRE] ComfyUI-Manager

Prestartup times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\rgthree-comfy

E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\torch\cuda\__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend cuda: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Checkpoint files will always be loaded safely.
Total VRAM 16376 MB, total RAM 98070 MB
pytorch version: 2.9.1+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 44131.0
working around nvidia conv3d memory bug.
Using pytorch attention
aimdo: src-win/cuda-detour.c:77:INFO:aimdo_setup_hooks: found driver at 00007FF90CFE0000, installing 4 hooks
aimdo: src-win/cuda-detour.c:61:DEBUG:install_hook_entrys: hooks successfully installed
aimdo: src/control.c:66:INFO:comfy-aimdo inited for GPU: NVIDIA GeForce RTX 4070 Ti SUPER (VRAM: 16375 MB)
DynamicVRAM support detected and enabled
Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.16.3
ComfyUI frontend version: 1.39.19
[Prompt Server] web root: E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\comfyui_frontend_package\static
[START] ComfyUI-Manager
### Loading: ComfyUI-Manager (V4.1)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 4863 [1c218282] *DETACHED | Released on '2026-03-05'
[ComfyUI-Manager] The matrix sharing feature has been disabled because the `matrix-nio` dependency is not installed.
        To use this feature, please run the following command:
        E:\StableDiffusion\ComfyUI\.venv_2.9\Scripts\python.exe -m pip install matrix-nio

[ComfyUI-Manager] Legacy UI is enabled.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/extension-node-map.json
[Crystools INFO] Crystools version: 1.27.4
[Crystools INFO] Platform release: 11
[Crystools INFO] JETSON: Not detected.
[Crystools INFO] CPU: Intel(R) Core(TM) i7-14700K - Arch: AMD64 - OS: Windows 11
[Crystools INFO] pynvml (NVIDIA) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools INFO] NVIDIA Driver: 591.74
ComfyUI-GGUF: Allowing full torch compile

================================================================================
WARNING: llama-cpp-python library not found, GGUF functionality is not available
To use GGUF features, install additional dependencies:
pip install -r requirements_gguf.txt
Basic JoyCaption functionality is still available
================================================================================

[JoyCaption] ℹ️ No custom models found, skipping user-defined HF models.
E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[ComfyUI-RMBG] v3.0.0 | 43 nodes Loaded
[E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False
[E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'MIGraphXExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
ComfyUI-GGUF: Allowing full torch compile

[rgthree-comfy] Loaded 48 epic nodes. 🎉

[rgthree-comfy] ComfyUI's new Node 2.0 rendering may be incompatible with some rgthree-comfy nodes and features, breaking some rendering as well as losing the ability to access a node's properties (a vital part of many nodes). It also appears to run MUCH more slowly spiking CPU usage and causing jankiness and unresponsiveness, especially with large workflows. Personally I am not planning to use the new Nodes 2.0 and, unfortunately, am not able to invest the time to investigate and overhaul rgthree-comfy where needed. If you have issues when Nodes 2.0 is enabled, I'd urge you to switch it off as well and join me in hoping ComfyUI is not planning to deprecate the existing, stable canvas rendering all together.

⚡ SeedVR2 optimizations check: SageAttention ✅ | Flash Attention ❌ | Triton ✅
💡 Optional: pip install flash-attn
🔧 Conv3d workaround active: PyTorch 2.9.1, cuDNN 91200 (fixing VAE 3x memory bug)
📊 Initial CUDA memory: 14.67GB free / 15.99GB total

Import times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-VFI
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\gguf_loader_patch.py
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_essentials
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\NN-custom-nodes
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-custom-scripts
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-LTXVideo
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-JoyCaption
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.4 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-videohelpersuite
   0.5 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-florence2
   0.7 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.7 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\seedvr2_videoupscaler
   0.8 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-MMAudio
   0.9 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-rmbg

Context impl SQLiteImpl.
Will assume non-transactional DDL.
Assets scan(roots=['models']) completed in 0.171s (created=0, skipped_existing=1071, orphans_pruned=0, total_seen=1073)
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\comfyui_manager\custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load WanTEModel
Model WanTEModel prepared for dynamic VRAM loading. 10835MB Staged. 0 patches attached. Force pre-loaded 49 weights: 392 KB.
Model WanTEModel prepared for dynamic VRAM loading. 10835MB Staged. 0 patches attached. Force pre-loaded 49 weights: 392 KB.
Requested to load WanVAE
0 models unloaded.
Model WanVAE prepared for dynamic VRAM loading. 242MB Staged. 0 patches attached. Force pre-loaded 52 weights: 28 KB.
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Using sage attention mode: auto
Requested to load WAN21
0 models unloaded.
Model WAN21 prepared for dynamic VRAM loading. 13627MB Staged. 1054 patches attached.
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:24<00:00, 28.81s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = False
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Using sage attention mode: auto
Requested to load WAN21
Model WAN21 prepared for dynamic VRAM loading. 13627MB Staged. 1054 patches attached.
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:16<00:00, 27.26s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = False
Requested to load WanVAE
Model WanVAE prepared for dynamic VRAM loading. 242MB Staged. 0 patches attached. Force pre-loaded 52 weights: 28 KB.
Loading RIFE model from: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-VFI\rife\train_log\flownet.pkl
Prompt executed in 358.35 seconds
got prompt
Requested to load WanTEModel
Model WanTEModel prepared for dynamic VRAM loading. 10835MB Staged. 0 patches attached. Force pre-loaded 49 weights: 392 KB.
0 models unloaded.
Model WanVAE prepared for dynamic VRAM loading. 242MB Staged. 0 patches attached. Force pre-loaded 52 weights: 28 KB.
Requested to load WAN21
0 models unloaded.
Model WAN21 prepared for dynamic VRAM loading. 13627MB Staged. 1054 patches attached.
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:25<00:00, 29.01s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_a
ccumulation = False
Requested to load WAN21
Model WAN21 prepared for dynamic VRAM loading. 13627MB Staged. 1054 patches attached.
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:13<00:00, 26.75s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = False
Requested to load WanVAE
Model WanVAE prepared for dynamic VRAM loading. 242MB Staged. 0 patches attached. Force pre-loaded 52 weights: 28 KB.
Prompt executed in 347.09 seconds
```
![Image](https://github.com/user-attachments/assets/50687dfe-86b6-4711-89e0-fd09e2bf5122)
![Image](https://github.com/user-attachments/assets/ebbb5bab-0b21-467b-88a5-fa38ef3e2f05)

With `--disable-dynamic-vram`

```
** Platform: Windows
** Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
** Python executable: E:\StableDiffusion\ComfyUI\.venv_2.9\Scripts\python.exe
** ComfyUI Path: E:\StableDiffusion\ComfyUI
** ComfyUI Base Folder Path: E:\StableDiffusion\ComfyUI
** User directory: E:\StableDiffusion\ComfyUI\user
** ComfyUI-Manager config path: E:\StableDiffusion\ComfyUI\user\__manager\config.ini
** Log path: E:\StableDiffusion\ComfyUI\user\comfyui.log
[PRE] ComfyUI-Manager

Prestartup times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\rgthree-comfy

E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\torch\cuda\__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Found comfy_kitchen backend cuda: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Checkpoint files will always be loaded safely.
Total VRAM 16376 MB, total RAM 98070 MB
pytorch version: 2.9.1+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 44131.0
working around nvidia conv3d memory bug.
Using pytorch attention
Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
ComfyUI version: 0.16.3
ComfyUI frontend version: 1.39.19
[Prompt Server] web root: E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\comfyui_frontend_package\static
[START] ComfyUI-Manager
### Loading: ComfyUI-Manager (V4.1)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 4863 [1c218282] *DETACHED | Released on '2026-03-05'
[ComfyUI-Manager] The matrix sharing feature has been disabled because the `matrix-nio` dependency is not installed.
        To use this feature, please run the following command:
        E:\StableDiffusion\ComfyUI\.venv_2.9\Scripts\python.exe -m pip install matrix-nio

[ComfyUI-Manager] Legacy UI is enabled.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/extension-node-map.json
[Crystools INFO] Crystools version: 1.27.4
[Crystools INFO] Platform release: 11
[Crystools INFO] JETSON: Not detected.
[Crystools INFO] CPU: Intel(R) Core(TM) i7-14700K - Arch: AMD64 - OS: Windows 11
[Crystools INFO] pynvml (NVIDIA) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools INFO] NVIDIA Driver: 591.74
ComfyUI-GGUF: Allowing full torch compile

================================================================================
WARNING: llama-cpp-python library not found, GGUF functionality is not available
To use GGUF features, install additional dependencies:
pip install -r requirements_gguf.txt
Basic JoyCaption functionality is still available
================================================================================

[JoyCaption] ℹ️ No custom models found, skipping user-defined HF models.
E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[ComfyUI-RMBG] v3.0.0 | 43 nodes Loaded
[E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False
[E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'MIGraphXExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
ComfyUI-GGUF: Allowing full torch compile

[rgthree-comfy] Loaded 48 epic nodes. 🎉

[rgthree-comfy] ComfyUI's new Node 2.0 rendering may be incompatible with some rgthree-comfy nodes and features, breaking some rendering as well as losing the ability to access a node's properties (a vital part of many nodes). It also appears to run MUCH more slowly spiking CPU usage and causing jankiness and unresponsiveness, especially with large workflows. Personally I am not planning to use the new Nodes 2.0 and, unfortunately, am not able to invest the time to investigate and overhaul rgthree-comfy where needed. If you have issues when Nodes 2.0 is enabled, I'd urge you to switch it off as well and join me in hoping ComfyUI is not planning to deprecate the existing, stable canvas rendering all together.

⚡ SeedVR2 optimizations check: SageAttention ✅ | Flash Attention ❌ | Triton ✅
💡 Optional: pip install flash-attn
🔧 Conv3d workaround active: PyTorch 2.9.1, cuDNN 91200 (fixing VAE 3x memory bug)
📊 Initial CUDA memory: 14.67GB free / 15.99GB total

Import times for custom nodes:
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\gguf_loader_patch.py
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-VFI
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_essentials
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\NN-custom-nodes
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-custom-scripts
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-JoyCaption
   0.0 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-LTXVideo
   0.1 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.5 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-florence2
   0.5 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-videohelpersuite
   0.8 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\seedvr2_videoupscaler
   0.9 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-MMAudio
   1.2 seconds: E:\StableDiffusion\ComfyUI\custom_nodes\comfyui-rmbg

Context impl SQLiteImpl.
Will assume non-transactional DDL.
Assets scan(roots=['models']) completed in 0.365s (created=0, skipped_existing=1071, orphans_pruned=0, total_seen=1073)
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load WanTEModel
loaded completely; 13529.67 MB usable, 10835.48 MB loaded, full load: True
Requested to load WanVAE
Unloaded partially: 4272.48 MB freed, 6563.00 MB remains loaded, 400.00 MB buffer reserved, lowvram patches: 0
loaded completely; 708.50 MB usable, 242.03 MB loaded, full load: True
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Using sage attention mode: auto
Requested to load WAN21
loaded partially; 3185.43 MB usable, 2703.60 MB loaded, 10924.30 MB offloaded, 472.59 MB buffer reserved, lowvram patches: 728
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
 20%|████████████████▊                                                                   | 1/5 [00:29<01:58, 29.57s/it]FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: E:\StableDiffusion\ComfyUI\.venv_2.9\Lib\site-packages\comfyui_manager\custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:20<00:00, 28.14s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = False
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Using sage attention mode: auto
Requested to load WAN21
loaded partially; 3226.44 MB usable, 2746.11 MB loaded, 10881.79 MB offloaded, 472.58 MB buffer reserved, lowvram patches: 728
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:14<00:00, 26.82s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = False
Requested to load WanVAE
loaded completely; 6083.62 MB usable, 242.03 MB loaded, full load: True
Loading RIFE model from: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-VFI\rife\train_log\flownet.pkl
Prompt executed in 352.93 seconds
got prompt
Requested to load WanTEModel
loaded completely; 13205.72 MB usable, 10835.48 MB loaded, full load: True
Unloaded partially: 4832.48 MB freed, 6003.00 MB remains loaded, 400.00 MB buffer reserved, lowvram patches: 0
Requested to load WAN21
loaded partially; 3156.63 MB usable, 2678.59 MB loaded, 10949.31 MB offloaded, 472.59 MB buffer reserved, lowvram patches: 730
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:20<00:00, 28.02s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = False
Requested to load WAN21
loaded partially; 3206.64 MB usable, 2721.10 MB loaded, 10906.80 MB offloaded, 472.58 MB buffer reserved, lowvram patches: 730
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = True
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:10<00:00, 26.11s/it]
Patching torch settings: torch.backends.cuda.matmul.allow_fp16_accumulation = False
Requested to load WanVAE
loaded completely; 6063.82 MB usable, 242.03 MB loaded, full load: True
Prompt executed in 309.00 seconds
```

![Image](https://github.com/user-attachments/assets/2cc055a1-4225-4e18-859e-627afadcd683)
![Image](https://github.com/user-attachments/assets/61c0aca4-8a31-4e97-b86c-047e34dd8837)

**Comment by rattus128** [comment]
@bandifiu do you have a sense of where the rerun is slower? You still have a lot of committed memory in dynamic mode which shouldn't happen on that level for a vanilla WAN FP8.

A terminal and task manager side by side video recording would be amazing if you up for it as we want to track down performance regressions. Looking at your logs the RAM task manager page the important one.

Can I get your workflow too?

**Comment by trevormyers** [comment]
> [@trevormyers](https://github.com/trevormyers) can you confirm your version of comfy-aimdo in pip?
> 
> ```
> pip show comfy-aimdo
> ```
> 
> Your logs are missing some expected startup messages from this component. There is an issue where the aimdo messages dont appear in the browser terminal.
> 
> Did you paste from the in-browser console or from the launch terminal?
> 
> If aimdo is up to date and you still have problems, can you re-paste the startup log from the terminal directly (not browser console). You dont need to repro the crash, we can just debug your startup messages.
> 
> If the issue persist after those steps and your logs are the same, we can debug further why your aimdo isn't probing correctly.
> 
> Aimdo is the low level backend to the dynamic VRAM engine

```
C:\Users\meanm>pip show comfy-aimdo
Name: comfy-aimdo
Version: 0.2.8
Summary: AI Model Dynamic Offloader for ComfyUI
Home-page:
Author: rattus
Author-email:
License:
Location: C:\Users\meanm\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires:
Required-by:
```

i'll run a comparison of runtimes for one of my usual workflows here in a little while. one with dynamic vram disabled, and one with it enabled. i did not exactly compare them, but i feel like maybe my prompts were executing more quickly with it enabled. hope this info helps.

(edit: just did a basic workflow with no custom nodes. nothing crazy. sdxl txt to img with 2 ksamplers and a latent upscale 1.5x. ran 10 batches each, for disabled and enabled dynamic vram. average prompt execution for enabled was 29.69 seconds. average prompt execution for disabled was 31.246 seconds. i know its a small sample size, but that's roughly 5% increase in speed. i just wish it didnt randomly run into cuda errors with it enabled.)

here's a direct copy from terminal of my startup without disabling dynamic vram. i do see the aimdo messages now:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS D:\ComfyUI> py main.py
Adding extra search path checkpoints D:\stable-diffusion-webui\models\Stable-diffusion
Adding extra search path configs D:\stable-diffusion-webui\models\Stable-diffusion
Adding extra search path vae D:\stable-diffusion-webui\models\VAE
Adding extra search path loras D:\stable-diffusion-webui\models\Lora
Adding extra search path loras D:\stable-diffusion-webui\models\LyCORIS
Adding extra search path upscale_models D:\stable-diffusion-webui\models\ESRGAN
Adding extra search path upscale_models D:\stable-diffusion-webui\models\RealESRGAN
Adding extra search path upscale_models D:\stable-diffusion-webui\models\SwinIR
Adding extra search path embeddings D:\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks D:\stable-diffusion-webui\models\hypernetworks
Adding extra search path controlnet D:\stable-diffusion-webui\models\ControlNet
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2026-03-07 23:29:52.428
** Platform: Windows
** Python version: 3.13.11 (tags/v3.13.11:6278944, Dec  5 2025, 16:26:58) [MSC v.1944 64 bit (AMD64)]
** Python executable: C:\Users\meanm\AppData\Local\Programs\Python\Python313\python.exe
** ComfyUI Path: D:\ComfyUI
** ComfyUI Base Folder Path: D:\ComfyUI
** User directory: D:\ComfyUI\user
** ComfyUI-Manager config path: D:\ComfyUI\user\__manager\config.ini
** Log path: D:\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   3.7 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend cuda: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': "ImportError: No module named 'triton'", 'capabilities': []}
Checkpoint files will always be loaded safely.
Total VRAM 11264 MB, total RAM 65450 MB
pytorch version: 2.10.0.dev20251210+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 29452.0
working around nvidia conv3d memory bug.
Using pytorch attention
aimdo: src-win/cuda-detour.c:77:INFO:aimdo_setup_hooks: found driver at 00007FF856D60000, installing 4 hooks
aimdo: src-win/cuda-detour.c:61:DEBUG:install_hook_entrys: hooks successfully installed
aimdo: src/control.c:66:INFO:comfy-aimdo inited for GPU: NVIDIA GeForce RTX 2080 Ti (VRAM: 11263 MB)
DynamicVRAM support detected and enabled
Python version: 3.13.11 (tags/v3.13.11:6278944, Dec  5 2025, 16:26:58) [MSC v.1944 64 bit (AMD64)]
ComfyUI version: 0.16.3
ComfyUI frontend version: 1.39.19
[Prompt Server] web root: C:\Users\meanm\AppData\Local\Programs\Python\Python313\Lib\site-packages\comfyui_frontend_package\static
### Loading: ComfyUI-Impact-Pack (V8.28.2)
[Impact Pack] Wildcard total size (0.04 MB) is within cache limit (50.00 MB). Using full cache mode.
### Loading: ComfyUI-Impact-Subpack (V1.3.5)
[Impact Pack/Subpack] Using folder_paths to determine whitelist path: D:\ComfyUI\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Pack/Subpack] Ensured whitelist directory exists: D:\ComfyUI\user\default\ComfyUI-Impact-Subpack
[Impact Pack/Subpack] Loaded 0 model(s) from whitelist: D:\ComfyUI\user\default\ComfyUI-Impact-Subpack\model-whitelist.txt
[Impact Pack] Wildcards loading done.
[Impact Subpack] ultralytics_bbox: D:\ComfyUI\models\ultralytics\bbox
[Impact Subpack] ultralytics_segm: D:\ComfyUI\models\ultralytics\segm
### Loading: ComfyUI-Inspire-Pack (V1.23)
### Loading: ComfyUI-Manager (V3.39.2)
[ComfyUI-Manager] network_mode: public
[ComfyUI-Manager] ComfyUI per-queue preview override detected (PR #11261). Manager's preview method feature is disabled. Use ComfyUI's --preview-method CLI option or 'Settings > Execution > Live preview method'.
### ComfyUI Revision: 4863 [1c218282] *DETACHED | Released on '2026-03-05'
ComfyUI Path Helper Nodes: Loaded
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[D:\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[D:\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False
[D:\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'MIGraphXExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
USDU batch patches applied successfully.
USDU batch patches applied successfully.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
FETCH ComfyRegistry Data: 5/129
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: C:
                                               fmpein
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "Opportunities don't happen. You create them." - Chris Grosser


Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI\custom_nodes\lora-info
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Path-Helper
   0.0 seconds: D:\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\ComfyUI\custom_nodes\comfyui_ipadapter_plus
   0.0 seconds: D:\ComfyUI\custom_nodes\comfyui_ultimatesdupscale
   0.1 seconds: D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
   0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.6 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: D:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   3.3 seconds: D:\ComfyUI\custom_nodes\was-node-suite-comfyui

Context impl SQLiteImpl.
Will assume non-transactional DDL.
Assets scan(roots=['models']) completed in 0.066s (created=0, skipped_existing=179, orphans_pruned=0, total_seen=179)
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 10/129
FETCH ComfyRegistry Data: 15/129
FETCH ComfyRegistry Data: 20/129
FETCH ComfyRegistry Data: 25/129
FETCH ComfyRegistry Data: 30/129
```

**Comment by rattus128** [comment]
Thanks for the additional info @trevormyers . There is a feature I have been planning to do that will actually help you recover VAE ooms. Wasnt a bugfix but I might look at it immediately to try and handle your case as a bugfix instead.

**Comment by rattus128** [comment]
btw @trevormyers it looks like the VAE tiler fallback is failing for you in dynamic mode. You might generally get a better experience with your own custom tiler regardless of dynamic or not. Try setting up a 2x2 tile with an appropriate overlap with the tiling VAE decode.

**Comment by bandifiu** [comment]
I'm using custom workflow not the base one. [wan22_i2v_custom.json](https://github.com/user-attachments/files/25825185/wan22_i2v_custom.json)
Same workflow but I added dev-utils node and all subgraphs expanded [wan22_i2v_custom_dev.json](https://github.com/user-attachments/files/25825221/wan22_i2v_custom_dev.json) (for some reason almost half the size)
I tried a basic example workflow, it behaves the same.

2 runs with disabled dynamic vram

<img width="763" height="605" alt="Image" src="https://github.com/user-attachments/assets/8ff2d6e0-63fd-423c-9557-db00f7901afc" />

With dynamic vram enabled:

The samplers run longer, also the speed reported in the console are the same 28-30s/it for every runs. 
The text encode time seems to keep increasing.
Clear Cache node runs longer, that is basically 
```
comfy.model_management.unload_all_models()
gc.collect()   
```

<img width="616" height="512" alt="Image" src="https://github.com/user-attachments/assets/bb7d17f2-4285-4d7a-a454-4392f913beb3" />

<img width="697" height="563" alt="Image" src="https://github.com/user-attachments/assets/eee5ae02-e910-405c-8964-b15712a18a32" />

**Comment by rattus128** [comment]
> I'm using custom workflow not the base one. [wan22_i2v_custom.json](https://github.com/user-attachments/files/25825185/wan22_i2v_custom.json) Same workflow but I added dev-utils node and all subgraphs expanded [wan22_i2v_custom_dev.json](https://github.com/user-attachments/files/25825221/wan22_i2v_custom_dev.json) (for some reason almost half the size) I tried a basic example workflow, it behaves the same.
> 
> 2 runs with disabled dynamic vram
> <img alt="Image" width="763" height="605" src="https://private-user-images.githubusercontent.com/95913570/559931728-8ff2d6e0-63fd-423c-9557-db00f7901afc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzI5OTY1MDMsIm5iZiI6MTc3Mjk5NjIwMywicGF0aCI6Ii85NTkxMzU3MC81NTk5MzE3MjgtOGZmMmQ2ZTAtNjNmZC00MjNjLTk1NTctZGIwMGY3OTAxYWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzA4VDE4NTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDhjN2QwOThjZjZjYTA5MmE1NjdhMzFlYzJkNWMzYjk3NDY2OGI1YjI2YzFhNjExMDc1MzlmOGQ3NjcxYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PQZzjt7ze9IneOcyD6J7khm_yHWKYVvRm7rwIJtmM0c">
> 
> With dynamic vram enabled:
> 
> The samplers run longer, also the speed reported in the console are the same 28-30s/it for every runs. The text encode time seems to keep increasing. Clear Cache node runs longer, that is basically
> 
> ```
> comfy.model_management.unload_all_models()
> gc.collect()   
> ```
> 
> <img alt="Image" width="616" height="512" src="https://private-user-images.githubusercontent.com/95913570/559931758-bb7d17f2-4285-4d7a-a454-4392f913beb3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzI5OTY1MDMsIm5iZiI6MTc3Mjk5NjIwMywicGF0aCI6Ii85NTkxMzU3MC81NTk5MzE3NTgtYmI3ZDE3ZjItNDI4NS00ZDdhLWE0NTQtNDM5MmY5MTNiZWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzA4VDE4NTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNzViZmI0M2QwYTU1ZTk2YTYzMjg0NTE2ZGM4YjhhNTY1MWI0MGFjYzU2NDBmMjg1MjIyMTZhMjgwYmJjMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.axlJh-jCKO24_82pq5O45pDubS_O9vMHvriJPUkgm2A"> <img alt="Image" width="697" height="563" src="https://private-user-images.githubusercontent.com/95913570/559931762-eee5ae02-e910-405c-8964-b15712a18a32.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzI5OTY1MDMsIm5iZiI6MTc3Mjk5NjIwMywicGF0aCI6Ii85NTkxMzU3MC81NTk5MzE3NjItZWVlNWFlMDItZTkxMC00MDVjLTg5NjQtYjE1NzEyYTE4YTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzA4VDE4NTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYzAzZTI4NTY0YzQ1MmM0ODA0ZWUxYzFlODRmNDRkNjIxNDZkOTIyODhlZjgwNTU0NjgxY2EyNmIxOWIyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NyB8_vk3bWbMliSKXHTDIlQWLqcV3SFflnVAbQTlti4">

Thanks for this data. I think i see the issue and i'm working on the fix. Its an already planned enhancement to reduce RAM thrash.

Your actually at a pretty interesting performance point. Im very curious what happens for you with --disable-pinned-memory FWIW. Its not a long term fix, but it will slash your committed RAM consumption and with WAN you can often async offload getting away with no pinning. I'm working on a system to get the best of both worlds. Lower RAM thrash while pinning.

**Comment by bandifiu** [comment]
With --disable-pinned-memory RAM usage is lower and speed also better.
Using --disable-dynamic-vram makes no noticable difference with and without --disable-pinned-memory.
I also noticed my committed memory was already around 30G without ComfyUI.

<img width="703" height="539" alt="Image" src="https://github.com/user-attachments/assets/b6c738a1-4871-472b-adf8-f7b177ded83d" />

<img width="916" height="255" alt="Image" src="https://github.com/user-attachments/assets/8672b4ad-492b-4ab8-a486-5c5fbddae578" />

**Comment by trevormyers** [comment]
Whatever change was made recently seems to have resolved my problems. I no longer get the OOM error. Tested it a few times in a row now without running the argument to disable dynamic vram. No issues. I'm going to mark this one resolved. Thanks for all the work you put in @rattus128
