### ISSUE TITLE
New Memory Managment is a Disaster for me. OOM on my Lora Trainer WF where comfy 0.9.x still works

### ISSUE THREAD

**Issue by n0valis** [comfyanonymous/ComfyUI#13458]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

ComfyUi is runing in a WSL on my Windows System. I am running my own custom node, a Lora Training workflow with my own block swapping logic. This was for Flux.2 and it was a tight task getting this to work with a 5090 but it ran succsessfully on the older version of comfy. I updated a few days ago to 0.18.1 and since then the whole thing collapses at the beginning og the the blockswapping phase where comfy allocates pinned memory and before the actual training logic starts.  

Actually there is enough RAM left on the WSL side [DEBUG MEM] step=0:before_backward | rss=33.66GB vms=213.66GB ram_used=34.54GB/75.88GB | cuda_alloc=19.35GB cuda_reserved=26.11GB cuda_max_alloc=22.26GB cuda_max_reserved=26.11GB. On the Windows side it looks tighter but still ~5GB of RAM left. God knows why the pressure on Windows is more aggressive than on WSL. 

I tried disableing the new memory stuf but that didn't help either. 
--disable-async-offload
--disable-pinned-memory

I tried to debug the difference between old comfy and new comfy but I coud not pin it down. I made a script that simulated the workflow and bootstrapped comfy.memory_management and that went trough. So it must be somewhere in the depths of comfyui. I ran the complete training run on v0.9.x over 21 hours with no issue. On 0.18 it crashes everytime at the same position. The exception is a plain PyTorch device OOM raised inside loss.backward(). But enough VRAM and RAM is actually availbale imho.

### Logs

```powershell
[2026-04-17 22:44:34.540]                     INFO     [DEBUG MEM] step=0:before_backward | rss=33.66GB vms=213.66GB          flux2_train_comfy.py:98
                             ram_used=34.54GB/75.88GB | cuda_alloc=19.35GB cuda_reserved=26.11GB                           
                             cuda_max_alloc=22.26GB cuda_max_reserved=26.11GB                                              
[2026-04-17 22:44:34.562]                     INFO     DEBUG LAST PHASE: step=0:before_backward                             flux2_train_comfy.py:1492
[2026-04-17 22:44:34.564]                     INFO     [DEBUG MEM] training_loop_exception phase=step=0:before_backward |     flux2_train_comfy.py:98
                             rss=33.66GB vms=213.73GB ram_used=34.54GB/75.88GB | cuda_alloc=19.35GB                        
                             cuda_reserved=26.11GB cuda_max_alloc=22.26GB cuda_max_reserved=26.11GB                        
[2026-04-17 22:44:34.566]                     INFO     CRITICAL ERROR in training_loop: Allocation on device                flux2_train_comfy.py:1497
[2026-04-17 22:44:34.567]                     INFO     Initiating emergency cleanup...                                      flux2_train_comfy.py:1500
[2026-04-17 22:44:35.910] [04/17/26 22:44:35] INFO     Offloader cleaned up.                                                flux2_train_comfy.py:1506
[2026-04-17 22:44:35.910]                     INFO     Moving models to CPU...                                              flux2_train_comfy.py:1512
[2026-04-17 22:44:42.502] [04/17/26 22:44:42] INFO     GPU memory cache cleared.                                            flux2_train_comfy.py:1528
[2026-04-17 22:44:42.505] Traceback (most recent call last):
[2026-04-17 22:44:42.505]   File "/opt/ComfyUI/custom_nodes/Flux2-Trainer/flux2_train_comfy.py", line 1369, in training_loop
    self.accelerator.backward(loss)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
[2026-04-17 22:44:42.506]   File "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/accelerate/accelerator.py", line 2740, in backward
    loss.backward(**kwargs)
    ~~~~~~~~~~~~~^^^^^^^^^^
[2026-04-17 22:44:42.506]   File "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/torch/_tensor.py", line 625, in backward
    torch.autograd.backward(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self, gradient, retain_graph, create_graph, inputs=inputs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
[2026-04-17 22:44:42.506]   File "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/torch/autograd/__init__.py", line 354, in backward
    _engine_run_backward(
    ~~~~~~~~~~~~~~~~~~~~^
        tensors,
        ^^^^^^^^
    ...<5 lines>...
        accumulate_grad=True,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
[2026-04-17 22:44:42.506]   File "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/torch/autograd/graph.py", line 841, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        t_outputs, *args, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )  # Calls into the C++ engine to run the backward pass
    ^
[2026-04-17 22:44:42.506] torch.OutOfMemoryError: Allocation on device 
[2026-04-17 22:44:42.506] [2026-04-17 22:44:42.508]                     INFO     [WORKFLOW DEBUG] train_loop:training_loop_exception break_at=1000 |          nodes_flux2.py:60
                             rss=50.12GB | vms=230.31GB | ram_used=50.70GB/75.88GB | ram_avail=25.19GB |                   
                             cuda_alloc=2.60GB | cuda_reserved=4.26GB | cuda_max_alloc=22.26GB |                           
                             cuda_max_reserved=26.11GB | global_step=0 | epoch=1 | has_comfy_pbar=True                     
[2026-04-17 22:44:42.509]                     ERROR    !!! Exception during processing !!! Allocation on device                      execution.py:621
[2026-04-17 22:44:42.515]                     ERROR    Traceback (most recent call last):                                            execution.py:622
                               File "/opt/ComfyUI/execution.py", line 534, in execute                                      
                                 output_data, output_ui, has_subgraph, has_pending_tasks = await                           
                             get_output_data(prompt_id, unique_id, obj, input_data_all,                                    
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb,                         
                             v3_data=v3_data)                                                                              
                                                                                           ^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   
                               File "/opt/ComfyUI/execution.py", line 334, in get_output_data                              
                                 return_values = await _async_map_node_over_list(prompt_id, unique_id,                     
                             obj, input_data_all, obj.FUNCTION, allow_interrupt=True,                                      
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb,                         
                             v3_data=v3_data)                                                                              
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
                               File "/opt/ComfyUI/execution.py", line 308, in _async_map_node_over_list                    
                                 await process_inputs(input_dict, i)                                                       
                               File "/opt/ComfyUI/execution.py", line 296, in process_inputs                               
                                 result = f(**inputs)                                                                      
                               File "/opt/ComfyUI/custom_nodes/Flux2-Trainer/nodes_flux2.py", line 719, in                 
                             train                                                                                         
                                 steps_done = training_loop(                                                               
                                     break_at_steps=break_at,                                                              
                                     epoch=network_trainer_obj.current_epoch.value,                                        
                                 )                                                                                         
                               File "/opt/ComfyUI/custom_nodes/Flux2-Trainer/flux2_train_comfy.py", line                   
                             1531, in training_loop                                                                        
                                 raise e                                                                                   
                               File "/opt/ComfyUI/custom_nodes/Flux2-Trainer/flux2_train_comfy.py", line                   
                             1369, in training_loop                                                                        
                                 self.accelerator.backward(loss)                                                           
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^                                                           
                               File                                                                                        
                             "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/accelerate/accel                 
                             erator.py", line 2740, in backward                                                            
                                 loss.backward(**kwargs)                                                                   
                                 ~~~~~~~~~~~~~^^^^^^^^^^                                                                   
                               File                                                                                        
                             "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/torch/_tensor.py                 
                             ", line 625, in backward                                                                      
                                 torch.autograd.backward(                                                                  
                                 ~~~~~~~~~~~~~~~~~~~~~~~^                                                                  
                                     self, gradient, retain_graph, create_graph, inputs=inputs                             
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                             
                                 )                                                                                         
                                 ^                                                                                         
                               File                                                                                        
                             "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/torch/autograd/_                 
                             _init__.py", line 354, in backward                                                            
                                 _engine_run_backward(                                                                     
                                 ~~~~~~~~~~~~~~~~~~~~^                                                                     
                                     tensors,                                                                              
                                     ^^^^^^^^                                                                              
                                 ...<5 lines>...                                                                           
                                     accumulate_grad=True,                                                                 
                                     ^^^^^^^^^^^^^^^^^^^^^                                                                 
                                 )                                                                                         
                                 ^                                                                                         
                               File                                                                                        
                             "/home/comfy/.conda/envs/cenv13/lib/python3.13/site-packages/torch/autograd/g                 
                             raph.py", line 841, in _engine_run_backward                                                   
                                 return Variable._execution_engine.run_backward(  # Calls into the C++                     
                             engine to run the backward pass                                                               
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                  
                                     t_outputs, *args, **kwargs                                                            
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                            
                                 )  # Calls into the C++ engine to run the backward pass                                   
                                 ^                                                                                         
                             torch.OutOfMemoryError: Allocation on device                                                  
                                                                                                                           
[2026-04-17 22:44:42.518]                     INFO     Memory summary:                                                               execution.py:627
                             |===========================================================================|                 
                             |                  PyTorch CUDA memory summary, device ID 0                 |                 
                             |---------------------------------------------------------------------------|                 
                             |            CUDA OOMs: 0            |        cudaMalloc retries: 0         |                 
                             |===========================================================================|                 
                             |        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |                 
                             |---------------------------------------------------------------------------|                 
                             | Allocated memory      |   2484 MiB |  21227 MiB |      0 B   |      0 B   |                 
                             |       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |                 
                             |       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |                 
                             |---------------------------------------------------------------------------|                 
                             | Active memory         |   2484 MiB |  21227 MiB |      0 B   |      0 B   |                 
                             |       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |                 
                             |       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |                 
                             |---------------------------------------------------------------------------|                 
                             | Requested memory      |      0 B   |      0 B   |      0 B   |      0 B   |                 
                             |       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |                 
                             |       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |                 
                             |---------------------------------------------------------------------------|                 
                             | GPU reserved memory   |   4064 MiB |  24896 MiB |      0 B   |      0 B   |                 
                             |       from large pool |      0 MiB |      0 MiB |      0 B   |      0 B   |                 
                             |       from small pool |      0 MiB |      0 MiB |      0 B   |      0 B   |                 
                             |---------------------------------------------------------------------------|                 
                             | Non-releasable memory |      0 B   |      0 B   |      0 B   |      0 B   |                 
                             |       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |                 
                             |       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |                 
                             |---------------------------------------------------------------------------|                 
                             | Allocations           |       0    |       0    |       0    |       0    |                 
                             |       from large pool |       0    |       0    |       0    |       0    |                 
                             |       from small pool |       0    |       0    |       0    |       0    |                 
                             |---------------------------------------------------------------------------|                 
                             | Active allocs         |       0    |       0    |       0    |       0    |                 
                             |       from large pool |       0    |       0    |       0    |       0    |                 
                             |       from small pool |       0    |       0    |       0    |       0    |                 
                             |---------------------------------------------------------------------------|                 
                             | GPU reserved segments |       0    |       0    |       0    |       0    |                 
                             |       from large pool |       0    |       0    |       0    |       0    |                 
                             |       from small pool |       0    |       0    |       0    |       0    |                 
                             |---------------------------------------------------------------------------|                 
                             | Non-releasable allocs |       0    |       0    |       0    |       0    |                 
                             |       from large pool |       0    |       0    |       0    |       0    |                 
                             |       from small pool |       0    |       0    |       0    |       0    |                 
                             |---------------------------------------------------------------------------|                 
                             | Oversize allocations  |       0    |       0    |       0    |       0    |                 
                             |---------------------------------------------------------------------------|                 
                             | Oversize GPU segments |       0    |       0    |       0    |       0    |                 
                             |===========================================================================|                 
                                                                                                                           
[2026-04-17 22:44:42.519]                     ERROR    Got an OOM, unloading all loaded models.                                      execution.py:628
```

**Comment by n0valis** [comment]
I checked v0.15.1 and this also does the job. 
Then 0.16.4 and that crashed.
So the desastrous hack must have happened somewhere inbetween.

**Comment by n0valis** [comment]
So now I found that --disable-dynamic-vram solves the problem for versions > 0.15.1
Maybe someone can explain what is going on here.

**Comment by Inorien** [comment]
my guess is that theres not clean handling of stuff being dynamically offloaded from vram and other code attempting to access data that was offloaded. i get OOM and access violation a lot since this dynamic vram thing. while it has enabled some workflows, it has utterly destroyed others.

**Comment by GeekyGhost** [comment]
When I was building the backend for the LTX Desktop app, specifically the Phase 1 model patcher, we ran into a similar wall. Generating high-resolution video requires massive, multi-step tensor operations. If left unchecked, the pipeline would suffer a "slow death" by fragmentation and eventually OOM, even on high-VRAM cards.

I resolved this by implementing a strict, aggressive memory management protocol across three specific areas of the codebase:

Inter-Step Forced Defragmentation (EnhancedDenoiser): Python's Garbage Collector (GC) is notoriously lazy. It leaves "dead" tensors hanging around in the cache. To fix this, I built an inter-step monitor. Between every denoising step, if the available VRAM dipped below a safe threshold, I forced the system to drop dead references and release the cache back to the allocator.

Aggressive Intermediate Cleanup (LTXPatchedAttention): Inside the patched attention mechanism, I didn't wait for Python to clean up massive intermediate tensors like q, k, v, and the temporal feta_score. The absolute millisecond an operation finished with a tensor, I used explicit del statements to destroy it. This tells the PyTorch memory allocator that the block is instantly available.

In-Place Operations (feta_utils.py): Rather than creating new tensors during mathematical operations (which fragments memory further), I used PyTorch's in-place operations (like .masked_fill_() and .div_()) to mutate existing tensors directly.

Why This Relates to Your ComfyUI Issue
Your custom Flux.2 training node is dying for the exact same reason, exacerbated by a recent architectural shift.

Starting in v0.18, ComfyUI introduced an aggressive dynamic VRAM offloader. This system constantly juggles tensors between your system RAM and the GPU to try and fit larger workflows. However, because you are running a custom node with your own block-swapping logic, your swapper and ComfyUI's dynamic offloader are fighting for control.

Because of Python's lazy GC, dead tensors from your forward pass or swap operations are hanging around. This chops your remaining 5GB of VRAM into hundreds of tiny, disconnected fragments. When loss.backward() fires, it demands a massive, contiguous chunk of VRAM to calculate the gradients. PyTorch looks at your highly fragmented cache, realizes it can't find a single unbroken block big enough, panics, and throws the OOM.

This is exactly why adding the --disable-dynamic-vram flag solves it: it stops ComfyUI from dynamically fragmenting the cache behind your custom node's back.

How to Resolve It Natively in ComfyUI
If you want your node to run natively on v0.18+ without forcing users to modify their launch arguments, you need to apply the LTX Desktop strategies directly to your flux2_train_comfy.py file.

**Comment by cdmusic2019** [comment]
From versions 0.18 to 0.19, I used it by adding the "Clean VRAM Used" node; the most stable version is 0.15.1.

**Comment by Inorien** [comment]
resolved my OOM and access violation issues by increasing Windows page file space from 4 GB (lmao) up to 32 GB. seems some CUDA stuff might rely on virtual memory specifically even when I have ~60 GB "free" RAM

**Comment by GeekyGhost** [comment]
> resolved my OOM and access violation issues by increasing Windows page file space from 4 GB (lmao) up to 32 GB. seems some CUDA stuff might rely on virtual memory specifically even when I have ~60 GB "free" RAM

yeah, that was my original solution, but it creeps like a memory leak for larger projects.

**Comment by n0valis** [comment]
This all happens before the first iteration is calculated. It really is not looking like are real OOM. As far as you can trust the Task Manager it shows ~8GB of RAM available. In WSL it is even more. VRAM is at this time even less allocated with ~10GB avail. So that is the part where I got lost. And I don't think I want to code against a leaky and obviously problematic implementation of an even more obviously undertested new feature in ComfyUI. 
Regarding the pagefile: Really 4GB? And you have set it to this value manually? I let windows decide the size and my pagfile is ~120GB. I am also seeing like many others constant swapping/pagefile access which is not really explainable by looking at resources being used. So the whole thing to me is spectecular bizarre and a typical case of wait and see. Strangely close to a game release from Paradox Entertainment.

**Comment by trevormyers** [comment]
I would like to point out that I still have to use --disable-dynamic-vram argument for a stable experience. I've tried running without args multiple times over the past month or so to no avail. Here's a link to the issue I created back in early March about the same thing.

[https://github.com/Comfy-Org/ComfyUI/issues/12823]

**Comment by Booyaka101** [comment]
@rattus128 — flagging this in case it's not on your radar alongside #12823.

@n0valis — since you're inside WSL but still need `--disable-dynamic-vram`, two pieces of data would help narrow this down:

1. **`uname -r`** — the auto-disable added in [`1080bd44`](https://github.com/comfyanonymous/ComfyUI/commit/1080bd44) detects WSL via `platform.uname().release.endswith(...)` matching `-Microsoft` or `microsoft-standard-WSL2` (see `is_wsl()` in `comfy/model_management.py`). If your kernel has a non-standard suffix (custom build, GPU-passthrough VM, trailing `+`, distro fork), the `endswith` check would miss your case and dynamic-VRAM would activate as if on bare Linux — which would explain why `--disable-dynamic-vram` is the only thing that helps.

2. **`pip show comfy-aimdo`** — version helps line up against the fixes shipped while debugging #12823.

**Comment by n0valis** [comment]
> [@rattus128](https://github.com/rattus128) — flagging this in case it's not on your radar alongside [#12823](https://github.com/Comfy-Org/ComfyUI/issues/12823).
> 
> [@n0valis](https://github.com/n0valis) — since you're inside WSL but still need `--disable-dynamic-vram`, two pieces of data would help narrow this down:
> 
>     1. **`uname -r`** — the auto-disable added in [`1080bd44`](https://github.com/comfyanonymous/ComfyUI/commit/1080bd44) detects WSL via `platform.uname().release.endswith(...)` matching `-Microsoft` or `microsoft-standard-WSL2` (see `is_wsl()` in `comfy/model_management.py`). If your kernel has a non-standard suffix (custom build, GPU-passthrough VM, trailing `+`, distro fork), the `endswith` check would miss your case and dynamic-VRAM would activate as if on bare Linux — which would explain why `--disable-dynamic-vram` is the only thing that helps.
> 
>     2. **`pip show comfy-aimdo`** — version helps line up against the fixes shipped while debugging [CUDA error OOM after updating to v0.16.3 #12823](https://github.com/Comfy-Org/ComfyUI/issues/12823).

I was indeed wondering and thus didn't consider disable vram earlier because I was aware of that wsl auto switch. And that obviously didn't work, or whatever.
```
❯ uname -r
6.6.87.2-microsoft-standard-WSL2
```
```
❯ pip show comfy-aimdo
Name: comfy-aimdo
Version: 0.2.12
Summary: AI Model Dynamic Offloader for ComfyUI
Author: rattus
```

**Comment by Booyaka101** [comment]
Apologies — my WSL-detection hypothesis was wrong. `6.6.87.2-microsoft-standard-WSL2` matches the second `endswith` in [`is_wsl()`](https://github.com/comfyanonymous/ComfyUI/blob/main/comfy/model_management.py#L178-L184), so `is_wsl()` returns `True` on your machine and the auto-disable path is being taken correctly.

Re-tracing the gating, there's an asymmetry that explains the symptom. Two separate `comfy-aimdo` calls happen in [`main.py`](https://github.com/comfyanonymous/ComfyUI/blob/main/main.py):

| line | call | gate |
|---|---|---|
| [44–45](https://github.com/comfyanonymous/ComfyUI/blob/main/main.py#L44-L45) | `comfy_aimdo.control.init()` — `ctypes.CDLL("aimdo.so", mode=258)` | `enables_dynamic_vram()` only |
| [218–235](https://github.com/comfyanonymous/ComfyUI/blob/main/main.py#L218-L235) | `comfy_aimdo.control.init_device(...)` + `aimdo_enabled = True` | `enables_dynamic_vram() and is_nvidia() and not is_wsl()` |

So on WSL, the `init_device` block is correctly skipped (`aimdo_enabled` stays `False`, and every `aimdo_enabled`-gated codepath in `ops.py`, `model_patcher.py`, `model_management.py`, `model_detection.py` and `utils.py` falls through to legacy behavior) — **but `aimdo.so` itself is still `dlopen`'d with `RTLD_NOW | RTLD_GLOBAL` (`mode=258`)**. Anything that library does on load (constructor-level CUDA hooks, allocator interposition via `RTLD_GLOBAL` symbol replacement, host-pinned-memory pre-registration) takes effect at that point regardless of whether `init_device` is ever called.

The only thing `--disable-dynamic-vram` changes for you is that `enables_dynamic_vram()` becomes `False`, which short-circuits line 45 and the `dlopen` never happens. That matches the observed behavior — `aimdo_enabled` is already `False` on WSL with or without the flag, so legacy ModelPatcher is in use either way; the only delta is the library load itself.

**Quick test that would confirm the diagnosis:** comment out line 45 in `main.py` (just the `comfy_aimdo.control.init()` call — leave the `import comfy_aimdo.control` on line 42 in place), restart, run your workflow without `--disable-dynamic-vram`. If the OOM goes away, the `dlopen` is the trigger.

@rattus128 — if this holds up, the line-45 gate likely needs the same `is_nvidia()` / `not is_wsl()` qualifiers as line 218, or `init()` could be deferred to immediately before `init_device()` so the existing WSL guard covers both.

**Comment by n0valis** [comment]
> **Quick test that would confirm the diagnosis:** comment out line 45 in `main.py` (just the `comfy_aimdo.control.init()` call — leave the `import comfy_aimdo.control` on line 42 in place), restart, run your workflow without `--disable-dynamic-vram`. If the OOM goes away, the `dlopen` is the trigger.

Yes I can confirm that.

**Comment by Booyaka101** [comment]
Thanks for running that, @n0valis — that's the empirical confirmation we needed that the `dlopen` on line 45 is the trigger.

The proposed fix is at #13818: it gates line 45 behind the same WSL guard that already protects the `init_device()` call at line 218, so on WSL the `dlopen` is skipped entirely. That matches what `--disable-dynamic-vram` achieves today, without requiring users to discover the workaround.

Branch is open and mergeable; happy to iterate on it if reviewers prefer a different shape.

**Comment by ailovertech** [comment]
same here, with rtx5080 and amd ryzen 9 ai 375hz, for video, the ui is totally unworkable now from some days
