### ISSUE TITLE
Updated my Nvidia driver. Now ComfyUI won't start.

### ISSUE THREAD

**Issue by alex-mitov** [comfyanonymous/ComfyUI#13798]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Hi,

I have just downloaded the latest ComfyUI portable (ComfyUI_v0.20.1_windows_portable_nvidia.7z) and then I downloaded the latest Nvidia Studio driver for my RTX 5090 and GTX 1080 Ti (596.36-desktop-win10-win11-64bit-international-nsd-dch-whql). Now neither the latest ComfyUI, nor older versions work. I get this error:

```
K:\ComfyUI_windows_portable_3>echo If you see this and ComfyUI did not start try updating your Nvidia Drivers to the latest. If you get a c10.dll error you need to install vc redist that you can find: https://aka.ms/vc14/vc_redist.x64.exe
If you see this and ComfyUI did not start try updating your Nvidia Drivers to the latest. If you get a c10.dll error you need to install vc redist that you can find: https://aka.ms/vc14/vc_redist.x64.exe
```

Any help is appreciated!

### Logs

```powershell
K:\ComfyUI_windows_portable_3>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
setup plugin alembic.autogenerate.schemas
setup plugin alembic.autogenerate.tables
setup plugin alembic.autogenerate.types
setup plugin alembic.autogenerate.constraints
setup plugin alembic.autogenerate.defaults
setup plugin alembic.autogenerate.comments
K:\ComfyUI_windows_portable_3\python_embeded\Lib\site-packages\torch\cuda\__init__.py:180: UserWarning: cudaGetDeviceCount() returned cudaErrorNotSupported, likely using older driver or on CPU machine (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAFunctions.cpp:88.)
  return torch._C._cuda_getDeviceCount() > 0
Found comfy_kitchen backend cuda: {'available': False, 'disabled': False, 'unavailable_reason': 'CUDA not available on this system', 'capabilities': []}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_mxfp8', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_mxfp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_mxfp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': "ImportError: No module named 'triton'", 'capabilities': []}
Checkpoint files will always be loaded safely.
Windows fatal exception: access violation

Stack (most recent call first):
  File "K:\ComfyUI_windows_portable_3\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 478 in _lazy_init
  File "K:\ComfyUI_windows_portable_3\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 1148 in current_device
  File "K:\ComfyUI_windows_portable_3\ComfyUI\comfy\model_management.py", line 204 in get_torch_device
  File "K:\ComfyUI_windows_portable_3\ComfyUI\comfy\model_management.py", line 254 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1023 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "K:\ComfyUI_windows_portable_3\ComfyUI\execution.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1023 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "K:\ComfyUI_windows_portable_3\ComfyUI\main.py", line 206 in <module>

K:\ComfyUI_windows_portable_3>echo If you see this and ComfyUI did not start try updating your Nvidia Drivers to the latest. If you get a c10.dll error you need to install vc redist that you can find: https://aka.ms/vc14/vc_redist.x64.exe
If you see this and ComfyUI did not start try updating your Nvidia Drivers to the latest. If you get a c10.dll error you need to install vc redist that you can find: https://aka.ms/vc14/vc_redist.x64.exe

K:\ComfyUI_windows_portable_3>pause
Press any key to continue . . .
```

**Comment by alex-mitov** [comment]
A quick update. It appears that after installing that driver, my 5090 is no longer being detected for some reason. I ran nvidia-smi and it looks like for some reason Windows has silently installed driver 560.94 after I installed the newest driver. Curiously, in my installed apps it says that I have 596.36.

**Comment by alex-mitov** [comment]
It turns out Nvidia has stopped providing support for GTX 1080 Ti in the last few drivers and this is why ComfyUI wouldn't start. Windows has been automatically installing lower driver version so that my 1080 Ti, which I use for display, would run but this made my 5090 not being detected because that driver was released before RTX 5090, hence the error in ComfyUI.

I have reverted to the last driver that supports both RTX 5090 and GTX 1080 Ti (driver 581.57 which is a few months old at this point), or buy a new GPU to replace my GTX 1080 Ti if I want to install new Nvidia drivers. I will close the issue now.
