### ISSUE TITLE
RTX 5090 (Blackwell) nvfp4 bypasses PyTorch allocator causing VAE decode OOM/slowdown on 32GB VRAM

### ISSUE THREAD

**Issue by yanceyknk** [comfyanonymous/ComfyUI#14157]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

VAE decode completes in ~10 seconds. Continuous batch processing runs stably without slowdown or OOM errors.

### Actual Behavior

On RTX 5090 (32GB), VAE decode intermittently takes 150-300 seconds or OOM occurs during diffusion sampling on the second consecutive run. After OOM, ComfyUI unloads all models and the next run succeeds normally.

Key observation in OOM memory summary:
- Allocated memory: 26972 MiB
- Tot Alloc: 0 B  ← PyTorch allocator sees nothing
- GPU reserved memory: 31584 MiB

nvfp4 native ops (enabled automatically on Blackwell/RTX 5090) allocate VRAM bypassing the PyTorch allocator. ComfyUI's memory management cannot see this memory, severely underestimates actual VRAM usage, and fails to trigger model offloading before VAE decode, leaving only 400-1100MB for VAE.

### Steps to Reproduce

1. RTX 5090 (32GB) on Windows
2. Load WAN 2.2 14B model with lightx2v 4-step LoRA (dual UNETLoader workflow)
3. Submit 2+ consecutive T2V generation tasks via API or queue
4. Observe: second run VAE decode becomes extremely slow or first run OOM

Note: Native ops log line will show "nvfp4" confirming the issue applies.

### Debug Logs

```powershell
Native ops: nvfp4, float8_e5m2, float8_e4m3fn , emulated ops: mxfp8
Requested to load WanVAE
loaded completely; 448 MB usable, 242.03 MB loaded, full load: True
[VAE decode takes 150+ seconds]

--- OOM case ---
torch.OutOfMemoryError: Allocation on device
Allocated memory: 26972 MiB | Tot Alloc: 0 B | Tot Freed: 0 B
GPU reserved memory: 31584 MiB
Got an OOM, unloading all loaded models.

--- Fix ---
Increasing EXTRA_RESERVED_VRAM in comfy/model_management.py for 16GB+ cards from +100MB to +4GB resolves the issue completely. 20+ consecutive runs stable at ~10s each.
```

**Comment by comfyanonymous** [comment]
1. Post your full ComfyUI logs.
2. Don't disable dynamic vram.

**Comment by yanceyknk** [comment]
I don't have --disable-smart-memory in my startup arguments.

My launch command is:
python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen 0.0.0.0 --port 8188 --max-upload-size 2048

The issue was resolved by increasing EXTRA_RESERVED_VRAM in comfy/model_management.py:

# Before
if total_vram > (15 * 1024):
    EXTRA_RESERVED_VRAM += 100 * 1024 * 1024

# After  
if total_vram > (15 * 1024):
    EXTRA_RESERVED_VRAM += 4 * 1024 * 1024 * 1024

After this change, 20+ consecutive runs are stable at ~10s each with no OOM or slow VAE decode.

It seems nvfp4 native ops on RTX 5090 allocate VRAM outside the PyTorch allocator (Tot Alloc: 0B in OOM summary), causing ComfyUI to underestimate actual VRAM usage and not aggressively enough trigger model offloading.

**Comment by rattus128** [comment]
This line means dynamic vram is disabled:

```
loaded completely; 448 MB usable, 242.03 MB loaded, full load: True
```

Probably by a custom model loader node.

**Comment by yanceyknk** [comment]
Dynamic vram is not disabled in my config. The issue is that nvfp4 native ops on RTX 5090 allocate VRAM outside the PyTorch allocator (Tot Alloc: 0B in OOM summary), so get_free_memory() returns incorrect values and dynamic vram never triggers. Increasing EXTRA_RESERVED_VRAM forces more aggressive offloading and resolves the issue.

**Comment by rattus128** [comment]
> Dynamic vram is not disabled in my config. The issue is that nvfp4 native ops on RTX 5090 allocate VRAM outside the PyTorch allocator (Tot Alloc: 0B in OOM summary), so get_free_memory() returns incorrect values and dynamic vram never triggers. Increasing EXTRA_RESERVED_VRAM forces more aggressive offloading and resolves the issue.

We can see from your log though, that at least your VAE is loaded with dynamic vram disabled. We need to fix that first as we cant fix dynamic VRAM if its not being activated.

```
loaded completely ...
```

^^ this is not dynamic VRAM mode.

We need your complete log to help and maybe figure out whats happening.

In dynamic VRAM, EXTRA_RESERVED_VRAM is completely ignored.

**Comment by Alan5168** [comment]
**Data point that may help narrow this down: same Blackwell nvfp4-native class of workload, zero repro on RTX 5070 Ti (16GB).**

Environment: RTX 5070 Ti (SM12.0/Blackwell, 16GB), Windows, torch 2.11.0+cu130, comfy-kitchen 0.2.16, ComfyUI master @ `51bf508` (2026-07-07).

Model: [`InsecureErasure/Wan2.2-I2V-A14B-Moe-Distill-Lightx2v-NVFP4`](https://huggingface.co/InsecureErasure/Wan2.2-I2V-A14B-Moe-Distill-Lightx2v-NVFP4) (dual MoE experts, ~9.3GB each, native nvfp4 compute confirmed active).

Test: 4 consecutive 640×640×81-frame I2V generations back-to-back, no restart. Result: zero VAE decode OOM, zero slowdown on any run — run 2+ was actually *faster* than the cold run (60.5s vs 80.6s), suggesting caches/workspaces warming up rather than degrading.

This is the same GPU architecture generation and native-nvfp4 code path as the reported failure, stress-tested with more consecutive runs than the 2-run repro here, and it doesn't reproduce. A few things that differ and might matter for isolating the cause:

- Card VRAM: 16GB here vs 32GB on the reporting RTX 5090 — counterintuitively the *smaller* card is fine, which argues against a simple "not enough headroom" story and might point at something proportional to total VRAM, or specific to that configuration.
- Workflow: a clean dual-expert NVFP4 checkpoint I2V here vs T2V with a separate lightx2v LoRA applied via dual UNETLoader in the report — LoRA patching interacting with the offload-cost accounting (cf. #11171's dequant-offload-cost fix) seems worth checking as a variable.
- Versions here postdate the original report by ~5-6 weeks, though I couldn't find any merged commit in between that touches `EXTRA_RESERVED_VRAM`, `get_free_memory()`, or comfy-kitchen's cublas/nvfp4 workspace handling — so I don't think this was silently fixed; more likely it's config/workload-dependent.

I also dug through comfy-kitchen's CUDA backend looking for an untracked persistent allocation that could explain a multi-GB shortfall: the nvfp4 gemm path does hold one process-lifetime global cublas workspace per device (`torch.empty()`, never registered with ComfyUI's model memory accounting), but it's capped at 32MB on Blackwell/Hopper — too small to be the culprit on its own. So no root cause to offer, just a contrasting data point in case it helps narrow where to look (e.g. whether it's LoRA-application-specific, or specific to how a 32GB card's larger absolute headroom interacts with the fixed `EXTRA_RESERVED_VRAM` margin).
