### ISSUE TITLE
RuntimeError: CUDA error: operation not supported

### ISSUE THREAD

**Issue by v4r4rth** [comfyanonymous/ComfyUI#1845]
I am unable to get ComfyUI running on my GPU - it has 16GB VRAM and I am getting the following error:

C:\ComfyUI>python main.py
Traceback (most recent call last):
  File "C:\ComfyUI\main.py", line 74, in <module>
    import execution
  File "C:\ComfyUI\execution.py", line 12, in <module>
    import nodes
  File "C:\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "C:\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\ComfyUI\comfy\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\comfy\model_management.py", line 105, in get_total_memory
    _, mem_total_cuda = torch.cuda.mem_get_info(dev)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\cuda\memory.py", line 663, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Any assistance? I tried changing the torch and cuda versions, reverted the changes and still not able to get it running...

**Comment by NeedsMoar** [comment]
Which GPU is it?

**Comment by v4r4rth** [comment]
It is an A40 GPU, 16GB Slice - I solved the issue by adding --disable-cudamalloc to the commandline arguments, working perfectly now!

**Comment by XReyRobert** [comment]
had to do the same on a P6000, thanks

**Comment by jackyin68** [comment]
But this parameter is not supported now. How to deal with this problem？ 
 main.py [-h] [--listen [IP]] [--port PORT] [--enable-cors-header [ORIGIN]] [--max-upload-size MAX_UPLOAD_SIZE] [--extra-model-paths-config PATH [PATH ...]] [--output-directory OUTPUT_DIRECTORY]
               [--temp-directory TEMP_DIRECTORY] [--input-directory INPUT_DIRECTORY] [--auto-launch] [--disable-auto-launch] [--cuda-device DEVICE_ID] [--cuda-malloc | --disable-cuda-malloc] [--dont-upcast-attention]
               [--force-fp32 | --force-fp16] [--bf16-unet | --fp16-unet | --fp8_e4m3fn-unet | --fp8_e5m2-unet] [--fp16-vae | --fp32-vae | --bf16-vae]
               [--fp8_e4m3fn-text-enc | --fp8_e5m2-text-enc | --fp16-text-enc | --fp32-text-enc] [--directml [DIRECTML_DEVICE]] [--disable-ipex-optimize] [--preview-method [none,auto,latent2rgb,taesd]]
               [--use-split-cross-attention | --use-quad-cross-attention | --use-pytorch-cross-attention] [--disable-xformers] [--gpu-only | --highvram | --normalvram | --lowvram | --novram | --cpu] [--disable-smart-memory]     
               [--deterministic] [--dont-print-server] [--quick-test-for-ci] [--windows-standalone-build] [--disable-metadata]
main.py: error: unrecognized arguments: --disable-cudamalloc

**Comment by v4r4rth** [comment]
> But this parameter is not supported now. How to deal with this problem？ 
>>main.py [-h] [--listen [IP]] [--port PORT] [--enable-cors-header [ORIGIN]] [--max-upload-size MAX_UPLOAD_SIZE] [--extra-model-paths-config PATH [PATH ...]] [--output-directory OUTPUT_DIRECTORY] [--temp-directory TEMP_DIRECTORY] [--input-directory INPUT_DIRECTORY] [--auto-launch] [--disable-auto-launch] [--cuda-device DEVICE_ID] **[--cuda-malloc | --disable-cuda-malloc]** [--dont-upcast-attention] [--force-fp32 | --force-fp16] [--bf16-unet | --fp16-unet | --fp8_e4m3fn-unet | --fp8_e5m2-unet] [--fp16-vae | --fp32-vae | --bf16-vae] [--fp8_e4m3fn-text-enc | --fp8_e5m2-text-enc | --fp16-text-enc | --fp32-text-enc] [--directml [DIRECTML_DEVICE]] [--disable-ipex-optimize] [--preview-method [none,auto,latent2rgb,taesd]] [--use-split-cross-attention | --use-quad-cross-attention | --use-pytorch-cross-attention] [--disable-xformers] [--gpu-only | --highvram | --normalvram | --lowvram | --novram | --cpu] [--disable-smart-memory] [--deterministic] [--dont-print-server] [--quick-test-for-ci] [--windows-standalone-build] [--disable-metadata] **main.py: error: unrecognized arguments: --disable-cudamalloc**

You have a typo:
--disable-cuda-malloc instead of disable-cudamalloc

**Comment by jackyin68** [comment]
Fine, many thanks to you!

**Comment by denyshubh** [comment]
After changing my .\run_nvidia_gpu.bat to fixed my issue
```bash
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-cuda-malloc
pause
```

**Comment by luojin** [comment]
thx

**Comment by AdamaISgood** [comment]
> After changing my .\run_nvidia_gpu.bat to below code fixed my issue.
> 
> ```shell
> .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-cuda-malloc
> pause
> ```

Newbie here
Please, where should I change that?

**Comment by Dayuppy** [comment]
> > After changing my .\run_nvidia_gpu.bat to below code fixed my issue.
> > ```shell
> > .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-cuda-malloc
> > pause
> > ```
> 
> Newbie here Please, where should I change that?

Go to where ComfyUI is installed. Find run_nvidia_gpu.bat. Right-click and edit. Change it. Re-save. Re-launch.

**Comment by AdamaISgood** [comment]
> > > After changing my .\run_nvidia_gpu.bat to below code fixed my issue.
> > > ```shell
> > > .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-cuda-malloc
> > > pause
> > > ```
> > 
> > 
> > Newbie here Please, where should I change that?
> 
> Go to where ComfyUI is installed. Find run_nvidia_gpu.bat. Right-click and edit. Change it. Re-save. Re-launch.

I installed the local version, not the portable one (had issues with it). So I don't have that ...

**Comment by tzhnihao** [comment]
> > > > After changing my .\run_nvidia_gpu.bat to below code fixed my run_nvidia_gpu.bat issue.
> > > > .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-cuda-malloc
> > > > pause
> > > 
> > > 
> > > Newbie here Please, where should I change that?
> > 
> > 
> > Go to where ComfyUI is installed. Find run_nvidia_gpu.bat. Right-click and edit. Change it. Re-save. Go to the installation location of ComfyUI. Find run_nvidia_gpu.bat. Right-click and edit. Change it. Re-save. Reboot.
> 
> I installed the local version, not the portable one (had issues with it). So I don't have that ... I installed the local version, not the portable version (with issues). So I don't have that......

You can find it by searching for that file name in your local comfyui
