### ISSUE TITLE
ERROR "Torch not compiled with CUDA enabled" also AFTER REINSTALLING TORCH

### ISSUE THREAD

**Issue by makeoo1** [comfyanonymous/ComfyUI#1887]
never had a problem before then I installed a custom node that caused comfyUI to stop working. I removed the node from the folder but still didn't work. I reinstalled the comfyUI folder but i get this error also after following the steps in the installation guide. I tired to reinstall torch few times but i always get this error

![image](https://github.com/comfyanonymous/ComfyUI/assets/113861865/77a723ff-4b01-48bd-9c95-c739fca17b22)

**Comment by NeedsMoar** [comment]
What's the output of "pip list -v"?  If the packages are somewhere other than appdata\local you're probably installing to another python.
What command are you using to install torch?  It's best to install with 

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
or whatever current command https://pytorch.org/get-started/locally/ lists 

Follow the instructions at https://pytorch.org/get-started/locally/#windows-verification afterwards and see if you can 

If torch_directml got installed somehow you probably need to remove that first too.

**Comment by makeoo1** [comment]
sorry for the late answer:

-I used the command that is given in the installation section and follow it step by step. 
Right now i have installed torch with cu181 because for some reason also my A1111 was giving me problems and it was slower then usual ( i normally got around 29 it/s ). 

-how can i remove torch_directml?

-attached is my -v list.

thx for the help!

[pip list -v.txt](https://github.com/comfyanonymous/ComfyUI/files/13261100/pip.list.-v.txt)

**Comment by makeoo1** [comment]
UPDATE:

i made it work by following your steps, downgrading protobuf, unistalling x formers from the directory and looking around online.

But now i am getting this error which i am not sure what does it even mean;
![image](https://github.com/comfyanonymous/ComfyUI/assets/113861865/280879e1-c1d8-4e51-a556-c4536758825a)


Thx again

**Comment by NeedsMoar** [comment]
Glad stuff is working.  :-)  I don't know why torch is such a pain sometimes but that command above will always do it for me.  

The tensorflow error appears to be because it's built against an outdated CUDA version, so I'd just reinstall tensorflow against the same runtime you used for torch.  I don't think many nodes actually use it for anything but might as well fix it.  

You can install an xformers + flash-attention2 windows version that works with PyTorch 2.1.0 and CUDA 12.1 if you want from https://github.com/bdashore3/flash-attention/releases/download/2.3.2/flash_attn-2.3.2-cp310-cp310-win_amd64.whl (then pip install the wheel when it's done downloading) and pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121
I found that it speeds things up by a lot on larger image generations vs the pytorch2 attention (and helps smaller sizes too, just nothing spectacular vs pytorch2) so you might want to install it but it isn't required.  Now that flash attention 2 is building correctly on windows again the xformers builds might include it already, I'm not entirely sure since it's a different module.   I'd just install flash attention first then do xformers.  I did similar but xformers didn't have a wheel built against any of the newer versions yet so that's built from source on my machine.

The socket error is something I've been hitting a lot since Saturday, mainly when I update all nodes with ComfyUI-Manager;  there's a bug happening in some node that calls the local websockets interacting with web browsers which it attempts to redirect to different security settings, I'm still clueless on how to fix that one.  It usually doesn't cause further issues unless you access something that tries to open an internet connection, then the whole cmd window will freeze.  Full debug web server output didn't give me anything useful about what was causing it except a 101 response when a local ws:// URL was accessed.

**Comment by makeoo1** [comment]
Many thanks for everything and the explanation! 

I will do as soon as i can and report here any updates (in case you wanna keep the issue open) 

Have a good one :D

**Comment by NeedsMoar** [comment]
ah installing wheels is a different command.    It's trying to do the build, you want:

pip install flash_attn-2.3.2-cp310-cp310-win_amd64.whl 

in the directory you saved the download

**Comment by NeedsMoar** [comment]
The error you got is because you don't have the CUDA developer's toolkit installed (nvcc is from that) which also needs at least the visual studio community tools installed.   You shouldn't need it unless you're really dead set on building something from scratch.

**Comment by makeoo1** [comment]
UPDATE:

sorry for the confusion, the error i just mentioned i don't think it's related with what we were talking about. 

I fixed the sampler error by downgrading to the version of the day I installed comfyui (ee74ef5). 

It seems that the images generation was indeed speed up! But i am not sure about what's happening with the Ksampler

**Comment by pikar0** [comment]
@makeoo1 do you fix the problem? I have the same problem... :S

**Comment by makeoo1** [comment]
> @makeoo1 do you fix the problem? I have the same problem... :S

nope ... :/

**Comment by pikar0** [comment]
> > @makeoo1 do you fix the problem? I have the same problem... :S
> 
> nope ... :/

Finally i started the program... 

I repeat all installation steps from "Anaconda" instead the "Windows Power Shell". And later i started the script with the command from Anaconda too.

Now the script start fine for me

**Comment by smthemex** [comment]
For this issue, I choose to delete the entire directory of "python_embeded" and then copy a  new one from the consolidation package. Silly but fast...Of course, some node environments still need to be reinstalled, but at least there won't be any more errors
