### ISSUE TITLE
Rebatch latent usage issues

### ISSUE THREAD

**Issue by omanhom** [comfyanonymous/ComfyUI#1957]
I used comfyui to redraw hundreds of pictures, using two loras and two controlnets (using openpose and lineart models). Unfortunately, the graphics card memory OOM (torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory . (out of memory)), and then I found a way to use Rebatch Latent (batch_size is set to 1) to redraw one by one like sd without reporting insufficient video memory. I was happy that this solved the problem. Later I discovered that all the redrawn pictures had the same posture. I was a little confused. Did I use it wrong? The following is my workflow chart:
![Snipaste_2023-11-13_13-26-02](https://github.com/comfyanonymous/ComfyUI/assets/13151762/ad0a2965-af31-4876-9bdf-c416e3bb9313)

**Comment by ltdrdata** [comment]
> I used comfyui to redraw hundreds of pictures, using two loras and two controlnets (using openpose and lineart models). Unfortunately, the graphics card memory OOM (torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory . (out of memory)), and then I found a way to use Rebatch Latent (batch_size is set to 1) to redraw one by one like sd without reporting OOM. I was happy that this solved the problem. Later I discovered that all the redrawn pictures had the same posture. I was a little confused. Did I use it wrong? The following is my workflow chart:

You need to change `seed` for each item of list.

**Comment by omanhom** [comment]
How to implement it, or are there currently implemented nodes available?

**Comment by ltdrdata** [comment]
![ListCounter](https://github.com/comfyanonymous/ComfyUI/assets/128333288/b301998b-4e18-4ba1-b36b-f1337d5d7682)

Try `List Counter`, this is easier.

If you consistently get the same image even after changing the seed, something is wrong, and your modifications have not been applied. Changing the seed should always result in a different image.

**Comment by artem-konevskikh** [comment]
@omanhom Hey! Have you solved this issue? I have the same problem and it looks like the sampler, instead of processing n batches, processes the first batch n times.

**Comment by ltdrdata** [comment]
> @omanhom Hey! Have you solved this issue? I have the same problem and it looks like the sampler, instead of processing n batches, processes the first batch n times.

You need to check your workflow.
Generally, this occurs due to a misunderstanding of how lists work.
