### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by lunatico67** [comfyanonymous/ComfyUI#2427]
I just updated Comfyui and some custom nodes and cannot open Comfyui.

The last lines of the command :

File "C:\Users\Luna\Documents\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

C:\Users\cebuk\Documents\ComfyUI_windows_portable>pause
Press any key to continue . . .

I press any key and the command window disappears.

**Comment by narukaze132** [comment]
It looks like you somehow ended up updating PyTorch automatically, which got you the default version. This version does not have CUDA support, meaning it has no GPU acceleration.

Assuming you have an Nvidia GPU, try running this command in that directory:

```
.\python_embeded\Scripts\pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
```

This should install a CUDA-compatible version of PyTorch.

**Comment by lunatico67** [comment]
Hi!
Thanks for the help narukazel. 
Yes; I have a Nvidia GPU.
I must go to the Documents/ComfyUI_windows_portable/pythom_embeded folder and at the top of the window type cmd to open it in the command window and type: .\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
?

**Comment by narukaze132** [comment]
Actually you need to run the `pip` program in the Scripts folder of that directory... though if the problem's solved I suppose it's not that important.

**Comment by sanmilano** [comment]
Thanks narukaze132! I had the same problem after updating ComfyUI and doing what you said solved the issue

**Comment by zboing** [comment]
in my case worked only after running update_comfyui_and_python_dependencies.bat

**Comment by lunatico67** [comment]
> in my case worked only after running update_comfyui_and_python_dependencies.bat

Same for me

**Comment by moon47usaco** [comment]
> in my case worked only after running update_comfyui_and_python_dependencies.bat

This worked for me as well... =]

**Comment by avviano** [comment]
Worked for me!

**Comment by HydraBucket** [comment]
I am running comfyui through stability matrix. How would I fix this error?

**Comment by gonzalu** [comment]
> in my case worked only after running update_comfyui_and_python_dependencies.bat

This is the way... MANY THANKS!!!

**Comment by GrieverSY** [comment]
> in my case worked only after running update_comfyui_and_python_dependencies.bat

Where is that bat file located? I can't find it in scripts.

**Comment by eflin1** [comment]
yes    where are these   update_comfyui_and_python_dependencies.bat    hidden within ComfyUI_windows_portable ?

**Comment by eflin1** [comment]
yes where are these update_comfyui_and_python_dependencies.bat hidden within ComfyUI_windows_portable ?

ok   I got it , they are within  C:\ComfyUI_windows_portable\update

**Comment by raochinmay6** [comment]
hel me  i try but nothing happen

## ComfyUI-Manager: installing dependencies done.
[2024-06-30 23:35] ** ComfyUI startup time: 2024-06-30 23:35:54.490675
[2024-06-30 23:35] ** Platform: Windows
[2024-06-30 23:35] ** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
[2024-06-30 23:35] ** Python executable: E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe
[2024-06-30 23:35] ** ComfyUI Path: E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\main.py
[2024-06-30 23:35] ** Log path: E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\comfyui.log
[2024-06-30 23:35] 
Prestartup times for custom nodes:
[2024-06-30 23:35]    0.0 seconds: E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
[2024-06-30 23:35]    0.6 seconds: E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-06-30 23:35] 
Traceback (most recent call last):
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\main.py", line 76, in <module>
[2024-06-30 23:35]     import execution
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 11, in <module>
[2024-06-30 23:35]     import nodes
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
[2024-06-30 23:35]     import comfy.diffusers_load
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
[2024-06-30 23:35]     import comfy.sd
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
[2024-06-30 23:35]     from comfy import model_management
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 119, in <module>
[2024-06-30 23:35]     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
[2024-06-30 23:35]                                   ^^^^^^^^^^^^^^^^^^
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 88, in get_torch_device
[2024-06-30 23:35]     return torch.device(torch.cuda.current_device())
[2024-06-30 23:35]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
[2024-06-30 23:35]     _lazy_init()
[2024-06-30 23:35]   File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
[2024-06-30 23:35]     raise AssertionError("Torch not compiled with CUDA enabled")
[2024-06-30 23:35] AssertionError: Torch not compiled with CUDA enabled

**Comment by nothingness6** [comment]
> in my case worked only after running update_comfyui_and_python_dependencies.bat

Great! It works for me when I tried it twice. It failed first time, but worked second time. 
Thx!

**Comment by MultiTech-Visions** [comment]
> I am running comfyui through stability matrix. How would I fix this error?

Same, any help?   I have no idea where this .bat file is - and searching does NOT find it.

I also did not install the portable thing, so that's not helpful either.

Any help would be much appreciated, this as completely derailed everything.

**Comment by mcmonkey4eva** [comment]
when running through matrix, you'll have to ask the matrix team how to deal with that, as they did not use the comfy standard install they did their own thing

**Comment by farizy4n** [comment]
For proble worng path python like me,
**Fatal error in launcher: Unable to create process using '"D:\a\ComfyUI\python_embeded\python.exe" ** 
Cos idk how to remove path "D:\a\.." 
Please try 

`.\python_embeded\python.exe -s -m pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118`

**Comment by rachelcenter** [comment]
> Hi! Thanks for the help narukazel. Yes; I have a Nvidia GPU. I must go to the Documents/ComfyUI_windows_portable/pythom_embeded folder and at the top of the window type cmd to open it in the command window and type: .\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118 ?

D:\ComfyUI_windows_portable\python_embeded\Scripts>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
'.\python_embeded' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rachelcenter** [comment]
> Actually you need to run the `pip` program in the Scripts folder of that directory... though if the problem's solved I suppose it's not that important.

how do i run the pip program there? I tried this:

D:\ComfyUI_windows_portable\python_embeded\Scripts>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118

RESULT:
'.\python_embeded' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ltdrdata** [comment]
> > Actually you need to run the `pip` program in the Scripts folder of that directory... though if the problem's solved I suppose it's not that important.
> 
> how do i run the pip program there? I tried this:
> 
> D:\ComfyUI_windows_portable\python_embeded\Scripts>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
> 
> RESULT: '.\python_embeded' is not recognized as an internal or external command, operable program or batch file.

You have to execute that command in `D:\ComfyUI_windows_portable`

**Comment by rachelcenter** [comment]
> > > Actually you need to run the `pip` program in the Scripts folder of that directory... though if the problem's solved I suppose it's not that important.
> > 
> > 
> > how do i run the pip program there? I tried this:
> > D:\ComfyUI_windows_portable\python_embeded\Scripts>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
> > RESULT: '.\python_embeded' is not recognized as an internal or external command, operable program or batch file.
> 
> You have to execute that command in `D:\ComfyUI_windows_portable>`

Microsoft Windows [Version 10.0.22631.4037]
(c) Microsoft Corporation. All rights reserved.

D:\ComfyUI_windows_portable>python_embeded\Scripts>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
Access is denied.

D:\ComfyUI_windows_portable>

**Comment by rachelcenter** [comment]
> > > Actually you need to run the `pip` program in the Scripts folder of that directory... though if the problem's solved I suppose it's not that important.
> > 
> > 
> > how do i run the pip program there? I tried this:
> > D:\ComfyUI_windows_portable\python_embeded\Scripts>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
> > RESULT: '.\python_embeded' is not recognized as an internal or external command, operable program or batch file.
> 
> You have to execute that command in `D:\ComfyUI_windows_portable>`

D:\ComfyUI_windows_portable>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
'.\python_embeded' is not recognized as an internal or external command,
operable program or batch file.

D:\ComfyUI_windows_portable>

**Comment by rachelcenter** [comment]
wait nvm i went to root of windows portable and pasted the following in and now its doing something: .**\python_embeded\python.exe -s -m pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118**

**Comment by ltdrdata** [comment]
> > > > Actually you need to run the `pip` program in the Scripts folder of that directory... though if the problem's solved I suppose it's not that important.
> > > 
> > > 
> > > how do i run the pip program there? I tried this:
> > > D:\ComfyUI_windows_portable\python_embeded\Scripts>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
> > > RESULT: '.\python_embeded' is not recognized as an internal or external command, operable program or batch file.
> > 
> > 
> > You have to execute that command in `D:\ComfyUI_windows_portable>`
> 
> D:\ComfyUI_windows_portable>.\python_embeded install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118 '.\python_embeded' is not recognized as an internal or external command, operable program or batch file.
> 
> D:\ComfyUI_windows_portable>

.\python_embeded\python.exe -m pip install --force-reinstall torch --index-url

**Comment by rachelcenter** [comment]
now its stuck on: Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
    
    and hasnt progressed past that. so while i wait i tried to double click the run_nvidia_gpu file and it all it says is:
    
    
D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
WARNING: Ignoring invalid distribution ~pmath (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
[DONE] Security scan

**Comment by rachelcenter** [comment]
D:\ComfyUI_windows_portable> .\python_embeded\python.exe -s -m pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
WARNING: Ignoring invalid distribution ~pmath (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.4.0%2Bcu118-cp311-cp311-win_amd64.whl (2692.5 MB)
Collecting filelock (from torch)
  Using cached https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting typing-extensions>=4.8.0 (from torch)
  Using cached https://download.pytorch.org/whl/typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting sympy (from torch)
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx (from torch)
  Using cached https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting jinja2 (from torch)
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.3-py3-none-any.whl (133 kB)
Collecting fsspec (from torch)
  Using cached https://download.pytorch.org/whl/fsspec-2024.2.0-py3-none-any.whl (170 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl (17 kB)
Collecting mpmath>=0.19 (from sympy->torch)
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
WARNING: Ignoring invalid distribution ~pmath (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:

**Comment by Agiltech-com-au** [comment]
> Actually you need to run the `pip` program in the Scripts folder of that directory... though if the problem's solved I suppose it's not that important.

Thanks. I don't know why i didnt see it earlier that it was just going to the folder first :P but it depends what folder your in. easier to just go to scripts folder and run pip install :P confusing for a noob at first

**Comment by serget2** [comment]
pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118

Did not work because it could not find cu118

**Comment by LukeG89** [comment]
@serget2 Why installing cu118 instead of cu124?

https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#nvidia

**Comment by serget2** [comment]
That is what agitechs command said

**Comment by LukeG89** [comment]
@serget2 The cuda version is outdated, use this command instead:
```
pip install --force-reinstall torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
```

**Comment by serget2** [comment]
![afbeelding](https://github.com/user-attachments/assets/d38e983e-f5ab-45ce-b937-a6ea33ccbaf1)

**Comment by serget2** [comment]
Got it for the portable version you need to put python.exe -m pip in front of your command, now it works

**Comment by blissiraDC** [comment]
> It looks like you somehow ended up updating PyTorch automatically, which got you the default version. This version does not have CUDA support, meaning it has no GPU acceleration.
> 
> Assuming you have an Nvidia GPU, try running this command in that directory:
> 
> ```
> .\python_embeded\Scripts\pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> This should install a CUDA-compatible version of PyTorch.

Absolute legend! Thanks!

**Comment by zlocot666** [comment]
Log into your python folder and there is a scripts folder.
Do you see the PIP file there?
In the address bar of the explorer, click edit and write cmd, then enter, click
paste this and the download will go
pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu128

**Comment by raochinmay6** [comment]
- Gilson0516 to execute the following commands:
      - cd C:\Users\jglee\AppData\Roaming\StabilityMatrix\Packages\ComfyUI
      - ls
      - .\venv\Scripts\activate
      - pip list
      - pip install --force-reinstall torch --index-url
      https://download.pytorch.org/whl/cu118
      <https://www.google.com/url?q=https://download.pytorch.org/whl/cu118&source=gmail&sa=D&sa=E>
   - Freubs to execute the command: .\python_embeded\Scripts\pip install
   --force-reinstall torch --index-url
   https://download.pytorch.org/whl/cu128
   <https://www.google.com/url?q=https://download.pytorch.org/whl/cu128&source=gmail&sa=D&sa=E>
from
   the Portable directory in a cmd window.
   - Jose4D to update CUDA to 12.8 by executing the command: pip install
   --force-reinstall torch --index-url
   https://download.pytorch.org/whl/cu128
   <https://www.google.com/url?q=https://download.pytorch.org/whl/cu128&source=gmail&sa=D&sa=E>
within
   "Stability Matrix" (...STABILITY_MATRIX\Data\Packages\ComfyUI\venv\Scripts).
   - Zlocot666 to check the python folder for a scripts folder with a PIP
   file, then to open cmd in that location and paste the provided link for
   download.

**Comment by benjamindemoor** [comment]
> Log into your python folder and there is a scripts folder. Do you see the PIP file there? In the address bar of the explorer, click edit and write cmd, then enter, click paste this and the download will go pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu128

this worked! thanks

**Comment by prathamesh-gharat** [comment]
> pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu128

It should be `./pip.exe` as in
```./pip.exe install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu128``` at least in power shell, otherwise it will use the global python installation instead of the portable one and install the torch package elsewhere.

**Comment by spyrohea** [comment]
it ended up deleting all
