### ISSUE TITLE
Cuda memory error even when I have memory left

### ISSUE THREAD

**Issue by yedidyakfir** [comfyanonymous/ComfyUI#2982]
I am trying to use the default workflow in comfyUI using sdxl refiner model.
However, I immediately get an error 

> Allocation on device 0 would exceed allowed memory. (out of memory) Currently allocated : 1.62 GiB Requested : 25.00 MiB Device limit : 6.00 GiB Free (according to CUDA): 3.45 GiB comfy ui

According to this I still have memory left in my cuda device but I still get the error.
What is the problem here?
Is there any way to solve it? 
I am not running anything else on my computer, just comfyUI.

**Comment by rdcoder33** [comment]
The error is not about your Storage Memory, it's about your VRAM (GPU's RAM). You should check how to run comfy ui in a low VRAM device.

**Comment by Kaneki-kibutsuji** [comment]
Funnily, I got this same issue when I was installing and testing new random nodes, I reverted back to previous snapshots and even removed all the new nodes, but the problem still stayed persistent. I somehow broke my Comfyui for almost 1 week and struggled with finding a solution or using --novram argument and half the speed to make it work somehow. 
After struggling for a week, I found multiple folder starting with the name ~Orch in Comfyui/Python_Embeded/Lib/site_packages that I had never seen before. It was a separate Torch, and somehow I was running 2 Torch in my Comfyui. Once I deleted those folders, my problems went away with memory out of cuda.
I still don't know which node caused it, but that is what fixed it for me. I took backup too just in case I was wrong before deleting, so be cautious before removing anything. 
I struggled for a whole week and went through the internet to find a solution, but could not, so I'm just throwing out what worked for me.

**Comment by ltdrdata** [comment]
This issue is likely occurring because of fragmentation during repeated allocation and deallocation in VRAM, making it impossible to allocate memory of that size continuously.

**Comment by Kaneki-kibutsuji** [comment]
> This issue is likely occurring because of fragmentation during repeated allocation and deallocation in VRAM, making it impossible to allocate memory of that size continuously.
> 
> try with --disable-smart-memory

Tried that along with --disable-cuda-malloc, nothing worked except for --novram to make refiner work, but it ended up slowing down my generation speed a little. 
Everything went to normal once I deleted that 2nd Torch folder that I still don't know how it got there or which node installed it as I was testing multiple random nodes at that time. 
I'm not that much into computer languages, so finding a solution was hard as some solutions were posted on python site which I could not understand or knew if they worked or what. I went through the internet and struggled for almost a week, that is until I noticed 2 Torch folders in site packages of python folder.
