### ISSUE TITLE
Applying DoRAs to SDXL causes torch.cuda.OutOfMemoryError 

### ISSUE THREAD

**Issue by sugosugi-sugosugo** [comfyanonymous/ComfyUI#3557]
Applying DoRAs to SDXL models causes OOM error.

[workflow.json](https://github.com/comfyanonymous/ComfyUI/files/15430891/workflow.json)

Using in-place multiplication for weight calculation seems to solve this problem, but I can't confirm this is a breaking change or not

```patch
diff --git a/comfy/model_patcher.py b/comfy/model_patcher.py
index c397ee5..580f09d 100644
--- a/comfy/model_patcher.py
+++ b/comfy/model_patcher.py
@@ -20,6 +20,17 @@ def apply_weight_decompose(dora_scale, weight):
 
     return weight * (dora_scale / weight_norm).type(weight.dtype)
 
+def get_weight_decompose_scale(dora_scale, weight):
+    weight_norm = (
+        weight.transpose(0, 1)
+        .reshape(weight.shape[1], -1)
+        .norm(dim=1, keepdim=True)
+        .reshape(weight.shape[1], *[1] * (weight.dim() - 1))
+        .transpose(0, 1)
+    )
+
+    return (dora_scale / weight_norm).type(weight.dtype)
+
 def set_model_options_patch_replace(model_options, patch, name, block_name, number, transformer_index=None):
     to = model_options["transformer_options"].copy()
 
@@ -365,7 +376,7 @@ class ModelPatcher:
                 try:
                     weight += (alpha * torch.mm(mat1.flatten(start_dim=1), mat2.flatten(start_dim=1))).reshape(weight.shape).type(weight.dtype)
                     if dora_scale is not None:
-                        weight = apply_weight_decompose(comfy.model_management.cast_to_device(dora_scale, weight.device, torch.float32), weight)
+                        weight *= get_weight_decompose_scale(comfy.model_management.cast_to_device(dora_scale, weight.device, torch.float32), weight)
                 except Exception as e:
                     logging.error("ERROR {} {} {}".format(patch_type, key, e))
             elif patch_type == "lokr":

```

## environment
- model: Base SDXL
- DoRA: https://civitai.com/models/449412/envy-starlight-scifi-aesthetic-collection
- OS: Windows 11
- Pytorch 2.2.2+cu121
- NVIDIA RTX 4070 Ti (VRAM:12GB)

## error log
<details>

```
D:\sd\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12282 MB, total RAM 32530 MB
pytorch version: 2.2.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:357: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load SDXL
Loading 1 new model
ERROR lora diffusion_model.output_blocks.2.1.transformer_blocks.4.ff.net.0.proj.weight Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 5.91 GiB
Requested               : 50.00 MiB
Device limit            : 11.99 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
!!! Exception during processing!!! Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 5.91 GiB
Requested               : 25.00 MiB
Device limit            : 11.99 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
Traceback (most recent call last):
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1344, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1314, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 37, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 761, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 663, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 640, in sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\sampler_helpers.py", line 64, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, model.memory_required([noise_shape[0] * 2] + list(noise_shape[1:])) + inference_memory)
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 462, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 306, in model_load
    raise e
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 302, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to, patch_weights=load_weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 270, in patch_model
    self.patch_weight_to_device(key, device_to)
  File "D:\sd\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 251, in patch_weight_to_device
    out_weight = self.calculate_weight(self.patches[key], temp_weight, key).to(weight.dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 5.91 GiB
Requested               : 25.00 MiB
Device limit            : 11.99 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

Prompt executed in 17.63 seconds
```
</details>

**Comment by shawnington** [comment]
so, make a pull request

**Comment by comfyanonymous** [comment]
Can you check if it still happens if you update?

**Comment by sugosugi-sugosugo** [comment]
I confirmed that the issue has been fixed. Thank you!

**Comment by shawnington** [comment]
```
return weight * (dora_scale / weight_norm)
```
vs 

```
return (dora_scale / weight_norm).type(weight.dtype)
```

Im struggling to figure out what this is doing different, its moving the multiply by weight to 

```
weight *= get_weight_decompose_scale
```

whats the difference between this and doing 

```
return weight * ((dora_scale / weight_norm).type(weight.dtype))
```

since the only change is the type(weight.dtype)

I don't really understand that differences in typing before or after multiplication. Does it keep it on device or prevent copy? 
Would that code do the same thing in one line as the entire function copy with only the return being different?

Definitely some stuff I have to learn if this works.

**Comment by sugosugi-sugosugo** [comment]
I think this is a Pytorch's stuff rather than a Python's one.

When function is used, a new tensor is allocated in GPU for return value  and be freed afterwards:
```python
# 1. function
weight1 = torch.nn.Parameter(torch.zeros(1)).cuda()

def calc(weight):
    return weight * 2

with torch.profiler.profile(
   activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA],
   profile_memory=True
) as p1:
  weight1 = calc(weight1)
print(p1.key_averages().table())
```

```
-------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
         Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
-------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
     [memory]         0.00%       0.000us         0.00%       0.000us       0.000us       0.000us         0.00%       0.000us       0.000us           8 b           8 b        -512 b        -512 b             2
    aten::mul       100.00%      12.084ms       100.00%      12.084ms      12.084ms      12.399ms       100.00%      12.399ms      12.399ms           0 b           0 b         512 b         512 b             1
-------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
```

When in-place method is used, no new allocations will happen:

```python
 # 2. in-place
weight2 = torch.nn.Parameter(torch.zeros(1)).cuda()

def two():
   return 2

with torch.profiler.profile(
   activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA],
   profile_memory=True
) as p2:
  weight2 *= two()

print(p2.key_averages().table())
```

```
--------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
          Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem    # of Calls
--------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
      [memory]         0.00%       0.000us         0.00%       0.000us       0.000us       0.000us         0.00%       0.000us       0.000us           8 b           8 b             1
    aten::mul_       100.00%      77.000us       100.00%      77.000us      77.000us      92.000us       100.00%      92.000us      92.000us           0 b           0 b             1
--------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
```

**Comment by shawnington** [comment]
> I think this is a Pytorch's stuff rather than a Python's one.
> 
> When function is used, a new tensor is allocated in GPU for return value and be freed afterwards:
> 
> ```python
> # 1. function
> weight1 = torch.nn.Parameter(torch.zeros(1)).cuda()
> 
> def calc(weight):
>     return weight * 2
> 
> with torch.profiler.profile(
>    activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA],
>    profile_memory=True
> ) as p1:
>   weight1 = calc(weight1)
> print(p1.key_averages().table())
> ```
> 
>  ```
> -------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
>          Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
> -------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
>      [memory]         0.00%       0.000us         0.00%       0.000us       0.000us       0.000us         0.00%       0.000us       0.000us           8 b           8 b        -512 b        -512 b             2
>     aten::mul       100.00%      12.084ms       100.00%      12.084ms      12.084ms      12.399ms       100.00%      12.399ms      12.399ms           0 b           0 b         512 b         512 b             1
> -------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
> ```
> 
> When in-place method is used, no new allocations will happen:
> 
> ```python
>  # 2. in-place
> weight2 = torch.nn.Parameter(torch.zeros(1)).cuda()
> 
> def two():
>    return 2
> 
> with torch.profiler.profile(
>    activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA],
>    profile_memory=True
> ) as p2:
>   weight2 *= two()
> 
> print(p2.key_averages().table())
> ```
> 
>  ```
> --------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
>           Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem    # of Calls
> --------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
>       [memory]         0.00%       0.000us         0.00%       0.000us       0.000us       0.000us         0.00%       0.000us       0.000us           8 b           8 b             1
>     aten::mul_       100.00%      77.000us       100.00%      77.000us      77.000us      92.000us       100.00%      92.000us      92.000us           0 b           0 b             1
> --------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
> ```

Ah, gotcha, thanks. That makes a lot more sense. I really appreciate the in depth break down.

**Comment by shawnington** [comment]
> > I think this is a Pytorch's stuff rather than a Python's one.
> > When function is used, a new tensor is allocated in GPU for return value and be freed afterwards:

After testing for MPS I got some strange results.

```python
device = torch.device("mps")

weight1 = torch.nn.Parameter(torch.zeros(1)).to(device)
print(f"Weight1 Tensors Loaded > torch.mps.current_allocated_memory(): {torch.mps.current_allocated_memory()} b\n")

def calc(weight):
    return weight * 2

with profiler.profile(with_stack=True, profile_memory=True) as p1:
  weight1 = calc(weight1)
print(f"\n MPS Memory: weight1 = calc(weight1) > torch.mps.current_allocated_memory(): {torch.mps.current_allocated_memory()} b")
print(p1.key_averages().table())
```
```
Weight1 Tensors Loaded > torch.mps.current_allocated_memory(): 256 b

MPS Memory: weight1 = calc(weight1) > torch.mps.current_allocated_memory(): 512 b
-----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                         Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  
-----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                     [memory]         0.00%       0.000us         0.00%       0.000us       0.000us           8 b           8 b             1  
                    aten::mul        99.98%      43.965ms       100.00%      43.975ms      43.975ms           0 b           0 b             1  
                   aten::item         0.02%       8.000us         0.02%      10.000us      10.000us           0 b           0 b             1  
    aten::_local_scalar_dense         0.00%       2.000us         0.00%       2.000us       2.000us           0 b           0 b             1  
-----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Self CPU time total: 43.975ms
```

```python
device = torch.device("mps")

weight2 = torch.nn.Parameter(torch.zeros(1)).to(device)
print(f"Weight2 Tensors Loaded > torch.mps.current_allocated_memory(): {torch.mps.current_allocated_memory()} b\n")

def two():
   return 2

with profiler.profile(with_stack=True, profile_memory=True) as p2:
  weight2 *= two()

print(f"\n MPS Memory: weight2 *= two() > torch.mps.current_allocated_memory(): {torch.mps.current_allocated_memory()} b")
print(p2.key_averages().table())
```
```
Weight2 Tensors Loaded > torch.mps.current_allocated_memory(): 256 b

 MPS Memory: weight2 *= two() > torch.mps.current_allocated_memory(): 512 b
-----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                         Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  
-----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                     [memory]         0.00%       0.000us         0.00%       0.000us       0.000us           8 b           8 b             1  
                   aten::mul_        98.63%     216.000us       100.00%     219.000us     219.000us           0 b           0 b             1  
                   aten::item         0.91%       2.000us         1.37%       3.000us       3.000us           0 b           0 b             1  
    aten::_local_scalar_dense         0.46%       1.000us         0.46%       1.000us       1.000us           0 b           0 b             1  
-----------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Self CPU time total: 219.000us
```

Both ways still allocate 256b of memory for the operation, and at least according to the documentation:

>>`torch.mps.current_allocated_memory()`: Returns the current GPU memory occupied by tensors in bytes.
>>Note: The returned size does not include cached allocations in memory pools of MPSAllocator.

the output is the size of current tensors, so it has to be doing a copy for both, but the in-place is dramatically faster like your profile. Im very confused.  

aten::mul_ is the in-place multiplication operation, so it is being multiplied in-place. Not sure why aten::item or aten::_local_scalar_dense are called, that could be responsible, and in-place multiplication might not be properly implemented for MPS in pytorch, the copy might be being made after aten::mul_ by aten::item 

The aten::item and aten::_local_scalar_dense are called using your profiling method also. 

Am I messing something up, this doesn't seem right?
