### ISSUE TITLE
torch.OutOfMemoryError: Allocation on device 

### ISSUE THREAD

**Issue by yankilong** [comfyanonymous/ComfyUI#5278]
### Expected Behavior

img to video ,use cogvideoX-5b-I2V

### Actual Behavior

![QQ20241019-013337](https://github.com/user-attachments/assets/0cb3d1ac-c7b3-4a1c-abc8-2f0c7b16f044)

### Steps to Reproduce

![e87808d9-0dfa-4a2c-a654-f1582f397343](https://github.com/user-attachments/assets/d1f60be4-4c3f-4273-8834-a0116a93b37c)

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** CogVideoDecode
- **Exception Type:** torch.OutOfMemoryError
- **Exception Message:** Allocation on device 
## Stack Trace

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1100, in decode
    frames = vae.decode(latents).sample
             ^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1184, in decode
    decoded = self._decode(z).sample
              ^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1142, in _decode
    return self.tiled_decode(z, return_dict=return_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1332, in tiled_decode
    tile = self.decoder(tile)
           ^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 877, in forward
    hidden_states = up_block(hidden_states, temb, sample)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 602, in forward
    hidden_states = resnet(hidden_states, temb, zq)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 291, in forward
    hidden_states = self.conv1(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 144, in forward
    output = self.conv(inputs)
             ^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 64, in forward
    return super().forward(input)
           ^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 608, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 603, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.3-18-g518c0dc
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884443136
  - **VRAM Free:** 10727621930
  - **Torch VRAM Total:** 1174405120
  - **Torch VRAM Free:** 192578858

## Logs
```
2024-10-19 01:10:47,703 - root - INFO - Total VRAM 12288 MB, total RAM 32694 MB
2024-10-19 01:10:47,703 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-19 01:10:47,712 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-19 01:10:47,712 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
2024-10-19 01:10:48,875 - root - INFO - Using pytorch cross attention
2024-10-19 01:10:50,342 - root - INFO - [Prompt Server] web root: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\web
2024-10-19 01:10:51,542 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-19 01:10:51,559 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-10-19 01:10:51,560 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-19 01:10:51,727 - numexpr.utils - INFO - NumExpr defaulting to 12 threads.
2024-10-19 01:10:52,044 - root - INFO - Total VRAM 12288 MB, total RAM 32694 MB
2024-10-19 01:10:52,044 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-19 01:10:52,045 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-19 01:10:52,045 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
2024-10-19 01:10:59,853 - root - INFO - 
Import times for custom nodes:
2024-10-19 01:10:59,853 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\0_FutureWarningIgnore.py
2024-10-19 01:10:59,853 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
2024-10-19 01:10:59,854 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-19 01:10:59,858 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\comfyui-portrait-master-zh-cn
2024-10-19 01:10:59,858 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
2024-10-19 01:10:59,859 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-10-19 01:10:59,860 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-19 01:10:59,860 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
2024-10-19 01:10:59,861 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-10-19 01:10:59,862 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-19 01:10:59,862 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-19 01:10:59,863 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyMath
2024-10-19 01:10:59,863 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-19 01:10:59,864 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-19 01:10:59,865 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-19 01:10:59,865 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-19 01:10:59,866 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
2024-10-19 01:10:59,866 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\rgthree-comfy
2024-10-19 01:10:59,867 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-10-19 01:10:59,867 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-19 01:10:59,868 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-19 01:10:59,868 - root - INFO -    0.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-19 01:10:59,869 - root - INFO -    0.1 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-19 01:10:59,869 - root - INFO -    0.1 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-10-19 01:10:59,870 - root - INFO -    0.2 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-10-19 01:10:59,873 - root - INFO -    0.2 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-19 01:10:59,873 - root - INFO -    0.2 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_WordCloud
2024-10-19 01:10:59,873 - root - INFO -    0.4 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-BrushNet
2024-10-19 01:10:59,874 - root - INFO -    0.4 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-19 01:10:59,875 - root - INFO -    0.6 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-19 01:10:59,876 - root - INFO -    0.6 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-10-19 01:10:59,876 - root - INFO -    0.9 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\comfyui-reactor-node
2024-10-19 01:10:59,877 - root - INFO -    1.2 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-10-19 01:10:59,877 - root - INFO -    1.6 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-19 01:10:59,878 - root - INFO -    2.0 seconds: F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-19 01:10:59,878 - root - INFO - 
2024-10-19 01:10:59,893 - root - INFO - Starting server

2024-10-19 01:10:59,893 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-19 01:11:30,511 - root - INFO - got prompt
2024-10-19 01:12:04,273 - ComfyUI-CogVideoXWrapper.nodes - INFO - Encoded latents shape: torch.Size([1, 1, 16, 60, 90])
2024-10-19 01:12:11,413 - root - INFO - Requested to load SD3ClipModel_
2024-10-19 01:12:11,413 - root - INFO - Loading 1 new model
2024-10-19 01:12:11,420 - root - INFO - loaded completely 0.0 4541.693359375 True
2024-10-19 01:12:16,327 - ComfyUI-CogVideoXWrapper.pipeline_cogvideox - INFO - Only one image conditioning frame received, img2vid
2024-10-19 01:13:46,800 - root - ERROR - !!! Exception during processing !!! Allocation on device 
2024-10-19 01:13:46,807 - root - ERROR - Traceback (most recent call last):
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1100, in decode
    frames = vae.decode(latents).sample
             ^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1184, in decode
    decoded = self._decode(z).sample
              ^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1142, in _decode
    return self.tiled_decode(z, return_dict=return_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1332, in tiled_decode
    tile = self.decoder(tile)
           ^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 877, in forward
    hidden_states = up_block(hidden_states, temb, sample)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 602, in forward
    hidden_states = resnet(hidden_states, temb, zq)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 291, in forward
    hidden_states = self.conv1(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 144, in forward
    output = self.conv(inputs)
             ^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 64, in forward
    return super().forward(input)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 608, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\comfyui\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 603, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^
torch.OutOfMemoryError: Allocation on device 

2024-10-19 01:13:46,810 - root - ERROR - Got an OOM, unloading all loaded models.
2024-10-19 01:13:46,883 - root - INFO - Prompt executed in 136.33 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":25,"last_link_id":29,"nodes":[{"id":15,"type":"ImageResizeKJ","pos":{"0":840,"1":1130},"size":{"0":315,"1":266},"flags":{},"order":3,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":12,"label":"image"},{"name":"get_image_size","type":"IMAGE","link":null,"shape":7,"label":"get_image_size"},{"name":"width_input","type":"INT","link":null,"widget":{"name":"width_input"},"shape":7,"label":"width_input"},{"name":"height_input","type":"INT","link":null,"widget":{"name":"height_input"},"shape":7,"label":"height_input"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[13],"slot_index":0,"label":"IMAGE"},{"name":"width","type":"INT","links":null,"label":"width"},{"name":"height","type":"INT","links":null,"label":"height"}],"properties":{"Node name for S&R":"ImageResizeKJ"},"widgets_values":[720,480,"lanczos",false,16,0,0,"disabled"]},{"id":13,"type":"CogVideoTextEncode","pos":{"0":820,"1":940},"size":{"0":420,"1":124},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":11,"label":"clip"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[20],"slot_index":0,"label":"conditioning"}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["bad",1,true]},{"id":12,"type":"CogVideoTextEncode","pos":{"0":800,"1":640},"size":{"0":400,"1":200},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":10,"label":"clip"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[19],"slot_index":0,"label":"conditioning"}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["scene 1:footjob,",1,true]},{"id":14,"type":"LoadImage","pos":{"0":380,"1":1040},"size":{"0":320,"1":310},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[12],"slot_index":0,"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"slot_index":1,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["00006-1215951672.png","image"]},{"id":17,"type":"CogVideoSampler","pos":{"0":1370,"1":430},"size":{"0":405.5999755859375,"1":370},"flags":{"collapsed":false},"order":7,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":18,"label":"pipeline"},{"name":"positive","type":"CONDITIONING","link":19,"label":"positive"},{"name":"negative","type":"CONDITIONING","link":20,"label":"negative"},{"name":"samples","type":"LATENT","link":null,"shape":7,"label":"samples"},{"name":"image_cond_latents","type":"LATENT","link":21,"shape":7,"label":"image_cond_latents"},{"name":"context_options","type":"COGCONTEXT","link":null,"shape":7,"label":"context_options"},{"name":"controlnet","type":"COGVIDECONTROLNET","link":null,"shape":7,"label":"controlnet"}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[14],"slot_index":0,"label":"cogvideo_pipe"},{"name":"samples","type":"LATENT","links":[15],"slot_index":1,"label":"samples"}],"properties":{"Node name for S&R":"CogVideoSampler"},"widgets_values":[480,720,49,2,6,0,"fixed","CogVideoXDPMScheduler",1]},{"id":16,"type":"CogVideoImageEncode","pos":{"0":1560,"1":1020},"size":{"0":315,"1":122},"flags":{},"order":6,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":17,"label":"pipeline"},{"name":"image","type":"IMAGE","link":13,"label":"image"},{"name":"mask","type":"MASK","link":null,"shape":7,"label":"mask"}],"outputs":[{"name":"samples","type":"LATENT","links":[21],"slot_index":0,"label":"samples"}],"properties":{"Node name for S&R":"CogVideoImageEncode"},"widgets_values":[16,true]},{"id":11,"type":"CLIPLoader","pos":{"0":330,"1":580},"size":{"0":315,"1":82},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[10,11],"slot_index":0,"label":"CLIP"}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","sd3"]},{"id":10,"type":"DownloadAndLoadCogVideoModel","pos":{"0":850,"1":320},"size":{"0":315,"1":194},"flags":{},"order":2,"mode":0,"inputs":[{"name":"pab_config","type":"PAB_CONFIG","link":null,"shape":7,"label":"pab_config"},{"name":"block_edit","type":"TRANSFORMERBLOCKS","link":null,"shape":7,"label":"block_edit"},{"name":"lora","type":"COGLORA","link":null,"shape":7,"label":"lora"}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[17,18],"slot_index":0,"label":"cogvideo_pipe"}],"properties":{"Node name for S&R":"DownloadAndLoadCogVideoModel"},"widgets_values":["THUDM/CogVideoX-5b-I2V","bf16","enabled","disabled",false]},{"id":18,"type":"CogVideoDecode","pos":{"0":1860,"1":460},"size":{"0":315,"1":198},"flags":{},"order":8,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":14,"label":"pipeline"},{"name":"samples","type":"LATENT","link":15,"label":"samples"}],"outputs":[{"name":"images","type":"IMAGE","links":[16],"slot_index":0,"label":"images"}],"properties":{"Node name for S&R":"CogVideoDecode"},"widgets_values":[true,240,360,0.2,0.2,true]},{"id":20,"type":"VHS_VideoCombine","pos":{"0":2210,"1":490},"size":{"0":660,"1":310},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":16,"label":"images"},{"name":"audio","type":"AUDIO","link":null,"shape":7,"label":"audio"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7,"label":"meta_batch"},{"name":"vae","type":"VAE","link":null,"shape":7,"label":"vae"}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"label":"Filenames"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"CogVideoX-I2V","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{},"muted":false}}}],"links":[[10,11,0,12,0,"CLIP"],[11,11,0,13,0,"CLIP"],[12,14,0,15,0,"IMAGE"],[13,15,0,16,1,"IMAGE"],[14,17,0,18,0,"COGVIDEOPIPE"],[15,17,1,18,1,"LATENT"],[16,18,0,20,0,"IMAGE"],[17,10,0,16,0,"COGVIDEOPIPE"],[18,10,0,17,0,"COGVIDEOPIPE"],[19,12,0,17,1,"CONDITIONING"],[20,13,0,17,2,"CONDITIONING"],[21,16,0,17,4,"LATENT"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[-1023.8700000000036,50.49000000000034]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by Kaneki-kibutsuji** [comment]
Got the same issue, even went back to previous snapshot with comfyui manager, but something seems broken and I always get out of memory error on sdxl upscale refiner. It wasn't like this before, everything was fine.

**Comment by Eldar-H-1** [comment]
I got the same issue

**Comment by SantoshPisini** [comment]
I got the same issue

**Comment by offmybach** [comment]
me 2

**Comment by Linka0512** [comment]
I got the same issue
It still doesn't work the way [Kaneki-kibutsuji](https://github.com/Kaneki-kibutsuji) did.

**Comment by Sniza** [comment]
Me 2, same issue

**Comment by MaraScott** [comment]
me 2 same issue as it seems https://github.com/comfyanonymous/ComfyUI/issues/4860

**Comment by sevdalin** [comment]
I hit the same issue

**Comment by M4Rv** [comment]
same issue

**Comment by Sharknaab** [comment]
Same issue and finally fixed it here
I just did a new comfyUI from scratch. All was working well untill I installed comfyui-workspace-manager

The solution for me was to delete 2 folders in Comfyui/Python_Embeded/Lib/site_packages :

- send2trash
- Send2Trash-1.8.2.dist-info

Seems random but actually worked for me

**Comment by kamehamehash** [comment]
> running 2 Torch in my Comfyui

How did you find you running 2 Torch in ComfyUI?
Thanks

**Comment by Kaneki-kibutsuji** [comment]
> > running 2 Torch in my Comfyui
> 
> How did you find you running 2 Torch in ComfyUI? Thanks

I was new to AI as well as Comfyui. I said 2 torch folder cause it was the same as the main torch folder when I opened it. As for how I found it? I went to the folder: Comfyui/Python_Embeded/Lib/site_packages, sorted by date, and found this odd folder named "~Orch torch"  created after the date I started having problems. It might not be 2 torches, but it seemed like that folder was the problem,m and deleting it solved my problem.
