### ISSUE TITLE
Azure VM with Nvidia A100 - Workflow Error

### ISSUE THREAD

**Issue by Holger001** [comfyanonymous/ComfyUI#5423]
### Your question

Here’s a clear English version of your paragraph:

---

While trying to set up a demo series using ComfyUI, I encountered an error message in the logs during a basic workflow (standard image generation). I am testing it on a single VM configuration: an Azure VM with Windows 10 and an Nvidia A100 GPU with the following specifications:

- **nvcc**: NVIDIA (R) Cuda compiler driver  
  Copyright (c) 2005-2024 NVIDIA Corporation  
  Built on Thu Mar 28, 02:30:10 Pacific Daylight Time, 2024  
  Cuda compilation tools, release 12.4, V12.4.131  
  Build cuda_12.4.r12.4/compiler.34097967_0

- **Python version**: 3.13.0

- **nvidia-smi**: Run on Wed Oct 30, 2024  
  Driver Version: 566.03  
  CUDA Version: 12.7  
  GPU: NVIDIA A100 80GB PCIe with 300W power capacity and 80GB memory

  ```plaintext
  +-----------------------------------------------------------------------------------------+
  | NVIDIA-SMI 566.03                 Driver Version: 566.03         CUDA Version: 12.7     |
  |-----------------------------------------+------------------------+----------------------+  
  | GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
  |                                         |                        |               MIG M. |
  |=========================================+========================+======================|
  |   0  NVIDIA A100 80GB PCIe        TCC   |   00000001:00:00.0 Off |                    0 |
  | N/A   27C    P0             43W /  300W |      10MiB /  81920MiB |      0%      Default |
  |                                         |                        |             Disabled |
  +-----------------------------------------+------------------------+----------------------+
  
  +-----------------------------------------------------------------------------------------+
  | Processes:                                                                              |
  |  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
  |        ID   ID                                                               Usage      |
  |=========================================================================================|
  |  No running processes found                                                             |
  +-----------------------------------------------------------------------------------------+
  ```

- **ncu version**: NVIDIA (R) Nsight Compute Command Line Profiler  
  Version 2024.1.1.0 (build 33998838) (public release)

- **Additional software**: Visual Studio Professional 2019 (Build 16.11.41)

Has anyone successfully run ComfyUI on a VM with an A100 GPU? If so, what configuration worked for you?

### Logs

```powershell
C:\DAA Demo\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-30 09:34:11.832212
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\DAA Demo\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\DAA Demo\ComfyUI_windows_portable\ComfyUI
** Log path: C:\DAA Demo\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   3.9 seconds: C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 81454 MB, total RAM 225229 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A100 80GB PCIe : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\web
C:\DAA Demo\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2779 [8ce2a105] *DETACHED | Released on '2024-10-22'

Import times for custom nodes:
   0.0 seconds: C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
!!! Exception during processing !!! CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\nodes.py", line 65, in encode
    output = clip.encode_from_tokens(tokens, return_pooled=True, return_dict=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 124, in encode_from_tokens
    self.load_model()
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 156, in load_model
    model_management.load_model_gpu(self.patcher)
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 559, in load_model_gpu
    return load_models_gpu([model])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 545, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 327, in model_load
    raise e
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 323, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to, lowvram_model_memory=lowvram_model_memory, load_weights=load_weights, force_patch_weights=force_patch_weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 467, in patch_model
    self.load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights, full_load=full_load)
  File "C:\DAA Demo\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 439, in load
    x[2].to(device_to)
  File "C:\DAA Demo\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\DAA Demo\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Prompt executed in 40.61 seconds
```

**Comment by milewski** [comment]
Did you figured it out? I have the same issue

**Comment by Holger001** [comment]
Problem solved. At least for my environment. Hope it also works for comparable ones. I had to install the Nvidia A100 driver version downsize to 554.xxx and change from Cuda 12.6 to 12.4. Just too bad that the cuda installation does not automatically correct the environment variables again and you have to set them manually to the desired version in the CUDA_PATH variable. Took me 2 hours 🙁. Then adjust the lightglue.py in the embedded python environment to avoid the compatibility message at startup. 
@torch.cuda.amp.custom_fwd(cast_inputs=torch.float32) to the new syntax 
@torch.amp.custom_fwd(cast_inputs=troch.float32, device_type=‘cuda’).

**Comment by milewski** [comment]
I fixed it by staring comfy with `CLI_ARGS=--disable-cuda-malloc`
