### ISSUE TITLE
Allocation on device

### ISSUE THREAD

**Issue by mordak-95** [comfyanonymous/ComfyUI#5528]
### Expected Behavior

I encountered an error in *CogVideo Sampler*.

### Actual Behavior

![image_2024-11-07_21-58-04](https://github.com/user-attachments/assets/802c6c0e-a2fb-4de6-a094-79a5640e89bf)

### Steps to Reproduce

{
  "last_node_id": 72,
  "last_link_id": 132,
  "nodes": [
    {
      "id": 37,
      "type": "ImageResizeKJ",
      "pos": {
        "0": 489,
        "1": 154
      },
      "size": {
        "0": 320,
        "1": 270
      },
      "flags": {
        "pinned": true
      },
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "image",
          "type": "IMAGE",
          "link": 71
        },
        {
          "name": "get_image_size",
          "type": "IMAGE",
          "link": null,
          "shape": 7
        },
        {
          "name": "width_input",
          "type": "INT",
          "link": null,
          "widget": {
            "name": "width_input"
          }
        },
        {
          "name": "height_input",
          "type": "INT",
          "link": null,
          "widget": {
            "name": "height_input"
          }
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            125
          ],
          "slot_index": 0,
          "shape": 3
        },
        {
          "name": "width",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "height",
          "type": "INT",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "ImageResizeKJ"
      },
      "widgets_values": [
        720,
        480,
        "lanczos",
        false,
        16,
        0,
        0,
        "disabled"
      ]
    },
    {
      "id": 56,
      "type": "CogVideoDecode",
      "pos": {
        "0": 1408,
        "1": 474
      },
      "size": {
        "0": 300.396484375,
        "1": 198
      },
      "flags": {
        "pinned": true
      },
      "order": 13,
      "mode": 0,
      "inputs": [
        {
          "name": "pipeline",
          "type": "COGVIDEOPIPE",
          "link": 128
        },
        {
          "name": "samples",
          "type": "LATENT",
          "link": 127
        }
      ],
      "outputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "links": [
            118
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoDecode"
      },
      "widgets_values": [
        false,
        96,
        96,
        0.083,
        0.083,
        true
      ]
    },
    {
      "id": 63,
      "type": "Note",
      "pos": {
        "0": 68,
        "1": 41
      },
      "size": {
        "0": 401.79364013671875,
        "1": 66.40528106689453
      },
      "flags": {
        "pinned": true
      },
      "order": 0,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "Downloaded from https://www.patreon.com/sebastiankamph\nBased on Kijai's amazing work"
      ],
      "color": "#2a363b",
      "bgcolor": "#3f5159"
    },
    {
      "id": 57,
      "type": "CogVideoSampler",
      "pos": {
        "0": 981,
        "1": 475
      },
      "size": {
        "0": 405.5999755859375,
        "1": 410
      },
      "flags": {
        "pinned": true
      },
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "pipeline",
          "type": "COGVIDEOPIPE",
          "link": 121
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 122
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 123
        },
        {
          "name": "samples",
          "type": "LATENT",
          "link": null,
          "shape": 7
        },
        {
          "name": "image_cond_latents",
          "type": "LATENT",
          "link": 129,
          "shape": 7
        },
        {
          "name": "context_options",
          "type": "COGCONTEXT",
          "link": null,
          "shape": 7
        },
        {
          "name": "controlnet",
          "type": "COGVIDECONTROLNET",
          "link": null,
          "shape": 7
        },
        {
          "name": "tora_trajectory",
          "type": "TORAFEATURES",
          "link": null,
          "shape": 7
        },
        {
          "name": "fastercache",
          "type": "FASTERCACHEARGS",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "cogvideo_pipe",
          "type": "COGVIDEOPIPE",
          "links": [
            128
          ],
          "slot_index": 0,
          "shape": 3
        },
        {
          "name": "samples",
          "type": "LATENT",
          "links": [
            127
          ],
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoSampler"
      },
      "widgets_values": [
        480,
        720,
        49,
        50,
        6,
        65334758276105,
        "fixed",
        "DPM++",
        1
      ],
      "color": "#223",
      "bgcolor": "#335"
    },
    {
      "id": 1,
      "type": "DownloadAndLoadCogVideoModel",
      "pos": {
        "0": 73,
        "1": 719
      },
      "size": {
        "0": 390.02581787109375,
        "1": 194
      },
      "flags": {
        "pinned": true
      },
      "order": 1,
      "mode": 0,
      "inputs": [
        {
          "name": "pab_config",
          "type": "PAB_CONFIG",
          "link": null,
          "shape": 7
        },
        {
          "name": "block_edit",
          "type": "TRANSFORMERBLOCKS",
          "link": null,
          "shape": 7
        },
        {
          "name": "lora",
          "type": "COGLORA",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "cogvideo_pipe",
          "type": "COGVIDEOPIPE",
          "links": [
            121,
            124
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "DownloadAndLoadCogVideoModel"
      },
      "widgets_values": [
        "THUDM/CogVideoX-5b-I2V",
        "bf16",
        "disabled",
        "disabled",
        false
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 20,
      "type": "CLIPLoader",
      "pos": {
        "0": 72,
        "1": 594
      },
      "size": {
        "0": 388.0544738769531,
        "1": 82
      },
      "flags": {
        "pinned": true
      },
      "order": 2,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            54,
            56
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPLoader"
      },
      "widgets_values": [
        "google_t5-v1_1-xxl_encoderonly.safetensors",
        "sd3"
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 36,
      "type": "LoadImage",
      "pos": {
        "0": 68,
        "1": 151
      },
      "size": {
        "0": 400,
        "1": 400
      },
      "flags": {
        "pinned": true
      },
      "order": 3,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            71
          ],
          "slot_index": 0,
          "shape": 3
        },
        {
          "name": "MASK",
          "type": "MASK",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "LoadImage"
      },
      "widgets_values": [
        "output_38_1730990674021.png",
        "image"
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 44,
      "type": "VHS_VideoCombine",
      "pos": {
        "0": 1726,
        "1": 474
      },
      "size": [
        610,
        310
      ],
      "flags": {
        "pinned": true
      },
      "order": 14,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 118
        },
        {
          "name": "audio",
          "type": "AUDIO",
          "link": null,
          "shape": 7
        },
        {
          "name": "meta_batch",
          "type": "VHS_BatchManager",
          "link": null,
          "shape": 7
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "Filenames",
          "type": "VHS_FILENAMES",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "VHS_VideoCombine"
      },
      "widgets_values": {
        "frame_rate": 12,
        "loop_count": 0,
        "filename_prefix": "CogVideoX-I2V",
        "format": "video/h264-mp4",
        "pix_fmt": "yuv420p",
        "crf": 19,
        "save_metadata": true,
        "pingpong": false,
        "save_output": true,
        "videopreview": {
          "hidden": false,
          "paused": false,
          "params": {
            "filename": "CogVideoX-I2V_00009.mp4",
            "subfolder": "",
            "type": "output",
            "format": "video/h264-mp4",
            "frame_rate": 24
          },
          "muted": false
        }
      },
      "color": "#223",
      "bgcolor": "#335"
    },
    {
      "id": 60,
      "type": "Note",
      "pos": {
        "0": -156,
        "1": 151
      },
      "size": {
        "0": 210,
        "1": 58
      },
      "flags": {
        "pinned": true
      },
      "order": 4,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "Load 720x480 images\nOr aspect ratio 3:2"
      ],
      "color": "#2a363b",
      "bgcolor": "#3f5159"
    },
    {
      "id": 61,
      "type": "Note",
      "pos": {
        "0": -156,
        "1": 601
      },
      "size": {
        "0": 210,
        "1": 58
      },
      "flags": {
        "pinned": true
      },
      "order": 5,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "Load t5xxl_fp8_e4m3fn text encoder (available in Model Manager)"
      ],
      "color": "#2a363b",
      "bgcolor": "#3f5159"
    },
    {
      "id": 71,
      "type": "Note",
      "pos": {
        "0": 2350,
        "1": 479
      },
      "size": {
        "0": 276.1275634765625,
        "1": 106.689697265625
      },
      "flags": {
        "pinned": true
      },
      "order": 6,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "Good frame rates:\n8\n12\n24"
      ],
      "color": "#2a363b",
      "bgcolor": "#3f5159"
    },
    {
      "id": 31,
      "type": "CogVideoTextEncode",
      "pos": {
        "0": 494,
        "1": 684
      },
      "size": {
        "0": 463.01251220703125,
        "1": 144
      },
      "flags": {
        "pinned": true
      },
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 56
        }
      ],
      "outputs": [
        {
          "name": "conditioning",
          "type": "CONDITIONING",
          "links": [
            123
          ],
          "slot_index": 0,
          "shape": 3
        },
        {
          "name": "clip",
          "type": "CLIP",
          "links": null
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoTextEncode"
      },
      "widgets_values": [
        "The video is not of a high quality, it has a low resolution. Watermark present in each frame. Strange motion trajectory. ",
        1,
        true
      ],
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 64,
      "type": "Note",
      "pos": {
        "0": -155,
        "1": 722
      },
      "size": {
        "0": 210,
        "1": 142.0885772705078
      },
      "flags": {
        "pinned": true
      },
      "order": 7,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "Select the latest CogVideoX I2V model. Use 5b for high end systems and 2b for low vram (2B I2V currently NOT available)\n\nDownloads AUTOMATICALLY when run."
      ],
      "color": "#2a363b",
      "bgcolor": "#3f5159"
    },
    {
      "id": 30,
      "type": "CogVideoTextEncode",
      "pos": {
        "0": 490,
        "1": 469
      },
      "size": {
        "0": 471.90142822265625,
        "1": 168.08047485351562
      },
      "flags": {
        "pinned": true
      },
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 54
        }
      ],
      "outputs": [
        {
          "name": "conditioning",
          "type": "CONDITIONING",
          "links": [
            122
          ],
          "slot_index": 0,
          "shape": 3
        },
        {
          "name": "clip",
          "type": "CLIP",
          "links": null
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoTextEncode"
      },
      "widgets_values": [
        "Starting with the given image of the woman facing the camera, she slowly turns her back and walks away into the darkness. The blue and red lights gradually dim as she moves further away, adding to the mysterious, sci-fi atmosphere. The futuristic text remains visible for a moment longer, then fades out, leaving the scene in shadow.",
        1,
        true
      ],
      "color": "#232",
      "bgcolor": "#353"
    },
    {
      "id": 58,
      "type": "CogVideoImageEncode",
      "pos": {
        "0": 910,
        "1": 950
      },
      "size": {
        "0": 315,
        "1": 122
      },
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "pipeline",
          "type": "COGVIDEOPIPE",
          "link": 124
        },
        {
          "name": "image",
          "type": "IMAGE",
          "link": 125
        },
        {
          "name": "mask",
          "type": "MASK",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "links": [
            129
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoImageEncode"
      },
      "widgets_values": [
        16,
        true
      ]
    }
  ],
  "links": [
    [
      54,
      20,
      0,
      30,
      0,
      "CLIP"
    ],
    [
      56,
      20,
      0,
      31,
      0,
      "CLIP"
    ],
    [
      71,
      36,
      0,
      37,
      0,
      "IMAGE"
    ],
    [
      118,
      56,
      0,
      44,
      0,
      "IMAGE"
    ],
    [
      121,
      1,
      0,
      57,
      0,
      "COGVIDEOPIPE"
    ],
    [
      122,
      30,
      0,
      57,
      1,
      "CONDITIONING"
    ],
    [
      123,
      31,
      0,
      57,
      2,
      "CONDITIONING"
    ],
    [
      124,
      1,
      0,
      58,
      0,
      "COGVIDEOPIPE"
    ],
    [
      125,
      37,
      0,
      58,
      1,
      "IMAGE"
    ],
    [
      127,
      57,
      1,
      56,
      1,
      "LATENT"
    ],
    [
      128,
      57,
      0,
      56,
      0,
      "COGVIDEOPIPE"
    ],
    [
      129,
      58,
      0,
      57,
      4,
      "LATENT"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {
    "ds": {
      "scale": 0.8954302432552613,
      "offset": [
        -178.5265717043045,
        -106.27388571244478
      ]
    }
  },
  "version": 0.4
}

### Debug Logs

```powershell
got prompt
Encoded latents shape: torch.Size([1, 1, 16, 60, 90])
!!! Exception during processing !!! Error while deserializing header: MetadataIncompleteBuffer
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 918, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 453, in load_clip
    clip_data.append(comfy.utils.load_torch_file(p, safe_load=True))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

Prompt executed in 19.30 seconds
got prompt
Requested to load SD3ClipModel_
Loading 1 new model
loaded partially 625.3578575134277 603.38671875 0
loaded partially 1234.1859825134277 1211.38671875 0
Only one image conditioning frame received, img2vid
Temporal tiling and context schedule disabled
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 868, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 874, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 649, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py", line 440, in forward
    embeds = embeds + pos_embedding
             ~~~~~~~^~~~~~~~~~~~~~~
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 20.36 seconds
```

**Comment by ltdrdata** [comment]
That means your VRAM is insufficient for the task.

**Comment by mordak-95** [comment]
> That means your VRAM is insufficient for the task.

The VRAM I have is 12GB.
How much should it be to be considered suitable?

**Comment by ltdrdata** [comment]
> > That means your VRAM is insufficient for the task.
> 
> The VRAM I have is 12GB. How much should it be to be considered suitable?

https://github.com/kijai/ComfyUI-CogVideoXWrapper?tab=readme-ov-file#update
That says 14GB is the peak.

**Comment by diGitTil** [comment]
confirm same error, and using a workflow I have used for weeks without any issues. after latest update of comfyUI, I now have this error.

**Comment by diGitTil** [comment]
encountered same error, solved by lowering latent image size.

**Comment by LnQan** [comment]
I've forgotten where I picked up this little trick, but you can try it: right-click on the node, and there should be an option called 'Fix node （recreate）'

**Comment by ltdrdata** [comment]
> I've forgotten where I picked up this little trick, but you can try it: right-click on the node, and there should be an option called 'Fix node （recreate）'

That is a feature of ComfyUI-Manager.

**Comment by dewarrn1** [comment]
Just to weigh in here, I am also seeing errors of this nature, but inconsistently. That is to say, an identical workflow with the same inputs, seeds, etc. will run to completion on some occasions, but it will then throw an Allocation on Device exception on others, typically on the CogVideo Decode node.  Further complicating the matter, it is often the case that simply restarting that same workflow in place, from the state that just threw the exception, will allow it to run to completion, saving out generated outputs, etc.

**Comment by thakshak** [comment]
Same issue on the CogVideoDecode node.
I'm using the [THUDM/CogVideoX-2b] model on a 1080ti 12GB VRAM.

**Comment by MagicL911** [comment]
It's due to attention mode. After this update, attention mode has been added

**Comment by dewarrn1** [comment]
Interesting. I had noticed an improvement recently in the last day or two, so maybe that's evidence.

**Comment by rhf2137** [comment]
减小缩放系数的值试试。

**Comment by rhf2137** [comment]
Try reducing the value of the scaling factor

**Comment by dsphotoblog** [comment]
check batchsize in empty latent image, too many batches will overload the vram

**Comment by aiisoft** [comment]
> > > 这意味着您的 VRAM 不足以完成任务。
> > 
> > 
> > 我拥有的 VRAM 是 12GB。应该有多少才算合适？
> 
> https://github.com/kijai/ComfyUI-CogVideoXWrapper?tab=readme-ov-file#update 也就是说 14GB 是峰值。

![Image](https://github.com/user-attachments/assets/f1e3ed94-6e56-4427-8b6b-4a8f7bd4410b)
me too
