### ISSUE TITLE
MacBook Pro M1, AssertionError: Torch not compiled with CUDA enabled.

### ISSUE THREAD

**Issue by fantasylion** [comfyanonymous/ComfyUI#5723]
### Your question

Hello:
After installing the documentation, running main.py resulted in an error: Torch not compiled with CUDA enabled. I saw that others could run after reinstalling torch, but I still couldn't after reinstalling it. Then I tried versions 2.3.1 and 2.3.0, but they didn't work either. Can someone help me.

Device: MacBook Pro M1
System: MacOS Big Sur 11.1
Python 3.12.7

Here are the versions I have tried and switched to.

```bash
torch                   2.5.1
torchaudio              2.5.1
torchsde                0.2.6
torchvision             0.20.1
```

```bash
torch                   2.3.1
torchaudio              2.3.1
torchsde                0.2.6
torchvision             0.18.1
```

```bash
torch                   2.3.0
torchaudio              2.3.0
torchsde                0.2.6
torchvision             0.18.0
```

### Logs

```powershell
Traceback (most recent call last):
  File "/Users/serioshi/AI/ComfyUI/main.py", line 91, in <module>
    import execution
  File "/Users/serioshi/AI/ComfyUI/execution.py", line 13, in <module>
    import nodes
  File "/Users/serioshi/AI/ComfyUI/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/Users/serioshi/AI/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/Users/serioshi/AI/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/Users/serioshi/AI/ComfyUI/comfy/model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/Users/serioshi/AI/ComfyUI/comfy/model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/serioshi/miniconda3/lib/python3.12/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/Users/serioshi/miniconda3/lib/python3.12/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by LukeG89** [comment]
Have you followed these instructions?

https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#apple-mac-silicon

**Comment by fantasylion** [comment]
> 您是否遵循了这些说明？
> 
> https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#apple-mac-silicon

Yes, I operated according to this document

**Comment by renjixiang** [comment]
你的问题解决了吗?我也遇到同样的问题了，求解

**Comment by fantasylion** [comment]
> 你的问题解决了吗?我也遇到同样的问题了，求解

MacOS 版本升级到 15.1.1 就可以了

**Comment by ELSS-ZION** [comment]
I'm having the same issue too. I upgraded to 15.2, and it didn't fix anything.

> > 你的问题解决了吗?我也遇到同样的问题了，求解
> 
> MacOS 版本升级到 15.1.1 就可以了

**Comment by huongng105** [comment]
> I'm having the same issue too. I upgraded to 15.2, and it didn't fix anything.
> 
> > > 你的问题解决了吗?我也遇到同样的问题了，求解
> > 
> > 
> > MacOS 版本升级到 15.1.1 就可以了

me too, please help :(

**Comment by djaychela** [comment]
.. Just chiming in to say I've had the same issue:

`AssertionError: Torch not compiled with CUDA enabled`

After following the instructions - installed anaconda and pytorch-nightly, cloned the repo, installed the dependencies and ran main.py but still get the same error as when I tried the original app.

**Comment by huongng105** [comment]
i fixed the problem after running python main.py --cpu, then at the node which was causing the issue (in my case was the DownloadAndLoadFlorence2Model), i saw an option to switch between cpu and cuda, so i choosed cpu, then choosed the suitable models and that's it, problem sold for me, hope this'll help
