### ISSUE TITLE
Comfyui cannot load sdxl model after update

### ISSUE THREAD

**Issue by GuaishouDM1** [comfyanonymous/ComfyUI#5991]
### Expected Behavior

Before update everything seems to work with sdxl and sd 1.5. I utilisied only default nodes

### Actual Behavior

Now default chekpoint loader node outputs an error when sdxl load requested

### Steps to Reproduce

The output error looks like this: 
![image](https://github.com/user-attachments/assets/9a46364b-f28f-4e84-998f-461fd2ac4e30)

### Debug Logs

```powershell
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
got prompt
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 553, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 712, in load_checkpoint_guess_config
    out = load_state_dict_guess_config(sd, output_vae, output_clip, output_clipvision, embedding_directory, output_model, model_options, te_model_options=te_model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 752, in load_state_dict_guess_config
    model = model_config.get_model(sd, diffusion_model_prefix, device=inital_load_device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\supported_models.py", line 208, in get_model
    out = model_base.SDXL(self, model_type=self.model_type(state_dict, prefix), device=device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 380, in __init__
    super().__init__(model_config, model_type, device=device)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 110, in __init__
    self.diffusion_model = unet_model(**unet_config, device=device, operations=operations)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 788, in __init__
    get_attention_layer(
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 568, in get_attention_layer
    return SpatialTransformer(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 682, in __init__
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim[d],
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 682, in <listcomp>
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim[d],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 515, in __init__
    self.ff = FeedForward(inner_dim, dim_out=dim, dropout=dropout, glu=gated_ff, dtype=dtype, device=device, operations=operations)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 80, in __init__
    operations.Linear(inner_dim, dim_out, dtype=dtype, device=device)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 0.43 seconds
```

### Other

This behaviour appeared only after update, previously everything worked properly. I have a 16 gb of RAM and RTX 4060 ti with 16 gb VRAM

**Comment by frankyifei** [comment]
I had the same issue. So I go back to 2d5b3e0 which seems working as usual

**Comment by comfyanonymous** [comment]
Can I see the full logs?

**Comment by frankyifei** [comment]
My work flow is complex so I will describe it here, will try to make a minimal workflow later. 
My setup: 24GB ram,  3060 12gb Vram, 
Workflow: load flux Q8_0 GGUF, with a couple of loras, and model compile to speed up a little. The issue with GGUF and lora is they don't work with compile, so I found a solution from Kijai's KJNodes [this](https://github.com/kijai/ComfyUI-KJNodes/blob/973ceb6ca8b7525d54873805888ad690090d6b1e/nodes/model_optimization_nodes.py#L229) to apply lora to weight before compile, which works well as at 2d5b3e0. Now this solution broke after 2d5b3e0, Kijai updated his node, it worked again but extremely slow. 
The difference in log I noticed is this: 
```
Requested to load Flux
loaded completely 0.0 12119.509887695312 True
```

This maybe a issue from Kijai's node, but we really need a solution to apply loras to models weight directly instead of as object patch, it could be very useful in many ways, because GGUF model will slow down greatly with loras [link](https://github.com/city96/ComfyUI-GGUF/issues/36#issue-2471513366).

**Comment by scentilating1** [comment]
same here

**Comment by kulkesk** [comment]
Same problem here with AMD video card. Before update i could make hires double pass gens with SDXL with enough ram to spare for other programms. Now my oom killer freaks out because my 16 gb of ram is full to the max
