### ISSUE TITLE
 MAC STUDIO M1MAX  Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by qinxiaoyi-stack** [comfyanonymous/ComfyUI#6447]
### Your question

MAC STUDIO M1MAX run CogVideoX-5b-1.5 with ComfyUI, 
Use python3 main.py --force-fp16 --use-split-cross-attentio --cpu to start ComfyUI.
But always throw exception -- AssertionError: Torch not compiled with CUDA enabled.
I was use CPU to run is model ,
and check pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu  to reinstall torch with Mac . it is not work. 

if you has this bug , and you fixed it ,please tell  me how to fix this bug.

### Logs

```powershell
!!! Exception during processing !!! Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 722, in process
    latents = model["pipe"](
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 778, in __call__
    noise_pred = self.transformer(
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/custom_nodes/ComfyUI-CogVideoXWrapper/custom_cogvideox_transformer_3d.py", line 569, in forward
    emb = self.time_embedding(t_emb, timestep_cond)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/diffusers/models/embeddings.py", line 1304, in forward
    sample = self.linear_1(sample)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 355, in pre_forward
    set_module_tensor_to_device(
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 329, in set_module_tensor_to_device
    new_value = value.to(device)
  File "/Users/qinyi/Downloads/ComfyUI-0.3.10/.venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by ltdrdata** [comment]
Your issue still indicates that `torch` is installed with the CUDA version. It seems you reinstalled Torch in a different Python environment, not the one where ComfyUI is running.

**Comment by markyway** [comment]
any update on your problem? Facing the same on my apple M3 Max

**Comment by lancer1911** [comment]
I encountered the same issue while using a Mac mini with an M4 Pro chip and resolved it by making the following changes. I modified the file ComfyUI/custom_nodes/ComfyUI-Janus-Pro/nodes/image_generation.py, as follows:
``` python
import torch
import numpy as np
from PIL import Image

class JanusImageGeneration:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "model": ("JANUS_MODEL",),
                "processor": ("JANUS_PROCESSOR",),
                "prompt": ("STRING", {
                    "multiline": True,
                    "default": "A beautiful photo of"
                }),
                "seed": ("INT", {
                    "default": 666666666666666,
                    "min": 0,
                    "max": 0xffffffffffffffff
                }),
                "batch_size": ("INT", {
                    "default": 1,
                    "min": 1,
                    "max": 16
                }),
                "cfg_weight": ("FLOAT", {
                    "default": 5.0,
                    "min": 1.0,
                    "max": 10.0,
                    "step": 0.5
                }),
                "temperature": ("FLOAT", {
                    "default": 1.0,
                    "min": 0.1,
                    "max": 2.0,
                    "step": 0.1
                }),
                "top_p": ("FLOAT", {
                    "default": 0.95,
                    "min": 0.0,
                    "max": 1.0
                }),
            },
        }
    
    RETURN_TYPES = ("IMAGE",)
    RETURN_NAMES = ("images",)
    FUNCTION = "generate_images"
    CATEGORY = "Janus-Pro"

    def generate_images(self, model, processor, prompt, seed, batch_size=1, temperature=1.0, cfg_weight=5.0, top_p=0.95):
        try:
            from janus.models import MultiModalityCausalLM
        except ImportError:
            raise ImportError("Please install Janus using 'pip install -r requirements.txt'")

        # Set up device
        if torch.backends.mps.is_available():
            device = torch.device("mps")
            # Ensure model is on the correct device
            model = model.to(device)
            # MPS optimization settings
            torch.mps.empty_cache()
        elif torch.cuda.is_available():
            device = torch.device("cuda")
            model = model.to(device)
        else:
            device = torch.device("cpu")
            model = model.to(device)
            
        # Set random seed
        torch.manual_seed(seed)
        if device.type == "cuda":
            torch.cuda.manual_seed(seed)

        # Image generation parameters
        image_token_num = 576  # 24x24 patches
        img_size = 384  # Output image size
        patch_size = 16  # Size of each patch
        parallel_size = batch_size

        # Prepare conversation format
        conversation = [
            {
                "role": "<|User|>",
                "content": prompt,
            },
            {"role": "<|Assistant|>", "content": ""},
        ]

        try:
            # Prepare input
            sft_format = processor.apply_sft_template_for_multi_turn_prompts(
                conversations=conversation,
                sft_format=processor.sft_format,
                system_prompt="",
            )
            prompt = sft_format + processor.image_start_tag

            # Encode input text
            input_ids = processor.tokenizer.encode(prompt)
            input_ids = torch.LongTensor(input_ids).to(device)

            # Prepare conditional and unconditional inputs
            tokens = torch.zeros((parallel_size*2, len(input_ids)), dtype=torch.int32, device=device)
            for i in range(parallel_size*2):
                tokens[i, :] = input_ids
                if i % 2 != 0:  # Unconditional input
                    tokens[i, 1:-1] = processor.pad_id

            # Get text embeddings
            with torch.device(device):
                inputs_embeds = model.language_model.get_input_embeddings()(tokens)

            # Generate image tokens
            generated_tokens = torch.zeros((parallel_size, image_token_num), dtype=torch.int32, device=device)
            outputs = None

            # Autoregressive generation
            for i in range(image_token_num):
                with torch.device(device):
                    outputs = model.language_model.model(
                        inputs_embeds=inputs_embeds, 
                        use_cache=True, 
                        past_key_values=outputs.past_key_values if i != 0 else None
                    )
                    hidden_states = outputs.last_hidden_state
                    
                    # Get logits and apply CFG
                    logits = model.gen_head(hidden_states[:, -1, :])
                    logit_cond = logits[0::2, :]
                    logit_uncond = logits[1::2, :]
                    
                    logits = logit_uncond + cfg_weight * (logit_cond-logit_uncond)
                    probs = torch.softmax(logits / temperature, dim=-1)

                    # Sample next token
                    next_token = torch.multinomial(probs, num_samples=1)
                    generated_tokens[:, i] = next_token.squeeze(dim=-1)

                    # Prepare input for next step
                    next_token = torch.cat([next_token.unsqueeze(dim=1), next_token.unsqueeze(dim=1)], dim=1).view(-1)
                    img_embeds = model.prepare_gen_img_embeds(next_token)
                    inputs_embeds = img_embeds.unsqueeze(dim=1)

                # MPS synchronization
                if device.type == "mps":
                    torch.mps.synchronize()

            # Decode generated tokens to image
            with torch.device(device):
                dec = model.gen_vision_model.decode_code(
                    generated_tokens.to(dtype=torch.int32), 
                    shape=[parallel_size, 8, img_size//patch_size, img_size//patch_size]
                )
            
            # MPS synchronization
            if device.type == "mps":
                torch.mps.synchronize()
            
            # Convert to numpy for processing
            dec = dec.to(torch.float32).cpu().numpy()
            
            # Ensure BCHW format
            if dec.shape[1] != 3:
                dec = np.repeat(dec, 3, axis=1)
            
            # Convert from [-1,1] to [0,1] range
            dec = (dec + 1) / 2
            
            # Ensure values are in [0,1] range
            dec = np.clip(dec, 0, 1)
            
            # Convert to ComfyUI format [B,C,H,W] -> [B,H,W,C]
            dec = np.transpose(dec, (0, 2, 3, 1))
            
            # Convert to tensor
            images = torch.from_numpy(dec).float()
            
            # Ensure correct format
            assert images.ndim == 4 and images.shape[-1] == 3, f"Unexpected shape: {images.shape}"
            
            return (images,)
            
        except Exception as e:
            print(f"Error during generation: {str(e)}")
            raise e
        finally:
            # Clean up MPS cache
            if device.type == "mps":
                torch.mps.empty_cache()

    @classmethod
    def IS_CHANGED(cls, seed, **kwargs):
        return seed
```
It works for my Mac mini M4 Pro.

**Comment by DrewNeon** [comment]
@lancer1911 What a saviour! This solution works like a charm!

**Comment by chfilm** [comment]
I dont have the image_generation.py file nor the janus pro folder there but running into the same issue. help?

**Comment by polarNerd204** [comment]
ME TOO!!     I dont have the image_generation.py file nor the janus pro folder there but running into the same issue. help?
