### ISSUE TITLE
Extremely Slow Generation Speed on ComfyUI with L20 GPU

### ISSUE THREAD

**Issue by 2575044704** [comfyanonymous/ComfyUI#6467]
### Your question

I am running ComfyUI on an L20 GPU. However, I have noticed that the generation speed is extremely slow.

Under the same resolution, model, and sampler settings, ComfyUI's generation speed is approximately 1.6 it/s. In contrast, WebUI achieves a speed of around 6.2 it/s. ComfyUI's speed is only about a quarter of that of WebUI.

Furthermore, I have observed that during image generation, ComfyUI's GPU utilization only reaches around 70%, whereas WebUI consistently utilizes 100% of the GPU.

What could be the reason for this significant performance difference and the low GPU utilization in ComfyUI?

### Logs

```powershell
(venv) root@c-67860ca5-15678007-858cd604fec9:~/ComfyUI# python main.py
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-01-14 16:22:36.355
** Platform: Linux
** Python version: 3.10.14 (main, Oct 22 2024, 13:26:02) [GCC 11.4.0]
** Python executable: /root/ComfyUI/venv/bin/python
** ComfyUI Path: /root/ComfyUI
** User directory: /root/ComfyUI/user
** ComfyUI-Manager config path: /root/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /root/ComfyUI/user/comfyui.log

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

Prestartup times for custom nodes:
   1.2 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 45589 MB, total RAM 64489 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.29.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA L20 : cudaMallocAsync
Using xformers attention
[Prompt Server] web root: /root/ComfyUI/web
### Loading: ComfyUI-Manager (V3.7.4)
### ComfyUI Version: v0.3.10-52-g1f1c7b7 | Released on '2025-01-13'

Import times for custom nodes:
   0.0 seconds: /root/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load SDXLClipModel
loaded completely 9.5367431640625e+25 1560.802734375 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
Requested to load SDXL
loaded completely 9.5367431640625e+25 4897.0483474731445 True
 70%|███████████████████████████████████████████████████████████████████████████▌                                | 14/20 [00:08<00:03,  1.68it/s][ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.65it/s]
Requested to load AutoencoderKL
loaded completely 9.5367431640625e+25 159.55708122253418 True
Prompt executed in 15.36 seconds
got prompt
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.69it/s]
Prompt executed in 12.40 seconds
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
got prompt
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.69it/s]
Prompt executed in 12.36 seconds
got prompt
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.69it/s]
Prompt executed in 12.38 seconds
```

### Comfyui Log and GPU usage
![comfyui](https://github.com/user-attachments/assets/8130a2c6-1c3b-4949-8343-81bc6553c5bd)
![comfyuilog](https://github.com/user-attachments/assets/30a2f0c0-ac4c-46e9-a4a0-0da233f2c11e)

**Comment by comfyanonymous** [comment]
Post your workflow.

**Comment by 2575044704** [comment]
> Post your workflow.

**I use the ComfyUI default workflow**

**Comment by comfyanonymous** [comment]
Can you try disabling xformers? --disable-xformers

**Comment by 2575044704** [comment]
> Can you try disabling xformers? --disable-xformers

I tried, but the speed still doesn't improve significantly

**Comment by 2575044704** [comment]
> Can you try disabling xformers? --disable-xformers

I actually solved it, I used the `--disable-cuda-malloc`, and it works. The generation speed is now incredibly fast, almost 4x faster than before. Disabling xformers didn't help, but this did
