### ISSUE TITLE
TypeError: 'NoneType' object is not callable in SUPIR_conditioner

### ISSUE THREAD

**Issue by ho3ien123** [comfyanonymous/ComfyUI#6671]
### Expected Behavior

The SUPIR_conditioner node should execute without errors and correctly process input data.
The workflow should run smoothly without encountering a NoneType object is not callable error.
The process should complete successfully without running out of GPU memory.
All input data should be correctly processed and passed to the subsequent nodes.
The execution should not fail due to memory allocation issues, and PyTorch should manage GPU memory efficiently.

### Actual Behavior

When executing the SUPIR_conditioner node, a TypeError: 'NoneType' object is not callable error occurs.
The issue happens in nodes_v2.py at line 637.
The system also encounters HIP out of memory errors when running KSampler, stating that it tried to allocate 6.46 GiB, but only 3.35 GiB was free.
PyTorch has already allocated 16.97 GiB, with 127.91 MiB reserved but unallocated.
Even setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True does not resolve the memory fragmentation issue.

### Steps to Reproduce

Run ComfyUI on Windows using the portable version.
Load a workflow that includes the SUPIR_conditioner node.
Click Queue Prompt to start processing.
The following errors appear:
TypeError: 'NoneType' object is not callable for the SUPIR_conditioner node.
HIP out of memory error when running KSampler, indicating insufficient VRAM.
The process fails to complete due to these errors.

### Debug Logs

```powershell
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Loading weights to:  cpu
Diffusion using fp16
FETCH ComfyRegistry Data: 10/32
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Attempting to load SDXL model from node inputs
Requested to load SDXL
loaded completely 5680.8 4897.0483474731445 True
!!! Exception during processing !!! Failed to load SDXL model
Traceback (most recent call last):
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-supir\nodes_v2.py", line 906, in process
    if is_accelerate_available:
       ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_accelerate_available' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-supir\nodes_v2.py", line 918, in process
    raise Exception("Failed to load SDXL model")
Exception: Failed to load SDXL model

Prompt executed in 5.99 seconds
FETCH ComfyRegistry Data: 15/32
got prompt
Loading weights to:  cpu
Diffusion using fp16
Encoder using bf16
[Tiled VAE]: input_size: torch.Size([1, 3, 4224, 2976]), tile_size: 512, padding: 32
[Tiled VAE]: split to 9x6 = 54 tiles. Optimal tile size 512x480, original tile size 512x512
[Tiled VAE]: Executing Encoder Task Queue:  11%|███▉                               | 550/4914 [00:06<00:36, 120.40it/s]FETCH ComfyRegistry Data: 20/32
[Tiled VAE]: Executing Encoder Task Queue:  35%|███████████▉                      | 1717/4914 [00:14<00:15, 200.82it/s]FETCH ComfyRegistry Data: 25/32
[Tiled VAE]: Executing Encoder Task Queue: 100%|██████████████████████████████████| 4914/4914 [00:20<00:00, 239.61it/s]
[Tiled VAE]: Done in 20.894s, max VRAM alloc 751.366 MB
[Tiled VAE]: input_size: torch.Size([1, 4, 528, 372]), tile_size: 64, padding: 11
[Tiled VAE]: split to 8x6 = 48 tiles. Optimal tile size 64x64, original tile size 64x64
[Tiled VAE]: Executing Decoder Task Queue:  33%|███████████▎                      | 1959/5904 [00:02<00:05, 788.40it/s]FETCH ComfyRegistry Data: 30/32
[Tiled VAE]: Executing Decoder Task Queue:  50%|█████████████████▏                | 2981/5904 [00:07<00:13, 210.77it/s]FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
nightly_channel: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote
[Tiled VAE]: Executing Decoder Task Queue:  53%|██████████████████                | 3142/5904 [00:07<00:13, 207.28it/s] [DONE]
[Tiled VAE]: Executing Decoder Task Queue:  54%|██████████████████▏               | 3166/5904 [00:07<00:12, 213.08it/s][ComfyUI-Manager] All startup tasks have been completed.
[Tiled VAE]: Executing Decoder Task Queue: 100%|██████████████████████████████████| 5904/5904 [00:47<00:00, 124.39it/s]
[Tiled VAE]: Done in 47.869s, max VRAM alloc 1846.727 MB
captions:  [['']]
Batch captioning
!!! Exception during processing !!! 'NoneType' object is not callable
Traceback (most recent call last):
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-supir\nodes_v2.py", line 637, in condition
    _c, _uc = SUPIR_model.conditioner.get_unconditional_conditioning(cond, uncond)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-supir\sgm\modules\encoders\modules.py", line 190, in get_unconditional_conditioning
    c = self(batch_c)
        ^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-supir\sgm\modules\encoders\modules.py", line 211, in forward
    emb_out = embedder(batch[embedder.input_key])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cluudp’\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-supir\sgm\modules\encoders\modules.py", line 493, in forward
    batch_encoding = self.tokenizer(
                     ^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

Prompt executed in 70.17 seconds
```

**Comment by HerrNerdstromDRK** [comment]
I am receiving the same error...

**Comment by Jidis83** [comment]
Did anybody figure out what causes this? I've been fighting with it for two days and finally have my four base nodes (SUPIR,RGThree,KJNodes,Comfy_Essentials) all installed and cooperating on a new comfy install, but SUPIR still deadends at that when it gets to the conditioner. 

I used it all the time in my previous install, but tried to get teacache and a couple other things working and made a big mess that broke it, and haven't gotten it to run since. I'm running the current desktop ComfyUI 0.20.1 in Windows. Is there a specific version of any base components that it likes, or might it be a matter of rolling back to an older Comfy?

Thanks!

**Comment by cybertownboy** [comment]
I have the same problem. Juggernaught SUPIR-v0Q are SDXL, right?   <img width="1119" height="797" alt="Image" src="https://github.com/user-attachments/assets/6280aaae-8ba6-4924-a514-ecc90dd09592" /> Sometimes, just sometimes, I get another problem at the model loader stage, saying that it cannot load the model. I just toggle between Highram= True/False and the problem goes away. Strange. Also, I downloaded a new portable comfy just the other week, and this is when it broke.

**Comment by nut-pine** [comment]
Encounter the same problems:
 - SDXL models can't be uploaded (**you have to keep reselecting it each time**)
 - SUPIR Conditioner get "**TypeError: 'NoneType' object is not callable**"

For some reason **SUPIR First Stage (Denoiser)** can't do denoise for image and maybe this is cause that error in **SUPIR Conditioner** 

**SUPIR Upscale (Legacy)** - works fine.

UPD: If I changed **SUPIR Model Loader (v2)** on **SUPIR Model Loader (Legacy)**  there is no "**TypeError: 'NoneType' object is not callable"** in **SUPIR Conditioner** and everyhting on sheme works correctly. 

<img width="1407" height="724" alt="Image" src="https://github.com/user-attachments/assets/8635911e-5edf-4c5b-84eb-f6503be70355" />

**Comment by cybertownboy** [comment]
I tried switching to Legacy, but instead I got a "Not implemented ERROR"

**Comment by nut-pine** [comment]
> I tried switching to Legacy, but instead I got a "Not implemented ERROR"

Hmmm, I'don't have one. I use python 3.12.7 and Torch version: 2.10.0+cu130

**Comment by cybertownboy** [comment]
> > I tried switching to Legacy, but instead I got a "Not implemented ERROR"
> 
> Hmmm, I'don't have one. I use python 3.12.7 and Torch version: 2.10.0+cu130

According to my log in portable: Python version: 3.13.12 
ComfyUI version: 0.22.2
pytorch version: 2.11.0+cu130

So we have a different version of Python. This is the version of Python that portable came with. I read somewhere that there is a new version of Comfy portable coming in June. Perhaps that version will solve my problem? I am not in any hurry.

**Comment by nut-pine** [comment]
> > > I tried switching to Legacy, but instead I got a "Not implemented ERROR"
> > 
> > 
> > Hmmm, I'don't have one. I use python 3.12.7 and Torch version: 2.10.0+cu130
> 
> According to my log in portable: Python version: 3.13.12 ComfyUI version: 0.22.2 pytorch version: 2.11.0+cu130
> 
> So we have a different version of Python. This is the version of Python that portable came with. I read somewhere that there is a new version of Comfy portable coming in June. Perhaps that version will solve my problem? I am not in any hurry.

That might be the issue, but I'm not sure. Well, most likely, you shouldn't wait for the new version—you should test it on an older one instead. 

Try downloading a this version: "Portable with PyTorch CUDA 12.6 and Python 3.12" https://docs.comfy.org/installation/comfyui_portable_windows and run it, just to test it out.

As I understand it, it’s common practice to have a few portable versions of ComfyUI.

**Comment by cybertownboy** [comment]
> > > > I tried switching to Legacy, but instead I got a "Not implemented ERROR"
> > > 
> > > 
> > > Hmmm, I'don't have one. I use python 3.12.7 and Torch version: 2.10.0+cu130
> > 
> > 
> > According to my log in portable: Python version: 3.13.12 ComfyUI version: 0.22.2 pytorch version: 2.11.0+cu130
> > So we have a different version of Python. This is the version of Python that portable came with. I read somewhere that there is a new version of Comfy portable coming in June. Perhaps that version will solve my problem? I am not in any hurry.
> 
> That might be the issue, but I'm not sure. Well, most likely, you shouldn't wait for the new version—you should test it on an older one instead.
> 
> Try downloading a this version: "Portable with PyTorch CUDA 12.6 and Python 3.12" https://docs.comfy.org/installation/comfyui_portable_windows and run it, just to test it out.
> 
> As I understand it, it’s common practice to have a few portable versions of ComfyUI.

I tried. I could not even find supir among the templates there in  "Portable with PyTorch CUDA 12.6 and Python 3.12" , and after copying models and custom nodes from my newer portable, comfy did not recognize any of those nodes.

**Comment by nut-pine** [comment]
> > > > > I tried switching to Legacy, but instead I got a "Not implemented ERROR"
> > > > 
> > > > 
> > > > Hmmm, I'don't have one. I use python 3.12.7 and Torch version: 2.10.0+cu130
> > > 
> > > 
> > > According to my log in portable: Python version: 3.13.12 ComfyUI version: 0.22.2 pytorch version: 2.11.0+cu130
> > > So we have a different version of Python. This is the version of Python that portable came with. I read somewhere that there is a new version of Comfy portable coming in June. Perhaps that version will solve my problem? I am not in any hurry.
> > 
> > 
> > That might be the issue, but I'm not sure. Well, most likely, you shouldn't wait for the new version—you should test it on an older one instead.
> > Try downloading a this version: "Portable with PyTorch CUDA 12.6 and Python 3.12" https://docs.comfy.org/installation/comfyui_portable_windows and run it, just to test it out.
> > As I understand it, it’s common practice to have a few portable versions of ComfyUI.
> 
> I tried. I could not even find supir among the templates there in "Portable with PyTorch CUDA 12.6 and Python 3.12" , and after copying models and custom nodes from my newer portable, comfy did not recognize any of those nodes.

Are you download them from Manager, they called ComfyUI-SUPIR? I have the same comfy ver. "PyTorch CUDA 12.6 and Python 3.12" and here all these nodes.

<img width="1654" height="793" alt="Image" src="https://github.com/user-attachments/assets/be782a37-b870-4a98-806a-1603d0b33191" />

<img width="1165" height="738" alt="Image" src="https://github.com/user-attachments/assets/819b464a-42fc-47d0-9ebf-8e30199f1311" />

**Comment by cybertownboy** [comment]
@nut-pine  It seems copying from the more modern version did not work, so I reinstalled a dozen things and then it recognized all nodes. It seems these nodes are different for each setup. Anyway, I started and got a few new problems . First, it could not load the SDXL model. Surely they dont have different models for each setup? That would be insane. Anyway, I clicked few times, and it went on to the next node only for the next error. "torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device".

**Comment by nut-pine** [comment]
> [@nut-pine](https://github.com/nut-pine) It seems copying from the more modern version did not work, so I reinstalled a dozen things and then it recognized all nodes. It seems these nodes are different for each setup. Anyway, I started and got a few new problems . First, it could not load the SDXL model. Surely they dont have different models for each setup? That would be insane. Anyway, I clicked few times, and it went on to the next node only for the next error. "torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device".

Man, you're doing something wrong.

1. Uninstall this version completely and extract clean version (this one i mean: PyTorch CUDA 12.6 and Python 3.12)

2. Then in custom nodes (go to the custom_nodes folder and type "cmd" in the line where the file path is specified) using git clone
download Manager `git clone https://github.com/Comfy-Org/ComfyUI-Manager.git` you have to install git, if you don't have it. 

3. Once you've installed the manager, install **Supir** nodes from it. Then download this model https://huggingface.co/Kijai/SUPIR_pruned/blob/main/SUPIR-v0Q_fp16.safetensors and put it inside checkpoints (I recommend create sub_folder Supir inside checkpoints and put it there)

4. Download any SDXL model and place it in the checkpoint. For examples this one [RealVisXL V4.0 (Baked Vae)](https://civitai.com/models/139562/realvisxl-v50?modelVersionId=344487)

That's it, it's enough for testing SUPIR. Then try **SUPIR Upscale (Legacy)** node. 

I don't know how much VRAM you have, but if you have 8GB then in  **SUPIR Upscale (Legacy)** enable fp8 unet, and use for testing these paramaters (attached images) 

<img width="935" height="771" alt="Image" src="https://github.com/user-attachments/assets/870a3182-9d0f-43fe-b59c-f490c153da97" />

**Comment by cybertownboy** [comment]
Thank you for your suggestions.

The answer came to me from KIJAI. There is a new SUPIR embedded in the new Comfy, exemplified in his workflow native_supir_example1, and it works like a charm :) 

There is a link to the workflow here:
https://github.com/Comfy-Org/ComfyUI/pull/13250

**Comment by nut-pine** [comment]
> Thank you for your suggestions.
> 
> The answer came to me from KIJAI. There is a new SUPIR embedded in the new Comfy, exemplified in his workflow native_supir_example1, and it works like a charm :)
> 
> There is a link to the workflow here: [#13250](https://github.com/Comfy-Org/ComfyUI/pull/13250)

Ohh, thanks for sharing;) Did not know about that workflow

**Comment by nailld** [comment]
我更新了版本，重启就可以了，不知道是不是这原因，因为昨天我用了都正常
