### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by MarcinSoj** [comfyanonymous/ComfyUI#6679]
### Expected Behavior

Problem after updating ComfyUI using : update_comfyui_and_python_dependencies.bat. Then when i open it with :run_nvidia_gpu.bat it shows me this error. There was no problem when i checked it 2 weeks ago. 

### Actual Behavior

c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-02-02 19:05:50.830
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\python_embeded\python.exe
** ComfyUI Path: c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI
** User directory: C:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\user
** ComfyUI-Manager config path: C:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: C:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   4.7 seconds: C:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\main.py", line 136, in <module>
    import execution
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\comfy\sd.py", line 6, in <module>
    from comfy import model_management
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\comfy\model_management.py", line 166, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\comfy\model_management.py", line 129, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 971, in current_device
    _lazy_init()
  File "c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

c:\A\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu>pause
Press any key to continue . . .

Problem after updating ComfyUI using : update_comfyui_and_python_dependencies.bat. Then when i open it with :run_nvidia_gpu.bat it shows me this error. There was no problem when i checked it 2 weeks ago. 

### Steps to Reproduce

Run update and open: run_nvidia_gpu.bat

### Debug Logs

```powershell
Do not know how to get Debug because comfyui is not opening.
```

**Comment by MarcinSoj** [comment]
Tried to update again and it is showing : ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albucore 0.0.13 requires numpy<2,>=1.24.4, but you have numpy 2.2.2 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.2 which is incompatible.
Successfully installed numpy-2.2.2. 

Have no idea how to fix this.

**Comment by LukeG89** [comment]
To solve the Pytorch issue, you have to reinstall it. 

Open terminal inside **python_embeded** folder and:

Run this command to uninstall it:
```
.\python.exe -m pip uninstall torch torchvision torchaudio
```
Then, this command to install the latest Pytorch with CUDA 12.6:
```
.\python.exe -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu126
```
Then, to solve the Numpy issue, you have to downgrade it to 1.26.4 with this command:
```
.\python.exe -m pip install --force-reinstall numpy==1.26.4
```

Anyways, the problem you encountered is due to the outdated link inside `update_comfyui_and_python_dependencies.bat`. Your installation seems pretty old (with cu121), so the link inside will install pytorch with cu121.

**Comment by MarcinSoj** [comment]
Thank you very much !!!! 

It is working now !! We can close this thread as resolved 🔥
