### ISSUE TITLE
Allocation on device

### ISSUE THREAD

**Issue by lukaszbel** [comfyanonymous/ComfyUI#6693]
### Expected Behavior

After last update I cannot run my workflows. I got Allocation on device error.

 **ComfyUI Version:** 0.3.13

### Actual Behavior

CAn run my pipeline, I got error.

### Steps to Reproduce

Run the pipeline.

### Debug Logs

```powershell
Manager



1

torch.OutOfMemoryError 11 DualCLIPLoader
The reference sampling implementation auto adjusts the shift value based on the resolution, if you don't want this you can just bypass (CTRL-B) this ModelSamplingFlux node.

text
DualCLIPLoader
Allocation on device


# ComfyUI Error Report
## Error Details
- **Node ID:** 11
- **Node Type:** DualCLIPLoader
- **Exception Type:** torch.OutOfMemoryError
- **Exception Message:** Allocation on device 
## Stack Trace

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 988, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path1, clip_path2], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 666, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 806, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 98, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 71, in __init__
    super().__init__(dtype_t5=dtype_t5, device=device, dtype=dtype, model_options=model_options)

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 40, in __init__
    self.t5xxl = comfy.text_encoders.sd3_clip.T5XXLModel(device=device, dtype=dtype_t5, model_options=model_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\sd3_clip.py", line 18, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config=textmodel_json_config, dtype=dtype, special_tokens={"end": 1, "pad": 0}, model_class=comfy.text_encoders.t5.T5, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 114, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 232, in __init__
    self.encoder = T5Stack(self.num_layers, model_dim, inner_dim, config_dict["d_ff"], config_dict["dense_act_fn"], config_dict["is_gated_act"], config_dict["num_heads"], config_dict["model_type"] != "umt5", dtype, device, operations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 197, in __init__
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0)), dtype=dtype, device=device, operations=operations) for i in range(num_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 185, in __init__
    self.layer.append(T5LayerFF(model_dim, ff_dim, ff_activation, gated_act, dtype, device, operations))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 57, in __init__
    self.DenseReluDense = T5DenseGatedActDense(model_dim, ff_dim, ff_activation, dtype, device, operations)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 40, in __init__
    self.wi_1 = operations.Linear(model_dim, ff_dim, bias=False, dtype=dtype, device=device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\pinokio\api\Comfyui\.venv\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)


## System Information
- **ComfyUI Version:** 0.3.13
- **Arguments:** C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py --user-directory C:\pinokio\api\Comfyui\user --input-directory C:\pinokio\api\Comfyui\input --output-directory C:\pinokio\api\Comfyui\output --front-end-root C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app --extra-model-paths-config C:\Users\Łukasz\AppData\Roaming\ComfyUI\extra_models_config.yaml --port 8000 --listen 127.0.0.1
- **OS:** nt
- **Python Version:** 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 3064089970
  - **Torch VRAM Total:** 12415139840
  - **Torch VRAM Free:** 48278912

## Logs

2025-02-04T02:23:39.138371 - Adding extra search path checkpoints C:\pinokio\api\Comfyui\models\checkpoints\
2025-02-04T02:23:39.138371 - Adding extra search path classifiers C:\pinokio\api\Comfyui\models\classifiers\
2025-02-04T02:23:39.138371 - Adding extra search path clip C:\pinokio\api\Comfyui\models\clip\
2025-02-04T02:23:39.138371 - Adding extra search path clip_vision C:\pinokio\api\Comfyui\models\clip_vision\
2025-02-04T02:23:39.138371 - Adding extra search path configs C:\pinokio\api\Comfyui\models\configs\
2025-02-04T02:23:39.138371 - Adding extra search path controlnet C:\pinokio\api\Comfyui\models\controlnet\
2025-02-04T02:23:39.138371 - Adding extra search path diffusers C:\pinokio\api\Comfyui\models\diffusers\
2025-02-04T02:23:39.138371 - Adding extra search path diffusion_models C:\pinokio\api\Comfyui\models\diffusion_models\
2025-02-04T02:23:39.138371 - Adding extra search path embeddings C:\pinokio\api\Comfyui\models\embeddings\
2025-02-04T02:23:39.138371 - Adding extra search path gligen C:\pinokio\api\Comfyui\models\gligen\
2025-02-04T02:23:39.138371 - Adding extra search path hypernetworks C:\pinokio\api\Comfyui\models\hypernetworks\
2025-02-04T02:23:39.138371 - Adding extra search path loras C:\pinokio\api\Comfyui\models\loras\
2025-02-04T02:23:39.138371 - Adding extra search path photomaker C:\pinokio\api\Comfyui\models\photomaker\
2025-02-04T02:23:39.138371 - Adding extra search path style_models C:\pinokio\api\Comfyui\models\style_models\
2025-02-04T02:23:39.138371 - Adding extra search path unet C:\pinokio\api\Comfyui\models\unet\
2025-02-04T02:23:39.138371 - Adding extra search path upscale_models C:\pinokio\api\Comfyui\models\upscale_models\
2025-02-04T02:23:39.138371 - Adding extra search path vae C:\pinokio\api\Comfyui\models\vae\
2025-02-04T02:23:39.138371 - Adding extra search path vae_approx C:\pinokio\api\Comfyui\models\vae_approx\
2025-02-04T02:23:39.138371 - Adding extra search path animatediff_models C:\pinokio\api\Comfyui\models\animatediff_models\
2025-02-04T02:23:39.138371 - Adding extra search path animatediff_motion_lora C:\pinokio\api\Comfyui\models\animatediff_motion_lora\
2025-02-04T02:23:39.138371 - Adding extra search path animatediff_video_formats C:\pinokio\api\Comfyui\models\animatediff_video_formats\
2025-02-04T02:23:39.138371 - Adding extra search path ipadapter C:\pinokio\api\Comfyui\models\ipadapter\
2025-02-04T02:23:39.138371 - Adding extra search path liveportrait C:\pinokio\api\Comfyui\models\liveportrait\
2025-02-04T02:23:39.138371 - Adding extra search path insightface C:\pinokio\api\Comfyui\models\insightface\
2025-02-04T02:23:39.138371 - Adding extra search path layerstyle C:\pinokio\api\Comfyui\models\layerstyle\
2025-02-04T02:23:39.138371 - Adding extra search path LLM C:\pinokio\api\Comfyui\models\LLM\
2025-02-04T02:23:39.138371 - Adding extra search path Joy_caption C:\pinokio\api\Comfyui\models\Joy_caption\
2025-02-04T02:23:39.138371 - Adding extra search path sams C:\pinokio\api\Comfyui\models\sams\
2025-02-04T02:23:39.138371 - Adding extra search path blip C:\pinokio\api\Comfyui\models\blip\
2025-02-04T02:23:39.138371 - Adding extra search path CogVideo C:\pinokio\api\Comfyui\models\CogVideo\
2025-02-04T02:23:39.138371 - Adding extra search path xlabs C:\pinokio\api\Comfyui\models\xlabs\
2025-02-04T02:23:39.138371 - Adding extra search path instantid C:\pinokio\api\Comfyui\models\instantid\
2025-02-04T02:23:39.138371 - Adding extra search path custom_nodes C:\pinokio\api\Comfyui\custom_nodes/
2025-02-04T02:23:39.138371 - Adding extra search path download_model_base C:\pinokio\api\Comfyui\models
2025-02-04T02:23:39.138371 - Setting output directory to: C:\pinokio\api\Comfyui\output
2025-02-04T02:23:39.138371 - Setting input directory to: C:\pinokio\api\Comfyui\input
2025-02-04T02:23:39.138371 - Setting user directory to: C:\pinokio\api\Comfyui\user
2025-02-04T02:23:39.149057 - [START] Security scan2025-02-04T02:23:39.149057 - 
2025-02-04T02:23:39.922718 - [DONE] Security scan2025-02-04T02:23:39.922718 - 
2025-02-04T02:23:40.022829 - ## ComfyUI-Manager: installing dependencies done.2025-02-04T02:23:40.022829 - 
2025-02-04T02:23:40.022829 - ** ComfyUI startup time:2025-02-04T02:23:40.022829 -  2025-02-04T02:23:40.022829 - 2025-02-04 02:23:40.0228292025-02-04T02:23:40.022829 - 
2025-02-04T02:23:40.044257 - ** Platform:2025-02-04T02:23:40.044257 -  2025-02-04T02:23:40.044257 - Windows2025-02-04T02:23:40.044257 - 
2025-02-04T02:23:40.044257 - ** Python version:2025-02-04T02:23:40.044257 -  2025-02-04T02:23:40.044257 - 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]2025-02-04T02:23:40.044257 - 
2025-02-04T02:23:40.044257 - ** Python executable:2025-02-04T02:23:40.044257 -  2025-02-04T02:23:40.044257 - C:\pinokio\api\Comfyui\.venv\Scripts\python.exe2025-02-04T02:23:40.044257 - 
2025-02-04T02:23:40.044257 - ** ComfyUI Path:2025-02-04T02:23:40.044257 -  2025-02-04T02:23:40.044257 - C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-02-04T02:23:40.044257 - 
2025-02-04T02:23:40.044257 - ** Log path:2025-02-04T02:23:40.044257 -  2025-02-04T02:23:40.044257 - C:\pinokio\api\Comfyui\comfyui.log2025-02-04T02:23:40.044257 - 
2025-02-04T02:23:40.976823 - 
Prestartup times for custom nodes:
2025-02-04T02:23:40.976823 -    1.8 seconds: C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-02-04T02:23:40.976823 - 
2025-02-04T02:23:42.378469 - Checkpoint files will always be loaded safely.
2025-02-04T02:23:42.457441 - Total VRAM 16376 MB, total RAM 32607 MB
2025-02-04T02:23:42.457441 - pytorch version: 2.5.1+cu121
2025-02-04T02:23:42.458434 - Set vram state to: NORMAL_VRAM
2025-02-04T02:23:42.458434 - Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
2025-02-04T02:23:43.452610 - Using pytorch attention
2025-02-04T02:23:44.606752 - ComfyUI version: 0.3.13
2025-02-04T02:23:44.638027 - [Prompt Server] web root: C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
2025-02-04T02:23:45.415572 - [34m[ComfyUI-Easy-Use] server: [0mv1.2.7 [92mLoaded[0m2025-02-04T02:23:45.415572 - 
2025-02-04T02:23:45.415572 - [34m[ComfyUI-Easy-Use] web root: [0mC:\pinokio\api\Comfyui\custom_nodes\ComfyUI-Easy-Use\web_version/v2 [92mLoaded[0m2025-02-04T02:23:45.415572 - 
2025-02-04T02:23:45.459578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-LTXVideo
2025-02-04T02:23:45.459578 - MultiGPU: Found ComfyUI-LTXVideo, creating compatible MultiGPU nodes
2025-02-04T02:23:45.459578 - MultiGPU: Registered LTXVLoaderMultiGPU
2025-02-04T02:23:45.459578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-Florence2
2025-02-04T02:23:45.460578 - MultiGPU: Module ComfyUI-Florence2 not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/comfyui-florence2
2025-02-04T02:23:45.460578 - MultiGPU: Module comfyui-florence2 not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/ComfyUI_bitsandbytes_NF4
2025-02-04T02:23:45.460578 - MultiGPU: Module ComfyUI_bitsandbytes_NF4 not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/comfyui_bitsandbytes_nf4
2025-02-04T02:23:45.460578 - MultiGPU: Module comfyui_bitsandbytes_nf4 not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/x-flux-comfyui
2025-02-04T02:23:45.460578 - MultiGPU: Module x-flux-comfyui not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/x-flux-comfyui
2025-02-04T02:23:45.460578 - MultiGPU: Module x-flux-comfyui not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-MMAudio
2025-02-04T02:23:45.460578 - MultiGPU: Module ComfyUI-MMAudio not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/comfyui-mmaudio
2025-02-04T02:23:45.460578 - MultiGPU: Module comfyui-mmaudio not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-GGUF
2025-02-04T02:23:45.460578 - MultiGPU: Found ComfyUI-GGUF, creating compatible MultiGPU nodes
2025-02-04T02:23:45.460578 - MultiGPU: Registered UnetLoaderGGUFMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered UnetLoaderGGUFDisTorchMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered UnetLoaderGGUFAdvancedMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered UnetLoaderGGUFAdvancedDisTorchMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered CLIPLoaderGGUFMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered CLIPLoaderGGUFDisTorchMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered DualCLIPLoaderGGUFMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered DualCLIPLoaderGGUFDisTorchMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered TripleCLIPLoaderGGUFMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Registered TripleCLIPLoaderGGUFDisTorchMultiGPU
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/PuLID_ComfyUI
2025-02-04T02:23:45.460578 - MultiGPU: Module PuLID_ComfyUI not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/pulid_comfyui
2025-02-04T02:23:45.460578 - MultiGPU: Module pulid_comfyui not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-HunyuanVideoWrapper
2025-02-04T02:23:45.460578 - MultiGPU: Module ComfyUI-HunyuanVideoWrapper not found - skipping
2025-02-04T02:23:45.460578 - MultiGPU: Checking for module at C:\pinokio\api\Comfyui\custom_nodes/comfyui-hunyuanvideowrapper
2025-02-04T02:23:45.461578 - MultiGPU: Module comfyui-hunyuanvideowrapper not found - skipping
2025-02-04T02:23:45.461578 - MultiGPU: Registration complete. Final mappings: DeviceSelectorMultiGPU, HunyuanVideoEmbeddingsAdapter, UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU, LTXVLoaderMultiGPU, UnetLoaderGGUFMultiGPU, UnetLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFAdvancedMultiGPU, UnetLoaderGGUFAdvancedDisTorchMultiGPU, CLIPLoaderGGUFMultiGPU, CLIPLoaderGGUFDisTorchMultiGPU, DualCLIPLoaderGGUFMultiGPU, DualCLIPLoaderGGUFDisTorchMultiGPU, TripleCLIPLoaderGGUFMultiGPU, TripleCLIPLoaderGGUFDisTorchMultiGPU
2025-02-04T02:23:45.492733 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\pinokio\api\Comfyui\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2025-02-04T02:23:45.492733 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2025-02-04T02:23:45.492733 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2025-02-04T02:23:45.700918 - C:\pinokio\api\Comfyui\custom_nodes/comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2025-02-04T02:23:45.758753 - 
2025-02-04T02:23:45.758753 - [92m[rgthree-comfy] Loaded 42 epic nodes. 🎉[00m2025-02-04T02:23:45.758753 - 
2025-02-04T02:23:45.758753 - 
2025-02-04T02:23:46.364191 - [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m2025-02-04T02:23:46.364191 - 
2025-02-04T02:23:46.364191 - [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `C:\pinokio\api\Comfyui\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m2025-02-04T02:23:46.364191 - 
2025-02-04T02:23:46.838577 - [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m220[0m [32mnodes successfully.[0m2025-02-04T02:23:46.838577 - 
2025-02-04T02:23:46.838577 - 
	[3m[93m"Art enables us to find ourselves and lose ourselves at the same time."[0m[3m - Thomas Merton[0m
2025-02-04T02:23:46.838577 - 
2025-02-04T02:23:46.847537 - ### Loading: ComfyUI-Manager (V2.55.3)2025-02-04T02:23:46.847537 - 
2025-02-04T02:23:46.848536 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)2025-02-04T02:23:46.849536 - 
2025-02-04T02:23:46.852549 - 
Import times for custom nodes:
2025-02-04T02:23:46.852549 -    0.0 seconds: C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-02-04T02:23:46.852549 -    0.0 seconds: C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-MultiGPU
2025-02-04T02:23:46.852549 -    0.0 seconds: C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-GGUF
2025-02-04T02:23:46.852549 -    0.0 seconds: C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-02-04T02:23:46.852549 -    0.0 seconds: C:\pinokio\api\Comfyui\custom_nodes/rgthree-comfy
2025-02-04T02:23:46.852549 -    0.0 seconds: C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-VideoHelperSuite
2025-02-04T02:23:46.852549 -    0.0 seconds: C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-LTXVideo
2025-02-04T02:23:46.852549 -    0.2 seconds: C:\pinokio\api\Comfyui\custom_nodes/comfyui_controlnet_aux
2025-02-04T02:23:46.852549 -    0.3 seconds: C:\pinokio\api\Comfyui\custom_nodes/ComfyUI-Easy-Use
2025-02-04T02:23:46.852549 -    1.1 seconds: C:\pinokio\api\Comfyui\custom_nodes/was-node-suite-comfyui
2025-02-04T02:23:46.852549 - 
2025-02-04T02:23:46.922922 - Starting server

2025-02-04T02:23:46.922922 - To see the GUI go to: http://127.0.0.1:8000
2025-02-04T02:23:46.964795 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2025-02-04T02:23:46.964795 - 
2025-02-04T02:23:46.974801 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2025-02-04T02:23:46.974801 - 
2025-02-04T02:23:46.992832 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-02-04T02:23:46.992832 - 
2025-02-04T02:23:47.025908 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-02-04T02:23:47.025908 - 
2025-02-04T02:23:47.041856 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-02-04T02:23:47.041856 - 
2025-02-04T02:23:47.662417 - FETCH DATA from: C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2025-02-04T02:23:47.662417 - 2025-02-04T02:23:47.669815 -  [DONE]2025-02-04T02:23:47.669815 - 
2025-02-04T02:24:23.994571 - got prompt
2025-02-04T02:24:23.994571 - Using pytorch attention in VAE
2025-02-04T02:24:23.994571 - Using pytorch attention in VAE
2025-02-04T02:24:24.076314 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-02-04T02:24:24.125437 - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2025-02-04T02:24:24.125437 - model_type FLUX
2025-02-04T02:24:37.675294 - !!! Exception during processing !!! Allocation on device 
2025-02-04T02:24:37.707647 - Traceback (most recent call last):
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 988, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path1, clip_path2], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 666, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 806, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 98, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 71, in __init__
    super().__init__(dtype_t5=dtype_t5, device=device, dtype=dtype, model_options=model_options)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 40, in __init__
    self.t5xxl = comfy.text_encoders.sd3_clip.T5XXLModel(device=device, dtype=dtype_t5, model_options=model_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\sd3_clip.py", line 18, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config=textmodel_json_config, dtype=dtype, special_tokens={"end": 1, "pad": 0}, model_class=comfy.text_encoders.t5.T5, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 114, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 232, in __init__
    self.encoder = T5Stack(self.num_layers, model_dim, inner_dim, config_dict["d_ff"], config_dict["dense_act_fn"], config_dict["is_gated_act"], config_dict["num_heads"], config_dict["model_type"] != "umt5", dtype, device, operations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 197, in __init__
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0)), dtype=dtype, device=device, operations=operations) for i in range(num_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 185, in __init__
    self.layer.append(T5LayerFF(model_dim, ff_dim, ff_activation, gated_act, dtype, device, operations))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 57, in __init__
    self.DenseReluDense = T5DenseGatedActDense(model_dim, ff_dim, ff_activation, dtype, device, operations)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 40, in __init__
    self.wi_1 = operations.Linear(model_dim, ff_dim, bias=False, dtype=dtype, device=device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pinokio\api\Comfyui\.venv\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
torch.OutOfMemoryError: Allocation on device 

2025-02-04T02:24:37.708211 - Got an OOM, unloading all loaded models.
2025-02-04T02:24:37.725500 - Prompt executed in 13.73 seconds
2025-02-04T02:26:28.026931 - got prompt
2025-02-04T02:26:28.772531 - !!! Exception during processing !!! Allocation on device 
2025-02-04T02:26:28.784364 - Traceback (most recent call last):
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 988, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path1, clip_path2], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 666, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 806, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 98, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 71, in __init__
    super().__init__(dtype_t5=dtype_t5, device=device, dtype=dtype, model_options=model_options)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 40, in __init__
    self.t5xxl = comfy.text_encoders.sd3_clip.T5XXLModel(device=device, dtype=dtype_t5, model_options=model_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\sd3_clip.py", line 18, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config=textmodel_json_config, dtype=dtype, special_tokens={"end": 1, "pad": 0}, model_class=comfy.text_encoders.t5.T5, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 114, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 232, in __init__
    self.encoder = T5Stack(self.num_layers, model_dim, inner_dim, config_dict["d_ff"], config_dict["dense_act_fn"], config_dict["is_gated_act"], config_dict["num_heads"], config_dict["model_type"] != "umt5", dtype, device, operations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 197, in __init__
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0)), dtype=dtype, device=device, operations=operations) for i in range(num_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 185, in __init__
    self.layer.append(T5LayerFF(model_dim, ff_dim, ff_activation, gated_act, dtype, device, operations))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 57, in __init__
    self.DenseReluDense = T5DenseGatedActDense(model_dim, ff_dim, ff_activation, dtype, device, operations)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 40, in __init__
    self.wi_1 = operations.Linear(model_dim, ff_dim, bias=False, dtype=dtype, device=device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pinokio\api\Comfyui\.venv\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
torch.OutOfMemoryError: Allocation on device 

2025-02-04T02:26:28.786368 - Got an OOM, unloading all loaded models.
2025-02-04T02:26:28.802955 - Prompt executed in 0.78 seconds
2025-02-04T02:28:17.916508 - got prompt
2025-02-04T02:28:18.439186 - !!! Exception during processing !!! Allocation on device 
2025-02-04T02:28:18.439186 - Traceback (most recent call last):
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 988, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path1, clip_path2], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 666, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 806, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 98, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 71, in __init__
    super().__init__(dtype_t5=dtype_t5, device=device, dtype=dtype, model_options=model_options)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\flux.py", line 40, in __init__
    self.t5xxl = comfy.text_encoders.sd3_clip.T5XXLModel(device=device, dtype=dtype_t5, model_options=model_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\sd3_clip.py", line 18, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config=textmodel_json_config, dtype=dtype, special_tokens={"end": 1, "pad": 0}, model_class=comfy.text_encoders.t5.T5, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 114, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 232, in __init__
    self.encoder = T5Stack(self.num_layers, model_dim, inner_dim, config_dict["d_ff"], config_dict["dense_act_fn"], config_dict["is_gated_act"], config_dict["num_heads"], config_dict["model_type"] != "umt5", dtype, device, operations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 197, in __init__
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0)), dtype=dtype, device=device, operations=operations) for i in range(num_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 185, in __init__
    self.layer.append(T5LayerFF(model_dim, ff_dim, ff_activation, gated_act, dtype, device, operations))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 57, in __init__
    self.DenseReluDense = T5DenseGatedActDense(model_dim, ff_dim, ff_activation, dtype, device, operations)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Łukasz\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\text_encoders\t5.py", line 40, in __init__
    self.wi_1 = operations.Linear(model_dim, ff_dim, bias=False, dtype=dtype, device=device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pinokio\api\Comfyui\.venv\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
torch.OutOfMemoryError: Allocation on device 

2025-02-04T02:28:18.441230 - Got an OOM, unloading all loaded models.
2025-02-04T02:28:18.454593 - Prompt executed in 0.55 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"last_node_id":41,"last_link_id":130,"nodes":[{"id":16,"type":"KSamplerSelect","pos":[480,912],"size":[315,58],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[19],"shape":3,"label":"SAMPLER"}],"properties":{"Node name for S&R":"KSamplerSelect"},"widgets_values":["euler"]},{"id":30,"type":"ModelSamplingFlux","pos":[480,1152],"size":[315,130],"flags":{},"order":9,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":56,"slot_index":0,"label":"model"},{"name":"width","type":"INT","link":115,"slot_index":1,"widget":{"name":"width"},"label":"width"},{"name":"height","type":"INT","link":114,"slot_index":2,"widget":{"name":"height"},"label":"height"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[55],"slot_index":0,"shape":3,"label":"MODEL"}],"properties":{"Node name for S&R":"ModelSamplingFlux"},"widgets_values":[1.15,0.5,1392,1712]},{"id":8,"type":"VAEDecode","pos":[1277.5745849609375,241.4618377685547],"size":[210,46],"flags":{},"order":17,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":24,"label":"samples"},{"name":"vae","type":"VAE","link":12,"label":"vae"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0,"label":"IMAGE"}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":13,"type":"SamplerCustomAdvanced","pos":[906.1104736328125,211.06903076171875],"size":[272.3617858886719,124.53733825683594],"flags":{},"order":16,"mode":0,"inputs":[{"name":"noise","type":"NOISE","link":37,"slot_index":0,"label":"noise"},{"name":"guider","type":"GUIDER","link":127,"slot_index":1,"label":"guider"},{"name":"sampler","type":"SAMPLER","link":19,"slot_index":2,"label":"sampler"},{"name":"sigmas","type":"SIGMAS","link":20,"slot_index":3,"label":"sigmas"},{"name":"latent_image","type":"LATENT","link":116,"slot_index":4,"label":"latent_image"}],"outputs":[{"name":"output","type":"LATENT","links":[24],"slot_index":0,"shape":3,"label":"output"},{"name":"denoised_output","type":"LATENT","links":null,"shape":3,"label":"denoised_output"}],"properties":{"Node name for S&R":"SamplerCustomAdvanced"},"widgets_values":[]},{"id":27,"type":"EmptySD3LatentImage","pos":[485.56170654296875,612.8764038085938],"size":[315,106],"flags":{},"order":8,"mode":0,"inputs":[{"name":"width","type":"INT","link":112,"widget":{"name":"width"},"label":"width"},{"name":"height","type":"INT","link":113,"widget":{"name":"height"},"label":"height"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[116],"slot_index":0,"shape":3,"label":"LATENT"}],"properties":{"Node name for S&R":"EmptySD3LatentImage"},"widgets_values":[1392,1712,1]},{"id":17,"type":"BasicScheduler","pos":[480,1008],"size":[315,106],"flags":{},"order":11,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":55,"slot_index":0,"label":"model"}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[20],"shape":3,"label":"SIGMAS"}],"properties":{"Node name for S&R":"BasicScheduler"},"widgets_values":["simple",20,1]},{"id":40,"type":"CFGGuider","pos":[2041.7757568359375,-41.73738098144531],"size":[315,98],"flags":{},"order":15,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":123},{"name":"positive","type":"CONDITIONING","link":130},{"name":"negative","type":"CONDITIONING","link":126}],"outputs":[{"name":"GUIDER","type":"GUIDER","links":[127],"slot_index":0}],"properties":{"Node name for S&R":"CFGGuider"},"widgets_values":[1.01]},{"id":39,"type":"CLIPTextEncode","pos":[810.628662109375,-24.575204849243164],"size":[422.84503173828125,164.31304931640625],"flags":{"collapsed":true},"order":13,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":121,"label":"clip"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[126],"slot_index":0,"label":"CONDITIONING"}],"title":"CLIP Text Encode (NEgative Prompt)","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""],"color":"#322","bgcolor":"#533"},{"id":25,"type":"RandomNoise","pos":[480,768],"size":[315,82],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"NOISE","type":"NOISE","links":[37],"shape":3,"label":"NOISE"}],"properties":{"Node name for S&R":"RandomNoise"},"widgets_values":[607280210647355,"randomize"],"color":"#2a363b","bgcolor":"#3f5159"},{"id":26,"type":"FluxGuidance","pos":[1449.265380859375,-213.46588134765625],"size":[317.4000244140625,58],"flags":{},"order":14,"mode":0,"inputs":[{"name":"conditioning","type":"CONDITIONING","link":129,"label":"conditioning"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[130],"slot_index":0,"shape":3,"label":"CONDITIONING"}],"properties":{"Node name for S&R":"FluxGuidance"},"widgets_values":[3.4000000000000004],"color":"#233","bgcolor":"#355"},{"id":38,"type":"Power Lora Loader (rgthree)","pos":[254.0276641845703,-200.78903198242188],"size":[340.20001220703125,214],"flags":{},"order":10,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":117,"dir":3},{"name":"clip","type":"CLIP","link":118,"dir":3}],"outputs":[{"name":"MODEL","type":"MODEL","links":[123],"slot_index":0,"shape":3,"dir":4},{"name":"CLIP","type":"CLIP","links":[120,121],"slot_index":1,"shape":3,"dir":4}],"properties":{"Show Strengths":"Single Strength"},"widgets_values":[null,{"type":"PowerLoraLoaderHeaderWidget"},{"on":true,"lora":"lukasz.safetensors","strength":1,"strengthTwo":null},{"on":false,"lora":"holoportraitv1.safetensors","strength":0.52,"strengthTwo":null},{"on":true,"lora":"Cyber_Room.safetensors","strength":0.4999999999999997,"strengthTwo":null},{"on":false,"lora":"Flux\\Mezzotint_Artstyle_for_Flux_-_by_Ethanar.safetensors","strength":0.5333343505859371,"strengthTwo":null},null,""]},{"id":34,"type":"PrimitiveNode","pos":[432,480],"size":[210,82],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"INT","type":"INT","links":[112,115],"slot_index":0,"widget":{"name":"width"},"label":"INT"}],"title":"width","properties":{"Run widget replace on values":false},"widgets_values":[1392,"fixed"],"color":"#323","bgcolor":"#535"},{"id":35,"type":"PrimitiveNode","pos":[672,480],"size":[210,82],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"INT","type":"INT","links":[113,114],"slot_index":0,"widget":{"name":"height"},"label":"INT"}],"title":"height","properties":{"Run widget replace on values":false},"widgets_values":[1712,"fixed"],"color":"#323","bgcolor":"#535"},{"id":9,"type":"SaveImage","pos":[1526.12060546875,180.73696899414062],"size":[985.3012084960938,1060.3828125],"flags":{},"order":18,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9,"label":"images"}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":10,"type":"VAELoader","pos":[42.75599670410156,458.219970703125],"size":[311.81634521484375,60.429901123046875],"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[12],"slot_index":0,"shape":3,"label":"VAE"}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.safetensors"]},{"id":11,"type":"DualCLIPLoader","pos":[48,288],"size":[315,106],"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[118],"slot_index":0,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["t5xxl_fp16.safetensors","clip_l.safetensors","flux","default"]},{"id":12,"type":"UNETLoader","pos":[48,144],"size":[315,82],"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[56,117],"slot_index":0,"shape":3,"label":"MODEL"}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["flux1-dev.safetensors","fp8_e4m3fn"],"color":"#223","bgcolor":"#335"},{"id":6,"type":"CLIPTextEncode","pos":[830.5343627929688,-262.1523132324219],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":12,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":120,"label":"clip"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[129],"slot_index":0,"label":"CONDITIONING"}],"title":"CLIP Text Encode (Positive Prompt)","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""],"color":"#232","bgcolor":"#353"},{"id":37,"type":"Note","pos":[480,1344],"size":[314.99755859375,117.98363494873047],"flags":{},"order":7,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["The reference sampling implementation auto adjusts the shift value based on the resolution, if you don't want this you can just bypass (CTRL-B) this ModelSamplingFlux node.\n"],"color":"#432","bgcolor":"#653"}],"links":[[9,8,0,9,0,"IMAGE"],[12,10,0,8,1,"VAE"],[19,16,0,13,2,"SAMPLER"],[20,17,0,13,3,"SIGMAS"],[24,13,0,8,0,"LATENT"],[37,25,0,13,0,"NOISE"],[55,30,0,17,0,"MODEL"],[56,12,0,30,0,"MODEL"],[112,34,0,27,0,"INT"],[113,35,0,27,1,"INT"],[114,35,0,30,2,"INT"],[115,34,0,30,1,"INT"],[116,27,0,13,4,"LATENT"],[117,12,0,38,0,"MODEL"],[118,11,0,38,1,"CLIP"],[120,38,1,6,0,"CLIP"],[121,38,1,39,0,"CLIP"],[123,38,0,40,0,"MODEL"],[126,39,0,40,2,"CONDITIONING"],[127,40,0,13,1,"GUIDER"],[129,6,0,26,0,"CONDITIONING"],[130,26,0,40,1,"CONDITIONING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7627768444385532,"offset":[820.170947246642,287.9786370387966]},"groupNodes":{}},"version":0.4}


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by hengfeihu** [comment]
same problem

**Comment by hengfeihu** [comment]
same problem

**Comment by yakay2023** [comment]
Brothers above, I have also encountered this problem. May I ask if you also have multiple graphics cards of different models? Could it be caused by this issue

**Comment by tpatterson34** [comment]
I was on an Alienware which has both an integrated Intel and Nvidia card.  The system was setup to use "Optimus".  I changed to Nvidia only and the problem was resolved for me.  

![Image](https://github.com/user-attachments/assets/b4e8e77e-fcb4-441e-b290-3981b8720d0e)

**Comment by ewebgh33** [comment]
I'm getting the same error today after updating Comfy. Trying to run Bytedance UNO which needs 16gb VRAM - I have 2x 4090 so 24gb VRAM on each, and yet I am getting the error "Allocation on device" with failed generation.

**Comment by marlonmarcello** [comment]
Same here for me. Started getting this after I updated Comfy on workflows that were working previously.
