### ISSUE TITLE
allocation on device

### ISSUE THREAD

**Issue by yuhongye123** [comfyanonymous/ComfyUI#6716]
### Expected Behavior

当我使用Janus-pro工作流时，出现Allocation on device错误

Manager

Show Image Feed 🐍
1

↹ Resize Feed
Feed Size...

Column count...

Clear
❌
队列
Failed
0.15s
Failed
72.09s
A portrait photo of a girl
Describe this image in detail.
This image features a cute, stylized deer with large, expressive eyes and a gentle smile. The deer has light brown fur with intricate patterns, and its ears are pointed and slightly curved outward. It has a pair of black headphones around its neck, giving it a modern, playful touch.

Behind the deer, there is a vibrant rainbow arching across the image, with each color segment clearly visible. The rainbow adds a cheerful and whimsical element to the scene. Scattered around the rainbow are small black stars, enhancing the playful and magical atmosphere.

Below the deer, there is a cloud that partially frames the deer, and beneath the cloud, the word "WAYTOAGI" is written in bold, black, uppercase letters. The text is centered and adds a name or brand to the image.

Overall, the image combines elements of nature, music, and fantasy, creating a whimsical and charming scene.
JanusModelLoader
Allocation on device

# ComfyUI Error Report
## Error Details
- **Node ID:** 10
- **Node Type:** JanusModelLoader
- **Exception Type:** torch.OutOfMemoryError
- **Exception Message:** Allocation on device 
## Stack Trace
```
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\custom_nodes/ComfyUI-Janus-Pro\nodes\model_loader.py", line 53, in load_model
    vl_gpt = vl_gpt.to(dtype).to(device).eval()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3157, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)

  [Previous line repeated 3 more times]

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^

```
## System Information
- **ComfyUI Version:** 0.3.13
- **Arguments:** C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py --user-directory C:\tools\user --input-directory C:\tools\input --output-directory C:\tools\output --front-end-root C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app --extra-model-paths-config C:\Users\于泓晔\AppData\Roaming\ComfyUI\extra_models_config.yaml --port 8000 --listen 127.0.0.1
- **OS:** nt
- **Python Version:** 3.12.8 (main, Dec 19 2024, 14:41:01) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA RTX 500 Ada Generation Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 4292411392
  - **VRAM Free:** 3377515726
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2025-02-06T08:32:16.291626 - Adding extra search path checkpoints C:\tools\models\checkpoints\
2025-02-06T08:32:16.291626 - Adding extra search path classifiers C:\tools\models\classifiers\
2025-02-06T08:32:16.291626 - Adding extra search path clip C:\tools\models\clip\
2025-02-06T08:32:16.291626 - Adding extra search path clip_vision C:\tools\models\clip_vision\
2025-02-06T08:32:16.291626 - Adding extra search path configs C:\tools\models\configs\
2025-02-06T08:32:16.291626 - Adding extra search path controlnet C:\tools\models\controlnet\
2025-02-06T08:32:16.291626 - Adding extra search path diffusers C:\tools\models\diffusers\
2025-02-06T08:32:16.291626 - Adding extra search path diffusion_models C:\tools\models\diffusion_models\
2025-02-06T08:32:16.291626 - Adding extra search path embeddings C:\tools\models\embeddings\
2025-02-06T08:32:16.291626 - Adding extra search path gligen C:\tools\models\gligen\
2025-02-06T08:32:16.291626 - Adding extra search path hypernetworks C:\tools\models\hypernetworks\
2025-02-06T08:32:16.291626 - Adding extra search path loras C:\tools\models\loras\
2025-02-06T08:32:16.291626 - Adding extra search path photomaker C:\tools\models\photomaker\
2025-02-06T08:32:16.291626 - Adding extra search path style_models C:\tools\models\style_models\
2025-02-06T08:32:16.291626 - Adding extra search path unet C:\tools\models\unet\
2025-02-06T08:32:16.291626 - Adding extra search path upscale_models C:\tools\models\upscale_models\
2025-02-06T08:32:16.291626 - Adding extra search path vae C:\tools\models\vae\
2025-02-06T08:32:16.291626 - Adding extra search path vae_approx C:\tools\models\vae_approx\
2025-02-06T08:32:16.291626 - Adding extra search path animatediff_models C:\tools\models\animatediff_models\
2025-02-06T08:32:16.291626 - Adding extra search path animatediff_motion_lora C:\tools\models\animatediff_motion_lora\
2025-02-06T08:32:16.291626 - Adding extra search path animatediff_video_formats C:\tools\models\animatediff_video_formats\
2025-02-06T08:32:16.291626 - Adding extra search path ipadapter C:\tools\models\ipadapter\
2025-02-06T08:32:16.291626 - Adding extra search path liveportrait C:\tools\models\liveportrait\
2025-02-06T08:32:16.291626 - Adding extra search path insightface C:\tools\models\insightface\
2025-02-06T08:32:16.291626 - Adding extra search path layerstyle C:\tools\models\layerstyle\
2025-02-06T08:32:16.291626 - Adding extra search path LLM C:\tools\models\LLM\
2025-02-06T08:32:16.291626 - Adding extra search path Joy_caption C:\tools\models\Joy_caption\
2025-02-06T08:32:16.291626 - Adding extra search path sams C:\tools\models\sams\
2025-02-06T08:32:16.291626 - Adding extra search path blip C:\tools\models\blip\
2025-02-06T08:32:16.291626 - Adding extra search path CogVideo C:\tools\models\CogVideo\
2025-02-06T08:32:16.291626 - Adding extra search path xlabs C:\tools\models\xlabs\
2025-02-06T08:32:16.291626 - Adding extra search path instantid C:\tools\models\instantid\
2025-02-06T08:32:16.291626 - Adding extra search path custom_nodes C:\tools\custom_nodes/
2025-02-06T08:32:16.291626 - Adding extra search path download_model_base C:\tools\models
2025-02-06T08:32:16.291626 - Setting output directory to: C:\tools\output
2025-02-06T08:32:16.291626 - Setting input directory to: C:\tools\input
2025-02-06T08:32:16.291626 - Setting user directory to: C:\tools\user
2025-02-06T08:32:16.318324 - [START] Security scan2025-02-06T08:32:16.318324 - 
2025-02-06T08:32:18.086119 - [DONE] Security scan2025-02-06T08:32:18.086119 - 
2025-02-06T08:32:18.213640 - ## ComfyUI-Manager: installing dependencies done.2025-02-06T08:32:18.213640 - 
2025-02-06T08:32:18.213640 - ** ComfyUI startup time:2025-02-06T08:32:18.213640 -  2025-02-06T08:32:18.213640 - 2025-02-06 08:32:18.2136402025-02-06T08:32:18.213640 - 
2025-02-06T08:32:18.252716 - ** Platform:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - Windows2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** Python version:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - 3.12.8 (main, Dec 19 2024, 14:41:01) [MSC v.1942 64 bit (AMD64)]2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** Python executable:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - C:\tools\.venv\Scripts\python.exe2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** ComfyUI Path:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** Log path:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - C:\tools\comfyui.log2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:19.164487 - 
Prestartup times for custom nodes:
2025-02-06T08:32:19.164487 -    2.9 seconds: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-02-06T08:32:19.164487 - 
2025-02-06T08:32:22.726197 - Checkpoint files will always be loaded safely.
2025-02-06T08:32:24.364305 - Total VRAM 4094 MB, total RAM 32213 MB
2025-02-06T08:32:24.364305 - pytorch version: 2.5.1+cu121
2025-02-06T08:32:24.364305 - Set vram state to: NORMAL_VRAM
2025-02-06T08:32:24.364305 - Device: cuda:0 NVIDIA RTX 500 Ada Generation Laptop GPU : cudaMallocAsync
2025-02-06T08:32:25.924906 - Using pytorch attention
2025-02-06T08:32:30.638055 - ComfyUI version: 0.3.13
2025-02-06T08:32:30.670123 - [Prompt Server] web root: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
2025-02-06T08:32:31.440408 - C:\tools2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - ############################################2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - C:\tools\custom_nodes\ComfyUI-NAI-styler\CSV2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - ############################################2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - []2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - ############################################2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.444598 - ### Loading: ComfyUI-Manager (V2.55.3)2025-02-06T08:32:31.444598 - 
2025-02-06T08:32:31.446532 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)2025-02-06T08:32:31.446532 - 
2025-02-06T08:32:31.454942 - 
Import times for custom nodes:
2025-02-06T08:32:31.454942 -    0.0 seconds: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-02-06T08:32:31.454942 -    0.0 seconds: C:\tools\custom_nodes/ComfyUI-Universal-Styler
2025-02-06T08:32:31.455532 -    0.0 seconds: C:\tools\custom_nodes/ComfyUI-Janus-Pro
2025-02-06T08:32:31.455532 -    0.0 seconds: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-02-06T08:32:31.455532 -    0.0 seconds: C:\tools\custom_nodes/ComfyUI-Custom-Scripts
2025-02-06T08:32:31.455532 - 
2025-02-06T08:32:31.465998 - Starting server

2025-02-06T08:32:31.465998 - To see the GUI go to: http://127.0.0.1:8000
2025-02-06T08:32:32.118865 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-02-06T08:32:32.118865 - 
2025-02-06T08:32:32.411520 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2025-02-06T08:32:32.411520 - 
2025-02-06T08:32:32.417905 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2025-02-06T08:32:32.417905 - 
2025-02-06T08:32:32.457303 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-02-06T08:32:32.457303 - 
2025-02-06T08:32:32.772897 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-02-06T08:32:32.772897 - 
2025-02-06T08:32:35.975887 - FETCH DATA from: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2025-02-06T08:32:35.975887 - 2025-02-06T08:32:36.138965 -  [DONE]2025-02-06T08:32:36.138965 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:58.855544 - got prompt
2025-02-06T08:32:58.861801 - Failed to validate prompt for output 21:
2025-02-06T08:32:58.861801 - * LoadImage 19:
2025-02-06T08:32:58.861801 -   - Custom validation failed for node: image - Invalid image file: ComfyUI_temp_gslhb_00067_.png
2025-02-06T08:32:58.861801 - Output will be ignored
2025-02-06T08:32:58.864592 - WARNING: [Errno 2] No such file or directory: 'C:\\tools\\input\\ComfyUI_temp_gslhb_00067_.png'
2025-02-06T08:32:58.868860 - Python version is above 3.10, patching the collections module.2025-02-06T08:32:58.868860 - 
2025-02-06T08:32:58.954306 - C:\tools\.venv\Lib\site-packages\transformers\models\auto\image_processing_auto.py:520: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
2025-02-06T08:32:59.557496 - You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
2025-02-06T08:32:59.697725 - Some kwargs in processor config are unused and will not have any effect: ignore_id, mask_prompt, sft_format, add_special_token, num_image_tokens, image_tag. 
2025-02-06T08:33:27.953439 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:27<00:00, 13.58s/it]2025-02-06T08:33:27.953439 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:27<00:00, 13.57s/it]2025-02-06T08:33:27.953439 - 
2025-02-06T08:33:46.930380 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2025-02-06T08:33:46.930380 - 2025-02-06T08:33:49.546645 -  [DONE]2025-02-06T08:33:49.546645 - 
2025-02-06T08:34:02.772143 - !!! Exception during processing !!! Allocation on device 
2025-02-06T08:34:02.893966 - Traceback (most recent call last):
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\custom_nodes/ComfyUI-Janus-Pro\nodes\model_loader.py", line 53, in load_model
    vl_gpt = vl_gpt.to(dtype).to(device).eval()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3157, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: Allocation on device 

2025-02-06T08:34:02.893966 - Got an OOM, unloading all loaded models.
2025-02-06T08:34:02.905522 - Prompt executed in 64.04 seconds
2025-02-06T08:37:30.160452 - got prompt
2025-02-06T08:37:30.164612 - Failed to validate prompt for output 21:
2025-02-06T08:37:30.164612 - * LoadImage 19:
2025-02-06T08:37:30.164612 -   - Custom validation failed for node: image - Invalid image file: ComfyUI_temp_gslhb_00067_.png
2025-02-06T08:37:30.164612 - Output will be ignored
2025-02-06T08:37:30.168012 - WARNING: [Errno 2] No such file or directory: 'C:\\tools\\input\\ComfyUI_temp_gslhb_00067_.png'
2025-02-06T08:37:30.509289 - Some kwargs in processor config are unused and will not have any effect: ignore_id, mask_prompt, sft_format, add_special_token, num_image_tokens, image_tag. 
2025-02-06T08:37:45.109332 - 
Loading checkpoint shards:  50%|█████     | 1/2 [00:13<00:13, 13.33s/it]2025-02-06T08:37:53.486877 - got prompt
2025-02-06T08:37:53.495823 - Failed to validate prompt for output 21:
2025-02-06T08:37:53.495823 - * LoadImage 19:
2025-02-06T08:37:53.495823 -   - Custom validation failed for node: image - Invalid image file: ComfyUI_temp_gslhb_00067_.png
2025-02-06T08:37:53.495823 - Output will be ignored
2025-02-06T08:38:10.005030 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:38<00:00, 20.13s/it]2025-02-06T08:38:10.006723 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:38<00:00, 19.12s/it]2025-02-06T08:38:10.006723 - 
2025-02-06T08:38:42.243574 - !!! Exception during processing !!! Allocation on device 
2025-02-06T08:38:42.249877 - Traceback (most recent call last):
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\custom_nodes/ComfyUI-Janus-Pro\nodes\model_loader.py", line 53, in load_model
    vl_gpt = vl_gpt.to(dtype).to(device).eval()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3157, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: Allocation on device 

2025-02-06T08:38:42.251916 - Got an OOM, unloading all loaded models.
2025-02-06T08:38:42.259679 - Prompt executed in 72.09 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":25,"last_link_id":43,"nodes":[{"id":19,"type":"LoadImage","pos":[-300,-110],"size":[320,320],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[42],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_temp_gslhb_00067_.png","image"]},{"id":25,"type":"JanusImageUnderstanding","pos":[100,10],"size":[400,236],"flags":{},"order":3,"mode":0,"inputs":[{"name":"model","type":"JANUS_MODEL","link":40,"label":"model"},{"name":"processor","type":"JANUS_PROCESSOR","link":41,"label":"processor"},{"name":"image","type":"IMAGE","link":42,"label":"image"}],"outputs":[{"name":"text","type":"STRING","links":[43],"label":"text"}],"properties":{"Node name for S&R":"JanusImageUnderstanding"},"widgets_values":["Describe this image in detail.",286196206414827,"randomize",0.1,0.95,512]},{"id":21,"type":"ShowText|pysssss","pos":[540,10],"size":[430,240],"flags":{},"order":5,"mode":0,"inputs":[{"name":"text","type":"STRING","link":43,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":["","This image features a cute, stylized deer with large, expressive eyes and a gentle smile. The deer has light brown fur with intricate patterns, and its ears are pointed and slightly curved outward. It has a pair of black headphones around its neck, giving it a modern, playful touch.\n\nBehind the deer, there is a vibrant rainbow arching across the image, with each color segment clearly visible. The rainbow adds a cheerful and whimsical element to the scene. Scattered around the rainbow are small black stars, enhancing the playful and magical atmosphere.\n\nBelow the deer, there is a cloud that partially frames the deer, and beneath the cloud, the word \"WAYTOAGI\" is written in bold, black, uppercase letters. The text is centered and adds a name or brand to the image.\n\nOverall, the image combines elements of nature, music, and fantasy, creating a whimsical and charming scene."]},{"id":16,"type":"PreviewImage","pos":[560,-350],"size":[250,260],"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":39,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":24,"type":"JanusImageGeneration","pos":[90,-340],"size":[400,240],"flags":{},"order":2,"mode":0,"inputs":[{"name":"model","type":"JANUS_MODEL","link":37,"label":"model"},{"name":"processor","type":"JANUS_PROCESSOR","link":38,"label":"processor"}],"outputs":[{"name":"images","type":"IMAGE","links":[39],"label":"images"}],"properties":{"Node name for S&R":"JanusImageGeneration"},"widgets_values":["A portrait photo of a girl",613299350692455,"fixed",1,5,1,0.95]},{"id":10,"type":"JanusModelLoader","pos":[-300,-290],"size":[315,102],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"model","type":"JANUS_MODEL","links":[37,40],"slot_index":0,"label":"model"},{"name":"processor","type":"JANUS_PROCESSOR","links":[38,41],"slot_index":1,"label":"processor"}],"properties":{"Node name for S&R":"JanusModelLoader"},"widgets_values":["deepseek-ai/Janus-Pro-1B"]}],"links":[[37,10,0,24,0,"JANUS_MODEL"],[38,10,1,24,1,"JANUS_PROCESSOR"],[39,24,0,16,0,"IMAGE"],[40,10,0,25,0,"JANUS_MODEL"],[41,10,1,25,1,"JANUS_PROCESSOR"],[42,19,0,25,2,"IMAGE"],[43,25,0,21,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[409.3333435058594,372.6666488647461]},"workspace_info":{"id":"fmD__XZpFj36_jkuHASUE"}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

### Actual Behavior

![Image](https://github.com/user-attachments/assets/8e261d23-3d4e-4620-ae6c-f4037390ce88)

### Steps to Reproduce

![Image](https://github.com/user-attachments/assets/8555c5be-dfc6-40dc-b4e9-bf5d630d3513)

### Debug Logs

```powershell
Manager



Show Image Feed 🐍
1

↹ Resize Feed
Feed Size...

Column count...

Clear
❌
队列
Failed
0.15s
Failed
72.09s
A portrait photo of a girl
Describe this image in detail.
This image features a cute, stylized deer with large, expressive eyes and a gentle smile. The deer has light brown fur with intricate patterns, and its ears are pointed and slightly curved outward. It has a pair of black headphones around its neck, giving it a modern, playful touch.

Behind the deer, there is a vibrant rainbow arching across the image, with each color segment clearly visible. The rainbow adds a cheerful and whimsical element to the scene. Scattered around the rainbow are small black stars, enhancing the playful and magical atmosphere.

Below the deer, there is a cloud that partially frames the deer, and beneath the cloud, the word "WAYTOAGI" is written in bold, black, uppercase letters. The text is centered and adds a name or brand to the image.

Overall, the image combines elements of nature, music, and fantasy, creating a whimsical and charming scene.
JanusModelLoader
Allocation on device


# ComfyUI Error Report
## Error Details
- **Node ID:** 10
- **Node Type:** JanusModelLoader
- **Exception Type:** torch.OutOfMemoryError
- **Exception Message:** Allocation on device 
## Stack Trace

  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\custom_nodes/ComfyUI-Janus-Pro\nodes\model_loader.py", line 53, in load_model
    vl_gpt = vl_gpt.to(dtype).to(device).eval()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3157, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)

  [Previous line repeated 3 more times]

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^

  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^


## System Information
- **ComfyUI Version:** 0.3.13
- **Arguments:** C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py --user-directory C:\tools\user --input-directory C:\tools\input --output-directory C:\tools\output --front-end-root C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app --extra-model-paths-config C:\Users\于泓晔\AppData\Roaming\ComfyUI\extra_models_config.yaml --port 8000 --listen 127.0.0.1
- **OS:** nt
- **Python Version:** 3.12.8 (main, Dec 19 2024, 14:41:01) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA RTX 500 Ada Generation Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 4292411392
  - **VRAM Free:** 3377515726
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs

2025-02-06T08:32:16.291626 - Adding extra search path checkpoints C:\tools\models\checkpoints\
2025-02-06T08:32:16.291626 - Adding extra search path classifiers C:\tools\models\classifiers\
2025-02-06T08:32:16.291626 - Adding extra search path clip C:\tools\models\clip\
2025-02-06T08:32:16.291626 - Adding extra search path clip_vision C:\tools\models\clip_vision\
2025-02-06T08:32:16.291626 - Adding extra search path configs C:\tools\models\configs\
2025-02-06T08:32:16.291626 - Adding extra search path controlnet C:\tools\models\controlnet\
2025-02-06T08:32:16.291626 - Adding extra search path diffusers C:\tools\models\diffusers\
2025-02-06T08:32:16.291626 - Adding extra search path diffusion_models C:\tools\models\diffusion_models\
2025-02-06T08:32:16.291626 - Adding extra search path embeddings C:\tools\models\embeddings\
2025-02-06T08:32:16.291626 - Adding extra search path gligen C:\tools\models\gligen\
2025-02-06T08:32:16.291626 - Adding extra search path hypernetworks C:\tools\models\hypernetworks\
2025-02-06T08:32:16.291626 - Adding extra search path loras C:\tools\models\loras\
2025-02-06T08:32:16.291626 - Adding extra search path photomaker C:\tools\models\photomaker\
2025-02-06T08:32:16.291626 - Adding extra search path style_models C:\tools\models\style_models\
2025-02-06T08:32:16.291626 - Adding extra search path unet C:\tools\models\unet\
2025-02-06T08:32:16.291626 - Adding extra search path upscale_models C:\tools\models\upscale_models\
2025-02-06T08:32:16.291626 - Adding extra search path vae C:\tools\models\vae\
2025-02-06T08:32:16.291626 - Adding extra search path vae_approx C:\tools\models\vae_approx\
2025-02-06T08:32:16.291626 - Adding extra search path animatediff_models C:\tools\models\animatediff_models\
2025-02-06T08:32:16.291626 - Adding extra search path animatediff_motion_lora C:\tools\models\animatediff_motion_lora\
2025-02-06T08:32:16.291626 - Adding extra search path animatediff_video_formats C:\tools\models\animatediff_video_formats\
2025-02-06T08:32:16.291626 - Adding extra search path ipadapter C:\tools\models\ipadapter\
2025-02-06T08:32:16.291626 - Adding extra search path liveportrait C:\tools\models\liveportrait\
2025-02-06T08:32:16.291626 - Adding extra search path insightface C:\tools\models\insightface\
2025-02-06T08:32:16.291626 - Adding extra search path layerstyle C:\tools\models\layerstyle\
2025-02-06T08:32:16.291626 - Adding extra search path LLM C:\tools\models\LLM\
2025-02-06T08:32:16.291626 - Adding extra search path Joy_caption C:\tools\models\Joy_caption\
2025-02-06T08:32:16.291626 - Adding extra search path sams C:\tools\models\sams\
2025-02-06T08:32:16.291626 - Adding extra search path blip C:\tools\models\blip\
2025-02-06T08:32:16.291626 - Adding extra search path CogVideo C:\tools\models\CogVideo\
2025-02-06T08:32:16.291626 - Adding extra search path xlabs C:\tools\models\xlabs\
2025-02-06T08:32:16.291626 - Adding extra search path instantid C:\tools\models\instantid\
2025-02-06T08:32:16.291626 - Adding extra search path custom_nodes C:\tools\custom_nodes/
2025-02-06T08:32:16.291626 - Adding extra search path download_model_base C:\tools\models
2025-02-06T08:32:16.291626 - Setting output directory to: C:\tools\output
2025-02-06T08:32:16.291626 - Setting input directory to: C:\tools\input
2025-02-06T08:32:16.291626 - Setting user directory to: C:\tools\user
2025-02-06T08:32:16.318324 - [START] Security scan2025-02-06T08:32:16.318324 - 
2025-02-06T08:32:18.086119 - [DONE] Security scan2025-02-06T08:32:18.086119 - 
2025-02-06T08:32:18.213640 - ## ComfyUI-Manager: installing dependencies done.2025-02-06T08:32:18.213640 - 
2025-02-06T08:32:18.213640 - ** ComfyUI startup time:2025-02-06T08:32:18.213640 -  2025-02-06T08:32:18.213640 - 2025-02-06 08:32:18.2136402025-02-06T08:32:18.213640 - 
2025-02-06T08:32:18.252716 - ** Platform:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - Windows2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** Python version:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - 3.12.8 (main, Dec 19 2024, 14:41:01) [MSC v.1942 64 bit (AMD64)]2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** Python executable:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - C:\tools\.venv\Scripts\python.exe2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** ComfyUI Path:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:18.252716 - ** Log path:2025-02-06T08:32:18.252716 -  2025-02-06T08:32:18.252716 - C:\tools\comfyui.log2025-02-06T08:32:18.252716 - 
2025-02-06T08:32:19.164487 - 
Prestartup times for custom nodes:
2025-02-06T08:32:19.164487 -    2.9 seconds: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-02-06T08:32:19.164487 - 
2025-02-06T08:32:22.726197 - Checkpoint files will always be loaded safely.
2025-02-06T08:32:24.364305 - Total VRAM 4094 MB, total RAM 32213 MB
2025-02-06T08:32:24.364305 - pytorch version: 2.5.1+cu121
2025-02-06T08:32:24.364305 - Set vram state to: NORMAL_VRAM
2025-02-06T08:32:24.364305 - Device: cuda:0 NVIDIA RTX 500 Ada Generation Laptop GPU : cudaMallocAsync
2025-02-06T08:32:25.924906 - Using pytorch attention
2025-02-06T08:32:30.638055 - ComfyUI version: 0.3.13
2025-02-06T08:32:30.670123 - [Prompt Server] web root: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
2025-02-06T08:32:31.440408 - C:\tools2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - ############################################2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - C:\tools\custom_nodes\ComfyUI-NAI-styler\CSV2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - ############################################2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - []2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.440408 - ############################################2025-02-06T08:32:31.440408 - 
2025-02-06T08:32:31.444598 - ### Loading: ComfyUI-Manager (V2.55.3)2025-02-06T08:32:31.444598 - 
2025-02-06T08:32:31.446532 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)2025-02-06T08:32:31.446532 - 
2025-02-06T08:32:31.454942 - 
Import times for custom nodes:
2025-02-06T08:32:31.454942 -    0.0 seconds: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-02-06T08:32:31.454942 -    0.0 seconds: C:\tools\custom_nodes/ComfyUI-Universal-Styler
2025-02-06T08:32:31.455532 -    0.0 seconds: C:\tools\custom_nodes/ComfyUI-Janus-Pro
2025-02-06T08:32:31.455532 -    0.0 seconds: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-02-06T08:32:31.455532 -    0.0 seconds: C:\tools\custom_nodes/ComfyUI-Custom-Scripts
2025-02-06T08:32:31.455532 - 
2025-02-06T08:32:31.465998 - Starting server

2025-02-06T08:32:31.465998 - To see the GUI go to: http://127.0.0.1:8000
2025-02-06T08:32:32.118865 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-02-06T08:32:32.118865 - 
2025-02-06T08:32:32.411520 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2025-02-06T08:32:32.411520 - 
2025-02-06T08:32:32.417905 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2025-02-06T08:32:32.417905 - 
2025-02-06T08:32:32.457303 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-02-06T08:32:32.457303 - 
2025-02-06T08:32:32.772897 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-02-06T08:32:32.772897 - 
2025-02-06T08:32:35.975887 - FETCH DATA from: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2025-02-06T08:32:35.975887 - 2025-02-06T08:32:36.138965 -  [DONE]2025-02-06T08:32:36.138965 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:36.180657 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
            2025-02-06T08:32:36.180657 - 
2025-02-06T08:32:58.855544 - got prompt
2025-02-06T08:32:58.861801 - Failed to validate prompt for output 21:
2025-02-06T08:32:58.861801 - * LoadImage 19:
2025-02-06T08:32:58.861801 -   - Custom validation failed for node: image - Invalid image file: ComfyUI_temp_gslhb_00067_.png
2025-02-06T08:32:58.861801 - Output will be ignored
2025-02-06T08:32:58.864592 - WARNING: [Errno 2] No such file or directory: 'C:\\tools\\input\\ComfyUI_temp_gslhb_00067_.png'
2025-02-06T08:32:58.868860 - Python version is above 3.10, patching the collections module.2025-02-06T08:32:58.868860 - 
2025-02-06T08:32:58.954306 - C:\tools\.venv\Lib\site-packages\transformers\models\auto\image_processing_auto.py:520: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
2025-02-06T08:32:59.557496 - You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
2025-02-06T08:32:59.697725 - Some kwargs in processor config are unused and will not have any effect: ignore_id, mask_prompt, sft_format, add_special_token, num_image_tokens, image_tag. 
2025-02-06T08:33:27.953439 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:27<00:00, 13.58s/it]2025-02-06T08:33:27.953439 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:27<00:00, 13.57s/it]2025-02-06T08:33:27.953439 - 
2025-02-06T08:33:46.930380 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2025-02-06T08:33:46.930380 - 2025-02-06T08:33:49.546645 -  [DONE]2025-02-06T08:33:49.546645 - 
2025-02-06T08:34:02.772143 - !!! Exception during processing !!! Allocation on device 
2025-02-06T08:34:02.893966 - Traceback (most recent call last):
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\custom_nodes/ComfyUI-Janus-Pro\nodes\model_loader.py", line 53, in load_model
    vl_gpt = vl_gpt.to(dtype).to(device).eval()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3157, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: Allocation on device 

2025-02-06T08:34:02.893966 - Got an OOM, unloading all loaded models.
2025-02-06T08:34:02.905522 - Prompt executed in 64.04 seconds
2025-02-06T08:37:30.160452 - got prompt
2025-02-06T08:37:30.164612 - Failed to validate prompt for output 21:
2025-02-06T08:37:30.164612 - * LoadImage 19:
2025-02-06T08:37:30.164612 -   - Custom validation failed for node: image - Invalid image file: ComfyUI_temp_gslhb_00067_.png
2025-02-06T08:37:30.164612 - Output will be ignored
2025-02-06T08:37:30.168012 - WARNING: [Errno 2] No such file or directory: 'C:\\tools\\input\\ComfyUI_temp_gslhb_00067_.png'
2025-02-06T08:37:30.509289 - Some kwargs in processor config are unused and will not have any effect: ignore_id, mask_prompt, sft_format, add_special_token, num_image_tokens, image_tag. 
2025-02-06T08:37:45.109332 - 
Loading checkpoint shards:  50%|█████     | 1/2 [00:13<00:13, 13.33s/it]2025-02-06T08:37:53.486877 - got prompt
2025-02-06T08:37:53.495823 - Failed to validate prompt for output 21:
2025-02-06T08:37:53.495823 - * LoadImage 19:
2025-02-06T08:37:53.495823 -   - Custom validation failed for node: image - Invalid image file: ComfyUI_temp_gslhb_00067_.png
2025-02-06T08:37:53.495823 - Output will be ignored
2025-02-06T08:38:10.005030 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:38<00:00, 20.13s/it]2025-02-06T08:38:10.006723 - 
Loading checkpoint shards: 100%|██████████| 2/2 [00:38<00:00, 19.12s/it]2025-02-06T08:38:10.006723 - 
2025-02-06T08:38:42.243574 - !!! Exception during processing !!! Allocation on device 
2025-02-06T08:38:42.249877 - Traceback (most recent call last):
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\于泓晔\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\custom_nodes/ComfyUI-Janus-Pro\nodes\model_loader.py", line 53, in load_model
    vl_gpt = vl_gpt.to(dtype).to(device).eval()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\transformers\modeling_utils.py", line 3157, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\tools\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: Allocation on device 

2025-02-06T08:38:42.251916 - Got an OOM, unloading all loaded models.
2025-02-06T08:38:42.259679 - Prompt executed in 72.09 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"last_node_id":25,"last_link_id":43,"nodes":[{"id":19,"type":"LoadImage","pos":[-300,-110],"size":[320,320],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[42],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_temp_gslhb_00067_.png","image"]},{"id":25,"type":"JanusImageUnderstanding","pos":[100,10],"size":[400,236],"flags":{},"order":3,"mode":0,"inputs":[{"name":"model","type":"JANUS_MODEL","link":40,"label":"model"},{"name":"processor","type":"JANUS_PROCESSOR","link":41,"label":"processor"},{"name":"image","type":"IMAGE","link":42,"label":"image"}],"outputs":[{"name":"text","type":"STRING","links":[43],"label":"text"}],"properties":{"Node name for S&R":"JanusImageUnderstanding"},"widgets_values":["Describe this image in detail.",286196206414827,"randomize",0.1,0.95,512]},{"id":21,"type":"ShowText|pysssss","pos":[540,10],"size":[430,240],"flags":{},"order":5,"mode":0,"inputs":[{"name":"text","type":"STRING","link":43,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":["","This image features a cute, stylized deer with large, expressive eyes and a gentle smile. The deer has light brown fur with intricate patterns, and its ears are pointed and slightly curved outward. It has a pair of black headphones around its neck, giving it a modern, playful touch.\n\nBehind the deer, there is a vibrant rainbow arching across the image, with each color segment clearly visible. The rainbow adds a cheerful and whimsical element to the scene. Scattered around the rainbow are small black stars, enhancing the playful and magical atmosphere.\n\nBelow the deer, there is a cloud that partially frames the deer, and beneath the cloud, the word \"WAYTOAGI\" is written in bold, black, uppercase letters. The text is centered and adds a name or brand to the image.\n\nOverall, the image combines elements of nature, music, and fantasy, creating a whimsical and charming scene."]},{"id":16,"type":"PreviewImage","pos":[560,-350],"size":[250,260],"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":39,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":24,"type":"JanusImageGeneration","pos":[90,-340],"size":[400,240],"flags":{},"order":2,"mode":0,"inputs":[{"name":"model","type":"JANUS_MODEL","link":37,"label":"model"},{"name":"processor","type":"JANUS_PROCESSOR","link":38,"label":"processor"}],"outputs":[{"name":"images","type":"IMAGE","links":[39],"label":"images"}],"properties":{"Node name for S&R":"JanusImageGeneration"},"widgets_values":["A portrait photo of a girl",613299350692455,"fixed",1,5,1,0.95]},{"id":10,"type":"JanusModelLoader","pos":[-300,-290],"size":[315,102],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"model","type":"JANUS_MODEL","links":[37,40],"slot_index":0,"label":"model"},{"name":"processor","type":"JANUS_PROCESSOR","links":[38,41],"slot_index":1,"label":"processor"}],"properties":{"Node name for S&R":"JanusModelLoader"},"widgets_values":["deepseek-ai/Janus-Pro-1B"]}],"links":[[37,10,0,24,0,"JANUS_MODEL"],[38,10,1,24,1,"JANUS_PROCESSOR"],[39,24,0,16,0,"IMAGE"],[40,10,0,25,0,"JANUS_MODEL"],[41,10,1,25,1,"JANUS_PROCESSOR"],[42,19,0,25,2,"IMAGE"],[43,25,0,21,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[409.3333435058594,372.6666488647461]},"workspace_info":{"id":"fmD__XZpFj36_jkuHASUE"}},"version":0.4}


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by wsbagnsv1** [comment]
You got multigpu installed by any chance? It seems to cause mem alloc errors since very recently

**Comment by wsbagnsv1** [comment]
The weird part is yesterday around 6pm utc everything worked fine, I used your node to speed up the generation of a video with hunyuan from 16min to 1:30, which is insane (;

**Comment by yuhongye123** [comment]
requires the protobuf library but it was not found in your environment. Checkout the instructions on the installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones that match your environment. Please note that you may need to restart your runtime after installation.

________________________________
发件人: wsbagnsv1 ***@***.***>
发送时间: 2025年2月6日 12:17
收件人: comfyanonymous/ComfyUI ***@***.***>
抄送: yuhongye123 ***@***.***>; Author ***@***.***>
主题: Re: [comfyanonymous/ComfyUI] allocation on device (Issue #6716)


The weird part is yesterday around 6pm utc everything worked fine, I used your node to speed up the generation of a video with hunyuan from 16min to 1:30, which is insane (;

―

**Comment by tpatterson34** [comment]
I am getting the same error. My system has 32GB RAM, 96GB vram (on SSD) configured. At the time of failure, the system did not exceed 54GB of utilization.  Protobuf is installed in the embedded python directory:
protobuf-5.29.3

**Comment by binary8888** [comment]
batch size太大

**Comment by mYUzE77** [comment]
i changed the game ready to studio driver so the control panel wasn't changed yet,.. after i set to GPU it's work,.. the error gone
