### ISSUE TITLE
Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

### ISSUE THREAD

**Issue by shahzaman900** [comfyanonymous/ComfyUI#6995]
### Expected Behavior

..

### Actual Behavior

..

### Steps to Reproduce

..

### Debug Logs

```powershell
..
```

**Comment by amayvarghese** [comment]
are you using a mac?

**Comment by shahzaman900** [comment]
yes

**Comment by ltdrdata** [comment]
https://studywarehouse.com/solution-trying-to-convert-float8_e4m3fn-to-the-mps-backend-but-it-does-not-have-support-for-that-dtype/

**Comment by shahzaman900** [comment]
did u resolve the issue ?

**Comment by MengDe-Cao** [comment]
how to solve this problem ?

**Comment by rogerganga** [comment]
I face the same error too

**Comment by jaekr84** [comment]
I have M1, and run with this line / python main.py --force-fp16 --use-split-cross-attention --cpu / and works for mee

**Comment by sayso10** [comment]
> I have M1, and run with this line / python main.py --force-fp16 --use-split-cross-attention --cpu / and works for mee

Could you please specify a little bit? Thx!

**Comment by jaekr84** [comment]
in your termial run with this lines python main.py --force-fp16 --use-split-cross-attention --cpu

**Comment by sayso10** [comment]
> in your termial run with this lines python main.py --force-fp16 --use-split-cross-attention --cpu

Thanks, but I got this:

/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'main.py': [Errno 2] No such file or directory

Did I miss something?

**Comment by sayso10** [comment]
> open you terminal and white cd [drag your ComfyUI folder] and run with main.py --force-fp16 --use-split-cross-attention --cpu

Thanks, but it said "no such file or directory"... Should I install or put anything in that folder in advance?

**Comment by khugomelo** [comment]
> > open you terminal and white cd [drag your ComfyUI folder] and run with main.py --force-fp16 --use-split-cross-attention --cpu
> 
> Thanks, but it said "no such file or directory"... Should I install or put anything in that folder in advance?

You do have to run this where you open comfy. How do you normally run it? I open terminal and navigate to where Comfy was installed. In my case "cd Applications/ComfyUI/" Then I do "source venv/bin/activate" to activate a virtual environment (Has to be setup before, use ChatGPT to help). And then I generally do "python3 main.py" Instead, I ran " python main.py --force-fp16 --use-split-cross-attention --cpu" as suggested by jakr84! It works!

**Comment by sayso10** [comment]
> > > open you terminal and white cd [drag your ComfyUI folder] and run with main.py --force-fp16 --use-split-cross-attention --cpu
> > 
> > 
> > Thanks, but it said "no such file or directory"... Should I install or put anything in that folder in advance?
> 
> You do have to run this where you open comfy. How do you normally run it? I open terminal and navigate to where Comfy was installed. In my case "cd Applications/ComfyUI/" Then I do "source venv/bin/activate" to activate a virtual environment (Has to be setup before, use ChatGPT to help). And then I generally do "python3 main.py" Instead, I ran " python main.py --force-fp16 --use-split-cross-attention --cpu" as suggested by jakr84! It works!

Hi, I installed comfy by its beta version for Mac, the way I open it was not that complex, like clicking the icon then it starts

**Comment by andrewdscott1984** [comment]
I've been using "python3 main.py --force-fp16 --use-split-cross-attention --cpu" and the process under the SamplerCustomAdvanced section is getting to about 20% and failing.  The error is "RuntimeError: mixed dtype (CPU): expect parameter to have scalar type of Float"

Can anybody assist?  Thanks!

**Comment by stereo3d** [comment]
same error.

**Comment by AlinBolcas** [comment]
Same issue. I can't seem to run 80% of what ComfyUI can do on Mac because of it.
No native support yet I guess.. ?

**Comment by KleinFelidae** [comment]
ai is not really designed to run on macs i dont think on a level apple intelligence is a failed project for a reason, its a divergent technology and uncompatible alot of the time these days, i mean you can do certain stuff that has been around a while and ported over and some could argue stuff about mlx but i dont think they are compatible. dont get me wrong i would love to be wrong but i am fairly certain there are bugs across the board that are unresolvable.

**Comment by huangsan2005** [comment]
> > open you terminal and white cd [drag your ComfyUI folder] and run with main.py --force-fp16 --use-split-cross-attention --cpu
> 
> Thanks, but it said "no such file or directory"... Should I install or put anything in that folder in advance?

ran "pip install -r requirements.txt"

**Comment by 22sparkz** [comment]
you can talk to me to my telegram @guilhem78 because I don't understand.

**Comment by ThilinaHewagama** [comment]
Issue still exists on mac, 
`Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.`

**Comment by matrixx136** [comment]
The idea that "AI isn't made for Mac" is a misconception. Python and major AI libraries like PyTorch run well on macOS, and Apple Silicon (M1/M2/M3) offers good performance with its Metal (MPS) GPU backend.

The specific issue many are encountering relates to newer FP8 (8-bit floating-point) model formats, particularly Float8_e4m3fn. The current MPS backend in PyTorch has limited or problematic support for this specific FP8 data type. This isn't a general GPU failure, but an incompatibility with this new, less common precision format. When a model uses it, you might see errors like "does not have support for that dtype" when trying to use the GPU.

Using flags like --force-fp16 --use-split-cross-attention --cpu is a workaround. The --cpu part bypasses the MPS FP8 issue by falling back to the CPU. As correctly pointed out, this is much slower and can lead to increased system RAM usage (potentially causing the process to be "killed" if memory runs out).

The most effective solution for this particular FP8 problem on Apple Silicon is to use an FP16 (16-bit floating-point) version of the model if available. This allows you to still leverage the GPU with a data type that MPS handles well.

**Comment by pushkarsingh32** [comment]
> --force-fp16 --use-split-cross-attention --cpu

I can see comfyui inside application folder. 

how can I start thing using terminal to give this command?

**Comment by johannespfeiffer** [comment]
For users of the Mac application:
Go to /Users/<username>/Documents/ComfyUI/user/default/comfy.settings.json and set `"Comfy.Server.LaunchArgs"` to
```
    "Comfy.Server.LaunchArgs": {"force-fp16": "", "use-split-cross-attention": "", "cpu": ""},
```

**Comment by ThilinaHewagama** [comment]
> For users of the Mac application: Go to `/Users/<username>/Documents/ComfyUI/user/default/comfy.settings.json` and set `"Comfy.Server.LaunchArgs"` to
> 
> ```
>     "Comfy.Server.LaunchArgs": {"force-fp16": "", "use-split-cross-attention": "", "cpu": ""},
> ```

Thank you @johannespfeiffer for the correct answer ❤️

**Comment by Jovanadeobaldia** [comment]
> For users of the Mac application: Go to `/Users/<username>/Documents/ComfyUI/user/default/comfy.settings.json` and set `"Comfy.Server.LaunchArgs"` to
> 
> ```
>     "Comfy.Server.LaunchArgs": {"force-fp16": "", "use-split-cross-attention": "", "cpu": ""},
> ```



Thanks so much! It's work for me, I have an M4 - Take time to generate the image, but without error! :)

**Comment by WiKiBIRD** [comment]
> For users of the Mac application: Go to `/Users/<username>/Documents/ComfyUI/user/default/comfy.settings.json` and set `"Comfy.Server.LaunchArgs"` to
> 
> ```
>     "Comfy.Server.LaunchArgs": {"force-fp16": "", "use-split-cross-attention": "", "cpu": ""},
> ```

Thanks bro! It works, takes much time to generate an image, how to boost it?

**Comment by paquinde** [comment]
> For users of the Mac application: Go to `/Users/<username>/Documents/ComfyUI/user/default/comfy.settings.json` and set `"Comfy.Server.LaunchArgs"` to
> 
> ```
>     "Comfy.Server.LaunchArgs": {"force-fp16": "", "use-split-cross-attention": "", "cpu": ""},
> ```

I'm glad I found this! But it does look like it's forcing this workflow into CPU only so it's extremely slow. Maybe I'll try removing the CPU part from the argument.

**Comment by Fleemo17** [comment]
Thank you Johannes for getting this to work on my Mac M1 Max. But good lord, it's been over a half an hour and my KSampler progress bar is at about 25% generating the tutorial swan image. Does this mean that Flux Kontext is out of reach for this M1 Mac user?

**Comment by Ghostkwebb** [comment]
> > For users of the Mac application: Go to `/Users/<username>/Documents/ComfyUI/user/default/comfy.settings.json` and set `"Comfy.Server.LaunchArgs"` to
> > ```
> >     "Comfy.Server.LaunchArgs": {"force-fp16": "", "use-split-cross-attention": "", "cpu": ""},
> > ```
> 
> I'm glad I found this! But it does look like it's forcing this workflow into CPU only so it's extremely slow. Maybe I'll try removing the CPU part from the argument.

Removing the CPU still gives the error, but the generation takes a significant amount of time (I'm on the app btw).

**Comment by johannespfeiffer** [comment]
Also, what helped me was to use fp16 models instead of fp8, so you don’t have to use the CPU fallback.

**Comment by Ghostkwebb** [comment]
> Also, what helped me was to use fp16 models instead of fp8, so you don’t have to use the CPU fallback.

Ooooooh, I shall try that, thank you very much. With the cpu argument or without it?

**Comment by budda** [comment]
> Also, what helped me was to use fp16 models instead of fp8, so you don’t have to use the CPU fallback.

it's a shame there is no fp16 diffusion model for flux1-dev-kontext 🙁

**Comment by Ghostkwebb** [comment]
> > Also, what helped me was to use fp16 models instead of fp8, so you don’t have to use the CPU fallback.
> 
> it's a shame there is no fp16 diffusion model for flux1-dev-kontext 🙁

There is though isn't there?

**Comment by A2beyond** [comment]
> Also, what helped me was to use fp16 models instead of fp8, so you don’t have to use the CPU fallback.

So what models do you use?

**Comment by lopkiloinm** [comment]
Check out this one: https://huggingface.co/mit-han-lab/nunchaku-flux.1-kontext-dev/blob/main/svdq-int4_r32-flux.1-kontext-dev.safetensors

**Comment by danboarder** [comment]
> Check out this one: https://huggingface.co/mit-han-lab/nunchaku-flux.1-kontext-dev/blob/main/svdq-int4_r32-flux.1-kontext-dev.safetensors

I tried this one in place of the flux1 kontext fp8 model, and I get this error on my M1 Max running the ComfyUI desktop app: 

UNETLoader
ERROR: Could not detect model type ... Documents/ComfyUI/models/diffusion_models/svdq-int4_r32-flux.1-kontext-dev.safetensors

Any suggestion? Thank you!

**Comment by NelsonRebelo** [comment]
> > Check out this one: https://huggingface.co/mit-han-lab/nunchaku-flux.1-kontext-dev/blob/main/svdq-int4_r32-flux.1-kontext-dev.safetensors
> 
> I tried this one in place of the flux1 kontext fp8 model, and I get this error on my M1 Max running the ComfyUI desktop app:
> 
> UNETLoader ERROR: Could not detect model type ... Documents/ComfyUI/models/diffusion_models/svdq-int4_r32-flux.1-kontext-dev.safetensors
> 
> Any suggestion? Thank you!

Following as I have the same issue.

**Comment by alfnielsen** [comment]
Why has this issue been closed?
It's not a solution to the problem, to just ignore the error, and run on the CPU instead!
(it doesn't make sense to run this model on Mac Silicon, if it does not use the GPU... Please don't say I need to clarify that 🫣😁)

**Comment by bbhxwl** [comment]
> Why has this issue been closed? It's not a solution to the problem, to just ignore the error, and run on the CPU instead! (it doesn't make sense to run this model on Mac Silicon, if it does not use the GPU... Please don't say I need to clarify that 🫣😁)

Can it be resolved?
