### ISSUE TITLE
XPU out of memory Error after LoadImage and KSampler

### ISSUE THREAD

**Issue by cedico** [comfyanonymous/ComfyUI#7004]
### Expected Behavior

Hi,
I expect to generate my image with some outpainting pads but it crashes systematically an error.

### Actual Behavior

Hi,
I'm using ComfYUI with Intel ARC A770 GPU, and when I load the default Workflow all works fine I can generate a new image.
But if I replace the "Empty latent image" node by these 3 nodes : LoadImage--PadImageForInpainting--VAEencode (OR same thing with: LoadImage--VAEencode), I obtain the Error:

`KSampler : XPU out of memory. Tried to allocate 128.00 GiB. GPU 0 has a total capacity of 15.56 GiB. Of the allocated memory 2.50 GiB is allocated by PyTorch, and 39.26 MiB is reserved by PyTorch but unallocated. Please use empty_cache to release all unoccupied cached memory.
`

Why 128GiB, is there any bug ? am I missing something ?

### Steps to Reproduce

I load the default Workflow in ComfyUI then I replace the "Empty latent image" node by these 3 nodes : LoadImage--PadImageForInpainting--VAEencode (OR same thing with: LoadImage--VAEencode)

### Debug Logs

```powershell
Error :
Requested to load AutoencoderKL
loaded completely 6372.3515625 159.55708122253418 True
scaled_dot_product_attention OOMed: switched to slice attention
out of memory error, increasing steps and trying again 4
Requested to load SD1ClipModel
loaded completely 14346.98505859375 235.84423828125 True
Requested to load BaseModel
loaded completely 13612.11984375 1639.4336013793945 True
0%| | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!! XPU out of memory. Tried to allocate 128.00 GiB. GPU 0 has a total capacity of 15.56 GiB. Of the allocated memory 2.90 GiB is allocated by PyTorch, and 47.65 MiB is reserved by PyTorch but unallocated. Please use empty_cache to release all unoccupied cached memory.
Traceback (most recent call last):
File "F:\AI\VideoComfy\ComfyUI\execution.py", line 327, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "F:\AI\VideoComfy\ComfyUI\execution.py", line 202, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "F:\AI\VideoComfy\ComfyUI\execution.py", line 174, in _map_node_over_list
process_inputs(input_dict, i)
File "F:\AI\VideoComfy\ComfyUI\execution.py", line 163, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "F:\AI\VideoComfy\ComfyUI\nodes.py", line 1540, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
File "F:\AI\VideoComfy\ComfyUI\nodes.py", line 1507, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
File "F:\AI\VideoComfy\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
raise e
File "F:\AI\VideoComfy\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
File "F:\AI\VideoComfy\ComfyUI\comfy\sample.py", line 45, in sample
samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 1110, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 1000, in sample
return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 985, in sample
output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "F:\AI\VideoComfy\ComfyUI\comfy\patcher_extension.py", line 110, in execute
return self.original(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 953, in outer_sample
output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 936, in inner_sample
samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
File "F:\AI\VideoComfy\ComfyUI\comfy\patcher_extension.py", line 110, in execute
return self.original(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 715, in sample
samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
File "C:\Python310\lib\site-packages\torch\utils_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\k_diffusion\sampling.py", line 161, in sample_euler
denoised = model(x, sigma_hat * s_in, **extra_args)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 379, in call
out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 916, in call
return self.predict_noise(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 919, in predict_noise
return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 359, in sampling_function
out = calc_cond_batch(model, conds, x, timestep, model_options)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 195, in calc_cond_batch
return executor.execute(model, conds, x_in, timestep, model_options)
File "F:\AI\VideoComfy\ComfyUI\comfy\patcher_extension.py", line 110, in execute
return self.original(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\samplers.py", line 308, in calc_cond_batch
output = model.apply_model(input_x, timestep, **c).chunk(batch_chunks)
File "F:\AI\VideoComfy\ComfyUI\comfy\model_base.py", line 132, in apply_model
return comfy.patcher_extension.WrapperExecutor.new_class_executor(
File "F:\AI\VideoComfy\ComfyUI\comfy\patcher_extension.py", line 110, in execute
return self.original(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\model_base.py", line 163, in _apply_model
model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
return forward_call(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 831, in forward
return comfy.patcher_extension.WrapperExecutor.new_class_executor(
File "F:\AI\VideoComfy\ComfyUI\comfy\patcher_extension.py", line 110, in execute
return self.original(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 873, in _forward
h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 44, in forward_timestep_embed
x = layer(x, context, transformer_options)
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
return forward_call(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\attention.py", line 796, in forward
x = block(x, context=context[i], transformer_options=transformer_options)
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
return forward_call(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\attention.py", line 683, in forward
n = self.attn1(n, context=context_attn1, value=value_attn1)
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
return forward_call(*args, **kwargs)
File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\attention.py", line 577, in forward
out = optimized_attention(q, k, v, self.heads, attn_precision=self.attn_precision)
File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\attention.py", line 455, in attention_pytorch
out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
torch.OutOfMemoryError: XPU out of memory. Tried to allocate 128.00 GiB. GPU 0 has a total capacity of 15.56 GiB. Of the allocated memory 2.90 GiB is allocated by PyTorch, and 47.65 MiB is reserved by PyTorch but unallocated. Please use empty_cache to release all unoccupied cached memory.

Got an OOM, unloading all loaded models.
Prompt executed in 6.09 seconds
```

**Comment by gambikules** [comment]
incrase your pagefile.sys to 30-40 go.

**Comment by cedico** [comment]
Thank you, but my pagefile.sys is actually 153 Go (after having rebooting) but I have still the same issue

**Comment by cedico** [comment]
Hi,
I've tried big pagefile.sys file size, but it failed each time.

Is it a bug ?

**Comment by simonlui** [comment]
It would be helpful if you could share a JSON workflow that is causing issues instead of talking about the nodes because I could not reproduce it with an A770 myself. Mind you the results are terrible but it did run without error.

![Image](https://github.com/user-attachments/assets/89d96e46-bf05-4c37-ae8a-d5f727ffb4ec)

**Comment by cedico** [comment]
Here is my Json file :

`{"last_node_id":18,"last_link_id":28,"nodes":[{"id":9,"type":"SaveImage","pos":[1493.727294921875,328.9999694824219],"size":[210,270],"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","localized_name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.15"},"widgets_values":["ComfyUI"]},{"id":8,"type":"VAEDecode","pos":[1248.9996337890625,173.45455932617188],"size":[210,46],"flags":{},"order":8,"mode":0,"inputs":[{"name":"samples","localized_name":"samples","type":"LATENT","link":7},{"name":"vae","localized_name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","localized_name":"IMAGE","type":"IMAGE","links":[9,10],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":11,"type":"VAEEncodeForInpaint","pos":[2046.2093505859375,63.01869201660156],"size":[340.20001220703125,98],"flags":{},"order":11,"mode":0,"inputs":[{"name":"pixels","localized_name":"pixels","type":"IMAGE","link":11},{"name":"vae","localized_name":"vae","type":"VAE","link":24},{"name":"mask","localized_name":"mask","type":"MASK","link":13}],"outputs":[{"name":"LATENT","localized_name":"LATENT","type":"LATENT","links":[14],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"VAEEncodeForInpaint"},"widgets_values":[6]},{"id":3,"type":"KSampler","pos":[902.929931640625,186],"size":[315,262],"flags":{},"order":7,"mode":0,"inputs":[{"name":"model","localized_name":"model","type":"MODEL","link":1},{"name":"positive","localized_name":"positive","type":"CONDITIONING","link":4},{"name":"negative","localized_name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","localized_name":"latent_image","type":"LATENT","link":26}],"outputs":[{"name":"LATENT","localized_name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"KSampler"},"widgets_values":[319712446390208,"fixed",20,8,"dpmpp_sde","karras",1]},{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","localized_name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","localized_name":"CONDITIONING","type":"CONDITIONING","links":[6,16],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":14,"type":"CheckpointLoaderSimple","pos":[1171.6669921875,-218.44393920898438],"size":[315,98],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","localized_name":"MODEL","type":"MODEL","links":[19],"slot_index":0},{"name":"CLIP","localized_name":"CLIP","type":"CLIP","links":[17],"slot_index":1},{"name":"VAE","localized_name":"VAE","type":"VAE","links":[21,24],"slot_index":2}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["cyberrealistic_v33-inpainting.safetensors"]},{"id":15,"type":"VAEDecode","pos":[2952.383544921875,-123.7530746459961],"size":[210,46],"flags":{},"order":13,"mode":0,"inputs":[{"name":"samples","localized_name":"samples","type":"LATENT","link":20},{"name":"vae","localized_name":"vae","type":"VAE","link":21}],"outputs":[{"name":"IMAGE","localized_name":"IMAGE","type":"IMAGE","links":[22],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":16,"type":"SaveImage","pos":[3273.15478515625,-130.28707885742188],"size":[315,270],"flags":{},"order":14,"mode":0,"inputs":[{"name":"images","localized_name":"images","type":"IMAGE","link":22}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.15"},"widgets_values":["ComfyUI"]},{"id":10,"type":"ImagePadForOutpaint","pos":[1604.7630615234375,68.74791717529297],"size":[315,174],"flags":{},"order":10,"mode":0,"inputs":[{"name":"image","localized_name":"image","type":"IMAGE","link":10}],"outputs":[{"name":"IMAGE","localized_name":"IMAGE","type":"IMAGE","links":[11],"slot_index":0},{"name":"MASK","localized_name":"MASK","type":"MASK","links":[13],"slot_index":1}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"ImagePadForOutpaint"},"widgets_values":[304,0,304,0,10]},{"id":12,"type":"KSampler","pos":[2498.846435546875,-134.01170349121094],"size":[315,262],"flags":{},"order":12,"mode":0,"inputs":[{"name":"model","localized_name":"model","type":"MODEL","link":19},{"name":"positive","localized_name":"positive","type":"CONDITIONING","link":15},{"name":"negative","localized_name":"negative","type":"CONDITIONING","link":16},{"name":"latent_image","localized_name":"latent_image","type":"LATENT","link":14}],"outputs":[{"name":"LATENT","localized_name":"LATENT","type":"LATENT","links":[20],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"KSampler"},"widgets_values":[736430874999987,"randomize",30,20,"dpmpp_sde","karras",1]},{"id":13,"type":"CLIPTextEncode","pos":[1625,-187.99996948242188],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","localized_name":"clip","type":"CLIP","link":17}],"outputs":[{"name":"CONDITIONING","localized_name":"CONDITIONING","type":"CONDITIONING","links":[15],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CLIPTextEncode"},"widgets_values":["a stunning forerest environment "]},{"id":6,"type":"CLIPTextEncode","pos":[418.9930725097656,127.43608093261719],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","localized_name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","localized_name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CLIPTextEncode"},"widgets_values":["a cute cat situated within a stunning forest environement surrounded by the beauty of the forest, with sunlight filtering through the trees, serene and captivating atmosphere"]},{"id":18,"type":"VAEEncodeForInpaint","pos":[493.32366943359375,676.9607543945312],"size":[340.20001220703125,98],"flags":{},"order":6,"mode":0,"inputs":[{"name":"pixels","localized_name":"pixels","type":"IMAGE","link":25},{"name":"vae","localized_name":"vae","type":"VAE","link":28},{"name":"mask","localized_name":"mask","type":"MASK","link":27}],"outputs":[{"name":"LATENT","localized_name":"LATENT","type":"LATENT","links":[26],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"VAEEncodeForInpaint"},"widgets_values":[6]},{"id":17,"type":"LoadImage","pos":[40.18556213378906,662.9107055664062],"size":[315,314],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","localized_name":"IMAGE","type":"IMAGE","links":[25],"slot_index":0},{"name":"MASK","localized_name":"MASK","type":"MASK","links":[27],"slot_index":1}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"LoadImage"},"widgets_values":["Firefly fresque de feu au sein d'un labirynthe 67301.jpg","image"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","localized_name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","localized_name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","localized_name":"VAE","type":"VAE","links":[8,28],"slot_index":2}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["DreamShaper_8_pruned.safetensors"]}],"links":[[1,4,0,3,0,"MODEL"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"],[10,8,0,10,0,"IMAGE"],[11,10,0,11,0,"IMAGE"],[13,10,1,11,2,"MASK"],[14,11,0,12,3,"LATENT"],[15,13,0,12,1,"CONDITIONING"],[16,7,0,12,2,"CONDITIONING"],[17,14,1,13,0,"CLIP"],[19,14,0,12,0,"MODEL"],[20,12,0,15,0,"LATENT"],[21,14,2,15,1,"VAE"],[22,15,0,16,0,"IMAGE"],[24,14,2,11,1,"VAE"],[25,17,0,18,0,"IMAGE"],[26,18,0,3,3,"LATENT"],[27,17,1,18,2,"MASK"],[28,4,2,18,1,"VAE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015782,"offset":[25.76630382222578,-185.37802907416062]}},"version":0.4}`

**Comment by cedico** [comment]
here is another JSON file : I've built the exact same workflow as you (see your image above) :

`{"last_node_id":23,"last_link_id":40,"nodes":[{"id":8,"type":"VAEDecode","pos":[1640.6749267578125,668.2035522460938],"size":[210,46],"flags":{},"order":8,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":36}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[38],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":23,"type":"PreviewImage","pos":[2027.0474853515625,688.0118408203125],"size":[210,26],"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":38}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":22,"type":"CLIPTextEncode","pos":[1231.7056884765625,341.31719970703125],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":34}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[39],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CLIPTextEncode"},"widgets_values":["Gret hills landscape with trees"]},{"id":6,"type":"CLIPTextEncode","pos":[571.8839111328125,256.8236083984375],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":33}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[40],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CLIPTextEncode"},"widgets_values":["text"]},{"id":17,"type":"LoadImage","pos":[-113.85548400878906,491.5661926269531],"size":[315,314],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[29],"slot_index":0},{"name":"MASK","type":"MASK","links":[],"slot_index":1}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"LoadImage"},"widgets_values":["Firefly fresque de feu au sein d'un labirynthe 67301.jpg","image"]},{"id":18,"type":"VAEEncodeForInpaint","pos":[744.616455078125,511.4725646972656],"size":[340.20001220703125,98],"flags":{},"order":6,"mode":0,"inputs":[{"name":"pixels","type":"IMAGE","link":31},{"name":"vae","type":"VAE","link":32},{"name":"mask","type":"MASK","link":30}],"outputs":[{"name":"LATENT","type":"LATENT","links":[26],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"VAEEncodeForInpaint"},"widgets_values":[6]},{"id":20,"type":"VAELoader","pos":[775.33740234375,724.9215087890625],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[32,36],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"VAELoader"},"widgets_values":["sdxl_vae.safetensors"]},{"id":21,"type":"CheckpointLoaderSimple","pos":[1061.44140625,120.11134338378906],"size":[315,98],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[35],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[33,34],"slot_index":1},{"name":"VAE","type":"VAE","links":null}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["epicrealismXL_vx1Finalkiss.safetensors"]},{"id":19,"type":"ImagePadForOutpaint","pos":[345.80377197265625,570.5109252929688],"size":[315,174],"flags":{},"order":3,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":29}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[31],"slot_index":0},{"name":"MASK","type":"MASK","links":[30],"slot_index":1}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"ImagePadForOutpaint"},"widgets_values":[0,0,16,24,50]},{"id":3,"type":"KSampler","pos":[1206.720947265625,684.5758056640625],"size":[315,262],"flags":{},"order":7,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":35},{"name":"positive","type":"CONDITIONING","link":39},{"name":"negative","type":"CONDITIONING","link":40},{"name":"latent_image","type":"LATENT","link":26}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.15","Node name for S&R":"KSampler"},"widgets_values":[953169201421482,"randomize",40,2,"deis","karras",1]}],"links":[[7,3,0,8,0,"LATENT"],[26,18,0,3,3,"LATENT"],[29,17,0,19,0,"IMAGE"],[30,19,1,18,2,"MASK"],[31,19,0,18,0,"IMAGE"],[32,20,0,18,1,"VAE"],[33,21,1,6,0,"CLIP"],[34,21,1,22,0,"CLIP"],[35,21,0,3,0,"MODEL"],[36,20,0,8,1,"VAE"],[38,8,0,23,0,"IMAGE"],[39,22,0,3,1,"CONDITIONING"],[40,6,0,3,2,"CONDITIONING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6209213230591555,"offset":[-22.284753268975308,-55.4034941360554]}},"version":0.4}`

**Comment by simonlui** [comment]
Yeah then it's not the workflow, it's your software environment. What version of Intel Extension for Pytorch/Pytorch nightly are you using?

**Comment by simonlui** [comment]
Nightly builds by their nature are unstable builds. You really need to be updating it on a very frequent basis if not daily because of the nature of its stability. I would try running that command again with a modification.
```
pip install --pre --upgrade torch torchvision torchaudio --index-url http://download.pytorch.org/whl/nightly/xpu
```
To update your environment and see if it has been solved. If it hasn't, you need to follow the 2nd part of the install instructions for the 2nd option which is the stable build with Intel's Extension for Pytorch. XPU support inside just Pytorch itself is very new without the extension.

**Comment by cedico** [comment]
I've tried the update with 1/ but the error is still present, and I have this **"out of memory error"** :

`[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
nightly_channel: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: xpu:0, offload device: cpu, dtype: torch.bfloat16
Requested to load AutoencoderKL
loaded completely 6372.3515625 159.55708122253418 True
scaled_dot_product_attention OOMed: switched to slice attention
out of memory error, increasing steps and trying again 4
out of memory error, increasing steps and trying again 8
out of memory error, increasing steps and trying again 16
out of memory error, increasing steps and trying again 32
out of memory error, increasing steps and trying again 64
out of memory error, increasing steps and trying again 128
Warning: Ran out of memory when regular VAE encoding, retrying with tiled VAE encoding.`

I can try 2/ if you think it will be better....

**Comment by cedico** [comment]
I've forgot to tell you than for the 1/ and to execute ComfyUI i was using the Windows CMD.exe command (not Anaconda).
I don't know if it is a problem ?

**Comment by cedico** [comment]
Simon, for the 2/ I would have another question if I may. Could you tell me the full installation script please ?

- Launch anaConda prompt in admin mode
- Git clone https://github.com/comfyanonymous/ComfyUI
- cd ComfyUI
- Put your SD checkpoints (the huge ckpt/safetensors files) in: models/checkpoints
  Put your VAE in: models/vae
- conda create -n ComfyUI python=3.11 libuv
- conda activate ComfyUI
- conda install libuv
- pip install torch==2.3.1.post0+cxx11.abi torchvision==0.18.1.post0+cxx11.abi torchaudio==2.3.1.post0+cxx11.abi intel-extension-for-pytorch==2.3.110.post0+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/ --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/

Is it correct, or am I forget anything?

**Comment by ltdrdata** [comment]
You didn't `pip install -r requirements.txt ` before `python main.py`

**Comment by simonlui** [comment]
> Is it apparently not correct, I am missing something?

You forgot to run the installation requirements for ComfyUI since you are installing it in a new environment. So before `python main.py`, you need to do `pip install -r requirements.txt`.

**Comment by cedico** [comment]
Thank you for your responses, but why is it not "_pip install -r requirements-**ipex**.txt_" ?

**Comment by simonlui** [comment]
> Thank you for your responses, but why is it not "_pip install -r requirements-**ipex**.txt_" ?

That file doesn't exist in ComfyUI's repository and ComfyUI also does not do hardware specific `requirements.txt` so you don't need to use a different file for Nvidia, AMD, Intel, etc. This is why the intructions specify you install Intel's version of Pytorch first or pip will not find Pytorch and install the Nvidia CUDA version by default.

**Comment by cedico** [comment]
Then well I run the flow in ComfyUI, I obtain this new Error :
`Error : VAEEncodeForInpaint : could not create an engine`

got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: xpu:0, offload device: cpu, dtype: torch.bfloat16
Requested to load AutoencoderKL
loaded completely 6372.3515625 159.55708122253418 True
2025-03-10 21:05:22,134 - _logger.py - IPEX - INFO - Currently split master weight for xpu only support sgd
2025-03-10 21:05:22,146 - _logger.py - IPEX - INFO - Conv BatchNorm folding failed during the optimize process.
2025-03-10 21:05:22,153 - _logger.py - IPEX - INFO - Linear BatchNorm folding failed during the optimize process.
onednn_verbose,info,oneDNN v3.5.3 (commit abbc771ddb7735e22309b75151c87ea9d48b620a)
onednn_verbose,info,cpu,runtime:threadpool,nthr:10
onednn_verbose,info,cpu,isa:Intel AVX2 with Intel DL Boost
onednn_verbose,info,gpu,runtime:DPC++
onednn_verbose,info,gpu,engine,0,backend:Level Zero,name:Intel(R) Arc(TM) A770 Graphics,driver_version:1.3.30398,binary_kernels:enabled
onednn_verbose,info,gpu,engine,1,backend:Level Zero,name:Intel(R) UHD Graphics 770,driver_version:1.3.31093,binary_kernels:enabled
onednn_verbose,info,graph,backend,0:dnnl_backend
onednn_verbose,info,experimental features are enabled
onednn_verbose,info,use batch_normalization stats one pass is enabled
onednn_verbose,primitive,info,template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,graph,info,template:operation,engine,partition_id,partition_kind,op_names,data_formats,logical_tensors,fpmath_mode,backend,exec_time
onednn_verbose,common,error,runtime,device not found in the given context
!!! Exception during processing !!! could not create an engine
Traceback (most recent call last):
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\nodes.py", line 391, in encode
    t = vae.encode(pixels)
        ^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\sd.py", line 569, in encode
    out = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\models\autoencoder.py", line 188, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 591, in forward
    h = self.conv_in(x)
        ^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\ops.py", line 101, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: could not create an engine

Prompt executed in 4.12 seconds
Exception in thread Thread-1 (prompt_worker):
Traceback (most recent call last):
  File "C:\anaconda3\envs\ComfyUI2\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\envs\ComfyUI2\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "F:\AI\VideoComfy\ComfyUI\main.py", line 208, in prompt_worker
    comfy.model_management.soft_empty_cache()
  File "F:\AI\VideoComfy\ComfyUI\comfy\model_management.py", line 1206, in soft_empty_cache
    torch.xpu.empty_cache()
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\intel_extension_for_pytorch\xpu\memory.py", line 21, in empty_cache
    intel_extension_for_pytorch._C._emptyCache()
RuntimeError: Queue cannot be constructed with the given context and device since the device is neither a member of the context nor a descendant of its member. -33 (PI_ERROR_INVALID_DEVICE)

**Comment by simonlui** [comment]
> Prompt executed in 4.12 seconds Exception in thread Thread-1 (prompt_worker): Traceback (most recent call last): File "C:\anaconda3\envs\ComfyUI2\Lib\threading.py", line 1045, in _bootstrap_inner self.run() File "C:\anaconda3\envs\ComfyUI2\Lib\threading.py", line 982, in run self._target(*self._args, **self._kwargs) File "F:\AI\VideoComfy\ComfyUI\main.py", line 208, in prompt_worker comfy.model_management.soft_empty_cache() File "F:\AI\VideoComfy\ComfyUI\comfy\model_management.py", line 1206, in soft_empty_cache torch.xpu.empty_cache() File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\intel_extension_for_pytorch\xpu\memory.py", line 21, in empty_cache intel_extension_for_pytorch._C._emptyCache() RuntimeError: Queue cannot be constructed with the given context and device since the device is neither a member of the context nor a descendant of its member. -33 (PI_ERROR_INVALID_DEVICE)

You have an Intel iGPU and are using Windows, right? It was not noted in the version of Intel's Extension for Pytorch you are using but later versions note the following at https://intel.github.io/intel-extension-for-pytorch/xpu/2.6.10+xpu/tutorials/known_issues.html where it states.

>Problem: RuntimeError: Can’t add devices across platforms to a single context. -33 (PI_ERROR_INVALID_DEVICE).
>Cause: If you run Intel® Extension for PyTorch* in a Windows environment where Intel® discrete GPU and integrated GPU co-exist, and the integrated GPU is not supported by Intel® Extension for PyTorch* but is wrongly identified as the first GPU platform.
>Solution: Disable the integrated GPU in your environment to work around. For long term, Intel® Graphics Driver will always enumerate the discrete GPU as the first device so that Intel® Extension for PyTorch* could provide the fastest device to end framework users in such co-exist scenario based on that.

You could technically use enumeration and ComfyUI's `--oneapi-device-selector=xpu:0` command line option to make sure it excludes it properly but disabling the iGPU is the easiest way.

**Comment by cedico** [comment]
you mean ?
`python main.py --oneapi-device-selector=xpu:0`

because when launching I obtain this error :

Set oneapi device selector to: xpu:0
Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.
C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "F:\AI\VideoComfy\ComfyUI\comfy\model_management.py", line 79, in <module>
    _ = torch.xpu.device_count()
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\xpu\__init__.py", line 57, in device_count
    return torch._C._xpu_getDeviceCount()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ONEAPI_DEVICE_SELECTOR parsing error. Backend is required but missing from "xpu:0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AI\VideoComfy\ComfyUI\main.py", line 136, in <module>
    import execution
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "F:\AI\VideoComfy\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "F:\AI\VideoComfy\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "F:\AI\VideoComfy\ComfyUI\comfy\sd.py", line 7, in <module>
    from comfy import model_management
  File "F:\AI\VideoComfy\ComfyUI\comfy\model_management.py", line 82, in <module>
    xpu_available = xpu_available or (hasattr(torch, "xpu") and torch.xpu.is_available())
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\xpu\__init__.py", line 63, in is_available
    return device_count() > 0
           ^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\xpu\__init__.py", line 57, in device_count
    return torch._C._xpu_getDeviceCount()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ONEAPI_DEVICE_SELECTOR parsing error. Backend is required but missing from "xpu:0"

**Comment by simonlui** [comment]
I made a typo, it's `gpu:0`, not xpu, sorry. but you should really be disabling your iGPU as the article mentions because that is the official fix and this is more a bandaid to hide it from the application.

**Comment by cedico** [comment]
>  but you should really be disabling your iGPU 

What do you mean by disibling my iGPU ? Initially I was configuring my ComfyUI to be optimized with my Intel A770 Gpu.
So I do'nt undertand...

> I made a typo, it's gpu:0, not xpu

After having made the above correction, I still have the same error :

python main.py --oneapi-device-selector=gpu:0
Set oneapi device selector to: gpu:0
Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended.
C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "F:\AI\VideoComfy\ComfyUI\comfy\model_management.py", line 79, in <module>
    _ = torch.xpu.device_count()
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\xpu\__init__.py", line 57, in device_count
    return torch._C._xpu_getDeviceCount()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ONEAPI_DEVICE_SELECTOR parsing error. Backend is required but missing from "gpu:0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AI\VideoComfy\ComfyUI\main.py", line 136, in <module>
    import execution
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "F:\AI\VideoComfy\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "F:\AI\VideoComfy\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "F:\AI\VideoComfy\ComfyUI\comfy\sd.py", line 7, in <module>
    from comfy import model_management
  File "F:\AI\VideoComfy\ComfyUI\comfy\model_management.py", line 82, in <module>
    xpu_available = xpu_available or (hasattr(torch, "xpu") and torch.xpu.is_available())
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\xpu\__init__.py", line 63, in is_available
    return device_count() > 0
           ^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\xpu\__init__.py", line 57, in device_count
    return torch._C._xpu_getDeviceCount()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ONEAPI_DEVICE_SELECTOR parsing error. Backend is required but missing from "gpu:0"

**Comment by simonlui** [comment]
Sorry forgot what we were dealing with here, and mixed OpenVINO syntax. It wants a backend, not the device. So we need `level_zero:0`.

**Comment by cedico** [comment]
Hi,
`python main.py --oneapi-device-selector=level_zero:0`

I've tried but I've still the first error back :


got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: xpu:0, offload device: cpu, dtype: torch.bfloat16
Requested to load AutoencoderKL
loaded completely 6372.3515625 159.55708122253418 True
2025-03-16 13:31:37,942 - _logger.py - IPEX - INFO - Currently split master weight for xpu only support sgd
2025-03-16 13:31:37,956 - _logger.py - IPEX - INFO - Conv BatchNorm folding failed during the optimize process.
2025-03-16 13:31:37,961 - _logger.py - IPEX - INFO - Linear BatchNorm folding failed during the optimize process.
!!! Exception during processing !!! Current platform can NOT allocate memory block with size larger than 4GB! Tried to allocate 5.46 GiB (GPU  0; 15.56 GiB total capacity; 556.67 MiB already allocated; 2.70 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI\VideoComfy\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\nodes.py", line 391, in encode
    t = vae.encode(pixels)
        ^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\sd.py", line 569, in encode
    out = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\models\autoencoder.py", line 188, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 602, in forward
    h = self.mid.attn_1(h)
        ^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\ComfyUI2\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 343, in forward
    h_ = self.optimized_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\VideoComfy\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 288, in pytorch_attention
    out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0.0, is_causal=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Current platform can NOT allocate memory block with size larger than 4GB! Tried to allocate 5.46 GiB (GPU  0; 15.56 GiB total capacity; 556.67 MiB already allocated; 2.70 GiB reserved in total by PyTorch)

Prompt executed in 4.86 seconds

**Comment by cedico** [comment]
Here is a JSON script which works fine and exploits my Intel GPU. So why the LoadImage Node still fails ?

`{
  "last_node_id": 16,
  "last_link_id": 24,
  "nodes": [
    {
      "id": 5,
      "type": "EmptyLatentImage",
      "pos": [
        473,
        609
      ],
      "size": [
        315,
        106
      ],
      "flags": {},
      "order": 0,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            2
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "EmptyLatentImage"
      },
      "widgets_values": [
        512,
        512,
        1
      ]
    },
    {
      "id": 9,
      "type": "SaveImage",
      "pos": [
        1493.727294921875,
        328.9999694824219
      ],
      "size": [
        210,
        270
      ],
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 9
        }
      ],
      "outputs": [],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15"
      },
      "widgets_values": [
        "ComfyUI"
      ]
    },
    {
      "id": 8,
      "type": "VAEDecode",
      "pos": [
        1248.9996337890625,
        173.45455932617188
      ],
      "size": [
        210,
        46
      ],
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 7
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 8
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            9,
            10
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "VAEDecode"
      },
      "widgets_values": []
    },
    {
      "id": 11,
      "type": "VAEEncodeForInpaint",
      "pos": [
        2046.2093505859375,
        63.01869201660156
      ],
      "size": [
        340.20001220703125,
        98
      ],
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "pixels",
          "type": "IMAGE",
          "link": 11
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 24
        },
        {
          "name": "mask",
          "type": "MASK",
          "link": 13
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            14
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "VAEEncodeForInpaint"
      },
      "widgets_values": [
        6
      ]
    },
    {
      "id": 3,
      "type": "KSampler",
      "pos": [
        902.929931640625,
        186
      ],
      "size": [
        315,
        262
      ],
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 1
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 4
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 6
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 2
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            7
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "KSampler"
      },
      "widgets_values": [
        319712446390208,
        "fixed",
        20,
        8,
        "dpmpp_sde",
        "karras",
        1
      ]
    },
    {
      "id": 7,
      "type": "CLIPTextEncode",
      "pos": [
        413,
        389
      ],
      "size": [
        425.27801513671875,
        180.6060791015625
      ],
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 5
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            6,
            16
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "text, watermark"
      ]
    },
    {
      "id": 4,
      "type": "CheckpointLoaderSimple",
      "pos": [
        26,
        474
      ],
      "size": [
        315,
        98
      ],
      "flags": {},
      "order": 1,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            1
          ],
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            3,
            5
          ],
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            8
          ],
          "slot_index": 2
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "DreamShaper_8_pruned.safetensors"
      ]
    },
    {
      "id": 14,
      "type": "CheckpointLoaderSimple",
      "pos": [
        1171.6669921875,
        -218.44393920898438
      ],
      "size": [
        315,
        98
      ],
      "flags": {},
      "order": 2,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            19
          ],
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            17
          ],
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            21,
            24
          ],
          "slot_index": 2
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "cyberrealistic_v33-inpainting.safetensors"
      ]
    },
    {
      "id": 15,
      "type": "VAEDecode",
      "pos": [
        2952.383544921875,
        -123.7530746459961
      ],
      "size": [
        210,
        46
      ],
      "flags": {},
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 20
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 21
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            22
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "VAEDecode"
      }
    },
    {
      "id": 16,
      "type": "SaveImage",
      "pos": [
        3273.15478515625,
        -130.28707885742188
      ],
      "size": [
        315,
        270
      ],
      "flags": {},
      "order": 13,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 22
        }
      ],
      "outputs": [],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15"
      },
      "widgets_values": [
        "ComfyUI"
      ]
    },
    {
      "id": 10,
      "type": "ImagePadForOutpaint",
      "pos": [
        1604.7630615234375,
        68.74791717529297
      ],
      "size": [
        315,
        174
      ],
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "image",
          "type": "IMAGE",
          "link": 10
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            11
          ],
          "slot_index": 0
        },
        {
          "name": "MASK",
          "type": "MASK",
          "links": [
            13
          ],
          "slot_index": 1
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "ImagePadForOutpaint"
      },
      "widgets_values": [
        304,
        0,
        304,
        0,
        10
      ]
    },
    {
      "id": 12,
      "type": "KSampler",
      "pos": [
        2498.846435546875,
        -134.01170349121094
      ],
      "size": [
        315,
        262
      ],
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 19
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 15
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 16
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 14
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            20
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "KSampler"
      },
      "widgets_values": [
        567336106876451,
        "randomize",
        30,
        20,
        "dpmpp_sde",
        "karras",
        1
      ]
    },
    {
      "id": 13,
      "type": "CLIPTextEncode",
      "pos": [
        1625,
        -187.99996948242188
      ],
      "size": [
        422.84503173828125,
        164.31304931640625
      ],
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 17
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            15
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "a stunning forerest environment "
      ]
    },
    {
      "id": 6,
      "type": "CLIPTextEncode",
      "pos": [
        418.9930725097656,
        127.43608093261719
      ],
      "size": [
        422.84503173828125,
        164.31304931640625
      ],
      "flags": {},
      "order": 3,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 3
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            4
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "cnr_id": "comfy-core",
        "ver": "0.3.15",
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "a cute cat situated within a stunning forest environement surrounded by the beauty of the forest, with sunlight filtering through the trees, serene and captivating atmosphere"
      ]
    }
  ],
  "links": [
    [
      1,
      4,
      0,
      3,
      0,
      "MODEL"
    ],
    [
      2,
      5,
      0,
      3,
      3,
      "LATENT"
    ],
    [
      3,
      4,
      1,
      6,
      0,
      "CLIP"
    ],
    [
      4,
      6,
      0,
      3,
      1,
      "CONDITIONING"
    ],
    [
      5,
      4,
      1,
      7,
      0,
      "CLIP"
    ],
    [
      6,
      7,
      0,
      3,
      2,
      "CONDITIONING"
    ],
    [
      7,
      3,
      0,
      8,
      0,
      "LATENT"
    ],
    [
      8,
      4,
      2,
      8,
      1,
      "VAE"
    ],
    [
      9,
      8,
      0,
      9,
      0,
      "IMAGE"
    ],
    [
      10,
      8,
      0,
      10,
      0,
      "IMAGE"
    ],
    [
      11,
      10,
      0,
      11,
      0,
      "IMAGE"
    ],
    [
      13,
      10,
      1,
      11,
      2,
      "MASK"
    ],
    [
      14,
      11,
      0,
      12,
      3,
      "LATENT"
    ],
    [
      15,
      13,
      0,
      12,
      1,
      "CONDITIONING"
    ],
    [
      16,
      7,
      0,
      12,
      2,
      "CONDITIONING"
    ],
    [
      17,
      14,
      1,
      13,
      0,
      "CLIP"
    ],
    [
      19,
      14,
      0,
      12,
      0,
      "MODEL"
    ],
    [
      20,
      12,
      0,
      15,
      0,
      "LATENT"
    ],
    [
      21,
      14,
      2,
      15,
      1,
      "VAE"
    ],
    [
      22,
      15,
      0,
      16,
      0,
      "IMAGE"
    ],
    [
      24,
      14,
      2,
      11,
      1,
      "VAE"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {
    "ds": {
      "scale": 0.6830134553650712,
      "offset": [
        -2448.298942895511,
        181.0216408156103
      ]
    }
  },
  "version": 0.4
}`

**Comment by simonlui** [comment]
^^^ RuntimeError: Current platform can NOT allocate memory block with size larger than 4GB! Tried to allocate 5.46 GiB (GPU 0; 15.56 GiB total capacity; 556.67 MiB already allocated; 2.70 GiB reserved in total by PyTorch)
> 
> Prompt executed in 4.86 seconds

This is saying the same thing but is different. The Ksampler showed the error in your first example. In this one, the GPU runtime showing the error which is an improvement because you are no longer trying to allocate 128 GiB and you are on the right track. The error message shown is valid as it's a known issue that only 4GB of VRAM is addressable at any one point with Intel Alchemist cards right now, which should be fixed in the next release of Pytorch coming out after the recent Intel Extension for Pytorch release (v2.7). You may need to choose lower resolution image in order to fit it into 4GB of VRAM to actually run it or use `--lowvram` with ComfyUI to make it work. The image I used in my example that I showed you is 427x320.

**Comment by cedico** [comment]
Hi,
Well done ! it works fine now. Thanks a lot :-)

**Comment by cedico** [comment]
@simonlui , could you confirm me that after the arriving of the next release of "Intel Extension for Pytorch", I will be able to work with 1024x1024 images (or more) ?

**Comment by simonlui** [comment]
It is something Intel said they would do in the next release, there is no guarantee it makes the cut as it has yet to happen. If it happens, yeah, it should be possible.

**Comment by cedico** [comment]
Thanks you, that's a good news

I would have a last question (asked few days ago, above).
You've shown me how to launch ComfyUI with the Option-2 method and "Anaconda Prompt":

- Launch AnaConda Prompt in admin mode
- Git clone https://github.com/comfyanonymous/ComfyUI
- cd ComfyUI
- Put your SD checkpoints (the huge ckpt/safetensors files) in: models/checkpoints
- Put your VAE in: models/vae
- conda create -n ComfyUI python=3.11 libuv
- conda activate ComfyUI
- conda install libuv
- pip install torch==2.3.1.post0+cxx11.abi torchvision==0.18.1.post0+cxx11.abi torchaudio==2.3.1.post0+cxx11.abi intel-extension-for-pytorch==2.3.110.post0+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/ --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/
- pip install -r requirements.txt
- python main.py

**Question:** which commands would you use (if it is possible) to run ComfyUI with CMD.exe please ?

**Comment by simonlui** [comment]
I wouldn't. It's a bad idea to leave conda out of the mix because of the complex dependencies you need to run Intel GPUs with ComfyUI. If I typed it out, it would probably take more words than I have written so far here so I won't do that.

**Comment by cedico** [comment]
Your answer suits me perfectly, I just wanted to be sure that I understood the need to absolutely use Conda rather than CMD.
Thanks again :-)
