### ISSUE TITLE
Desktop ComfyUI (Windows) executable won't accept parameters on it's commandline

### ISSUE THREAD

**Issue by C-Denninger** [comfyanonymous/ComfyUI#7087]
### Your question

**Situation**
I'm new to ComfyUI and installed it in Windows 11 to run in the _Desktop_ ComfyUI version.
Since my NVIDIA GPU needs the '--disable-cuda-malloc' argument I have to add this to the program's startup. According to [README.md](https://github.com/hiddenswitch/ComfyUI/blob/master/README.md) the argument can be added to the command line, but that does not seem to work. 

1. At first, I changed _ComfyUI.exe_ in _ComfyUI.exe --disable-cuda-malloc_ in the link on my desktop (see the image included).
2. Secondly, I tried to run the program from the DOS-prompt. Again using the _ComfyUI.exe --disable-cuda-malloc_ command line. Also with no results. The program starts, but is running without the '--disable-cuda-malloc' argument.
What I _could_ see in the DOS-prompt however is an extra log, maybe someone here can analyze?
I added the full _DOS-prompt-log_ below here. 

Note that running the command line _ComfyUI.exe -h_ or _--help_ also _only_ starts the program and does _not_ display the [program syntaxis](https://github.com/hiddenswitch/ComfyUI/blob/master/README.md).
With the _portable_ version I have no problem running and creating images (as commenteed in #6843).

**Programs and hardware**
- ComfyUI version: 0.3.18
- ComfyUI_frontend version: 1.10.17
- Python version: 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
- Embedded Python: false
- Pytorch version: 2.6.0+cu126
- RAM total: 35.85 GB
- NVIDIA GeForce MX110
NVIDIA App-version: 11.0.2.337
Driver version: Game Ready - 572.60 - Thu Feb 27, 2025
Total graphic memory: 20.405 MB ≈ 20 GB
Dedicated graphic memory: 2.048 MB ≈ 2 GB GDDR5
- (Dutch) Windows 11 Home, version: 24H2 (Build 26100.3323).

**Related articles:**
- At first, I thought this issue was described in #6843. But that was not the case, that issue is about the _Portable_ ComfyUI version. Not the _Desktop_ version I'm using. 
- Adding the '--disable-cuda-malloc' argument to the _Portable_ version's 'run_nvidia_gpu.bat' is as described in  #1845

## Command in the DOS-prompt
C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\ComfyUI.exe --disable-cuda-malloc

## DOS-prompt-log
15:16:49.173 > Starting app v0.4.26
15:16:49.180 > Initializing Sentry
15:16:49.414 > App ready
15:16:49.419 > Queueing event desktop:app_ready with properties null
15:16:49.422 > Getting config: windowStyle
15:16:49.423 > Getting config: installState
15:16:51.766 > Getting config: installState
15:16:51.766 > Getting config: basePath
15:16:51.769 > Getting config: selectedDevice
15:16:51.769 > Using uv at C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\uv\win\uv.exe
15:16:51.770 > Install state: installed
15:16:51.771 > Validating installation. Recorded state: [installed]
15:16:51.771 > Getting config: basePath
15:16:51.773 > Running direct process command: pip install --dry-run -r C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\requirements.txt
15:16:51.774 > Running command: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\uv\win\uv.exe pip install --dry-run -r C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\requirements.txt in D:\ComfyUI
Audited 21 packages in 16ms
Would make no changes
15:16:52.089 > Running direct process command: pip install --dry-run -r C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt
15:16:52.090 > Running command: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\uv\win\uv.exe pip install --dry-run -r C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt in D:\ComfyUI
Audited 11 packages in 10ms
Would make no changes
15:16:52.444 > Validation result: isValid:true, state:installed {
  inProgress: false,
  installState: 'installed',
  basePath: 'OK',
  venvDirectory: 'OK',
  pythonInterpreter: 'OK',
  uv: 'OK',
  pythonPackages: 'OK',
  git: 'OK',
  vcRedist: 'OK'
}
15:16:52.447 > Setting up GPU context
15:16:53.980 > Getting config: versionConsentedMetrics
15:16:53.981 > Tracking desktop:app_ready with properties {
  distinct_id: '83b30f99-60f5-4479-b3a4-97f95d66b694',
  time: 1741184209419,
  '$os': 'win32'
}
15:16:54.007 > Initializing todesktop
15:16:54.014 > Server start
15:16:54.020 > Tracking comfyui:server_start_start with properties {
  distinct_id: '83b30f99-60f5-4479-b3a4-97f95d66b694',
  time: 1741184214020,
  '$os': 'win32'
}
15:16:54.036 > Running command: D:\ComfyUI\.venv\Scripts\python.exe C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py --user-directory D:\ComfyUI\user --input-directory D:\ComfyUI\input --output-directory D:\ComfyUI\output --front-end-root C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app --base-directory D:\ComfyUI --extra-model-paths-config C:\Users\%UserName%\AppData\Roaming\ComfyUI\extra_models_config.yaml --log-stdout --listen 127.0.0.1 --port 8000 in D:\ComfyUI
15:16:54.074 > Received renderer-ready message!
15:16:54.075 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.077 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.078 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.079 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.080 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.081 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.082 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.082 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.083 > Sending queued message {
  channel: 'validation-update',
  data: {
    inProgress: false,
    installState: 'installed',
    basePath: 'OK',
    venvDirectory: 'OK',
    pythonInterpreter: 'OK',
    uv: 'OK',
    pythonPackages: 'OK',
    git: 'OK',
    vcRedist: 'OK'
  }
}
15:16:54.084 > Sending queued message { channel: 'loading-progress', data: { status: 'starting-server' } }
Adding extra search path custom_nodes D:\ComfyUI\custom_nodes
Adding extra search path download_model_base D:\ComfyUI\models
15:16:54.776 > Adding extra search path custom_nodes D:\ComfyUI\custom_nodes
Adding extra search path download_model_base D:\ComfyUI\models
Adding extra search path custom_nodes C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
Setting output directory to: D:\ComfyUI\output
Setting input directory to: D:\ComfyUI\input
Setting user directory to: D:\ComfyUI\user
15:16:54.778 > Adding extra search path custom_nodes C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
Setting output directory to: D:\ComfyUI\output
Setting input directory to: D:\ComfyUI\input
Setting user directory to: D:\ComfyUI\user

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
15:16:59.183 > [START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.

** ComfyUI startup time: 2025-03-05 15:16:59.183
** Platform: Windows
** Python version: 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
** Python executable: D:\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
** ComfyUI Base Folder Path: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
** User directory: D:\ComfyUI\user
15:16:59.186 > ** ComfyUI startup time: 2025-03-05 15:16:59.183
** Platform: Windows
** Python version: 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
** Python executable: D:\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
** ComfyUI Base Folder Path: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI
** User directory: D:\ComfyUI\user
** ComfyUI-Manager config path:
15:16:59.481 > ** ComfyUI-Manager config path:
 D:\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: D:\ComfyUI\user\comfyui.log
15:16:59.483 >  D:\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: D:\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
15:17:03.130 >
Prestartup times for custom nodes:
   8.4 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
15:17:03.132 >    8.4 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
Checkpoint files will always be loaded safely.
15:17:05.482 > Checkpoint files will always be loaded safely.
Total VRAM 2048 MB, total RAM 36715 MB
15:17:05.914 > Total VRAM 2048 MB, total RAM 36715 MB

pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce MX110 : cudaMallocAsync
15:17:05.915 > pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce MX110 : cudaMallocAsync

Using pytorch attention
15:17:07.658 > Using pytorch attention

ComfyUI version: 0.3.18
15:17:09.444 > ComfyUI version: 0.3.18

[Prompt Server] web root: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
15:17:09.485 > [Prompt Server] web root: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app

### Loading: ComfyUI-Manager (V3.27)
15:17:10.041 > ### Loading: ComfyUI-Manager (V3.27)

[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
15:17:10.043 > [ComfyUI-Manager] network_mode: public
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)

Import times for custom nodes:
15:17:10.051 >
Import times for custom nodes:
   0.0 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager

WARNING: this card most likely does not support cuda-malloc, if you get "CUDA error" please run ComfyUI with: --disable-cuda-malloc
15:17:10.053 >    0.0 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
WARNING: this card most likely does not support cuda-malloc, if you get "CUDA error" please run ComfyUI with: --disable-cuda-malloc

Starting server
15:17:10.072 > Starting server
To see the GUI go to: http://127.0.0.1:8000
15:17:10.074 > To see the GUI go to: http://127.0.0.1:8000

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
15:17:10.096 > [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
15:17:10.108 > [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
15:17:10.159 > [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
15:17:10.203 > Python server is ready
15:17:10.204 > Tracking comfyui:server_start_end with properties {
  distinct_id: '83b30f99-60f5-4479-b3a4-97f95d66b694',
  time: 1741184230204,
  '$os': 'win32'
}
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
15:17:10.369 > [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
15:17:10.411 > [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
FETCH ComfyRegistry Data: 5/36
15:17:13.500 > FETCH ComfyRegistry Data: 5/36
FETCH ComfyRegistry Data: 10/36
15:17:17.084 > FETCH ComfyRegistry Data: 10/36
got prompt
15:17:19.518 > got prompt
model weight dtype torch.float32, manual cast: None
15:17:19.891 > model weight dtype torch.float32, manual cast: None
model_type EPS
15:17:19.893 > model_type EPS
FETCH ComfyRegistry Data: 15/36
15:17:20.407 > FETCH ComfyRegistry Data: 15/36
Using pytorch attention in VAE
15:17:21.143 > Using pytorch attention in VAE
Using pytorch attention in VAE
15:17:21.148 > Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
15:17:21.321 > VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
Requested to load SD1ClipModel
15:17:21.476 > Requested to load SD1ClipModel
loaded completely 9.5367431640625e+25 235.84423828125 True
15:17:21.487 > loaded completely 9.5367431640625e+25 235.84423828125 True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
15:17:21.492 > CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16

!!! Exception during processing !!! CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
15:17:22.857 > !!! Exception during processing !!! CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1542, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1509, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sample.py", line 43, in sample
    sampler = comfy.samplers.KSampler(model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=denoise, model_options=model.model_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1060, in __init__
    self.set_steps(steps, denoise)
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1081, in set_steps
    self.sigmas = self.calculate_sigmas(steps).to(self.device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
15:17:22.862 > Traceback (most recent call last):
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1542, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1509, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sample.py", line 43, in sample
    sampler = comfy.samplers.KSampler(model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=denoise, model_options=model.model_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1060, in __init__
    self.set_steps(steps, denoise)
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1081, in set_steps
    self.sigmas = self.calculate_sigmas(steps).to(self.device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Prompt executed in 3.34 seconds
15:17:22.868 > Prompt executed in 3.34 seconds
15:17:23.140 > Tracking execution with properties {
  distinct_id: '83b30f99-60f5-4479-b3a4-97f95d66b694',
  time: 1741184243140,
  '$os': 'win32',
  status: 'failed'
}
FETCH ComfyRegistry Data: 20/36
15:17:23.908 > FETCH ComfyRegistry Data: 20/36
15:17:24.012 > @todesktop/runtime: alwaysResolve: Promise timed out after 30000ms
15:17:24.078 > @todesktop/runtime: AutoUpdater: Setting up UpdaterAgent
15:17:24.078 > @todesktop/runtime: AutoUpdater: UpdaterAgent: UpdaterAgent: _uninstallSquirrelWindowsAppIfItExists()
15:17:24.079 > @todesktop/runtime: AutoUpdater: UpdaterAgent: UpdaterAgent: Does Squirrel.Windows uninstall marker exist? false C:\Users\%UserName%\AppData\Local\@comfyorg\comfyui-electron\.shouldUninstall
15:17:24.079 > @todesktop/runtime: AutoUpdater: checking for update on interval
15:17:24.079 > @todesktop/runtime: AutoUpdater: checking for update on launch
15:17:24.079 > @todesktop/runtime: AutoUpdater: _check called {
  source: 'auto-check-on-launch',
  pendingCheckSources: [ 'auto-check-on-launch' ]
}
15:17:24.080 > @todesktop/runtime: AutoUpdater: _actuallyPerformCheck called
15:17:24.080 > @todesktop/runtime: Checking for update
15:17:24.081 > @todesktop/runtime: AutoUpdater: checking-for-update
15:17:25.226 > @todesktop/runtime: Update for version 0.4.26 is not available (latest version: 0.4.26, downgrade is allowed).
15:17:25.227 > @todesktop/runtime: AutoUpdater: update-not-available {
  version: '0.4.26',
  files: [
    {
      url: 'ComfyUI Setup 0.4.26 - Build 2503047uzec04mv-x64.exe',
      sha512: '9KyjTjvdSPKaX4xtHjcnUSktQoKES7kqKBZ2I4meCVRdDvStKeT6pLL3N33flNbpSPbJJNiwq1vhR6Ii0AvKpg==',
      size: 149735432
    }
  ],
  path: 'ComfyUI Setup 0.4.26 - Build 2503047uzec04mv-x64.exe',
  sha512: '9KyjTjvdSPKaX4xtHjcnUSktQoKES7kqKBZ2I4meCVRdDvStKeT6pLL3N33flNbpSPbJJNiwq1vhR6Ii0AvKpg==',
  releaseDate: '2025-03-04T01:04:14.072Z'
}
15:17:25.228 > @todesktop/runtime: AutoUpdater: UpdaterAgent: UpdaterAgent: Analysing autoUpdater.checkForUpdates result {
  currentVersion: '0.4.26',
  latestVersion: '0.4.26',
  updateInfo: {
    version: '0.4.26',
    files: [ [Object] ],
    path: 'ComfyUI Setup 0.4.26 - Build 2503047uzec04mv-x64.exe',
    sha512: '9KyjTjvdSPKaX4xtHjcnUSktQoKES7kqKBZ2I4meCVRdDvStKeT6pLL3N33flNbpSPbJJNiwq1vhR6Ii0AvKpg==',
    releaseDate: '2025-03-04T01:04:14.072Z'
  }
}
15:17:25.229 > @todesktop/runtime: AutoUpdater: No update available
FETCH ComfyRegistry Data: 25/36
15:17:27.355 > FETCH ComfyRegistry Data: 25/36
FETCH ComfyRegistry Data: 30/36
15:17:30.841 > FETCH ComfyRegistry Data: 30/36
FETCH ComfyRegistry Data: 35/36
15:17:34.207 > FETCH ComfyRegistry Data: 35/36
FETCH ComfyRegistry Data [DONE]
15:17:35.352 > FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
15:17:35.419 > [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes

nightly_channel:
15:17:35.484 > nightly_channel:
https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
15:17:35.486 > https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

 [DONE]
15:17:35.526 >  [DONE]

[ComfyUI-Manager] All startup tasks have been completed.
15:17:35.595 > [ComfyUI-Manager] All startup tasks have been completed.
15:19:11.855 > App window closed.
15:19:11.882 > Quitting ComfyUI because window all closed
15:19:11.885 > Before-quit: Killing Python server
15:19:11.887 > Killing ComfyUI python server.
15:19:11.888 > Tracking desktop:app_quit with properties {
  distinct_id: '83b30f99-60f5-4479-b3a4-97f95d66b694',
  time: 1741184351888,
  '$os': 'win32',
  reason: {},
  exitCode: 0
}
15:19:11.895 > Python process exited with code null and signal SIGTERM

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 3
- **Node Type:** KSampler
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

## Stack Trace

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1542, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1509, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sample.py", line 43, in sample
    sampler = comfy.samplers.KSampler(model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=denoise, model_options=model.model_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1060, in __init__
    self.set_steps(steps, denoise)

  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1081, in set_steps
    self.sigmas = self.calculate_sigmas(steps).to(self.device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.18
- **Arguments:** C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py --user-directory D:\ComfyUI\user --input-directory D:\ComfyUI\input --output-directory D:\ComfyUI\output --front-end-root C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app --base-directory D:\ComfyUI --extra-model-paths-config C:\Users\%UserName%\AppData\Roaming\ComfyUI\extra_models_config.yaml --log-stdout --listen 127.0.0.1 --port 8000
- **OS:** nt
- **Python Version:** 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.6.0+cu126
## Devices

- **Name:** cuda:0 NVIDIA GeForce MX110 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 2147352576
  - **VRAM Free:** 1768056423
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs

2025-03-05T15:16:54.776054 - Adding extra search path custom_nodes D:\ComfyUI\custom_nodes
2025-03-05T15:16:54.776054 - Adding extra search path download_model_base D:\ComfyUI\models
2025-03-05T15:16:54.776054 - Adding extra search path custom_nodes C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
2025-03-05T15:16:54.776054 - Setting output directory to: D:\ComfyUI\output
2025-03-05T15:16:54.776054 - Setting input directory to: D:\ComfyUI\input
2025-03-05T15:16:54.776054 - Setting user directory to: D:\ComfyUI\user
2025-03-05T15:16:55.494915 - [START] Security scan2025-03-05T15:16:55.494915 - 
2025-03-05T15:16:59.059004 - [DONE] Security scan2025-03-05T15:16:59.059004 - 
2025-03-05T15:16:59.183734 - ## ComfyUI-Manager: installing dependencies done.2025-03-05T15:16:59.183734 - 
2025-03-05T15:16:59.183734 - ** ComfyUI startup time:2025-03-05T15:16:59.183734 -  2025-03-05T15:16:59.183734 - 2025-03-05 15:16:59.1832025-03-05T15:16:59.183734 - 
2025-03-05T15:16:59.183734 - ** Platform:2025-03-05T15:16:59.183734 -  2025-03-05T15:16:59.183734 - Windows2025-03-05T15:16:59.183734 - 
2025-03-05T15:16:59.183734 - ** Python version:2025-03-05T15:16:59.183734 -  2025-03-05T15:16:59.183734 - 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]2025-03-05T15:16:59.184755 - 
2025-03-05T15:16:59.184755 - ** Python executable:2025-03-05T15:16:59.184755 -  2025-03-05T15:16:59.184755 - D:\ComfyUI\.venv\Scripts\python.exe2025-03-05T15:16:59.184755 - 
2025-03-05T15:16:59.184755 - ** ComfyUI Path:2025-03-05T15:16:59.184755 -  2025-03-05T15:16:59.184755 - C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-03-05T15:16:59.184755 - 
2025-03-05T15:16:59.184755 - ** ComfyUI Base Folder Path:2025-03-05T15:16:59.184755 -  2025-03-05T15:16:59.184755 - C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-03-05T15:16:59.184755 - 
2025-03-05T15:16:59.184755 - ** User directory:2025-03-05T15:16:59.184755 -  2025-03-05T15:16:59.184755 - D:\ComfyUI\user2025-03-05T15:16:59.184755 - 
2025-03-05T15:16:59.481104 - ** ComfyUI-Manager config path:2025-03-05T15:16:59.481104 -  2025-03-05T15:16:59.482234 - D:\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-03-05T15:16:59.482234 - 
2025-03-05T15:16:59.482234 - ** Log path:2025-03-05T15:16:59.482234 -  2025-03-05T15:16:59.482234 - D:\ComfyUI\user\comfyui.log2025-03-05T15:16:59.482234 - 
2025-03-05T15:17:03.130976 - 
Prestartup times for custom nodes:
2025-03-05T15:17:03.130976 -    8.4 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-03-05T15:17:03.130976 - 
2025-03-05T15:17:05.482083 - Checkpoint files will always be loaded safely.
2025-03-05T15:17:05.914687 - Total VRAM 2048 MB, total RAM 36715 MB
2025-03-05T15:17:05.914687 - pytorch version: 2.6.0+cu126
2025-03-05T15:17:05.915720 - Set vram state to: NORMAL_VRAM
2025-03-05T15:17:05.915720 - Device: cuda:0 NVIDIA GeForce MX110 : cudaMallocAsync
2025-03-05T15:17:07.657708 - Using pytorch attention
2025-03-05T15:17:09.445715 - ComfyUI version: 0.3.18
2025-03-05T15:17:09.485574 - [Prompt Server] web root: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
2025-03-05T15:17:10.042358 - ### Loading: ComfyUI-Manager (V3.27)
2025-03-05T15:17:10.043364 - [ComfyUI-Manager] network_mode: public
2025-03-05T15:17:10.043364 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
2025-03-05T15:17:10.051480 - 
Import times for custom nodes:
2025-03-05T15:17:10.052636 -    0.0 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-03-05T15:17:10.052636 -    0.0 seconds: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-03-05T15:17:10.052636 - 
2025-03-05T15:17:10.052636 - 
WARNING: this card most likely does not support cuda-malloc, if you get "CUDA error" please run ComfyUI with: --disable-cuda-malloc

2025-03-05T15:17:10.073001 - Starting server

2025-03-05T15:17:10.073001 - To see the GUI go to: http://127.0.0.1:8000
2025-03-05T15:17:10.096336 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-03-05T15:17:10.108397 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-03-05T15:17:10.159730 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-03-05T15:17:10.223342 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-03-05T15:17:10.411650 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-03-05T15:17:13.500866 - FETCH ComfyRegistry Data: 5/362025-03-05T15:17:13.500866 - 
2025-03-05T15:17:17.085932 - FETCH ComfyRegistry Data: 10/362025-03-05T15:17:17.085932 - 
2025-03-05T15:17:19.520050 - got prompt
2025-03-05T15:17:19.891812 - model weight dtype torch.float32, manual cast: None
2025-03-05T15:17:19.894805 - model_type EPS
2025-03-05T15:17:20.408691 - FETCH ComfyRegistry Data: 15/362025-03-05T15:17:20.408691 - 
2025-03-05T15:17:21.144905 - Using pytorch attention in VAE
2025-03-05T15:17:21.149928 - Using pytorch attention in VAE
2025-03-05T15:17:21.321412 - VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
2025-03-05T15:17:21.477885 - Requested to load SD1ClipModel
2025-03-05T15:17:21.488717 - loaded completely 9.5367431640625e+25 235.84423828125 True
2025-03-05T15:17:21.491594 - CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
2025-03-05T15:17:22.856857 - !!! Exception during processing !!! CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-03-05T15:17:22.861119 - Traceback (most recent call last):
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1542, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 1509, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sample.py", line 43, in sample
    sampler = comfy.samplers.KSampler(model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=denoise, model_options=model.model_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1060, in __init__
    self.set_steps(steps, denoise)
  File "C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\samplers.py", line 1081, in set_steps
    self.sigmas = self.calculate_sigmas(steps).to(self.device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-03-05T15:17:22.864630 - Prompt executed in 3.34 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"last_node_id":9,"last_link_id":9,"nodes":[{"id":9,"type":"SaveImage","pos":[1538,51],"size":[210,58],"flags":{"collapsed":false},"order":6,"mode":0,"inputs":[{"name":"images","localized_name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.18"},"widgets_values":["ComfyUI"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[16,49],"size":[315,98],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","localized_name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","localized_name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","localized_name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"cnr_id":"comfy-core","ver":"0.3.18","Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["v1-5-pruned-emaonly-fp16.safetensors"]},{"id":5,"type":"EmptyLatentImage","pos":[502,741],"size":[315,106],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","localized_name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.18","Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":8,"type":"VAEDecode","pos":[1273,53],"size":[210,46],"flags":{},"order":5,"mode":0,"inputs":[{"name":"samples","localized_name":"samples","type":"LATENT","link":7},{"name":"vae","localized_name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","localized_name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.18","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":6,"type":"CLIPTextEncode","pos":[395,237],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","localized_name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","localized_name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.18","Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":7,"type":"CLIPTextEncode","pos":[382,476],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","localized_name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","localized_name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.18","Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":3,"type":"KSampler","pos":[925,190],"size":[315,262],"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","localized_name":"model","type":"MODEL","link":1},{"name":"positive","localized_name":"positive","type":"CONDITIONING","link":4},{"name":"negative","localized_name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","localized_name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","localized_name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.18","Node name for S&R":"KSampler"},"widgets_values":[119113864191836,"randomize",20,8,"euler","normal",1]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.1,"offset":[-12.520661157024943,-15.446280991735643]},"node_versions":{"comfy-core":"0.3.18"}},"version":0.4}


## Additional Context
Command used at the Windows DOS-prompt: C:\Users\%UserName%\AppData\Local\Programs\@comfyorgcomfyui-electron\ComfyUI.exe --disable-cuda-malloc
```

### Other

![Image](https://github.com/user-attachments/assets/5643dcb2-b395-40e3-8b92-14a10ce535a7)

**Comment by LukeG89** [comment]
In the Desktop app there is a Server-Config panel in Settings. Here you can find all the options.

Anyways, this is the official Desktop repository: https://github.com/Comfy-Org/desktop
If you have problems, open a issue there.

**Comment by C-Denninger** [comment]
Correction @LukeG89,

I just got an update from ComfyUI version 0.3.18 to 0.3.22
Now the workaround works! 

> It looks like a nice workaround but strangely it does not solve the CUDA issue. I still get a CUDA error (different now) after restarting the program.
> 
> > VAEDecode
> > CUDA error: the launch timed out and was terminated
> > CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> > For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> > Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > **Note:** There are _no logs_ with this error...

The command line still is not interpreted as it should, tough.

**Comment by LukeG89** [comment]
> I was sent here from the program itself (click on the [Find issues](https://github.com/comfyanonymous/ComfyUI/issues?q=CUDA%20error%3A%20the%20launch%20timed%20out%20and%20was%20terminated%0ACUDA%20kernel%20errors%20might%20be%20asynchronously%20reported%20at%20some%20other%20API%20call%2C%20so%20the%20stacktrace%20below%20might%20be%20incorrect.%0AFor%20debugging%20consider%20passing%20CUDA_LAUNCH_BLOCKING%3D1%0ACompile%20with%20%60TORCH_USE_CUDA_DSA%60%20to%20enable%20device-side%20assertions.%0A%20is%3Aissue)-button in the program itself to get here). The site you [suggest](https://github.com/Comfy-Org/desktop) is back to the same site. Or is this a different one?

The site I suggested is the Desktop app GitHub repository. If you have trouble with the app, you have to refer to that repo

**Comment by LukeG89** [comment]
> PS. According to the [Desktop installation instructions](https://docs.comfy.org/installation/desktop/windows) and [README.md](https://github.com/hiddenswitch/ComfyUI/blob/master/README.md) there should be some possibilities adding '--disable-cuda-malloc' in a "config.yaml", or a "config.json". Both files are not present on my pc.
> Maybe adding "config.yaml" (where?) can be used as a workaround?

The README you linked is from a different ComfyUI version, as I said in the previous messagge, only refer to the Desktop repo

**Comment by C-Denninger** [comment]
Ah thanks for explaining @LukeG89!

The CUDA --disable-cuda-malloc problem is fixed, next time I will search on:
- [https://github.com/Comfy-Org/desktop/issues](https://github.com/Comfy-Org/desktop/issues) for the Desktop (ComfyUI.exe) issues and _don't_ use the in-program Find issues-button.
- [https://github.com/comfyanonymous/ComfyUI/issues/](https://github.com/comfyanonymous/ComfyUI/issues/) for the Portable (batch (.bat) files) issues and use the in-program Find issues-button.

Te command line and [README.md](https://github.com/hiddenswitch/ComfyUI/blob/master/README.md#command-line-arguments) is another problem. I will close this call.

Thanks again!
