### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by cas12e3** [comfyanonymous/ComfyUI#7126]
### Your question

CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Logs

```powershell

```

**Comment by LukeG89** [comment]
More info is needed. Post the full debug logs, from ComfyUI startup to the error

**Comment by EpicMulletGuy** [comment]
I encountered the same error and also received the following warning in my stability matrix console after updating (it seems Blackwell GPU support was mentioned in the changelog but appears to be only partially implemented):

`ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py:235: UserWarning: 
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/`

I resolved this issue using the files from this link: https://huggingface.co/w-e-w/torch-2.6.0-cu128.nv. After installing them, the workflow now runs as expected again.

Before the Stability Matrix and ComfyUI update today, I was already using these files until an official solution came out without any errors on the same workflow. It seems that Stability Matrix/ComfyUI is using PyTorch 2.6.0+cu126 instead of 2.6.0+cu128, and TorchVision 2.1.0+cu126 instead of 0.20.0+cu128. However, the versions I linked are not official releases from NVIDIA, so they will not be included by default. When I updated it removed them and installed the cu126 ones that are not currently working with NVIDIA Blackwell GPU's on Windows.  

The PyTorch/TorchVision versions from the Hugging Face link above worked for me on Windows—perhaps they will for you as well but remember these are not official from NVIDIA.

**Comment by LukeG89** [comment]
@EpicMulletGuy For your case, it was better (safer) to install the nightly Pytorch with CUDA 12.8
Check the instructions provided by Comfy:
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#nvidia

**Comment by EpicMulletGuy** [comment]
> [@EpicMulletGuy](https://github.com/EpicMulletGuy) For your case, it was better (safer) to install the nightly Pytorch with CUDA 12.8 Check the instructions provided by Comfy: https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#nvidia
> 
> There is also a ComfyUI portable with nightly Pytorch already installed in the NVIDIA 50 Series discussion:
> 
> * [Nvidia 50 Series (Blackwell) support thread: How to get ComfyUI running on your new 50 series GPU. #6643](https://github.com/comfyanonymous/ComfyUI/discussions/6643)

Ah i must have missed that release, cheers LukeG89.

**Comment by MakitaToki** [comment]
@LukeG89  CLIP text encoder encountered the same issue on the 5070 Ti. Below is the detailed error information. Do I need to upgrade my PyTorch version?


> # ComfyUI Error Report
> ## Error Details
> - **Node ID:** 7
> - **Node Type:** CLIPTextEncode
> - **Exception Type:** RuntimeError
> - **Exception Message:** CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> ## Stack Trace
> ```
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
>     process_inputs(input_dict, i)
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 69, in encode
>     return (clip.encode_from_tokens_scheduled(tokens), )
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 152, in encode_from_tokens_scheduled
>     pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 214, in encode_from_tokens
>     o = self.cond_stage_model.encode_token_weights(tokens)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sdxl_clip.py", line 60, in encode_token_weights
>     g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 45, in encode_token_weights
>     o = self.encode(to_encode)
>         ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 274, in encode
>     return self(tokens)
>            ^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 241, in forward
>     embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
>                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 195, in process_tokens
>     tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 205, in forward
>     return self.forward_comfy_cast_weights(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 201, in forward_comfy_cast_weights
>     return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\functional.py", line 2551, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ```
> ## System Information
> - **ComfyUI Version:** 0.3.26
> - **Arguments:** C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py --user-directory C:\Users\Administrator\Documents\ComfyUI\user --input-directory C:\Users\Administrator\Documents\ComfyUI\input --output-directory C:\Users\Administrator\Documents\ComfyUI\output --front-end-root C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app --base-directory C:\Users\Administrator\Documents\ComfyUI --extra-model-paths-config C:\Users\Administrator\AppData\Roaming\ComfyUI\extra_models_config.yaml --log-stdout --listen 127.0.0.1 --port 8000
> - **OS:** nt
> - **Python Version:** 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
> - **Embedded Python:** false
> - **PyTorch Version:** 2.6.0+cu126
> ## Devices
> 
> - **Name:** cuda:0 NVIDIA GeForce RTX 5070 Ti : cudaMallocAsync
>   - **Type:** cuda
>   - **VRAM Total:** 17094475776
>   - **VRAM Free:** 13998696440
>   - **Torch VRAM Total:** 1644167168
>   - **Torch VRAM Free:** 7546872
> 
> ## Logs
> ```
> 2025-03-22T07:27:35.946123 - Adding extra search path custom_nodes C:\Users\Administrator\Documents\ComfyUI\custom_nodes
> 2025-03-22T07:27:35.947123 - Adding extra search path download_model_base C:\Users\Administrator\Documents\ComfyUI\models
> 2025-03-22T07:27:35.947123 - Adding extra search path custom_nodes C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
> 2025-03-22T07:27:35.947123 - Setting output directory to: C:\Users\Administrator\Documents\ComfyUI\output
> 2025-03-22T07:27:35.947123 - Setting input directory to: C:\Users\Administrator\Documents\ComfyUI\input
> 2025-03-22T07:27:35.947123 - Setting user directory to: C:\Users\Administrator\Documents\ComfyUI\user
> 2025-03-22T07:27:36.368172 - [START] Security scan2025-03-22T07:27:36.368172 - 
> 2025-03-22T07:27:36.832607 - [DONE] Security scan2025-03-22T07:27:36.832607 - 
> 2025-03-22T07:27:36.893590 - ## ComfyUI-Manager: installing dependencies done.2025-03-22T07:27:36.893590 - 
> 2025-03-22T07:27:36.893590 - ** ComfyUI startup time:2025-03-22T07:27:36.893590 -  2025-03-22T07:27:36.893590 - 2025-03-22 07:27:36.8932025-03-22T07:27:36.893590 - 
> 2025-03-22T07:27:36.893590 - ** Platform:2025-03-22T07:27:36.894603 -  2025-03-22T07:27:36.894603 - Windows2025-03-22T07:27:36.894603 - 
> 2025-03-22T07:27:36.894603 - ** Python version:2025-03-22T07:27:36.894603 -  2025-03-22T07:27:36.894603 - 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]2025-03-22T07:27:36.894603 - 
> 2025-03-22T07:27:36.894603 - ** Python executable:2025-03-22T07:27:36.894603 -  2025-03-22T07:27:36.894603 - C:\Users\Administrator\Documents\ComfyUI\.venv\Scripts\python.exe2025-03-22T07:27:36.894603 - 
> 2025-03-22T07:27:36.894603 - ** ComfyUI Path:2025-03-22T07:27:36.894603 -  2025-03-22T07:27:36.894603 - C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-03-22T07:27:36.894603 - 
> 2025-03-22T07:27:36.894603 - ** ComfyUI Base Folder Path:2025-03-22T07:27:36.894603 -  2025-03-22T07:27:36.894603 - C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-03-22T07:27:36.894603 - 
> 2025-03-22T07:27:36.895310 - ** User directory:2025-03-22T07:27:36.895310 -  2025-03-22T07:27:36.895310 - C:\Users\Administrator\Documents\ComfyUI\user2025-03-22T07:27:36.895310 - 
> 2025-03-22T07:27:36.895310 - ** ComfyUI-Manager config path:2025-03-22T07:27:36.895310 -  2025-03-22T07:27:36.895310 - C:\Users\Administrator\Documents\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-03-22T07:27:36.895310 - 
> 2025-03-22T07:27:36.895310 - ** Log path:2025-03-22T07:27:36.895310 -  2025-03-22T07:27:36.895310 - C:\Users\Administrator\Documents\ComfyUI\user\comfyui.log2025-03-22T07:27:36.895310 - 
> 2025-03-22T07:27:37.455945 - [ComfyUI-Manager] Failed to restore comfyui-frontend-package
> 2025-03-22T07:27:37.455945 - expected str, bytes or os.PathLike object, not NoneType
> 2025-03-22T07:27:37.457224 - 
> Prestartup times for custom nodes:
> 2025-03-22T07:27:37.457224 -    1.5 seconds: C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
> 2025-03-22T07:27:37.457224 - 
> 2025-03-22T07:27:38.467513 - Checkpoint files will always be loaded safely.
> 2025-03-22T07:27:38.491281 - C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py:235: UserWarning: 
> NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
> The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
> If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
> 
>   warnings.warn(
> 2025-03-22T07:27:38.544998 - Total VRAM 16303 MB, total RAM 31862 MB
> 2025-03-22T07:27:38.544998 - pytorch version: 2.6.0+cu126
> 2025-03-22T07:27:38.544998 - Set vram state to: NORMAL_VRAM
> 2025-03-22T07:27:38.545996 - Device: cuda:0 NVIDIA GeForce RTX 5070 Ti : cudaMallocAsync
> 2025-03-22T07:27:39.204305 - Using pytorch attention
> 2025-03-22T07:27:39.884663 - ComfyUI version: 0.3.26
> 2025-03-22T07:27:39.902310 - [Prompt Server] web root: C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
> 2025-03-22T07:27:40.113362 - ### Loading: ComfyUI-Manager (V3.30.4)
> 2025-03-22T07:27:40.113362 - [ComfyUI-Manager] network_mode: public
> 2025-03-22T07:27:40.114363 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
> 2025-03-22T07:27:40.117364 - 
> Import times for custom nodes:
> 2025-03-22T07:27:40.117364 -    0.0 seconds: C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
> 2025-03-22T07:27:40.117364 -    0.0 seconds: C:\Users\Administrator\Documents\ComfyUI\custom_nodes\aigodlike-comfyui-translation
> 2025-03-22T07:27:40.117364 -    0.0 seconds: C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
> 2025-03-22T07:27:40.117364 - 
> 2025-03-22T07:27:40.124004 - Starting server
> 
> 2025-03-22T07:27:40.124517 - To see the GUI go to: http://127.0.0.1:8000
> 2025-03-22T07:27:40.301930 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> 2025-03-22T07:27:40.387188 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> 2025-03-22T07:27:40.456305 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> 2025-03-22T07:27:40.528388 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> 2025-03-22T07:27:40.551747 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> 2025-03-22T07:27:44.948580 - FETCH ComfyRegistry Data: 5/792025-03-22T07:27:44.949085 - 
> 2025-03-22T07:27:49.892235 - FETCH ComfyRegistry Data: 10/792025-03-22T07:27:49.892235 - 
> 2025-03-22T07:27:55.564376 - FETCH ComfyRegistry Data: 15/792025-03-22T07:27:55.564376 - 
> 2025-03-22T07:28:01.035343 - FETCH ComfyRegistry Data: 20/792025-03-22T07:28:01.035343 - 
> 2025-03-22T07:28:06.425393 - FETCH ComfyRegistry Data: 25/792025-03-22T07:28:06.425393 - 
> 2025-03-22T07:28:11.402095 - FETCH ComfyRegistry Data: 30/792025-03-22T07:28:11.402095 - 
> 2025-03-22T07:28:16.454715 - FETCH ComfyRegistry Data: 35/792025-03-22T07:28:16.454715 - 
> 2025-03-22T07:28:21.668480 - FETCH ComfyRegistry Data: 40/792025-03-22T07:28:21.668480 - 
> 2025-03-22T07:28:26.493278 - FETCH ComfyRegistry Data: 45/792025-03-22T07:28:26.493827 - 
> 2025-03-22T07:28:31.840535 - FETCH ComfyRegistry Data: 50/792025-03-22T07:28:31.840535 - 
> 2025-03-22T07:28:37.692333 - FETCH ComfyRegistry Data: 55/792025-03-22T07:28:37.692333 - 
> 2025-03-22T07:28:43.125896 - FETCH ComfyRegistry Data: 60/792025-03-22T07:28:43.125896 - 
> 2025-03-22T07:28:48.477493 - FETCH ComfyRegistry Data: 65/792025-03-22T07:28:48.477493 - 
> 2025-03-22T07:28:53.953293 - FETCH ComfyRegistry Data: 70/792025-03-22T07:28:53.953293 - 
> 2025-03-22T07:28:58.973895 - FETCH ComfyRegistry Data: 75/792025-03-22T07:28:58.973895 - 
> 2025-03-22T07:29:03.448071 - FETCH ComfyRegistry Data [DONE]2025-03-22T07:29:03.448071 - 
> 2025-03-22T07:29:03.512371 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
> 2025-03-22T07:29:03.545655 - nightly_channel: 2025-03-22T07:29:03.545655 - 
> 2025-03-22T07:29:03.545655 - https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote2025-03-22T07:29:03.545655 - 
> 2025-03-22T07:29:03.545655 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-03-22T07:29:03.545655 - 2025-03-22T07:29:03.942434 -  [DONE]2025-03-22T07:29:03.942434 - 
> 2025-03-22T07:29:03.980556 - [ComfyUI-Manager] All startup tasks have been completed.
> 2025-03-22T07:31:12.737838 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-03-22T07:31:12.737838 - 2025-03-22T07:31:13.158817 -  [DONE]2025-03-22T07:31:13.158817 - 
> 2025-03-22T07:31:13.206694 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-03-22T07:31:13.206694 - 
> 2025-03-22T07:31:13.231308 - nightly_channel: 2025-03-22T07:31:13.231308 - 
> 2025-03-22T07:31:13.231308 - https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/cache2025-03-22T07:31:13.231308 - 
> 2025-03-22T07:31:13.231308 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-03-22T07:31:13.231308 - 2025-03-22T07:31:13.601299 -  [DONE]2025-03-22T07:31:13.601299 - 
> 2025-03-22T07:31:13.650620 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-03-22T07:31:13.650620 - 2025-03-22T07:31:13.936804 -  [DONE]2025-03-22T07:31:13.936804 - 
> 2025-03-22T07:31:13.946763 - FETCH DATA from: C:\Users\Administrator\Documents\ComfyUI\user\default\ComfyUI-Manager\cache\832903789_extras.json2025-03-22T07:31:13.946763 - 2025-03-22T07:31:13.946763 -  [DONE]2025-03-22T07:31:13.946763 - 
> 2025-03-22T07:45:16.526723 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2025-03-22T07:45:16.526723 - 2025-03-22T07:45:16.922134 -  [DONE]2025-03-22T07:45:16.922134 - 
> 2025-03-22T07:45:16.972159 - [ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.2025-03-22T07:45:16.972159 - 
> 2025-03-22T07:45:16.995864 - nightly_channel: 2025-03-22T07:45:16.995864 - 
> 2025-03-22T07:45:16.995864 - https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/cache2025-03-22T07:45:16.995864 - 
> 2025-03-22T07:45:16.995864 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-03-22T07:45:16.995864 - 2025-03-22T07:45:17.408218 -  [DONE]2025-03-22T07:45:17.408218 - 
> 2025-03-22T07:45:17.460776 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2025-03-22T07:45:17.460776 - 2025-03-22T07:45:17.747300 -  [DONE]2025-03-22T07:45:17.748308 - 
> 2025-03-22T07:45:17.758244 - FETCH DATA from: C:\Users\Administrator\Documents\ComfyUI\user\default\ComfyUI-Manager\cache\832903789_extras.json2025-03-22T07:45:17.758244 - 2025-03-22T07:45:17.758244 -  [DONE]2025-03-22T07:45:17.758244 - 
> 2025-03-22T07:49:02.562049 - got prompt
> 2025-03-22T07:49:02.894934 - model weight dtype torch.float16, manual cast: None
> 2025-03-22T07:49:02.903497 - model_type V_PREDICTION
> 2025-03-22T07:49:07.523309 - Using pytorch attention in VAE
> 2025-03-22T07:49:07.524310 - Using pytorch attention in VAE
> 2025-03-22T07:49:07.840037 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
> 2025-03-22T07:49:08.075885 - Requested to load SDXLClipModel
> 2025-03-22T07:49:08.084192 - loaded completely 9.5367431640625e+25 1560.802734375 True
> 2025-03-22T07:49:08.086772 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
> 2025-03-22T07:49:10.066771 - !!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 2025-03-22T07:49:10.069285 - Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 69, in encode
>     return (clip.encode_from_tokens_scheduled(tokens), )
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 152, in encode_from_tokens_scheduled
>     pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 214, in encode_from_tokens
>     o = self.cond_stage_model.encode_token_weights(tokens)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sdxl_clip.py", line 60, in encode_token_weights
>     g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 45, in encode_token_weights
>     o = self.encode(to_encode)
>         ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 274, in encode
>     return self(tokens)
>            ^^^^^^^^^^^^
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 241, in forward
>     embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
>                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 195, in process_tokens
>     tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 205, in forward
>     return self.forward_comfy_cast_weights(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 201, in forward_comfy_cast_weights
>     return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Documents\ComfyUI\.venv\Lib\site-packages\torch\nn\functional.py", line 2551, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 
> 2025-03-22T07:49:10.070290 - Prompt executed in 7.51 seconds
> 
> ```
> ## Attached Workflow
> Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
> ```
> {"last_node_id":14,"last_link_id":9,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","localized_name":"clip","label":"CLIP","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","localized_name":"条件","label":"条件","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.26","Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","localized_name":"clip","label":"CLIP","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","localized_name":"条件","label":"条件","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.26","Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","localized_name":"Latent","label":"Latent","type":"LATENT","links":[2],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.26","Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":6,"mode":0,"inputs":[{"name":"samples","localized_name":"Latent","label":"Latent","type":"LATENT","link":7},{"name":"vae","localized_name":"vae","label":"VAE","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","localized_name":"图像","label":"图像","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.26","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","localized_name":"图片","label":"图像","type":"IMAGE","link":9}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.26"},"widgets_values":["ComfyUI"]},{"id":10,"type":"MarkdownNote","pos":[30,630],"size":[315,88],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[],"properties":{},"widgets_values":["🛈 Need more details? Check out [docs.comfy.org/get_started](https://docs.comfy.org/get_started/gettingstarted)"],"color":"#432","bgcolor":"#653"},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","localized_name":"模型","label":"模型","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","localized_name":"CLIP","label":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","localized_name":"VAE","label":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"cnr_id":"comfy-core","ver":"0.3.26","Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["noobaiXLNAIXL_vPred10Version.safetensors"]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":5,"mode":0,"inputs":[{"name":"model","localized_name":"模型","label":"模型","type":"MODEL","link":1},{"name":"positive","localized_name":"正面条件","label":"正面条件","type":"CONDITIONING","link":4},{"name":"negative","localized_name":"负面条件","label":"负面条件","type":"CONDITIONING","link":6},{"name":"latent_image","localized_name":"Latent图像","label":"Latent","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","localized_name":"Latent","label":"Latent","type":"LATENT","links":[7],"slot_index":0}],"properties":{"cnr_id":"comfy-core","ver":"0.3.26","Node name for S&R":"KSampler"},"widgets_values":[1034640140646665,"randomize",20,8,"euler","normal",1]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.1000000000000005,"offset":[519.9956084773995,121.44507073667499]}},"version":0.4}
> ```
> 
> ## Additional Context
> (Please add any additional context or steps to reproduce the error here)

**Comment by LukeG89** [comment]
@MakitaToki Yes, currently the only way to use NVIDIA 50 Series GPUs is installing the latest nightly Pytorch with CUDA 12.8, as I reported in the message above

**Comment by Young-Geo** [comment]
@LukeG89 The 3070Ti I'm using is also experiencing the same issue. How can this be resolved?

**Comment by kwang0429** [comment]
I have the same error with RTX 4090

Prompt executed in 8394.80 seconds
[Crystools ERROR] Could not get GPU utilization.exception: access violation reading 0x0000021556AC17B8
[Crystools ERROR] Monitor of GPU is turning off (not on UI!)
Exception in thread Thread-10 (prompt_worker):
Traceback (most recent call last):
File "threading.py", line 1075, in _bootstrap_inner
File "threading.py", line 1012, in run
File "E:\Comfy_2025\ComfyUI\main.py", line 215, in prompt_worker
comfy.model_management.soft_empty_cache()
File "E:\Comfy_2025\ComfyUI\comfy\model_management.py", line 1291, in soft_empty_cache
torch.cuda.empty_cache()
File "E:\Comfy_2025\python_embeded\Lib\site-packages\torch\cuda\memory.py", line 222, in empty_cache
torch._C._cuda_emptyCache()
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

Error handling request
Traceback (most recent call last):
File "E:\Comfy_2025\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 477, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfy_2025\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 567, in _handle
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfy_2025\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfy_2025\ComfyUI\server.py", line 50, in cache_control
response: web.Response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfy_2025\ComfyUI\server.py", line 142, in origin_only_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfy_2025\ComfyUI\server.py", line 523, in system_stats
vram_total, torch_vram_total = comfy.model_management.get_total_memory(device, torch_total_too=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfy_2025\ComfyUI\comfy\model_management.py", line 206, in get_total_memory
_, mem_total_cuda = torch.cuda.mem_get_info(dev)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfy_2025\python_embeded\Lib\site-packages\torch\cuda\memory.py", line 836, in mem_get_info
return torch.cuda.cudart().cudaMemGetInfo(device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
