### ISSUE TITLE
UserWarning: NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.

### ISSUE THREAD

**Issue by fireYtail** [comfyanonymous/ComfyUI#7127]
### Expected Behavior

There shouldn't be any errors on a fresh install, it should work regardless of the GPU. Alternatively, it should automatically detect the incompatibility and try to fix it.

The user shouldn't have to manually reinstall. This workaround is far from an acceptable solution, A lot of people don't know how to fix this issue (the manual reinstall). You shouldn't expect the average ComfyUI user to know how to fix it entirely by themselves.

### Actual Behavior

On a fresh install (or an older install), when using a 5070 ti the following error comes up:

```
A:\Sin Sincronización\Chrome\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Checkpoint files will always be loaded safely.
A:\Sin Sincronización\Chrome\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

There is a way to fix this, but the user has to follow these specific steps manually:
1) Navigate to python_embedded\ directory and open a new command prompt in this location.
2) Run python -m pip uninstall torch torchvision
3) Run python -m pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu128 and wait for a very long download of over 3 GB.

### Steps to Reproduce

With a 5070 ti as your GPU, make a fresh install of ComfyUI and run it (or run an already existing installation)

### Debug Logs

```powershell
A:\Sin Sincronización\Chrome\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Checkpoint files will always be loaded safely.
A:\Sin Sincronización\Chrome\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

### Other

I upgraded from a 1080 ti to a 5070 ti, but this isn't relevant since it happens on a fresh install (latest release) too.

**Comment by LukeG89** [comment]
It's "normal" behaviour, as you can see from the NVIDIA 50xx discussion:
- https://github.com/comfyanonymous/ComfyUI/discussions/6643

In the discussion, there is the download link to a ComfyUI portable with nightly Pytorch already installed.

Stable Pytorch is currently incompatible with 50 series GPUs, but I guess it's just a matter of time.

**Comment by LukeG89** [comment]
Actually, there is the link in the readme to the discussion I linked:
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#windows-portable


![Image](https://github.com/user-attachments/assets/d5a2cfc1-9674-443a-8563-c589e427e994)


There is also a note in the NVIDIA section about nightly pytorch for 50xx GPUs:
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#nvidia

![Image](https://github.com/user-attachments/assets/7569b8e8-428b-4f4f-9c0a-6c24e9d23157)

**Comment by canglangzhishuiz** [comment]
I solved this issue on Windows 11 with an RTX 5070 Ti and WSL2.  

First, install **CUDA 12.8**.  
Then, install PyTorch using:  
```bash
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
```
Finally, clone the **PyTorch3D** source code and install it:  
```bash
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d
pip install -e .
```

**Comment by chaxheri** [comment]
Same problem when use 5070Ti，is any updating for this issue?

**Comment by calvinwonghk** [comment]
windows desktop version, python seems path is : C:\Users\<user>\Documents\ComfyUI\.venv\Scripts

**Comment by spha-code** [comment]
> Thanks for tips! Windows desktop installer version Just go python path is : C:\Users<user>\Documents\ComfyUI.venv\Scripts
> 
> pip uninstall torch pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> now is working fine, thanks for tips!

This worked for me!

**Comment by akaghzi** [comment]
> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

worked for me, i am using ubuntu 24

**Comment by aotianlong** [comment]
> Thanks for tips! Windows desktop installer version Just go python path is : C:\Users<user>\Documents\ComfyUI.venv\Scripts
> 
> pip uninstall torch pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> now is working fine, thanks for tips!

worked for me , thank you.

**Comment by sszxt** [comment]
Thank you @calvinwonghk it worked for me too

**Comment by Rakshith12-pixel** [comment]
So, cuda 12.8 and above builds of pytorch>=2.7.0 must have no issues on RTX 50 series right?
