### ISSUE TITLE
9070 XT Error / Crash on Ubuntu Linux

### ISSUE THREAD

**Issue by Viexi** [comfyanonymous/ComfyUI#7400]
### Your question

I am attempting to run ComfyUI using ROCm6.3, however I run into issues when trying to run it using my 9070 XT AMD GPU.

I either get a "**HIP error: invalid device function**" error if I start main.py without any args, or if I add "HSA_OVERRIDE_GFX_VERSION=11.0.0", I get an immediate soft-crash that requires a hard reset to resolve.

Because it's taken me forever to try to get to even this point let me outline my process below, just incase I'm missing anything:

Create venv
Clone Comfy into Venv
pip install pytorch (ROCm6.3) into venv
install comfy requirements.txt
run into the issues above.

Can anyone suggest if I am doing something wrong or if I've missed a requirement or dependency? Cheers.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 7
- **Node Type:** CLIPTextEncode
- **Exception Type:** RuntimeError
- **Exception Message:** HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

## Stack Trace

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd.py", line 153, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd.py", line 215, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 662, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 274, in encode
    return self(tokens)
           ^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 241, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 195, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/ops.py", line 205, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/ops.py", line 201, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.27
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0.dev20250326+rocm6.3
## Devices

- **Name:** cuda:0 AMD Radeon RX 9070 XT : hipMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17095983104
  - **VRAM Free:** 16013852672
  - **Torch VRAM Total:** 247300612
  - **Torch VRAM Free:** 0

## Logs

2025-03-26T14:34:53.451806 - Checkpoint files will always be loaded safely.
2025-03-26T14:34:54.285220 - Total VRAM 16304 MB, total RAM 32000 MB
2025-03-26T14:34:54.285259 - pytorch version: 2.8.0.dev20250326+rocm6.3
2025-03-26T14:34:54.285421 - AMD arch: gfx1201
2025-03-26T14:34:54.285465 - Set vram state to: NORMAL_VRAM
2025-03-26T14:34:54.285524 - Device: cuda:0 AMD Radeon RX 9070 XT : hipMallocAsync
2025-03-26T14:34:55.954755 - Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
2025-03-26T14:34:57.575736 - ComfyUI version: 0.3.27
2025-03-26T14:34:57.579964 - ComfyUI frontend version: 1.14.5
2025-03-26T14:34:57.580611 - [Prompt Server] web root: /home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/comfyui_frontend_package/static
2025-03-26T14:34:58.092959 - 
Import times for custom nodes:
2025-03-26T14:34:58.093002 -    0.0 seconds: /home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/custom_nodes/websocket_image_save.py
2025-03-26T14:34:58.093026 - 
2025-03-26T14:34:58.096303 - Starting server

2025-03-26T14:34:58.096465 - To see the GUI go to: http://127.0.0.1:8188
2025-03-26T14:35:09.714919 - got prompt
2025-03-26T14:35:10.196306 - model weight dtype torch.float16, manual cast: None
2025-03-26T14:35:10.208741 - model_type EPS
2025-03-26T14:35:14.311397 - Using split attention in VAE
2025-03-26T14:35:14.312339 - Using split attention in VAE
2025-03-26T14:35:14.751876 - VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
2025-03-26T14:35:14.807632 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-03-26T14:35:15.581241 - Requested to load SD1ClipModel
2025-03-26T14:35:16.196577 - loaded completely 14520.8 235.84423828125 True
2025-03-26T14:35:16.257972 - !!! Exception during processing !!! HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

2025-03-26T14:35:16.263256 - Traceback (most recent call last):
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd.py", line 153, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd.py", line 215, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 662, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 274, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 241, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 195, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/ops.py", line 205, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/ops.py", line 201, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


2025-03-26T14:35:16.264108 - Prompt executed in 6.55 seconds
2025-03-26T14:35:52.157138 - got prompt
2025-03-26T14:35:52.160415 - !!! Exception during processing !!! HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

2025-03-26T14:35:52.161293 - Traceback (most recent call last):
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd.py", line 153, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd.py", line 215, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 662, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 274, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 241, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/sd1_clip.py", line 195, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/ops.py", line 205, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/ComfyUI/comfy/ops.py", line 201, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viexi/Documents/Stable Diffusion/comfy/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


2025-03-26T14:35:52.162323 - Prompt executed in 0.00 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"id":"3a12a7cc-d61a-491b-8470-55a4002ab9b5","revision":0,"last_node_id":9,"last_link_id":9,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":3,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":5}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[6]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[2]}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":4,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":1},{"localized_name":"positive","name":"positive","type":"CONDITIONING","link":4},{"localized_name":"negative","name":"negative","type":"CONDITIONING","link":6},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":2}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[7]}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[377127218870716,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":5,"mode":0,"inputs":[{"localized_name":"samples","name":"samples","type":"LATENT","link":7},{"localized_name":"vae","name":"vae","type":"VAE","link":8}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","slot_index":0,"links":[9]}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":6,"mode":0,"inputs":[{"localized_name":"images","name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[1]},{"localized_name":"CLIP","name":"CLIP","type":"CLIP","slot_index":1,"links":[3,5]},{"localized_name":"VAE","name":"VAE","type":"VAE","slot_index":2,"links":[8]}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["v1-5-pruned-emaonly-fp16.safetensors"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":2,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":3}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[4]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[0,0]}},"version":0.4}


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by buekera** [comment]
Interesting. I created an issue today which may oder may not be related to yours, but for me I'm not even able to use my AMD 9070 XT, because ComfyUI defaults to my old Nvidia 1050 when trying to run ComfyUI.

Other than that I also installed ComfyUI the same way you did, with rocm6.3.

**Comment by buekera** [comment]
I can confirm that your solution is working @Viexi .
I just followed the instructions in the reddit post, minus the secure boot stuff, and it's working now.
Just something I did addintionally before: install the package 'mesa' and 'vulkan-radeon' version 25. This is to use the latest drivers - for arch I needed to enable experimental mirrors to be able to download them.

**Comment by jasonfrancis** [comment]
I was encountering the same issue on a `gfx1103` card. I read somewhere that there is a bug with 16 bit operations that blows up in AMD's driver.  I was able to get around this with the `--force-fp32` flag.  Then for stability I had to find the best setting for `HSA_OVERRIDE_GFX_VERSION`, in my case it was `11.0.1`, but your mileage may vary.

**Comment by RobertoMaurizzi** [comment]
With a GPU shown by `rocminfo` to be `gfx1150` in a **AMD Ryzen AI 9 HX 370 w/ Radeon 890M** (MinisForum X1 Pro), Debian testing/trixie, drivers from ROCm 6.4.0, configured with:
```bash
amdgpu-install --vulkan=amdvlk --usecase=graphics,hip,rocm,dkms
```
(after manually downloading and installing missing stdlibc++ packages from Debian unstable/sid), I get the following results with today's ComfyUI In a virtual environment set up with `pytorch-2.7-rocm63` (since that's the latest available...):
```bash
HSA_OVERRIDE_GFX_VERSION=11.5.1 python main.py --force-fp32  # HIP error: invalid device function on KSampler
HSA_OVERRIDE_GFX_VERSION=11.5.0 python main.py --force-fp32  # HIP error: invalid device function on KSampler
HSA_OVERRIDE_GFX_VERSION=11.0.0 python main.py --force-fp32  # works
HSA_OVERRIDE_GFX_VERSION=11.0.2 python main.py --force-fp32  # works... and is faster? Or maybe it's because I shut down ollama?
HSA_OVERRIDE_GFX_VERSION=11.0.2 python main.py               # core dump on KSampler
HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py               # core dump on KSampler
HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py --force-fp32  # HIP error: invalid device function on KSampler
```

**Comment by RobertoMaurizzi** [comment]
Very funny: LTX .0.97 works without the --force-fp32 and generating 5 second videos at 24fps is FASTER than SDLX generating a 832x1216 image...
The ksampler still crashes without --force-fp32 and I'm starting to be royally annoyed at AMD for not even trying to support the AI370 but skipping directly to the new 380-395 :-P
AMD needs to compete with NVidia but not for the "which company mistreat their customer more" prize :-P

**Comment by RobertoMaurizzi** [comment]
I'll add: I split the VRAM/RAM 32/64... but I'm seeing rocm-smi saying VRAM 6% GPU 100% while my system ram consumption is maxed (and sometimes I get out out memory errors). My very strong impression is that the GPU is processing data from the system RAM instead of its dedicated shared memory "VRAM".

**Comment by wasd-tech** [comment]
@Viexi Do you still need help? I have a working ROCm enviroment. The only bad thing is that the performances with pytorch in image generation with an rx 9070 (xt) are bad compared even with other AMD cards.

**Comment by wasd-tech** [comment]
@RobertoMaurizzi I suggest you to try a little workaround, if you have time to try something, and use the official docker from AMD. I use it on Fedora (so a non supported OS) in combination with distrobox and it just works with everything AI programs I throw in it. The command looks like this:
```
distrobox create  -i rocm/dev-ubuntu-24.04:6.4-complete -n NAME_OF_CONTAINER #like ubuntu_rocm
```
and after entered the container install in your python virtual enviroment the nightly version of pytorch_rocm:
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.4
```
And after that try to use HSA_OVERRIDE_GFX_VERSION=11.5.1 like you did before. I don't have an APU like yours so maybe it will not work but from what I can tell reading the source code an official support for gfx1151 will probably come with ROCm 6.5 but is already present in all the ROCm libraries so it can work.

**Comment by kasper93** [comment]
> ROCm 6.4.1 introduces support for the RDNA4 architecture-based Radeon AI PRO R9700, Radeon RX 9070 XT, and Radeon RX 9060 XT GPUs for compute workloads.

See https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.4.1/reference/system-requirements.html

RDNA4 is officially supported now, so you shouldn't use any `HSA_OVERRIDE` hacks and report upstream if something is not working as expected.

VAE decoding OOM issues is tracked here https://github.com/ROCm/ROCm/issues/4742

**Comment by pkrasicki** [comment]
You have a space in the path, so it's probably this: https://github.com/ROCm/ROCm/issues/4329. The solution would be to create a new venv in another location that doesn't have a space in the path and install ComfyUI there. If it is that issue, consider commenting there and asking for a bugfix release.
