### ISSUE TITLE
AMD 780M

### ISSUE THREAD

**Issue by DNDEBUG** [comfyanonymous/ComfyUI#7798]
### Your question

Ryzen 8700G, Radeon 780M
Using ComfyUI on windows with ZLUDA it worked fine, but following the documentation to use rocm on linux resulted in some HIP error

no extra option or environment variable gave a better result

make sure i am in the render and video group
I install Python 3.12
Clone ComfyUI
create the venv with python 3.12
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2.4
pip install -r requirements.txt
python main.py

![Image](https://github.com/user-attachments/assets/c11ec60b-cc94-4083-a116-9b6b97056d56)

log

# ComfyUI Error Report
## Error Details
- **Node ID:** 7
- **Node Type:** CLIPTextEncode
- **Exception Type:** RuntimeError
- **Exception Message:** HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

## Stack Trace
```
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd.py", line 154, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd.py", line 216, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sdxl_clip.py", line 59, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 288, in encode
    return self(tokens)
           ^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 250, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/ops.py", line 225, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/ops.py", line 221, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** 0.3.30
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.12.10 (main, Apr 25 2025, 14:49:36) [GCC 14.2.1 20250207]
- **Embedded Python:** false
- **PyTorch Version:** 2.7.0+rocm6.2.4
## Devices

- **Name:** cuda:0 AMD Radeon Graphics : native
  - **Type:** cuda
  - **VRAM Total:** 14489661440
  - **VRAM Free:** 12598055936
  - **Torch VRAM Total:** 1772093440
  - **Torch VRAM Free:** 127607808

## Logs
```
2025-04-25T15:50:59.964488 - Checkpoint files will always be loaded safely.
2025-04-25T15:51:00.752757 - Total VRAM 13818 MB, total RAM 27637 MB
2025-04-25T15:51:00.752795 - pytorch version: 2.7.0+rocm6.2.4
2025-04-25T15:51:00.752933 - AMD arch: gfx1103
2025-04-25T15:51:00.752968 - Set vram state to: NORMAL_VRAM
2025-04-25T15:51:00.752998 - Device: cuda:0 AMD Radeon Graphics : native
2025-04-25T15:51:01.673110 - Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
2025-04-25T15:51:02.711558 - Python version: 3.12.10 (main, Apr 25 2025, 14:49:36) [GCC 14.2.1 20250207]
2025-04-25T15:51:02.711592 - ComfyUI version: 0.3.30
2025-04-25T15:51:02.712080 - ComfyUI frontend version: 1.17.11
2025-04-25T15:51:02.712378 - [Prompt Server] web root: /run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/comfyui_frontend_package/static
2025-04-25T15:51:02.981936 - 
Import times for custom nodes:
2025-04-25T15:51:02.981977 -    0.0 seconds: /run/media/danilen52/1tb/git/ComfyUI/custom_nodes/websocket_image_save.py
2025-04-25T15:51:02.981995 - 
2025-04-25T15:51:02.984790 - Starting server

2025-04-25T15:51:02.984925 - To see the GUI go to: http://127.0.0.1:8188
2025-04-25T15:51:11.619909 - got prompt
2025-04-25T15:51:11.629835 - Using split attention in VAE
2025-04-25T15:51:11.630627 - Using split attention in VAE
2025-04-25T15:51:11.672678 - VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
2025-04-25T15:51:11.790515 - model weight dtype torch.float16, manual cast: None
2025-04-25T15:51:11.790868 - model_type EPS
2025-04-25T15:51:12.242732 - Using split attention in VAE
2025-04-25T15:51:12.243477 - Using split attention in VAE
2025-04-25T15:51:12.275656 - VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
2025-04-25T15:51:12.435874 - Requested to load SDXLClipModel
2025-04-25T15:51:12.445644 - loaded completely 9.5367431640625e+25 1560.802734375 True
2025-04-25T15:51:14.854171 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
2025-04-25T15:51:29.699350 - !!! Exception during processing !!! HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

2025-04-25T15:51:29.702265 - Traceback (most recent call last):
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd.py", line 154, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd.py", line 216, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sdxl_clip.py", line 59, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 288, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 250, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/ops.py", line 225, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/ops.py", line 221, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


2025-04-25T15:51:29.703224 - Prompt executed in 18.08 seconds
2025-04-25T15:52:26.472304 - got prompt
2025-04-25T15:52:26.475749 - !!! Exception during processing !!! HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

2025-04-25T15:52:26.476507 - Traceback (most recent call last):
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/run/media/danilen52/1tb/git/ComfyUI/execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd.py", line 154, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd.py", line 216, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sdxl_clip.py", line 59, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 288, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 250, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/ops.py", line 225, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/comfy/ops.py", line 221, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/danilen52/1tb/git/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


2025-04-25T15:52:26.477200 - Prompt executed in 0.00 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"id":"d1fb9798-ecc0-4c26-990f-8082b5c660ad","revision":0,"last_node_id":9,"last_link_id":9,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":3,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":5},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[6]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":2,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":3},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[4]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":null},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":null},{"localized_name":"batch_size","name":"batch_size","type":"INT","widget":{"name":"batch_size"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[2]}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":4,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":1},{"localized_name":"positive","name":"positive","type":"CONDITIONING","link":4},{"localized_name":"negative","name":"negative","type":"CONDITIONING","link":6},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":2},{"localized_name":"seed","name":"seed","type":"INT","widget":{"name":"seed"},"link":null},{"localized_name":"steps","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"cfg","name":"cfg","type":"FLOAT","widget":{"name":"cfg"},"link":null},{"localized_name":"sampler_name","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null},{"localized_name":"scheduler","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"denoise","name":"denoise","type":"FLOAT","widget":{"name":"denoise"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[7]}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[759307587529116,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":5,"mode":0,"inputs":[{"localized_name":"samples","name":"samples","type":"LATENT","link":7},{"localized_name":"vae","name":"vae","type":"VAE","link":8}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","slot_index":0,"links":[9]}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":6,"mode":0,"inputs":[{"localized_name":"images","name":"images","type":"IMAGE","link":9},{"localized_name":"filename_prefix","name":"filename_prefix","type":"STRING","widget":{"name":"filename_prefix"},"link":null}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":1,"mode":0,"inputs":[{"localized_name":"ckpt_name","name":"ckpt_name","type":"COMBO","widget":{"name":"ckpt_name"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[1]},{"localized_name":"CLIP","name":"CLIP","type":"CLIP","slot_index":1,"links":[3,5]},{"localized_name":"VAE","name":"VAE","type":"VAE","slot_index":2,"links":[8]}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["ponyDiffusionV6XL_v6StartWithThisOne.safetensors"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[30.926025088764163,33.56356882147554]},"frontendVersion":"1.17.11"},"version":0.4}
```

### Logs

```powershell

```

**Comment by SnekiSnake** [comment]
I have this issue as well. You can bypass it by running "python main.py --cpu" 
Diving into it more, it doesn't look like ROCm is fully supported on the 780m/760m iGPUs.
https://rocm.docs.amd.com/projects/install-on-linux/en/develop/reference/system-requirements.html#system-requirements

(I use Ubuntu 24.04 on a Ryzen 5 Framework 13)

**Comment by DNDEBUG** [comment]
that isn't bypassing really, its just using the CPU instead of the GPU

**Comment by psiryan** [comment]
I'm having the same issue with my 9070.

**Comment by SnekiSnake** [comment]
> I'm having the same issue with my 9070.

I *think* figured it out as it's now working for me on my 7900 XT running Ubuntu 24.04 LTS. You'll need to download the AMD drivers as seen here (You'll need to copy and run BOTH boxes): https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html 

Then run (without the quotes) "sudo apt install -y libamd-comgr2 libhsa-runtime64-1 librccl1 librocalution0 librocblas0 librocfft0 librocm-smi64-1 librocsolver0 librocsparse0 rocm-device-libs-17 rocm-smi rocminfo hipcc libhiprand1 libhiprtc-builtins5 radeontop". This step may not be necessary but I wanted to include it just in case.  

Then install the correct (and most recent) PyTorch version via https://pytorch.org/get-started/locally/ in your python environment.

As of the time of writing this you'll use "pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.3" (without the quotes) in your python environment. 

Then assuming you also ran "pip install -r requirments.txt" in your python environment as well, it will work. 

Lastly, because the 9070 isn't supported on AMD's site, i'd recommend running (without the quotes):
"export HSA_OVERRIDE_GFX_VERSION=11.0.0"
and 
"export HCC_AMDGPU_TARGET=gfx1100” 
prior to running "python main.py". This temporarily force sets python to think you're using a supported gfx1100 GPU. 

I was even able to get 75% of a workload to run on my framework by doing this, but it died because of a hardware limitation because the system obviously didn't have the compute units on the die it was looking for.

**Comment by wasd-tech** [comment]
@DNDEBUG try to add HSA_OVERRIDE_GFX_VERSION=11.0.0 to the launch command. It should work.

**Comment by fish-finger-flinger** [comment]
Look here
https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU
download latest rocm-gfx1103-AMD-780M-phoenix-V5.0-for-hip-skd-6.2.4.7z and follow instructions
try here
https://github.com/patientx/ComfyUI-Zluda

**Comment by jammm** [comment]
> I'm having the same issue with my 9070.

TheRock wheels should support 9070 now. https://github.com/ROCm/TheRock/blob/main/RELEASES.md
