### ISSUE TITLE
AMD RYZEN AI MAX+ 395 w/ Radeon 8060S not supported

### ISSUE THREAD

**Issue by marcushoff** [comfyanonymous/ComfyUI#8211]
### Expected Behavior

Image generated.

### Actual Behavior

Error on image generation.

### Steps to Reproduce

Run comfyUI on computer with AMD RYZEN AI MAX+ 395 w/ Radeon 8060S (gfx1151)

### Debug Logs

```powershell
Checkpoint files will always be loaded safely.
Total VRAM 63970 MB, total RAM 127940 MB
pytorch version: 2.8.0.dev20250518+rocm6.4
AMD arch: gfx1151
Set vram state to: NORMAL_VRAM
Device: cuda:0 Radeon 8060S Graphics : hipMallocAsync
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.12.9 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 18:56:27) [GCC 11.2.0]
ComfyUI version: 0.3.34
ComfyUI frontend version: 1.19.9
[Prompt Server] web root: /home/mho/miniconda3/envs/comfyui-web/lib/python3.12/site-packages/comfyui_frontend_package/static

Import times for custom nodes:
   0.0 seconds: /home/mho/ComfyUI/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SD1ClipModel
loaded completely 62198.675 235.84423828125 True
!!! Exception during processing !!! HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/mho/ComfyUI/execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/mho/ComfyUI/execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/sd.py", line 166, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/sd.py", line 228, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/sd1_clip.py", line 682, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/sd1_clip.py", line 288, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "/home/mho/miniconda3/envs/comfyui-web/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/miniconda3/envs/comfyui-web/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/sd1_clip.py", line 250, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/miniconda3/envs/comfyui-web/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/miniconda3/envs/comfyui-web/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/ops.py", line 237, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/ComfyUI/comfy/ops.py", line 233, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mho/miniconda3/envs/comfyui-web/lib/python3.12/site-packages/torch/nn/functional.py", line 2560, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


Prompt executed in 0.64 seconds
```

### Other

System Info

comfyui: 0.3.34
comfyui_frontend: 1.19.9

OS: posix
Python Version: 3.12.9 | packaged by Anaconda, Inc. | (main, Feb 6 2025, 18:56:27) [GCC 11.2.0]
Embedded Python: false
Pytorch Version: 2.8.0.dev20250518+rocm6.4
Arguments: main.py
RAM Total: 124.94 GB
RAM Free: 108.03 GB

Devices

Name: cuda:0 Radeon 8060S Graphics : hipMallocAsync
Type: cuda
VRAM Total: 62.47 GB
VRAM Free: 61.49 GB
Torch VRAM Total: 235.84 MB
Torch VRAM Free: 0 B

**Comment by wasd-tech** [comment]
As far as I know Pytorch isn't compiled against gfx1151 (your APU) by default so it will not work for now.
You could try with the packages of this [repo](https://github.com/ROCm/TheRock), they have a pytorch version specifically for your APU. I haven't tested it because I don't own that kind of hardware but I saw that there are numerous discussions that talk about it.

**Comment by marcushoff** [comment]
You're right it's Pytorch. Thank you AMD for releasing an APU with AI in it's name, but not building the AI libraries. I did try the repo and the Pytorch version supposedly working with gfx1151. It breaks requirement dependencies w ComyUI. Maybe I should try building ComfyUI normally and substituting Pytorch

**Comment by marcushoff** [comment]
Update:
Using Pytorch from the repo works.

I did a normal ComyUI install w Python 3.11 following rocm3.4 instructions. Then installed Pytorch on top of that from the repo. Ignoring warnings and manually installing any missing modules. I got it running. I think there are some things, that can be optimized. The Pytorch from the library is 2.7, it might help downgrading all other torch libraries to same level.

````
Checkpoint files will always be loaded safely.
Total VRAM 63970 MB, total RAM 127940 MB
pytorch version: 2.7.0a0+gitbfd8155
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.7.0a0+gitbfd8155)
    Python  3.11.3 (you have 3.11.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
/home/mho/.local/lib/python3.11/site-packages/xformers/triton/softmax.py:30: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16 if _triton_softmax_fp16_enabled else None)
/home/mho/.local/lib/python3.11/site-packages/xformers/triton/softmax.py:86: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
/home/mho/.local/lib/python3.11/site-packages/xformers/ops/swiglu_op.py:106: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd
/home/mho/.local/lib/python3.11/site-packages/xformers/ops/swiglu_op.py:127: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd
xformers version: 0.0.20
AMD arch: gfx1151
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon Graphics : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
Python version: 3.11.11 (main, Dec 11 2024, 16:28:39) [GCC 11.2.0]
ComfyUI version: 0.3.34
ComfyUI frontend version: 1.19.9
[Prompt Server] web root: /home/mho/miniconda3/envs/comfyui/lib/python3.11/site-packages/comfyui_frontend_package/static

Import times for custom nodes:
   0.0 seconds: /home/mho/ComfyUI/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SD1ClipModel
loaded completely 62594.7375 235.84423828125 True
Requested to load BaseModel
loaded completely 62067.00166015625 1639.406135559082 True
100%|███████████████████████████████████████████| 20/20 [00:44<00:00,  2.21s/it]
Requested to load AutoencoderKL
loaded completely 59060.48876953125 319.11416244506836 True
Prompt executed in 157.09 seconds
got prompt
100%|███████████████████████████████████████████| 20/20 [00:05<00:00,  3.52it/s]
Prompt executed in 6.29 seconds


````

**Comment by wasd-tech** [comment]
> You're right it's Pytorch. Thank you AMD for releasing an APU with AI in it's name, but not building the AI libraries. 

I know what you mean, I have an rx 9070 xt.
I think that only with ROCm 7.0 there will be a good compatibility at the same level of CUDA.
I am curious of one thing about this type of APU. Can you test that the gpu has access to all the memory of pc? It will be useful to other people who have this kind of hardware. Maybe you can try to run a huge batch and see if it use all the memory.

**Comment by marcushoff** [comment]
I tried, but gave up after running a batch of 8. It just takes forever to load. Once it's loaded running the second batch is no problem. I assume this has something to do with the implementation not being optimized.
Someone on Reddit said that the stock Fedora rocm and pytorch should work with the APU. So I'm going to try to copy those modules in to comyui and see if it works next.

**Comment by CaptailTyler** [comment]
Can you provide benchmarks of your results when you get it working, I am really interested in this PC, thinking of getting the GMKtec EVO-X2.

**Comment by icarus0508** [comment]
@marcushoff  hi  , i just download https://github.com/ROCm/TheRock/pkgs/container/therock_pytorch_dev_ubuntu_24_04_gfx1151, and activate the docker.  how do i get the pytorch and install comfyui   

Thankyou

**Comment by marcushoff** [comment]
You need to [build](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#manual-install-windows-linux) comfyui in a Python 3.11 environment. 
At the step, where you should install torch, audio and vision, you install the [downloaded](https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x) version. 
Then continue as normal.

**Comment by icarus0508** [comment]
@marcushoff  Thx  it works, only if i should install Numpy = 1.26.4 intead 

Really help a lot

**Comment by wasd-tech** [comment]
@marcushoff I also need to thank you about your experiment with new hardware. I made a guide for ROCm with the list of commands to install all the major programs and your results with AMD RYZEN AI MAX+ 395 are priceless. I will surely add them on the guide.

**Comment by marcushoff** [comment]
No need to thank me. Would like to see you guide when it's done.
BTW, there's a [new pytorch](https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x) out for 3.12 now.

**Comment by wasd-tech** [comment]
@marcushoff I already wrote the guide, you can find it [here](https://github.com/wasd-tech/Guida-AMD-HIP-ROCm). Unfortunately it is still in Italian, but I am translating it in English. I've divided it by topics so it's easy to search for what you want to install. The reason it's in Italian is that it was initially a list of commands, with comments, that I used to install programs for AMD, but then I turned it into a full guide.

**Comment by 0xIslamTaha** [comment]
I really appreciate this thread, so I will write down all the steps that I did to make it works:
```python
conda create -n comfyenv
conda activate comfyenv

git clone git@github.com:comfyanonymous/ComfyUI.git
cd ComfyUI

# check python version 
# python 3.11.9

python -m pip install --upgrade pip
pip install -r requirements.txt

# download the 3 torch file from here https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x
pip install torch-2.7.0a0+rocm_git3f903c3-cp311-cp311-win_amd64.whl
pip install torchaudio-2.7.0a0+52638ef-cp311-cp311-win_amd64.whl
pip install torchvision-0.22.0+9eb57cd-cp311-cp311-win_amd64.whl

python main.py

```

**Comment by m0n5t3r** [comment]
dockerfile that works for me:
```dockerfile
FROM ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_gfx1151:main

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt -y install git
    
RUN git clone https://github.com/comfyanonymous/ComfyUI.git /app

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN python3 -m venv --system-site-packages /venv && \
    /venv/bin/pip install -r requirements.txt

ENV LD_LIBRARY_PATH=/opt/rocm/lib/llvm/lib:

CMD ["/venv/bin/python3", "main.py", "--listen", "--port", "8188", "--base-directory", "/data/"]
EXPOSE 8188
```

(where by "works" I mean "comfyui starts up and workflows run fine up to the VAE, where they crash with a page fault in dmesg, as documented [here](https://github.com/ROCm/TheRock/issues/986)")

edited to add: initially I had to supply `requirements.txt` because I was using the `rocm/pytorch` image as a base, and it had no `torchaudio`, and simply installing `torchaudio` with pip pulled a whole different torch that's nvidia-specific and wouldn't work; afterwards I discovered that the comfyui manager also has some dependencies it needs, so I've added those to the requirements even if I keep `custom_nodes` in a volume - I hate the manager because it's highly incompatible with containerization, but it offers a convenient way to download a number of models I wouldn't know where to find otherwise)

**Comment by wasd-tech** [comment]
> "comfyui starts up and workflows run fine up to the VAE, where they crash with a page fault in dmesg, as documented https://github.com/ROCm/TheRock/issues/986"

@m0n5t3r You can try to run the tiled version of the VAE Decode and also setting is precision to bf16 by adding `--bf16-vae` at the end of the command. It is a know issue by the way, I also have it with my rx 9070 xt.

**Comment by m0n5t3r** [comment]
that doesn't help in this case, but works almost fine with `--cpu-vae` (the CPU is fast enough that there's not much difference, maybe it's even faster at least for what I've tried); there are random crashes in CLIP occasionally, and reliable crashes in the upscaler-with-model, just like the VAE before (tried 2 upscaler models, but I don't really now what I'm doing)

**Comment by KoDelioDa** [comment]
I encountered the same problem, whether it was with comfyui, invoke-ai, or even the source code.



from diffusers import StableDiffusionPipeline import torch

model_id = "sd-legacy/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

image.save("astronaut_rides_horse.png")


They will all crash at approximately the VAE position, throwing an "Aborted (core dumped)" error.

**Comment by wasd-tech** [comment]
@m0n5t3r @marcushoff @KoDelioDa and all the people that have a gfx1151
AMD just released ROCm 6.4.2 and it says:

> hipBLASLt (0.12.1)
> Added
>     Support for gfx1151 on Linux, complementing the previous support in the HIP SDK for Windows.

https://rocm.docs.amd.com/en/latest/about/release-notes.html
I suggest that if there are errors with torch downloaded from the official pytorch, you can try to download it from https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/. Unfortunately this suggestion only applies to linux though.

I hope it solves some of the problems

**Comment by m0n5t3r** [comment]
Thanks for the info, updating the host amdgpu driver (and ROCm, but that's more or less irrelevant for the containers I think) seems to have made some things much faster (LLMs mainly, but maybe image models too)

The issues with VAE and upscalers persist though; TheRock folks build / release a pre-release version of ROCm anyway (7.0.0 right now) and torch 2.7.0:

```
Python 3.12.3 (main, Jun 18 2025, 17:59:45) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocm_sdk
>>> rocm_sdk.__version__
'7.0.0rc20250715'
>>> import torch
>>> torch.__version__
'2.7.0a0+rocm7.0.0rc20250715'
```

I don't know what VAE and upscalers do differently from the image models (or why the FLUX CLIP crashes a few times at first and then works flawlessly), but I have a suspicion there's not much Comfy can do about it, though, since crashing happens in somewhere in torch code, or even the drivers - amdgpu complains about page faults in dmesg.

**Comment by KoDelioDa** [comment]
@m0n5t3r @wasd-tech 

---

Thank you for your suggestion. I was very excited when I received this message. However, after installing ROCm 6.4.2 and trying to install PyTorch both from the official website and from [https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/](https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/), I still encountered errors. This time, the issue seems more complex and is likely caused by changes in the latest ROCm version.

1. When I used the official PyTorch build and ran ComfyUI, it showed that no CUDA device was found.
2. When I used the PyTorch build from [https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/](https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/), I received the following error:

   ```
   File "/home/node1/ComfyUI/comfy/ops.py", line 237, in forward
       return self.forward_comfy_cast_weights(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/node1/ComfyUI/comfy/ops.py", line 233, in forward_comfy_cast_weights
       return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/node1/miniconda3/envs/cf2/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
       return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   RuntimeError: HIP error: invalid device function
   HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
   For debugging consider passing AMD_SERIALIZE_KERNEL=3
   Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
   ```
3. Following the error in point 2, I manually set environment variables based on [[this script](https://github.com/lhl/strix-halo-testing/blob/main/rocm-env.sh)](https://github.com/lhl/strix-halo-testing/blob/main/rocm-env.sh) in an attempt to fix the issue. After doing so, the following error occurred:

   ```
   got prompt
   model weight dtype torch.float16, manual cast: None
   model_type EPS
   Segmentation fault (core dumped)
   ```

---

**Comment by m0n5t3r** [comment]
for your point 1, pytorch isn't distributing official builds for ROCm 6.4 yet, you'd have to install them from nightly (https://pytorch.org/get-started/locally/ - select preview, linux, pip, python and it will give you the command to install torch; I didn't have much luck with it)

**Comment by wasd-tech** [comment]
@KoDelioDa I'm sorry if I gave you false expectations :cry: I don't have that hardware some I can only point sources.

@m0n5t3r  I also think there are more general problems with ROCm/Torch than with specific programs. I encountered very similar problems with all the AI programs that I tried (ComfyUI, WanGP, fluxgym, kohya_ss). @KoDelioDa  pointed out that even transformer itself has problems. And the most important thing is that there are identical bugs on different GPUs (I have an rx 9070 xt).

If someone want to open an issue on the ROCm/torch side (regarding for example the VAE bug) I will surely join the conversation

**Comment by KoDelioDa** [comment]
---

When issue **3** occurred, I went back to issue **2** and set environment variables to spoof the system, as shown in **4**:

```
export HSA_OVERRIDE_GFX_VERSION=11.0.0
export AMD_SERIALIZE_KERNEL=3
```

Then I launched ComfyUI using:

```
python main.py --listen 0.0.0.0
```

However, when I clicked "Run" to start generating images, an error still occurred, as shown in **5**:

```
To see the GUI go to: http://0.0.0.0:8188

got prompt

model weight dtype torch.float16, manual cast: None

model_type EPS

Using split attention in VAE

Using split attention in VAE

VAE load device: cuda:0, offload device: cpu, dtype: torch.float32

CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16

loaded diffusion model directly to GPU

Requested to load BaseModel

loaded completely 9.5367431640625e+25 1639.406135559082 True

Requested to load SD1ClipModel

loaded completely 95122.82880859375 235.84423828125 True

0%| | 0/20 [00:00<?, ?it/s]:0:rocdevice.cpp :2994: 3461243762 us: Callback: Queue 0x7501ba000000 aborting with error : HSA_STATUS_ERROR_INVALID_ISA: The instruction set architecture is invalid. code: 0x100f

Aborted (core dumped)
```

After the error in **5**, I went back again to **4**, kept the environment variables, and started ComfyUI with the following command in **6**:

```
python main.py --listen 0.0.0.0 --force-fp32 --fp32-unet --fp32-vae --fp32-text-enc
```

This time it worked:

```
got prompt
model weight dtype torch.float32, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
Requested to load SD1ClipModel
loaded completely 9.5367431640625e+25 471.6884765625 True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float32
loaded diffusion model directly to GPU
Requested to load BaseModel
loaded completely 9.5367431640625e+25 3278.812271118164 True
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.99it/s]
Requested to load AutoencoderKL
loaded completely 91885.9658203125 319.11416244506836 True
Prompt executed in 8.12 seconds
got prompt
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:04<00:00,  3.23s/it]
Prompt executed in 65.80 seconds
```

---




> [@m0n5t3r](https://github.com/m0n5t3r) [@wasd-tech](https://github.com/wasd-tech)
> 
> Thank you for your suggestion. I was very excited when I received this message. However, after installing ROCm 6.4.2 and trying to install PyTorch both from the official website and from https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/, I still encountered errors. This time, the issue seems more complex and is likely caused by changes in the latest ROCm version.谢谢你的建议。当我收到这条消息时，我非常兴奋。但是，在安装 ROCm 6.4.2 并尝试从官网和 https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/ 安装 PyTorch 后，我仍然遇到错误。这一次，问题似乎更加复杂，很可能是由最新 ROCm 版本的更改引起的。
> 
> 1. When I used the official PyTorch build and ran ComfyUI, it showed that no CUDA device was found.当我使用官方 PyTorch 版本并运行 ComfyUI 时，它显示没有找到 CUDA 设备。
> 2. When I used the PyTorch build from https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/, I received the following error:当我使用 https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.2/ 的 PyTorch 版本时，我收到以下错误：
>    ```
>    File "/home/node1/ComfyUI/comfy/ops.py", line 237, in forward
>        return self.forward_comfy_cast_weights(*args, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/home/node1/ComfyUI/comfy/ops.py", line 233, in forward_comfy_cast_weights
>        return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/home/node1/miniconda3/envs/cf2/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
>        return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    RuntimeError: HIP error: invalid device function
>    HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
>    For debugging consider passing AMD_SERIALIZE_KERNEL=3
>    Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
>    ```
> 3. Following the error in point 2, I manually set environment variables based on [[this script](https://github.com/lhl/strix-halo-testing/blob/main/rocm-env.sh)](https://github.com/lhl/strix-halo-testing/blob/main/rocm-env.sh) in an attempt to fix the issue. After doing so, the following error occurred:在第 2 点出现错误之后，我根据 [[ 此脚本 ](https://github.com/lhl/strix-halo-testing/blob/main/rocm-env.sh)]（https://github.com/lhl/strix-halo-testing/blob/main/rocm-env.sh） 手动设置环境变量，以尝试解决该问题。这样做后，发生以下错误：
>    ```
>    got prompt
>    model weight dtype torch.float16, manual cast: None
>    model_type EPS
>    Segmentation fault (core dumped)
>    ```

A. I haven't tested images with different precisions.
B. I haven't tested it on Flux. Maybe I won't test Flux. My current project only needs SDXL.
C. It doesn't seem necessary to use Rocm 6.4.2 to use environment variables. I have seen other projects (LLM) using Rocm of gfx1100 to run.
I have tested 8060S in different projects (image generation, LLM, etc.). I think this is the incompatibility between the underlying Rocm and Pytorch, and this incompatibility may have many various problems, which will make the comfyui experience poor.
Anyway, I can run sdxl now, my project is complete, it's time to use CUDA lol)

**Comment by fanyang89** [comment]
Mine works fine. Arch Linux + Linux 6.15.7-arch1-1

```
sudo pacman -S python-pytorch-opt-rocm
yay -S python-torchvision-rocm
python -m pip install -r requirements.txt --break-system-packages  # comfyui packages only
```

I didn't install torchaudio since I don't need it.

```
-> % python main.py --listen 0.0.0.0 --fast fp16_accumulation
Checkpoint files will always be loaded safely.
Total VRAM 65536 MB, total RAM 63933 MB
pytorch version: 2.7.1
AMD arch: gfx1151
ROCm version: (6, 4)
Set vram state to: NORMAL_VRAM
Device: cuda:0 Radeon 8060S Graphics : native
Using pytorch attention
torchaudio missing, ACE model will be broken
torchaudio missing, ACE model will be broken
Python version: 3.13.5 (main, Jun 21 2025, 09:35:00) [GCC 15.1.1 20250425]
ComfyUI version: 0.3.44
ComfyUI frontend version: 1.23.4
[Prompt Server] web root: /home/<hide>/.local/lib/python3.13/site-packages/comfyui_frontend_package/static

Import times for custom nodes:
   0.0 seconds: /home/<hide>/workspace/ComfyUI/custom_nodes/websocket_image_save.py

Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://0.0.0.0:8188
^C
Stopped server
```

**Comment by m0n5t3r** [comment]
yeah, but does it actually generate images? because it starts for those who see the issue, and then it crashes on VAE or upscaling

**Comment by pccr10001** [comment]
Get worked ComfyUI on AI MAX+ 395, install `triton` to avoid the VAE error.

* Install docker
* Clone ComfyUI
```
apt update
apt install git -y
git clone https://github.com/comfyanonymous/ComfyUI
```
* Launch container with official ROCm container
```
 docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
--device=/dev/kfd --device=/dev/dri --group-add video \
-v `pwd`/ComfyUI:/opt/ComfyUI -p 8188:8188 \
--ipc=host --shm-size 8G ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_gfx1151:main
```
* Fix OpenMP library
```
echo '/opt/rocm/lib/llvm/lib' >> /etc/ld.so.conf.d/rocm.conf
rm /etc/ld.so.cache
ldconfig
```
* Install packages
```
cd /opt/ComfyUI
pip install -r requirements.txt  --break-system-packages
pip install triton==3.2.0 # fix VAE crash on GPU
```
* Launch ComfyUI
```
PYTORCH_TUNABLEOP_ENABLED=1 MIOPEN_FIND_MODE=FAST ROCBLAS_USE_HIPBLASLT=1 python3 main.py --listen 0.0.0.0
```

**Comment by treviloan** [comment]
Just curious if anyone has gotten this to work?

**Comment by vchrizz** [comment]
Chiming in because I have the same hardware and seem to run into same issue(s) mentioned here.

**Comment by kenny8zeng** [comment]
Same AMD 395 hardware and issues, am continuing to follow progress ......

**Comment by treviloan** [comment]
I did get this working on my GMKTec AMD Ryzen™ AI Max+ 395 --EVO-X2 running Ubuntu 24.04

I am using docker with Rocm 6.4.3 from AMD 

following the instructions here for driver install:
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html

GPU permissions:
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/prerequisites.html#group-permissions

and then I shared my dockerfile and sample compose here:
https://github.com/treviloan/Comfy-gfx1151

I did have to force fp32, the initial load is a little slow but decent after. I will keep looking for optimizations.

**Comment by kenny8zeng** [comment]
> I did get this working on my GMKTec AMD Ryzen™ AI Max+ 395 --EVO-X2 running Ubuntu 24.04
> 
> I am using docker with Rocm 6.4.3 from AMD
> 
> following the instructions here for driver install: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html
> 
> GPU permissions: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/prerequisites.html#group-permissions
> 
> and then I shared my dockerfile and sample compose here: https://github.com/treviloan/Comfy-gfx1151
> 
> I did have to force fp32, the initial load is a little slow but decent after. I will keep looking for optimizations.

Judging from my verification, this operation successfully completed the official basic literary and artistic process.
However, comfyui seems unstable when I use qwen image, the process crashes and exits during the execution text to image process, and I'm not sure what's the reason.

Obviously, @treviloan tells us that the most important thing is to specify all model categories to use fp32 precision.

**Comment by pccr10001** [comment]
I compiled PyTorch 2.8.0 and Flash Attention and I can get 1.02it/s (904*1600) on AI+ MAX 395.
<img width="1453" height="85" alt="Image" src="https://github.com/user-attachments/assets/f220eee2-0c83-4acc-8f75-957f93893127" />
 
* Official image (torch 2.7.0, ROCm 250715) 68% faster
<img width="1448" height="93" alt="Image" src="https://github.com/user-attachments/assets/a4c6d348-6e34-434d-902a-7501f5be0352" />
* AOTriton enabled
<img width="1452" height="80" alt="Image" src="https://github.com/user-attachments/assets/e7bf0254-4f23-485b-a592-592a54279945" />

### Docker
* Check with [https://github.com/pccr10001/comfyui-gfx1151-fa?tab=readme-ov-file#docker](https://github.com/pccr10001/comfyui-gfx1151-fa?tab=readme-ov-file#docker) first
```
git clone https://github.com/pccr10001/comfyui-gfx1151-fa
cd comfyui-gfx1151-fa
mkdir ComfyUI
docker compose up -d
```
* Move models to `ComfyUI/models`

### Manual Step
* Install docker
* Launch container with official ROCm image
```
docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
--device=/dev/kfd --device=/dev/dri --group-add video \
-v `pwd`/ComfyUI:/opt/ComfyUI -p 8188:8188 \
--ipc=host --shm-size 8G ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_gfx1151:main
```
* Grab wheels from [release](https://github.com/pccr10001/rocm-pytorch-gfx1151/releases/tag/v2.8.0a0)
* Uninstall preloaded torch
```
pip uninstall torch torchvision torchaudio --break-system-packages -y
```
* Install wheels
```
pip install ./torch-2.8.0a0+gitba56102-cp312-cp312-linux_x86_64.whl ./torchaudio-2.8.0a0+6e1c7fe-cp312-cp312-linux_x86_64.whl ./torchvision-0.23.0a0+824e8c8-cp312-cp312-linux_x86_64.whl  ./flash_attn-2.0.4-cp312-cp312-linux_x86_64.whl  --break-system-packages
```
* Install ROCm Python dependences
```
pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx1151/ rocm[libraries,devel] --break-system-packages
```
* Install ComfyUI dependences
```
pip install -r requirements.txt --break-system-packages
```
* Fix ROCm library path
```
echo /usr/local/lib/python3.12/dist-packages/_rocm_sdk_core/lib >> /etc/ld.so.conf
ldconfig
```
* Launch ComfyUI
```
PYTORCH_TUNABLEOP_ENABLED=1 MIOPEN_FIND_MODE=FAST ROCBLAS_USE_HIPBLASLT=1 python3 main.py --listen 0.0.0.0 --use-flash-attention
```
* Happy generating

**Comment by m0n5t3r** [comment]
An update: using packages from https://github.com/ROCm/TheRock/ like 

```
pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx1151/ torch==2.7.1+rocm7.0.0rc20250825 torchvision==0.22.1+rocm7.0.0rc20250825 torchaudio==2.7.1a0+rocm7.0.0rc20250825
```

works for me with the current `amdgpu` driver (`6.12.12`); I haven't seen any crashes or VAE / upscaler issues in the cursory testing I did. 

Specifying the version is needed for now due to some issues on the dependencies and the build process for TheRock (at the moment `20250825` is the last working build, if you install without specifying versions you get `amdgpu-arch not found` on importing `torch` and a segfault on importing `torchaudio`, due to it pulling `torchaudio` `2.8.0` and torch `2.7.1`; if you specify the versions but use a build more recent than `20250825` you just get `amdgpu-arch not found` on both.

**Comment by m0n5t3r** [comment]
incidentally, you don't need a rocm ubuntu base image for your container, my current dockerfile is this

```dockerfile
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt -y update && \
    apt -y install git python3-venv libatomic1 libgomp1 

RUN git clone https://github.com/comfyanonymous/ComfyUI.git /app

WORKDIR /app

RUN python3 -m venv --system-site-packages /venv && \
    /venv/bin/pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx1151/ torch==2.7.1+rocm7.0.0rc20250825 torchvision==0.22.1+rocm7.0.0rc20250825 torchaudio==2.7.1a0+rocm7.0.0rc20250825 && \
    /venv/bin/pip install -r requirements.txt && \
    rm -rf /root/.cache/pip

CMD ["/venv/bin/python3", "main.py", "--listen", "--port", "8188", "--base-directory", "/data/", "--database-url", "sqlite:////data/user/comfyui.db"]
EXPOSE 8188
```

(I'm mounting the custom nodes, models, etc in `/data`)

**Comment by m0n5t3r** [comment]
... and as a final point, after discussions in https://github.com/ROCm/TheRock/issues/1262 and https://github.com/ROCm/TheRock/issues/1421#issuecomment-3271701992: 

* running a `pip install --index [...] torch torchaudio torchvision` will pull a mismatched version of `torchaudio`, so you need to either specify the version, i.e. `torchaudio==2.7.1a0`, or do `pip install --pre` to pull torch 2.9.0, etc.
* the `amdgpu-arch not found` thing is due to the venv bindir not being in `PATH` (turns out `amdgpu-arch` is a script that ultimately calls a rocm binary and returns `gfx1151`), so the workaround to that is either adding `/path/to/venv/bin` it to `PATH`, or setting `ROCM_SDK_TARGET_FAMILY=gfx1151` so it doesn't try to run the `amdgpu-arch` binary

**Comment by Bricklou** [comment]
I have a similar issue on an AMD Radeon 7900 XTX.

**Comment by RobertoMaurizzi** [comment]
and they finally released ROCm 6.4.4 and related versions of PyTorch and friends that do work for Strix Points and Strix Halos... 😩 

Compatibility matrix: https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/compatibility/compatibilityryz/native_linux/native_linux_compatibility.html#rocm-6-4-4
Installation: https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installryz/native_linux/install-ryzen.html
Pytorch wheels: https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installryz/native_linux/install-pytorch.html

I'm running a 370 on Debian testing with kernel 6.16.7, but the in-kernel driver seems to work properly with the drivers (the dkms module doesn't build (or at least it didn't in 6.4.3, didn't try again), so I expect it to work on the 395 too.

With this new versions I don't need to use `HSA_OVERRIDE_GFX_VERSION=11.0.2` anymore and I get ~60 seconds for an image that takes ~25 on a 3070 Laptop version (since I finally don't need to add `--force-fp32`)

**Comment by wasd-tech** [comment]
@RobertoMaurizzi I suggest you to also take a look at this as well: https://github.com/ROCm/TheRock/blob/main/RELEASES.md

There are wheels for Windows too! They worked for me on my rx 9070 xt so hopefully they will work for you, too!

**Comment by SiegeKeebsOffical** [comment]
This is what worked for me using Bazzite - the steps listed by pccr10001 had to be slightly re-arranged/adjusted to work

https://github.com/SiegeKeebsOffical/Bazzite-ComfyUI-AMD-AI-MAX-395/tree/main

**Comment by RobertoMaurizzi** [comment]
I did try TheRock wheels and also their docker image, but they didn't work on/for a gfx1150 apparently.
I assume they might start now since there's official support.

**Comment by wfox4** [comment]
Thanks @RobertoMaurizzi Finally was able to use the normal VAE encode and decode on Ubuntu using https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installryz/native_linux/install-pytorch.html (I used firefox to use comfyui, heard people had problems with brave browser... idk i just heard it around) Also want to say it's my first year on linux so I'm still learning alot but this was the easiest way to get it working.
14.51s/it on a qwen image edit 2509 image sized at 1328x784. Not the best but atleast I can use it

**Comment by IgnatBeresnev** [comment]
Hi, I made yet another `comfyui-gfx-1151` repo, hopefully the solution in it works at least for a couple of months 🥲 

https://github.com/IgnatBeresnev/comfyui-gfx1151

I described the reasons why and how it works in detail in the README. Long story short, a lot of information from above seems to be outdated, and the image and wheels from [pccr10001/comfyui-gfx1151-fa](https://github.com/pccr10001/comfyui-gfx1151-fa) don't seem to work anymore. Thankfully, if you take the official pytorch docker image published recently by AMD, you can get ComfyUI up and running with flash-attention (well, triton) in a jiffy, without installing any custom-built wheels.

**Comment by DasPauluteli** [comment]
> ⚠️ **Outdated — see my [updated follow-up below](https://github.com/Comfy-Org/ComfyUI/issues/8211#issuecomment-4951924507) and the maintained script in the [gist](https://gist.github.com/DasPauluteli/78748b6df5a1bc876b649286d8bc04f6).** The inline script below still works, but some details here are superseded (GTT `--set` is in **GB not %**, the script now auto-detects your **gfx115x** arch, and I dropped `--high-ram`/`--disable-mmap`). Grab the current version from the gist.

For anyone landing here on a **Ryzen AI MAX+ 395 / Radeon 8060S (gfx1151)**: this is fully working now on a current stack, no `--force-fp32`, no `HSA_OVERRIDE_GFX_VERSION`, no fp32 hacks. Most of the pain in this thread is from the old ROCm 6.4.x era. Moving to a current ROCm fixes the `HIP error: invalid device function` / `HSA_STATUS_ERROR_INVALID_ISA` crashes outright.

**_"I don't care about technical details, I just want ComfyUI to work."_**, great! [Click here for my convenience script](https://github.com/Comfy-Org/ComfyUI/issues/8211#:~:text=precision%20workarounds%20needed.-,Script,-Below%2C%20you%27ll%20find)

**Working setup (Arch/CachyOS, kernel 6.x):**

Within a Python 3.13.13 venv:
`uv venv -p 3.13`

PyTorch from the ROCm 7.2 stable wheels:
`uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm7.2`

The gfx1151 AMD nightlies (`--pre --index-url https://rocm.nightlies.amd.com/v2/gfx1151/`) also work and are a bit faster, but expect **missing features/regressions**. Stick to stable unless you want to debug. Note: on the nightly index you need `--pre` (or pinned versions), otherwise you get a mismatched `torchaudio`.

Env vars (gfx1151 attention path):
```
export TORCH_BLAS_PREFER_HIPBLASLT=1
export TORCH_ROCM_AOTRITON_ENABLE=1
export FLASH_ATTENTION_TRITON_AMD_ENABLE=1
```

**The big one for unified memory: set the GTT split.** By default the GPU only gets a small carveout of system RAM, which causes stalls/OOM on large models. Give it (almost) all of it:
```
uv tool install amd-debug-tools
sudo amd-ttm --set 100
```
This made the largest difference for big checkpoints. (Re-run after reboot if it doesn't persist.)

**Launch flags that actually matter:**
```
python main.py --use-pytorch-cross-attention --disable-mmap --high-ram
```
- `--use-pytorch-cross-attention` → routes into the AOTriton flash kernels; biggest quality-neutral inference speedup here.
- `--disable-mmap` → if your models live on a compressed btrfs subvol (zstd), mmap demand-paging faults pages in slowly with a per-fault decompress. Disabling mmap reads the file sequentially at full NVMe speed instead. On my box this turned a ~4 min cold load of a 17 GB checkpoint into near-instant.
- **Do NOT use `--force-channels-last`** — it triggers a per-tensor memory-format conversion during load that's useless for DiT/transformer models (Flux, Chroma, SD3) and adds minutes to load time single-threaded.

Generating fine on Flux/Chroma/SDXL at full fp16, no precision workarounds needed.

### Script

Below, you'll find my personal ComfyUI start script. It automatically installs, updates and manages ComfyUI.
I also included my AMD APU fork [DasPauluteli/ComfyUI-AMDGPUMonitor](https://github.com/DasPauluteli/ComfyUI-AMDGPUMonitor) of [iDAPPA/ComfyUI-AMDGPUMonitor](https://github.com/iDAPPA/ComfyUI-AMDGPUMonitor) for your convenience.

![AMD GPU Monitor Screenshot](https://github.com/DasPauluteli/ComfyUI-AMDGPUMonitor/raw/main/screenshot.png)

Instructions are at the top of the script.

Requirements:
- uv
- git
- fish
- amdsmi and/or rocm-smi-lib
- amd-debug-tools

To install on Arch based distros:
```
sudo pacman -S uv git fish amdsmi rocm-smi-lib
uv tool install amd-debug-tools
```

Here's the script. Drop it in the directory you want ComfyUI installed to as e.g. start.fish
```fish
#!/usr/bin/fish

# ════════════════════════════════════════════════════════════
#  ComfyUI · gfx1151 (Ryzen AI MAX+ 395 / Radeon 8060S)
#  Install + update + launch
# ════════════════════════════════════════════════════════════
#
#  USAGE:
#    Drop this script into your ComfyUI folder and run it:
#        fish start.fish
#    The script uses its OWN location as the ComfyUI directory,
#    so there's nothing to configure. If the folder doesn't
#    contain ComfyUI yet, it installs it in place on first run.
#
#  CHANGING THE ROCm VERSION:
#    Edit TORCH_CHANNEL below.
#      stable   → recommended. Released ROCm wheels, fewest surprises.
#      nightly  → experimental. gfx1151 AMD nightlies. Can be faster
#                 and ship newer kernels, but may be missing features
#                 or carry regressions/bugs. Switch back to stable if
#                 anything breaks.
#
#  ONE-TIME SETUP (run these yourself once, not handled below):
#
#    1. Install uv (if you don't have it):
#         curl -LsSf https://astral.sh/uv/install.sh | sh
#
#    2. GTT / unified-memory split — let the GPU address (almost)
#       all of system RAM instead of the small default carveout.
#       This is the single most important knob on Strix Halo for
#       big models; without it large checkpoints can stall or OOM.
#
#         uv tool install amd-debug-tools
#         sudo amd-ttm --set 100        # give GTT up to 100% of RAM
#         amd-ttm                       # verify (no args = read current)
#
#       NOTE: the TTM limit is NOT guaranteed to persist across a
#       reboot. If you hit slow loads / OOM after rebooting, re-run
#       `sudo amd-ttm --set 100`. The launch checks it for you below.
#
# ════════════════════════════════════════════════════════════

# Use the directory this script lives in as the ComfyUI directory.
set COMFYUI_DIR (path resolve (path dirname (status filename)))
set COMFYUI_REPO https://github.com/comfyanonymous/ComfyUI.git
set COMFYUI_BRANCH master
set PYTHON_VERSION 3.13          # proven working on gfx1151

# ── ROCm / PyTorch channel ──────────────────────────────────
set TORCH_CHANNEL stable          # "stable" or "nightly" — see USAGE above

cd $COMFYUI_DIR

# ── Colors ──────────────────────────────────────────────────
set RESET  (set_color normal)
set BOLD   (set_color --bold white)
set DIM    (set_color brblack)
set GREEN  (set_color green)
set YELLOW (set_color yellow)
set RED    (set_color red)
set CYAN   (set_color cyan)
set ORANGE (set_color bryellow)
set WHITE  (set_color white)

function section
    echo "$CYAN┌─ $BOLD$argv[1]$RESET"
end
function ok
    echo "$GREEN│ ✓$RESET $argv"
end
function warn
    echo "$YELLOW│ ⚠$RESET $argv"
end
function err
    echo "$RED│ ✗$RESET $argv"
end
function info
    echo "$CYAN│   $RESET$argv$RESET"
end
function done_section
    echo "$CYAN└──────────────────────────────$RESET"
    echo ""
end

# ── Tooling check ───────────────────────────────────────────
section "Tooling"
if not type -q uv
    err "uv not found. Install with:"
    info "curl -LsSf https://astral.sh/uv/install.sh | sh"
    done_section
    exit 1
end
ok "uv found"
if not type -q git
    err "git not found"
    done_section
    exit 1
end
ok "git found"
done_section

# ── Channel configuration ───────────────────────────────────
if test $TORCH_CHANNEL = nightly
    set TORCH_LABEL  "PyTorch (gfx1151 Nightly)"
    set TORCH_FLAGS  --pre
    set TORCH_INDEX  https://rocm.nightlies.amd.com/v2/gfx1151/
    set TORCH_BANNER "gfx1151 · ROCm Nightly (experimental)"
else
    set TORCH_LABEL  "PyTorch (Stable)"
    set TORCH_FLAGS
    set TORCH_INDEX  https://download.pytorch.org/whl/rocm7.2
    set TORCH_BANNER "gfx1151 · ROCm Stable (7.2)"
end

# ── Installation (if this folder isn't ComfyUI yet) ─────────
set FRESH_INSTALL false
if not test -e main.py
    section "Installation"
    info "No ComfyUI here – installing into $COMFYUI_DIR"
    if not test -d .git
        git init -q
    end
    if not git remote | string match -q origin
        git remote add origin $COMFYUI_REPO
    end
    git fetch origin 2>&1 | while read -l line; info $line; end
    # -f overwrites tracked files only; this script (untracked) is kept.
    git checkout -f -B $COMFYUI_BRANCH origin/$COMFYUI_BRANCH 2>&1 | while read -l line; info $line; end
    if not test -e main.py
        err "Install failed (main.py still missing)"
        done_section
        exit 1
    end
    info "Creating venv (Python $PYTHON_VERSION)"
    uv venv --python $PYTHON_VERSION .venv 2>&1 | while read -l line; info $line; end
    if test $pipestatus[1] -ne 0
        err "venv creation failed"
        done_section
        exit 1
    end
    set FRESH_INSTALL true
    ok "ComfyUI installed, venv ready"
    done_section
end

# ── Custom nodes ────────────────────────────────────────────
# AMDGPUMonitor: live GPU/VRAM/GTT readout in the ComfyUI UI.
# Needs rocm-smi or amd-smi on PATH (Arch: pacman -S amdsmi rocm-smi-lib).
section "Custom nodes"
set NODE_DIR custom_nodes/ComfyUI-AMDGPUMonitor
set NODE_REPO https://github.com/DasPauluteli/ComfyUI-AMDGPUMonitor.git
if test -d $NODE_DIR/.git
    timeout 5 git -C $NODE_DIR pull 2>&1 | while read -l line; info $line; end
    if test $pipestatus[1] -eq 0
        ok "AMDGPUMonitor up to date"
    else
        warn "AMDGPUMonitor pull failed (offline?) – keeping current"
    end
else
    info "Installing AMDGPUMonitor"
    git clone $NODE_REPO $NODE_DIR 2>&1 | while read -l line; info $line; end
    if test $pipestatus[1] -eq 0
        ok "AMDGPUMonitor installed"
    else
        warn "AMDGPUMonitor clone failed"
    end
end
if not type -q rocm-smi; and not type -q amd-smi
    warn "Neither rocm-smi nor amd-smi on PATH – monitor will show no data"
    info "Arch: sudo pacman -S amdsmi rocm-smi-lib"
end
done_section

# ── ROCm environment for gfx1151 ────────────────────────────
set -x TORCH_BLAS_PREFER_HIPBLASLT 1
set -x TORCH_ROCM_AOTRITON_ENABLE 1
set -x FLASH_ATTENTION_TRITON_AMD_ENABLE 1

source .venv/bin/activate.fish

# ── GTT / TTM check ─────────────────────────────────────────
section "GTT / Unified Memory"
if type -q amd-ttm
    set TTM_LINE (amd-ttm 2>/dev/null | string match -r 'pages limit:.*')
    if test -n "$TTM_LINE"
        info $TTM_LINE
    end
    ok "amd-ttm present – on slow loads run: sudo amd-ttm --set 100"
else
    warn "amd-ttm not found – GTT split may be on the (small) default"
    info "One-time: uv tool install amd-debug-tools"
    info "Then:     sudo amd-ttm --set 100"
end
done_section

# ── Git pull ────────────────────────────────────────────────
if test $FRESH_INSTALL = false
    section "Repository"
    timeout 5 git pull 2>&1 | while read -l line; info $line; end
    if test $pipestatus[1] -eq 0
        ok "Repository up to date"
    else
        warn "Git pull failed (offline?) – starting anyway"
    end
    done_section
end

# ── Torch ────────────────────────────────────────────────────
section $TORCH_LABEL
info "Checking for updates..."
# NOTE: --pre is required on the gfx1151 index, otherwise uv pulls
# an incompatible torchaudio (see Comfy-Org/ComfyUI#8211).
uv pip install $TORCH_FLAGS torch torchvision torchaudio \
    --index-url $TORCH_INDEX 2>&1 | while read -l line; info $line; end
if test $pipestatus[1] -eq 0
    ok "Torch up to date"
else
    warn "Torch update failed"
end
done_section

# ── Requirements (only when changed) ────────────────────────
section "Dependencies"
set REQ_HASH (md5sum requirements.txt | cut -d' ' -f1)
set HASH_FILE .venv/.req_hash

if not test -f $HASH_FILE; or test (cat $HASH_FILE) != $REQ_HASH
    info "requirements.txt changed, installing..."
    uv pip install -r requirements.txt 2>&1 | while read -l line; info $line; end
    if test $pipestatus[1] -eq 0
        echo $REQ_HASH > $HASH_FILE
        ok "Dependencies updated"
    else
        warn "Installation failed"
    end
else
    ok "Dependencies unchanged, skipped"
end
done_section

# ── Start ────────────────────────────────────────────────────
echo -e "$ORANGE

 ▄▄▄▄▄▄▄                  ▄▄       ▄▄▄  ▄▄▄ ▄▄▄▄▄
███▀▀▀▀▀                 ██        ███  ███  ███
███      ▄███▄ ███▄███▄ ▀██▀ ██ ██ ███  ███  ███
███      ██ ██ ██ ██ ██  ██  ██▄██ ███▄▄███  ███
▀███████ ▀███▀ ██ ██ ██  ██   ▀██▀ ▀██████▀ ▄███▄
                               ██
                             ▀▀▀

$RESET"
echo "$WHITE  $TORCH_BANNER · 128GB unified memory$RESET"
echo ""
printf "$YELLOW  Press any key to start...$RESET"
stty -icanon -echo; dd bs=1 count=1 2>/dev/null >/dev/null; stty icanon echo
echo ""
echo ""

python main.py \
    --enable-manager \
    --preview-method auto \
    --use-pytorch-cross-attention \
    --disable-mmap \
    --high-ram 2>&1 | while read -l line
    echo $line
    if string match -q "*To see the GUI go to:*" $line
        set -l url (string match -r 'https?://\S+' $line)
        if type -q xdg-open
            xdg-open $url &
        else if type -q open
            open $url &
        end
    end
end | tee -a ./logs/comfyui.log
```

**Comment by DasPauluteli** [comment]
**Update (2026-07-12) — revised script, plus two corrections to my comment above.**

The maintained version now lives in a gist (one script: install + update + launch, bundles the [AMDGPUMonitor](https://github.com/DasPauluteli/ComfyUI-AMDGPUMonitor) node, optional auto-generated desktop launcher): **https://gist.github.com/DasPauluteli/78748b6df5a1bc876b649286d8bc04f6**

**What changed since the comment above:**
- **Nightly is now the default channel** — AMD's TheRock multi-arch index. The script now **auto-detects your GPU arch** (via `amd-smi`/`rocminfo`) and installs the matching per-arch device extra, e.g. `uv pip install --pre --upgrade "torch[device-gfx1151]" "torchvision[device-gfx1151]" torchaudio --index-url https://rocm.nightlies.amd.com/whl-multi-arch`. **Heads-up on `gfx115x`:** the index lists an `amd-torch-device-gfx115x` package, but there is **no `device-gfx115x` pip extra** — it only comes in as a dependency of the per-arch extras (and torchvision has no gfx115x family package at all), so `torch[device-gfx115x]` just warns and silently installs a **device-less (broken) torch**. Use the per-arch extra for your chip. Stable (rocm7.2) stays as a fallback. Note the `--upgrade` — without it an already-installed nightly reports "already satisfied" and never moves.
- **A few more env vars help on gfx1151:** `PYTORCH_ALLOC_CONF=expandable_segments:True`, `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1`, `COMFYUI_ENABLE_MIOPEN=1`, `MIOPEN_FIND_MODE=FAST`.

**Two corrections to what I wrote above:**
- **`amd-ttm --set` takes GIGABYTES, not a percentage.** `sudo amd-ttm --set 100` = a 100 GB GTT limit (≈28 GB left for the OS on a 128 GB box), not "100% of RAM". It's a *dynamic* limit, so leave the system some headroom. And it **does persist** — `--set` writes `/etc/modprobe.d/ttm.conf` and needs one reboot; you do **not** have to re-run it every boot (that was the old runtime-only behavior). Already have the tool? Update it with `uv tool upgrade amd-debug-tools`.
- **I dropped `--high-ram` and `--disable-mmap` from the launch line.** On unified memory they keep weights in un-evictable/anonymous RAM instead of letting the kernel hold them file-backed, which caused zram thrash under load here. I kept `--use-pytorch-cross-attention` (the AOTriton speedup). `--disable-mmap` can still help cold-load speed if your models sit on a compressed btrfs subvol and you have RAM headroom — measure it for your setup.

Full script + readme (requirements include **kitty**, for the optional desktop launcher) are in the gist.

**Comment by DasPauluteli** [comment]
> Hi, I made yet another `comfyui-gfx-1151` repo, hopefully the solution in it works at least for a couple of months 🥲
> 
> https://github.com/IgnatBeresnev/comfyui-gfx1151
> 
> I described the reasons why and how it works in detail in the README. Long story short, a lot of information from above seems to be outdated, and the image and wheels from [pccr10001/comfyui-gfx1151-fa](https://github.com/pccr10001/comfyui-gfx1151-fa) don't seem to work anymore. Thankfully, if you take the official pytorch docker image published recently by AMD, you can get ComfyUI up and running with flash-attention (well, triton) in a jiffy, without installing any custom-built wheels.

I recommend **not** using ComfyUi forks. These are often outdated or cannot be updated. Instead, [my script](https://gist.github.com/DasPauluteli/78748b6df5a1bc876b649286d8bc04f6l) installs ComfyUi and the latest [ROCm-PyTorch builds](https://github.com/ROCm/TheRock/blob/main/external-builds/pytorch/README.md), updates them both automatically, and takes care of the optimal flags and other settings for you. Just follow the installation instructions once, and you’ll be all set - even for the future.
