### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ameen-roayan** [comfyanonymous/ComfyUI#8431]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Hello 
Issue keeps happening after every comfy update using the .bat file in the installation folder. 

### Actual Behavior

trying to launch comfyui and i get stopped everytime. 

### Steps to Reproduce

Just launch it 

### Debug Logs

```powershell
I:\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen --enable-cors-header --fast
Adding extra search path checkpoints F:\AI\Automatic1111\stable-diffusion-webui\models\Stable-diffusion
Adding extra search path configs F:\AI\Automatic1111\stable-diffusion-webui\models\Stable-diffusion
Adding extra search path vae F:\AI\Automatic1111\stable-diffusion-webui\models\VAE
Adding extra search path loras F:\AI\Automatic1111\stable-diffusion-webui\models\Lora
Adding extra search path loras F:\AI\Automatic1111\stable-diffusion-webui\models\LyCORIS
Adding extra search path upscale_models F:\AI\Automatic1111\stable-diffusion-webui\models\ESRGAN
Adding extra search path upscale_models F:\AI\Automatic1111\stable-diffusion-webui\models\RealESRGAN
Adding extra search path upscale_models F:\AI\Automatic1111\stable-diffusion-webui\models\SwinIR
Adding extra search path embeddings F:\AI\Automatic1111\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks F:\AI\Automatic1111\stable-diffusion-webui\models\hypernetworks
Adding extra search path controlnet F:\AI\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\models
Adding extra search path instantid I:\ComfyUI\models\instantid
Adding extra search path ipadapter I:\ComfyUI\models\ipadapter
Adding extra search path Models I:\ComfyUI\models
Adding extra search path checkpoints I:\ComfyUI\ComfyUI\models\checkpoints
Adding extra search path clip I:\ComfyUI\ComfyUI\models\clip
Adding extra search path clip_interrogator I:\ComfyUI\ComfyUI\models\clip_interrogator
Adding extra search path clip_vision I:\ComfyUI\ComfyUI\models\clip_vision
Adding extra search path clipseg I:\ComfyUI\ComfyUI\models\clipseg
Adding extra search path configs I:\ComfyUI\ComfyUI\models\configs
Adding extra search path controlnet I:\ComfyUI\ComfyUI\models\controlnet
Adding extra search path diffusers I:\ComfyUI\ComfyUI\models\diffusers
Adding extra search path diffusion_models I:\ComfyUI\ComfyUI\models\diffusion_models
Adding extra search path Dlib I:\ComfyUI\ComfyUI\models\Dlib
Adding extra search path dz_facedetailer I:\ComfyUI\ComfyUI\models\dz_facedetailer
Adding extra search path embeddings I:\ComfyUI\ComfyUI\models\embeddings
Adding extra search path face_restore I:\ComfyUI\ComfyUI\models\face_restore
Adding extra search path facedetection I:\ComfyUI\ComfyUI\models\facedetection
Adding extra search path facerestore_models I:\ComfyUI\ComfyUI\models\facerestore_models
Adding extra search path florence2 I:\ComfyUI\ComfyUI\models\florence2
Adding extra search path gligen I:\ComfyUI\ComfyUI\models\gligen
Adding extra search path grounding-dino I:\ComfyUI\ComfyUI\models\grounding-dino
Adding extra search path hypernetworks I:\ComfyUI\ComfyUI\models\hypernetworks
Adding extra search path insightface I:\ComfyUI\ComfyUI\models\insightface
Adding extra search path instantid I:\ComfyUI\ComfyUI\models\instantid
Adding extra search path ipadapter I:\ComfyUI\ComfyUI\models\ipadapter
Adding extra search path lama I:\ComfyUI\ComfyUI\models\lama
Adding extra search path liveportrait I:\ComfyUI\ComfyUI\models\liveportrait
Adding extra search path LLavacheckpoints I:\ComfyUI\ComfyUI\models\LLavacheckpoints
Adding extra search path LLM I:\ComfyUI\ComfyUI\models\LLM
Adding extra search path loras I:\ComfyUI\ComfyUI\models\loras
Adding extra search path mediapipe I:\ComfyUI\ComfyUI\models\mediapipe
Adding extra search path mmdets I:\ComfyUI\ComfyUI\models\mmdets
Adding extra search path onnx I:\ComfyUI\ComfyUI\models\onnx
Adding extra search path photomaker I:\ComfyUI\ComfyUI\models\photomaker
Adding extra search path prompt_generator I:\ComfyUI\ComfyUI\models\prompt_generator
Adding extra search path pulid I:\ComfyUI\ComfyUI\models\pulid
Adding extra search path reactor I:\ComfyUI\ComfyUI\models\reactor
Adding extra search path rembg I:\ComfyUI\ComfyUI\models\rembg
Adding extra search path sams I:\ComfyUI\ComfyUI\models\sams
Adding extra search path style_models I:\ComfyUI\ComfyUI\models\style_models
Adding extra search path svd I:\ComfyUI\ComfyUI\models\svd
Adding extra search path t5 I:\ComfyUI\ComfyUI\models\t5
Adding extra search path text_encoders I:\ComfyUI\ComfyUI\models\text_encoders
Adding extra search path ultralytics I:\ComfyUI\ComfyUI\models\ultralytics
Adding extra search path unet I:\ComfyUI\ComfyUI\models\unet
Adding extra search path upscale_models I:\ComfyUI\ComfyUI\models\upscale_models
Adding extra search path vae I:\ComfyUI\ComfyUI\models\vae
Adding extra search path vae_approx I:\ComfyUI\ComfyUI\models\vae_approx
Adding extra search path xlabs I:\ComfyUI\ComfyUI\models\xlabs
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-06-05 17:47:02.883400
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: I:\ComfyUI\python_embeded\python.exe
** ComfyUI Path: I:\ComfyUI\ComfyUI
** Log path: I:\ComfyUI\ComfyUI\user\comfyui.log
  WARNING: The script f2py.exe is installed in 'I:\ComfyUI\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 1.4.17 requires scikit-image>=0.21.0, but you have scikit-image 0.20.0 which is incompatible.
blendmodes 2023 requires Pillow<11,>=10.0.0, but you have pillow 11.2.1 which is incompatible.
datasets 2.19.1 requires fsspec[http]<=2024.3.1,>=2023.1.0, but you have fsspec 2024.6.1 which is incompatible.
faster-whisper 1.0.3 requires av<13,>=11.0, but you have av 14.4.0 which is incompatible.
image-reward 1.5 requires timm==0.6.13, but you have timm 1.0.11 which is incompatible.
inference-cli 0.22.2 requires opencv-python<=4.10.0.84,>=4.8.1.78, but you have opencv-python 4.11.0.86 which is incompatible.
inference-cli 0.22.2 requires requests<=2.31.0, but you have requests 2.32.3 which is incompatible.
inference-cli 0.22.2 requires rich<=13.5.2, but you have rich 13.9.4 which is incompatible.
inference-gpu 0.22.2 requires anthropic~=0.34.2, but you have anthropic 0.30.1 which is incompatible.
inference-gpu 0.22.2 requires onnxruntime-gpu~=1.15.1, but you have onnxruntime-gpu 1.20.1 which is incompatible.
inference-gpu 0.22.2 requires opencv-python<=4.10.0.84,>=4.8.1.78, but you have opencv-python 4.11.0.86 which is incompatible.
inference-gpu 0.22.2 requires pillow<11.0, but you have pillow 11.2.1 which is incompatible.
inference-gpu 0.22.2 requires requests<=2.31.0, but you have requests 2.32.3 which is incompatible.
inference-gpu 0.22.2 requires rich<=13.5.2, but you have rich 13.9.4 which is incompatible.
inference-gpu 0.22.2 requires setuptools<=72.1.0,>=70.0.0, but you have setuptools 80.3.1 which is incompatible.
ltx-video 0.1.2 requires huggingface-hub~=0.25.2, but you have huggingface-hub 0.30.2 which is incompatible.
mediapipe 0.10.9 requires protobuf<4,>=3.11, but you have protobuf 4.25.2 which is incompatible.
sensevoice-onnx 1.1.0 requires setuptools<=65.0, but you have setuptools 80.3.1 which is incompatible.
simple-lama-inpainting 0.1.2 requires pillow<10.0.0,>=9.5.0, but you have pillow 11.2.1 which is incompatible.
torchscale 0.3.0 requires fairscale==0.4.0, but you have fairscale 0.4.13 which is incompatible.
torchscale 0.3.0 requires timm==0.6.13, but you have timm 1.0.11 which is incompatible.
xformers 0.0.30 requires torch==2.7.0, but you have torch 2.7.1 which is incompatible.

Prestartup times for custom nodes:
   0.0 seconds: I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: I:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   8.3 seconds: I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "I:\ComfyUI\ComfyUI\main.py", line 130, in <module>
    import execution
  File "I:\ComfyUI\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "I:\ComfyUI\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "I:\ComfyUI\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "I:\ComfyUI\ComfyUI\comfy\sd.py", line 7, in <module>
    from comfy import model_management
  File "I:\ComfyUI\ComfyUI\comfy\model_management.py", line 221, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "I:\ComfyUI\ComfyUI\comfy\model_management.py", line 172, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ComfyUI\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
  File "I:\ComfyUI\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 363, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I:\ComfyUI>pause
Press any key to continue . . .
```

**Comment by baiyan0817** [comment]
**My question is the same**

**Specific operations**
1.After git pull
2.pip install -r requirements.txt --upgrade
3.Report an error directly.

**Code Showcase**
Launching ComfyUI using explicit path...
Adding extra search path checkpoints E:\AI\stable-diffusion-webui\models\Stable-diffusion
Adding extra search path configs E:\AI\stable-diffusion-webui\models\Stable-diffusion
Adding extra search path vae E:\AI\stable-diffusion-webui\models\VAE
Adding extra search path loras E:\AI\stable-diffusion-webui\models\Lora
Adding extra search path loras E:\AI\stable-diffusion-webui\models\LyCORIS
Adding extra search path upscale_models E:\AI\stable-diffusion-webui\models\ESRGAN
Adding extra search path upscale_models E:\AI\stable-diffusion-webui\models\RealESRGAN
Adding extra search path upscale_models E:\AI\stable-diffusion-webui\models\SwinIR
Adding extra search path embeddings E:\AI\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks E:\AI\stable-diffusion-webui\models\hypernetworks
Adding extra search path controlnet E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\models
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-06-06 11:20:22.493
** Platform: Windows
** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
** Python executable: E:\AI\ComfyUI_windows\ComfyUI\comfyuipy-312\Scripts\python.exe
** ComfyUI Path: E:\AI\ComfyUI_windows\ComfyUI
** ComfyUI Base Folder Path: E:\AI\ComfyUI_windows\ComfyUI
** User directory: E:\AI\ComfyUI_windows\ComfyUI\user
** ComfyUI-Manager config path: E:\AI\ComfyUI_windows\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: E:\AI\ComfyUI_windows\ComfyUI\user\comfyui.log
[ComfyUI-Manager] 'numpy' dependency were fixed

Prestartup times for custom nodes:
  10.5 seconds: E:\AI\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows\ComfyUI\main.py", line 130, in <module>
    import execution
  File "E:\AI\ComfyUI_windows\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "E:\AI\ComfyUI_windows\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "E:\AI\ComfyUI_windows\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "E:\AI\ComfyUI_windows\ComfyUI\comfy\sd.py", line 7, in <module>
    from comfy import model_management
  File "E:\AI\ComfyUI_windows\ComfyUI\comfy\model_management.py", line 221, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows\ComfyUI\comfy\model_management.py", line 172, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows\ComfyUI\comfyuipy-312\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
  File "E:\AI\ComfyUI_windows\ComfyUI\comfyuipy-312\Lib\site-packages\torch\cuda\__init__.py", line 363, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Script finished. Press any key to close window.
请按任意键继续. . .

**Comment by baiyan0817** [comment]
I solved this problem

**Specific operations**
Troubleshooting
get the "Torch not compiled with CUDA enabled" error, uninstall torch with:
pip uninstall torch
And install it again with the command above.

Nvidia users should install stable pytorch using this command:
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu128

**Comment by GGGO87** [comment]
Same issue here, above solution not working

**Comment by TheChildishMillennial** [comment]
The fix to this issue is to run:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Replace whatever your CUDA version is (cu118, cu128, etc.).
This command is what pytorch.org says to use instead of --extra-index-url.
