### ISSUE TITLE
Flux Kontext comic example worked but basic example did not

### ISSUE THREAD

**Issue by Lastofthefirst** [comfyanonymous/ComfyUI#8687]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

 I was able to successfully use the flux comic example that made  of the anime fenik ear character but when I tried the basic example I ran out of memory and got the following error. What could be possible causes for OOM on the simpler workflow?

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 13
- **Node Type:** SamplerCustomAdvanced
- **Exception Type:** torch.cuda.OutOfMemoryError
- **Exception Message:** Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.45 GiB
Requested               : 192.00 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 10.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
This error means you ran out of memory on your GPU.

TIPS: If the workflow worked before you might have accidentally set the batch_size to a large number.
## Stack Trace

  File "[Home directory]/sd/ComfyUI/execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "[Home directory]/sd/ComfyUI/execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "[Home directory]/sd/ComfyUI/execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)

  File "[Home directory]/sd/ComfyUI/execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "[Home directory]/sd/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 707, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 1014, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 982, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 965, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 114, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 744, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/k_diffusion/sampling.py", line 189, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 396, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 945, in __call__
    return self.predict_noise(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 948, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)

  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 189, in sampling_function
    out = orig_fn(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 376, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)

  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)

  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 152, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(

  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 190, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 242, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options, attn_mask=kwargs.get("attention_mask", None))

  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 149, in forward_orig
    img, txt = block(img=img,

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)

  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/layers.py", line 199, in forward
    img = img + apply_mod(self.img_mlp(apply_mod(self.img_norm2(img), (1 + img_mod2.scale), img_mod2.shift, modulation_dims_img)), img_mod2.gate, None, modulation_dims_img)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)

  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 682, in forward
    return F.gelu(input, approximate=self.approximate)


## System Information
- **ComfyUI Version:** 0.3.42
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.2.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25438126080
  - **VRAM Free:** 24707530668
  - **Torch VRAM Total:** 67108864
  - **Torch VRAM Free:** 33554348

## Logs

2025-06-26T19:49:28.376257 - 
2025-06-26T19:49:28.376810 - [Impact Pack] Wildcards loading done.2025-06-26T19:49:28.376908 - 
2025-06-26T19:49:28.596878 - [34m[ComfyUI-Easy-Use] server: [0mv1.3.0 [92mLoaded[0m2025-06-26T19:49:28.596900 - 
2025-06-26T19:49:28.596911 - [34m[ComfyUI-Easy-Use] web root: [0m[Home directory]/sd/ComfyUI/custom_nodes/comfyui-easy-use/web_version/v2 [92mLoaded[0m2025-06-26T19:49:28.596920 - 
2025-06-26T19:49:28.618806 - [Crystools [0;32mINFO[0m] Crystools version: 1.25.1
2025-06-26T19:49:28.626268 - [Crystools [0;32mINFO[0m] Platform release: 6.1.0-37-amd64
2025-06-26T19:49:28.626327 - [Crystools [0;32mINFO[0m] JETSON: Not detected.
2025-06-26T19:49:28.628389 - [Crystools [0;32mINFO[0m] CPU: AMD Ryzen 9 7900X 12-Core Processor - Arch: x86_64 - OS: Linux 6.1.0-37-amd64


...


2025-06-26T19:50:38.084939 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/node_db/new/custom-node-list.json2025-06-26T19:50:38.084960 - 2025-06-26T19:50:38.332121 -  [DONE]2025-06-26T19:50:38.332160 - 
2025-06-26T19:50:38.333567 - [ComfyUI-Manager] All startup tasks have been completed.
2025-06-26T20:31:24.212240 - got prompt
2025-06-26T20:31:24.384972 - Using pytorch attention in VAE
2025-06-26T20:31:24.386271 - Using pytorch attention in VAE
2025-06-26T20:31:25.326869 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-06-26T20:31:25.978185 - [Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

2025-06-26T20:31:26.033059 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-06-26T20:31:26.701470 - clip missing: ['text_projection.weight']
2025-06-26T20:31:53.203712 - Requested to load FluxClipModel_
2025-06-26T20:31:53.859217 - loaded completely 22513.7375 9319.23095703125 True
2025-06-26T20:31:54.380009 - Requested to load AutoencodingEngine
2025-06-26T20:31:54.405598 - loaded completely 10351.706535339355 159.87335777282715 True
2025-06-26T20:31:55.158833 - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2025-06-26T20:31:55.169560 - model_type FLUX
2025-06-26T20:32:01.078416 - Requested to load Flux
2025-06-26T20:32:01.952700 - loaded completely 13410.058412261962 11350.067443847656 True
2025-06-26T20:32:51.495395 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:49<00:00,  2.54s/it]2025-06-26T20:32:51.495508 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:49<00:00,  2.48s/it]2025-06-26T20:32:51.495521 - 
2025-06-26T20:32:52.521733 - Requested to load AutoencodingEngine
2025-06-26T20:32:52.798113 - loaded completely 189.4568214416504 159.87335777282715 True
2025-06-26T20:32:53.347736 - loaded completely 10833.758471298217 9319.23095703125 True
2025-06-26T20:33:43.840297 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:50<00:00,  2.58s/it]2025-06-26T20:33:43.840403 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:50<00:00,  2.52s/it]2025-06-26T20:33:43.840416 - 
2025-06-26T20:33:45.661794 - loaded completely 10833.758471298217 9319.23095703125 True
2025-06-26T20:34:36.531675 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:50<00:00,  2.60s/it]2025-06-26T20:34:36.531776 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:50<00:00,  2.54s/it]2025-06-26T20:34:36.531790 - 
2025-06-26T20:34:38.384146 - loaded completely 10833.758471298217 9319.23095703125 True
2025-06-26T20:35:29.793196 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:51<00:00,  2.62s/it]2025-06-26T20:35:29.793300 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:51<00:00,  2.56s/it]2025-06-26T20:35:29.793314 - 
2025-06-26T20:35:31.641028 - loaded completely 10833.758471298217 9319.23095703125 True
2025-06-26T20:36:23.409049 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:51<00:00,  2.64s/it]2025-06-26T20:36:23.409583 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:51<00:00,  2.58s/it]2025-06-26T20:36:23.409606 - 
2025-06-26T20:36:25.276254 - loaded completely 10833.758471298217 9319.23095703125 True
2025-06-26T20:37:17.337372 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:51<00:00,  2.66s/it]2025-06-26T20:37:17.337488 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:51<00:00,  2.59s/it]2025-06-26T20:37:17.337504 - 
2025-06-26T20:37:19.199207 - loaded completely 10833.758471298217 9319.23095703125 True
2025-06-26T20:38:11.451039 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:52<00:00,  2.66s/it]2025-06-26T20:38:11.451156 - 
100%|███████████████████████████████████████████████████████████████| 20/20 [00:52<00:00,  2.60s/it]2025-06-26T20:38:11.451169 - 
2025-06-26T20:38:14.165076 - Prompt executed in 409.95 seconds
2025-06-26T20:40:33.001491 - got prompt
2025-06-26T20:40:33.061977 - model weight dtype torch.bfloat16, manual cast: None
2025-06-26T20:40:33.062219 - model_type FLUX
2025-06-26T20:40:39.562963 - [Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

2025-06-26T20:40:39.595589 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-06-26T20:40:51.976027 - clip missing: ['text_projection.weight']
2025-06-26T20:40:52.320817 - Requested to load FluxClipModel_
2025-06-26T20:40:53.414773 - loaded completely 22183.86406211853 9319.23095703125 True
2025-06-26T20:40:53.697762 - Requested to load Flux
2025-06-26T20:40:58.103002 - loaded partially 22245.433419891357 22245.107421875 0
2025-06-26T20:40:58.124155 - 
  0%|                                                                        | 0/20 [00:00<?, ?it/s]2025-06-26T20:40:58.765000 - 
  0%|                                                                        | 0/20 [00:00<?, ?it/s]2025-06-26T20:40:58.765048 - 
2025-06-26T20:40:58.826258 - !!! Exception during processing !!! Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.45 GiB
Requested               : 192.00 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 10.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
2025-06-26T20:40:58.897527 - Traceback (most recent call last):
  File "[Home directory]/sd/ComfyUI/execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "[Home directory]/sd/ComfyUI/execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "[Home directory]/sd/ComfyUI/execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "[Home directory]/sd/ComfyUI/execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "[Home directory]/sd/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 707, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 1014, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 982, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 965, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 114, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 744, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/k_diffusion/sampling.py", line 189, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 396, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 945, in __call__
    return self.predict_noise(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 948, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 189, in sampling_function
    out = orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 376, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 152, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 190, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 242, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options, attn_mask=kwargs.get("attention_mask", None))
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 149, in forward_orig
    img, txt = block(img=img,
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/layers.py", line 199, in forward
    img = img + apply_mod(self.img_mlp(apply_mod(self.img_norm2(img), (1 + img_mod2.scale), img_mod2.shift, modulation_dims_img)), img_mod2.gate, None, modulation_dims_img)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 682, in forward
    return F.gelu(input, approximate=self.approximate)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.45 GiB
Requested               : 192.00 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 10.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

2025-06-26T20:40:58.897647 - Got an OOM, unloading all loaded models.
2025-06-26T20:41:02.793563 - Prompt executed in 29.79 seconds
2025-06-26T20:41:20.781857 - got prompt
2025-06-26T20:41:20.827229 - Requested to load Flux
2025-06-26T20:41:22.526890 - loaded partially 22245.433419891357 22245.107421875 0
2025-06-26T20:41:22.528054 - 
  0%|                                                                        | 0/20 [00:00<?, ?it/s]2025-06-26T20:41:22.705638 - 
  0%|                                                                        | 0/20 [00:00<?, ?it/s]2025-06-26T20:41:22.705663 - 
2025-06-26T20:41:22.706509 - !!! Exception during processing !!! Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.45 GiB
Requested               : 192.00 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 10.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
2025-06-26T20:41:22.706770 - Traceback (most recent call last):
  File "[Home directory]/sd/ComfyUI/execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "[Home directory]/sd/ComfyUI/execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "[Home directory]/sd/ComfyUI/execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "[Home directory]/sd/ComfyUI/execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "[Home directory]/sd/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 707, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 1014, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 982, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 965, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 114, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 744, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/k_diffusion/sampling.py", line 189, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 396, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 945, in __call__
    return self.predict_noise(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 948, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 189, in sampling_function
    out = orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 376, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 152, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 190, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 242, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options, attn_mask=kwargs.get("attention_mask", None))
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 149, in forward_orig
    img, txt = block(img=img,
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/layers.py", line 199, in forward
    img = img + apply_mod(self.img_mlp(apply_mod(self.img_norm2(img), (1 + img_mod2.scale), img_mod2.shift, modulation_dims_img)), img_mod2.gate, None, modulation_dims_img)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 682, in forward
    return F.gelu(input, approximate=self.approximate)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.45 GiB
Requested               : 192.00 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 10.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

2025-06-26T20:41:22.706835 - Got an OOM, unloading all loaded models.
2025-06-26T20:41:26.448674 - Prompt executed in 5.64 seconds
2025-06-26T20:41:43.804363 - got prompt
2025-06-26T20:41:43.813743 - Requested to load Flux
2025-06-26T20:41:45.404814 - loaded partially 22245.433419891357 22245.107421875 0
2025-06-26T20:41:45.405978 - 
  0%|                                                                        | 0/20 [00:00<?, ?it/s]2025-06-26T20:41:45.583528 - 
  0%|                                                                        | 0/20 [00:00<?, ?it/s]2025-06-26T20:41:45.583554 - 
2025-06-26T20:41:45.584423 - !!! Exception during processing !!! Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.45 GiB
Requested               : 192.00 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 10.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
2025-06-26T20:41:45.584685 - Traceback (most recent call last):
  File "[Home directory]/sd/ComfyUI/execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "[Home directory]/sd/ComfyUI/execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "[Home directory]/sd/ComfyUI/execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "[Home directory]/sd/ComfyUI/execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "[Home directory]/sd/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 707, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 1014, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 982, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 965, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 114, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 744, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/k_diffusion/sampling.py", line 189, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 396, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 945, in __call__
    return self.predict_noise(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 948, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "[Home directory]/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 189, in sampling_function
    out = orig_fn(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 376, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 152, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "[Home directory]/sd/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/model_base.py", line 190, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 242, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options, attn_mask=kwargs.get("attention_mask", None))
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/model.py", line 149, in forward_orig
    img, txt = block(img=img,
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/sd/ComfyUI/comfy/ldm/flux/layers.py", line 199, in forward
    img = img + apply_mod(self.img_mlp(apply_mod(self.img_norm2(img), (1 + img_mod2.scale), img_mod2.shift, modulation_dims_img)), img_mod2.gate, None, modulation_dims_img)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "[Home directory]/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 682, in forward
    return F.gelu(input, approximate=self.approximate)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.45 GiB
Requested               : 192.00 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 10.94 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

2025-06-26T20:41:45.584758 - Got an OOM, unloading all loaded models.
2025-06-26T20:41:49.196672 - Prompt executed in 5.39 seconds


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"id":"ad18abd3-bdee-4f80-8fae-d15d4f845b9d","revision":0,"last_node_id":58,"last_link_id":158,"nodes":[{"id":11,"type":"DualCLIPLoader","pos":[48,288],"size":[315,130],"flags":{},"order":0,"mode":0,"inputs":[{"localized_name":"clip_name1","name":"clip_name1","type":"COMBO","widget":{"name":"clip_name1"},"link":null},{"localized_name":"clip_name2","name":"clip_name2","type":"COMBO","widget":{"name":"clip_name2"},"link":null},{"localized_name":"type","name":"type","type":"COMBO","widget":{"name":"type"},"link":null},{"localized_name":"device","name":"device","shape":7,"type":"COMBO","widget":{"name":"device"},"link":null}],"outputs":[{"localized_name":"CLIP","name":"CLIP","type":"CLIP","slot_index":0,"links":[10]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"DualCLIPLoader","widget_ue_connectable":{}},"widgets_values":["t5xxl_fp16.safetensors","clip_l.safetensors","flux","default"]},{"id":17,"type":"BasicScheduler","pos":[480,1008],"size":[315,106],"flags":{},"order":16,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":55},{"localized_name":"scheduler","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"steps","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"denoise","name":"denoise","type":"FLOAT","widget":{"name":"denoise"},"link":null}],"outputs":[{"localized_name":"SIGMAS","name":"SIGMAS","type":"SIGMAS","links":[20]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"BasicScheduler","widget_ue_connectable":{}},"widgets_values":["simple",20,1]},{"id":16,"type":"KSamplerSelect","pos":[480,912],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[{"localized_name":"sampler_name","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null}],"outputs":[{"localized_name":"SAMPLER","name":"SAMPLER","type":"SAMPLER","links":[19]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"KSamplerSelect","widget_ue_connectable":{}},"widgets_values":["euler"]},{"id":8,"type":"VAEDecode","pos":[866,367],"size":[210,46],"flags":{},"order":21,"mode":0,"inputs":[{"localized_name":"samples","name":"samples","type":"LATENT","link":24},{"localized_name":"vae","name":"vae","type":"VAE","link":12}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","slot_index":0,"links":[9]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"VAEDecode","widget_ue_connectable":{}},"widgets_values":[]},{"id":30,"type":"ModelSamplingFlux","pos":[480,1152],"size":[315,130],"flags":{},"order":13,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":56},{"localized_name":"max_shift","name":"max_shift","type":"FLOAT","widget":{"name":"max_shift"},"link":null},{"localized_name":"base_shift","name":"base_shift","type":"FLOAT","widget":{"name":"base_shift"},"link":null},{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":115},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":114}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[54,55]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"ModelSamplingFlux","widget_ue_connectable":{"width":true,"height":true}},"widgets_values":[1.15,0.5,1024,1024]},{"id":27,"type":"EmptySD3LatentImage","pos":[480,624],"size":[315,106],"flags":{},"order":11,"mode":0,"inputs":[{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":112},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":113},{"localized_name":"batch_size","name":"batch_size","type":"INT","widget":{"name":"batch_size"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[116]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"EmptySD3LatentImage","widget_ue_connectable":{"width":true,"height":true}},"widgets_values":[1024,1024,1]},{"id":34,"type":"PrimitiveNode","pos":[432,480],"size":[210,82],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"INT","type":"INT","widget":{"name":"width"},"slot_index":0,"links":[112,115]}],"title":"width","properties":{"Run widget replace on values":false,"widget_ue_connectable":{}},"widgets_values":[1024,"fixed"],"color":"#323","bgcolor":"#535"},{"id":35,"type":"PrimitiveNode","pos":[672,480],"size":[210,82],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"INT","type":"INT","widget":{"name":"height"},"slot_index":0,"links":[113,114]}],"title":"height","properties":{"Run widget replace on values":false,"widget_ue_connectable":{}},"widgets_values":[1024,"fixed"],"color":"#323","bgcolor":"#535"},{"id":9,"type":"SaveImage","pos":[1155,196],"size":[985.3012084960938,1060.3828125],"flags":{},"order":22,"mode":0,"inputs":[{"localized_name":"images","name":"images","type":"IMAGE","link":9},{"localized_name":"filename_prefix","name":"filename_prefix","type":"STRING","widget":{"name":"filename_prefix"},"link":null}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"SaveImage","widget_ue_connectable":{}},"widgets_values":["ComfyUI"]},{"id":37,"type":"Note","pos":[480,1344],"size":[314.99755859375,117.98363494873047],"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[],"properties":{"text":"","widget_ue_connectable":{}},"widgets_values":["The reference sampling implementation auto adjusts the shift value based on the resolution, if you don't want this you can just bypass (CTRL-B) this ModelSamplingFlux node.\n"],"color":"#432","bgcolor":"#653"},{"id":26,"type":"FluxGuidance","pos":[480,144],"size":[317.4000244140625,58],"flags":{},"order":14,"mode":0,"inputs":[{"localized_name":"conditioning","name":"conditioning","type":"CONDITIONING","link":41},{"localized_name":"guidance","name":"guidance","type":"FLOAT","widget":{"name":"guidance"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[123]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"FluxGuidance","widget_ue_connectable":{}},"widgets_values":[2.5],"color":"#233","bgcolor":"#355"},{"id":13,"type":"SamplerCustomAdvanced","pos":[864,192],"size":[272.3617858886719,124.53733825683594],"flags":{},"order":20,"mode":0,"inputs":[{"localized_name":"noise","name":"noise","type":"NOISE","link":37},{"localized_name":"guider","name":"guider","type":"GUIDER","link":30},{"localized_name":"sampler","name":"sampler","type":"SAMPLER","link":19},{"localized_name":"sigmas","name":"sigmas","type":"SIGMAS","link":20},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":116}],"outputs":[{"localized_name":"output","name":"output","type":"LATENT","slot_index":0,"links":[24]},{"localized_name":"denoised_output","name":"denoised_output","type":"LATENT","links":null}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"SamplerCustomAdvanced","widget_ue_connectable":{}},"widgets_values":[]},{"id":39,"type":"VAEEncode","pos":[501.1323547363281,-12.391702651977539],"size":[140,46],"flags":{},"order":17,"mode":0,"inputs":[{"localized_name":"pixels","name":"pixels","type":"IMAGE","link":143},{"localized_name":"vae","name":"vae","type":"VAE","link":120}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","links":[138]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"VAEEncode","widget_ue_connectable":{}},"widgets_values":[]},{"id":42,"type":"ReferenceLatent","pos":[676.4634399414062,-28.66999626159668],"size":[197.712890625,46],"flags":{},"order":18,"mode":0,"inputs":[{"localized_name":"conditioning","name":"conditioning","type":"CONDITIONING","link":123},{"localized_name":"latent","name":"latent","shape":7,"type":"LATENT","link":138}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","links":[157]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"ReferenceLatent","widget_ue_connectable":{}},"widgets_values":[]},{"id":22,"type":"BasicGuider","pos":[887.5904541015625,60.72023010253906],"size":[222.3482666015625,46],"flags":{},"order":19,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":54},{"localized_name":"conditioning","name":"conditioning","type":"CONDITIONING","link":157}],"outputs":[{"localized_name":"GUIDER","name":"GUIDER","type":"GUIDER","slot_index":0,"links":[30]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"BasicGuider","widget_ue_connectable":{}},"widgets_values":[]},{"id":53,"type":"ImageScaleBy","pos":[249.71116638183594,-83.57847595214844],"size":[210,82],"flags":{},"order":15,"mode":4,"inputs":[{"localized_name":"image","name":"image","type":"IMAGE","link":142},{"localized_name":"upscale_method","name":"upscale_method","type":"COMBO","widget":{"name":"upscale_method"},"link":null},{"localized_name":"scale_by","name":"scale_by","type":"FLOAT","widget":{"name":"scale_by"},"link":null}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","links":[143]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"ImageScaleBy","widget_ue_connectable":{}},"widgets_values":["area",0.5000000000000001]},{"id":40,"type":"FluxKontextImageScale","pos":[43.59303665161133,-83.14352416992188],"size":[187.75448608398438,26],"flags":{},"order":12,"mode":0,"inputs":[{"localized_name":"image","name":"image","type":"IMAGE","link":158}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","links":[142]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"FluxKontextImageScale","widget_ue_connectable":{}},"widgets_values":[]},{"id":25,"type":"RandomNoise","pos":[480,768],"size":[315,82],"flags":{},"order":5,"mode":0,"inputs":[{"localized_name":"noise_seed","name":"noise_seed","type":"INT","widget":{"name":"noise_seed"},"link":null}],"outputs":[{"localized_name":"NOISE","name":"NOISE","type":"NOISE","links":[37]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"RandomNoise","widget_ue_connectable":{}},"widgets_values":[474359024420739,"randomize"],"color":"#2a363b","bgcolor":"#3f5159"},{"id":28,"type":"Note","pos":[48,576],"size":[336,288],"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[],"properties":{"text":"","widget_ue_connectable":{}},"widgets_values":["If you get an error in any of the nodes above make sure the files are in the correct directories.\n\nSee the examples page for the links : https://comfyanonymous.github.io/ComfyUI_examples/flux/\n\nflux1-kontext-dev.safetensors goes in: ComfyUI/models/unet/\n\nt5xxl_fp16.safetensors and clip_l.safetensors go in: ComfyUI/models/clip/\n\nae.safetensors goes in: ComfyUI/models/vae/\n\n\nTip: You can set the weight_dtype above to one of the fp8 types if you have memory issues."],"color":"#432","bgcolor":"#653"},{"id":10,"type":"VAELoader","pos":[50.72727584838867,466.54541015625],"size":[311.81634521484375,60.429901123046875],"flags":{},"order":7,"mode":0,"inputs":[{"localized_name":"vae_name","name":"vae_name","type":"COMBO","widget":{"name":"vae_name"},"link":null}],"outputs":[{"localized_name":"VAE","name":"VAE","type":"VAE","slot_index":0,"links":[12,120]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"VAELoader","widget_ue_connectable":{}},"widgets_values":["flux/ae.safetensors"]},{"id":41,"type":"LoadImage","pos":[-274.419921875,-82.92684936523438],"size":[274.080078125,314],"flags":{},"order":8,"mode":0,"inputs":[{"localized_name":"image","name":"image","type":"COMBO","widget":{"name":"image"},"link":null},{"localized_name":"choose file to upload","name":"upload","type":"IMAGEUPLOAD","widget":{"name":"upload"},"link":null}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","links":[158]},{"localized_name":"MASK","name":"MASK","type":"MASK","links":null}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"LoadImage","widget_ue_connectable":{}},"widgets_values":["ComfyUI_02714_.png","image"]},{"id":12,"type":"UNETLoader","pos":[84.8408203125,93.45100402832031],"size":[315,82],"flags":{},"order":9,"mode":0,"inputs":[{"localized_name":"unet_name","name":"unet_name","type":"COMBO","widget":{"name":"unet_name"},"link":null},{"localized_name":"weight_dtype","name":"weight_dtype","type":"COMBO","widget":{"name":"weight_dtype"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[56]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"UNETLoader","widget_ue_connectable":{}},"widgets_values":["flux1-kontext-dev.safetensors","default"],"color":"#223","bgcolor":"#335"},{"id":6,"type":"CLIPTextEncode","pos":[384,240],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":10,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":10},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[41]}],"title":"CLIP Text Encode (Positive Prompt)","properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"CLIPTextEncode","widget_ue_connectable":{}},"widgets_values":[" turn the boat into a giant cello that is being used as a boat"],"color":"#232","bgcolor":"#353"}],"links":[[9,8,0,9,0,"IMAGE"],[10,11,0,6,0,"CLIP"],[12,10,0,8,1,"VAE"],[19,16,0,13,2,"SAMPLER"],[20,17,0,13,3,"SIGMAS"],[24,13,0,8,0,"LATENT"],[30,22,0,13,1,"GUIDER"],[37,25,0,13,0,"NOISE"],[41,6,0,26,0,"CONDITIONING"],[54,30,0,22,0,"MODEL"],[55,30,0,17,0,"MODEL"],[56,12,0,30,0,"MODEL"],[112,34,0,27,0,"INT"],[113,35,0,27,1,"INT"],[114,35,0,30,4,"INT"],[115,34,0,30,3,"INT"],[116,27,0,13,4,"LATENT"],[120,10,0,39,1,"VAE"],[123,26,0,42,0,"CONDITIONING"],[138,39,0,42,1,"LATENT"],[142,40,0,53,0,"IMAGE"],[143,53,0,39,0,"IMAGE"],[157,42,0,22,1,"CONDITIONING"],[158,41,0,40,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.167184107045001,"offset":[111.59981097565857,-157.33035603045667]},"frontendVersion":"1.21.7","groupNodes":{"EmptyLatentImage":{"nodes":[{"type":"PrimitiveNode","pos":[432,480],"size":{"0":210,"1":82},"flags":{},"order":6,"mode":0,"outputs":[{"name":"INT","type":"INT","links":[],"widget":{"name":"height"},"slot_index":0}],"title":"height","properties":{"Run widget replace on values":false},"color":"#323","bgcolor":"#535","index":0},{"type":"PrimitiveNode","pos":[672,480],"size":{"0":210,"1":82},"flags":{},"order":7,"mode":0,"outputs":[{"name":"INT","type":"INT","links":[],"slot_index":0,"widget":{"name":"width"}}],"title":"width","properties":{"Run widget replace on values":false},"color":"#323","bgcolor":"#535","index":1},{"type":"EmptySD3LatentImage","pos":[480,624],"size":{"0":315,"1":106},"flags":{},"order":10,"mode":0,"inputs":[{"name":"width","type":"INT","link":null,"widget":{"name":"width"}},{"name":"height","type":"INT","link":null,"widget":{"name":"height"}}],"outputs":[{"name":"LATENT","type":"LATENT","links":[],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"EmptySD3LatentImage"},"widgets_values":[1024,1024,1],"index":2}],"links":[[1,0,2,0,34,"INT"],[0,0,2,1,35,"INT"]],"external":[[0,0,"INT"],[1,0,"INT"],[2,0,"LATENT"]],"config":{"0":{"output":{"0":{"name":"height"}},"input":{"value":{"visible":true}}},"1":{"output":{"0":{"name":"width"}},"input":{"value":{"visible":true}}},"2":{"input":{"width":{"visible":false},"height":{"visible":false}}}}}},"ue_links":[],"links_added_by_ue":[]},"version":0.4}


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by robinjhuang** [comment]
<img width="386" alt="Image" src="https://github.com/user-attachments/assets/bf8bec2a-fdac-46a8-b8cd-773a2603f829" />

Probably because the comic one is loading in fp8

**Comment by Lastofthefirst** [comment]
Ah thanks, i thought fp8 was a separate version of the model that had to be downloaded independently.

**Comment by ssesweb** [comment]
Help! When I load a workflow, it says that FluxKontextImageScale and workflowEdit nodes are missing.

![Image](https://github.com/user-attachments/assets/e6217ecd-8e92-44d5-94fc-100732405e62)

**Comment by as-alt** [comment]
> Help! When I load a workflow, it says that FluxKontextImageScale and workflowEdit nodes are missing.
> 
> ![Image](https://github.com/user-attachments/assets/e6217ecd-8e92-44d5-94fc-100732405e62)

Updating your comfyui to the latest version can solve the problem

**Comment by Ewenftr** [comment]
> Help! When I load a workflow, it says that FluxKontextImageScale and workflowEdit nodes are missing.
> 
> ![Image](https://github.com/user-attachments/assets/e6217ecd-8e92-44d5-94fc-100732405e62)

In case updating Comfy still give you the "missing node" try searching for the nodes and adding them manually, their names should be in chinese but it seems to be the problem.

**Comment by aga7on** [comment]
Just updated Comfy still geting those errors. Just wondering, are there is any tool like showing tips where those nodes i can download and install it manually

**Comment by OchotaDariusz** [comment]
> Just updated Comfy still geting those errors. Just wondering, are there is any tool like showing tips where those nodes i can download and install it manually

If you are using portable windows version, then go to `update` folder and run `update_comfyui.bat` - this will update comfyui correctly.

**Comment by JoeWentLow** [comment]
I get this message when I try to update Comfyui with the  update_comfyui.bat file: 
_pygit2.GitError: Repository not found at ..\ComfyUI\

Any idea what is wrong?

**Comment by OchotaDariusz** [comment]
> I get this message when I try to update Comfyui with the update_comfyui.bat file: _pygit2.GitError: Repository not found at ..\ComfyUI\
> 
> Any idea what is wrong?

The fastest way to solve that will be to download the new portable version, copy models from your current one and then run update_comfyui.bat (don't forget to create new .bat file in portable comfyui folder and paste [that script](https://raw.githubusercontent.com/Comfy-Org/ComfyUI-Manager/main/scripts/install-manager-for-portable-version.bat) to install manager)

**Comment by snowyss** [comment]
<img width="1644" height="892" alt="Image" src="https://github.com/user-attachments/assets/b93e04a3-af3f-491c-9b25-b8745d03bcde" />

got prompt double_encode !!! Exception during processing !!! Allocation on device Traceback (most recent call last):   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\execution.py", line 496, in execute     output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\execution.py", line 315, in get_output_data     return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\execution.py", line 289, in _async_map_node_over_list     await process_inputs(input_dict, i)   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\execution.py", line 277, in process_inputs     result = f(**inputs)              ^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 932, in process     y = vae.encode([concatenated], device, end_=(end_image is not None and not fun_or_fl2v_model),tiled=tiled_vae)[0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\wan_video_vae.py", line 1315, in encode     hidden_state = self.double_encode(video, device, pbar=pbar, sample=sample)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\wan_video_vae.py", line 1296, in double_encode     x = self.model.encode_2(video, pbar=pbar, sample=sample)         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\wan_video_vae.py", line 991, in encode_2     out_ = self.encoder(x[:, :, 1 + 4 * (i - 1):1 + 4 * i, :, :],            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl     return self._call_impl(*args, **kwargs)

 File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl     return self._call_impl(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl     return forward_call(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\wan_video_vae.py", line 571, in forward     x = layer(x, feat_cache, feat_idx)         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl     return self._call_impl(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl     return forward_call(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\wan_video_vae.py", line 283, in forward     x = layer(x, feat_cache[idx])         ^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl     return self._call_impl(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl     return forward_call(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\wan_video_vae.py", line 37, in forward     x = F.pad(x, padding)         ^^^^^^^^^^^^^^^^^   File "D:\AI Studio\ComfyUI-aki-v2\python\Lib\site-packages\torch\nn\functional.py", line 5290, in pad     return torch._C._nn.pad(input, pad, mode, value)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ torch.OutOfMemoryError: Allocation on device  Got an OOM, unloading all loaded models. Prompt executed in 1.47 seconds

**Comment by hsnfx** [comment]
Hi , I solved the problem of missing FluxKontextImageScale 
you just need to delete the node in the whatever workflow you have and add it manually again
