### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

### ISSUE THREAD

**Issue by hotntwitchy** [comfyanonymous/ComfyUI#8708]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

I am running torch 128 and have a 5080 GPU. Running in Ubuntu. 

### Logs

```powershell

```

**Comment by hotntwitchy** [comment]
ComfyUI Error Report
## Error Details
- **Node ID:** 4
- **Node Type:** CLIPTextEncode
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


## Stack Trace
```
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^

  File "/home/hotntwitchy/comfy/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd.py", line 167, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd.py", line 229, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 683, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 288, in encode
    return self(tokens)

  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^

  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 250, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)

  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^

  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/ops.py", line 237, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^

  File "/home/hotntwitchy/comfy/ComfyUI/comfy/ops.py", line 233, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** 0.3.42
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.13.3 (main, Jun 16 2025, 18:15:32) [GCC 14.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.7.1+cu126
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 5080 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 16597319680
  - **VRAM Free:** 13290405372
  - **Torch VRAM Total:** 268435456
  - **Torch VRAM Free:** 21134844

## Logs
```
2025-06-27T15:33:31.553944 - [START] Security scan2025-06-27T15:33:31.553957 - 
2025-06-27T15:33:31.879657 - [DONE] Security scan2025-06-27T15:33:31.879669 - 
2025-06-27T15:33:31.900058 - ## ComfyUI-Manager: installing dependencies done.2025-06-27T15:33:31.900082 - 
2025-06-27T15:33:31.900095 - ** ComfyUI startup time:2025-06-27T15:33:31.900103 -  2025-06-27T15:33:31.900110 - 2025-06-27 15:33:31.9002025-06-27T15:33:31.900116 - 
2025-06-27T15:33:31.900125 - ** Platform:2025-06-27T15:33:31.900131 -  2025-06-27T15:33:31.900137 - Linux2025-06-27T15:33:31.900143 - 
2025-06-27T15:33:31.900150 - ** Python version:2025-06-27T15:33:31.900156 -  2025-06-27T15:33:31.900162 - 3.13.3 (main, Jun 16 2025, 18:15:32) [GCC 14.2.0]2025-06-27T15:33:31.900168 - 
2025-06-27T15:33:31.900174 - ** Python executable:2025-06-27T15:33:31.900180 -  2025-06-27T15:33:31.900186 - /home/hotntwitchy/comfy-env/bin/python32025-06-27T15:33:31.900192 - 
2025-06-27T15:33:31.900198 - ** ComfyUI Path:2025-06-27T15:33:31.900204 -  2025-06-27T15:33:31.900209 - /home/hotntwitchy/comfy/ComfyUI2025-06-27T15:33:31.900215 - 
2025-06-27T15:33:31.900224 - ** ComfyUI Base Folder Path:2025-06-27T15:33:31.900230 -  2025-06-27T15:33:31.900235 - /home/hotntwitchy/comfy/ComfyUI2025-06-27T15:33:31.900241 - 
2025-06-27T15:33:31.900247 - ** User directory:2025-06-27T15:33:31.900253 -  2025-06-27T15:33:31.900259 - /home/hotntwitchy/comfy/ComfyUI/user2025-06-27T15:33:31.900266 - 
2025-06-27T15:33:31.900273 - ** ComfyUI-Manager config path:2025-06-27T15:33:31.900279 -  2025-06-27T15:33:31.900285 - /home/hotntwitchy/comfy/ComfyUI/user/default/ComfyUI-Manager/config.ini2025-06-27T15:33:31.900291 - 
2025-06-27T15:33:31.900299 - ** Log path:2025-06-27T15:33:31.900304 -  2025-06-27T15:33:31.900310 - /home/hotntwitchy/comfy/ComfyUI/user/comfyui.log2025-06-27T15:33:31.900316 - 
2025-06-27T15:33:32.275016 - [ComfyUI-Manager] In Python 3.13 and above, PIP Fixer does not downgrade `numpy` below version 2.0. If you need to force a downgrade of `numpy`, please use `pip_auto_fix.list`.
2025-06-27T15:33:32.275203 - 
Prestartup times for custom nodes:
2025-06-27T15:33:32.275265 -    0.9 seconds: /home/hotntwitchy/comfy/ComfyUI/custom_nodes/ComfyUI-Manager
2025-06-27T15:33:32.275299 - 
2025-06-27T15:33:33.042736 - Checkpoint files will always be loaded safely.
2025-06-27T15:33:33.075445 - /home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
2025-06-27T15:33:33.181237 - Total VRAM 15828 MB, total RAM 62878 MB
2025-06-27T15:33:33.181304 - pytorch version: 2.7.1+cu126
2025-06-27T15:33:33.181456 - Set vram state to: NORMAL_VRAM
2025-06-27T15:33:33.181602 - Device: cuda:0 NVIDIA GeForce RTX 5080 : cudaMallocAsync
2025-06-27T15:33:33.708171 - Using pytorch attention
2025-06-27T15:33:34.440005 - Python version: 3.13.3 (main, Jun 16 2025, 18:15:32) [GCC 14.2.0]
2025-06-27T15:33:34.440112 - ComfyUI version: 0.3.42
2025-06-27T15:33:34.442103 - ComfyUI frontend version: 1.23.4
2025-06-27T15:33:34.442415 - [Prompt Server] web root: /home/hotntwitchy/comfy-env/lib/python3.13/site-packages/comfyui_frontend_package/static
2025-06-27T15:33:34.750769 - ### Loading: ComfyUI-Manager (V3.33.3)
2025-06-27T15:33:34.751106 - [ComfyUI-Manager] network_mode: public
2025-06-27T15:33:34.774852 - ### ComfyUI Version: v0.3.42-2-g9093301a | Released on '2025-06-27'
2025-06-27T15:33:34.783190 - 
Import times for custom nodes:
2025-06-27T15:33:34.783314 -    0.0 seconds: /home/hotntwitchy/comfy/ComfyUI/custom_nodes/websocket_image_save.py
2025-06-27T15:33:34.783385 -    0.0 seconds: /home/hotntwitchy/comfy/ComfyUI/custom_nodes/ComfyUI-Manager
2025-06-27T15:33:34.783419 - 
2025-06-27T15:33:34.855099 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-06-27T15:33:34.862381 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-06-27T15:33:35.044584 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-06-27T15:33:35.089989 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-06-27T15:33:35.130632 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-06-27T15:33:35.159779 - Context impl SQLiteImpl.
2025-06-27T15:33:35.159875 - Will assume non-transactional DDL.
2025-06-27T15:33:35.160555 - No target revision found.
2025-06-27T15:33:35.166242 - Starting server

2025-06-27T15:33:35.166494 - To see the GUI go to: http://127.0.0.1:8188
2025-06-27T15:33:37.624353 - FETCH ComfyRegistry Data: 5/902025-06-27T15:33:37.624376 - 
2025-06-27T15:33:40.593849 - FETCH ComfyRegistry Data: 10/902025-06-27T15:33:40.593879 - 
2025-06-27T15:33:43.665534 - FETCH ComfyRegistry Data: 15/902025-06-27T15:33:43.665575 - 
2025-06-27T15:33:46.691585 - FETCH ComfyRegistry Data: 20/902025-06-27T15:33:46.691609 - 
2025-06-27T15:33:49.663646 - FETCH ComfyRegistry Data: 25/902025-06-27T15:33:49.663674 - 
2025-06-27T15:33:52.639473 - FETCH ComfyRegistry Data: 30/902025-06-27T15:33:52.639504 - 
2025-06-27T15:33:55.575260 - FETCH ComfyRegistry Data: 35/902025-06-27T15:33:55.575283 - 
2025-06-27T15:33:58.525576 - FETCH ComfyRegistry Data: 40/902025-06-27T15:33:58.525645 - 
2025-06-27T15:34:01.507737 - FETCH ComfyRegistry Data: 45/902025-06-27T15:34:01.507763 - 
2025-06-27T15:34:03.682211 - got prompt
2025-06-27T15:34:03.715831 - model weight dtype torch.float16, manual cast: None
2025-06-27T15:34:03.716418 - model_type EPS
2025-06-27T15:34:03.914771 - Using pytorch attention in VAE
2025-06-27T15:34:03.915657 - Using pytorch attention in VAE
2025-06-27T15:34:03.964113 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-06-27T15:34:04.003842 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-06-27T15:34:04.136647 - Requested to load SD1ClipModel
2025-06-27T15:34:04.177535 - loaded completely 11761.3625 235.84423828125 True
2025-06-27T15:34:04.180237 - !!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-06-27T15:34:04.181821 - Traceback (most recent call last):
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd.py", line 167, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd.py", line 229, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 683, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 288, in encode
    return self(tokens)
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 250, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/ops.py", line 237, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/ops.py", line 233, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-06-27T15:34:04.182833 - Prompt executed in 0.50 seconds
2025-06-27T15:34:04.500065 - FETCH ComfyRegistry Data: 50/902025-06-27T15:34:04.500095 - 
2025-06-27T15:34:07.448482 - FETCH ComfyRegistry Data: 55/902025-06-27T15:34:07.448512 - 
2025-06-27T15:34:07.982330 - got prompt
2025-06-27T15:34:07.986750 - !!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-06-27T15:34:07.988580 - Traceback (most recent call last):
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd.py", line 167, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd.py", line 229, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 683, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 288, in encode
    return self(tokens)
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 250, in forward
    embeds, attention_mask, num_tokens = self.process_tokens(tokens, device)
                                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/ops.py", line 237, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy/ComfyUI/comfy/ops.py", line 233, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hotntwitchy/comfy-env/lib/python3.13/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-06-27T15:34:07.989840 - Prompt executed in 0.01 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"id":"44280e70-6d0d-413b-bc6f-70aed9fbdc60","revision":0,"last_node_id":7,"last_link_id":9,"nodes":[{"id":5,"type":"EmptyLatentImage","pos":[846,763],"size":[270,106],"flags":{},"order":0,"mode":0,"inputs":[{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":null},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":null},{"localized_name":"batch_size","name":"batch_size","type":"INT","widget":{"name":"batch_size"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","links":[6]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"EmptyLatentImage"},"widgets_values":[1920,1080,1]},{"id":1,"type":"KSampler","pos":[1221,297],"size":[270,262],"flags":{},"order":4,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":1},{"localized_name":"positive","name":"positive","type":"CONDITIONING","link":2},{"localized_name":"negative","name":"negative","type":"CONDITIONING","link":3},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":6},{"localized_name":"seed","name":"seed","type":"INT","widget":{"name":"seed"},"link":null},{"localized_name":"steps","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"cfg","name":"cfg","type":"FLOAT","widget":{"name":"cfg"},"link":null},{"localized_name":"sampler_name","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null},{"localized_name":"scheduler","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"denoise","name":"denoise","type":"FLOAT","widget":{"name":"denoise"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","links":[7]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"KSampler"},"widgets_values":[450926759988290,"randomize",20,8,"euler","normal",1]},{"id":6,"type":"VAEDecode","pos":[1583.8543701171875,195.5821075439453],"size":[140,46],"flags":{},"order":5,"mode":0,"inputs":[{"localized_name":"samples","name":"samples","type":"LATENT","link":7},{"localized_name":"vae","name":"vae","type":"VAE","link":8}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","links":[9]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":7,"type":"PreviewImage","pos":[1708.3028564453125,548.43017578125],"size":[140,26],"flags":{},"order":6,"mode":0,"inputs":[{"localized_name":"images","name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":3,"type":"CLIPTextEncode","pos":[662,216],"size":[400,200],"flags":{},"order":2,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":4},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","links":[2]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"CLIPTextEncode"},"widgets_values":["Badass dragon breathing fire, black"]},{"id":4,"type":"CLIPTextEncode","pos":[674,478],"size":[400,200],"flags":{},"order":3,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":5},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","links":[3]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"CLIPTextEncode"},"widgets_values":["cool"]},{"id":2,"type":"CheckpointLoaderSimple","pos":[211,297],"size":[270,98],"flags":{},"order":1,"mode":0,"inputs":[{"localized_name":"ckpt_name","name":"ckpt_name","type":"COMBO","widget":{"name":"ckpt_name"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","links":[1]},{"localized_name":"CLIP","name":"CLIP","type":"CLIP","links":[4,5]},{"localized_name":"VAE","name":"VAE","type":"VAE","links":[8]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.42","Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["v1-5-pruned-emaonly.safetensors"]}],"links":[[1,2,0,1,0,"MODEL"],[2,3,0,1,1,"CONDITIONING"],[3,4,0,1,2,"CONDITIONING"],[4,2,1,3,0,"CLIP"],[5,2,1,4,0,"CLIP"],[6,5,0,1,3,"LATENT"],[7,1,0,6,0,"LATENT"],[8,2,2,6,1,"VAE"],[9,6,0,7,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6830134553650705,"offset":[45.68890000000025,400.3065999999996]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by 6Morpheus6** [comment]
@hotntwitchy Your system information shows PyTorch Version: 2.7.1+cu126
If that's true you have the wrong torch version which also matches the error you got.
Please verify it.
Activate your comfyui environment.
I think on your  linux terminal it is:
- `cd /home/hotntwitchy`
- `source comfy-env/bin/activate`
- `pip show torch`
If you really get torch 2.7.1+cu126, use this command below:
- `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 --force-reinstall --no-deps`
Try comfyui again once the installation is finished.

**Comment by samanthajonesfitness** [comment]
Im having this same issue

**Comment by hotntwitchy** [comment]
> [@hotntwitchy](https://github.com/hotntwitchy) Your system information shows PyTorch Version: 2.7.1+cu126 If that's true you have the wrong torch version which also matches the error you got. Please verify it. Activate your comfyui environment. I think on your linux terminal it is:
> 
>     * `cd /home/hotntwitchy`
> 
>     * `source comfy-env/bin/activate`
> 
>     * `pip show torch`
>       If you really get torch 2.7.1+cu126, use this command below:
> 
>     * `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 --force-reinstall --no-deps`
>       Try comfyui again once the installation is finished.

Thanks for the help! I ran what you suggested and got: 
(comfy-env) hotntwitchy@TwitchyOS:~$ cd /home/hotntwitchy
(comfy-env) hotntwitchy@TwitchyOS:~$ source comfy-env/bin/activate
(comfy-env) hotntwitchy@TwitchyOS:~$ pip show torch
Name: torch
Version: 2.7.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration

Doesn't say the cu, but when I run the following I get: 

python3 -c "import torch; print(torch.__version__)"
2.7.1+cu126

I ran your above command and it's now working! I had installed 128 already but I'm guessing my syntax didn't set it as active.

**Comment by GhosTHaise** [comment]
This error occurs when your CUDA version is not compatible with the version of PyTorch installed on ComfyUI.
I solved this with (I use comfyui portable version on windows) : 
1/ Check your current  cuda version

<img width="1534" height="1039" alt="Image" src="https://github.com/user-attachments/assets/6074ba04-17e9-4af7-ad1e-614230fda8d1" />

2/ Install the torch , torchvision , torchaudio for your cuda version.

<img width="1202" height="423" alt="Image" src="https://github.com/user-attachments/assets/dc33abb8-6e24-461c-bb57-49cbc810af38" />

Here is the full command to do it :
Enter in "**ComfyUI_windows_portable**" , there is a python_embeded folder , and we need to use the python installed inside this. 
`.\python_embeded\python.exe -s -m pip install torch 
torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126(replace the 126 by your current version) --force-reinstall --no-deps 
`

**Comment by momoids** [comment]
I'm having the same problem and I'm a noob! I'm using the portable version. I'm trying to use a workflow that was in "templates/model 3D/Hunyuan3D 2.1". After I put an image of a green orc, press RUN, and the error appears! Can anyone help me?

<img width="3817" height="1773" alt="Image" src="https://github.com/user-attachments/assets/a1b10ba7-e5af-471d-b172-8d40f0f3812b" />

<img width="3801" height="1764" alt="Image" src="https://github.com/user-attachments/assets/98b7c87b-9cce-46a4-abc7-d30755f4eb9c" />

<img width="2442" height="1775" alt="Image" src="https://github.com/user-attachments/assets/283a8bd8-c99e-48e7-80d9-44b17b2e0f4a" />
