### ISSUE TITLE
Error when running Flux Kontext FP8 model

### ISSUE THREAD

**Issue by CrazyDadGamer11** [comfyanonymous/ComfyUI#9009]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

When using the Flux Kontext model in Comfy_UI, an error reports that CUDA error: CUBLAS_STATUS_NOT_SUPPORTED. It is with Ksampler. Have added stack output from running. Have tried updating and downgrading to various version of Pytorch, cuda, Cuda tools but nothing has worked, exactly same error every time. I am running a 4080 Super which I have heard is more than capable of running it

### Logs

```powershell
F:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-07-22 17:45:27.484
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: F:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\AI\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: F:\AI\ComfyUI_windows_portable\ComfyUI
** User directory: F:\AI\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: F:\AI\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: F:\AI\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   2.8 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 16376 MB, total RAM 32614 MB
pytorch version: 2.7.1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
Using pytorch attention
Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
ComfyUI version: 0.3.44
ComfyUI frontend version: 1.23.4
[Prompt Server] web root: F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\comfyui_frontend_package\static
sageattn not found, using sdpa
sageattn not found, using sdpa
sageattn not found, using sdpa
F5TTS. Checking out submodules
F5TTS. Something is wrong with your git installation.  It is unable to checkout submodules.  You can install the latest from https://git-scm.com/downloads
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2124, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-f5-tts\__init__.py", line 2, in <module>
    from .F5TTS import F5TTSAudio, F5TTSAudioInputs, F5TTSAudioAdvanced
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-f5-tts\F5TTS.py", line 24, in <module>
    from f5_tts.model import DiT, UNetT  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'f5_tts'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-f5-tts module for custom nodes: No module named 'f5_tts'
jjk_util loding
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2124, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KokoroTTS\__init__.py", line 1, in <module>
    from .KokoroTextToSpeech import NODE_CLASS_MAPPINGS
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KokoroTTS\KokoroTextToSpeech.py", line 4, in <module>
    from kokoro_onnx import Kokoro
ModuleNotFoundError: No module named 'kokoro_onnx'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KokoroTTS module for custom nodes: No module named 'kokoro_onnx'
theUpsiders Logic Nodes: Loaded
### Loading: ComfyUI-Manager (V3.34)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.44-29-g1da5639e | Released on '2025-07-19'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
成功从 F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TuZi-Flux-Kontext\.env 加载 .env 文件。
[F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False
[F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2124, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT\__init__.py", line 1, in <module>
    from .tensorrt_convert import DYNAMIC_TRT_MODEL_CONVERSION
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 7, in <module>
    import tensorrt as trt
ModuleNotFoundError: No module named 'tensorrt'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT module for custom nodes: No module named 'tensorrt'

[rgthree-comfy] Loaded 47 exciting nodes. 🎉


Import times for custom nodes:
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KokoroTTS
   0.0 seconds (IMPORT FAILED): F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Jjk-Nodes
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX-MZ
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TuZi-Flux-Kontext
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.3 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.3 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
   0.3 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds (IMPORT FAILED): F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-f5-tts
   1.1 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX

Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 5/92
FETCH ComfyRegistry Data: 10/92
got prompt
Failed to validate prompt for output 136:
* VAELoader 39:
  - Value not in list: vae_name: 'my_vae\ae.safetensors' not in ['ae.safetensors', 'flux1-dev_vae.safetensors', 'sdxl_vae.safetensors', 'wan_2.1_vae.safetensors', 'taesd', 'taesdxl', 'taesd3']
* DualCLIPLoader 38:
  - Value not in list: clip_name1: 'my_text_encoders\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors' not in ['ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors', 'clip_l.safetensors', 't5xxl_fp8_e4m3fn.safetensors', 't5xxl_fp8_e4m3fn_scaled.safetensors', 'umt5_xxl_fp8_e4m3fn_scaled.safetensors']
  - Value not in list: clip_name2: 'my_text_encoders\t5xxl_fp8_e4m3fn_scaled.safetensors' not in ['ViT-L-14-TEXT-detail-improved-hiT-GmP-HF.safetensors', 'clip_l.safetensors', 't5xxl_fp8_e4m3fn.safetensors', 't5xxl_fp8_e4m3fn_scaled.safetensors', 'umt5_xxl_fp8_e4m3fn_scaled.safetensors']
* UNETLoader 37:
  - Value not in list: unet_name: 'my_diffusion_models\flux1-dev-kontext_fp8_scaled.safetensors' not in ['cosmos_predict2_2B_video2world_480p_16fps.safetensors', 'flux1-dev-fp8.safetensors', 'flux1-dev-kontext_fp8_scaled.safetensors', 'flux1-schnell-fp8.safetensors']
Output will be ignored
Prompt executed in 0.28 seconds
FETCH ComfyRegistry Data: 15/92
FETCH ComfyRegistry Data: 20/92
FETCH ComfyRegistry Data: 25/92
FETCH ComfyRegistry Data: 30/92
FETCH ComfyRegistry Data: 35/92
FETCH ComfyRegistry Data: 40/92
FETCH ComfyRegistry Data: 45/92
FETCH ComfyRegistry Data: 50/92
FETCH ComfyRegistry Data: 55/92
FETCH ComfyRegistry Data: 60/92
FETCH ComfyRegistry Data: 65/92
FETCH ComfyRegistry Data: 70/92
FETCH ComfyRegistry Data: 75/92
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load AutoencodingEngine
loaded completely 10935.51171875 159.87335777282715 True
Using scaled fp8: fp8 matrix mult: False, scale input: False
Requested to load FluxClipModel_
loaded completely 9.5367431640625e+25 4903.231597900391 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
FETCH ComfyRegistry Data: 80/92
FETCH ComfyRegistry Data: 85/92
Using scaled fp8: fp8 matrix mult: True, scale input: True
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
FETCH ComfyRegistry Data: 90/92
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
Requested to load Flux
loaded completely 12539.786919891358 11350.088394165039 True
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!! CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Ddesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 427, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 270, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 244, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 232, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1516, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1483, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1143, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1033, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1018, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 986, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 969, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 748, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 190, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 400, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 949, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 952, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 380, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 152, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 190, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\flux\model.py", line 242, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options, attn_mask=kwargs.get("attention_mask", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\flux\model.py", line 113, in forward_orig
    img = self.img_in(img)
          ^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 84, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 371, in forward_comfy_cast_weights
    out = fp8_linear(self, input)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 317, in fp8_linear
    o = torch._scaled_mm(input, w, out_dtype=input_dtype, bias=bias, scale_a=scale_input, scale_b=scale_weight)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Ddesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`

Prompt executed in 21.27 seconds
```

**Comment by yoland68** [comment]
Trying to reproduce it

**Comment by CrazyDadGamer11** [comment]
Good evening. Problem solved. Embedded pytorch + cuda versions did not meet required specs. comfy was not using system installed. forced update within COMFY_UI. All Fixed
