### ISSUE TITLE
Wan2.2 video template doesn't work on Apple Silicon

### ISSUE THREAD

**Issue by mkduk** [comfyanonymous/ComfyUI#9255]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Text to video rendering from the built-in template for Wan2.2.

### Actual Behavior

> KSampler: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

### Steps to Reproduce

Apple Studio M2 running Sequoia 15.6.
Fresh install of ComfyUI Version 0.4.61 (250805o3pa42x0d).
Choose "Browse Templates" from the "Workflow" menu.
Click "Video" in the left column.
Click the template "Wan 2.2 14B Text to Video".
Without making any changes to the workflow, click "Run" at the bottom.

Based on a [closed bug report for a similar issue last February](https://github.com/comfyanonymous/ComfyUI/issues/6995) I added launch arguments to the comfy.settings.json file to force fp16, use split cross attention, and allow CPU fallback:
 "Comfy.Server.LaunchArgs": {"force-fp16": "", "use-split-cross-attention": "", "cpu": ""}
It appears to work except that it falls back to the CPU, so rendering goes on forever with 0% GPU usage and no apparent progress.
When I remove the CPU fallback argument, the error comes right back.

Another [similar issue report](https://github.com/comfyanonymous/ComfyUI/issues/6254) suggested that an old version of pyTorch could cause this error. I opened Comfy's virtual environment (cd into ComfyUI/.venv/bin and run "source activate") and checked the version with "pip3 show torch". It reports pyTorch 2.8.0.dev20250525, which should be sufficient.

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 57
- **Node Type:** KSamplerAdvanced
- **Exception Type:** TypeError
- **Exception Message:** Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

## Stack Trace

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1555, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1488, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1143, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1033, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1018, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 986, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 969, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 748, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/k_diffusion/sampling.py", line 190, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 400, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 949, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 952, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 380, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 155, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 194, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/wan/model.py", line 580, in forward
    return self.forward_orig(x, timestep, context, clip_fea=clip_fea, freqs=freqs, transformer_options=transformer_options, **kwargs)[:, :, :t, :h, :w]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/wan/model.py", line 524, in forward_orig
    e = self.time_embedding(
        ^^^^^^^^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/container.py", line 245, in forward
    input = module(input)
            ^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 84, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 375, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 51, in cast_bias_weight
    bias = comfy.model_management.cast_to(s.bias, bias_dtype, device, non_blocking=non_blocking, copy=has_function, stream=offload_stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_management.py", line 1031, in cast_to
    return weight.to(dtype=dtype, copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


## System Information
- **ComfyUI Version:** 0.3.49
- **Arguments:** /Applications/ComfyUI.app/Contents/Resources/ComfyUI/main.py --user-directory /Users/Morbo/Starship/AI/ComfyUI/user --input-directory /Users/Morbo/Starship/AI/ComfyUI/input --output-directory /Users/Morbo/Starship/AI/ComfyUI/output --front-end-root /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app --base-directory /Users/Morbo/Starship/AI/ComfyUI --extra-model-paths-config /Users/Morbo/Library/Application Support/ComfyUI/extra_models_config.yaml --log-stdout --listen 127.0.0.1 --port 8000
- **OS:** posix
- **Python Version:** 3.12.9 (main, Feb 12 2025, 15:09:19) [Clang 19.1.6 ]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0.dev20250525
## Devices

- **Name:** mps
  - **Type:** mps
  - **VRAM Total:** 137438953472
  - **VRAM Free:** 62765088768
  - **Torch VRAM Total:** 137438953472
  - **Torch VRAM Free:** 62765088768

## Logs

2025-08-08T13:44:30.861597 - Adding extra search path custom_nodes /Users/Morbo/Starship/AI/ComfyUI/custom_nodes
2025-08-08T13:44:30.861646 - Adding extra search path download_model_base /Users/Morbo/Starship/AI/ComfyUI/models
2025-08-08T13:44:30.861667 - Adding extra search path custom_nodes /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes
2025-08-08T13:44:30.861684 - Setting output directory to: /Users/Morbo/Starship/AI/ComfyUI/output
2025-08-08T13:44:30.861702 - Setting input directory to: /Users/Morbo/Starship/AI/ComfyUI/input
2025-08-08T13:44:30.861713 - Setting user directory to: /Users/Morbo/Starship/AI/ComfyUI/user
2025-08-08T13:44:31.155544 - [START] Security scan2025-08-08T13:44:31.155553 - 
2025-08-08T13:44:31.452705 - [DONE] Security scan2025-08-08T13:44:31.452731 - 
2025-08-08T13:44:31.505500 - ## ComfyUI-Manager: installing dependencies done.2025-08-08T13:44:31.505545 - 
2025-08-08T13:44:31.505570 - ** ComfyUI startup time:2025-08-08T13:44:31.505583 -  2025-08-08T13:44:31.505595 - 2025-08-08 13:44:31.5052025-08-08T13:44:31.505607 - 
2025-08-08T13:44:31.505624 - ** Platform:2025-08-08T13:44:31.505634 -  2025-08-08T13:44:31.505644 - Darwin2025-08-08T13:44:31.505653 - 
2025-08-08T13:44:31.505665 - ** Python version:2025-08-08T13:44:31.505674 -  2025-08-08T13:44:31.505684 - 3.12.9 (main, Feb 12 2025, 15:09:19) [Clang 19.1.6 ]2025-08-08T13:44:31.505693 - 
2025-08-08T13:44:31.505703 - ** Python executable:2025-08-08T13:44:31.505712 -  2025-08-08T13:44:31.505721 - /Users/Morbo/Starship/AI/ComfyUI/.venv/bin/python2025-08-08T13:44:31.505730 - 
2025-08-08T13:44:31.505739 - ** ComfyUI Path:2025-08-08T13:44:31.505748 -  2025-08-08T13:44:31.505757 - /Applications/ComfyUI.app/Contents/Resources/ComfyUI2025-08-08T13:44:31.505765 - 
2025-08-08T13:44:31.505774 - ** ComfyUI Base Folder Path:2025-08-08T13:44:31.505783 -  2025-08-08T13:44:31.505792 - /Applications/ComfyUI.app/Contents/Resources/ComfyUI2025-08-08T13:44:31.505801 - 
2025-08-08T13:44:31.505810 - ** User directory:2025-08-08T13:44:31.505819 -  2025-08-08T13:44:31.505828 - /Users/Morbo/Starship/AI/ComfyUI/user2025-08-08T13:44:31.505836 - 
2025-08-08T13:44:31.505847 - ** ComfyUI-Manager config path:2025-08-08T13:44:31.505856 -  2025-08-08T13:44:31.505865 - /Users/Morbo/Starship/AI/ComfyUI/user/default/ComfyUI-Manager/config.ini2025-08-08T13:44:31.505874 - 
2025-08-08T13:44:31.505884 - ** Log path:2025-08-08T13:44:31.505892 -  2025-08-08T13:44:31.505901 - /Users/Morbo/Starship/AI/ComfyUI/user/comfyui.log2025-08-08T13:44:31.505909 - 
2025-08-08T13:44:31.806704 - [ComfyUI-Manager] Failed to restore comfyui-frontend-package
2025-08-08T13:44:31.806853 - expected str, bytes or os.PathLike object, not NoneType
2025-08-08T13:44:31.807342 - 
Prestartup times for custom nodes:
2025-08-08T13:44:31.807407 -    0.9 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager
2025-08-08T13:44:31.807492 - 
2025-08-08T13:44:34.791744 - Checkpoint files will always be loaded safely.
2025-08-08T13:44:34.822102 - Total VRAM 131072 MB, total RAM 131072 MB
2025-08-08T13:44:34.822188 - pytorch version: 2.8.0.dev20250525
2025-08-08T13:44:34.823618 - Mac Version (15, 6)
2025-08-08T13:44:34.823764 - Set vram state to: SHARED
2025-08-08T13:44:34.823807 - Device: mps
2025-08-08T13:44:36.889403 - Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
2025-08-08T13:44:39.934682 - Python version: 3.12.9 (main, Feb 12 2025, 15:09:19) [Clang 19.1.6 ]
2025-08-08T13:44:39.934766 - ComfyUI version: 0.3.49
2025-08-08T13:44:39.936179 - [Prompt Server] web root: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app
2025-08-08T13:44:40.518707 - ### Loading: ComfyUI-Manager (V3.30.4)
2025-08-08T13:44:40.519053 - [ComfyUI-Manager] network_mode: public
2025-08-08T13:44:40.532614 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
2025-08-08T13:44:40.539870 - 
Import times for custom nodes:
2025-08-08T13:44:40.539934 -    0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/websocket_image_save.py
2025-08-08T13:44:40.539967 -    0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager
2025-08-08T13:44:40.539992 - 
2025-08-08T13:44:40.669822 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-08-08T13:44:40.677371 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-08-08T13:44:40.701420 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-08-08T13:44:40.750998 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-08-08T13:44:40.781476 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-08-08T13:44:40.955005 - Failed to initialize database. Please ensure you have installed the latest requirements. If the error persists, please report this as in future the database will be required: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-08T13:44:40.959925 - Starting server

2025-08-08T13:44:40.960135 - To see the GUI go to: http://127.0.0.1:8000
2025-08-08T13:44:42.079974 - comfyui-frontend-package not found in requirements.txt
2025-08-08T13:44:43.500329 - FETCH ComfyRegistry Data: 5/932025-08-08T13:44:43.500371 - 
2025-08-08T13:44:46.728475 - FETCH ComfyRegistry Data: 10/932025-08-08T13:44:46.728547 - 
2025-08-08T13:44:49.968590 - FETCH ComfyRegistry Data: 15/932025-08-08T13:44:49.968666 - 
2025-08-08T13:44:53.329005 - FETCH ComfyRegistry Data: 20/932025-08-08T13:44:53.329047 - 
2025-08-08T13:44:56.753340 - FETCH ComfyRegistry Data: 25/932025-08-08T13:44:56.753405 - 
2025-08-08T13:45:00.377948 - FETCH ComfyRegistry Data: 30/932025-08-08T13:45:00.378023 - 
2025-08-08T13:45:03.710201 - FETCH ComfyRegistry Data: 35/932025-08-08T13:45:03.710292 - 
2025-08-08T13:45:06.969619 - FETCH ComfyRegistry Data: 40/932025-08-08T13:45:06.969689 - 
2025-08-08T13:45:10.758388 - FETCH ComfyRegistry Data: 45/932025-08-08T13:45:10.758563 - 
2025-08-08T13:45:14.439133 - FETCH ComfyRegistry Data: 50/932025-08-08T13:45:14.439298 - 
2025-08-08T13:45:18.423050 - FETCH ComfyRegistry Data: 55/932025-08-08T13:45:18.423109 - 
2025-08-08T13:45:21.785009 - FETCH ComfyRegistry Data: 60/932025-08-08T13:45:21.785134 - 
2025-08-08T13:45:25.240293 - FETCH ComfyRegistry Data: 65/932025-08-08T13:45:25.240371 - 
2025-08-08T13:45:29.180557 - FETCH ComfyRegistry Data: 70/932025-08-08T13:45:29.180634 - 
2025-08-08T13:45:32.606662 - FETCH ComfyRegistry Data: 75/932025-08-08T13:45:32.606747 - 
2025-08-08T13:45:36.308502 - FETCH ComfyRegistry Data: 80/932025-08-08T13:45:36.308567 - 
2025-08-08T13:45:40.008732 - FETCH ComfyRegistry Data: 85/932025-08-08T13:45:40.008795 - 
2025-08-08T13:45:43.434261 - FETCH ComfyRegistry Data: 90/932025-08-08T13:45:43.434332 - 
2025-08-08T13:45:46.010023 - FETCH ComfyRegistry Data [DONE]2025-08-08T13:45:46.010100 - 
2025-08-08T13:45:46.087310 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-08-08T13:45:46.113200 - nightly_channel: 
https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/remote
2025-08-08T13:45:46.113461 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-08-08T13:45:46.113473 - 2025-08-08T13:45:46.312498 -  [DONE]2025-08-08T13:45:46.312535 - 
2025-08-08T13:45:46.339320 - [ComfyUI-Manager] All startup tasks have been completed.
2025-08-08T13:57:05.669436 - got prompt
2025-08-08T13:57:05.702159 - Using split attention in VAE
2025-08-08T13:57:05.702806 - Using split attention in VAE
2025-08-08T13:57:05.891708 - VAE load device: mps, offload device: cpu, dtype: torch.bfloat16
2025-08-08T13:57:05.934017 - Using scaled fp8: fp8 matrix mult: False, scale input: False
2025-08-08T13:57:06.239100 - Requested to load WanTEModel
2025-08-08T13:57:06.243368 - loaded completely 9.5367431640625e+25 6419.477203369141 True
2025-08-08T13:57:06.244576 - CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
2025-08-08T13:57:17.074375 - Using scaled fp8: fp8 matrix mult: False, scale input: True
2025-08-08T13:57:17.087830 - model weight dtype torch.float16, manual cast: None
2025-08-08T13:57:17.088086 - model_type FLOW
2025-08-08T13:57:21.015041 - Requested to load WAN21
2025-08-08T13:57:22.582859 - loaded completely 9.5367431640625e+25 13627.512924194336 True
2025-08-08T13:57:22.757075 - 
  0%|          | 0/10 [00:00<?, ?it/s]2025-08-08T13:57:23.006674 - 
  0%|          | 0/10 [00:00<?, ?it/s]2025-08-08T13:57:23.006719 - 
2025-08-08T13:57:23.011985 - !!! Exception during processing !!! Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.
2025-08-08T13:57:23.019038 - Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1555, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 1488, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1143, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1033, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 1018, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 986, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 969, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 748, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/k_diffusion/sampling.py", line 190, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 400, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 949, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 952, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 380, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/samplers.py", line 325, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 155, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_base.py", line 194, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/wan/model.py", line 580, in forward
    return self.forward_orig(x, timestep, context, clip_fea=clip_fea, freqs=freqs, transformer_options=transformer_options, **kwargs)[:, :, :t, :h, :w]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ldm/wan/model.py", line 524, in forward_orig
    e = self.time_embedding(
        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/container.py", line 245, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Morbo/Starship/AI/ComfyUI/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 84, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 375, in forward_comfy_cast_weights
    weight, bias = cast_bias_weight(self, input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/ops.py", line 51, in cast_bias_weight
    bias = comfy.model_management.cast_to(s.bias, bias_dtype, device, non_blocking=non_blocking, copy=has_function, stream=offload_stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/model_management.py", line 1031, in cast_to
    return weight.to(dtype=dtype, copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

2025-08-08T13:57:23.021620 - Prompt executed in 17.35 seconds
2025-08-08T13:57:23.137586 - comfyui-frontend-package not found in requirements.txt


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

{"id":"ec7da562-7e21-4dac-a0d2-f4441e1efd3b","revision":0,"last_node_id":63,"last_link_id":132,"nodes":[{"id":38,"type":"CLIPLoader","pos":[38.86457061767578,189.26513671875],"size":[346.391845703125,106],"flags":{},"order":0,"mode":0,"inputs":[{"localized_name":"clip_name","name":"clip_name","type":"COMBO","widget":{"name":"clip_name"},"link":null},{"localized_name":"type","name":"type","type":"COMBO","widget":{"name":"type"},"link":null},{"localized_name":"device","name":"device","shape":7,"type":"COMBO","widget":{"name":"device"},"link":null}],"outputs":[{"localized_name":"CLIP","name":"CLIP","type":"CLIP","slot_index":0,"links":[74,75]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CLIPLoader","models":[{"name":"umt5_xxl_fp8_e4m3fn_scaled.safetensors","url":"https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors","directory":"text_encoders"}]},"widgets_values":["umt5_xxl_fp8_e4m3fn_scaled.safetensors","wan","default"]},{"id":7,"type":"CLIPTextEncode","pos":[420,480],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":8,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":75},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[129,130]}],"title":"CLIP Text Encode (Negative Prompt)","properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CLIPTextEncode"},"widgets_values":["色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走"],"color":"#322","bgcolor":"#533"},{"id":39,"type":"VAELoader","pos":[40,350],"size":[344.731689453125,59.98149108886719],"flags":{},"order":1,"mode":0,"inputs":[{"localized_name":"vae_name","name":"vae_name","type":"COMBO","widget":{"name":"vae_name"},"link":null}],"outputs":[{"localized_name":"VAE","name":"VAE","type":"VAE","slot_index":0,"links":[76]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"VAELoader","models":[{"name":"wan_2.1_vae.safetensors","url":"https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors","directory":"vae"}]},"widgets_values":["wan_2.1_vae.safetensors"]},{"id":54,"type":"ModelSamplingSD3","pos":[640,-70],"size":[210,60],"flags":{},"order":9,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":110},{"localized_name":"shift","name":"shift","type":"FLOAT","widget":{"name":"shift"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[125]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"ModelSamplingSD3"},"widgets_values":[8.000000000000002]},{"id":55,"type":"ModelSamplingSD3","pos":[640,60],"size":[210,58],"flags":{},"order":10,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":112},{"localized_name":"shift","name":"shift","type":"FLOAT","widget":{"name":"shift"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[123]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"ModelSamplingSD3"},"widgets_values":[8]},{"id":58,"type":"KSamplerAdvanced","pos":[890,360],"size":[304.748046875,498.6905822753906],"flags":{},"order":12,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":123},{"localized_name":"positive","name":"positive","type":"CONDITIONING","link":128},{"localized_name":"negative","name":"negative","type":"CONDITIONING","link":130},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":113},{"localized_name":"add_noise","name":"add_noise","type":"COMBO","widget":{"name":"add_noise"},"link":null},{"localized_name":"noise_seed","name":"noise_seed","type":"INT","widget":{"name":"noise_seed"},"link":null},{"localized_name":"steps","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"cfg","name":"cfg","type":"FLOAT","widget":{"name":"cfg"},"link":null},{"localized_name":"sampler_name","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null},{"localized_name":"scheduler","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"start_at_step","name":"start_at_step","type":"INT","widget":{"name":"start_at_step"},"link":null},{"localized_name":"end_at_step","name":"end_at_step","type":"INT","widget":{"name":"end_at_step"},"link":null},{"localized_name":"return_with_leftover_noise","name":"return_with_leftover_noise","type":"COMBO","widget":{"name":"return_with_leftover_noise"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","links":[124]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"KSamplerAdvanced"},"widgets_values":["disable",0,"fixed",20,3.5,"euler","simple",10,10000,"disable"]},{"id":57,"type":"KSamplerAdvanced","pos":[890,-60],"size":[304.748046875,334],"flags":{},"order":11,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":125},{"localized_name":"positive","name":"positive","type":"CONDITIONING","link":127},{"localized_name":"negative","name":"negative","type":"CONDITIONING","link":129},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":126},{"localized_name":"add_noise","name":"add_noise","type":"COMBO","widget":{"name":"add_noise"},"link":null},{"localized_name":"noise_seed","name":"noise_seed","type":"INT","widget":{"name":"noise_seed"},"link":null},{"localized_name":"steps","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"cfg","name":"cfg","type":"FLOAT","widget":{"name":"cfg"},"link":null},{"localized_name":"sampler_name","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null},{"localized_name":"scheduler","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"start_at_step","name":"start_at_step","type":"INT","widget":{"name":"start_at_step"},"link":null},{"localized_name":"end_at_step","name":"end_at_step","type":"INT","widget":{"name":"end_at_step"},"link":null},{"localized_name":"return_with_leftover_noise","name":"return_with_leftover_noise","type":"COMBO","widget":{"name":"return_with_leftover_noise"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","links":[113]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"KSamplerAdvanced"},"widgets_values":["enable",785477396017016,"randomize",20,3.5,"euler","simple",0,10,"enable"]},{"id":8,"type":"VAEDecode","pos":[1240,-40],"size":[210,46],"flags":{},"order":13,"mode":0,"inputs":[{"localized_name":"samples","name":"samples","type":"LATENT","link":124},{"localized_name":"vae","name":"vae","type":"VAE","link":76}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","slot_index":0,"links":[131]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":61,"type":"SaveVideo","pos":[1240,190],"size":[710,660],"flags":{},"order":15,"mode":0,"inputs":[{"localized_name":"video","name":"video","type":"VIDEO","link":132},{"localized_name":"filename_prefix","name":"filename_prefix","type":"STRING","widget":{"name":"filename_prefix"},"link":null},{"localized_name":"format","name":"format","type":"COMBO","widget":{"name":"format"},"link":null},{"localized_name":"codec","name":"codec","type":"COMBO","widget":{"name":"codec"},"link":null}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"SaveVideo"},"widgets_values":["video/ComfyUI","auto","auto"]},{"id":6,"type":"CLIPTextEncode","pos":[420,280],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":7,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":74},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[127,128]}],"title":"CLIP Text Encode (Positive Prompt)","properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CLIPTextEncode"},"widgets_values":["A close-up of a young woman smiling gently in the rain, raindrops glistening on her face and eyelashes. The video captures the delicate details of her expression and the water droplets, with soft light reflecting off her skin in the rainy atmosphere."],"color":"#232","bgcolor":"#353"},{"id":62,"type":"MarkdownNote","pos":[-480,-120],"size":[480,350],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[],"title":"Model Links","properties":{},"widgets_values":["[Tutorial](https://docs.comfy.org/tutorials/video/wan/wan2_2\n) | [教程](https://docs.comfy.org/zh-CN/tutorials/video/wan/wan2_2\n)\n\n**Diffusion Model**\n- [wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors](https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors)\n- [wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors](https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors)\n\n**VAE**\n- [wan_2.1_vae.safetensors](https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors)\n\n**Text Encoder**   \n- [umt5_xxl_fp8_e4m3fn_scaled.safetensors](https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors)\n\n\nFile save location\n\n\nComfyUI/\n├───📂 models/\n│   ├───📂 diffusion_models/\n│   │   ├─── wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors\n│   │   └─── wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors\n│   ├───📂 text_encoders/\n│   │   └─── umt5_xxl_fp8_e4m3fn_scaled.safetensors \n│   └───📂 vae/\n│       └── wan_2.1_vae.safetensors\n\n"],"color":"#432","bgcolor":"#653"},{"id":60,"type":"CreateVideo","pos":[1240,60],"size":[270,78],"flags":{},"order":14,"mode":0,"inputs":[{"localized_name":"images","name":"images","type":"IMAGE","link":131},{"localized_name":"audio","name":"audio","shape":7,"type":"AUDIO","link":null},{"localized_name":"fps","name":"fps","type":"FLOAT","widget":{"name":"fps"},"link":null}],"outputs":[{"localized_name":"VIDEO","name":"VIDEO","type":"VIDEO","links":[132]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"CreateVideo"},"widgets_values":[16]},{"id":37,"type":"UNETLoader","pos":[34.225364685058594,-71.77911376953125],"size":[346.7470703125,82],"flags":{},"order":3,"mode":0,"inputs":[{"localized_name":"unet_name","name":"unet_name","type":"COMBO","widget":{"name":"unet_name"},"link":null},{"localized_name":"weight_dtype","name":"weight_dtype","type":"COMBO","widget":{"name":"weight_dtype"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[110]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"UNETLoader","models":[{"name":"wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors","url":"https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors","directory":"diffusion_models"}]},"widgets_values":["wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors","default"]},{"id":56,"type":"UNETLoader","pos":[34.70310592651367,57.175601959228516],"size":[346.7470703125,82],"flags":{},"order":4,"mode":0,"inputs":[{"localized_name":"unet_name","name":"unet_name","type":"COMBO","widget":{"name":"unet_name"},"link":null},{"localized_name":"weight_dtype","name":"weight_dtype","type":"COMBO","widget":{"name":"weight_dtype"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[112]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"UNETLoader","models":[{"name":"wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors","url":"https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors","directory":"diffusion_models"}]},"widgets_values":["wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors","default"]},{"id":63,"type":"Note","pos":[20,720],"size":[370,120],"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[],"title":"Video Size","properties":{},"widgets_values":["By default, we set the video to a smaller size for users with low VRAM. If you have enough VRAM, you can change the size"],"color":"#432","bgcolor":"#653"},{"id":59,"type":"EmptyHunyuanLatentVideo","pos":[50,530],"size":[315,130],"flags":{},"order":6,"mode":0,"inputs":[{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":null},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":null},{"localized_name":"length","name":"length","type":"INT","widget":{"name":"length"},"link":null},{"localized_name":"batch_size","name":"batch_size","type":"INT","widget":{"name":"batch_size"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[126]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.45","Node name for S&R":"EmptyHunyuanLatentVideo"},"widgets_values":[640,640,81,1]}],"links":[[74,38,0,6,0,"CLIP"],[75,38,0,7,0,"CLIP"],[76,39,0,8,1,"VAE"],[110,37,0,54,0,"MODEL"],[112,56,0,55,0,"MODEL"],[113,57,0,58,3,"LATENT"],[123,55,0,58,0,"MODEL"],[124,58,0,8,0,"LATENT"],[125,54,0,57,0,"MODEL"],[126,59,0,57,3,"LATENT"],[127,6,0,57,1,"CONDITIONING"],[128,6,0,58,1,"CONDITIONING"],[129,7,0,57,2,"CONDITIONING"],[130,7,0,58,2,"CONDITIONING"],[131,8,0,60,0,"IMAGE"],[132,60,0,61,0,"VIDEO"]],"groups":[{"id":1,"title":"Step1 - Load models","bounding":[20,-150,371.0310363769531,571.3974609375],"color":"#3f789e","font_size":24,"flags":{}},{"id":2,"title":"Step2 - Video size","bounding":[20,450,367.5572814941406,222.82713317871094],"color":"#3f789e","font_size":24,"flags":{}},{"id":3,"title":"Step3 Prompt","bounding":[410,210,445.27801513671875,464.2060852050781],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.6303940863128874,"offset":[593.9180115080065,315.40287834870713]},"frontendVersion":"1.25.3","VHS_latentpreview":false,"VHS_latentpreviewrate":0,"VHS_MetadataImage":true,"VHS_KeepIntermediate":true},"version":0.4}


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

### Other

There appear to be a number of issue reports for this error message on Macs: [8881](https://github.com/comfyanonymous/ComfyUI/issues/8881), [6859](https://github.com/comfyanonymous/ComfyUI/issues/6859), [6254](https://github.com/comfyanonymous/ComfyUI/issues/6254), [5787](https://github.com/comfyanonymous/ComfyUI/issues/5787), [5541](https://github.com/comfyanonymous/ComfyUI/issues/5541), [5533](https://github.com/comfyanonymous/ComfyUI/issues/5533), [5335](https://github.com/comfyanonymous/ComfyUI/issues/5335)
But none of these seem to actually have any resolution. Has anyone successfully gotten Wan2.2 video to work on Apple silicon?

**Comment by jeff-forest** [comment]
Use GGUF to load corresponding Models, as attached sample screenshot.
Instead using the fp8 Model, for Mac better use the similar GGUF version from https://huggingface.co/QuantStack/Wan2.2-T2V-A14B-GGUF 

<img width="808" height="474" alt="Image" src="https://github.com/user-attachments/assets/9ade5ca2-3220-4dee-8c86-402fcef82fda" />

**Comment by mkduk** [comment]
Thank you @jeff-forest , this worked for me. I do have some questions though if you don't mind.

- QuantStack has GGUF versions of Wan2.2 files in a variety of sizes and configurations. It looks like you're using the 5-bit "Q5_K_M" version, and that one worked for me. Why 5-bit and how did you know to choose that size?
- What does K_M mean and why did you choose that version? (as opposed to the other versions with "K", "K_S", "0", or "1")

Thank you for your help!

**Comment by dprkh** [comment]
> Thank you [@jeff-forest](https://github.com/jeff-forest) , this worked for me. I do have some questions though if you don't mind.
> 
>     * QuantStack has GGUF versions of Wan2.2 files in a variety of sizes and configurations. It looks like you're using the 5-bit "Q5_K_M" version, and that one worked for me. Why 5-bit and how did you know to choose that size?
> 
>     * What does K_M mean and why did you choose that version? (as opposed to the other versions with "K", "K_S", "0", or "1")
> 
> 
> Thank you for your help!

The number of bits indicates the precision. The lower the precision is, the less memory will be used, and the faster inference will be. `K_M` etc, are mixed precision strategies, i.e. only some weights are quantized. `S` stands for small, `M` stands for medium, and `L` stands for large, where small has the greatest amount of weights quantized, and large has the least amount of weights quantized. This is a trade-off between amount of resources used and quality of the output, i.e. if the precision is too low, the output quality may not be satisfactory.
