### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by RobotCyclopsGirlNamePending** [comfyanonymous/ComfyUI#9650]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Someone else has a stale issue with the same error, but has different hardware or a different version of things. I tried putting in one of the commands from the git thread but it didn't solve the issue. I'm an amateur, I don't know ai/python jargon.

### Logs

```powershell
Adding extra search path custom_nodes C:\ComfyUI\custom_nodes
Adding extra search path download_model_base C:\ComfyUI\models
Adding extra search path custom_nodes C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
Setting output directory to: C:\ComfyUI\output
Setting input directory to: C:\ComfyUI\input
Setting user directory to: C:\ComfyUI\user
Checkpoint files will always be loaded safely.
C:\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py:283: UserWarning: 
    Found GPU0 NVIDIA GeForce GTX 1080 Ti which is of cuda capability 6.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (7.0) - (12.0)
    
  warnings.warn(
C:\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py:304: UserWarning: 
    Please install PyTorch with a following CUDA
    configurations:  12.6 following instructions at
    https://pytorch.org/get-started/locally/
    
  warnings.warn(matched_cuda_warn.format(matched_arches))
C:\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py:326: UserWarning: 
NVIDIA GeForce GTX 1080 Ti with CUDA capability sm_61 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.
If you want to use the NVIDIA GeForce GTX 1080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Total VRAM 11264 MB, total RAM 32661 MB
pytorch version: 2.8.0+cu129
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : cudaMallocAsync
Using pytorch attention
Python version: 3.12.11 (main, Aug 18 2025, 19:17:54) [MSC v.1944 64 bit (AMD64)]
ComfyUI version: 0.3.56
[Prompt Server] web root: C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
Skipping loading of custom nodes
Failed to initialize database. Please ensure you have installed the latest requirements. If the error persists, please report this as in future the database will be required: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Starting server

To see the GUI go to: http://127.0.0.1:8000
comfyui-frontend-package not found in requirements.txt
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load AutoencoderKL
loaded completely 7823.0 319.11416244506836 True
!!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 343, in encode
    t = vae.encode(pixels[:,:,:,:3])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 656, in encode
    out = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ldm\models\autoencoder.py", line 184, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "C:\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 591, in forward
    h = self.conv_in(x)
        ^^^^^^^^^^^^^^^
  File "C:\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 140, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 548, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 543, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Prompt executed in 0.93 seconds
```

### Other

- NVIDIA GeForce GTX 1080 Ti
- Windows 10
- 2.8.0+cu128

I have another ai (MMVserverSIO) that I am using, and I don't wish to input commands that will potentially break it. If this means I have to reinstall or redownload comfyUI in an unconventional way, I am fine with this, but I need help getting it to work. I only want to use basic img2img.

**Comment by AngelTs** [comment]
Maybe the old GTX 1080 Ti is the problem. Try to install prior to v0.3.44 (08.07.2025), which is with the new 2.8.0+cu129

**Comment by mlsterpr0** [comment]
Have same error with gtx 1050ti. Actually i'm trying this on my old pc, so i thought some of the software is outdated. I just updated nvidia driver nothing else.
I noticed you on windows 10, so am i.

**Comment by RobotCyclopsGirlNamePending** [comment]
> Maybe the old GTX 1080 Ti is the problem. Try to install prior to v0.3.44 (08.07.2025), which is with the new 2.8.0+cu129

This solution worked, thank you very much

**Comment by mlsterpr0** [comment]
> > Maybe the old GTX 1080 Ti is the problem. Try to install prior to v0.3.44 (08.07.2025), which is with the new 2.8.0+cu129
> 
> This solution worked, thank you very much

I just followed manual installation instuction, and it works now. So the problem was portable version

**Comment by SlothiDeathi** [comment]
> Maybe the old GTX 1080 Ti is the problem. Try to install prior to v0.3.44 (08.07.2025), which is with the new 2.8.0+cu129

are you talking about pytorch version or something else? 

I have the same issue but my gtx is a 1050, and my windows is 11

**Comment by AngelTs** [comment]
> > Maybe the old GTX 1080 Ti is the problem. Try to install prior to v0.3.44 (08.07.2025), which is with the new 2.8.0+cu129
> 
> are you talking about pytorch version or something else?
> 
> I have the same issue but my gtx is a 1050, and my windows is 11

Yes, for GTX you need pytorch 2.8.0 and max CUDA cu128, not cu129
NVIDIA GeForce GTX 10XX with CUDA capability sm_6X is not compatible with the current PyTorch installation (cu129).
The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120, which is the newest comfyui=v0.3.56 (30.08.2025)

**Comment by yebbasheartbreak** [comment]
> > > Maybe the old GTX 1080 Ti is the problem. Try to install prior to v0.3.44 (08.07.2025), which is with the new 2.8.0+cu129
> > 
> > 
> > are you talking about pytorch version or something else?
> > I have the same issue but my gtx is a 1050, and my windows is 11
> 
> Yes, for GTX you need pytorch 2.8.0 and max CUDA cu128, not cu129 NVIDIA GeForce GTX 10XX with CUDA capability sm_6X is not compatible with the current PyTorch installation (cu129). The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120, which is the newest comfyui=v0.3.56 (30.08.2025)

<img width="856" height="213" alt="Image" src="https://github.com/user-attachments/assets/8f61cd4e-e4b0-47ac-8758-e3e3f66e8784" />

I have this version of pytorch and it keeps saying this error like if i dont have that version.

<img width="961" height="354" alt="Image" src="https://github.com/user-attachments/assets/11c3ca9f-2ef9-4cff-9967-20853bc93ede" />

**Comment by AngelTs** [comment]
That is because in `1t window you check the version of installed Python and Pytorch cu126, but in 2nd windows is portable python and Pytorch cu129. Download portable version less than v0.3.44 (08.07.2025. 
Try this one v0.3.40 (05.06.2025) https://github.com/comfyanonymous/ComfyUI/releases/download/v0.3.40/ComfyUI_windows_portable_nvidia.7z

**Comment by Seeriox** [comment]
> That is because in `1t window you check the version of installed Python and Pytorch cu126, but in 2nd windows is portable python and Pytorch cu129. Download portable version less than v0.3.44 (08.07.2025. Try this one v0.3.40 (05.06.2025) https://github.com/comfyanonymous/ComfyUI/releases/download/v0.3.40/ComfyUI_windows_portable_nvidia.7z

OMG MAN THX SO MUCH I LOVE YOU

**Comment by martinfitzjerl-ctrl** [comment]
this workked

**Comment by martinfitzjerl-ctrl** [comment]
thank you guys so much got my first few images to come out

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/7c492755-687d-4a18-98e4-f85053cf1a18" />

**Comment by martinfitzjerl-ctrl** [comment]
had the CUDA error  then just downloaded the portable version    https://github.com/comfyanonymous/ComfyUI/releases/download/v0.3.40/ComfyUI_windows_portable_nvidia.7z

I have a HP Omen 15 gaming laptop with CUDA

**Comment by MaKeMaK-lee** [comment]
Having a temporary solution is good, but will there be an option to simply select the old pytorch in new versions?
