### ISSUE TITLE
CUDA error NVIDIA GeForce GTX 1070

### ISSUE THREAD

**Issue by e212-cpu** [comfyanonymous/ComfyUI#9705]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

Have downloaded straight from Comfy UI site with a 8GB Vram NVIDIA GeForce GTX 1070. I'm pretty new to this so any help is really appreciated 

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

# ComfyUI Error Report
## Error Details
- **Node ID:** 7
- **Node Type:** CLIPTextEncode
- **Exception Type:** torch.AcceleratorError
- **Exception Message:** CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

## Stack Trace
```
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 74, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 170, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 232, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 689, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 291, in encode
    return self(tokens)
           ^^^^^^^^^^^^

  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 253, in forward
    embeds, attention_mask, num_tokens, embeds_info = self.process_tokens(tokens, device)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 263, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 259, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\.venv\Lib\site-packages\torch\nn\functional.py", line 2546, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** 0.3.56
- **Arguments:** C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py --user-directory C:\user --input-directory C:\input --output-directory C:\output --front-end-root C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app --base-directory C:\ --extra-model-paths-config C:\Users\Roxanne II\AppData\Roaming\ComfyUI\extra_models_config.yaml --log-stdout --listen 127.0.0.1 --port 8000
- **OS:** nt
- **Python Version:** 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0+cu129
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589803520
  - **VRAM Free:** 7582253056
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2025-09-03T18:39:00.634153 - Adding extra search path custom_nodes C:\custom_nodes
2025-09-03T18:39:00.634153 - Adding extra search path download_model_base C:\models
2025-09-03T18:39:00.635154 - Adding extra search path custom_nodes C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes
2025-09-03T18:39:00.635154 - Setting output directory to: C:\output
2025-09-03T18:39:00.635154 - Setting input directory to: C:\input
2025-09-03T18:39:00.635154 - Setting user directory to: C:\user
2025-09-03T18:39:01.510916 - [START] Security scan2025-09-03T18:39:01.510916 - 
2025-09-03T18:39:02.744369 - [DONE] Security scan2025-09-03T18:39:02.744369 - 
2025-09-03T18:39:02.907766 - ## ComfyUI-Manager: installing dependencies done.2025-09-03T18:39:02.907766 - 
2025-09-03T18:39:02.907766 - ** ComfyUI startup time:2025-09-03T18:39:02.907766 -  2025-09-03T18:39:02.907766 - 2025-09-03 18:39:02.9072025-09-03T18:39:02.907766 - 
2025-09-03T18:39:02.907766 - ** Platform:2025-09-03T18:39:02.907766 -  2025-09-03T18:39:02.907766 - Windows2025-09-03T18:39:02.907766 - 
2025-09-03T18:39:02.907766 - ** Python version:2025-09-03T18:39:02.907766 -  2025-09-03T18:39:02.907766 - 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]2025-09-03T18:39:02.908767 - 
2025-09-03T18:39:02.908767 - ** Python executable:2025-09-03T18:39:02.908767 -  2025-09-03T18:39:02.908767 - C:\.venv\Scripts\python.exe2025-09-03T18:39:02.908767 - 
2025-09-03T18:39:02.908767 - ** ComfyUI Path:2025-09-03T18:39:02.908767 -  2025-09-03T18:39:02.908767 - C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-09-03T18:39:02.908767 - 
2025-09-03T18:39:02.908767 - ** ComfyUI Base Folder Path:2025-09-03T18:39:02.908767 -  2025-09-03T18:39:02.908767 - C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI2025-09-03T18:39:02.908767 - 
2025-09-03T18:39:02.908767 - ** User directory:2025-09-03T18:39:02.908767 -  2025-09-03T18:39:02.908767 - C:\user2025-09-03T18:39:02.908767 - 
2025-09-03T18:39:02.908767 - ** ComfyUI-Manager config path:2025-09-03T18:39:02.908767 -  2025-09-03T18:39:02.908767 - C:\user\default\ComfyUI-Manager\config.ini2025-09-03T18:39:02.908767 - 
2025-09-03T18:39:02.908767 - ** Log path:2025-09-03T18:39:02.908767 -  2025-09-03T18:39:02.908767 - C:\user\comfyui.log2025-09-03T18:39:02.908767 - 
2025-09-03T18:39:04.205682 - [ComfyUI-Manager] Skipped fixing the 'comfyui-frontend-package' dependency because the ComfyUI is outdated.
2025-09-03T18:39:04.206684 - 
Prestartup times for custom nodes:
2025-09-03T18:39:04.206684 -    3.6 seconds: C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-09-03T18:39:04.206684 - 
2025-09-03T18:39:06.694376 - Checkpoint files will always be loaded safely.
2025-09-03T18:39:06.736406 - C:\.venv\Lib\site-packages\torch\cuda\__init__.py:283: UserWarning: 
    Found GPU0 NVIDIA GeForce GTX 1070 which is of cuda capability 6.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (7.0) - (12.0)
    
  warnings.warn(
2025-09-03T18:39:06.737407 - C:\.venv\Lib\site-packages\torch\cuda\__init__.py:304: UserWarning: 
    Please install PyTorch with a following CUDA
    configurations:  12.6 following instructions at
    https://pytorch.org/get-started/locally/
    
  warnings.warn(matched_cuda_warn.format(matched_arches))
2025-09-03T18:39:06.738409 - C:\.venv\Lib\site-packages\torch\cuda\__init__.py:326: UserWarning: 
NVIDIA GeForce GTX 1070 with CUDA capability sm_61 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.
If you want to use the NVIDIA GeForce GTX 1070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
2025-09-03T18:39:06.805962 - Total VRAM 8192 MB, total RAM 16310 MB
2025-09-03T18:39:06.805962 - pytorch version: 2.8.0+cu129
2025-09-03T18:39:06.806962 - Set vram state to: NORMAL_VRAM
2025-09-03T18:39:06.807962 - Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
2025-09-03T18:39:08.703569 - Using pytorch attention
2025-09-03T18:39:11.188227 - Python version: 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
2025-09-03T18:39:11.188227 - ComfyUI version: 0.3.56
2025-09-03T18:39:11.220076 - [Prompt Server] web root: C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
2025-09-03T18:39:12.656486 - ### Loading: ComfyUI-Manager (V3.36)
2025-09-03T18:39:12.657486 - [ComfyUI-Manager] network_mode: public
2025-09-03T18:39:12.657486 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
2025-09-03T18:39:12.676334 - 
Import times for custom nodes:
2025-09-03T18:39:12.676334 -    0.0 seconds: C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-09-03T18:39:12.676334 -    0.0 seconds: C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-09-03T18:39:12.676334 - 
2025-09-03T18:39:12.739960 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-09-03T18:39:12.752893 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-09-03T18:39:12.858979 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-09-03T18:39:12.910292 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-09-03T18:39:12.978359 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-09-03T18:39:13.369170 - Failed to initialize database. Please ensure you have installed the latest requirements. If the error persists, please report this as in future the database will be required: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-09-03T18:39:13.400541 - Starting server

2025-09-03T18:39:13.401540 - To see the GUI go to: http://127.0.0.1:8000
2025-09-03T18:39:14.672459 - comfyui-frontend-package not found in requirements.txt
2025-09-03T18:39:15.020558 - comfyui-frontend-package not found in requirements.txt
2025-09-03T18:39:16.151468 - FETCH ComfyRegistry Data: 5/962025-09-03T18:39:16.151468 - 
2025-09-03T18:39:19.675227 - FETCH ComfyRegistry Data: 10/962025-09-03T18:39:19.676228 - 
2025-09-03T18:39:23.246908 - FETCH ComfyRegistry Data: 15/962025-09-03T18:39:23.246908 - 
2025-09-03T18:39:26.715258 - FETCH ComfyRegistry Data: 20/962025-09-03T18:39:26.715258 - 
2025-09-03T18:39:30.383097 - FETCH ComfyRegistry Data: 25/962025-09-03T18:39:30.383097 - 
2025-09-03T18:39:36.861979 - FETCH ComfyRegistry Data: 30/962025-09-03T18:39:36.861979 - 
2025-09-03T18:39:40.348950 - FETCH ComfyRegistry Data: 35/962025-09-03T18:39:40.348950 - 
2025-09-03T18:39:43.937125 - FETCH ComfyRegistry Data: 40/962025-09-03T18:39:43.937125 - 
2025-09-03T18:39:47.948308 - FETCH ComfyRegistry Data: 45/962025-09-03T18:39:47.948308 - 
2025-09-03T18:39:51.480654 - FETCH ComfyRegistry Data: 50/962025-09-03T18:39:51.480654 - 
2025-09-03T18:39:54.974390 - FETCH ComfyRegistry Data: 55/962025-09-03T18:39:54.974390 - 
2025-09-03T18:39:58.610966 - FETCH ComfyRegistry Data: 60/962025-09-03T18:39:58.610966 - 
2025-09-03T18:40:02.244667 - FETCH ComfyRegistry Data: 65/962025-09-03T18:40:02.244667 - 
2025-09-03T18:40:08.552386 - FETCH ComfyRegistry Data: 70/962025-09-03T18:40:08.552386 - 
2025-09-03T18:40:12.107035 - FETCH ComfyRegistry Data: 75/962025-09-03T18:40:12.107035 - 
2025-09-03T18:40:15.527569 - FETCH ComfyRegistry Data: 80/962025-09-03T18:40:15.527569 - 
2025-09-03T18:40:19.100467 - FETCH ComfyRegistry Data: 85/962025-09-03T18:40:19.100467 - 
2025-09-03T18:40:22.627566 - FETCH ComfyRegistry Data: 90/962025-09-03T18:40:22.627566 - 
2025-09-03T18:40:26.268135 - FETCH ComfyRegistry Data: 95/962025-09-03T18:40:26.268135 - 
2025-09-03T18:40:27.495436 - FETCH ComfyRegistry Data [DONE]2025-09-03T18:40:27.495436 - 
2025-09-03T18:40:27.648668 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-09-03T18:40:27.668682 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-09-03T18:40:27.668682 - 2025-09-03T18:40:27.782817 -  [DONE]2025-09-03T18:40:27.782817 - 
2025-09-03T18:40:27.856068 - [ComfyUI-Manager] All startup tasks have been completed.
2025-09-03T18:41:16.236309 - got prompt
2025-09-03T18:41:16.237308 - Failed to validate prompt for output 11:
2025-09-03T18:41:16.237308 - * CheckpointLoaderSimple 4:
2025-09-03T18:41:16.237308 -   - Value not in list: ckpt_name: 'None' not in ['v1-5-pruned-emaonly-fp16.safetensors']
2025-09-03T18:41:16.237308 - Output will be ignored
2025-09-03T18:41:16.237308 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2025-09-03T18:41:26.599944 - got prompt
2025-09-03T18:41:26.860055 - model weight dtype torch.float16, manual cast: None
2025-09-03T18:41:26.871064 - model_type EPS
2025-09-03T18:41:27.803130 - Using pytorch attention in VAE
2025-09-03T18:41:27.804132 - Using pytorch attention in VAE
2025-09-03T18:41:28.007896 - VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
2025-09-03T18:41:28.134087 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-09-03T18:41:28.559243 - loaded diffusion model directly to GPU
2025-09-03T18:41:28.560244 - Requested to load BaseModel
2025-09-03T18:41:28.580261 - loaded completely 9.5367431640625e+25 1639.406135559082 True
2025-09-03T18:41:28.816697 - Requested to load SD1ClipModel
2025-09-03T18:41:28.923886 - loaded completely 4160.386235046387 235.84423828125 True
2025-09-03T18:41:29.028470 - !!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-09-03T18:41:29.035476 - Traceback (most recent call last):
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 74, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 170, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 232, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 689, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 291, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 253, in forward
    embeds, attention_mask, num_tokens, embeds_info = self.process_tokens(tokens, device)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 263, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 259, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\functional.py", line 2546, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-09-03T18:41:29.039477 - Prompt executed in 2.44 seconds
2025-09-03T18:47:13.078353 - got prompt
2025-09-03T18:47:13.085732 - !!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-09-03T18:47:13.087733 - Traceback (most recent call last):
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 74, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 170, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd.py", line 232, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 689, in encode_token_weights
    out = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 45, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 291, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 253, in forward
    embeds, attention_mask, num_tokens, embeds_info = self.process_tokens(tokens, device)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\sd1_clip.py", line 204, in process_tokens
    tokens_embed = self.transformer.get_input_embeddings()(tokens_embed, out_dtype=torch.float32)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 263, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Roxanne II\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\ops.py", line 259, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\torch\nn\functional.py", line 2546, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-09-03T18:47:13.090738 - Prompt executed in 0.01 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"id":"9c18b393-6e21-4ddd-8eb8-d4a7bbb0fac2","revision":0,"last_node_id":11,"last_link_id":10,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[399.60101318359375,413.1181640625],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":3,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":5},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[6]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.56","Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":3,"type":"KSampler","pos":[869.538818359375,172.9217071533203],"size":[315,262],"flags":{},"order":4,"mode":0,"inputs":[{"localized_name":"model","name":"model","type":"MODEL","link":1},{"localized_name":"positive","name":"positive","type":"CONDITIONING","link":4},{"localized_name":"negative","name":"negative","type":"CONDITIONING","link":6},{"localized_name":"latent_image","name":"latent_image","type":"LATENT","link":2},{"localized_name":"seed","name":"seed","type":"INT","widget":{"name":"seed"},"link":null},{"localized_name":"steps","name":"steps","type":"INT","widget":{"name":"steps"},"link":null},{"localized_name":"cfg","name":"cfg","type":"FLOAT","widget":{"name":"cfg"},"link":null},{"localized_name":"sampler_name","name":"sampler_name","type":"COMBO","widget":{"name":"sampler_name"},"link":null},{"localized_name":"scheduler","name":"scheduler","type":"COMBO","widget":{"name":"scheduler"},"link":null},{"localized_name":"denoise","name":"denoise","type":"FLOAT","widget":{"name":"denoise"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[7]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.56","Node name for S&R":"KSampler"},"widgets_values":[453115676427642,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":5,"mode":0,"inputs":[{"localized_name":"samples","name":"samples","type":"LATENT","link":7},{"localized_name":"vae","name":"vae","type":"VAE","link":8}],"outputs":[{"localized_name":"IMAGE","name":"IMAGE","type":"IMAGE","slot_index":0,"links":[10]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.56","Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":2,"mode":0,"inputs":[{"localized_name":"clip","name":"clip","type":"CLIP","link":3},{"localized_name":"text","name":"text","type":"STRING","widget":{"name":"text"},"link":null}],"outputs":[{"localized_name":"CONDITIONING","name":"CONDITIONING","type":"CONDITIONING","slot_index":0,"links":[4]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.56","Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, purple galaxy bottle,"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{"collapsed":false},"order":0,"mode":0,"inputs":[{"localized_name":"ckpt_name","name":"ckpt_name","type":"COMBO","widget":{"name":"ckpt_name"},"link":null}],"outputs":[{"localized_name":"MODEL","name":"MODEL","type":"MODEL","slot_index":0,"links":[1]},{"localized_name":"CLIP","name":"CLIP","type":"CLIP","slot_index":1,"links":[3,5]},{"localized_name":"VAE","name":"VAE","type":"VAE","slot_index":2,"links":[8]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.56","Node name for S&R":"CheckpointLoaderSimple","models":[{"name":"v1-5-pruned-emaonly-fp16.safetensors","url":"https://huggingface.co/Comfy-Org/stable-diffusion-v1-5-archive/resolve/main/v1-5-pruned-emaonly-fp16.safetensors?download=true","directory":"checkpoints"}]},"widgets_values":["v1-5-pruned-emaonly-fp16.safetensors"]},{"id":11,"type":"PreviewImage","pos":[1538.934814453125,214.88087463378906],"size":[140,26],"flags":{},"order":6,"mode":0,"inputs":[{"localized_name":"images","name":"images","type":"IMAGE","link":10}],"outputs":[],"properties":{"cnr_id":"comfy-core","ver":"0.3.56","Node name for S&R":"PreviewImage"}},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":1,"mode":0,"inputs":[{"localized_name":"width","name":"width","type":"INT","widget":{"name":"width"},"link":null},{"localized_name":"height","name":"height","type":"INT","widget":{"name":"height"},"link":null},{"localized_name":"batch_size","name":"batch_size","type":"INT","widget":{"name":"batch_size"},"link":null}],"outputs":[{"localized_name":"LATENT","name":"LATENT","type":"LATENT","slot_index":0,"links":[2]}],"properties":{"cnr_id":"comfy-core","ver":"0.3.56","Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[10,8,0,11,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.925196374622357,"offset":[116.92981753562769,51.00863893158907]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

### Logs

```powershell

```

**Comment by Ph0rk0z** [comment]
You need to downgrade pytorch:

>If you want to use the NVIDIA GeForce GTX 1070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

The version you have doesn't support your GPU.

**Comment by RadaVRada** [comment]
Same with 1050ti. Yesterday everything worked perfectly, then I stupidly updated and now ComfyUI is useless for me. My problem is specifically with the AIO Preprocessor. I’m trying to roll back but everything just keeps breaking.

**Comment by hushtear** [comment]
The same thing happens with the 1080ti.
The problem is pytorch. You need to uninstall and reinstall it.
Here's how to do it:
In the \\ComfyUI folder
open the cmd from the folder and type:
`pip uninstall torch torchvision torchaudio`
then, to be on the safe side
`pip cache purge`
and finally
`pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu118`

### **_BUT NONE OF THIS WORKS._**
I believe it is an internal package in comfyui, specifically this one:
‘F:\imging\supersd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch-2.8.0+cu129.dist-info’

and honestly, I don't know what to do to solve the problem.
I'm pretty sure this was done because Nvidia stopped supporting the 1000 series a few days ago.

Quick solution?
Have you been wanting to upgrade your graphics card for a while?
Now is the right time, just make sure you choose a 2000 series or higher.

**Comment by Ph0rk0z** [comment]
The solution is manage your own python environment and not rely on scripts. I have Torch 2.7.1 and 2.8.0 in different conda and it works fine. Portable is likely re-installing torch 2.8.0 so you have to edit/read what the "easy" scripts are doing.

**Comment by Leiyas** [comment]
The same issue with the 1050 Ti. As I understand it, the problem is that the desktop app automatically switched to Python 3.12 and installs PyTorch 2.8.
For example, from what I've gathered, the GTX 1050 Ti supports a maximum of CUDA 11.8. The last working version of PyTorch is somewhere around 2.1.2 with cu118. Newer versions (2.2+) require CUDA 12.1+ and won't run on the GTX 1050Ti. Also, Python 3.12 doesn't support the necessary older PyTorch versions. PyTorch 2.1.2 supports Python 3.8–3.11. So yes, a downgrade to a lower Python version that worked with the card is needed.
But how to do that when the stupid ComfyUi automatically installs its own Python 3.12 and PyTorch? Idk. I'm not a programmer at all.
In short, the developers really screwed up with this transition. Ideally, the installation process should allow for version selection, but they didn't think of that.I had version ComfyUi 3.30 and I have no idea what Python and PyTorch, everything worked perfectly. After updating to the new version Comfy doesn't work. Thinking of deleting it to hell, but where to find an alternative with nodes?

**Comment by ghost** [comment]
### ⭐ THE SOLUTION IS HERE, GUYS! ⭐

Well, at least it worked for me. I’m using a GTX 1050, and 👀 I’m running the latest version of ComfyUI Portable currently available 👀. Follow these steps exactly as written:

1. Install Python version 3.13 or higher.
2. Open CMD as Administrator inside the **_comfyui_windows_portable folder_**, then run the following command: `.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio`
3. Install PyTorch with this command (still inside the **_comfyui_windows_portable_** folder): `.\python_embeded\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126`
4. Done!

The problem most people are facing, I believe, is installing PyTorch incorrectly. I made this mistake myself—I was installing it in the comfyui_windows_portable folder instead of the python_embeded folder, which is where Python and PyTorch are actually installed by default in ComfyUI.

I also made the mistake of installing it system-wide (just opening CMD and running the install command directly). Eventually, I decided to use my eyes and read the error on the console, and that’s when I finally figured out the real issue.

**Comment by Ph0rk0z** [comment]
Pascal is supported up to cuda 12.8 and I guess torch 2.7.0 or 2.7.1. Whenever they made the cutoff to cuda 12.9 is when they would stop support.

**Comment by imui1986-web** [comment]
Oh no, I, a non-technical person, have also encountered a CUDA problem. I couldn't understand your conversation at all. 😭

**Comment by sljapaaba-huehue** [comment]
i cant find the comfyui_windows_portable folder...

**Comment by hushtear** [comment]
> i cant find the comfyui_windows_portable folder...

The fact that you created your account today, probably just to write this comment, tells me that you seriously need help.

You can download comfyui in three ways:
Desktop application
Windows portable package
Manual installation


Download the Windows portable package because if you download and install nodes that are not compatible with each other, they sometimes cause problems and to solve them, it is often quicker to get another package and start from scratch. And for the reason that if you mess up, it remains isolated there.

For the rest, watch the tutorials and READ EVERYTHING CAREFULLY because the question you wrote is only because you didn't read.

**Comment by hushtear** [comment]
> ### ⭐ THE SOLUTION IS HERE, GUYS! ⭐
> Well, at least it worked for me. I’m using a GTX 1050, and 👀 I’m running the latest version of ComfyUI Portable currently available 👀. Follow these steps exactly as written:
> 
> 1. Install Python version 3.13 or higher.
> 2. Open CMD as Administrator inside the **_comfyui_windows_portable folder_**, then run the following command: `.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio`
> 3. Install PyTorch with this command (still inside the **_comfyui_windows_portable_** folder): `.\python_embeded\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126`
> 4. Done!
> 
> The problem most people are facing, I believe, is installing PyTorch incorrectly. I made this mistake myself—I was installing it in the comfyui_windows_portable folder instead of the python_embeded folder, which is where Python and PyTorch are actually installed by default in ComfyUI.
> 
> I also made the mistake of installing it system-wide (just opening CMD and running the install command directly). Eventually, I decided to use my eyes and read the error on the console, and that’s when I finally figured out the real issue.

Have you tried using the ksampler or groundingDINO node?

**Comment by sljapaaba-huehue** [comment]
Thank you. I downloaded a desktop application,and yes i noticed that few of the nodes had "confrontations",so it tried deleting all of them and reinstalling,that didnt work either. I will try to start from scratch tomorow with the windows portable package as you said,and will keep you informed,also for the benefit of the rest of the guys that come here.

**Comment by ghost** [comment]
> > ### ⭐ THE SOLUTION IS HERE, GUYS! ⭐
> > Well, at least it worked for me. I’m using a GTX 1050, and 👀 I’m running the latest version of ComfyUI Portable currently available 👀. Follow these steps exactly as written:
> > 
> > 1. Install Python version 3.13 or higher.
> > 2. Open CMD as Administrator inside the **_comfyui_windows_portable folder_**, then run the following command: `.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio`
> > 3. Install PyTorch with this command (still inside the **_comfyui_windows_portable_** folder): `.\python_embeded\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126`
> > 4. Done!
> > 
> > The problem most people are facing, I believe, is installing PyTorch incorrectly. I made this mistake myself—I was installing it in the comfyui_windows_portable folder instead of the python_embeded folder, which is where Python and PyTorch are actually installed by default in ComfyUI.
> > I also made the mistake of installing it system-wide (just opening CMD and running the install command directly). Eventually, I decided to use my eyes and read the error on the console, and that’s when I finally figured out the real issue.
> 
> Have you tried using the ksampler or groundingDINO node?

I usually work with the default Ksampler node in ComfyUI, which was not the root cause of the issue. The error consistently occurred at the Clip Text Encode node during generation.

The problem was resolved after uninstalling the old versions of torch, torchvision, and torchaudio, and reinstalling versions compatible with my GPU.

My graphics card is based on the Pascal architecture, which is no longer officially supported in the latest PyTorch releases. Since PyTorch has dropped support for NVIDIA GPUs that rely on Pascal, the only long-term solution is to upgrade to a newer GPU if I want to stay up to date with the framework.

As another user mentioned above, I finally installed the following version: `pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu128`

This is the last official PyTorch release with support for Pascal-based GPUs, which makes it the most stable option for those still running on this architecture.

**Comment by Reiikz** [comment]
> The same thing happens with the 1080ti. The problem is pytorch. You need to uninstall and reinstall it. Here's how to do it: In the \ComfyUI folder open the cmd from the folder and type: `pip uninstall torch torchvision torchaudio` then, to be on the safe side `pip cache purge` and finally `pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu118`
> ### **_BUT NONE OF THIS WORKS._**
> 
> I believe it is an internal package in comfyui, specifically this one: ‘F:\imging\supersd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch-2.8.0+cu129.dist-info’
> 
> and honestly, I don't know what to do to solve the problem. I'm pretty sure this was done because Nvidia stopped supporting the 1000 series a few days ago.
> 
> Quick solution? Have you been wanting to upgrade your graphics card for a while? Now is the right time, just make sure you choose a 2000 series or higher.

Guy with a GTX 1060 3GB on Arch Linux here.
Can confirm this solved the issue.
Guys remember to do this in the python virtual environment you're running comfy from.

**Comment by hushtear** [comment]
> > The same thing happens with the 1080ti. The problem is pytorch. You need to uninstall and reinstall it. Here's how to do it: In the \ComfyUI folder open the cmd from the folder and type: `pip uninstall torch torchvision torchaudio` then, to be on the safe side `pip cache purge` and finally `pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu118`
> > ### **_BUT NONE OF THIS WORKS._**
> > I believe it is an internal package in comfyui, specifically this one: ‘F:\imging\supersd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch-2.8.0+cu129.dist-info’
> > and honestly, I don't know what to do to solve the problem. I'm pretty sure this was done because Nvidia stopped supporting the 1000 series a few days ago.
> > Quick solution? Have you been wanting to upgrade your graphics card for a while? Now is the right time, just make sure you choose a 2000 series or higher.
> 
> Guy with a GTX 1060 3GB on Arch Linux here. Can confirm this solved the issue. Guys remember to do this in the python virtual environment you're running comfy from.

I don't know why, but it doesn't work for me

**Comment by hushtear** [comment]
OK, I found a way to use CUDA 118 compatible graphics cards.

Delete Python.
Download Miniconda.
Create a dedicated virtual environment. (python version 3.10.x)
Download PyTorch and the other two packages into this environment (using the command written in the other comments).
Download the remaining packages.
Write a bat file, something like this:
```
@echo off

REM Activate the ComfyUI environment created with Anaconda *comfyenv is an example of a venv name chosen by you
call “C:\Users\[YourUsername]\miniconda3\Scripts\activate.bat” comfyenv

REM Move to the ComfyUI folder
cd /d D:\imging\supersd\ComfyUI_windows_portable\ComfyUI

REM Start ComfyUI
python main.py

REM Keep the terminal window open after startup to see any errors
pause
```

Start comfyui from the bat file you wrote

Get help from chatgpt or gemini if you don't know exactly what to do... keep in mind that the first solution may not necessarily be the most correct one.
Examples of questions for Gemini:
How can I completely remove Python from my system?
How do you recommend downloading Anaconda?
How do I create a clean venv via cmd commands from Anaconda?
How do I activate a venv to download packages for conda?
How do I download packages that are specified in a file in a specific directory?


It may not be a quick fix, but it works.

**Comment by sljapaaba-huehue** [comment]
Ok,this is a spanich vilage for me. What i tried is,as i said,i downloaded the portable verison,tried runing it,some nodes were missing offcourse,then i didnt know how to add custom nodes,but then i tried installing desktop version so i can download nodes for a workflow with manager,then i copied those nodes into the Portable version custom nodes folder,still doesnt work... is there any way to make this work " https://www.youtube.com/watch?v=S-YzbXPkRB8&t=651s ",thats the video i found out about this. Portable or desktop,just make it work

**Comment by sljapaaba-huehue** [comment]
Right now i uninstaled p2.8 and im downloading .\python_embeded\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126

**Comment by sljapaaba-huehue** [comment]
still,is there a way for comfyui portable to detect and automaticaly install custom nodes?

**Comment by hushtear** [comment]
> still,is there a way for comfyui portable to detect and automaticaly install custom nodes?

Install comyui manager

**Comment by Vic7bd** [comment]
> ### ⭐ THE SOLUTION IS HERE, GUYS! ⭐
> Well, at least it worked for me. I’m using a GTX 1050, and 👀 I’m running the latest version of ComfyUI Portable currently available 👀. Follow these steps exactly as written:
> 
> 1. Install Python version 3.13 or higher.
> 2. Open CMD as Administrator inside the **_comfyui_windows_portable folder_**, then run the following command: `.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio`
> 3. Install PyTorch with this command (still inside the **_comfyui_windows_portable_** folder): `.\python_embeded\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126`
> 4. Done!
> 
> The problem most people are facing, I believe, is installing PyTorch incorrectly. I made this mistake myself—I was installing it in the comfyui_windows_portable folder instead of the python_embeded folder, which is where Python and PyTorch are actually installed by default in ComfyUI.
> 
> I also made the mistake of installing it system-wide (just opening CMD and running the install command directly). Eventually, I decided to use my eyes and read the error on the console, and that’s when I finally figured out the real issue.

Спасибо, всё заработало на 1060 (6ГБ) и 1070 Ti (8ГБ). Но главное потом не запускать "update_comfyui_and_python_dependencies", а использовать только "update_comfyui", иначе всё обновите до нового и перестанет работать.
===
Thanks, everything worked fine on my 1060 (6GB) and 1070 Ti (8GB). But the key is to not run "update_comfyui_and_python_dependencies" afterwards, but only "update_comfyui." Otherwise, you'll update everything to the new version and it won't work.

**Comment by Vic7bd** [comment]
Нашёл для себя ещё одно решение - даже стыдно, что надо было всего лишь скачать другую сборку для 10-й версии. 
И там можно смело обновляться :-) 
---
I found another solution for myself - it’s even a shame that it was only necessary to download another assembly for the 10th version.
And there you can safely update :-)

![Image](https://github.com/user-attachments/assets/8e21e445-d542-49de-84f7-847149dbdf36)

**Comment by martinfitzjerl-ctrl** [comment]
See previous thread too https://github.com/comfyanonymous/ComfyUI/issues/9650#issuecomment-3374594297

and it worked for me just getting the portable for my older nvidia Cuda set up  @Vic7bd @e212-cpu

**Comment by mcaniffb** [comment]
> ### ⭐ THE SOLUTION IS HERE, GUYS! ⭐
> Well, at least it worked for me. I’m using a GTX 1050, and 👀 I’m running the latest version of ComfyUI Portable currently available 👀. Follow these steps exactly as written:
> 
> 1. Install Python version 3.13 or higher.
> 2. Open CMD as Administrator inside the **_comfyui_windows_portable folder_**, then run the following command: `.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio`
> 3. Install PyTorch with this command (still inside the **_comfyui_windows_portable_** folder): `.\python_embeded\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126`
> 4. Done!
> 
> The problem most people are facing, I believe, is installing PyTorch incorrectly. I made this mistake myself—I was installing it in the comfyui_windows_portable folder instead of the python_embeded folder, which is where Python and PyTorch are actually installed by default in ComfyUI.
> 
> I also made the mistake of installing it system-wide (just opening CMD and running the install command directly). Eventually, I decided to use my eyes and read the error on the console, and that’s when I finally figured out the real issue.

Guy with 1080ti on Windows 10
This worked, thank you.

**Comment by MaKeMaK-lee** [comment]
> ### ⭐ THE SOLUTION IS HERE, GUYS! ⭐
> Well, at least it worked for me. I’m using a GTX 1050, and 👀 I’m running the latest version of ComfyUI Portable currently available 👀. Follow these steps exactly as written:
> 
> 1. Install Python version 3.13 or higher.
> 2. Open CMD as Administrator inside the **_comfyui_windows_portable folder_**, then run the following command: `.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio`
> 3. Install PyTorch with this command (still inside the **_comfyui_windows_portable_** folder): `.\python_embeded\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126`
> 4. Done!

Thanks!

### If anyone finds this useful, here's the same solution for the non-portable desktop version "for dummies":
1. Open the **.venv** folder (it's in the ComfyUI root folder or the ComfyUI data root folder, depending on where you installed it) in cmd (preferably as administrator) using any method. For example, for Windows 10:
- Open the desired folder in Explorer
- Hold down the Shift key on your keyboard
- Right-click on an empty space in the folder
- In the context menu, select Open PowerShell window here
- In the window that opens, type cmd and press Enter

2. Check the command `.\Scripts\python.exe -m pip list` - it should give you a list of well over 10 installed packages.

3. Enter the command `.\Scripts\python.exe -m pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu126`.
If the last line of the response is "Successfully installed torch-2.7.0+cu126 torchaudio-2.7.0+cu126 torchvision-0.22.0+cu126" and step 2 was successful, everything should be fine.

This worked for me on the version at the time of writing the comment, perhaps in your case you will need to change something else.

**Comment by 7dir** [comment]
> ## Нашёл для себя ещё одно решение - даже стыдно, что надо было всего лишь скачать другую сборку для 10-й версии.
> И там можно смело обновляться :-)
> I found another solution for myself - it’s even a shame that it was only necessary to download another assembly for the 10th version. And there you can safely update :-)
> 
> ![Image](https://github.com/user-attachments/assets/8e21e445-d542-49de-84f7-847149dbdf36)

Yes, but native cubin support for Pascal sm_61 ends at CUDA version 11.8 (cu118) and versions 12 compile PTX for the old architecture for emulation and then there is a 10-30% speed drop.

Да, но нативная поддержка cubin для Pascal sm_61 заканчивается на версии CUDA 11.8 (cu118) и 12 версии собирают PTX для старой архитектуры для эмуляции и тогда просадка по скорости 10-30%.

**Comment by rajibaditya** [comment]
I am on a 1050 ti and I can vouch that this has worked for me:
1. I updated comfyui to latest stable (portable)
1. uninstalled torch torchvision torch audio
`./python.exe -m pip uninstall torch torchvision torchaudio -y` 
3. Installed the following: 
torch 2.8.0
torchvision 0.23.0
torchaudio 2.8.0
WITH
cuda 12.8
`./python.exe -m pip install torch==2.8.0+cu128 torchvision==0.23.0+cu128 torchaudio==2.8.0+cu128 --extra-index-url https://download.pytorch.org/whl/cu128`

This hasn't broken anything. The reason i wanted to update/upgrade was because the new dynamic vram feature requires torch 2.8.0
