### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by darioDesignCOMFYui** [comfyanonymous/ComfyUI#9887]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Your question

ComfyUI was working fine until today when I updated it via Manager in the UI menu, after the update I restarted it only to be stuck in the following log, I tried uninstalling torch and reinstalling it to no avail, hope someone here knows the answer. Thanks in advance.

### Logs

```powershell
A:\COMFY\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-15 16:45:36.764
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: A:\COMFY\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: A:\COMFY\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: A:\COMFY\ComfyUI_windows_portable\ComfyUI
** User directory: A:\COMFY\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: A:\COMFY\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: A:\COMFY\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: A:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   8.7 seconds: A:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\main.py", line 147, in <module>
    import execution
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 15, in <module>
    import comfy.model_management
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "A:\COMFY\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 1071, in current_device
    _lazy_init()
  File "A:\COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 403, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

A:\COMFY\ComfyUI_windows_portable>pause
```

**Comment by ACJPhil** [comment]
The same problem occurs after updating ComfyUI in Stability Matrix. Also tried several things i. e. uninstalling and reinstalling torch as well as ComfyUI.

**Comment by ACJPhil** [comment]
> The same problem occurs after updating ComfyUI in Stability Matrix. Also tried several things i. e. uninstalling and reinstalling torch as well as ComfyUI.

Here is what helped me: https://github.com/comfyanonymous/ComfyUI/issues/2427

Solved it by going into my ComfyUI\venv\Scripts opened cmd inside that folder and `pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu128`

Hope it helps.

**Comment by darioDesignCOMFYui** [comment]
> > The same problem occurs after updating ComfyUI in Stability Matrix. Also tried several things i. e. uninstalling and reinstalling torch as well as ComfyUI.
> 
> Here is what helped me: [#2427](https://github.com/comfyanonymous/ComfyUI/issues/2427)
> 
> Solved it by going into my ComfyUI\venv\Scripts opened cmd inside that folder and `pip install --force-reinstall torch --index-url https://download.pytorch.org/whl/cu128`
> 
> Hope it helps.

I´ll try it thanks!, but i cant seem to find the /venv folder inside my ComfyUI, i do have a /Scripts folder, ill try it in there

**Comment by darioDesignCOMFYui** [comment]
Managed to fix it by going to ComfuUI/ opened cmd and placing .\python.exe -m pip install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

looks like in the update, the PyTorch version didnt have CUDA support.

**Comment by akatsukijoe** [comment]
I met the prpblem again and followed the check process to check the nvcc version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Aug_20_13:58:20_Pacific_Daylight_Time_2025
**Cuda compilation tools, release 13.0, V13.0.88
Build cuda_13.0.r13.0/**compiler.36424714_0

the python version is
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32

also **comfirmed the torch is working**
>>> import torch
>>> print(torch.cuda.is_available())
True
>>>

I **update the torch** from https://pytorch.org/get-started/locally/#windows-installation
use the command: pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu130
finished the installation and saw the message as following:
Successfully installed torch-2.10.0.dev20251014+cu130 torchvision-0.25.0.dev20251014+cu130

while run_nvidia_gpu.bat, always show the error message as following:
Traceback (most recent call last):
  File "C:\ComfyUI_Portable\ComfyUI\main.py", line 149, in <module>
    import execution
  File "C:\ComfyUI_Portable\ComfyUI\execution.py", line 15, in <module>
    import comfy.model_management
  File "C:\ComfyUI_Portable\ComfyUI\comfy\model_management.py", line 237, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_Portable\ComfyUI\comfy\model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_Portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 1071, in current_device
    _lazy_init()
  File "C:\ComfyUI_Portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 403, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Justify87** [comment]
```
.\ComfyUI_windows_portable\python_embeded\python.exe -m pip uninstall -y torch torchvision torchaudio
.\ComfyUI_windows_portable\python_embeded\python.exe -m pip cache purge
.\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip wheel setuptools
.\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --index-url https://download.pytorch.org/whl/cu129 torch torchvision torchaudio

```
For comfyui portable v0.3.65 with python 3.13.6

**Comment by chenweigh** [comment]
> ```
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip uninstall -y torch torchvision torchaudio
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip cache purge
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip wheel setuptools
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --index-url https://download.pytorch.org/whl/cu129 torch torchvision torchaudio
> ```
> 
> For comfyui portable v0.3.65 with 3.13.6

### Env
```
mac,inter
```
### Problem
```bash
Looking in indexes: https://download.pytorch.org/whl/cu129
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

### Step
```bash
pyenv install 3.13.6
pyenv local 3.13.6
python -m venv venv
source venv/bin/activate
pip install --upgrade pip wheel setuptools
pip install --index-url https://download.pytorch.org/whl/cu129 torch torchvision torchaudio
```

**Comment by akatsukijoe** [comment]
> ```
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip uninstall -y torch torchvision torchaudio
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip cache purge
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip wheel setuptools
> .\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --index-url https://download.pytorch.org/whl/cu129 torch torchvision torchaudio
> it seemed not work...............
> 
> For comfyui portable v0.3.65 with 3.13.6

**Comment by Justify87** [comment]
I used it on a freshly downloaded comfyui. The error appears after using "update with dependencies". This fixed it for me instantly

**Comment by VioletVolatile** [comment]
I can confirm that `update_comfyui_and_python_dependencies.bat` broke my installation on Windows 11 as well.

**Comment by lingleblater-collab** [comment]
Getting similar error for attempting a template workflow for Wan animate:

Sharing logs to see if anyone else can help.

My system is running on intel dGPU (ARC A770)

# ComfyUI Error Report
## Error Details
- **Node ID:** 108
- **Node Type:** DownloadAndLoadSAM2Model
- **Exception Type:** AssertionError
- **Exception Message:** Torch not compiled with CUDA enabled

## Stack Trace
```
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-segment-anything-2\nodes.py", line 55, in loadmodel
    if torch.cuda.get_device_properties(0).major >= 8:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py", line 614, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^

  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py", line 403, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")

```
## System Information
- **ComfyUI Version:** 0.3.76
- **Arguments:** main.py --port 49000 --preview-method auto --output-directory C:\Users\IntelArc\Documents\AI-Playground\media --lowvram --disable-ipex-optimize --bf16-unet --reserve-vram 6.0
- **OS:** nt
- **Python Version:** 3.12.12 (main, Oct 14 2025, 21:24:50) [MSC v.1944 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.9.0+xpu
## Devices

- **Name:** xpu:0 Intel(R) Arc(TM) A770 Graphics
  - **Type:** xpu
  - **VRAM Total:** 16704737280
  - **VRAM Free:** 16704737280
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2025-12-02T21:17:34.386493 - Adding extra search path checkpoints C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-12-02T21:17:34.386493 - Adding extra search path clip C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-12-02T21:17:34.386493 - Adding extra search path vae C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-12-02T21:17:34.386493 - Adding extra search path unet C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\checkpoints
2025-12-02T21:17:34.386493 - Adding extra search path loras C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\service\models\stable_diffusion\lora
2025-12-02T21:17:34.386493 - Setting output directory to: C:\Users\IntelArc\Documents\AI-Playground\media
2025-12-02T21:17:34.857081 - [START] Security scan2025-12-02T21:17:34.857081 - 
2025-12-02T21:17:34.909051 - [ComfyUI-Manager] python -m pip not available. Falling back to uv.
2025-12-02T21:17:34.991850 - [ComfyUI-Manager] Using uv as Python module for pip operations.
2025-12-02T21:17:35.184403 - [DONE] Security scan2025-12-02T21:17:35.184403 - 
2025-12-02T21:17:35.320403 - ## ComfyUI-Manager: installing dependencies done.2025-12-02T21:17:35.320403 - 
2025-12-02T21:17:35.320403 - ** ComfyUI startup time:2025-12-02T21:17:35.320403 -  2025-12-02T21:17:35.320403 - 2025-12-02 21:17:35.3202025-12-02T21:17:35.320403 - 
2025-12-02T21:17:35.320403 - ** Platform:2025-12-02T21:17:35.320403 -  2025-12-02T21:17:35.320403 - Windows2025-12-02T21:17:35.320403 - 
2025-12-02T21:17:35.320403 - ** Python version:2025-12-02T21:17:35.320403 -  2025-12-02T21:17:35.320403 - 3.12.12 (main, Oct 14 2025, 21:24:50) [MSC v.1944 64 bit (AMD64)]2025-12-02T21:17:35.320403 - 
2025-12-02T21:17:35.320403 - ** Python executable:2025-12-02T21:17:35.320403 -  2025-12-02T21:17:35.320403 - C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\.venv\Scripts\python.exe2025-12-02T21:17:35.320403 - 
2025-12-02T21:17:35.320403 - ** ComfyUI Path:2025-12-02T21:17:35.320403 -  2025-12-02T21:17:35.320403 - C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI2025-12-02T21:17:35.320403 - 
2025-12-02T21:17:35.321453 - ** ComfyUI Base Folder Path:2025-12-02T21:17:35.321453 -  2025-12-02T21:17:35.321453 - C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI2025-12-02T21:17:35.321453 - 
2025-12-02T21:17:35.321453 - ** User directory:2025-12-02T21:17:35.321453 -  2025-12-02T21:17:35.321453 - C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\user2025-12-02T21:17:35.321453 - 
2025-12-02T21:17:35.321453 - ** ComfyUI-Manager config path:2025-12-02T21:17:35.321453 -  2025-12-02T21:17:35.321453 - C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\user\__manager\config.ini2025-12-02T21:17:35.321453 - 
2025-12-02T21:17:35.321453 - ** Log path:2025-12-02T21:17:35.321453 -  2025-12-02T21:17:35.321453 - C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\user\comfyui.log2025-12-02T21:17:35.322458 - 
2025-12-02T21:17:35.735912 - 
Prestartup times for custom nodes:
2025-12-02T21:17:35.735912 -    1.3 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-12-02T21:17:35.735912 - 
2025-12-02T21:17:37.591953 - Checkpoint files will always be loaded safely.
2025-12-02T21:17:37.846548 - Total VRAM 15931 MB, total RAM 32384 MB
2025-12-02T21:17:37.846548 - pytorch version: 2.9.0+xpu
2025-12-02T21:17:37.847555 - Set vram state to: LOW_VRAM
2025-12-02T21:17:37.847555 - Device: xpu:0 Intel(R) Arc(TM) A770 Graphics
2025-12-02T21:17:39.345675 - Using pytorch attention
2025-12-02T21:17:41.715286 - Python version: 3.12.12 (main, Oct 14 2025, 21:24:50) [MSC v.1944 64 bit (AMD64)]
2025-12-02T21:17:41.715286 - ComfyUI version: 0.3.76
2025-12-02T21:17:41.727367 - ComfyUI frontend version: 1.32.10
2025-12-02T21:17:41.732392 - [Prompt Server] web root: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\.venv\Lib\site-packages\comfyui_frontend_package\static
2025-12-02T21:17:42.431958 - Total VRAM 15931 MB, total RAM 32384 MB
2025-12-02T21:17:42.432954 - pytorch version: 2.9.0+xpu
2025-12-02T21:17:42.432954 - Set vram state to: LOW_VRAM
2025-12-02T21:17:42.432954 - Device: xpu:0 Intel(R) Arc(TM) A770 Graphics
2025-12-02T21:17:43.098989 - ComfyUI-GGUF: Allowing full torch compile
2025-12-02T21:17:43.184733 - ### Loading: ComfyUI-Manager (V3.38)
2025-12-02T21:17:43.184733 - [ComfyUI-Manager] network_mode: public
2025-12-02T21:17:43.184733 - [ComfyUI-Manager] Since --preview-method is set, ComfyUI-Manager's preview method feature will be ignored.
2025-12-02T21:17:43.477126 - ### ComfyUI Revision: 4297 [30c259ca] *DETACHED | Released on '2025-12-01'
2025-12-02T21:17:43.826708 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-12-02T21:17:43.863627 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-12-02T21:17:43.889284 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-12-02T21:17:43.926621 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-12-02T21:17:43.989095 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-12-02T21:17:44.624895 - [36;20m[C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2025-12-02T21:17:44.624895 - [36;20m[C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2025-12-02T21:17:44.626031 - [36;20m[C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2025-12-02T21:17:44.971067 - 
Import times for custom nodes:
2025-12-02T21:17:44.971067 -    0.0 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\websocket_image_save.py
2025-12-02T21:17:44.971067 -    0.0 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-segment-anything-2
2025-12-02T21:17:44.971067 -    0.0 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-GGUF
2025-12-02T21:17:44.971067 -    0.1 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-kjnodes
2025-12-02T21:17:44.971067 -    0.4 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui_controlnet_aux
2025-12-02T21:17:44.971067 -    0.6 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2025-12-02T21:17:44.971067 -    0.8 seconds: C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-tensorops
2025-12-02T21:17:44.971067 - 
2025-12-02T21:17:45.251892 - Context impl SQLiteImpl.
2025-12-02T21:17:45.251892 - Will assume non-transactional DDL.
2025-12-02T21:17:45.255410 - No target revision found.
2025-12-02T21:17:45.306928 - Starting server

2025-12-02T21:17:45.307925 - To see the GUI go to: http://127.0.0.1:49000
2025-12-02T21:17:46.895785 - FETCH ComfyRegistry Data: 5/1092025-12-02T21:17:46.895785 - 
2025-12-02T21:17:49.974943 - FETCH ComfyRegistry Data: 10/1092025-12-02T21:17:49.974943 - 
2025-12-02T21:17:53.040982 - FETCH ComfyRegistry Data: 15/1092025-12-02T21:17:53.040982 - 
2025-12-02T21:17:56.103502 - FETCH ComfyRegistry Data: 20/1092025-12-02T21:17:56.103502 - 
2025-12-02T21:17:59.739787 - FETCH ComfyRegistry Data: 25/1092025-12-02T21:17:59.739787 - 
2025-12-02T21:18:02.870797 - FETCH ComfyRegistry Data: 30/1092025-12-02T21:18:02.870797 - 
2025-12-02T21:18:06.286823 - FETCH ComfyRegistry Data: 35/1092025-12-02T21:18:06.286823 - 
2025-12-02T21:18:09.375284 - FETCH ComfyRegistry Data: 40/1092025-12-02T21:18:09.375284 - 
2025-12-02T21:18:12.453513 - FETCH ComfyRegistry Data: 45/1092025-12-02T21:18:12.453513 - 
2025-12-02T21:18:15.494842 - FETCH ComfyRegistry Data: 50/1092025-12-02T21:18:15.494842 - 
2025-12-02T21:18:18.527078 - FETCH ComfyRegistry Data: 55/1092025-12-02T21:18:18.528386 - 
2025-12-02T21:18:22.339031 - FETCH ComfyRegistry Data: 60/1092025-12-02T21:18:22.339031 - 
2025-12-02T21:18:25.396733 - FETCH ComfyRegistry Data: 65/1092025-12-02T21:18:25.397739 - 
2025-12-02T21:18:28.512053 - FETCH ComfyRegistry Data: 70/1092025-12-02T21:18:28.513060 - 
2025-12-02T21:18:31.632276 - FETCH ComfyRegistry Data: 75/1092025-12-02T21:18:31.632276 - 
2025-12-02T21:18:34.688203 - FETCH ComfyRegistry Data: 80/1092025-12-02T21:18:34.688203 - 
2025-12-02T21:18:37.802000 - FETCH ComfyRegistry Data: 85/1092025-12-02T21:18:37.802000 - 
2025-12-02T21:18:41.217803 - FETCH ComfyRegistry Data: 90/1092025-12-02T21:18:41.218800 - 
2025-12-02T21:18:44.312091 - FETCH ComfyRegistry Data: 95/1092025-12-02T21:18:44.313110 - 
2025-12-02T21:18:47.360754 - FETCH ComfyRegistry Data: 100/1092025-12-02T21:18:47.360754 - 
2025-12-02T21:18:50.405120 - FETCH ComfyRegistry Data: 105/1092025-12-02T21:18:50.405120 - 
2025-12-02T21:18:53.355313 - FETCH ComfyRegistry Data [DONE]2025-12-02T21:18:53.355313 - 
2025-12-02T21:18:53.536734 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-12-02T21:18:53.561506 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-12-02T21:18:53.561506 - 2025-12-02T21:18:53.636676 -  [DONE]2025-12-02T21:18:53.636676 - 
2025-12-02T21:18:53.720766 - [ComfyUI-Manager] All startup tasks have been completed.
2025-12-02T21:19:00.873920 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-12-02T21:19:00.875031 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-12-02T21:19:01.151616 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-12-02T21:19:01.155182 - [DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
2025-12-02T21:19:04.092001 - got prompt
2025-12-02T21:19:05.301161 - Using pytorch attention in VAE
2025-12-02T21:19:05.303666 - Using pytorch attention in VAE
2025-12-02T21:19:05.489030 - VAE load device: xpu:0, offload device: cpu, dtype: torch.bfloat16
2025-12-02T21:19:08.516786 - [{}]2025-12-02T21:19:08.517781 - 
2025-12-02T21:19:08.535579 - !!! Exception during processing !!! Torch not compiled with CUDA enabled
2025-12-02T21:19:08.537560 - Traceback (most recent call last):
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\custom_nodes\comfyui-segment-anything-2\nodes.py", line 55, in loadmodel
    if torch.cuda.get_device_properties(0).major >= 8:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py", line 614, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^
  File "C:\Users\IntelArc\AppData\Local\Programs\AI Playground\resources\ComfyUI\.venv\Lib\site-packages\torch\cuda\__init__.py", line 403, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

2025-12-02T21:19:08.540078 - Prompt executed in 4.43 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system. (template workflow from WAN2.1 animate)
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by Highstaker** [comment]
Just in case it helps someone. I installed in using Pinokio.co (I managed to do it inside a podman container, but that's a story for another day). And had the same problem

```
Traceback (most recent call last):
  File "/root/pinokio/api/comfy.git/app/main.py", line 179, in <module>
    import execution
  File "/root/pinokio/api/comfy.git/app/execution.py", line 17, in <module>
    import comfy.model_management
  File "/root/pinokio/api/comfy.git/app/comfy/model_management.py", line 246, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/root/pinokio/api/comfy.git/app/comfy/model_management.py", line 196, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/root/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 1094, in current_device
    _lazy_init()
  File "/root/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 417, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

So I went to `{pinokio_data_folder}/api/comfy.git/app/env/bin/`, then `source activate`.

Then uninstalled existing torch
```
pip uninstall torch torchvision torchaudio -y
pip cache purge
```

Using `nvidia-smi`, I determined CUDA version (12.8 in my case). So I installed it with
```
pip install --timeout=600 torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```
where `cu128` is for CUDA version 12.8.

Restarted ComfyUI in Pinokio interface, and now it works.

[This article](https://beaithink.com/solved-how-to-fix-torch-not-compiled-with-cuda-enabled-torch-cuda-is_available-false/) was very helpful.
