### ISSUE TITLE
[Error] occurred when executing KSample on GTX 980 (Nvidia 535 driver & Linux)

### ISSUE THREAD

**Issue by EvianMcKeown** [comfyanonymous/ComfyUI#991]
Hi, I have just moved over from automatic1111 and I am having this issue when i attempt to generate an image on the SDXL 1.0 safetensor.

I followed the instructions from the readme for nvidia users `(pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118 xformers)` and then `pip install -r requirements.txt`

Below is the stack trace.

```
Error occurred when executing KSampler:

CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


  File "/home/evianmckeown/Documents/workspace/ComfyUI/execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evianmckeown/Documents/workspace/ComfyUI/execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evianmckeown/Documents/workspace/ComfyUI/execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evianmckeown/Documents/workspace/ComfyUI/nodes.py", line 1153, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evianmckeown/Documents/workspace/ComfyUI/nodes.py", line 1123, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evianmckeown/Documents/workspace/ComfyUI/comfy/sample.py", line 75, in sample
    comfy.model_management.load_model_gpu(model)
  File "/home/evianmckeown/Documents/workspace/ComfyUI/comfy/model_management.py", line 307, in load_model_gpu
    accelerate.dispatch_model(real_model, device_map=device_map, main_device=torch_dev)
  File "/home/evianmckeown/miniconda3/lib/python3.11/site-packages/accelerate/big_modeling.py", line 371, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/evianmckeown/miniconda3/lib/python3.11/site-packages/accelerate/hooks.py", line 532, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/evianmckeown/miniconda3/lib/python3.11/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evianmckeown/miniconda3/lib/python3.11/site-packages/accelerate/hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/evianmckeown/miniconda3/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 292, in set_module_tensor_to_device
    new_value = old_value.to(device)
                ^^^^^^^^^^^^^^^^^^^^
Queue size: 0
Extra options

```

**Comment by comfyanonymous** [comment]
Use this when launching it: --disable-cuda-malloc

**Comment by EvianMcKeown** [comment]
Thank you, it works.
I thought cuda malloc would be disabled automatically on my card?

**Comment by comfyanonymous** [comment]
The code that disables cuda-malloc on maxwell is windows only at the moment.

**Comment by ElaGnarly** [comment]
> Use this when launching it: --disable-cuda-malloc

how can i use

**Comment by hypntze** [comment]
> Use this when launching it: --disable-cuda-malloc

how can i use

**Comment by Moltes74** [comment]
> > Use this when launching it: --disable-cuda-malloc
> 
> how can i use

Open the "run_nvidia_gpu" file, add --disable-cuda-malloc after  --windows-standalone-build and save

**Comment by drago87** [comment]
would this work on AMD cards or is there enything else i can do?
